### ISSUE TITLE
Suggestion: Expanded settings for quests.

### ISSUE THREAD

**Issue by TheGam1ngWizard** [PikaMug/Quests#1003]
**What does your feature do?**
Additional settings for a quest that a. forces user to accept a quest on region entry, and b. enables/disables 'ask to accept'.

**How would people use it?**

a. forced tutorials, when a player enters the tutorial area, the initial tutorial quest is pushed on them. then the rest can be done with stages. Or dungeons in the world, using entry on dungeon to activate it to control rewards in found dungeons.

and 2. disabling the 'would you like to accept this quest' on a per quest basis would allow users to use WorldGuardExtraFlags to run 'command on entry' and do the same thing as above.

**Comment by PikaMug** [comment]
Region entry is already available in the Quests Editor, see option '6' below:

![editor](https://camo.githubusercontent.com/913520f47b407e7300c7d98d84331f221c79d845/68747470733a2f2f692e696d6775722e636f6d2f4865473977394b2e706e67)

Toggling 'ask to accept' is known as `ask-confirmation` in config.yml:
https://github.com/PikaMug/Quests/wiki/2-%E2%80%90-Configuration#configyml

**Comment by TheGam1ngWizard** [comment]
'Set Region' only changes the fact that they 'have to be in the region to accept the quest' it DOESN'T make them take the quest. 

And toggling 'ask to accept' is only global, not per quest as I requested.

**Comment by PikaMug** [comment]
Looks like I misinterpreted your suggestion - thanks for the clarification.

As you’ve stated, forcing players to take a quest when entering a region should be done with the _/questadmin give [player] [quest]_ command using a plugin like WorldGuardExtraFlags. 

Making quest confirmation work on a per-quest basis has been suggested before, but declined with the reasoning that players should have a consistent experience when taking quests.

I’d be glad to reopen this ticket if you’d care to explain why having confirmation per-quest would be preferred over disabling it for all quests.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheGam1ngWizard** [comment]
I think my issue with the confirmation per-quest actually comes from a (likely non-intended) use of quests. 

I want to setup 'danger zones' around the world (IE: dungeons) that on entry activate a quest (IE: Starts spawning of enemies, manages loot, rewards, ect) without the immersion breaking 'yes/no' confirmation (since nothing is 'offering' the quest, it's just there.) But I also want to have quest givers around the world (in cities, towns, and on the roads) that can give quests using the normal quest giving acceptance.

Having the option to have quest confirmation per-quests lets me do both.

I can have zone based forced quests, and npc based optional quests.

(also things like, forced tutorials on server entry, or entry into a new city. 

They get put in the tutorial area on first join, and have to go through the quest steps to exit; simple psychology, if they have the option to skip its more likely they are going to end up breaking the rules, and causing trouble.)

**Comment by PikaMug** [comment]
That sounds very interesting, but I'm a little confused. You've made it clear that ask-confirmation should be disabled for the tutorial and danger zones, but what is the advantage of then enabling confirmation for city/town/road quests? Were you planning on disabling quitting of those quests?

**Comment by TheGam1ngWizard** [comment]
Advantages of having the ability to turn it on would be quests like the stereotypical fetch quests. Or npc 'I need a iron sword, can you make me one?' 'yes/no'.

An example of a city quest that could be done without ask-confirmation is getting to a new city, and needing to kill X amount of mobs outside of it before your let in. (you get close, guards stop you, auto give quest. then you only get a Luckperms track increase to get inside town if you do the quest.)

and i'm fully okay with players quitting the quests after their given. (ie: in above they decide its not worth it, so just leave and quit the quest.) It's them giving up opportunities, so i'm not worried about that in my case. 

--

although now that I think about it, if I could disable quitting on a per-quest basis. you could do some fun stuff with that. Like 'questing' someone with a disease that harms them over time (a delay until stage increase) or having a potion that effects someone with 'lure' (ie: gives them a quest that auto spawns mobs until they complete the time of potion, or a objective of some sort.)

You could even use that per-quest disable quitting to put 'bounties' on players. Where the player loses the quest on death by player, and drops a reward (making them the target).

Hmmm, Is that already in quests? That sounds useful.

**Comment by PikaMug** [comment]
I'm sticking by my original stance that requesting confirmation on some quests, rather than all or none, is not conducive to a consistent user experience. Also, the ability to disable per-quest quitting was added under Edit Options -> General some time ago, which partially satisfies this ticket. If avoiding confirmation is still desired, running _/questadmin give_ as mentioned previously should override the config option in question.
