### ISSUE TITLE
Console error: Unable to use "....." as an item name

### ISSUE THREAD

**Issue by Debloat** [PikaMug/Quests#1004]
Build 47

I don't know how to replicate this but I'm guessing it's about the server machine locale. On plugin startup, plugin logs this error:

http://www.pastebin.com/SJCNiaDW

As far as I can see, the plugin looks for "STONE_PİCKAXE" instead of "STONE_PICKAXE". The capital "İ" is present in Turkish language which is the server locale.

**Comment by PikaMug** [comment]
I'm guessing this was manually entered, as the [Bukkit Materials enum](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html) (used when loading item from hand) is in English regardless of the server's locale. 

The solution is to either edit your quest in-game or in the quests.yml file and replace the unusable character.

**Comment by Debloat** [comment]
I did not change anything tho. This error came out of box, with default config. I just re-wrote materials with capitals and that fixed it.

**Comment by PikaMug** [comment]
Haven't been able to replicate this, but since OP was able to fix I'm going to close this issue.
