### ISSUE TITLE
Suggestion for Quests 

### ISSUE THREAD

**Issue by ZombieGaminqLP** [PikaMug/Quests#1005]
**What does your feature do?**
Just save the Regions with his World   Worldguard save his Region in World Folders
Example:
Farmworld1
- __global__
- spawn
Farmworld2
- __global__
- spawn
Farmworld3
- __global__
- spawn

Ea farmworld have a global region named __global__ so ur plugin see only 3 times __global__ but 
from which world he should take the global region ?

**How would people use it?**
Allow poeple making quests for only 1 World

**Comment by PikaMug** [comment]
This is essentially an extension of #839 

Solution for now is it simply change the region names to something unique, like global1, spawn2, etc.
