### ISSUE TITLE
Planner Issue - Quest Activation too far in future

### ISSUE THREAD

**Issue by LarcekGiglamesh** [PikaMug/Quests#1006]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-3.8.1.jar

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Trying to start a Quest that was set to start on a specific day (weekday) starting 00:00:00 and ending 23:55:00 with 6 days repeat cycle and 1 day cooldown so players can only grab it on that day each week but the ingame message prints weeks on some. 

The calculated time seems right, starting at 00:00 o'clock at least. 
[Screenshot](https://imgur.com/HlheMv6)

Server Log: [https://paste.dimdev.org/cowoxodofa.md](https://paste.dimdev.org/cowoxodofa.md)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Quest Config: [https://paste.dimdev.org/idapofibuk.sql](https://paste.dimdev.org/idapofibuk.sql)

**Comment by PikaMug** [comment]
Thanks for the report. Had no issue taking and completing your quest, but I'll go ahead and wait the 1 day to see if I can replicate the issue.

![firewood](https://user-images.githubusercontent.com/2267126/71774154-a2d81b80-2f37-11ea-8b5a-2531da7c1e24.png)

**Comment by LarcekGiglamesh** [comment]
thanks. never figured out the issue of the server being 1 month off exactly, but will give it a try in future once more.

**Comment by PikaMug** [comment]
Sorry for the delay. Just gave it another shot and the repeat cycle appears to be working as expected.

![firewood2](https://user-images.githubusercontent.com/2267126/71836674-81d01180-3082-11ea-9e26-579f1ba2ce02.png)

You mentioned your server has a timing issue? I'm not educated on that sort of issue, but perhaps the internal clock is running slow? Regardless, you'll certainly want to fix that as both the repeat cycle and cooldowns are based on system time.
