### ISSUE TITLE
Suggestion to make more Quest Options

### ISSUE THREAD

**Issue by ZombieGaminqLP** [PikaMug/Quests#1007]
**What does your feature do?**
Adding a Option so we can make Quests with biomes 

Find a Mesa Biome
Ask Player Location Biome

**How would people use it?**
Players need to search a Mesa biome and when the guys on biome Mesa the quest is finish

**Comment by PikaMug** [comment]
Stay-within-biome condition has been added to development builds. See https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Condition-Editor
