### ISSUE TITLE
Quest Giver NPC

### ISSUE THREAD

**Issue by TheGam1ngWizard** [PikaMug/Quests#1008]
Having the quest giver be the same NPC you want the player to talk too makes the NPC say "No more quests available" every time you right click them while still progressing the conversation.

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions (missing Quests version). Please try the latest development build and, if that doesn't resolve this issue, reply below with the requested information:

https://ci.codemc.io/job/PikaMug/job/Quests/
