### ISSUE TITLE
Kill specified NPC doesn't count.

### ISSUE THREAD

**Issue by apatuka** [PikaMug/Quests#1009]
**What is your Quests version / build number (do _not_ say "latest")?**
Using Quest version 3.8.2-b47 downloaded from CodeMc.

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
There isn't any console error.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Its the Stage 3, the only Kill NPC
https://pastebin.com/rRYD3CrF

**Comment by PikaMug** [comment]
Thanks for the report. To be clear, you're saying that killing the target NPC for Stage 3 doesn't advance the quest to Stage 4?

**Comment by apatuka** [comment]
PikaMug,

Correct, the Stage 3 have the task to kill a Specific NPC, i killed the target NPC, but don't gave me credit 1/1, i checked the NPC ID with /npc sel (i even use the Right Click to get NPC ID from Quest Editor) and the NPC ID matches with the objective NPC ID.

**Comment by PikaMug** [comment]
Pretty sure I've fixed this via e03a7ea1712676759adb64f72fa9dc5af8346487 so please give the following build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/48/

Note that this build is somewhat experimental and may cause issues with QuestsGUI if installed. If you continue to experience a problem, comment below to reopen the issue.
