### ISSUE TITLE
CitizensBooks Integration (Initial Action // Stage 1 Starting Action)

### ISSUE THREAD

**Issue by zaccieslak** [PikaMug/Quests#1010]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

I'm using CitizensBooks with Quest Actions to pull out books for players when they start/finish a Quest stage. I properly set the book with "/npcbook filter set "filter name"", then in the actions.yml of Quests, I input: "open-book: "filter name"". This works perfectly fine and opens books when I want them to, except for the first stage of any quest. Since I have some basic tutorial quests that only require 1 stage, having the book open would be amazing. For any quest that has more than 1 step, the books open. I've tried the Initial Action, and the Starting Action for Stage 1 for all my quests, and I'm guessing that something in Quests is either making the book close automatically, or that it's just not allowing the book to be opened. 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

N/A - The books are just not opening or just closing automatically.

**Comment by PikaMug** [comment]
Thanks for your report. I'm assuming other Actions function correctly in its place, meaning this would most likely be an issue with CitizensBooks. It seems you've already taken the correct first step by requesting help from the developer at https://github.com/nicuch/CitizensBooks/issues/34

If the developer finds reason to believe otherwise I'll look into further, but there doesn't appear to be evidence of that at this time. One possibility to consider is that Minecraft may not allow you to open a book while receiving a title (the message that shows on-screen when you start a quest). Try setting `show-titles: false` in config.yml just to see if that might resolve the issue.

**Comment by zaccieslak** [comment]
Ahh, Nicuch saw that the gui-display seems to be conflicting with the action of opening a book. Since the gui-display opens an inventory, it doesn't allow a book to be opened! I've tried setting the delay on the first stage, but it seems that actions are performed instantly, which means that there's no workaround to having both the gui-display and the book opening.

I did try the show-titles the first time it didnt' work, hoping that was it haha! Thanks homie!

**Comment by PikaMug** [comment]
I see, in that case I'll have to add a cancellable event for the gui-display so that the developer can do that. Until then, consider removing the GUI items for the associated quests to ensure the book opens.

**Comment by nicuch** [comment]
I might try to force-close any inventory that a player have. I added the command /npcbook forceopen to force a player to open a book, for any plugin that does not have support for my plugin. But the thing is: force-closing inventories might result in further more bugs; for example: if a player might have a item on cursor while closing the inventory, results in item being lost, or dropped.

**Comment by zaccieslak** [comment]
Right, it's an amazing thing to have a book open instead of text spamming the chat area, but for the simple one-stage quests or for the first stage of a quest to open a book would be awesome! Is there a way to add a delay on actions? That would help in many ways - I have a quest that spawns a certain mythic mob, but am wanting to have the mobs spawn 10 seconds after they reach a location so that they can read the book opened by the npcbook plugin, but they instantly spawn, even with a delay set. The delay on actions would also allow the npcbook plugin to open the book on the first stage of any quest
