### ISSUE TITLE
Planner Issue - No GUI after first completion

### ISSUE THREAD

**Issue by Blautee** [PikaMug/Quests#1011]
**Quests version / build number:**
3.8.1-b42

**Problem and how to replicate it:**
After updating from 3.7 to 3.8, a planned quest, that usually uses GUI to accept, no longer will use this GUI after first completion. When trying again after the planned time passed, accepting the quest only works via chat (which is problematic when using own chat plugins).
Console gives no errors.

**example quest from quests.yml:**
[Pastebin](https://pastebin.com/raw/xGjsJF2y)

Thanks in advance :3

**Comment by PikaMug** [comment]
I'm fairly certain this has already been fixed in the latest development builds, available at:
https://ci.codemc.io/job/PikaMug/job/Quests/

Note that these builds contains some API changes which may interfere with QuestsGUI until the next official release.
