### ISSUE TITLE
GPS commands don't work in Events #2

### ISSUE THREAD

**Issue by DustKing5** [PikaMug/Quests#1012]
I created command-event what start gps to certain point with command (compass start point player) when the player finish the quest. The gps started, the plugin write the gps start message, but no arrow and the gps is not active (see the picture).

If I run the same command as player, this work perfectly.

Without the GPS-quest plugin (only with the GPS) this work fine.

![image](https://user-images.githubusercontent.com/32779449/69570362-fa41ae00-0fbf-11ea-8ba9-1dd1beecb04c.png)

All the best! This is cool plugin!

**Comment by PikaMug** [comment]
This is about what I would expect. The GPS-Quests bridge plugin is only designed to carry a player through an entire quest - not a mere portion of it. Thus, activating it partway via command will cause it to either not function or break. As you say, the solution is to simply not use GPS-Quests and continue with how you're doing it via command.
