### ISSUE TITLE
Quest giving console error / not working

### ISSUE THREAD

**Issue by Tobi-Jakka** [PikaMug/Quests#1014]
**What is your Quests version / build number (do not say "latest")?**
3.8.2 (Also tested with 3.8.1, which is the latest on spigot, though same error)
**Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?**
Yes this is the console error:
https://pastebin.com/GPRjvHUy
**If applicable, can you provide an example quest from quests.yml using Pastebin.com?**
No

**Comment by PikaMug** [comment]
You either have two copies of the Quests plugin in your folder, or are trying to use it with another plugin that uses the "Quests" name. Remove the extra jar to resolve the issue.
