### ISSUE TITLE
Suggestion for a Permission

### ISSUE THREAD

**Issue by ZombieGaminqLP** [PikaMug/Quests#1015]
**What does your feature do?**
Add a Permission that allow guys to join only so many quests that the permission allow example

quests.quest.2

User can only start 2 Quests

quests.quest.1

Can only start 1 Quest

**Comment by PikaMug** [comment]
A nice idea, but Quests already offers a hard limit for all players as `max-quests` in the config.yml file. Using the requirements system to prevent certain quests from being taken before others is the standard approach for slowing progress, and limiting the number of quests a certain group can take could potentially conflict with that system if they do not "rank up" appropriately.
