### ISSUE TITLE
ChatControl Support

### ISSUE THREAD

**Issue by imhandmade** [PikaMug/Quests#1022]
```
**What is your Quests version / build number (do _not_ say "latest")?** 

Version: 3-8-2-b48
```

```
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** 

Use the chatcontrol plugin to handle the messaging, and when you go to use the password phrases, it doesn't count since chatcontrol is the chat handling plugin.
```

```
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

http://paste.xiav.icu/dimurohiyu.sql
```

**Comment by PikaMug** [comment]
Thanks for your report. I used your quest and was still able to complete it with ChatControl 5.8.7 installed. Perhaps there is something specific to your setup that is causing issue?

![chat](https://user-images.githubusercontent.com/2267126/71770910-04c95e80-2f01-11ea-98f8-ccc4225c7015.png)

**Comment by imhandmade** [comment]
I was using version 8.5.0 ChatControlPro

**Comment by PikaMug** [comment]
I did use the free version. Unfortunately, Quests does not implement support for Premium resources, so your best bet is to request help on the SpigotMC hiring forum (not affiliated). A developer can either submit a pull request if the fix would not require depending on the resource, or create a separate fork specifically for your situation.

https://www.spigotmc.org/forums/hiring-developers.55/

**Comment by imhandmade** [comment]
You support GPS, even though that is a premium plugin?

**Comment by PikaMug** [comment]
[GPS-Quests](https://www.spigotmc.org/resources/gps-quests.67835/) is an entirely different project with a standalone jar. Quests does not have any built-in support for GPS.

**Comment by imhandmade** [comment]
Ahh, well this is unfortunate, gotta look for another quests plugin then, ;c
