### ISSUE TITLE
AUTOSELL Support

### ISSUE THREAD

**Issue by SladeHazard** [PikaMug/Quests#1023]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.1-b42
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
So basically i have a quest named Iron Miner the goal is to miner 150 iron blocks my server has autosell which give has fortune and autopickup on pickaxe when i disable the autosell plugin from clip the quest works fine but when it's enabled and players break the iron blocks /quest it still says 0/150
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/trkaweCc

**Comment by SladeHazard** [comment]
bump

**Comment by PikaMug** [comment]
Thanks for your report. AutoSell is a premium plugin without publicly available source code, so finding a solution would be difficult for me, if not impossible.

As far as I can tell, the AutoSell plugin doesn't explicitly cancel the BlockBreakEvent. However, it appears to catch the event on all priority levels, which I suspect may be overriding Quests turn to catch it at priority HIGHEST. I recommend reaching out to their Discord for support, as all signs point to an issue on their end. Feel free to provide them a link to this ticket.

Here is a link to their Discord. I believe they have a channel specifically for AutoSell that you can access once you follow their steps for proving you've purchased the resource:
https://discordapp.com/invite/0utOOIYX82aImw7h

Applicable code:
https://github.com/PikaMug/Quests/blob/776e28cb0a43fc13e4cb05ec8098a9308bbdc643/main/src/main/java/me/blackvein/quests/listeners/PlayerListener.java#L521
