### ISSUE TITLE
Delivery Items changes to "Air"

### ISSUE THREAD

**Issue by AmmoniakNH3** [PikaMug/Quests#1024]
**What is your Quests version / build number (do not say "latest")?**
3.8.2
**Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?**
When I set a specific Item in a Deliver-Quest, the Item changes automatically to Air.
**If applicable, can you provide an example quest from quests.yml using Pastebin.com?**
https://pastebin.com/dY8nyFcR

**Comment by PikaMug** [comment]
Thanks for the report, but I need more information. In your example quest, are you referring to the Arrow added to Stage 1? At what time does it change to Air (when editing, after taking the quest, et al.)?

**Comment by AmmoniakNH3** [comment]
When i reload the quest config with the /questadmin reload command

**Comment by AmmoniakNH3** [comment]
MY false. When i accept the Quest at the first time there is a event at the Server Console

>.... [15:33:44 INFO]: Showing new title for Tjarderik
>.... [15:33:44 INFO]: Showing new subtitle for Tjarderik
>.... [15:33:44 WARN]: java.lang.NullPointerException
>.... [15:33:44 WARN]: at me.blackvein.quests.Quests.showObjectives(Quests.java:1021)
>.... [15:33:44 WARN]: at me.blackvein.quests.Quester.takeQuest(Quester.java:519)
>.... [15:33:44 WARN]: at me.blackvein.quests.listeners.PlayerListener.onInventoryClickEvent(PlayerListener.java:160)
>.... [15:33:44 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor728.execute(Unknown Source)
>.... [15:33:44 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [15:33:44 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [15:33:44 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [15:33:44 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2314)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006)
>.... [15:33:44 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929)
>.... [15:33:44 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by PikaMug** [comment]
It seems this is probably a result of recent change 7d90b19171981f29b6f8e30a6c84b92d1463ffb0

Does this issue occur for you using Quests 3.8.1?

**Comment by en0ped** [comment]
Can confirm exact behavior that started after the 3.8.2 update

**Comment by PikaMug** [comment]
The following build should resolve this issue. You may need to quit the quest and retake it for changes to take effect:
https://ci.codemc.io/job/PikaMug/job/Quests/50/
