### ISSUE TITLE
Console Spam "Could not pass Player Move Event"

### ISSUE THREAD

**Issue by mercurialmusic** [PikaMug/Quests#1025]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.8.2 using CraftBukkit version git-Spigot-492a779-731e819 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
**Loads** of console spam: https://gist.github.com/mercurialmusic/6c4a8401ce61acfcd37da9818df62e47

The spam seems to happen when the player has an old active quest with a destination objective.

**Comment by PikaMug** [comment]
Thanks for the report. It seems the most crucial part of the error is missing, specifically the lines following "Caused by: java.lang.NullPointerException". Please provide that information before I can proceed with this ticket.

**Comment by mercurialmusic** [comment]
Unfortunately that was the entire error, repeated ad nauseam. I updated the original paste above to include a larger chunk of the logs. Perhaps the debug build you provided in #1026 will also catch this one.

**Comment by PikaMug** [comment]
I see, that's very surprising as without that information, there's no way for me to tell where the problem is originating from. Do you have any suspicions as to what causes it? If you're the only player online, does it still happen if your player stands still, or only if the player moves?

You're welcome to try that build, but sadly I doubt it will make much difference.

**Comment by mercurialmusic** [comment]
Yes, it was happening when a player was online and playing who had accepted a destination-based quest in ~early December but had not yet completed it. So, many restarts, a MC version, and a plugin version later it started spitting out that spam. Forcing her to quit the quest solved the problem. I haven't seen it repeated since, but unsure if it was fixed or perhaps just hasn't come up again. Have most recently been using 3.8.3-b52 without issue.

**Comment by PikaMug** [comment]
In that case, I'm going to go ahead and close the ticket since you've been unable to replicate it on the most recent version of Quests. If it happens again, feel free to open a new issue.
