### ISSUE TITLE
Illegal Argument Exception spam on Player Join

### ISSUE THREAD

**Issue by mercurialmusic** [PikaMug/Quests#1026]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.8.2 using CraftBukkit version git-Spigot-492a779-731e819 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Console spam **every time** a player joins the server: https://gist.github.com/mercurialmusic/d911b9426e42866643e62441a453d03e

**Comment by PikaMug** [comment]
Thanks for the report. Please give the following build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/51/

It won't resolve the issue, but should give a more detailed error that should help us determine which item/quest is being problematic. Let me know once you have that information.

**Comment by mercurialmusic** [comment]
Thanks, I will try it.

**Comment by mercurialmusic** [comment]
This might have been solved in 3.8.3-b52 - I haven't seen it happen again.

**Comment by PikaMug** [comment]
Alright, I'll go ahead and close the ticket. Should it happen again, comment here with the new stacktrace.
