### ISSUE TITLE
Error Spam: Enchantment level is either too low or too high...

### ISSUE THREAD

**Issue by PacificMR** [PikaMug/Quests#1028]
Quest version: 3.8.2
Paper version: 1.15.1 - 33

The console is spammed by the error listed in the pastebin below very frequently. This did not happen when using quest version 3.8.1 on MC version 1.14. No configuration changes have been made. The only difference is updated to 3.8.2 and updated MC to 1.15.1

Error: https://pastebin.com/SeqCYNyE

Hope this can be solved.
Thanks a lot.

**Comment by PacificMR** [comment]
Another issue since updating. This is being spammed as well.

`java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48
java.lang.NullPointerException: null
>.... [11:38:21 ERROR]: Could not pass event BlockBreakEvent to Quests v3.8.2-b48`

**Comment by PikaMug** [comment]
In the future, please split up issues into separate tickets.

For the first issue, it seems like a variant of #1026 so visit that ticket and try the dev build I linked to there. It should give you an indication of which quest is causing the error.

The second issue appears to be a variant of #1028 which is still in progress. If you can give any insight into what players are doing in-game to cause this error, it'd be appreciated.

**Comment by PacificMR** [comment]
For the second issue it seems to happen whenever players break blocks.
