### ISSUE TITLE
kill location displayed as <location> in chat

### ISSUE THREAD

**Issue by ScuroK** [PikaMug/Quests#1030]
**Quests 3.8.2**

**If i have to kill mobs at a certain location it tells me to reach "<location>" instead of the location name i've set**

**https://pastebin.com/zPvjT9QP **

**Comment by PikaMug** [comment]
When you say "in chat" what are you doing to trigger the message? Taking the quest? Running a command?

Also, please use a website like Pastebin to share your quest. Usually I'd close the ticket for failing to do that, but I know you're a longtime user, so please just edit your post.

**Comment by ScuroK** [comment]
Yes when taking the quest

**Comment by PikaMug** [comment]
Thanks for the clarification. Fix will be available in the next SpigotMC release.
