### ISSUE TITLE
Duplicate bug

### ISSUE THREAD

**Issue by Kamiell** [PikaMug/Quests#1031]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.8.2
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Duplication bug:

Steps to replicate;
1 Create any quests and /questsadmin reload
2 Edit that quest in game, set a NPC for "Set NPC start" save and /questsadmin reload
3 The quest is now duplicated

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
I wasn't able to replicate this. Please respond to the following:

1. Does the issue still occur on Quests 3.8.3?
2. Are you using QuestsGUI?
3. Does the quest you're editing already have a Start NPC set? Or are you adding one for the first time when editing?
4. When you say "duplicated" do you mean it appears in _/quest list_ more than once? Or is there a duplicate quest in the quests.yml file?

**Comment by Kamiell** [comment]
Hmm, it seems to be interfering with another plugin, which one I didn't found out yet. Thanks for helping anyways!
