### ISSUE TITLE
Error When Selecting "Denizen Script" option in Actions

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1033]
Quests Version: v3.8.3-b53
I'm unable to assign scripts as it just errors before entering the name.
https://pastebin.com/h4mBjfvA

**Comment by PikaMug** [comment]
What version of Denizen are you running? Looks like they may have changed some internal class names. You may wish to try downgrading to an older version of Denizen for the time being.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Maitlans** [comment]
I'm using Denizen-1.1.2-b1700 the latest one, I downgraded to the version they released in October I was able to get and assign the script but when it executes it now spews this error.
https://pastebin.com/RJ0ShfUS
If I have to keep downgrading do you have a recommended version that you know 100% works?

**Comment by PikaMug** [comment]
I've been using Denizen-1.0.6-b1676-REL for testing, but the October release you downgraded to should suffice, and I wasn't able to replicate that second error. Could you provide the quest you're using to execute your script? It'll be located in the _quests.yml_ file.

**Comment by Maitlans** [comment]
My quests.yml along with Actions
https://pastebin.com/AmMB3f0e
After retrying today I'm not getting that same error I was getting yesterday I'm getting this new one
https://pastebin.com/xnaZvQ1s

**Comment by PikaMug** [comment]
Thanks for that. I've fixed the newest error with a8fd1d02e6e6cb0eb5e4b9a5deee6fb9aefa547e which you can download here:
https://ci.codemc.io/job/PikaMug/job/Quests/55/

As for using newer Denizen builds, I'll let you know once I get that working.

**Comment by Maitlans** [comment]
Thank you @PikaMug, everything now works as intended, thank you for such an amazing plugin, keep up the amazing work!
