### ISSUE TITLE
Quest Planner improvement for repeatable content.

### ISSUE THREAD

**Issue by Edson-G** [PikaMug/Quests#1034]
**What does your feature do?**
It would be an extension of the already existing Quest Planner. What it does is simply to, when a previously unavailable quest becomes available, every player that has completed it before can do it again. So, for example, if i set a quest that starts at 00:00 and ends at 23:59 of the same day with a  repeat cycle of one day, then everyday at midnight every player is able to retake the quest. Of course, if the player didn't finish the quest already, nothing changes.

**How would people use it?**
It would be possible to create daily quests that reset for everyone at the same time, which makes a lot of sense for some applications.

**Comment by PikaMug** [comment]
Already possible, you're just using the wrong settings. If you want your quest to be available for one hour after midnight, set your start to 00:00 and your end to 01:00. Then create a repeat cycle of 23 hours and a player cooldown of at least 1 hour. This way, your quest becomes available at midnight each day, and players are only able to complete it once a night.
