### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by DeniedINC** [PikaMug/Quests#1035]
Maybe I'm doing it wrong but trying to use this placeholder %quests_player_has_completedquest_<quest>%. I've tried 

The quest name: %quests_player_has_completedquest_Journey_Begins%
The quest name in the file: %quests_player_has_completedquest_custom1%

They all return false. I used it in a hologram so maybe that's why? Wanted to know the correct usage of the placeholder though

**Comment by PikaMug** [comment]
Pretty sure it'd be %quests_player_has_completed_quest_Journey Begins% but if that doesn't work, please open an issue at https://github.com/PikaMug/PlaceholderExpansion-Quests/issues
