### ISSUE TITLE
Color code section for the quest texts

### ISSUE THREAD

**Issue by xHashii** [PikaMug/Quests#1042]
Hello!

So, my suggestion is to add a section/page to the wiki where it says about the color codes you can use in the quests.yml

**What does your feature do?**
Many people try to use color codes - example is "&6 or &7".
So it would be really clarifying for people when they see it and actually understand that the color syntax is used as `<red>, <green>, <blue>` and etc.

**Comment by PikaMug** [comment]
Thanks for your suggestion. Such a page already exists at
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#formatting

Simply use `< >` instead of `% %`
