### ISSUE TITLE
NPC getting two stacks of items during NPC delivery task

### ISSUE THREAD

**Issue by ZamponiMarco** [PikaMug/Quests#1043]
**What is your Quests version / build number (do _not_ say "latest")?**
Quest_3.8.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Set up a mission in which a stage requires to deliver to an NPC multiple stacks of one material. 
If you right click him holding multiple stacks of such item in your inventory, but you are not on the first hotbar slot with the item, two stacks will be taken from the player, the one in the first hotbar slot available and the one held in hand.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/0MLAbxhW

**Comment by PikaMug** [comment]
This behavior is intentional under the reasoning that most players do not wish to cycle through their inventory to find the delivery item(s).

**Comment by ZamponiMarco** [comment]
I understand this, but it still consumes two stacks instead of one and it only counts one stack for the progress of the quest

**Comment by PikaMug** [comment]
@ZamponiMarco I see. Can you provide a quest to test that with? You've only provided config settings.

**Comment by ZamponiMarco** [comment]
Sry, my bad, here is an example i just created that produces this bug
https://pastebin.com/4KkCq4vx

So basically, let's assume you have an hotbar full of stacks of logs, if you start delivering for example holding slot 7 or 8 the first slots disappear too and they are counted just one time for the mission

**Comment by PikaMug** [comment]
I was able to replicate the issue. Feel free to submit a new PR, else I'll look into a fix soon.

**Comment by PikaMug** [comment]
Issue resolved in the following dev build:
https://ci.codemc.io/job/PikaMug/job/Quests/60/
