### ISSUE TITLE
Color Codes in Objective Override not Functional on 1.13 (Works on 1.10)

### ISSUE THREAD

**Issue by Xekter** [PikaMug/Quests#1047]
Hey, just wanted to make this to talk about an issue I've been having lately. To make it easy to follow, I'll go step by step as to what I've done so far.

1. Created a Quest on Version 1.10 using color codes (&1, &2, etc) in the Objective Override section of each stage (Where you can customize the objective message) and all the colors displayed as expected. No issues were found as far as I saw.

2. Created a Quest on Version 1.13 using color codes in the Objective Override section, and instead of the colors displaying properly, they showed up in the &a color and showed exactly what I wrote. For example, &3&l-> &bTravel to Market is what would be displayed in the light green (&a) color. 

3. The next step I was told to take was to try it through config using <red>, <yellow>, <orange>, etc. each time I wanted to customize the objective overrides. This, however, didn't work either. This ended up actually bugging out the colors of the ask message and worsened the issue once the new config file was added in (ask message was never touched in the config, not sure why it changed).

Screenshots of each event can be provided if you need them (they're sorta scattered + I didn't really know how to import them in an organized manner).

Thank you for being able to take your time to look into this issue.

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions.

@Xekter Please provide your Quests version to reopen this issue (do not say "latest").

**Comment by Xekter** [comment]
Oh, sorry. The quest version being used is Quests 3.8.4-b56.

Here is a pastebin showing the stages I have tried editing for the Quest. 

https://pastebin.com/tZ5DBM78 

Thanks! Just let me know if I need to provide anything else or if I did anything wrong in submitting an issue report.

**Comment by PikaMug** [comment]
Both formatting codes and tags should be supported with this build:
https://ci.codemc.io/job/PikaMug/job/Quests/62/

**Comment by Xekter** [comment]
Yup, that works! Though, I did notice one more bug - when the player completes the quest and it shows the (Completed) [Objective Message], the Objective Message colors don't show up. I wasn't sure whether I needed to make a new post for this since it is a follow-up, but if I do, I'll go ahead and do that.

**Comment by PikaMug** [comment]
@Xekter Use https://ci.codemc.io/job/PikaMug/job/Quests/63/
