### ISSUE TITLE
\lang folder missing

### ISSUE THREAD

**Issue by AndrewRoxxy** [PikaMug/Quests#1051]
I downloaded the last file of "quests" plugin from the spigot page, I installed it on my server which runs 1.12.2 spigot server and the plugins work perfectly. Except for the language part. It seems that the plugin is unable to create the folder even if I gave my plugins folder the "write" permission. I tried many times but still not working.

**Comment by PikaMug** [comment]
Thanks for using Quests. If you’re on Windows, try following this guide: https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting

If that doesn’t work, or you’re on another OS, create the /lang/**-** folders manually and download the desired languages from https://github.com/PikaMug/Quests/tree/master/main/src/main/resources/lang

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
