### ISSUE TITLE
PlayerMoveEvent Bug and a Quest Task Error

### ISSUE THREAD

**Issue by RedishTiger** [PikaMug/Quests#1052]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v3.8.5-b64 and paper version git-Paper-80 (MC: 1.15.2)
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
PlayerMoveEvent Bug:
https://pastebin.com/GFVAquk6
Quest Task Error:
https://pastebin.com/KLjGXQmZ

I have no idea how to replicate them, but they both spam the console and I have no clue how to fix.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Here's some examples of some quests I have: 
https://pastebin.com/auYGz3pj
I don't know if these are the quests causing the issues, but they're probably the most mechanicy quests I have, both relying off reaching a certain area.

**Comment by PikaMug** [comment]
Please try https://ci.codemc.io/job/PikaMug/job/Quests/66/ and report back with any new issues.
