### ISSUE TITLE
Quest Journal Customization.

### ISSUE THREAD

**Issue by DeniedINC** [PikaMug/Quests#1053]
Would you be able to make the GUI 100% customizable like the way QuantumRPG does it or Deluxemenus.

I would want to choose a material for the next/previous page, exit button, background fill, and empty quest fill.
Changing the title format would be awesome too. Something like this in the config.
journaltitle: "&6Quest Journal - %page_number%"

This is the only feature I personally use and would love to be able to make it fit my server properly. As a player it is also quite annoying having to press the exit button manually instead of closing the inventory, hitting escape, or having the option to go back instead of exiting.

Here's what I'm trying to make my menu look like.

[GUI EXAMPLE](https://i.gyazo.com/10f19183dfb996af4aa546b21aaed872.png)

I believe adding this customization would make the QuestsGUI plugin a must have along with your original plugin.

**Comment by PikaMug** [comment]
This issue tracker is for Quests only; not QuestsGUI. Please use the discussion thread at https://www.spigotmc.org/threads/questsgui-paid.399346/

That said, I’m already looking into the blank space thing and Esc on command prompts. Remember that the QuestsGUI is built _on top_ of Quests, so if the journalTitle string for the main plugin is edited it should display in QuestsGUI as well.

For things like Esc on editor prompts and moving icons around, it’s very unlikely. Without getting too technical, QuestsGUI doesn’t know which icon correlates to which prompt number - it’s based on slot numbers in the interface. So if you were to move the icons around or close a prompt without clicking a slot, the plugin won’t know which prompt number to use. It’s done this way to minimize issues when new features are added to Quests (and thus, new numbers). 

You could hire a developer from the SpigotMC forums (not sponsored) to either make a similar GUI plugin or a bridge with Deluxemenus, but anything with that kind of advanced functionality will be much more likely to break when Quests updates, requiring continuous work. Ultimately, this should not be the case with QuestsGUI once it hits 1.0 version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
