### ISSUE TITLE
Suggestion for Fail Quest Message

### ISSUE THREAD

**Issue by Xekter** [PikaMug/Quests#1054]
**What does your feature do?**
This feature essentially adds a message when a player fails a quest (other than the typical Quest Failed message).

For example: A quest asks the player to deliver a book to an NPC on a boat before the boat leaves. You use a quest event for this setting it to fail the quest if the player does not finish this stage (delivering the book) within 1 minute. In the case the player fails, the user can set a custom fail message that appears right after the Quest Failed default message saying something like:

You failed to deliver the book in time! The boat now departs! 

I feel like this would be cool as it tells the player why they failed the quest and adds more detail to the story to show what went wrong.

**How would people use it?**
My suggestion for this would be to make the Fail Quest option under Quest Events appear something similar to this once selected:
1 - Fail Quest (Y or N)
2 - Set Fail Message

The Fail Message should appear after the default Quest Failed message, so something similar to this (forgive me as I don't know how the Quest Failed looks exactly for the default message, but here's a shot).
***QUEST FAILED***
You failed to deliver the book in time! The boat now departs! 

Would be nice too if this allows color codes for extra customization.

Thanks for looking into my suggestion!

**Comment by PikaMug** [comment]
Thanks for your suggestion. It's becoming apparent that failing a quest should probably become its own action type, as shown here:

![68747470733a2f2f692e696d6775722e636f6d2f4e6a48476979352e706e67](https://user-images.githubusercontent.com/2267126/73497578-1cbdc200-4389-11ea-90aa-2d29283868ae.png)

However, I do not consider this to be of high priority, so it will be addressed in due time.

**Comment by Xekter** [comment]
Sounds good! When this is addressed, would it also be possible to add a "Set fail message" option in actions?

**Comment by PikaMug** [comment]
For the message, just use the `Send message` action and set the "QUEST FAILED" message in _strings.yml_ to be blank or a space.
