### ISSUE TITLE
i cant get the gui to work when i install the quests gui plugin

### ISSUE THREAD

**Issue by Stoniasawsome** [PikaMug/Quests#1055]
**Where else have you looked for answers to this question?**

**If applicable, which class or method is this in reference to?**

**Share your question with as much detail as possible?**

**Comment by PikaMug** [comment]
Thanks for using Quests! However, you have not asked a question. Also, this issue tracker is for Quests; not QuestsGUI. Please use the discussion thread at https://www.spigotmc.org/threads/questsgui-paid.399346/
