### ISSUE TITLE
color White not correct?

### ISSUE THREAD

**Issue by Stoniasawsome** [PikaMug/Quests#1056]
**What is your Quests version / build number (do _not_ say "latest")?**

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by Stoniasawsome** [comment]
my current version is 1.15

**Comment by Stoniasawsome** [comment]
the error is saying 
sheep-to-shear has invalid color White, see quest Shear Sheep stage 1
but it says in the plugin this is the format to use..  (White)

sheep-to-shear has invalid color White, see quest Shear Sheep stage 1
Loaded language en-US. Translations via Crowdin
Unable to load custom objectives because quest for custom20 was null

this is the custom quest
custom20:
    name: Shear Sheep
    ask-message: '&eShear &d3 White Sheep&e.'
    finish-message: Well done!
    stages:
      ordered:
        '1':
          sheep-to-shear:
          - White
          sheep-amounts:
          - 3
    planner:
      cooldown: 604800
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true

**Comment by PikaMug** [comment]
@Stoniasawsome Use https://ci.codemc.io/job/PikaMug/job/Quests/67/
