### ISSUE TITLE
Can we do actions on quest failed?

### ISSUE THREAD

**Issue by delocura** [PikaMug/Quests#1058]
I have asked in discord but anybody have answers.

When the quest starts the player is teleported to a dungeon or other map.
But if the time finish or the player fail the quest.
He stay in that map and dont return.
Only return when the player complete the quest.
I like do actions when a player fails the quest.
Example.
He need shear 30 sheeps in a dungeon full of sheeps.
When he shear the 30 sheeps he return to the lobby that i have created for quests.
When he dies he return to the spawn of the server and the quest is cancelled.
When the time runs out he only fails the quest but stay in that site. And can get infinite wool...

I think that actions in failed quests is the bes suggestion if it doesn´t exists.
And is easy add that no?

I wait a answer, thanks 4 all.

**Comment by PikaMug** [comment]
Not currently possible. However, I'll keep this in mind when addressing #1054

By the way, if you intend on creating a quest for shearing sheep, I suggest updating to the latest development build, as a bug was recently fixed with that objective type:
https://ci.codemc.io/job/PikaMug/job/Quests/67/
