### ISSUE TITLE
How can I change the / Qa command

### ISSUE THREAD

**Issue by DaniRangel** [PikaMug/Quests#1061]
I use the Quality Armory plugin, and that plugin uses the / qa command, then it generated conflict with Quests

**Comment by PikaMug** [comment]
Change the command within either Quests or QualityArmory by opening on of the jar files in a tool like 7zip and changing the command in the plugin.yml file. Alternatively, you might be able to use a plugin like https://www.spigotmc.org/resources/mycommand.22272/ (not sponsored)
