### ISSUE TITLE
Console Spam with DungeonsXL

### ISSUE THREAD

**Issue by iNezuko** [PikaMug/Quests#1064]
### What is your Quests version / build number (do not say "latest")?
3.8.5-b64

### Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?
https://pastebin.com/CaUBGyAm

I'm experiencing issue when I enter DungeonsXL with someone that has different version than the other (didn't test on other versions except for 1.8.9, 1.15.1, 1.15.2). My server is on 1.8.8 and uses viaversion. 

The crash shows  "Could not pass event PlayerMoveEvent" when someone moves.
It seems like it crashes also when someone punches.
It doesnt happen when player with any version enters dungeon alone.
This doesnt occur when Quest isnt installed, **but still occurs when DungeonsXL module isn't there** (I assume that's probably problem, because Quest cant determine where player is in the world, since the world is temporary)

**Comment by iNezuko** [comment]
Edit: Players that use the same client version (1.8.8) spam the console with "event PlayerMoveEvent" "event PlayerInteractEvent".

**Comment by PikaMug** [comment]
I've moved your console error to a Pastebin. Please follow the issue instructions more carefully next time.

The commit I've pushed should resolve the issue. Look forward to its inclusion in the next release.
