### ISSUE TITLE
Config to remove QA modifications in chat

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1065]
**What does your feature do?**
It will hide strings such as "Has forced you to finish your quest" from being shown in chat.
**How would people use it?**
Right now what can be done is making the string empty but the chat still pops up an empty line.  The reason why I'd want to hide them is because utilizing scripts with Denizen to assign skip, give and remove quests from users to get a bit more customization how they're done. The current hack of having an empty line isn't a big deal but it may appear weird at times.

**Comment by PikaMug** [comment]
Thanks for your suggestion. First I'd like to encourage you to keep an eye on https://github.com/DenizenScript/Depenizen/pull/305 which, if accepted, will let you use the next release of Depenizen to give, quit or advance a quest for a player. The quit command specifically has a true/false flag for whether to notify the player, but iirc none of them should send any messages.

Regardless, feel free to list the other strings I should look at in the interim.

**Comment by Maitlans** [comment]
Oh thanks for the great Denizen contribution, this is a big step towards very advanced quests with interesting mechanics. 

Side note suggestion for the Denizen, could you potentially add an attribute for custom objectives even if the quests plugin doesn't understand them if they can be projected in the journal or when you do /quest that can be completed specifically using Denizen. Let me know if I have to open a suggestions thread :D

**Comment by PikaMug** [comment]
The aforementioned pull request was merged and is now in wide circulation, satisfying this ticket.
