### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1066]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-3.8.5
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I want to only have the user be able to type the command /quest or /quests journal but giving the user just the permission "quests.journal" alone will give him access to all of the other /quests commands.

**Comment by PikaMug** [comment]
The `quests.journal` permission does not give rights to anything other than the Quests Journal. All _/quests_ permissions are `true` by default, so you need to revoke the permissions for commands which you don't want them to have. So, rather you giving players the `quests.journal` permission, you need to take away `quests.stats`, `quests.take`, et al.

If you remove those permissions and find players are still able to use them, that'd be a bug, in which case feel free to open a new issue.
