### ISSUE TITLE
Crafting shift click 

### ISSUE THREAD

**Issue by call911nowplz** [PikaMug/Quests#1067]
Quests version:  3.8.4
Minecraft version: 1.8

Bug description: crafting items quests won't progress if you shift click the crafted item instead of moving it with the cursor.
No console errors.

**Comment by PikaMug** [comment]
Thanks for the report. I wasn't able to replicate this issue on a 1.8.8 server, nor a 1.15.2 server. Could please provide the quest that you're using for testing? Either c/p into a site like Pastebin or just upload the entire quests.yml file.

**Comment by call911nowplz** [comment]
https://cdn.discordapp.com/attachments/385955986348965909/673855512571281408/quests.yml
Here is my quests.yml.
I use custom recipes with another plugin (its just normal items with custom names and lores)
It DOES work when moving it with cursor isntead of shift-clicking. The issue is only with shift clicking crafted items.

**Comment by PikaMug** [comment]
In that case, any number of things could be happening depending on how it modifies/handles the crafting event. Is this plugin available freely online?

**Comment by call911nowplz** [comment]
https://www.spigotmc.org/resources/prorecipes.52533/
Use /Rec
To create a recipe.
I used multiple plugins, all have the same outcome

**Comment by PikaMug** [comment]
I've looked at the source code for the that plugin and confirmed what some of the reviews said - it doesn't handle shift-clicking correctly. In other words, this is an issue with that particular plugin; not Quests.

Recommend using a different recipe plugin that's still active, such as [this one](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-12-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/) (not sponsored).

**Comment by call911nowplz** [comment]
Tested that plugin, It doesn't support custom names/lores. 
But if it's that other plugin then alright, Noted
thanks
