### ISSUE TITLE
BUG WITH PASSWORD STAGE NOT TAKE IN IT

### ISSUE THREAD

**Issue by anthony114669** [PikaMug/Quests#1068]
ok when i create a quest when the stage 1 requiere a password in the chat if i OP it works but if im a normal player the code does not work at all. there is a bug or i missing some permission?

**Comment by tiarnia** [comment]
same issue only OP's can respond and get it to work otherwise it just says the password in normal chat

**Comment by PikaMug** [comment]
Thanks for your report. This is not a bug - players must have at least one permission that starts with `quests`. This goes for most other objective types as well.

Relevant line of code: https://github.com/PikaMug/Quests/blob/16edbed39b531ccd5bdc8483d44513febdc149db/main/src/main/java/me/blackvein/quests/Quests.java#L3110
