### ISSUE TITLE
Duplicate Quests

### ISSUE THREAD

**Issue by MisterMisterK** [PikaMug/Quests#1070]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.6
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Editing a quest results in 2 of the same quests and it makes them un-removeable.

1. Make a quest
2. Assign an NPC to the quest.
3. Edit the quest and save it.
4. /questsadmin reload
5. Duplicate is made
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for your report. I wasn't able to replicate this issue per se, but did discover that quest IDs would erroneously increment after editing, It seems likely that what you're experiencing is a by-product of this.

That said, please try the following build and let me know whether the problem has been alleviated:
https://ci.codemc.io/job/PikaMug/job/Quests/70/
