### ISSUE TITLE
None of my quests are being loaded, and cannot create any new quests.

### ISSUE THREAD

**Issue by RedishTiger** [PikaMug/Quests#1072]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests version 3.8.6-b69
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Quests plugin loads up, all my actions get loaded in, but 0 Quests. I can't even create any new quests. It let's me go through the quest editor menu, but at the end, nothing gets saved. No idea how to replicate it, it just suddenly happened when I updated quests. Also, no errors at all. 
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Example quests from my file:
https://pastebin.com/auYGz3pj

**Comment by PikaMug** [comment]
Thanks for your report. Please share your startup log, as there's likely a warning that indicates what the problem is.

**Comment by RedishTiger** [comment]
> Thanks for your report. Please share your startup log, as there's likely a warning that indicates what the problem is.

I found the issue, however I'm not sure why I'm getting it?
https://pastebin.com/C09f07ub

It's saying special characters aren't allowed, however on previous versions I was able to use this character fine. 
----> ✪

**Comment by RedishTiger** [comment]
It seems something must have changed the symbols actually. Strange! Issue is solved though. Thankyou for your reply ^_^
