### ISSUE TITLE
Color Text Bug

### ISSUE THREAD

**Issue by destrutoyt** [PikaMug/Quests#1075]
**What is your Quests version / build number (do _not_ say "latest")?**
In the moment was 3.8.2 but I already updated to 3.8.6

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I'm trying to put some colors in the text of Quest when completing, starting, ending a mission. but when I start a mission It doesn't show me the colors that I put.

![2020-02-11_19 19 47](https://user-images.githubusercontent.com/60949635/74292153-4a015d00-4d05-11ea-97ea-b727acc694c7.png)

**Comment by destrutoyt** [comment]
And How can i remove that thing that says [Server: Title Command Successfully executed]

**Comment by PikaMug** [comment]
Quests doesn't parse colors in that format. Refer to the following documentation:
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#formatting
If you find `%red%` doesn't work, try `<red>` instead.

To disable those messages, run `/gamerule sendCommandFeedback false`.
