### ISSUE TITLE
how to remove already completed quests from the list

### ISSUE THREAD

**Issue by Stoniasawsome** [PikaMug/Quests#1076]
i am using quests 3.8.6 on my 1.15.1 server.

This question probably pertains to both questsgui and quests i dont know. I want to know if theres a way to make completed quests not show up. i have looked thru the wiki documents and cant find nothing about this. An example is when i type /quests list i can see all the quests ive already completed. I dont want players to be able to retake them. and also it would make room for more quests in the gui cause im currently out of room in there and have no second page. i have 50 beginner quests. when those are complete i have 50 more advanced quests, after that 50 more expert quests. but my players can only see the first 53 in the gui. if i could remove the completed quests then i could see the rest in the gui. I dont have any planner options set on the quests. just 50 points needed for the advanced quests and 250 needed for the expert quests.

**Comment by PikaMug** [comment]
Quests that can be redone only show if the quest is redo-able. In other words, if you don't want players to repeat the quest, then don't set a repeat-cycle in the first place.

More room in the GUI has already been requested, see #973

**Comment by Stoniasawsome** [comment]
i dont have anything set repeat cycle set ill show you the quest

  custom6:
    name: Mine Stone
    ask-message: §eMine §d64 Stone§e, and gather the cobblestone.
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          break-block-amounts:
          - 64
          break-block-durability:
          - 0
    rewards:
      money: 1000
      quest-points: 1
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true

 upon further inspection what happens is you cant actually redo the quest, but it also dont get removed from the list.

**Comment by PikaMug** [comment]
@Stoniasawsome Does it still happen if you set `ignore-locked-quests: true` in the _config.yml_ file?
