### ISSUE TITLE
[Suggestion] Make the plugin compatible with Twilight Forest

### ISSUE THREAD

**Issue by CanineNote** [PikaMug/Quests#1079]
Twilight Forest is a dimension exploration mod focused on adventure that will take you on a journey meeting strange creatures, exploring dungeons, and much more than able to be listed, but here are some of the major features:

Fully fledged dungeons (That incorporate new mobs which could be tracked by your plugin)
Diverse boss battles with new mechanics (That incorporate even more mobs that could be tracked by your plugin)
Items and loot which could be turned in to your NPC of choice.
and more.

Think about the potential for a modded server to be able to go into another dimension, kill a boss that was intended to be killed, and get rewarded for it. Sure we could use "MythicMobs, CustomMobs, or Boss" but why would we when we have bosses at our fingertips?

The mod has many downloads (26,896,657) to be exact, and it is found in most packs which are needing quests.

**Comment by PikaMug** [comment]
Thanks for your suggestion. At first, I was under the impression you were requesting compatibility with a Bukkit plugin, but it appears you're using the Twilight Forest client mod with Cauldron/MCPC. My knowledge of both is limited, but it's my understanding that Cauldron/MCPC merely allows server plugins to run on your modded server and does not provide any kind of interface for Quests to hook into to. That said, it's not possible to accomplish what you're asking without the developers of Twilight Forest providing some sort of API (specifically, an Event that triggers upon the death of their custom creatures). Even then, it would not be practical to implement the desired functionality directly into Quests - myself or [another developer](https://www.spigotmc.org/forums/hiring-developers.55/) (not affiliated) would need to [create a Quests module](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API) for it.

If you're intent on making this happen, you would need to start by requesting the aforementioned API from the Twilight Forest devs. Their issue tracker appears to be located at https://github.com/TeamTwilight/twilightforest
