### ISSUE TITLE
Unable to load module from file: SkillAPIModule.jar

### ISSUE THREAD

**Issue by BearLeonLight** [PikaMug/Quests#1080]
**What is your Quests version / build number (do _not_ say "latest")?**
 version: Quests 3.8.7-b72
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
errors : https://pastebin.com/9npZXxSi
ServerLog: https://pastebin.com/xLbC9kjP
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Everything is preset

**Comment by PikaMug** [comment]
The module is outdated. Contact the developer and request an update.
