### ISSUE TITLE
Quests not being accepted through Npcs

### ISSUE THREAD

**Issue by P-paj** [PikaMug/Quests#1081]
Version: 3.8.7-b72
Quests Gui Version: .8

The Problem:
No console errors found, but we just cant accept any quests through npcs, clicking on the gui icon does nothing, inventory stays open, icon stays in spot. Except for one npc we've found who, when you try to start the message responds "You must speak to [NPC NAME] to start this quest" twice

I can still do the quests with /questadmin give {playername} {questname} command, just cant start them at NPCs.

**Comment by PikaMug** [comment]
This issue tracker is for the Quests plugin, not QuestsGUI. Please answer the following questions:

1. What is your Quests version?
2. Does the problem still occur after removing QuestsGUI?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by P-paj** [comment]
Thank you.
Quests Version:  3.8.7-b72

yeah i just figured since it was involving the gui to give you those details
i removed quests gui and the issue persists...

**Comment by P-paj** [comment]
Actually all npcs are doing this now... its like the quest is at them, but they dont think it is once you try and start it?...

**Comment by PikaMug** [comment]
@P-paj Please give the following build a try and inform me of the results:
https://ci.codemc.io/job/PikaMug/job/Quests/73/

**Comment by P-paj** [comment]
Same Results! Getting "you must speak to {NPC NAME} to start quest" for all npcs!

Heres my quests.yml if that at all helps

**Comment by PikaMug** [comment]
@P-paj Thanks for getting back to me. Please give this one a try:
https://ci.codemc.io/job/PikaMug/job/Quests/74/

**Comment by Kangaroo942** [comment]
I had the same problem, but version 3.8.8 fixed it.
Thanks.

**Comment by AmmoniakNH3** [comment]
I have the problem too, Quests version 3.8.8 b74 
Can click at the Item and nothing happens.

**Comment by PikaMug** [comment]
@AmmoniakNH3 Would you mind creating a new issue with more information? I'm unsure whether the issue you're having is with Quests or QuestsGUI at this point, but this ticket is already resolved.
