### ISSUE TITLE
Quests Uncompleting

### ISSUE THREAD

**Issue by BarynnD** [PikaMug/Quests#1084]
Quests Version: 3.8.5

I encountered a random problem that came around when I wasn't configuring the plugin or anything of the likes. My friend had noticed that all of the quests had reset for him and that they were all available again a few hours after completion. I tried editing his actual player data in the plugin to give him back the quest completion status but it just erased the completed quests data again after reload. No console errors or anything to track the problem.

Pastebin of one of the few custom quests: https://pastebin.com/HWrfyFJR

**Comment by PikaMug** [comment]
Thanks for your report. I was unable to replicate the issue. Please ensure that it still occurs on the latest development build: https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by BarynnD** [comment]
I installed the latest update of the plugin and then edited the Player Data file for quests before loading up the server and It had displayed properly that he finished all the quests. Thanks for the quick response.
