### ISSUE TITLE
QuestsGUI Error On Startup

### ISSUE THREAD

**Issue by RageYT** [PikaMug/Quests#1087]
**What is your Quests version / build number (do _not_ say "latest")?**
##### Quests
v3.8.7-b72

##### QuestGUI
v0.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
QuestsGUI seems to have an issue on startup and does not load.

https://pastebin.com/psCDQix8

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/sm2VJRmy

**Comment by RageYT** [comment]
I noticed this line in the console, Citizens2 wouldn't be required for QuestsGUI by chance would it?

`INFO java.lang.NoClassDefFoundError: net/citizensnpcs/api/npc/NPC`

**Comment by PikaMug** [comment]
This issue tracker is for Quests; not QuestsGUI. I’ll look into the issue, but please submit future reports to the discussion thread at https://www.spigotmc.org/threads/questsgui-paid.399346/
