### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by marvinej** [PikaMug/Quests#1088]
**What does your feature do?**
Autosave quests being edited or created. 

**How would people use it?**
When someone is editing a quest or creating a quest auto save it every 3 mins to avoid data loss. I just spent an hour creating a quest and suddenly i was no longer in the editor and when i went to give the next command it just typed the number into chat.

**Comment by PikaMug** [comment]
Thanks for your report. Unfortunately, this isn’t possible when creating a quest as the user may not have filled out all required fields. As for editing a quest, I can’t think of any situations where the user would make a large enough edit to warrant auto-saving. Feel free to correct me on this if anything comes to mind.

**Comment by marvinej** [comment]
Its entirely possible. It may just require spme extra thought and work from
a programming perspective. Save it to its own seperate yml configuration
that can be loaded up later or something. I was technically doing an edit
as i saved it then came back to it the next day because the process of
creating takes so damn long.

**Comment by PikaMug** [comment]
What I meant is that it isn’t possible with how the editor is currently programmed. Feel free to submit a pull request.

Could you please elaborate? I’m able to make a basic quest in a matter of minutes. What exactly are you doing that takes so long?

**Comment by PikaMug** [comment]
Closing to due lack of response from OP.
