### ISSUE TITLE
Specific Quest permissions

### ISSUE THREAD

**Issue by Masterfixer06** [PikaMug/Quests#1089]
Hello there,

I was wondering if it is possible to give specific groups specific quests with PermissionsEx? Wasn't able to find an answer at the permissions/commands list.

Thanks!

**Comment by PikaMug** [comment]
Yes, players can be allowed/denied a quest based a certain permission. Use the `Edit Requirements -> Set permission requirements` option to accomplish this. See https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Requirements
