### ISSUE TITLE
quest suggestion 

### ISSUE THREAD

**Issue by pookylish** [PikaMug/Quests#1092]
hello i was wondering if possible could you add a collect option on the quest list when you click on items when starting a quest so then people can go and collect items and then bring them back to hand the quest in because at the moment there is craft break enchant ect so for example the quest could go go collect 45 red tulips and then deliver the items for rewards and so on thank you for taking the time to read this many thanks Pookylish

**Comment by PikaMug** [comment]
Thanks for your suggestion. If you want players to collect and deliver tulips, simply use a "Break block" objective for Stage 1, followed by a "Deliver item" objective for Stage 2.
