### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pookylish** [PikaMug/Quests#1094]
25.02 09:35:32 [Server] ERROR Ambiguous plugin name `Quests' for files `plugins/Quests-3.8.8.jar' and `plugins/quests.jar' in `plugins'

do you know what is wrong it was working ok till i downloaded this version

**Comment by PikaMug** [comment]
Thanks for your report. Does this build work instead? https://ci.codemc.io/job/PikaMug/job/Quests/75/

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
