### ISSUE TITLE
 Translation German Error Messages ingame

### ISSUE THREAD

**Issue by thedarkcookieez** [PikaMug/Quests#1096]
**What is your Quests version / build number (do _not_ say "latest")?**
Version 3.8.8 | Minecraft Paper 1.4.4 243b

I switched from en-US to de-DE.
At  **/quests take**
without what comes out then /quests NULL at out
and also at **/quests remove [player name]** without anything behind it
I don't have an error message in the console

http://prntscr.com/r7ophq
https://hastebin.com/yekulezera.pl

Thanks

**Comment by PikaMug** [comment]
I'm not having any trouble with de-DE on my end.

![german](https://user-images.githubusercontent.com/2267126/75312468-fe33d500-5827-11ea-904a-f10ba7a4457a.png)

Here's a few things you can try:

1. Troubleshooting https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting
2. Delete the /lang folder (or just the de-DE folder) and restart the server
3. Toggle `translate-subcommands` in your _config.yml_ file
4. Download the _strings.yml_ file directly from https://github.com/PikaMug/Quests/tree/master/main/src/main/resources/lang/de-DE
