### ISSUE TITLE
QuestGUI bug

### ISSUE THREAD

**Issue by NotKili** [PikaMug/Quests#1099]
**What is your Quests version / build number (do _not_ say "latest")?**

My current Quests version is 3.8.8, my QuestsGUI version is 0.11.
Our server is running Mohist-2e1b046

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

So, i bought QuestsGUI on spigot and uploaded it to our test server. Trying to use the GUI-Editor is really buggy, opening it lags a bit and after setting up one of the features (name for example, doesnt matter which one), you cant move your mouse cursor anymore. Its literally frozen in the middle of the screen. The only way to leave the server is to close minecraft.
There are no errors in console and/or logs aswell.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

Guess thats not needed because its a GUI bug. I am not even able to set up an example quest xD

**Comment by PikaMug** [comment]
This issue tracker is for Quests; not QuestsGUI. Please use the discussion thread at https://www.spigotmc.org/threads/questsgui-paid.399346/
