### ISSUE TITLE
Moduels(Compatibility Quests-Denizen)

### ISSUE THREAD

**Issue by Brack04NC** [PikaMug/Quests#1102]
Sorry for the inconvenience but what extension must the quests modules have and if I create them with Denizen are they compatible with quests?
Thank you.
(I haven't found any tutorials on Quests or on Denizen)

**Comment by PikaMug** [comment]
Modules have a .jar extension

You can’t create a module with Denizen. However, you can make a _script_ which used Denizen commands (or deeper integration with Depenizen).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
