### ISSUE TITLE
Error when using /qa reload 

### ISSUE THREAD

**Issue by Wirlie** [PikaMug/Quests#1103]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.8.8 (from Spigot)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I'm get this console error when use `/qa reload`. I have not modified the quests.yml file manually, only using the in-game editor. Problem gets fixed when I do a server reload, but after few editions and reloads problem appears again.

https://pastebin.com/qBBqPYjz

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
I provide mi quests.yml if needed.

https://pastebin.com/FXqiKHt1

Thank you for the help, and sorry if anyone already have reported this issue (I have done a search and cannot found any issue similar to this).

**Comment by PikaMug** [comment]
Thanks for the report. Please try the following development build:
https://ci.codemc.io/job/PikaMug/job/Quests/76/
