### ISSUE TITLE
Periodic Quests

### ISSUE THREAD

**Issue by Masterfixer06** [PikaMug/Quests#1104]
Hi there,

I was wondering if it's possible to set up the plugin so that players can only do a quest, for example, once per week. With this I mean any quest, not a cooldown for a specific quest. What I'd like to set up is that players can once a week choose a quest and that the other quests are not available. When the week is over, whether the quest is done or not, they can select a new quest and the old one will be gone.

I ask this because I was planning to sell server ranks which have different quest cooldowns. Is this possible or not, and if it is, how? I couldn't find anyone else with the same question, so i thought i'd ask it here.

**Comment by PikaMug** [comment]
Just revoke their Quests permissions, then restore them after a week. How you do this will vary with permission plugin, but as for timing it use something like boosCooldowns (not sponsored).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
