### ISSUE TITLE
Progress bar utilizing boss bars

### ISSUE THREAD

**Issue by BarynnD** [PikaMug/Quests#1105]
**Where else have you looked for answers to this question?**
I have looked through the closed Questions in the Issues tab on the Github and also tried googling it to no avail.

**If applicable, which class or method is this in reference to?**
Not sure what this means. :/

**Share your question with as much detail as possible?**
Is there a way to track quest progress in the form of a Boss Bar on top of the screen or even through a scoreboard utilizing an API of some sorts?

**Comment by PikaMug** [comment]
No, there is no way to do this within Quests itself. One could almost certainly create a secondary plugin or [module](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API) which uses either the boss bar or scoreboards, however as I alluded to in #986 I personally have no interest in doing this due other commonly used plugins competing for the space. Another alternative for those without knowing Java would be to use [the PAPI extension](https://www.spigotmc.org/resources/placeholderexpansion-quests.69357/) with a plugin that lets you create your own bars or scoreboards, like [FeatherBoard](https://www.spigotmc.org/resources/featherboard.2691/) (not affiliated).
