### ISSUE TITLE
Hidding chat messages

### ISSUE THREAD

**Issue by SeussCZ** [PikaMug/Quests#1107]
Will be nice to hide all messages in the chat (using language file). 

**example (string file):**
questDungeonsCreate: " "
or
questDungeonsCreate: ""
show in chat: **empty line**

I want to hide this empty line in chat. Something like if string file is null the line "p.sendMessage(ChatColor.YELLOW);" will be removed.

**Comment by PikaMug** [comment]
`questDungeonsCreate: ""` with no space should already work? See here:
https://github.com/PikaMug/Quests/blob/4d183edaea7ba656eaab526cfd723607ab30f336/main/src/main/java/me/blackvein/quests/listeners/DungeonsListener.java#L30
