### ISSUE TITLE
Delay not working

### ISSUE THREAD

**Issue by JordyPin** [PikaMug/Quests#1108]
**What is your Quests version / build number (do _not_ say "latest")?** 
3.8.8-b75

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I have set up a delay on a location quest with 14 stages. Each of these stages has a 20h delay, but when the 20h is hit after reaching the location, it does not move you to the next stage. I can also not manually move people onto the next stage using the qa nextstage command.
I tried a five minute delay quest to see if this was just my mess up on one quest, but I had the same issue.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/7sUSQVsK

**Comment by PikaMug** [comment]
The delay is how long to wait before the stage begins. Although there is no built-in option to force the player to the next stage, you could accomplish this with a Denizen script that runs the _/qa nextsage_ command.

**Comment by JordyPin** [comment]
Hi, yeah the issue that I'm having is that it doesnt automatically start the next stage after the delay. To try and better explain;

I accept the quest 
I go the location specified 
I get the complete message confirmation
I assume this is when the delay would then begin? However it doesnt ever put me onto stage 2, after the delay time.

**Comment by JordyPin** [comment]
Update after testing: Doesn't work with my 20h delay quest, however now works with my 5m delay quest. Perhaps something to do with time length? Also, worked after I added a break quest into #stage 1 along with the reach location, but not when it was just reach location.

**Comment by PikaMug** [comment]
@JordyPin I've been unable to replicate the issue, but have taken a crack at fixing it. Please give the following development build a try after backing-up your Quests folder:
https://ci.codemc.io/job/PikaMug/job/Quests/78/

**Comment by PikaMug** [comment]
Closing due to lack of response from OP. Recommend using latest dev build as opposed to the one linked above.
