### ISSUE TITLE
Smelt Quests isn't working

### ISSUE THREAD

**Issue by SmallBear46** [PikaMug/Quests#1109]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I created a quest where i need to mine then smelt iron ore, BUT, the smelt part isn't counted. 
Quests was the only plugin in my plugin folder to do what you say in the other post. Not working too.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://hastebin.com/raw/ajihudovan

**Comment by PikaMug** [comment]
Continuation of #1101 

Please provide your Bukkit/Spigot version.

**Comment by SmallBear46** [comment]
Spigot 1.15.2 Latest Build

**Comment by PikaMug** [comment]
The example quest you provided works fine after following these steps:

1. Quit the quest if already taken.
2. Change Iron_ore to Iron_ingot via the in-game _/quests editor_ (not in the file itself).
3. Save quest, then run _/questadmin reload_.
4. Take the quest and complete both stages.

![fer](https://user-images.githubusercontent.com/2267126/76153415-c33c6780-6099-11ea-93d7-c791f66c384e.png)
