### ISSUE TITLE
All the quest issues I have found

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1111]
When quests require enchanted gear as a delivery, or other things, explicitly put the enchants required on the item (Because it does not state the enchant)

When doing potions show the actual names of the potions and exactly what they are by putting your mouse over it, because currently it will just say "Healing potion" but never specify what type or even level

Water bottles are glitched for deliveries and cannot be delivered

Paper is glitched and does not allow deliveries of it if you have more than 3 quests that do paper deliveries

questsGUI does not actually save quests in 1.8.8

**Comment by PikaMug** [comment]
One issue per ticket, please. Also, you didn't follow the issue instructions (missing Quests version, etc.).

Lastly, this issue tracker is for Quests; not QuestsGUI. Any problems regarding that belong in the discussion thread at https://www.spigotmc.org/threads/questsgui-paid.399346/
