### ISSUE TITLE
NULL Items

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1112]
**What is your Quests version / build number (do _not_ say "latest")?**

3.8.8-b75

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Make a quest that has a deliver to NPC as a stage

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com**
No

It will always print NULL as an item when you create a delivery quest and go to set items

**Comment by PikaMug** [comment]
I'm unable to replicate this. Could be an issue with your locale files (within the /lang folder) or a particular item isn't supported. Either provide an example quest or give specific instructions on how to replicate the issue (what item you used, any special properties, etc.).

**Comment by Larskei-dev** [comment]
My Server version is 1.8.8 and I am running TacoSpigot, I completely wiped all the files, and tried it, same issue.

**Comment by PikaMug** [comment]
@Larskei-dev Thanks, but again, either provide an example quest or give specific instructions on how to replicate the issue (what item you used, any special properties, etc.).
