### ISSUE TITLE
Permission reward

### ISSUE THREAD

**Issue by Kangaroo942** [PikaMug/Quests#1113]
if I have the reward permission ... how do I set it to "global"

[screen](https://prnt.sc/rcnd2b)

Sorry for my english.... :)

pl: Quests-3.8.8; LuckPerms-Bukkit-5.0.72; Citizens-2.0.26-b1828

**Comment by PikaMug** [comment]
Not currently possible. Looks like Vault can already do this, so I'll have to add a menu option for specifying the world context (or lack thereof).
