### ISSUE TITLE
ERROR Console Spam

### ISSUE THREAD

**Issue by BlitzGamer-88** [PikaMug/Quests#1116]
Quests version: 3.8.8-b75
Server version: Paper-237(1.14.4)

Hello. So this thing happens random or at least I can't rly tell when and why it starts as it spams my console. This is the error that spams my console a few times a second: https://pastebin.com/uiyT0pQz
This spam stops on server restart but it usualy starts again. It doesn't start at the same hour every time but rather random.

These are my quests: https://pastebin.com/G6JPvUD2

**Comment by PikaMug** [comment]
Thanks for the report. The log you've provided doesn't indicate where the problem lies, so I'll have to try the replicate it. Are you able to share any more information?

**Comment by bzigus** [comment]
Hey, I was running into this issue too. It makes the plugin unusable. I got more info in my error. https://pastebin.com/Bxzasc1n
