### ISSUE TITLE
Chunk loading crash

### ISSUE THREAD

**Issue by supertakeru** [PikaMug/Quests#1117]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.8.8
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/kWsDTnCH
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
This appears to be a corrupted chunk and not an issue with Quests. However, I've added some checks as an extra precaution. Thanks for your report!
