### ISSUE TITLE
"Talk To NPC(s)" name(s) aren't showed on quest steps (messages too during the quest)

### ISSUE THREAD

**Issue by Corazun** [PikaMug/Quests#1118]
Hello, the plugin had a minor issue, the NPCs name aren't properly displayed on messages (on screens)

![image](https://user-images.githubusercontent.com/54606072/76499544-3437a280-643f-11ea-92f0-f576f5f3db12.png)

![image](https://user-images.githubusercontent.com/54606072/76503766-bbd4df80-6446-11ea-9c91-bc228979811f.png)

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions (missing Quests version and example quest). Feel free to comment below with the missing information to reopen.
