### ISSUE TITLE
Multiverse problem?

### ISSUE THREAD

**Issue by supertakeru** [PikaMug/Quests#1119]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.8
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/62uNc5wV
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report! Someone tried to take an NPC-given quest via command from a different world than the NPC resides in. This will be resolved in the next release.
