### ISSUE TITLE
Delay Not Working Before Stage / Action

### ISSUE THREAD

**Issue by Gamn69** [PikaMug/Quests#1125]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When a delay for a stage is set the actions run before the delay is over. The actions run when the stage is initiated. (This may be similar to issue #1108.)

**Comment by PikaMug** [comment]
Unable to replicate. Please provide an example quest from quests.yml using Pastebin/Hastebin re-open.
