### ISSUE TITLE
Process Delay

### ISSUE THREAD

**Issue by MaxIsV** [PikaMug/Quests#1127]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.5 version of Quests
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
With the help of timings, I tracked the delay during the execution of the process "Quests::Event: m.b.q.l.PlayerListener (PlayerCommandPreprocessEvent)" https://timings.aikar.co/?id=a72ce7a083214c8bbfe99080e76590c9#timings
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
The timing report doesn't indicate any issues with Quests and the event specified is well within acceptable parameters. If there's something you need help with, update to Quests 3.8.8 and open a new issue with more information.
