### ISSUE TITLE
Quests Bug

### ISSUE THREAD

**Issue by SladeHazard** [PikaMug/Quests#1129]
**latest v3.8.8-b75**

**quests not working and error on server start, Error: hastebin.com/mimitojaye.bash**

**If applicable, yes it's applicable: Quests.yml: https://hastebin.com/ubocomamed.bash**

Quest server startup log: [07:27:39 INFO]: [Quests] Enabling Quests v3.8.8-b75
[07:27:39 INFO]: [Quests] Loaded language en-US. Translations via Crowdin
[07:27:39 WARN]: [Quests] WorldGuard was detected, but is not enabled! Fix WorldGuard to allow linkage.

**Comment by PikaMug** [comment]
The root cause is just as it says - you need to fix your WorldGuard setup. However, I'll push a commit to mitigate the errors.

**Comment by SladeHazard** [comment]
> The root cause is just as it says - you need to fix your WorldGuard setup. However, I'll push a commit to mitigate the errors.

What is wrong with my worldguard setup i'm using default files also fixing worldguard will fix this?
