### ISSUE TITLE
/questadmin reload - Internal Error

### ISSUE THREAD

**Issue by TheOriginalHawk** [PikaMug/Quests#1136]
**What is your Quests version / build number (do _not_ say "latest")?**
-> Quests 3.8.9.jar Jenkins Build #80

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
-> Probably issue with Citizens again. Happens with /questadmin reload and throws internal error. I have let all config files generate again as we only had test quests before.

-> https://pastebin.com/dxRY65kf (Error msg)
-> https://pastebin.com/SGiXEvzT (On server start)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
-> https://pastebin.com/eDHZuUfF (quests.yml)

**Comment by PikaMug** [comment]
Thanks for the report. This is not related to Citizens, but rather the reward you set for the StoneTest quest. What were you trying to set as a reward?

**Comment by PikaMug** [comment]
@TheOriginalHawk Issue has been addressed. Use the following build, and either remove the reward from your file or start fresh:
https://ci.codemc.io/job/PikaMug/job/Quests/81/
