### ISSUE TITLE
Quest won't save (1 or Yes entry

### ISSUE THREAD

**Issue by TheOriginalHawk** [PikaMug/Quests#1137]
**What is your Quests version / build number (do _not_ say "latest")?**
-> Quests3.8.9.jar Jenkins Build #81

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
-> Quests wont save with either '1' or 'Yes' input. '2' for "dont save" works though. I don't know how to replicate, I hope this time it's not me being clumsy, but I for sure believe I typed '1' (no ' '). I fully reset the config files upon downloading Build #81 [Sorry for getting on your nerves. Just really want this awesome plugin to finally work]

-> https://pastebin.com/S52Mcn1B

-> Quests and Citizens start/load up fine.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
-> Default - Quest didn't save.

**Comment by PikaMug** [comment]
@TheOriginalHawk Thanks for the report. You're not on my nerves at all - the input is appreciated.

Please give the following build a try (you shouldn't need to reset any files this time):
https://ci.codemc.io/job/PikaMug/job/Quests/82/
