### ISSUE TITLE
Quest Permissions With Citizens

### ISSUE THREAD

**Issue by Masterfixer06** [PikaMug/Quests#1139]
Hi there,

I've recently downloaded the Quests plugin and the Citizens2 plugin. What I was trying to do is that players can accept quests by going to the npc, but that they were only allowed to take a quest once in a week.

I have managed to accomplish this using boosCooldowns and Luckperms, but this only works with commands (/quest take [quest]). When I was testing the npc, I could just 'spam' the quests; the cooldown didn't seem to work. The specific Quest permission didn't seem to be working with the npc.

My question is, is it possible to apply cooldowns on quests with npc's, or is this not yet possible? With this I mean a way to apply different cooldowns on different groups, preferably using Luckperms and boosCooldowns.

I know it's very specific, but hopefully you can help me!

Thanks in advance!

**Comment by PikaMug** [comment]
You can apply cooldowns to any quest using the [Edit Planner](https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner) menu in the /quests editor. However, this will apply to the quest regardless of whether it was taken via NPC or via command.

**Comment by Masterfixer06** [comment]
Hi there,

I don't think you quite got my question.
My plan was to sell different ranks on my server, then set cooldowns on the command for taking quests, and make it that different groups/ranks have different cooldowns. I have accomplished this with using commands from the Quests plugin itself, but I can't seem to get a cooldown on taking a quest with Citizens.

What I have done to set a cooldown for taking a quest with a command:
- I have set a cooldown on the command '/quest take [quest]' using boosCooldowns.
- I have put the boosCooldowns group permission in a LuckPerms group.

But now the cooldown only applies to quests taken with commands, but not with Citizens.
How can I accomplish this?

For clarification, I don't want a cooldown for a specific quest, but a cooldown for taking quests in general.

I hope you can help me with this, thanks in advance!

**Comment by PikaMug** [comment]
It sounds like you want to place a cooldown on an [Event](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/Event.html) (namely, Citizens' [NPCClickEvent](https://jd.citizensnpcs.co/net/citizensnpcs/api/event/NPCClickEvent.html)). This is not available through Quests, as many would consider that limiting to gameplay. However, it is possible, as some PvP plugins do this to limit fighting speeds, teleportation, etc.

A quick Internet search for "bukkit event cooldown" nets plenty of tutorials on how to do this. However, if you don't feel comfortable writing a plugin of your own, consider hiring a developer to do it for you at https://www.spigotmc.org/forums/hiring-developers.55/ (not sponsored).
