### ISSUE TITLE
Players finish quests without starting a quest.

### ISSUE THREAD

**Issue by TheOriginalHawk** [PikaMug/Quests#1140]
**What is your Quests version / build number (do _not_ say "latest")?**
Quest-3.8.9.jar Jenkins Build #82

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Guess who's back =) - Yeah I don't know at this point anymore. A player gets rewarded without running a command/touching an npc (still not working for me). Citizens and Quests start up perfectly (Quests fails to link, but links after citizens load.) Wierd is that I don't have a quest which rewards $100. 

* I have tried resetting my citizens too, but for some reason it saves all npcs created despite me deleting every single file. I'll try resetting both again when my server gets emptier.

"Error" : https://pastebin.com/s1NtcjER

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
-> https://pastebin.com/cDtwNJdm

**Comment by TheOriginalHawk** [comment]
I will go back to an old version of Citizens (2.0.25) and Quests (3.7.8) as they had worked when we first updated from 1.14 to 1.15.2. I'll do this when the server empties out.

**Comment by PikaMug** [comment]
I'm not certain this is an issue with Quests. The "error" you provided just shows someone with console access running a command [which fails] to give player Caroooot money, and then sends them a message. Perhaps one of your admins is pulling a prank on you? Could also be some other plugin running commands, but it's not typically done that way.

**Comment by TheOriginalHawk** [comment]
Nope, there was no other Staff member online. I'll be trying older versions again with old citizens versions and see if I manage to get everything running smoothly like it once did.

**Comment by PikaMug** [comment]
Feel free to update this ticket with any progress. However, I must stress that Quests would only issue commands like that if you have a command reward or action linked to a quest (of which I see neither of in the provided quests.yml file).
