### ISSUE TITLE
I use the default Quest who i get when i install the plugin. I as op can take quests, but non op get error:

### ISSUE THREAD

**Issue by tw1xen** [PikaMug/Quests#1143]
[20:49:17 INFO]: [Quests] roxer01 attempted to take quest "null" but something went wrong

Version: Quests 3.8.8
Running at latest paper-clip build

**Comment by PikaMug** [comment]
Thanks for your report. I'm unable to replicate this. Can you open _quests.yml_ and share the quest which you're trying to take? Use either Pastebin.com or Hastebin to maintain spacing.
