### ISSUE TITLE
Can't right-click NPCs during the editor and when trying to open the GUI

### ISSUE THREAD

**Issue by Stuart-BimboJimbo** [PikaMug/Quests#1144]
**What is your Quests version / build number (do _not_ say "latest")?**
-> Quests-3.8.9.jar Jenkins Build # 82
-> Citizens v2.0.26-SNAPSHOT (build 1854)
-> PaperSpigot-1.15.2.jar (Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT))

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
-> I can't right-click when choosing my NPC or to run a Quest. There is no error given from Quests or Citizens. I've tried resetting everything.

-> Startup (Citizens + Quests output marked with XXXXXX... at the end of the line): https://pastebin.com/84m9sqVQ

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
-> quests.yml: https://pastebin.com/NSfz7sBw

**Comment by PikaMug** [comment]
Thanks for your report. I was unable to replicate the issue on a 1.15.2 server. Please try removing non-essential plugins temporarily to ensure there is no conflict.

![stone](https://user-images.githubusercontent.com/2267126/77795582-2fc8d780-7044-11ea-9636-645d73793c42.png)

**Comment by Stuart-BimboJimbo** [comment]
Does Quests run a certain command in the background when clicking the NPC's?

**Comment by PikaMug** [comment]
Yes, the commands to display a title/subtitle are run, but this applies when taking a quest via command, as well. There are no widely-popular plugins which conflict to my knowledge, but it's the most likely possibility in this scenario.
