### ISSUE TITLE
Not loading correct after having 49+ (inkl. 49) Plugins

### ISSUE THREAD

**Issue by Stuart-BimboJimbo** [PikaMug/Quests#1146]
**What is your Quests version / build number (do _not_ say "latest")?**
-> Quests-3.8.9.jar Jenkins Build # 82
-> Citizens v2.0.26-SNAPSHOT (build 1854)
-> PaperSpigot-1.15.2.jar (Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT))

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
-> During server start Citizens loads before Quests when there are 48- plugins. After reaching 49+ plugins Citizens begins to load after Quests. Quests doesn't hook but apparently hooks again after Citizens loads. This feature which I believe has been implemented in Jenkins Build # 80 doesn't really work like it should as I can't use Citizens in combination with Quests (Citizens Gui with R-Click).

-> Over 49 Plugins Load: https://pastebin.com/vZiwECJ1
-> Under 49 Plugins Load: https://pastebin.com/e36cpVM8

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
-> https://pastebin.com/QB9YatHV

**Question** 
-> Could you please try to make a version which hard depends on Citizens? Maybe that'll do the trick and load after Citizens then.

**Comment by Stuart-BimboJimbo** [comment]
If you need a list of Plugins please message me via Discord: Stuart#6985 =)

**Comment by PikaMug** [comment]
Hard-depending Citizens is not an option, as Quests is designed to work without it.

Dev builds aren't working at the moment (one of the repositories is down), so please wait for the upcoming release on SpigotMC.

**Comment by Stuart-BimboJimbo** [comment]
I'll see if the loading works in the new version. Thank you.

**Comment by PikaMug** [comment]
I do not make custom versions of Quests except for rare debugging purposes, of which this is not currently one. However, you could open the jar with a tool like 7-Zip and change the plugin.yml file yourself.
