### ISSUE TITLE
No count Spawner mobs

### ISSUE THREAD

**Issue by Atlantiis31** [PikaMug/Quests#1149]
Hello,
I had a suggestion,

**What does your feature do?**
Would it be possible to add the possibility to activate/desactivate the counting of mobs from spawners for each quests ?
Currently, all the mobs count for a quest.

Thanks for this plugin and your working ;) !

**Comment by PikaMug** [comment]
Thanks for your suggestion. It's possible, but not really something I feel would benefit most users. As such, this would be better left to a [custom objective module](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API#objectives-api). If you're not comfortable with creating one, I'd recommend hiring a developer from https://www.spigotmc.org/forums/hiring-developers.55/ (not sponsored).
