### ISSUE TITLE
Rewards Are broken

### ISSUE THREAD

**Issue by kyledavis124** [PikaMug/Quests#1152]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

https://pastebin.com/xc6qXG9c

I set up everything using the editor. I set the Rewards for money to 50 and quest points to 1 and when completing the quest, I get 50 quest points and 1 money. 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/FnWNAtJY

**Comment by PikaMug** [comment]
Thanks for catching that! Please use the following development build:
https://ci.codemc.io/job/PikaMug/job/Quests/85/
