### ISSUE TITLE
Quest Modules Error on startup with Quests 3.9.0

### ISSUE THREAD

**Issue by marvinej** [PikaMug/Quests#1153]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.0
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/xZitjk5D
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
This is an issue with the module; not Quests. Report it to the module author.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marvinej** [comment]
You are the module author...these are plugins i got from you at
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules

They are clearly authored by you and link to your github...

**Comment by PikaMug** [comment]
@marvinej No, I’m not - that’s merely a list of modules that I’m aware exist. MagicQuests is made by a different developer.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marvinej** [comment]
Perhaps you didn't bother to read the entire paste, idk. I just posted all
of the errors for you because i figured you made an API change or something
that broke them since NONE of them work including boss quest and mobarena
quests which are both clearly authored by you. https://imgur.com/7XHtLj4
Could not load 'plugins/MagicQuests-1.3-SNAPSHOT.jar'
Could not load 'plugins/BossQuestsModule-1.0.jar'
Could not load 'plugins/MobArenaQuestsModule-1.0.jar'

**Comment by PikaMug** [comment]
Oh I see, you've put them in the /plugins folder. They need to go in /plugins/Quests/modules.

**Comment by marvinej** [comment]
ok. Sorry for bothering you. that seems to have corrected the issue. i must have overlooked putting them in the correct folder. as a side note if its not too difficult perhaps you could ad an error catch to tell people when they put them in the wrong place.
