### ISSUE TITLE
Quest Journal Colors

### ISSUE THREAD

**Issue by Masterfixer06** [PikaMug/Quests#1155]
Hi there,

I have a suggestion about the quest journal.
Lately, I have been testing and trying to understand this plugin. When I had a look at the quest journal, I almost couldn't read the quest progress. I personally think the contrast between the background and the characters is too small.

My suggestion is to **change the colors of the quest progress in the quest journal to a darker color.**

Hope you can fix it!

**Comment by PikaMug** [comment]
Thanks for the suggestion. Could you please be specific about which colors you want changed, and which colors you think would be better replacements?

**Comment by Masterfixer06** [comment]
Hi there,

I specificly mean lime green, aqua, yellow and pink (&a, &b, &d, &e).
I would replace them with darker colours such as dark blue, dark green, gold, etc. I think it doesn't really matter which color you pick, as long as it is no light color.
I'd replace the lime green with either dark green or dark blue.

**Comment by Xekt** [comment]
Maybe if it's possible to customize the looks of Quest Journal within the config or some other file if that's possible, that could be cool.

**Comment by PikaMug** [comment]
It occurs to be that not everyone is using the default texture pack, so using darker colors may be a hindrance to some. In contrast, those with lighter packs or less sensitive eyes would benefit from making this configurable.

However, for stage objectives, Quests sometimes relies on GREEN and GRAY to differentiate between completed and uncompleted tasks (as a result of poor legacy design). It is for this reason that I'm unwilling to fully commit to such a change at this time.

That said, I will be changing the few instances of AQUA and LIGHT_PURPLE (pink) to use DARK_AQUA instead, as it functions as a middle-ground between the other two shades of blue. It is my understanding this will also better assist those with some forms of colorblindness.
