### ISSUE TITLE
Quests is not supporting white colored name of item

### ISSUE THREAD

**Issue by Katalijst** [PikaMug/Quests#1158]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.9.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Make an item with a custom name and make the name white and not italic anymore with `&f`, add it as a reward.
When you get it at the end of the quest, the name is in italic like it had no color code.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
I can't since it will register the name without the color code.

**Comment by PikaMug** [comment]
Try switching the order of the codes.

**Comment by Katalijst** [comment]
What do you mean exactly ? This happen when you set an item from hand as reward. I have custom items an they need &f at the start of their names to have it appears not italic.
But then when I add them as reward and check the code of the quests file, it registered the name without &f. I can't change the order of anything in my case.

**Comment by PikaMug** [comment]
Quests uses a Bukkit implementation to save items, and the way they do it, the leading color of white is not saved to file. You can trick it by using a different color code ahead of the one you need. For example, changing `&fMyCustomName` to `&a&fMyCustomName` will ultimately give you a white-colored name which is not italicized.
