### ISSUE TITLE
Location quests don't work

### ISSUE THREAD

**Issue by DarkAnxiety** [PikaMug/Quests#1159]
**What is your Quests version / build number (do _not_ say "latest")?**
  3.9.1-b86

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
  So, I have a quest where first you get some information in tekst (wich always works) and after that I have stages where you have to go to different locations. So when I am OPped and i go to the locations it tells me to go to the next location but when i deOP myself and I go to the location nothing happens.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
   https://pastebin.com/feweS6D0

**Comment by PikaMug** [comment]
Unable to replicate. I removed OP status and completed a location objective just fine:

![location](https://user-images.githubusercontent.com/2267126/78332657-6d52c680-7556-11ea-97fe-08dee38c5249.png)

It's most likely that some other plugin is altering your PlayerMoveEvent when not OP. Try removing all non-essential plugins temporarily, then add them back one-by-one to find the conflict.
