### ISSUE TITLE
NULL Override Messages

### ISSUE THREAD

**Issue by Xekt** [PikaMug/Quests#1160]
**Quest Version:** 3.9.1-b81

**Description of Problem:** When trying to edit any sort of override message (objective override, rewards override, requirements message override, etc), a NULL message replaces what the normal statement should be. Also, it appears that if I try to "clear" what is in these override messages, nothing occurs. 

![Screen Shot 2020-04-02 at 12 10 44 PM](https://user-images.githubusercontent.com/30645246/78278614-ea8d2580-74db-11ea-99fa-9d2daa4feaac.png)

This was not an issue I had before on previous versions so I am assuming it is a bug and have made this report.

Thank you!

**Comment by PikaMug** [comment]
Thanks for the report. Have you tried regenerating your language file (or entire /lang folder)?

**Comment by Xekt** [comment]
I just tried regenerating the language file and it appears to still show up. Is there another fix I could try?

**Comment by Xekt** [comment]
Was there a fix added for this? I saw this was closed so just curious

**Comment by PikaMug** [comment]
@Xekt Use https://ci.codemc.io/job/PikaMug/job/Quests/87/
