### ISSUE TITLE
Player Cooldown Innaccurate

### ISSUE THREAD

**Issue by Xekt** [PikaMug/Quests#1161]
**Quest Version:** 3.9.1-b86

**Description of Problem:** The value being set for the player cooldown within Planner for a Quest is not properly being read in.

![Screen Shot 2020-04-02 at 12 09 57 PM](https://user-images.githubusercontent.com/30645246/78278854-4788db80-74dc-11ea-983e-57f6d4a7a853.png)
![Screen Shot 2020-04-02 at 12 10 27 PM](https://user-images.githubusercontent.com/30645246/78278862-4a83cc00-74dc-11ea-9e63-64e3b8901908.png)

This is an issue that I have not found in previous versions, so I am assuming it is a bug. 

Thank you!

**Comment by PikaMug** [comment]
Thanks for the report. Any chance you could share the Fish Voucher quest for testing? Use a website like Pastebin or Hastebin to retain formatting.

**Comment by Xekt** [comment]
Of course!
Here is the paste bin of the Quest.
https://pastebin.com/c3ZqBCi9
Please do let me know if there is an issue I missed with the Quest or if this is a bug.

Thanks for looking into this!

**Comment by PikaMug** [comment]
Use https://ci.codemc.io/job/PikaMug/job/Quests/88/

May need to re-set the cooldown in-game.
