### ISSUE TITLE
Not generating the language files anymore

### ISSUE THREAD

**Issue by Katalijst** [PikaMug/Quests#1162]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.1-b86

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Make a new server, install the plugin Quests, and check if the language files were created.

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting

**Comment by Katalijst** [comment]
I did the troubleshooting, still it doesn't appear, despite the data and modules files being generated

**Comment by PikaMug** [comment]
@Katalijst In that case, try creating a the lang folder manually and downloading your language from https://github.com/PikaMug/Quests/tree/master/main/src/main/resources/lang

For French, path should look like /Quests/lang/fr-FR/strings.yml and in your config.yml, set `language: fr-FR`
