### ISSUE TITLE
Folders in GUI Item Display

### ISSUE THREAD

**Issue by Xekt** [PikaMug/Quests#1165]
**Feature Suggestion:** The feature I would like to request is essentially an update towards the GUI aspect of the Quest Plugin. As of now, it only allows for the admin to be able to turn the quest into a GUI Format where the player can right-click an NPC for example and a GUI opens up with all the quests that can be started from that NPC.

The feature I am requesting is to essentially allow folders within the GUI where a player could right-click an NPC and a GUI opens up showing, for example, the options "Easy", "Medium", or "Hard". These folders can be custom named from the admin creating the quests, and after doing this, the player may click the block that corresponds to, for example, "Easy", and any quests for that NPC that fall under the "Easy" tab will be opened up. 

**Usage:** 
Player right-clicks NPC -> GUI Opens Up showing Green Wool (Easy), Yellow Wool (Medium), Red Wool (Hard) -> Player left-clicks the Green Wool -> Any Quests that is set under the Easy Folder will be displayed.

**Comment by PikaMug** [comment]
Thanks for your suggestion. Going forward, any and all GUI-related enhancements will be address through the QuestsGUI plugin. If you would like to see this in a future update, feel free to request it in the plugin's discussion thread on SpigotMC.
