### ISSUE TITLE
Disable Compass

### ISSUE THREAD

**Issue by Tecnok** [PikaMug/Quests#1167]
Version Quests: 3.9.1
Version server: 1.15.2

Problem: no option to disable the compass (in previus versions this was an option). I have a problem with other plugin that use the compass and the message that show is from quests and I don't wana that.

**Comment by Tecnok** [comment]
Sorry, but that didn't work, I tried before create this issue:

Config: https://prnt.sc/rsu0q3
Plugin with conflict: https://prnt.sc/rsu0gy
Result: https://prnt.sc/rsu09v

**Comment by PikaMug** [comment]
@Tecnok My mistake, I forgot that setting was removed in 3.9.0. You must instead remove the `quests.compass` permission. With most permission plugins, this would be done with a dash in front, so give `-quests.compass` to any ranks you don't want to have the ability.

**Comment by Tecnok** [comment]
Thanks, with the permision in false now the compass don't work.
