### ISSUE TITLE
Clear Overrides Not Working

### ISSUE THREAD

**Issue by Xekt** [PikaMug/Quests#1168]
**Quests Version:** 3.9.2-b88

**Problem:** If I set any sort of override message (whether that be for requirements, rewards, objectives, etc), if I try to type "clear", nothing actually gets cleared and all overrides previously set remain.

**Example of Quest (Pastebin):** https://pastebin.com/K9QMeggx

Thank you!

**Comment by Xekt** [comment]
So I updated to the new version, but it appears now instead of "clear" not doing anything, it adds "clear" to the list of rewards, objectives, etc of whatever override I am doing.

![Screen Shot 2020-04-05 at 10 19 21 PM](https://user-images.githubusercontent.com/30645246/78520263-91e3b400-778b-11ea-8cd1-b1dad09a445b.png)

This was my testing it out. I am on Quests version 3.9.2-b89.

**Comment by PikaMug** [comment]
@Xekt Use https://ci.codemc.io/job/PikaMug/job/Quests/92/
