### ISSUE TITLE
Reward Override Not Displaying 

### ISSUE THREAD

**Issue by Xekt** [PikaMug/Quests#1169]
**Quests Version:** 3.9.2-b88

**Problem:** After setting a reward override, it appears that it does not display properly. A screenshot has been provided as well as a Pastebin for the quest that shows both what I have set as the reward and what the output appears to be.

<img width="540" alt="Screen Shot 2020-04-03 at 5 31 55 PM" src="https://user-images.githubusercontent.com/30645246/78410116-15a57100-75d1-11ea-8834-ff5b07f29de6.png">

<img width="653" alt="Screen Shot 2020-04-03 at 5 33 29 PM" src="https://user-images.githubusercontent.com/30645246/78410214-50a7a480-75d1-11ea-9278-2ff91d332e64.png">

**Example of Quest (Pastebin):** https://pastebin.com/K9QMeggx

Thank you!

**Comment by PikaMug** [comment]
Worked fine for me, at least on the latest dev build.

![fishrew](https://user-images.githubusercontent.com/2267126/78419837-8e2f2080-7617-11ea-9acc-3ebd91c2eb9f.png)

Try https://ci.codemc.io/job/PikaMug/job/Quests/89/
