### ISSUE TITLE
Mythic Mobs Integration

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1171]
**What does your feature do?**
While BOSS is a good plugin for making basic bosses, Mythic Mobs far surpasses any other boss plugin in customization and abilities you can make, BOSS is nowhere close to the possibilities that we can do with Mythic Mobs. So just a custom objective named Mythic Kill Boss or something of that nature.

**How would people use it?**
Kill Mythic mob objective

**Comment by PikaMug** [comment]
https://www.spigotmc.org/resources/mythicmobs-%E2%9A%94-quests-add-on-%E2%9A%94.7261/
