### ISSUE TITLE
 I have a problem with the translation of blocks in the missions, I would like the items to be read in Spanish from the mission book. for example the Stone is taken from the minecraft system and is in English.

### ISSUE THREAD

**Issue by OsteRM** [PikaMug/Quests#1177]
**Where else have you looked for answers to this question?**

**Share your question with as much detail as possible?**

**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
Thanks for your question. Unfortunately, this isn't possible as translations can only occur in client-side chat. Books cannot be supported at this time.
