### ISSUE TITLE
Delete unfinished quest after saving

### ISSUE THREAD

**Issue by coolcat93** [PikaMug/Quests#1178]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.1
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
My quests are deleted even after saving them. When I try to save the quests and come back to them later they are no longer there.

Make a quest but have it uncompleted (saving it for later editing)
save it,
try to reload the plugin to view the quest
Quest does not show up under the list.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Unable to replicate. Please share the specific steps you took to cause this behavior.

**Comment by coolcat93** [comment]
https://youtu.be/w0C53G0pkGw

Here is the exact thing my Quest Creator did. They save the quest that has multiple stages, do /questadmin reload, and then it does not show up under the list or let them edit it.

**Comment by PikaMug** [comment]
@coolcat93 Thanks for the detailed steps.

Issue stems from how Quests loads two-worded wool dye colors ("Light Blue", "Light Gray", et al.). Please give the following development build a try: https://ci.codemc.io/job/PikaMug/job/Quests/93/

**Comment by coolcat93** [comment]
will do, thank you
