### ISSUE TITLE
Quests loading/reading asynchronously 

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1179]
**What does your feature do?**
This feature would just be a change from the original Bukkit configuration tools to a asynchronous reader, honestly though the best way to do this would be to be able to store the quests in a MySQL server and have them called from and loaded when needed rather than all of it loaded in RAM. MySQL also offers a lot more possibilities such as Multi-Server Quest synchronization and it just far more efficient to load what you need rather than loading everything in ram, as my question before asked about quest generation and having huge quantities of quests is not really viable in a bukkit config format as it would have to load possibly multi-gigabyte files constantly, MySQL integration can make this extremely simple though as you can store them on it instead, and we can also no longer have to do /questadmin reload to load the new quests therefore increasing stability, also making it a live edit plugin, meaning we can actually have people editing and creating quests whilst we also have possibly hundreds or thousands of players playing them. I really want this feature specifically because I love quests, and while it is great, I would also love to just make a copy of my server and get rid of all the maps and everything and simply just have a editing server where all the NPC's and things of that nature are close together so that my admins and quest editors don't have to fly around 2000+ block maps constantly to make a single quest. It would drastically speed up how fast we can make quests, and how many quests we can make.

Also a really good work around to deal with NPC's ID's synchronizing would simply be to give the ability to give a "Alias ID" So lets say for example we have 3 different servers and 3 of the "same" NPC's so what you could do is set a "Alias ID" for the NPC where it can refer to the NPC regardless of server or ID.

For example it could be stored like this:

Server1:
 NPC-ID:
  - 274
  Alias: 255
Server2:
 NPC-ID:
  - 245
  Alias: 255
Server3:
 NPC-ID:
  - 173
  Alias: 255

Now in this example there are 3 NPC's on 3 different servers that each have different ID's (274, 245, 173)... But now if we make a quest we use the ALIAS, meaning we would use 255 as the NPC ID, and that would then handle synchronizing it between multiple servers, because for each server it would look at the Alias, then find the actual ID, for example if we looked at Server1, it would lookup Alias 255, then find Server1, then it would see the actual ingame ID and use that!

Also for locations you can follow the same methodology, giving a Alias usage so that if a player has to reach X location there are aliases for each of those.

This is obviously a very large undertaking on your behalf, however I think it would dramatically increase this plugin from being a simple replacement for like askyblock challenges, to making it a feasible tool to use as a full core gamemode, as of right now this plugin does not have the ability to have thousands or hundreds of thousands of quests as we have tested with a procedural generator to make quests, when we push past the several thousand mark, it literally takes up multiple gigabytes of ram, and crashes when you try to reload the server simply because it is IMPOSSIBLE to read 800,000+ Lines of config within a server tick (or even a few hundred server ticks) so the server just freezes and crashes from not having a tick within 60 seconds. MySQL not only solves this issue, it makes the plugin FAR more compatible with multiserver setups, and makes this plugin essentially infinitely scalable, this would majorly benefit everyone using this plugin, also that being said, you will probably also need to make another plugin to accompany this that would let people convert their MASSIVE configs and massive amount of already made quests into the MySQL server, that way people don't have to throw away hundreds if not thousands of hours of work just to get these features!

**How would people use it?**
Explained above!

**Comment by Larskei-dev** [comment]
While other people have asked for MySQL integration I do hope this is not marked duplicate because I believe I have gone above and beyond any of those requests and submitted a actual path to a solution, and how to start doing cross server synchronization.

**Comment by PikaMug** [comment]
Thanks for the suggestion. I've looked into it and it seems loading through the Bukkit implementations is thread-safe despite some serialization. The same cannot be said for _saving_ configurations which, although not the purpose of this ticket, does appear as though it may be limited by how many characters a String can hold, which is 2147483647. This amounts to a roughly 4 GB maximum file size.

As such, while exploring alternative I/O options would be optimal, you said it yourself that MySQL would be the best way to do this. Even if Quests were able to support large files, concurrency would be a concern, especially if someone wanted to use the same file for multiple servers as you've outlined.

I've gone ahead and made _/questadmin reload_ run async (plugin enable is still sync because of a _getOnlinePlayers()_ call which may or may not be thread-safe). I'll leave the stress-testing to you. Feel free to bring up your points about MySQL in #312 as well as your alias idea.

Use https://ci.codemc.io/job/PikaMug/job/Quests/92/
