### ISSUE TITLE
Questing errors

### ISSUE THREAD

**Issue by coolcat93** [PikaMug/Quests#1180]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.1
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Plugin says that a quest is being created/edited when it is not being worked on.

Create a new quest
save the quest
do /questadmin reload
"Someone is creating/editing a quest with that name"
Console spits out this error:
ERROR Unable to load custom objectives because quest for custom33 was null

**Comment by coolcat93** [comment]
https://youtu.be/VRIYRsRe3HE here is the steps my Quest Creator did to replicate this error.

**Comment by PikaMug** [comment]
Side effect of #1178
