### ISSUE TITLE
Can't get stages to save

### ISSUE THREAD

**Issue by joshch26** [PikaMug/Quests#1183]
I looked around on the issues page but I can't seem to figure this one out. I'm trying to set a quest for people to kill a few mobs around spawn. I've set the mobs to be skeleton and zombie, and they need to kill 2 each. I can save the stage from that point, but I'd like to set a 500 block radius. Once I start add location parameters, the "7 - Done" no longer works.

Here's a few screenshots.

Adding the information.
<img width="1440" alt="Screen Shot 2020-04-07 at 5 07 29 PM" src="https://user-images.githubusercontent.com/63319729/78720014-ebb2be00-78f2-11ea-8a11-4ecd4163c817.png">

After I type 7 into the chat. It doesn't seem to save.
<img width="1440" alt="Screen Shot 2020-04-07 at 5 07 45 PM" src="https://user-images.githubusercontent.com/63319729/78720049-fcfbca80-78f2-11ea-95d5-3f1fb0764638.png">

Am I just crazy? Or is there something wrong? I'm using build # 92.

**Comment by Xekt** [comment]
You need a kill location, kill radii, and location name for each entry of Mob Type.

Ex.
Kill radii
- 500
- 500
Location names
- Spawn
- Spawn

Similar to how you did the 
- 2
- 2

for the number of mobs that need to be killed for each type.

**Comment by PikaMug** [comment]
@Xekt is correct.
