### ISSUE TITLE
Console spammed with error Could not pass event EntityDeathEvent to Quests v3.9.0-b84

### ISSUE THREAD

**Issue by Klawdek** [PikaMug/Quests#1184]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests version 3.9.0-b84
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The console is being spammed with the folloing error:  https://pastebin.com/Jxam1NY6
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
This is my quests.yml file: https://pastebin.com/EW3FFHZd

I know I am one version behind, however I am on 1.15.2 not a snapshot of 1.16 and the new version looks like it is for 1.16.  Otherwise how could it create worlds for 1.16?

**Comment by PikaMug** [comment]
Use latest development build https://ci.codemc.io/job/PikaMug/job/Quests/
