### ISSUE TITLE
Console error spam.

### ISSUE THREAD

**Issue by BlitzGamer-88** [PikaMug/Quests#1185]
Quests version: 3.9.2-b94
Server version: Paper-237(1.14.4)

So last time when I reported this I couldn't really tell if this is random or not. I still can't figure out the reason this is happening but sometimes I get  my console spammed by Quests.

So this is not happening every time and is fixed by a restart but then it starts again.
Basically whenever I do something it returns an error. Last time I said I was spammed only by this error: `Could not pass event PlayerMoveEvent to Quests v3.9.2-b94` and it happens whenever someone on the server moves but now I am also spammed by these: `Could not pass event BlockDamageEvent to Quests v3.9.2-b94` & `Could not pass event BlockBreakEvent to Quests v3.9.2-b94`. The last two happen when players break or "damage" the block.

These are also some errors I get in the console:
https://paste.helpch.at/yitisuqaho.apache

**Comment by PikaMug** [comment]
@BlitzGamer-88 Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/96/

**Comment by BlitzGamer-88** [comment]
I really wish I could say it fixes it but it didn't. Also I forgot to mention that quests don't work at all whenever this starts. Also after I changed the jar and restarted the server the error occurred immediately.

**Comment by PikaMug** [comment]
@BlitzGamer-88 Thanks for the response. Please provide the first Quests error that appears in the console to re-open this issue.

**Comment by BlitzGamer-88** [comment]
So I restarted the server and checked the logs. First the plugin enables successfully but then I get this:
https://paste.helpch.at/mifevewiwe.cs
I don't think that should cause it but I said I would give that as well then there are no other errors until I moved: https://paste.helpch.at/okevutetik.sql
The second one appeared after I joined and logged in and moved. Then it just starts spamming this type of errors.

**Comment by PikaMug** [comment]
@BlitzGamer-88 That first group of messages is just telling you that there's new language phrases available since last version. You can ignore it, or update your /lang/* files to get rid of the warning.

Please give this build a try: https://ci.codemc.io/job/PikaMug/job/Quests/97/

If you need further assistance, just share the initial error for the new version again. Thanks!

**Comment by delbertina** [comment]
Not OP, but having the same issue so figured I'd jump in with the error I'm getting with the dev version linked. : )

[https://pastebin.com/nXKL7gJg](https://pastebin.com/nXKL7gJg)

**Comment by PikaMug** [comment]
@delbertina Doesn't seem related at first glace, but please try the following build and create a separate issue with the new console output.

https://ci.codemc.io/job/PikaMug/job/Quests/98/
