### ISSUE TITLE
Block-break does not work with ensemble of plugins

### ISSUE THREAD

**Issue by NChitty** [PikaMug/Quests#1186]
Version 3.8.8-b75

I am running a Prison Server and to reduce the grind for many levels I was trying to use quests to give players money for mining blocks. However, one or more of the plugins I have prevents the block-break from occurring and I was wondering if you had any ideas.

Here is the config if you need it: https://pastebin.com/WJWiWg4p

![plugins](https://user-images.githubusercontent.com/2151324/79028714-2caf0a80-7b5f-11ea-90d3-4023462b89c8.PNG)

**Comment by PikaMug** [comment]
Thanks for the report. As far as this project (and the Bukkit API) is concerned, a block is not truly broken unless it is removed from the map by a player’s hand. If a plugin has canceled the event, or is removing the block by unexpected means, then Quests has no business incrementing the objective. Consider finding which plugin is preventing the block from breaking and adjust its settings accordingly.
