### ISSUE TITLE
Quest GUI Icons being handed to players by NPCs

### ISSUE THREAD

**Issue by SimonKertonegoro** [PikaMug/Quests#1187]
**What is your Quests version/build number (do _not_ say "latest")? 3.9.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_? 
The quest plugin is incompatible with the new versions of Denizen. 

It creates an error when starting quests using the GUI served by an NPC. 

If the player presses the Q key, the NPC basically hands them the GUI item with customized Name, Lore, and metadata

**Comment by PikaMug** [comment]
Unable to replicate. While hovering over an item and pressing 'Q' does start the quest, it doesn't drop anything, at least no for me.

Do you perhaps have another plugin installed which might modify this event?

**Comment by Yukitty** [comment]
> Unable to replicate.

**Comment by Yukitty** [comment]
> Unable to replicate.
You need to specifically have the quest start by running a Denizen task in the most recent versions of Denizen (every release above #1702 on https://ci.citizensnpcs.co/job/Denizen)

**Comment by PikaMug** [comment]
@Yukitty Thanks for the explanation. Issue appears to stem from DenizenScript/Denizen-Core@a9995132c2f8e9d16c3b473247b32a8e68a8df45 which is seemingly included in the Denizen 1.13 release on SpigotMC. It's not immediately clear to me where runTaskScript(ScriptEntryData, Map) was moved to, so I'll check with the developer and come back to this.
