### ISSUE TITLE
Console errors with PlayerMoveEvent and PlayerJoinEvent

### ISSUE THREAD

**Issue by delbertina** [PikaMug/Quests#1191]
**What is your Quests version / build number (do _not_ say "latest")?**
Jenkins build # 98

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When some players join who have active quests it starts spewing these errors.
[https://pastebin.com/4rVLT5Zn](https://pastebin.com/4rVLT5Zn)
At some point the errors change to this one.
[https://pastebin.com/xLTdeqz0](https://pastebin.com/xLTdeqz0)
I'm not sure if it's the same issue, but the quest book and ./quest also have errors for the player when these errors are going. The errors do stop when the player quits all the quests.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
I have 10 quests each with 13 locations to reach. Here's one of them. The rest are exactly the same except the color and the coords are changed. [https://pastebin.com/KRULvQqU](https://pastebin.com/KRULvQqU)

**Comment by PikaMug** [comment]
Thanks for the report. Could you please provide your quest with an ID of `custom15`? That one appears to be causing the majority of errors.

**Comment by delbertina** [comment]
[Here's the custom15 quest.](https://pastebin.com/a7XjcV0S) That quest isnt part of the set players are currently doing, but it is the first quest in the quests file so idk if that has anything to do with it.

**Comment by TheDilPickle** [comment]
I made a similar quest where the players have to located heads for easter and it caused the same exact issues.  It is the player heads that are causing the bug.

**Comment by PikaMug** [comment]
@TheDilPickle OP is using player heads for the GUI display only, so I'm skeptical of that conclusion. However, I'm unable to replicate the issue with either quest; everything works fine for me.

@delbertina Would you please give this build a try and reply with your findings? https://ci.codemc.io/job/PikaMug/job/Quests/99/

**Comment by delbertina** [comment]
Am using playerheads for the things players are supposed to find.

Updated to build 99 and so far no errors, but [this happened when a player joined](https://pastebin.com/y8RnMzuL) with some active quests. Not sure if this is an issue, but report back if anymore errors or issues pop up.

**Comment by TheDilPickle** [comment]
I'm not sure what you did but we are no longer getting those insane errors when the locations are on heads etc.  Thank you so so much.  I used the build 99 that you gave.  It only showed one warn when a player joined but that was it and never happened again.

**Comment by delbertina** [comment]
[This error happened just now.](https://pastebin.com/MPYyN4UU)

**Comment by PikaMug** [comment]
@delbertina https://ci.codemc.io/job/PikaMug/job/Quests/101/

**Comment by Technodate** [comment]
Getting playermoveevent errors and exceptions after using qa setstage: https://pastebin.com/HJdkvx5z

next stage works fine.

Errors start when using the setstage command on a quest that's longer than 1 word. (and if you type out it's full name.

qa setstage <player> mob 2 -> works
qa setstage <player> mob hunter 2 -> a lot of errors x.x
)
3.9.2-b94 and 3.9.3-b104 both give the errors after these events.
Does it for the starter quests too, not just the custom ones.

**Comment by PikaMug** [comment]
@Technodate Feel free to create a separate issue with an error from the latest development build.
