### ISSUE TITLE
Massive Error Spam During Location Based Quest

### ISSUE THREAD

**Issue by TheDilPickle** [PikaMug/Quests#1192]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.8
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When a player takes the quest and needs to find certain player heads it throws back these errors if they leave the server and then rejoin. The errors occur for every block a player moves. There was probably 1 million lines of error code that I omitted for that pastern.  https://pastebin.com/RHT93r2u   To fix this the quest needs to be forcefully quitted by an admin.  Then also get this error in chat if they try to do /q or the journal.  https://prnt.sc/ry3aea

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/76b2BUwT

**Comment by PikaMug** [comment]
Thanks for the report. Please try the following development build and report your findings in #1191
