### ISSUE TITLE
Bug / Error

### ISSUE THREAD

**Issue by KukiCrumblez** [PikaMug/Quests#1199]
Server Version 1.14.4

I keep getting this console error whenever I try to reload. I added an event with a sound effect then it suddenly bugged.

Console error: https://pastebin.com/QF8ZsRxX

**Comment by PikaMug** [comment]
This may be an issue with the editor, but changing `PORTALTRAVEL` to `PORTAL_TRAVEL` in your _quests.yml_ file should resolve the issue.

**Comment by PikaMug** [comment]
Use https://ci.codemc.io/job/PikaMug/job/Quests/101/
