### ISSUE TITLE
Villager Careers

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#1201]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.2-b94

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
In my case I made a kill quest where a player had to kill villagers, got an internal error when doing /quest in game as well.
![Screenshot 2020-04-15 at 11 07 48](https://user-images.githubusercontent.com/38226281/79320208-b6692a00-7f09-11ea-9313-420b74ba60ae.png)

https://pastebin.com/Xh8a378L (Console)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/xtG4CHwx

**Comment by Technodate** [comment]
Was just making a test quest btw, I'm not a monster.

**Comment by PikaMug** [comment]
Thanks for the report. Which version of Minecraft is your server running?

**Comment by Technodate** [comment]
1.12 spigot

**Comment by PikaMug** [comment]
@Technodate Sorry, I meant to ask which version of CraftBukkit/Spigot/Paper? For example:

`This server is running CraftBukkit version git-Spigot-947a8e7-3a91182 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
`

**Comment by Technodate** [comment]
`This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)`

**Comment by PikaMug** [comment]
@Technodate Thanks. This error has occurred because a Bukkit method to obtain a Villager's career wasn't added until later builds (possibly even 1.12.1 or 1.12.2). You could either update your server to newer 1.12 builds until you pass the cutoff version, or wait while I investigate whether a fix is feasible.
