### ISSUE TITLE
Either blocks broke of listed counts towards stage

### ISSUE THREAD

**Issue by CammB** [PikaMug/Quests#1206]
**Where else have you looked for answers to this question?**
Looked through closed issues and on forums without much luck. 

**Share your question with as much detail as possible?**
I'm wondering if it's possible or will be to list multiple blocks in a stage to be broken, and have one amount they all count to. 

For example. A lumberjack quest could require you to cut 64 of any log in the game since they're now separate id's

**If applicable, which class or method is this in reference to?**
Not too sure sorry,

**Comment by PikaMug** [comment]
Thanks for the question. Please see #789
