### ISSUE TITLE
Quests wont load in item requirements, letting people do every quest that has one for free... 

### ISSUE THREAD

**Issue by P-paj** [PikaMug/Quests#1207]
**3.9.3-b101**

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No errors, i add the items in quests editor as requirements, they are simply colored renamed normal items then do /questadmin reload (as well as trying a server restart) and they never loaded in

you cant see them as requirements in the quest editor menu, and players can access them for free.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
It happens on every quest with an item requirement to begin it (though all the items have colors added, if thats an issue somehow)

**Comment by P-paj** [comment]
Issue was discovered early this month but not reported till now, lotta players getting free quest stuff lol. So it likely is an issue back to 3.9.0 or earlier

**Comment by P-paj** [comment]
example quest, but it happens on all of em: https://pastebin.com/BZXVZJxL

**Comment by PikaMug** [comment]
Use https://ci.codemc.io/job/PikaMug/job/Quests/103/
