### ISSUE TITLE
More stacktrace

### ISSUE THREAD

**Issue by supertakeru** [PikaMug/Quests#1208]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v3.9.3-b101
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Stacktrace
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/rwDdZyUm

**Comment by PikaMug** [comment]
Duplicate of #1205
