### ISSUE TITLE
Always gets the last character of input

### ISSUE THREAD

**Issue by SauROnmiKE** [PikaMug/Quests#1209]
**What is your Quests version / build number (do _not_ say "latest")?
- 3.9.2

**Describe the problem and how to replicate it.**
Just started using the plugin and tried creating my first quest. It seems that for everything I type, the plugin takes as an answer the last character I am using twice.
Steps to reproduce the problem:

1. Joined my server. No other command used other than /login from AuthMe to login.
2. Issued the /quests editor command.
3. Typed "1" to create a new quest.
4. Then I am asked to enter the quest's name, followed by the editor menu. I just continued.
5. I typed the name and then I got the editor menu twice, like I gave wrong input or something.
6. I then typed "2" to set the ask message.
7. I was asked to set the ask message, but it automatically set it to "2", like I entered it twice.
8. The same happens for every option, when sometimes I can't exit menus, forcing me to disconnect.

**If applicable, can you provide an example quest from quests.yml?**
Every quest.

I don't know if any additional information would help, or what other plugins I am using. I have not found the same issue in the repo (or at least I did not see it). Thank you for your time, have a nice day and stay safe.

**Comment by PikaMug** [comment]
Thanks for the report. I haven't been able to replicate this. Would you mind seeing if it still happens for you in the latest development build?

https://ci.codemc.io/job/PikaMug/job/Quests/103/

**Comment by SauROnmiKE** [comment]
I tested with the latest build but the issue persists. I even tested it with other mods on my server in case the problem was a hardware one from my side, but they are facing the same issue as well.

I made a small recording, maybe I did not accurately describe the problem? I don't know, I hope it will help you in some way: https://www.youtube.com/watch?v=pOf0pyHQEmM

**Comment by SauROnmiKE** [comment]
*UPDATE
This is caused by the server. I am using Magma, Forge/Paper hybrid and they have the same issue on other text-input plugins as well. I reported the issue to them. Sorry for the false issue. Stay safe!
