### ISSUE TITLE
Setstage throws errors for quests with longer names.

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#1211]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.3-b103

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Use the setstage command and for the <quest> use a quest with a name longer than 2 words, you must also input 2 or more words when executing the command.

qa give player mob hunter
qa setstage player mob 2
qa setstage player mob h 1
^ third command gives the first null error.
Every bit the player moves after the third command also throws errors in console.
then;
qa setstage player mob 1 <-- throws last error.
qa setstage player mob 1 <-- second time after that it does work.

https://pastebin.com/dVrnUUXr

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
The basic quests Quests comes with also have this issue.

**Comment by PikaMug** [comment]
Thanks for the report. Fixed in 17ee93d7e8df6983cab9da72ac0e89ab68b5a0f1
