### ISSUE TITLE
Crops count towards quests progress no matter it's durability/age stage.

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1213]
**What is your Quests version / build number (do _not_ say "latest")?**
https://ci.codemc.io/job/PikaMug/job/Quests/104/
Running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No console errors

In my case I made a block break quest for fully grown carrots, potatoes and crops. Which would have a durability value of 7.
I've defined them as that in the quest as well.

However you'll be able to break them and let it count towards the progress no matter what it's durability/age stage is at.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/7mcTRk0r

**Comment by PikaMug** [comment]
Forgive me, I got the impression in #1204 that you were saying crop/carrots/potatoes weren't being translated properly (like the mushrooms); not that the count is ignoring durability. I still appreciate you making a separate ticket, as it's not related to the mushrooms.

Will look into a solution.

**Comment by PikaMug** [comment]
Use https://ci.codemc.io/job/PikaMug/job/Quests/105/

**Comment by DateInJapanese** [comment]
It now doesn't count them at all.
Breaking crops, carrots or potatoes of any durability, 0-7 doesn't count any of them.

**Comment by DateInJapanese** [comment]
Using 3.9.3-b107, it doesn't count any of them now, no matter their durability stage.

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/110/

**Comment by DateInJapanese** [comment]
Yes! It works now, thanks!
