### ISSUE TITLE
Error about BlockBreakEvent

### ISSUE THREAD

**Issue by hexagon02** [PikaMug/Quests#1214]
**I got the latest build of Quests on Jenkins (#104)**

**I created on my server some easy quests that have as requirements events like block-breaking and item-crafting. When players try to break those blocks the console shows this error message (i'm sorry that it is reversed but i use multicraft, so line 26 is line 1) and it doesn't work.

https://pastebin.com/dg25ipPt

How can i solve it? Thank you very much

**Comment by PikaMug** [comment]
Thanks for the report. I need more information, so please try the following build and, once you're able to replicate the issue, reply with the new error. It should include a message stating "Error occurred while dispatching [objective-type] for [quest-name]" and, if so, please include the named quest from your _quests.yml_ file using Pastebin/Hastebin.

https://ci.codemc.io/job/PikaMug/job/Quests/105/

**Comment by hexagon02** [comment]
Thank you, I will let you know!

**Comment by hexagon02** [comment]
This is the new error.

https://pastebin.com/JzshbMvM

here is the quest "grano e barbabietole". I think that the issue happens when a player tries to do a quest that requires to have completed "grano e barbabietole"

https://pastebin.com/2wv4dYT6

here is the whole quests.yml:

https://pastebin.com/HeAH84ny

**Comment by PikaMug** [comment]
Much appreciated. Same process, but hopefully this one resolves the issue:
https://ci.codemc.io/job/PikaMug/job/Quests/106/

**Comment by hexagon02** [comment]
Thank you! It no longer shows the issue in the console, but when the player tries to complete the quest destroying wheat it doesn't count it
