### ISSUE TITLE
Delay issue

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#1216]
Hi! Previous issue: https://github.com/PikaMug/Quests/issues/1016

I did as you asked, then I completed the first stage and this is what I got https://imgur.com/a/uiHjSaK

**Comment by PikaMug** [comment]
Thanks for the report. Your previous issue was created over 5 months ago. Please check whether the issue still occurs with Quests 3.9.3 (latest version at time of writing).

**Comment by KsuKsuKsu** [comment]
It works correctly with latest version. Thank you!
