### ISSUE TITLE
Jobs Reborn

### ISSUE THREAD

**Issue by Bossbirdyman51** [PikaMug/Quests#1219]
**What does your feature do?**

**How would people use it?**
Hi,
Thx for your great jobs can you add jobs reborn reward experience for quests ? And take jobs requirements to take a quests example : If you have woodcutter lvl 5 you can take this quests thx for your help ^^

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#need-support-for-other-plugins
