### ISSUE TITLE
Questsxdungeonsxl

### ISSUE THREAD

**Issue by Cevillion** [PikaMug/Quests#1220]
**Where else have you looked for answers to this question?** Discord and asked developer of Dungeonsxl

**Share your question with as much detail as possible?** i tried added a quest with citizens, citizens work in the dungeons but the quest doesn’t show up.

**If applicable, which class or method is this in reference to?** I’m not sure

**Comment by PikaMug** [comment]
Hello, it sounds like this should be reported as a bug. Please open a new issue and choose the "Report a bug" option. Make sure to include your Quests, DungeonsXL and module versions, as well as any other relevant information. Thanks!
