### ISSUE TITLE
Placeholders error for quests before taking them

### ISSUE THREAD

**Issue by call911nowplz** [PikaMug/Quests#1221]
Ver 3.9.3

In the previous version, If i displayed a placeholder of a quest that isn't active for me, I get an empty line. That allowed me to use javascript to change that empty placeholder to whatever i want.
now it turns into Error. and i get this error on Console
https://pastebin.com/MY1iPJSt
it's a PAPI error yes, But this wasn't an issue with previous quests builds.

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/108/
