### ISSUE TITLE
Eating Objective for Quests.

### ISSUE THREAD

**Issue by TheCrazyCreepr** [PikaMug/Quests#1226]
Hey there, thank you for taking time to read this suggestion.

I would find it very helpful if you could add an objective to your quest plugin that counts the amount of food consumed.

People could use this feature for quests like "Eat 10 Apples", "Eat 10 Fish", etc.

Using Quests v3.9.1-b86 on a 1.8.8 Server.

Thank you for considering this suggestion,
TCC

**Comment by PikaMug** [comment]
Thanks for the suggestion. Please try https://ci.codemc.io/job/PikaMug/job/Quests/111/
