### ISSUE TITLE
Questsxdungeonsxl

### ISSUE THREAD

**Issue by Cevillion** [PikaMug/Quests#1227]
**What is your Quests version / build number (do _not_ say "latest")?**Quests 3.9.2 DungeonsXLquestsmodule 1.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** I’m trying to have a quest be put in the dungeons I’ve set the quest start with an npc but quests don’t show up when we test the dungeon out. 

**If applicable, can you provide an example quest from quests.yml _using pastebin.com** yes

**Comment by PikaMug** [comment]
Thanks for the report. Issues with that module should be opened at https://github.com/PikaMug/DungeonsXLQuestsModule/issues
