### ISSUE TITLE
error spammm

### ISSUE THREAD

**Issue by ducdzz61** [PikaMug/Quests#1228]
https://pastebin.com/vdezaveK pls help

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions (missing Quests version, description of problem, example quest, et al.). Feel free to provide the requested information to re-open this ticket.

**Comment by ducdzz61** [comment]
Quests 3.9.3, server version: paperspigot 1.12.2

**Comment by PikaMug** [comment]
@ducdzz61 Thanks for that information. What steps did you take to create this error? Do you have an example quest to share?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
