### ISSUE TITLE
Quest blocks do not work

### ISSUE THREAD

**Issue by HauserGrim** [PikaMug/Quests#1229]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.3
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Create quest
Add quest to quest blocks in requirements
Save quest
Reload plugin
Check again quest blocks in editor
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/112/
