### ISSUE TITLE
Citizens NPC Quest GUI Name Appearance Stuck on Original Name

### ISSUE THREAD

**Issue by fantaphantom** [PikaMug/Quests#1230]
Hello,

Whenever I set an item for the GUI of an NPC (for the quests gui) it always reverts the name to the quest name but in purple text. So for exmaple if I made a gui icon that has a name such as &6Burger  for the quest named "Pizza" it always changes the icons item name to Pizza in purple color

I'm still not sure if this is a bug or I'm doing something completely wrong but I really don't want the item icons for the Quest NPC GUI to have purple names and not be customization. It really makes it look kind of bad in the GUI

**Comment by PikaMug** [comment]
Each item gets its name from the quest itself; not the item's display name. You would need to add the color code to the start of applicable quest names.
