### ISSUE TITLE
[ERROR]: [Quests] This protocol does not support npc-effect: NOTE

### ISSUE THREAD

**Issue by garsh1** [PikaMug/Quests#1231]
My version of quests is 3.9.3. I get this error whenever I join in game after a server restart. I have all the default quests and I added one more quest. The error stops when there are no players in game. The plugin still works perfectly as far as I can tell but it is spamming my console and is rather annoying.

**Comment by PikaMug** [comment]
Thanks for the report. This has to do with the particle effect shown over a NPC's head when a quest is available (in this case, a Note particle). Although some particles are protocol-specific (meaning only for certain versions of Minecraft) the Note particle should work on all tested versions.

What is your Minecraft server version? Also, you can temporarily disable the "spamming" by setting `npc-effects.enabled: false` in your _config.yml_ file.

**Comment by garsh1** [comment]
My server version is 1.8.8, I do not see the npc-effect.enabled option in the properties but that might be because it is so old.

**Comment by PikaMug** [comment]
@garsh1 Thanks. Please try https://ci.codemc.io/job/PikaMug/job/Quests/113/
