### ISSUE TITLE
Collection objective (inventory checks)

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1236]
**What does your feature do?**
It's a stage objective different from the delivery stage.
It checks for items within the player inventory, without taking them out of the inventory, or having to interact with npcs.

The player must have the selected amount of items in their inventory at one time.
Collection quests do not remove selected items either.

It's commonly used in quests as a stage where the player has to collect certain items at places or from enemies, before having to use those items in a following quest or stage.

**How would people use it?**
Setting up quests using a collection objective allows the quest designer to guide the player more carefully and precise. It also allows the player to get the item in different ways shall the quest designer allow them to.
i.e. A player must collect 5 diamonds.
- A player can get them by mining 5 diamond ore without fortune
- Or 5< diamond ore with fortune
- A player can trade with other players to complete the quest
- A player can complete the stage via crates or loot boxes if they give them the item.
- etc.

Adding collection objectives like stated above will allow the quest designer to make quests more personalised to the player, as well as guide them better step by step without confusion.
Collection objectives like stated above also won't require any location objectives to be defined either. Which is good, because setting location objectives was a previous way of making a collection quest, though it prevented a lot of options from being possible, mainly the ones stated above.

**Comment by PikaMug** [comment]
It sounds like you want a "while holding X items" condition, which is already planned as part of https://github.com/PikaMug/Quests/projects/2

While I can see the transparency advantage of a Collection objective, if you want the player to keep the items, just set a Deliver 5 items objective and give them 5 diamonds as a Reward. This will allow them to obtain the 5 items however they like, but still keep them upon completion of the quest.

**Comment by DateInJapanese** [comment]
Well it was mainly so you wouldn't need a delivery stage, since those can be really unnecessary in a story sometimes.
It's a bit of the same of "while holding x items," but I do want to be able to set quests where the player would need more than 64 of a single item in 1 stage.
