### ISSUE TITLE
No quest start & finish message requirement

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1237]
**What does your feature do?**
It makes it so start and finish messages from starting and finishing the quest are not necessary.
Pretty much so they won't be required to be entered with any text anymore. And that quests can be made without having to enter anything there.

If because of the way the plugin is coded the entry of text is a must. It would at least be nice to be able to set a 'standard' message. So when noting is entered in the start or finish message, it uses the standard message.

**How would people use it?**
When not knowing how to start a quest with text or how to end it, it would speed up the process of designing the quest as well as releasing it to the public much faster.
Personally I know how to start a quest off with a question, but ending it is often difficult and time taking for me. It takes way more time than I'd like it to, so not having it be required would speed up the process by a lot. Making it so much more time efficient.

It would especially help when just trying out objectives or making test quests.
You might think it's only a few seconds of time saving, but it adds up really quickly.

**Comment by PikaMug** [comment]
Yes, I've also been thinking that start/finish messages should have a pre-populated, default message. Not sure what those messages should _be_ exactly (other than that they should be short in length), and also whether or not they should be pre-translated into the selected language. Feel free to make suggestions below.

**Comment by DateInJapanese** [comment]
Would that mean that having them completely empty would not be possible?

Start:
Want to start a new quest?
Are you sure you want to start a new quest?
Do you want to start a new quest?
Do you want to start this quest?
Ready to start a new quest?
Start a new quest?
Start quest?
^ They're all alike, but that's what a standard message would be.

Finish:
You've finished the quest.
Quest completed.
Quest finished.

They can always be refined or changed later, and people would be able to change them themselves as well when added.
And you could have them be pre-translated, shorter length messages should do a better job there as grammar should be less of a worry.

**Comment by PikaMug** [comment]
As far as I know, it's already not possible to have them completely empty, but I'll consider that possibility.

The only suggestion I take issue with is "Start quest?" as that's too similar to the "Accept quest?" message that players also get if `ask-confirmation: true` is set in _config.yml_ (which it is by default). Everything else looks like a good candidate. I'll keep this open for a bit in-case others care to make suggestions.

**Comment by PikaMug** [comment]
Feels like two months has been a reasonable amount of wait time.

It occurred to me that the ask-message is referred to as the quest _description_ internally, because some users may choose not to have an NPC "ask" the player. As such, the message had to actually be something that could be understood as both a request or a description. Ultimately, I went with "Challenge objectives with haste!" paired with "You have finished all objectives." for the finish-message.

Open to further discussion before the next release.

**Comment by PikaMug** [comment]
As of 3ac36aeeed9f55896c4b11ccccfa309b4dcf3575 I removed the "with haste" part, as that could be confused with requiring a Potion of Haste. Also, the finish message seemed redundant as it appears _after_ the "QUEST COMPLETE" message, so it is now simply "Thank you!"

**Comment by DateInJapanese** [comment]
Perhaps "Well done!" or something similar would work better than "Thank you!"
As "Well done" fits more universally, complimenting the player on their performance. While "Thank you" would indicate that another person or a npc is speaking to the player, but not everyone has every quest linked to a npc.

**Comment by PikaMug** [comment]
@DateInJapanese Agreed. Well done!
