### ISSUE TITLE
Add brown and red mooshrooms to "milk cows"

### ISSUE THREAD

**Issue by SNoided** [PikaMug/Quests#1241]
Being able to choose which cows to milk

1) Cow
2) Mooshroom
3) Brown Mooshroom (When a flower is fed to it, you can milk out suspicious stew with the effects of the flower you fed it)

Putting how many times you need to milk the cows chosen, separated by a comma

e.g.

Mobs : Mooshroom, Cow
Milking?: 5, 4

**Comment by PikaMug** [comment]
Current behavior is dictated by the [PlayerBucketFillEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerBucketFillEvent.html), which does not trigger when using a Bowl. I'm not sure which event would be used when milking a Mooshroom, but if you're able to find that out, I'd be glad to consider adding it.

**Comment by SNoided** [comment]
Maybe this can jelp? Not sure https://github.com/ZtechNetwork/MCBVanillaBehaviorPack/blob/e1678f2301dfa920033b7494ad79d089eb188b91/entities/mooshroom.json

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerInteractAtEntityEvent.html

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/Event.Result.html

**Comment by PikaMug** [comment]
PlayerInteractAtEntityEvent is a possible candidate, but I'm not certain of how I would check whether the milking event was successful other than checking the item in the player's hand 1 tick later, which isn't super desirable. Unfortunately, the other two links are not related.

I may end up posing this question on the forums myself. Thanks for your effort thus far.

**Comment by PikaMug** [comment]
I've looked into it and it seems the aforementioned event is the only viable option. However, given the niche this fills, and the need to differentiate between Red and Brown Mooshrooms (the latter of which are only available in MC 1.14+), I think this would be best left to a module.
