### ISSUE TITLE
"Kill Mythicmobs Objective" Not working in modern MythicMobs versions.

### ISSUE THREAD

**Issue by P-paj** [PikaMug/Quests#1243]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.3-b107
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I've reached out to mythicmob devs as well - But after trying their Free version, Premium version, and Dev versions, ive found they all have lost quests support - so i suspect they've changed something and quests hasn't kept up. 

About half of the quests on my server aren't working because we use mythicmobs - on any modern MythicMobs version out in the last month.

I can't even access the "kill mythic mobs" custom objective - on the stage planner.

No errors in console btw

yeah the oldest available download on the mythicmobs site (they dont keep a full backlog of every build like a jenkins) is still having this issue - i legit cant downgrade to fix without going way back to a super old version =(

**Comment by PikaMug** [comment]
Thanks for the report. Quests does not need to be "kept up" as it is MythicMobs that depends on the Quests API. I will attempt to assist you in this matter, but be advised that, unless this proves to be an issue with the API, I will likely be directing you back to their team.

What are the exact MythicMobs and MythicMobsQuestModule versions that you're using?

**Comment by P-paj** [comment]
Thank you pika! I wasnt aware you could even update your mythicmobsquesmodule. But i just did to 
brand new version: 391 and issue is still persisting. mythicmobs 4.9.0 and 4.9.1

**Comment by PikaMug** [comment]
> your mythicmobsquesmodule

I do need to stress again that it's not my module, but from the author(s) of MythicMobs. Since you've updated, does that mean you're on version 4.5.5 of the module?

**Comment by P-paj** [comment]
using the newest build from http://mc.hackerzlair.org:8080/job/MythicMobsQuests/ april 12. 391. 
what command to run to get version number?

**Comment by PikaMug** [comment]
That appears to be the latest version of 4.5.5, the "391" seemingly just refers to the minimum compatible version of Quests (3.9.1 and up). I created a basic quest with a Kill MythicMob objective and completed it just fine on a Minecraft 1.15.2 server:

![mythic](https://user-images.githubusercontent.com/2267126/80078308-b9bd7080-851c-11ea-9988-77aa8f7b693d.png)

Could you provide the exact quest you're using from your _quests.yml_ file? Use a website like Pastebin or Hastebin to retain formatting.

**Comment by P-paj** [comment]
Yeah im quite concerned. I've tried downgrading and the issue with compoleting the quests, or accessing the objective remain... >.< Thanks for your time.

https://pastebin.com/vxLincYt

**Comment by P-paj** [comment]
You're running 4.9.0 Mm?

**Comment by P-paj** [comment]
Also im running questsgui, no clue if thats causing the issue =)

**Comment by PikaMug** [comment]
Correct, I'm using MythicMobs 4.9.0 and Quests 3.9.3, as specified.

If your MM spawners have stopped working, that indicates an issue with your MM installation. Might I suggest backing up your _/plugins_ folder and then delete the _/MythicMobs_ folder to start fresh?
