### ISSUE TITLE
Permission checking objective

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1245]
**What does your feature do?**
It's a new stage, where the stage will check if the player has a certain permission.
If they do have a certain permission the stage will advance.
If not, a message could pop up in chat, but still advance once they get the permission.

**How would people use it?**
People would use it as a way to check if a player has achieved certain things on their server.
Maybe check if they have a rank, or just access to the quest in general.
This would allow people to make pay2play quests if they so wish, where they giver the player a taste of the quest line first.

It could be used to check mid-quest if a player has completed another quest, if the other quest gave the player a permission node.
While it can be achieved by items as well, items can be dropped, lost, and take up inventory space. Not always something you want. On top of that items can also glitch out, while permissions only have a true or false statement.

Permission checking can check if players have reached certain regions before, if those regions gave permissions on entry.
Making it so the player won't have to travel all the way back if they already unlocked that part of the world map.
Same with talking to npcs, if a player already found npcs before, they won't have to travel back again.

It has a lot of potential that could greatly change the possibility of what's achievable with Quests. Please consider adding it.

**Comment by PikaMug** [comment]
Currently, I hold no opinions on "pay2play" quests, but I can see a player being frustrated if they aren't able to finish a quest due to such restrictions, especially if the server does not allow quitting. The current permission _Requirement_ feels more appropriate, so that the quest cannot be started unless payment has been processed. Same goes for servers with crate keys - receiving only half the crate until one purchases the key feels acquisitive. A separate "preview" quest would be more appropriate if such a system is desired.

A condition for whether players are within a region is slated at #1083 so that's a non-issue, but I'm unsure what you mean about NPCs. Does Citizens offer per-entity interaction permissions (and does GCore, for manner of #1287)? Even if so, I feel like a region condition would take care of that so long as the NPC remains inside its boundaries.

Is there any other situation in which a permission Condition would be preferred over a Requirement?

**Comment by DateInJapanese** [comment]
#1083 asks for a different feature other than what I wanted to achieve with this request, though I will agree that I wasn't clear on that.
So basically what I had in mind, was WGExtraFlags, or a similar plugin that can activate commands, or give permissions etc. on region entry.
This makes it possible to track whether the player has been there before or not. Making it unnecessary to go back to the region for the quest, once its stage appears.
This would be useful for servers with bigger world maps, as well as multiword servers, to not only save time for players for having to travel back, but also to not have to go through loading times when entering other worlds.

I had the same thoughts about the npc interaction. To where the player won't have to go all the back, if they already talked to an npc before. While I wasn't thinking of the npc interaction specifically myself, I did think it would be nice to name, as it would be one of many possibilities that would become available with permission checking stages.

==

I'd say its main use would be for continuity within Quests.
-Imagine comparing the permission checking objective -vs- the item collection objective (not the delivery one).
Except for that you don't have to have anything on your inventory, instead it's a permission node. That's all really.
This way you won't need to keep the items on you at all times, which can help with the flow of completing quests.
Having the player finish them, getting a feeling of accomplishment, without being interrupted with having to look for items or such.

Another way it would help with continuity, is that you would -not- have to make a separate quest to instead check for permissions as a requirement.
Reason you wouldn't want to do that, is because it can be confusing, as to which quest follows up which. Though it might be possible to add numbers behind the quest, it's not the prettiest sight, and it doesn't do the job of actually finishing the quest if it has to use a requirement check to go on. Meaning that it wouldn't make sense either, that the player receives the message that they completed it.

This way it can maintain both the beauty of the features/objectives of the quest, the storyline, and the layout. Without being interrupted.

==

On top of that - since not all messages from Quests are customisable in a way where you could remove them while still making sense, I do believe a system/game feature as mentioned would be a good alternative to escaping those messages.
Which is why having the permission condition would not only add new possibilities for stages and layouts, but at the same time it would also help make the story writing easier, as well as fix some problems with the messages (if the messages are considered a problem when quest making).

**Comment by PikaMug** [comment]
Thanks for the detailed response! I noted this in the "To Do" tags, but I should've explained that this was no longer being considered for an objective, but as a [Condition](https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Condition-Editor), as objectives are "tangible" tasks for the player to compete.

My understanding is you want a way to give players a quest's rewards even if they never accepted the quest, but have completed its objectives regardless. While using permissions as temporary storage is a valid solution, I think it would be faster to cut out the middleman and run _/quests take <quest>_ upon entering the region.

I'm not sure I follow on the messages example. How would having a certain permission prevent a message from being shown?

**Comment by DateInJapanese** [comment]
I'd still want the player to have accepted the quest, or be given it.
But yes, it would make it possible for them to have already finished a stage/task before it was given.
While /quests take would work for region quests, -and not for the luck based ones, it would not only still display the messages, but it would often run the command multiple times, which would be unnecessary and spammy in the console.
I say that, because I've looked for quite some time, and couldn't find many, if any, plugins that run commands only on first entry.

On top of that, you'd need to have confirmation set to false in the config, so the player doesn't type yes/no when entering.
But if you were to force give the quest, it could give it to the player multiple times, even if they already finished it.

When mentioning the messages, I was talking about the quest- start, finish and reward messages, as well as the forced quest messages. As those messages wouldn't be shown, if you don't have to make an extra quest just to test for permissions.
