### ISSUE TITLE
Citizen/phatloots - quests link 

### ISSUE THREAD

**Issue by Necros909** [PikaMug/Quests#1246]
**What is your Quests version / build number (do _not_ say "latest")?**

3.9.3

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

https://pastebin.com/Cm3gMNpF

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/aPde3AG5

**Comment by PikaMug** [comment]
Thanks for the report. Could you please provide your server startup log?

**Comment by Necros909** [comment]
https://pastebin.com/7T3xfdBk
Even tho at the end it says quests linked with citizens the npc still don't work

**Comment by PikaMug** [comment]
@Necros909 Please give this version a try: https://ci.codemc.io/job/PikaMug/job/Quests/114/
