### ISSUE TITLE
attempted to take quest "null" but something went wrong

### ISSUE THREAD

**Issue by chivivor** [PikaMug/Quests#1249]
When a player clicks to take a quest I see this in the logs

<player name> attempted to take quest "null" but something went wrong

Is this a permission issue? How do I fix it, works great for me as OP.

Thanks in advance

Mark

**Comment by chivivor** [comment]
Also it appears that some players it works and some it doesn't so not sure what to do here :(

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions (missing Quests version, example quest, et al.).
