### ISSUE TITLE
Does not register broken lillypads.

### ISSUE THREAD

**Issue by marvinej** [PikaMug/Quests#1250]
Version: Quests 3.9.3

we have a quest to collect lillypads and it does not register when you break them.

**Comment by PikaMug** [comment]
Thanks for the report. What do you mean by "collect" lillypads? Is this a break-block objective? Deliver-items objective?

**Comment by marvinej** [comment]
Yes break block

**Comment by PikaMug** [comment]
Working fine for me on the latest development build:

![lily](https://user-images.githubusercontent.com/2267126/80272059-2f981800-8694-11ea-880b-940ec9787fb2.png)

What is your MC server version? Do you have any protection plugins like WorldGuard installed that might be interfering? If you're using an anti-cheat or ViaVersion, try diabling those temporarily.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
