### ISSUE TITLE
Could not pass event PlayerJoinEvent to Quests v3.9.3-b107

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#1254]
Quests v3.9.3-b107

Hi! I have an error only for that user every time he's logining: https://pastebin.com/BSuLyhWx
And than crash: https://pastebin.com/3JX6BBhq

**Comment by PikaMug** [comment]
Duplicate of #1233 

Use latest development build https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by KsuKsuKsu** [comment]
Did not fix still :(
new log: https://pastebin.com/EmVCpxLA

And thay player said he can't take any quest. Other players can take quest and have not the same error before loggining.

**Comment by PikaMug** [comment]
@KsuKsuKsu Thanks for the followup. Please try https://ci.codemc.io/job/PikaMug/job/Quests/115/

**Comment by KsuKsuKsu** [comment]
He can take quest but it's still errors

That error for all players: https://pastebin.com/VhcDWmar
That error only for him: https://pastebin.com/46Kgy2XW

and new error for all players: https://pastebin.com/ZqChRxPS

**Comment by PikaMug** [comment]
@KsuKsuKsu The first "all players" error says you're still using build 114. Again, please try build 115 https://ci.codemc.io/job/PikaMug/job/Quests/115/

**Comment by KsuKsuKsu** [comment]
I don’t know how it happened. Forgive me please <3

Now i did it and i will report tomorrow
