### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by victoryne** [PikaMug/Quests#1255]
**Where else have you looked for answers to this question?** Github

**Share your question with as much detail as possible?** When we try to take a quests on a pnj, we have this message : "The quest may not be started via command." We have the latest release of plugin quests, our server is 1.13.2 with paper.

Thank you in advance for your answer.

**Comment by PikaMug** [comment]
Not sure what a "pnj" is, but make sure `allow-command-questing: true` is set in your _config.yml_ file.
