### ISSUE TITLE
Quests plugin breaks after player attempts to start a quest

### ISSUE THREAD

**Issue by SoraShiunin** [PikaMug/Quests#1256]
**What is your Quests version / build number (do _not_ say "latest")?**
Ver 3.9.3 / Minecraft 1.13.2
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
After a player attempts to start a quest. The whole plugin breaks
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
The error spamming console after a player attempts a quest: https://pastebin.com/wXNqN68A
The error when I attempt a quests reload:  https://pastebin.com/4p8Fe19t
The quests file: https://pastebin.com/t7F2UU1L

**Comment by PikaMug** [comment]
Thanks for the report. Is there more to the error? Looks as though it may have been cut off half-way.

**Comment by SoraShiunin** [comment]
https://pastebin.com/YbAgrmZx I think this is the whole error, then it starts looping.

**Comment by PikaMug** [comment]
@SoraShiunin Thanks for that information. It's hard to tell whether this is actually the fault of Quests, or some other plugin that's modified the PlayerMoveEvent. In any case, I've pushed a potential fix which you can try here: https://ci.codemc.io/job/PikaMug/job/Quests/115/

If you still get that error, try running your server with only Quests installed temporarily. If the issue goes away, then add plugins back until you find the conflict.

**Comment by SoraShiunin** [comment]
The fix din't work however I found the issue. It was permissions. I recently changed from PEX to LuckPerms and I just had to give quests.quests and etc permissions to the default group. With Pex it worked without giving the permissions so it never crossed my mind.
