### ISSUE TITLE
/quests list: Hide quests where the player does not have the requirement(s)

### ISSUE THREAD

**Issue by Yldales** [PikaMug/Quests#1257]
Hi,

**What does your feature do?**
Actually, when using /quests list, every quests loaded are displayed. This feature would allow to only show quests that a player can really take.

**Comment by PikaMug** [comment]
This is working as intended - the command is supposed to show all quests, not just those available. However, I will consider adding a way to specify a filter.

**Comment by Yldales** [comment]
Thanks for you response.

**Comment by Yldales** [comment]
Hi @PikaMug,

I've just found out that setting `ignore-locked-quests` to `true` does exactly what is described here.
Are they any downside setting this value to `true` ?

**Comment by PikaMug** [comment]
You're right, forgot about that! There should not be any other effects, to my knowledge.
