### ISSUE TITLE
Don't show ask message if requirements are not met. Introduce another NPC effect for unavailable quests

### ISSUE THREAD

**Issue by SauROnmiKE** [PikaMug/Quests#1259]
**What does your feature do?**
Instead of having a player answer Yes/No to a quest whose requirements are not yet met, immediately show the requirements message, that is set in the details list override option. Yes, I know that confirmation can be turned off, but it is necessary so that the player knows which quest to accept, but shouldn't go through reading all the quest intro, then type "Yes" just to see that he/she cannot accept that same quest.

Maybe also add a third NPC particle to signal the player of the unavailable quest(s)? Of course, this effect would appear third in place, in case the NPC has ONLY unavailable quests. Thanks for your time, stay safe!

**How would people use it?**
1.  Option in config.yml to immediately reject quests with unsatisfied conditions,  but without having to turn confirmation on/off.
2. Option to set an "unavailable-quest" NPC effect.

**Comment by james-d-elliott** [comment]
This would be useful for repeatable quests that have two versions, the main version which cannot be repeated with the main rewards, and the repeatable version with cut down rewards (with the main quest being the start requirement). In fact the option to hide the second quest would be nice.

**Comment by PikaMug** [comment]
Couldn't this be resolved by setting `ignore-locked-quests: true` in _config.yml_?

**Comment by PikaMug** [comment]
Regardless, this should effectively be resolved by the solution to #1361
