### ISSUE TITLE
Can't load actions that trigger effects

### ISSUE THREAD

**Issue by SauROnmiKE** [PikaMug/Quests#1261]
**What is your Quests version / build number**
3.9.3-b107

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I am trying to create a new action, where I need to open a fence gate when the player talks to the NPC, completing that specific stage. I enter the action editor, created a new one and pressed "4" to enter an effect. Then I entered FENCEGATETOGGLE and added the location, I saved and the plugin reloaded, generating this error: https://pastebin.com/2PsRb6vn

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Not applicable, did not apply action to quest yet. Here is the action though: https://pastebin.com/Rjm2SfMK

Thanks for your time, have a nice day!

**Comment by SauROnmiKE** [comment]
*UPDATE*
Okay this is a little embarrassing, but I just realized that the effects menu is referring to sound effects, so I guess this is why the plugin outputs that the gate's location is invalid? In this case, I'd like to suggest that maybe actions can really trigger effects such as doors opening, closing and similar actions?

**Comment by PikaMug** [comment]
Sorry for the confusion, but I'm glad you worked that out. I'm not certain fence gate toggles are something I'm interested in doing, as it's rather specific and multiple players triggering the action simultaneously could have unforeseen consequences. Maybe something like powering Redstone at the location would be more likely. Feel free to open a "Make a suggestion" ticket if you'd like to discuss this further.
