### ISSUE TITLE
Repeat Cycle Fix or Help

### ISSUE THREAD

**Issue by Bazzleberry** [PikaMug/Quests#1262]
Hi, I have been having a problem with the Quests Repeat Cycle. Whenever I want it to repeat I can't open it. The Repeat Cycle line is grey and it says (optional). Need help unlocking it or fixing it.
![Planner](https://user-images.githubusercontent.com/64435633/80409930-51112380-888f-11ea-8241-8e9a8cca011f.PNG)

**Comment by PikaMug** [comment]
You must set a start and end date first. For more information, see https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner
