### ISSUE TITLE
Error may not be started by a command

### ISSUE THREAD

**Issue by victoryneM** [PikaMug/Quests#1264]
**What is your Quests version / build number (do _not_ say "latest")?** 3.9.4 b110 server paper 629 mc 1.13.2

Proble is an error message when player wants to take a quest on a citizen : "the quest may not be started by a command"

I precise that we check in the config file and have allow-command-questing:true et allow-command-quests-with-npcs:true

Can you see to solve the problem ?

**Comment by PikaMug** [comment]
Thanks for the report. Do you have a quest to share from your _quests.yml_ file?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
