### ISSUE TITLE
Doesn't work with tlauncher

### ISSUE THREAD

**Issue by Obamzuro** [PikaMug/Quests#1265]
Hi, I can't import quests mod with any version of minecraft in tlauncher.
In latest versions of minecraft, I see an error message in latest.log:
[main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file Mod File: C:\Users\qwerty\AppData\Roaming\.minecraft\mods\Quests-3.9.3.jar is missing mods.toml file
[28???2020 11:36:00.513] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: File C:\Users\qwerty\AppData\Roaming\.minecraft\mods\Quests-3.9.3.jar has been ignored - it is invalid
And In < 1.12 versions mod just doesn't load.

For importing I use next article:
https://tlauncher.org/en/install-mods.html

**Comment by PikaMug** [comment]
Quests is a server plugin; not a mod.
