### ISSUE TITLE
From Version #114++ breaks my Quests

### ISSUE THREAD

**Issue by Andore97** [PikaMug/Quests#1266]
Server: paperspigot 1.8.8-R0.1
Quest Dev Version #114

https://pastebin.com/gdwmh0dm

**Comment by PikaMug** [comment]
mcMMO Classic has been removed or is disabled. Restore mcMMO Classic then, if desired, modify/delete quests which use it.

**Comment by Andore97** [comment]
"Restore mcMMO Classic then" ? what you mean with that

**Comment by PikaMug** [comment]
As in, re-install it.

**Comment by Andore97** [comment]
Using the latest 1.8 Jenkis Build of mcmmo Classic, Quests dont recognizes mcmmo anymore after the update to the latest Quest version. i temporary removed mcmmo reward from my Quests and the errors are gone but i need it.

**Comment by Andore97** [comment]
and this new errors come up if anyone hits a mythicmob monster or the monster hits player:
https://pastebin.com/qgiWZFkS
MythicMobs version 4.5.1-2584

**Comment by PikaMug** [comment]
If linking with mcMMO failed after removing the rewards, then there should be a separate error or warning in your server log. Feel free to open a new issue with that information if you'd like me to investigate.

I'm aware of the issue with the MythicMobs module - keep an eye out for a new release soon.
