### ISSUE TITLE
several questions

### ISSUE THREAD

**Issue by thedarkcookieez** [PikaMug/Quests#1267]
1)
The "Eichenholzzauntor" is the German translation but should be called "glasses for grandpa"
https://prnt.sc/s7h17v

2)
Can I edit the entire line in String.yml? ( -100 Cubeis)
https://prnt.sc/s7h2vq

3)
You can deactivate the delivery message if you don't need it, for example, you deliver 1 item

**Comment by PikaMug** [comment]
1. I do not understand your question.
2. There is a "money" string which you can try changing. If that doesn't work, you'll have to change it within Vault.
3. You must supply a delivery message. If you would prefer a blank line, you'd have to edit your _quests.yml_ file and replace the message with `" "`.

**Comment by thedarkcookieez** [comment]
1.
Oak fence is the item to be delivered.
Now the name of the item is displayed but not the one I assigned
