### ISSUE TITLE
"plugin is currently loading. Please try again later"

### ISSUE THREAD

**Issue by MythicCanadian** [PikaMug/Quests#1268]
Quests Version: 3.9.3
Spigot Version: 1.15.2

 I've been using the Quests plugin on my server for a while with no issues. But I updated it to the newest version yesterday (3.9.3), and now the "/quest" command or trying to use "/quests editor" both just return "plugin is currently loading. Please try again later". I've gotten rid of all modules, restarted multiple times, and even tried regenerating the config but it's still broken. Any help would be appreciated!

https://pastebin.com/4LkPrYFX

**Comment by MythicCanadian** [comment]
I've tried with the latest dev build of Quests too and I get the same error.

https://pastebin.com/73Y3wwNJ

**Comment by PikaMug** [comment]
Thanks for the report. Issue has to do with one of your quests which has stage using a Command Action. Please try the following development build, which should at least give an indication of _which_ quest is causing trouble:

https://ci.codemc.io/job/PikaMug/job/Quests/117/

Note that if you're using QuestsGUI, the current version may not be compatible with this build.
