### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant me.blackvein.quests.particle.PreBuiltParticle.ANGRY_VILLAGER

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1269]
Quests-3.9.4#117

![image](https://user-images.githubusercontent.com/61608872/80552384-0ca19700-89f9-11ea-98ce-b2e80103bac9.png)

Error log
https://pastebin.com/H4Erpaci

**Comment by PikaMug** [comment]
In your _config.yml_ change "angry_villager" to "villager_angry"

**Comment by hkkongou** [comment]
> In your _config.yml_ change "angry_villager" to "villager_angry"
Problem still exist
![image](https://user-images.githubusercontent.com/61608872/80565341-cd883b80-8a22-11ea-9cd8-2b63955b6c31.png)

![image](https://user-images.githubusercontent.com/61608872/80565364-d711a380-8a22-11ea-8755-1da6ad780255.png)
in order to stop this continue to have error message , i disabled the npc-effects
It do stop showing errors.
But the problem still exist right?

**Comment by PikaMug** [comment]
@hkkongou Thanks for the followup. Please re-enable npc-effects and try the following build:
https://ci.codemc.io/job/PikaMug/job/Quests/118/

Note that if you're using QuestsGUI, the current version may not be compatible with that build.
