### ISSUE TITLE
Repeat Cycle Help

### ISSUE THREAD

**Issue by Bazzleberry** [PikaMug/Quests#1270]
Hello. I have a question about the planner section. I have set up repeatable quests but I am not sure if it is bugged or if maybe im doing it wrong.

I set a start time, end time, repeat cycle time, ect. And when I click the npc a message says “quest will be activated in ___ seconds” but when it reaches that time it just resets the timer completely and no quest is available.

I wont appreciate the help and if you need more info id gladly give it. Thank you

**Comment by PikaMug** [comment]
Need to see what values you've set. Either copy/paste from _quests.yml_ or take a screenshot of the editor in-game.

Also, see https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner

**Comment by Bazzleberry** [comment]
planner:
      start: 28:3:2020:9:0:0:America/Toronto
      end: 28:3:2020:8:59:59:America/Toronto
      repeat: 86400
      cooldown: 32400

**Comment by Bazzleberry** [comment]
Its not just this quest but its for all of them (including the one on the wiki page for an example daily quest)

**Comment by PikaMug** [comment]
The start date is March 28th @ 9:00 AM
The end date is March 28th @ 8:59 AM

You can't have a quest end before it starts. Either set your start date earlier, or your end date later.

**Comment by SauROnmiKE** [comment]
If you don't want a quest to be available only on certain hours of the day, I just set the start date = now and the end date to year 9999, just with the cooldown I want (e.g. 120 seconds).
