### ISSUE TITLE
Can I change max amount from 64 to 100? 

### ISSUE THREAD

**Issue by Toffliz** [PikaMug/Quests#1271]
**Where else have you looked for answers to this question?**
Where everyone else puts issues! 

**Share your question with as much detail as possible?**
I am wondering if I can change the max amount of 64 to 100. Because i want a quest where you need to break 100 stone but i can't because the max amount is 64. Where do i change this? Is it possible to change? 

**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
No, because the max ItemStack limit is 64. Just add a second stack of 36 and, if you really need it to show up as 100, use a display override.
