### ISSUE TITLE
/quests list: Clickables quests.

### ISSUE THREAD

**Issue by Yldales** [PikaMug/Quests#1275]
Hi, 

A minor QoL suggestion, which would allow players to select a quest from the `/quests list` output directly by clicking on the quest's name inside their chat.

This can also be useful in the case where certain quests use color codes in their name (`&6Guide: &aEntering the Island`) and can only be taken using `/quests take`.

**Comment by PikaMug** [comment]
Spigot-only feature. Quests still supports Minecraft 1.7.10 (Bukkit-only) at this time.
