### ISSUE TITLE
Disable message

### ISSUE THREAD

**Issue by SladeHazard** [PikaMug/Quests#1276]
Uh is there any way to disable quest finish-message? i tried setting it to '' please help I don't want an extra message there are already so many messages player receives after finishing!

**Comment by PikaMug** [comment]
No. Both the start and finish messages are required to solidify that the fact that it's a _quest_ and not just some mundane task - there must be a story element. However, you might be able to show a blank line instead by manually changing the message to `" "` in your quests.yml file (not that this is recommended).
