### ISSUE TITLE
Still Quests got reset

### ISSUE THREAD

**Issue by Andore97** [PikaMug/Quests#1277]
next time dont close it!
https://github.com/PikaMug/Quests/issues/1266
A very active players quests got again Reset, Quest points are still there but the 
completed Quests and active again gone!

**Comment by PikaMug** [comment]
Your previous ticket was closed because the original issue had been resolved. If you are having a subsequent issue, you must still adhere to the template. Please provide your Quests version and a detailed description (any console errors, what was your player doing when it happened).

**Comment by Alexz1008** [comment]
For what it's worth I'm having the same issue, I will make a template post in just a moment, just glad someone else is having the same issue as me haha

**Comment by Andore97** [comment]
@PikaMug WHEN comes the MySQL Support?? Flatfile saving is so unefficent.

**Comment by PikaMug** [comment]
@Alexz1008 Please see my recommendation in your issue.

@Andore97 See #312 as that question is unrelated. Reply with the requested information or this ticket will be closed.

**Comment by Andore97** [comment]
Quests version 3.9.4-b118
 git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

No Errors currently. idk how to that players Quests got reset.

**Comment by arturek1666** [comment]
Looks like this issue is not fixed yet, as it's not closed, but I also had reset issues every time server stops, this is annoying as f...
Did not tested the new update with 1.16 maybe that fix it, but if this post wasn't closed I guess it did not got fixed.

**Comment by PikaMug** [comment]
I've been trying to replicate this without luck. It'd be useful if I had more information - how did the server stop, how many players online, which quests were affected, what other information is left in the file, etc.

**Comment by PikaMug** [comment]
Although I was never able to replicate this, Quests 4.0.0-rc.1 contains a number of bug fixes which should hopefully alleviate this issue. Feel free to provide new information below if this proves not to be the case.
