### ISSUE TITLE
Id problem

### ISSUE THREAD

**Issue by Manu5656** [PikaMug/Quests#1278]
Colored blocks are not considered by the plugin, for example colored wool, colored concrete etc. How should these ids be written?

I am using Quests-3.9.3 version on a PaperSpigot 1.12.2 server

https://imgur.com/a/XK8Qiov

**Comment by PikaMug** [comment]
On versions of Minecraft pre-1.13, the color is determined by the durability, which you currently have set to `0`. Use the proper material name and then set a higher durability.
