### ISSUE TITLE
Problem with muted players.

### ISSUE THREAD

**Issue by FearOfBlu** [PikaMug/Quests#1279]
**Where else have you looked for answers to this question?**
I've checked the website and I can't seem to find a fix
**Share your question with as much detail as possible?**
If players are muted they cannot say yes/no in chat. This makes it so they can't start quests
**If applicable, which class or method is this in reference to?**
Quests, General

**Comment by FearOfBlu** [comment]
This is a massive problem for me as I don't want anyone to not be able to use this plugin.

**Comment by FearOfBlu** [comment]
Alright I found a fix for anyone with this problem just go into config and set ask-confirmation: false

**Comment by PikaMug** [comment]
Although I understand this is not ideal, it is beyond my control. The Bukkit Conversation API (which Quests uses for all prompts) simply does not see the player's input if they are muted.

The best solution is the one you've found - disable the prompt entirely with that config setting. Thanks for using Quests!
