### ISSUE TITLE
Sometimes all of a player's quests are deleted, but quest points remain

### ISSUE THREAD

**Issue by Alexz1008** [PikaMug/Quests#1280]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.1 b86
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Every once in a while (I have a server centering around questing with hundreds of quests and maybe 60 people on at peak times and this is still infrequent enough that I only deal with it once every 2 days) a player will completely lose all of the quests they have, but retain their quest points.

(The below is not really necessary to read, but it may be a little useful)
It's extremely difficult to me to find out when it happens, because usually the people it happens to are people who have already completed all the quests and are wanting to try out some new ones but no longer have the quest requirements. However, I finally found a case that I could narrow down to the past 3 days, and I checked the logs and there's absolutely nothing. There are a few error logs of quests failing to load data but they are on completely unrelated players. Not a single related error log having to do with the player.

I rooted around in the code, specifically in Quester#getBaseData(), and I searched all the logs for "was null" so I could see if I could find any null references, but there weren't any. I'm afraid I have no idea how to help, and at best I can _maybe_ suggest that looking into every single interaction with completed quests may help you find the problem. This issue has existed for 2+ years, I really hope you guys can figure it out, and I'm glad to help how I can if it's possible.

**Comment by PikaMug** [comment]
There have been several significant fixes for loading data since 3.9.1, so I recommend upgrading to the latest version is recommended. If you still experience the issue after updating, I'll take a closer look, but as you say it'll be hard to narrow down without a lead.
