### ISSUE TITLE
PAPI placeholder not working in GUI

### ISSUE THREAD

**Issue by Derfavo** [PikaMug/Quests#1281]
Version 3.9.3

I Setup a Quest and used %Player_name% to get the playername. This is now working in the GUI where u get the Quests.

Quest example: https://pastebin.com/nxBQNkTx

**Comment by PikaMug** [comment]
Thanks for your report, but I don't understand the issue. Where is the placeholder "not working"?

**Comment by Derfavo** [comment]
https://gyazo.com/1053a4524c3f89e9e383bf0a77769687 Here is Screensgot.

**Comment by PikaMug** [comment]
@Derfavo Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/119/
