### ISSUE TITLE
Mythic Mobs

### ISSUE THREAD

**Issue by Derfavo** [PikaMug/Quests#1282]
**What does your feature do?**
Be able to spawn with the Actions tab a Mob from Mythic Mob.
**How would people use it?**
Create a new Mob Action set a Mythic Mob as spawnable creature.

**Comment by PikaMug** [comment]
Thanks for the suggestion. No external integration for Actions is planned at this time, but it's not an impossibility. I'll keep this on the back burner, but in the meantime, consider spawning the mobs via command.

**Comment by DeadlykillOfficial** [comment]
You can still use Command section to spawn mobs using actions using following format:
mm m spawn <mob><amount> <world>,<x>,<y>,<z>
Example: mm m spawn EliteZombie 1 test,0,5,0 
It will spawn MythicMob called EliteZombie in world "test" at coordinates 0,5,0
You can use EliteZombie:50 to spawn Level 50 Elite Zombie. If you are using leveling of mobs.
@Derfavo

**Comment by PikaMug** [comment]
Closing as integration with MythicMobs will be left to modules. Actions with other plugins will still be considered if proposed, but for spawning creatures please follow the suggestion by @DeadlykillOfficial for MythicMobs.
