### ISSUE TITLE
I don't know what this means

### ISSUE THREAD

**Issue by hypews2020** [PikaMug/Quests#1283]
**Where else have you looked for answers to this question?**
Google, other threads on spigot. 
**Share your question with as much detail as possible?**
I am creating a stage within a quest. I want players to kill certain npcs and then move onto the next stage. I have added all npcs with their id's but I get the message "All required lists must have the same number of entries!" I am unsure as to what this means.
**If applicable, which class or method is this in reference to?**
I dont know.

**Comment by PikaMug** [comment]
All lists must be the same size. For example, let's say you've added six NPC IDS. You also have to have six messages, six locations, or whatever else is required in that menu.

For basic questions which are not Java-related, I encourage you to join [the community Discord](https://discord.com/invite/d56CQ6e)
