### ISSUE TITLE
Error after complete quest - Talk NPC and permission reward

### ISSUE THREAD

**Issue by croderdai** [PikaMug/Quests#1284]
Quests version: 3.9.4-b118

Error after complete quest: https://pastebin.com/3nAZ53dx
and reward not work for me.
1 quest in quest.yml: https://pastebin.com/0X2dX3hE

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/119/
