### ISSUE TITLE
Acacia sapling doesn't exist.

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1285]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Put acacia sapling in your quest stage.
![Screenshot 2020-05-05 at 09 43 41](https://user-images.githubusercontent.com/38226281/81044748-335a4480-8eb5-11ea-8d64-3f64418eec66.png)
![Screenshot 2020-05-05 at 09 43 52](https://user-images.githubusercontent.com/38226281/81044751-348b7180-8eb5-11ea-9492-25eab34cc93a.png)

Also, the build version doesn't appear for me, tried reloading server too.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/xVv1JSjJ
Stage 3.

**Comment by PikaMug** [comment]
Don't worry about the build number - that's just because of the way I compiled this version. As for sapling problem, I'll have to take a closer look.

**Comment by PikaMug** [comment]
Fixed in 0a694c3ccfb9906104fa3724d0db9b9090070d11
