### ISSUE TITLE
Flowers (red_rose) counts towards progression no matter it's durability stage.

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1286]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
It's the same as #1213, but this one is for red_rose's instead of the carrots and potatoes etc.
Again, no console errors.

While it does paste the correct flower names into the tasks when the stage is entered, it doesn't actually look for the durability.
So while it displays "allium" in chat, it doesn't check for alliums only, but allows all flowers.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/aiheZuAY

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/129/
