### ISSUE TITLE
Support for GCore

### ISSUE THREAD

**Issue by Derfavo** [PikaMug/Quests#1287]
**What does your feature do?**
Add Support for GCore NPC's https://www.spigotmc.org/resources/gcore.24180/
https://www.spigotmc.org/resources/gcore.24180/ NPC's are Client side NPC's and can be different for every Player. So more Features for every Server. 
Source: https://gitlab.com/GuillaumeVDN/gcore
**How would people use it?**
Just like Citizen NPC. 
But with GCore NPC you can Change states from NPC's
- Armor
- life
- Weapon
- Position
and more..

**Comment by PikaMug** [comment]
GCore is no longer being updated as a standalone resource.
