### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by hypews2020** [PikaMug/Quests#1289]
**Where else have you looked for answers to this question?**
Google, Spigot
**Share your question with as much detail as possible?**
I made two quests that use an NPC to start it. All opped players can start the quest by right clicking the npc but people that arent opped get an error message
"Something went wrong. Please contact a server administator"
I dont know what this means
**If applicable, which class or method is this in reference to?**
N/A

**Comment by PikaMug** [comment]
Thanks for the report. When you get that message, there should be an accompanying message in the console with more information. Could you please share the console message?

**Comment by C4BR3R4** [comment]
It's the same with me and it's not with all the players.
The error that appears on the console is:
`[Quests] PLAYER attempted to take quest "null" but something went wrong`

It's the same as in: https://github.com/PikaMug/Quests/issues/993

**Comment by jimender2** [comment]
I also have this issue and it is quite annoying.

Running /questadmin reset player fixes it for one player but I really do not want to do it on every player.

**Comment by PikaMug** [comment]
I've pushed what I hope will be a solution to this error. If anyone continues to experience the issue on this development build, please comment in the original ticket #993 

https://ci.codemc.io/job/PikaMug/job/Quests/126/
