### ISSUE TITLE
Server Crash on Quest Acceptance

### ISSUE THREAD

**Issue by zdwars** [PikaMug/Quests#1290]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4, build #119. Running with Mythic Mobs and DungeonsXL modules.

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Whenever anyone takes and then accepts a quest, the entire server locks up and must be reset.
Error log: https://pastebin.com/MdsJ45ah

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Example quest (which has verifiably caused this error): https://pastebin.com/vxquNR3f

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/120/

**Comment by zdwars** [comment]
And all fixed up!
