### ISSUE TITLE
Feature Request- Some options for GPS-Quests

### ISSUE THREAD

**Issue by Dynamite99** [PikaMug/Quests#1292]
Hello, I am a long time user of Quests, Quests GUI and a few other modules/addons. I love the support and work that goes into this plugin. I have a feature request I suggested in discord, but also want to place here so it's easier to see

**What does your feature do?**
An option for the GPS feature to be turned on/off in the options tab for a quest/stage. Also an option for players to switch it to the quest they want to complete. Another option for it to be turned off by players so they don't have it hovering above them constantly if they are not working on a quest. Maybe also a range option so players who are in a Quest zone get it automatically, rather than having it on constantly.

**How would people use it?**
For person setting up the quests, maybe in the Stages portion of the quest to have the option to toggle the GPS setting. For players, /quests toggle (quest) or /quests toggle (off)

Thank you!

**Comment by PikaMug** [comment]
Thanks for your suggestion. Native support for GPS was removed in version 3.7.0 of Quests. There are no plans to reintegrate in any capacity.

However, if you would like to request similar functionality for the GPS-Quests bridge plugin, you're welcome to do so at https://github.com/PikaMug/GPS-Quests/issues
