### ISSUE TITLE
IndexOutOfBoundsException Error

### ISSUE THREAD

**Issue by ItsSynchro** [PikaMug/Quests#1293]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_** Server start-up is normal, except for the very end when I receive this error. https://pastebin.com/6hu2wATf

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/AqmzGzby I'd be more than willing to provide the entire quests.yml privately if requested.

**Comment by PikaMug** [comment]
Thanks for the report. Please use https://ci.codemc.io/job/PikaMug/job/Quests/121/ which should give you an indication of which quest is causing issue.

**Comment by ItsSynchro** [comment]
Same issue still occurs, without giving an indication of what exactly is causing it. Instead, upon doing /quests it displays "Plugin is currently load. Please try again later!"
