### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Manu5656** [PikaMug/Quests#1294]
I restarted the server and the plugin no longer works. If someone does a command it says "The plugin is loading, try again later". This is the error I have in the console. How can I solve it?

https://hastebin.com/epalivuvuc.cs

**Comment by Manu5656** [comment]
I tried reloading the plugin via plugman (since the commands doesn't make them do it) and I see this in the console
https://hastebin.com/ikikejozer.bash

**Comment by PikaMug** [comment]
Do not abuse the title field. I've updated yours accordingly.

The issue you've reported has likely been resolved since the version you're using. Please use the latest version of Quests at https://ci.codemc.io/job/PikaMug/job/Quests/121/
