### ISSUE TITLE
QuestsGUI take second quest dont work

### ISSUE THREAD

**Issue by Tecnok** [PikaMug/Quests#1296]
QuestsGUI: 0.17
Quests: 3.9.4

There is not console errors, but the problem is this: 
I have two practically the same missions that simply change the amount of ores to break. When you select the first mission and complete it, trying to do the second one doesn't let you select from the menu. But if you select it with the / quests take command if it lets you do it. Also if you select those two missions at the same time before completing the first one if it leaves you both. This happens with all similar missions.

https://pastebin.com/R8LdFpNH

**Comment by PikaMug** [comment]
Thanks for your report. However, all issues regarding QuestsGUI must be posted at https://www.spigotmc.org/threads/questsgui-paid.399346/

You might first try renaming your second quest in way which does not use a + symbol.
