### ISSUE TITLE
New user can't accept quest, says to contact admin.

### ISSUE THREAD

**Issue by Kalhagen8** [PikaMug/Quests#1297]
I saw that user lyimpike, in ticket number 946, linked here: (https://github.com/PikaMug/Quests/issues/946) had an issue where new users on the server couldn't accept a Quest until an admin used /questsadmin reset for the user, and then it would work. I am also experiencing this issue, and like the previous help ticket, I am also using LuckPerms. Have you looked more into what might have been causing this or do I need to switch permissions plugins in order to use the Quests plugin?

Quests version is 3.9.4. There are no console errors.

Here is the Quest he was attempting to accept, on Pastebin as requested: https://pastebin.com/zFeZ7HrL.

Here is the config file as well: https://pastebin.com/KD7WHLNy

Thanks in advance!

**Comment by PikaMug** [comment]
Thanks for the report. Are you referring to a specific ticket number? I do not recall issues by username.

You've neglected to follow the template and use Pastebin.com for your quest, so I'd appreciate if you'd update your ticket. Also, would you please share your _config.yml_ file?

**Comment by Kalhagen8** [comment]
Thank you for the response. I apologize for not following the template. I was unfamiliar with Pastebin and did not use it, but I have updated the above post to reflect the information that you requested.

**Comment by dvunderscoremaus** [comment]
Hi Kalhagen8, I also had this problem but found out if I did /questsadmin reset <player> it would fix the issue.

**Comment by Kalhagen8** [comment]
@dvunderscoremaus, did you need to do this after every new player that joined? That would be alright if I was just running a server for friends, but isn't practical for a large server.

**Comment by dvunderscoremaus** [comment]
I only did it on the one person who came across the issue.

**Comment by PikaMug** [comment]
I haven't been able to replicate this despite attempts with several versions of LuckPerms. Please upgrade to Quests 4.0.0-rc.1 and, if the issue persists, comment below to reopen the issue. Thanks!
