### ISSUE TITLE
Update ItemUtil to use newer API for Enchantment Names

### ISSUE THREAD

**Issue by frost-byte** [PikaMug/Quests#1298]
**What does your feature do?**
Fixes an issue related to the storage and retrieval of enchantment names for newer versions of Minecraft by dropping the usage of a deprecated API method - `Enchantment.getByName` to use `Enchantment.getByKey`. The new method uses namespaced keys to identify an enchantment: minecrafting:unbreaking instead of DURABILITY

**How would people use it?**
This is primarily for plugin developers or people who want to use a consistent, up to date convention for identifying enchantments that actually match the names you see in game.
It would hopefully make it easier to write configurations or update them.

[Spigot Javadoc for 1.15.2 - Enchantment.getByName](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html#getByName-java.lang.String-)
[Spigot Javadoc for 1.15.2 - Enchantment.getByKey](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html#getByKey-org.bukkit.NamespacedKey-)

**Comment by PikaMug** [comment]
Thanks for the suggestion. However, the deprecated method you're referencing is in use because Quests supports protocol back to MC 1.7.10 at time of writing. If the plugin should ever drop support for older versions, rest assured we will use keys instead.
