### ISSUE TITLE
Deliver Item Source 

### ISSUE THREAD

**Issue by longbow122** [PikaMug/Quests#1300]
Hello! I've been trying to flick through the source code to find something I'd like to change inside it. I was wondering if you could show me as to where it is? I can't seem to find it myself. The file I'm trying to find is the one where you've written the code for the deliver item stage objective. 
If you'd like a faster response or more clarity on this, feel free to contact me on my discord at 
longbow122#1576
Thanks in advance!

**Comment by PikaMug** [comment]
Thanks for your question. Unfortunately, the original author did not code objects/classes for any one objective, which is likely why you're having trouble. If you would reply with your use-case, I'd be glad to point you in the right direction.

**Comment by longbow122** [comment]
Hi, I'm simply trying to add a feature where I'm able to make a text-based representation of the items needed to deliver. So, if a player needed to give in 64 diamond blocks, but only gave in 4, the NPC deliver message would be able to tell them that through the use of a placeholder. Through testing, I've found that the plugin is able to actually *know* how many items are left, so I figure if I'm able to get the value of that integer, I can simply make a placeholder out of it.

**Comment by PikaMug** [comment]
You may be interested in using the `%quests_player_current_objectives_<quest>%` tag of https://www.spigotmc.org/resources/placeholderexpansion-quests.69357/

Otherwise, try the following:
```java
final Quests questsPlugin = (Quests) Bukkit.getServer().getPluginManager().getPlugin("Quests"); 
final Quester quester = getQuester(player.getUniqueId());
    if (quester == null) {
        return;
    }
    for (Quest quest : quester.getCurrentQuests().keySet()) {
        if (quest.getId().equals("custom1")) { // or compare .getName() instead
            Stage stage = quester.getCurrentStage(quest);
            // do something with stage.getItemsToDeliver();
        }
    }
```

**Comment by longbow122** [comment]
Hi, thanks for the suggestion for the PAPI expansion. I'm afraid that didn't work so I'm about to move onto the java alternative now. Here's the error if you'd like to look into it on your side. Thanks for all the help you've given me so far!
https://pastebin.com/ePCbX9KT

**Comment by PikaMug** [comment]
@longbow122 Seems as though you're using an outdated version of Quests.

**Comment by longbow122** [comment]
I'm currently using 3.8.1. I thought that was compatible? Either way, I'll update

**Comment by PikaMug** [comment]
@longbow122 Sorry, looks like the minimum version would be 3.8.6 so I've updated the page accordingly. However, using the latest version (currently 3.9.4) is always recommended.
