### ISSUE TITLE
Plugin not giving out permissions

### ISSUE THREAD

**Issue by hypews2020** [PikaMug/Quests#1302]
**Where else have you looked for answers to this question?**
Google, Spigot
**Share your question with as much detail as possible?**
When someone completes a quest, it is not giving out the plugin I tell it to do. It is also not giving the item I tell it to do. I have tried changing the item and permission.
**If applicable, which class or method is this in reference to?**
N/A

**Comment by PikaMug** [comment]
You have not asked a question. Please use the Report a bug template.
