### ISSUE TITLE
Playerjoinevent/playerinteractevent lag spike crash server

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1304]
Quests version:
Quests-3.9.5.jar #121
![image](https://user-images.githubusercontent.com/61608872/82109871-21598b00-976c-11ea-9f15-d54eff87a116.png)
![image](https://user-images.githubusercontent.com/61608872/82109877-28809900-976c-11ea-958d-3d02a973a763.png)
Hi, this is a survival server with some rpg stuff.
There has been some super lag problem going on , when i look at the timings report and it shows quest plugin uses packet event lag the server so badly.

Timings:
https://timings.aikar.co/?id=048e9996b43b48bcb0076faaa9dac5bc
Log:
https://drive.google.com/file/d/10QxLYiLUwmDWpxvJAqbiugnRkt0gPYYC/view?usp=sharing
quest.yml:
https://drive.google.com/file/d/10OwhUU8lXJy9w23O4lUI0Ja0_IyctKso/view?usp=sharing

**Comment by PikaMug** [comment]
Your server is lagging, which caused Quest to fail, but it was not caused by Quests. My guess would be the UltimateStacker hologram updater - try removing that plugin first, then continue to remove plugins until you locate the issue.
