### ISSUE TITLE
Reach Location Quests Require OP

### ISSUE THREAD

**Issue by Dancull47** [PikaMug/Quests#1305]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
For some odd reason my quest which requires players to reach a location only works for OPed users
Tested w/o OP, didn't register as I went to the location, tested w/ OP fixed right away

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
    stages:
      ordered:
        '1':
          locations-to-reach:
          - Spawn 99.0 18.0 -36.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Farm Balloon
          start-message: §f[§cNPC§f] §aFlint §7§l» §fYou gotta check out a few of
            our starter zones! Follow the path to the &lright &fand you'll reach the       &aFarm
            Ballloon&f!
          complete-message: '&f[&cNPC&f] &aFlint &7&l» &fHarvest lots of crops, travel
            through the &aValley&f, and explore the &aRetreat&f! Take the ballon to
            the &aFarm &fto start your journey!'
        '2':
          locations-to-reach:
          - Spawn -34.0 30.0 52.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Forest Balloon
          start-message: §f[§cNPC§f] §aFlint §7§l» §fOur next zone is the &cForest&f!
            Follow the path &lup&f the hill to the &lleft&f of me and you'll reach
            the &aForest&f Balloon!
          complete-message: '&f[&cNPC&f] &aFlint &7&l» &fBattle &cOrcs &fwhile breaking
            down Trees! You can take the Balloon to the &aForest&f!'
        '3':
          locations-to-reach:
          - Spawn -75.0 33.0 -156.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Mine Entrance
          start-message: §f[§cNPC§f] §aFlint §7§l» §fThe next zone is the &cMine&f!
            You can find it to the &lright &fof the Colloseum.
          complete-message: '&f[&cNPC&f] &aFlint &7&l» &fIf you enjoy mining rare
            ores and battling spooky creatures, youll have some fun times down there!'
        '4':
          locations-to-reach:
          - Spawn -129.0 18.0 38.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Graveyard
          start-message: §f[§cNPC§f] §aFlint §7§l» §fOur last zone is the &cGraveyard&f!
            You can find it to the &lleft &fof the Colloseum.
          complete-message: '&f[&cNPC&f] &aFlint &7&l» &fIf you enjoy slaying the
            Undead, this is the zone for you!'

**Comment by PikaMug** [comment]
Most likely another plugin is cancelling the PlayerMoveEvent; likely a region protection plugin. Try removing all plugins except Quests and add them back one-by-one until you find the issue.
