### ISSUE TITLE
You may not take (Quest) at this location

### ISSUE THREAD

**Issue by JewelAprils** [PikaMug/Quests#1306]
**Where else have you looked for answers to this question?**
All over the internet
**Share your question with as much detail as possible?**
I made a quest and then tried clicking it, in the gui and it says may not take (Quest) in this location. I don't have any regions set and have cleared them just to be sure.  
**If applicable, which class or method is this in reference to?**
Quest Plugin

**Comment by PikaMug** [comment]
You have not asked a question. Please create a new issue using the Report a bug option and include all requested information.
