### ISSUE TITLE
Denizen Integration

### ISSUE THREAD

**Issue by Curtis73** [PikaMug/Quests#1308]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I get this error thrown whenever I try and activate a denizen script through an action:
https://pastebin.com/nbbWfM7g
I'm running Denizen build 1708

I'm not sure if this is related or not, but the option to activate a Denizen script doesn't show in the stage editor, but does show in the actions editor.
![image](https://user-images.githubusercontent.com/14040165/82547579-e5e70400-9b51-11ea-83c9-9505ef0a608e.png)

**Comment by PikaMug** [comment]
I'll look into the issue. However, the Denizen script selection was intentionally moved in a previous update. It is now only available as an Action through the _/actions editor_.

**Comment by PikaMug** [comment]
@Curtis73 Even after updating to Denizen build 1708, I've been unable to replicate this error on my test server. Could you provide one of the scripts that causes this error?

**Comment by Curtis73** [comment]
I've just attempted to reproduce the issue myself and it all appears to work fine, so whatever the issue was it's sorted itself.
Thanks for your help!
