### ISSUE TITLE
Denizen GUI Issue

### ISSUE THREAD

**Issue by MattChit** [PikaMug/Quests#1309]
**Where else have you looked for answers to this question?**
Google, Discord, Github, Wiki
**Share your question with as much detail as possible?**
Quests version: 3.9.4
Denizen veresion: 1.1.4

I have been trying to get my GUI denizen script to run on quests. To do this, I set up my GUI script for denizen. The script works when I do denizens /ex inventory command. When I make an action and set it as the denizen script, after saving and reloading, the action ends up showing that no Denizen script is set. If I instead use a script that does something simple like say hello to the player, the action works. 
**If applicable, which class or method is this in reference to?**
Denizen actions

**Comment by PikaMug** [comment]
You have not posed a question. Please create an issue using the Report a Bug option. Make sure to include your script for testing.
