### ISSUE TITLE
"And/Or" Options

### ISSUE THREAD

**Issue by XavierDare** [PikaMug/Quests#1310]
simple allows a quest to have you either have to deliver 2 items OR 1 item from a list. So lets say that you are making a fetch quest. You can bring the npc either mutton OR chicken OR steak (and possibly based on this choice you will get different rewards/npc reactions)

**Comment by PikaMug** [comment]
AND function is just adding multiple objectives. OR function should be handled with multiple quests. If you want a player to take the Mutton quest but not the Chicken quest, or vice versa, use the "quest blocks" selection under [Edit Requirements](https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Requirements).
