### ISSUE TITLE
Error delivering item to NPC with reduced durability. 

### ISSUE THREAD

**Issue by MorithK** [PikaMug/Quests#1311]
Paper version git-Paper-283 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Quests version 3.9.4-b${env.BUILD_NUMBER} 
YML's: https://pastebin.com/KzdGw70C

Created a fishing rod with lore in initial action to give to player. 
Set same fishing rod as item to deliver back to NPC. (held in hand to set item)

Having used the rod to fish with per the quest the rod's durability is now reduced. On trying to give the rod to the NPC I get error message:
Fishing Rod: 11x1 is not a required item for this quest!
The difference is 'durability'

**Comment by PikaMug** [comment]
This isn't an error - the item has been modified. Either instruct the player to repair the item or use a different item which cannot be damaged.
