### ISSUE TITLE
Lag help

### ISSUE THREAD

**Issue by SladeHazard** [PikaMug/Quests#1313]
How to optimize this: https://gyazo.com/f9b37c8b2eb3e45ac03e072a9f176c8a
https://timings.aikar.co/?id=39872b9c2df74bbc98ab83510cbf31ce#timings

**Comment by PikaMug** [comment]
Quests is checking whether the player is Op or has permission to use the plugin before updating their compass in the new world. I'm not certain how much of this can be made asynchronous, so I'll look into it and get back to you.

**Comment by PikaMug** [comment]
@SladeHazard I've decided to adjust the checks mentioned in my previous comment. The change is significant, so please test this development build thoroughly, and report back with any issues:
https://ci.codemc.io/job/PikaMug/job/Quests/125/
