### ISSUE TITLE
OPEN QUEST GUI

### ISSUE THREAD

**Issue by SladeHazard** [PikaMug/Quests#1314]
Hi what's the command to open the gui for quests which player open using npc i want them to be able to open it directly

**Comment by PikaMug** [comment]
There is no such command; the NPC GUI can currently only be opened by speaking to an NPC.

Closest you could get is _/quests list_ with [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) installed (premium) and `click-to-take: true` set in its config.yml file.
