### ISSUE TITLE
Quest Points Top

### ISSUE THREAD

**Issue by JessePesse123** [PikaMug/Quests#1315]
**What does your feature do?**
A placeholder that outputs the playername of the player with the most questpoints. Or for example Quests_quest_points_top<number> would give you the playername of that place in the top.
**How would people use it?**
People could implement it in scoreboard, Banner Boards,...

**Comment by PikaMug** [comment]
Wrong issue tracker. See https://github.com/PikaMug/PlaceholderExpansion-Quests
