### ISSUE TITLE
Potion delivery allows potion when effect is met, but not the duration.

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1316]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4
Craftbukkit 1.12-R0.1-SNAPSHOT

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I made delivery quest, where the player has to deliver a long fire res potion.
But it also allows the short one to be delivered instead.
No console errors.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/k23zsK6e

**Comment by PikaMug** [comment]
Possibly related to #954

**Comment by PikaMug** [comment]
Does this still occur on the Quests 4.0.0-rc.1 build?
