### ISSUE TITLE
Npc gui.

### ISSUE THREAD

**Issue by Qekker** [PikaMug/Quests#1317]
**Hello**

Is it possible to make quest on npc not dissapear when they are complete. I just want them to become enchanted and not dissapear. 

Another question is: Is it possible to make a quest where players have to kill a specific group players?

**Comment by PikaMug** [comment]
Hello. I'm not certain I understand your first question. You want to make a quest repeatable? This can be done by setting a repeat-cycle under the Edit Planner option for a quest.

Groups are not a concept within Quests. Is there a particular plugin you're seeking compatibility with?

**Comment by Qekker** [comment]
Noo, i dont want to make a repeatable quest. I want to have the quests on the npc to become enchanted when they are complete.  So you can see which quest you already have completed. 

I’m making a prison server where I want to make a quest. That is named “kill a guard”. I’m using pex

**Comment by PikaMug** [comment]
I see, unfortunately setting GUI items to become enchanted based on quest completion isn't currently an option.

If the "guard" is an NPC, just use the Kill an NPC objective. If it's an actual player, there is no way to specify which player(s) within Quests itself as they can go offline at any time.

**Comment by Qekker** [comment]
Will you think about adding theese features?

Is run x blocks to complete a quest an option?
