### ISSUE TITLE
Permission reward error

### ISSUE THREAD

**Issue by ExistenZ131** [PikaMug/Quests#1322]
**What is your Quests version / build number (do _not_ say "latest")?**
- 3.9.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
- Tried to fix the bug with permission rewards, its works now but i get an error in console. https://pastebin.com/Gd3D3T5w

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
- https://pastebin.com/hWezQjSW

**Comment by PikaMug** [comment]
Thanks for the report. Does this still occur on the latest development build? https://ci.codemc.io/job/PikaMug/job/Quests/126/

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
