### ISSUE TITLE
Bug Name

### ISSUE THREAD

**Issue by XxDierkX** [PikaMug/Quests#1323]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
when I write the name of item for gui and after doing it, it does not say the name that I have written, what appears is the name of the mission
![Image](https://user-images.githubusercontent.com/66573796/83980897-75244380-a8d6-11ea-93ed-300b760261e6.png)
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. Please provide the quest from quests.yml using Pastebin/Hastebin

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
