### ISSUE TITLE
error with permissions

### ISSUE THREAD

**Issue by llronaldoll** [PikaMug/Quests#1325]
**What is your Quests version / build number (do _not_ say "latest")?**
 3.9.4-

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
players without permission continue to be able to execute Player Commands

this happens in case the quests journal permission is given to them

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
just give quests.journal permission, and he will have all other player permissions!

**Comment by PikaMug** [comment]
All non-admin permissions are given by default. You must negate/subtract the permission to disable functionality.
