### ISSUE TITLE
GCore Client Sided NPCs Support

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1326]
**What does your feature do?**

Adds support to GCore's Client sided NPC's API.
https://www.spigotmc.org/resources/gcore.24180/

**How would people use it?**
Quests will feel more interactive such as the NPC walking along side with the player perhaps showing him a town or an escort quest. There's lots of possibilities.

**Comment by PikaMug** [comment]
Duplicate of #1287
