### ISSUE TITLE
Is there a feature on this plugin to allow players to choose between killing an NPC or letting them live for a different reward? (while in mid-quest)

### ISSUE THREAD

**Issue by HoopsHowTos** [PikaMug/Quests#1327]
**Where else have you looked for answers to this question?**
Plugin’s Page

**Share your question with as much detail as possible?**
For example: You’ve been told to go search for a man’s wife in a cave... She’s a bandit leader now... You can have the option to either A) convince her to return to her husband. OR B) Kill her for the loot. I just want to know if you’d be able to perform this in one of the actions/stages... I’m pretty certain that you CAN’T. But I figured it’s worth a shot asking...
**If applicable, which class or methodis this in reference to?**
Reference towards the in game /Quests Editor.

**Comment by PikaMug** [comment]
Not sure if you got an answer to this or not, but there is no "let NPC live" objective.

However, you could have two different quests - one for killing, and one for something tame like giving her a flower - and then use "quest blocks" under Edit Requirements to prevent one quest from being taken if the other has been completed.
