### ISSUE TITLE
Citizens won't interact with quests

### ISSUE THREAD

**Issue by Verious1030** [PikaMug/Quests#1329]
**What is your Quests version / build number (3.9.4)?**

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/UHZc3u1w
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/dDgjxEAR

**Comment by PikaMug** [comment]
I see you have duplicates of several plugins in your server (that's what those "Ambiguous plugin name..." errors mean). Please correct these issues before seeking assistance.

**Comment by Verious1030** [comment]
Ok, I fixed the ambiguous plugins error, This is my log now https://pastebin.com/Xn1tt7fA

**Comment by PikaMug** [comment]
@Verious1030 At line 1841, I see the following:

> [15:49:56] [Server thread/INFO]: [Quests] Sucessfully linked Quests with Citizens 2.0.26-SNAPSHOT (build 1996)

What exactly isn't working in-game?
