### ISSUE TITLE
No quests are saved

### ISSUE THREAD

**Issue by IRulesMC** [PikaMug/Quests#1331]
Hello,
so, I make a quest, edit it and save it. I exit and I do /qa reload ( it reloads properly, no errors ). After this, I do /quests list but there are only the default quests. Am I doing something wrong or?
Versions:
Server: paper 1.12.2
Plugin: 3.9.4

**Comment by PikaMug** [comment]
Please inspect the contents of your quests.yml file. If the quest is present, share it here using Pastebin/Hastebin. If not, please share your server's startup log using the same paste site.

Also consider trying the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/
