### ISSUE TITLE
Creating new quest from other plugin

### ISSUE THREAD

**Issue by a-wernon** [PikaMug/Quests#1333]
Hi!
Is there a way to create quest in way other than editing then manually in yaml file and from gui? In my case I looked for method that I can call from my own plugin to generate quest.
**Where else have you looked for answers to this question?**
I've looked through code of plugin but it is hard to understand whole logic of a complex project. So if there is a simple solution, it'll be great to know about it before writing such method by myself.
Also, I read whole wiki and found out nothing about my problem.

**Share your question with as much detail as possible?**

**Comment by PikaMug** [comment]
Thanks for your question. Quests was not designed to allow other plugins to create quests programatically. The most you can do currently is create a new Quest object and set an ID, name, and other attributes. However, you will be unable to apply any Stages and it may not even be possible to save the quest without reflection.

As you may know, the [Custom Quest API](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API) can be used to create Requirements, Rewards, and Objectives. This allows you to give server owners the ability to use your novel ideas as they see fit in their quests - and cease if/when they outgrow them. Circumventing this would possibly strip owners of this power, and questadmins of their usefulness. It is for this reason, as well a desire to prevent potential abuse, that the creation of quests is left in human hands.
