### ISSUE TITLE
Quests not being accepted by commands/not existing

### ISSUE THREAD

**Issue by Sinnerrrr** [PikaMug/Quests#1335]
**What is your Quests version / build number (do _not_ say "latest")?**

Version: 3.9.4 (May 5, 2020)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Excerpt from https://github.com/PikaMug/Quests/issues/1334 :

I am using a plugin for World Guard that allows my regions to execute commands on entry (in this case, I wanted players to automatically receive a quest when they entered an area) which gives me the prompt telling me that the quest I created couldn't be accepted via commands when I enter it, however when I attempt to accept the quest manually I'm told that no such quest exists. I can edit the quest, the World Guard regions seem to recognize it as a valid quest, however whenever I attempt to accept a quest via the /quest take or the /questadmin give command, I am told that no such named quests exist. I have reloaded the quests multiple times and have saved and created new, blank quests as controls and I am still unable to accept them via command or region. Reloading the server had no effect.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/mMzfkhTC

Thank you!

**Comment by PikaMug** [comment]
Thanks for the report. Could you please share the message you're getting from "prompt telling me that the quest I created couldn't be accepted via commands". Also, what is the exact command you're using?

**Comment by Sinnerrrr** [comment]
> Thanks for the report. Could you please share the message you're getting from "prompt telling me that the quest I created couldn't be accepted via commands". Also, what is the exact command you're using?

The prompt I am getting when attempting to accept the quest I sent previously is: "[Quest name] may not be started via command." while using /quests take [Quest name].
When I attempt to use /questadmin give [Player] [Quest name] I am told said quest does not exist. 

Thank you!

**Comment by PikaMug** [comment]
It appears you cannot accept the quest because it uses a block start (option 5 in the image below). You must be standing in the LunarCrater world at coordinates x=-24.0 y=71.0 z=203.0 in order to take the quest.

![CreateQuest](https://i.imgur.com/HeG9w9K.png)

I would think _/questadmin give_ would circumvent this, but I must ask again for the _exact_ command you're using (including how you're typing the player name and quest name) if you'd like me to look into that further.

**Comment by Sinnerrrr** [comment]
Apologies, I didn't realize you needed the exact way I was typing the commands in, I thought you just meant the syntax for what I was typing.

I'm aware that it uses a block start, and even when I'm in those blocks I cannot accept the quest.

Commands are typed as follows: 
/quests take Welcome to Lunar Base LeGuin! 
/questadmin give b4time10 Welcome to Lunar Base LeGuin! 

As of today the /questadmin give command has successfully given me the quest, (I have not changed permissions, quest structure, etc... I don't know why it works now) however anyone who is not an operator still has no way to accept quests outside of an operator doing it for them. The /quests take command still gives me the "[Quest Name] may not be started via command." prompt, regardless of operator status or where the player is stood (either within the start block or outside of it).

Thank you!

**Comment by PikaMug** [comment]
I've looked into this and it boils down to the fact that Block start isn't technically a Requirement, but rather a key descriptor of a quest, which is not designed to be easily overriden. That said, I may look into relocating the Block start (and perhaps its neighbors as well), but until then I'm afraid the solution is to simply not use a Block start in this scenario.
