### ISSUE TITLE
Objective isn't working with silk

### ISSUE THREAD

**Issue by Kamiell** [PikaMug/Quests#1336]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.5
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
If you want a stage where players need to mine certain blocks they can't mine those blocks with Silk Touch.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
-

**Comment by PikaMug** [comment]
This is intentional to allow players to mine blocks without having to progress their quest. Please see the final "Pro-tip" in https://github.com/PikaMug/Quests/wiki/3-%E2%80%90-Quests-Editor
