### ISSUE TITLE
Quests Rewards are Decreasing Times after Time

### ISSUE THREAD

**Issue by Travefleix** [PikaMug/Quests#1338]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Quests reward are always decreasing, after people did the second run or third run.
Ex: 
Quest_1 rewards 7 Blaze Powder, and has a cooldown for 15 minutes.
After person A took the quest for the 3rd time, the rewards are decreasing to 4 Blaze Powder.
Then Person B Took the quest for the 1st time, and still get 4 Blaze Powder until it fixed via quests editor.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Update to the latest version (3.9.5), and if the issue still occurs, provide an example quest for testing.
