### ISSUE TITLE
Quests stop being progressive on restarts/crashes

### ISSUE THREAD

**Issue by call911nowplz** [PikaMug/Quests#1339]
Ver: Quests: 3.9.5

Error: No errors.

quests.yml: https://pastebin.com/Qm1H6djJ

So basically, Sometimes on restarts, player's quests get stuck. Its been an issue for months now and im surprised it's not reported, Or atleast not from what i've seen.
Quests become completely frozen until i manually set their stage back to where they were.

**Comment by PikaMug** [comment]
Thanks for your report. As you mentioned, I have not received any reports about such an issue. Could you provide more detail on a single instance of this occurring? Specifically, include the following information:

- Minecraft version
- Current quest/stage/objective
- Whether other players can take/finish the quest
- Crash report, if applicable

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
