### ISSUE TITLE
Allow for dynamic descriptions on customReward, customObjective, customRequirement

### ISSUE THREAD

**Issue by Nutty101** [PikaMug/Quests#1340]
**What does your feature do?**
At the moment the requirement has no ability to display anything other than what is placed into the set name spot by the developer. Not the person making the quests. So it looks a bit off when your requirement cannot be explained to a user since it could be a vast array of things.

**How would people use it?**
This would just make the quests for intuitive for players.

![image](https://user-images.githubusercontent.com/14265073/86550246-8c6f4480-bf07-11ea-9847-88c71db1bb5c.png)

**Comment by PikaMug** [comment]
Thanks for your request, but I'm a little confused. Are you asking for a description to be shown when selecting/creating the custom rew/obj/req, or when requirements are listed upon failing to meet them, per the picture you shared?

**Comment by Nutty101** [comment]
Sorry for the delay.  When we create an Addon for Quests, the admin will enter the npcdest curloc (Current location). However, when this is a requirement it shows to the user the command name. Others like Objectives you can change that display (Example:  [See line 25 for example](https://github.com/PikaMug/DungeonsXLQuestsModule/blob/37bba9c99251bed29dd63cc7f45e961ee9cc3df4/src/main/java/me/pikamug/DungeonsXLQuests/DungeonXLKillPlayersObjective.java#L25)).  You can also set this on Rewards (Example: [Line 25 - SetRewardName](https://github.com/PikaMug/mcMMOQuestsModule/blob/2d75e1540ed8e9d1302d8d852ab74ad23485a092/src/main/java/me/pikamug/mcMMOQuests/mcMMOSkillReward.java#L20))

**Comment by PikaMug** [comment]
Compiling against the above commit will net you a setDisplay() method for the constructor of your custom requirement.

You'll also notice that setRewardName() has been deprecated in favor of a setDisplay() for custom rewards as well (functionally identical, but done for consistency).

**Comment by Nutty101** [comment]
You are so awesome. Thank you!!!
