### ISSUE TITLE
I having an issue with one of my quests not opening a book while the other 3 quests are opening their books. They are all setup the same way just the name of the book is different.

### ISSUE THREAD

**Issue by Gables2014** [PikaMug/Quests#1341]

**Comment by PikaMug** [comment]
Quests does not offer a way to open books. If you're using CitizensBooks or Denizen scripts, please seek assistance from the plugin's developer or support forum.

**Comment by Gables2014** [comment]
Well I seen to be able to make Quests open a book with 3 of the quests
