### ISSUE TITLE
Permission Rewards

### ISSUE THREAD

**Issue by ChiiTaii** [PikaMug/Quests#1342]
I'm having trouble setting up permission rewards for quests. I haven't been able to find any valuable information so far. Generally, I am not sure what to type as a general format under 'Set permission rewards' 
In terms of specifics, I am trying to set up granting players access to a specific warp after completing the quest although I have no idea how to format granting any permissions to players.
Also, I do not know how to set the format for issuing commands as a reward, and have not been able to find any helpful information on this either.
Thanks

**Comment by PikaMug** [comment]
When entering a permission reward, type the entire permission as it appears in the plugin's documentation. For example, allowing access to EssentialsX's _/warp_ command would be:

`essentials.warp`

As for giving access to a specific warp, the target plugin must support per-warp permissions. I am unsure whether EssentialsX allows this and, if not, you'll need to find an alternative plugin.

The same goes for command rewards. Enter the command as it appears in their docs (without the forward-slash).
