### ISSUE TITLE
updated to 1.16 and got error

### ISSUE THREAD

**Issue by MicleBrick** [PikaMug/Quests#1343]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.5
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
got this error after upgrading to 1.16
https://hastebin.com/iyepudufar.md

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
This is not an issue with Quests. See https://bugs.mojang.com/browse/MC-185417
