### ISSUE TITLE
npc-effects: ?

### ISSUE THREAD

**Issue by Boy17000** [PikaMug/Quests#1344]
**Where else have you looked for answers to this question?*everywhere... from google to spidgot to the discord (POORLY MANAGED HELP) to here.*

**Share your question with as much detail as possible?** 
So my question is basically an NPC symbol above the NPC head. like people see the note effect but can we by anyway 
have it so that a player who still has to do a quest of the NPC see the NPC name but above it a symbol like "�"? and if they
already finished the quest they don't see it anymore

**If applicable, which class or method is this in reference to?*idk npc-effects I don't really understand the question here..*

**Comment by PikaMug** [comment]
The Discord is not "managed help"; it is a community server.

Only particles may be used for NPC-effects at this time. What you desire would require disabling the feature, then creating a similar plugin which uses a resource like HolographicDisplays for the text.
