### ISSUE TITLE
How i can show a "ask-message" in a book interface?

### ISSUE THREAD

**Issue by MrCobayo18** [PikaMug/Quests#1346]
Hello! How i can show a "ask-message" in a book interface? I don´t wanna show a text in the chat area, i wanna open a book with the text. Is possible? Thanks.

**Comment by PikaMug** [comment]
Quests itself is unable to insert quest strings outside of where it's designed to. However, if you have knowledge of Java, you could acquire the string via `Quest#getDescription` and place it wherever you like.
