### ISSUE TITLE
Fail Requirement Message not showing

### ISSUE THREAD

**Issue by trevor1097** [PikaMug/Quests#1358]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.6-b134

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When i Set details list override and the quest is given by an NPC it still show "No more quests available."

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Quests.yml - https://pastebin.com/uX5GpJex
No console errors

**Comment by PikaMug** [comment]
@trevor1097 Your quest must have at least one stage objective.

**Comment by trevor1097** [comment]
Sorry i had just listed up to that point. Here is the whole quest from quests.yml. https://pastebin.com/YB9Za576

**Comment by trevor1097** [comment]
@PikaMug
