### ISSUE TITLE
Player Decisions Feature

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1359]
Decisions is a feature which can completely transform the way how story telling can be done and feel more immersive with the consequences of your actions making the player pay more attention to what they're doing as it can have an impact on their rewards/etc, a decision can have a bad or good ending, it is all up to the story teller how they want to use them. I think this is something that would benefit being officially added within the plugin and not a third party, I've come up with 2 ideas of how to implement this, I'm no programmer so I don't know which one is easier or not or the challenge of such a feature, but I think its one to be considered due to the big impact it can have. Thank you.

**What does your feature do?**
Basically adds decisions to quests, the player is able to take a different path.

It could work based on stages too. 

New section called "Edit Decisions" the section is optional doesn't have to be used the player basically adds every decision that is able to be made within the quest based on an ID, every decision will basically have its own set of stages which can lead to other decisions or when reach the end entirely end the quest.

New option added to the Edit Stages menu inside of a stage called  "Decisions" you're basically able to input what decisions you want that stage to popup in chat that the player can click on which will take them to one of the new set of stages that decision has.

Ultimately I think this is a little complicated but I'm trying to think of what's the best format to be done. 
Another way could be a new option is added to stages that as well makes a chat dialogue pop up with the decisions but when clicked on it just entirely removes you from the current quest and puts you in another quest that the player wants, so server owners can just make a different quest for every decision they want to have.

**How would people use it?**
To have a more impactful way of telling a story and make the player feel in control of what's happening.

**Comment by PikaMug** [comment]
Thanks for your suggestion. Multiple stage/objective paths have been suggested before and, while I'm certainly not opposed them, it would be somewhat challenging to add, as you've said. One can already force players to chose between quests using the Quest Blocks feature under Edit Requirements.

Clickable text is a Spigot-only feature which Quests cannot currently support as a goal of the project is to not dampen its unsupported use in Bukkit-only servers (namely for modded environments like Cauldron).

As I'm currently working on https://github.com/PikaMug/Quests/projects/2 the best chance of this happening would be a Pull Request.

**Comment by PikaMug** [comment]
Closing due to lack of interest from the developer community.
