### ISSUE TITLE
Issue with quests gui updating

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [PikaMug/Quests#1360]
Because of /quests editor and you update message in chat it works but in the gui of a quest won't update
tried resetting, and even tried 1.8 quests for 1.16.1 and it still wont work
I only use 'quests' not quest gui premium plugin, and the normal quests don't update the guis for some reason in 1.16.1
if this could be fixed

**What is your Quests version / build number (do _not_ say "latest")?** it is 1.16.1 quest

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Install quests, restart server add 1 or mutiple quests to an npc and it will give u a gui message but
if u try to update it will stay same one forever even after deleting sometimes
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Yes I use Quests 3.9.5 1.16.1 quests thanks!
Hope bug gets fixed

**Comment by PikaMug** [comment]
Thanks for the report. The only built-in GUI is for NPCs, which has been tested to work fine on 1.16.1 servers, even following your instructions. Since you have not provided an example quest/file to test with, I must close this issue pending further information.
