### ISSUE TITLE
Config option to hide 'planned' quests.

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1361]
**What does your feature do?**
Adds a true/false option to the config for `hide-locked-planned-quests` or similar.
Which hides quests that are unavailable at that time to the player, because of the planner.

Reason why I made a feature request rather than a bug report, is because even though it should be considered a locked quests if unavailable. I still think it should be a separate option, as it makes more sense in a lot of cases to want to hide 'planned quests' but not hide 'locked quests'.

**How would people use it?**
This way designers can make quest updates by adding new quests, while still hiding them from the player until the planned release date.
It would work especially well for LTE quests, as you could hide them when they aren't available, without having to delete the quests from the yml.

**Comment by PikaMug** [comment]
Thanks for the suggestion. What is the advantage to this over just setting a Planner start-date far in the future? I'm not sure what an LTE quest is.

**Comment by DateInJapanese** [comment]
LTE = Limited Time Event;

For example Christmas quests, halloween quests etc.

=

The advantage of being able to hide planned quests over setting the start-date far in the future would be so they won't display in the /quests list.

![Screenshot 2020-08-05 at 16 00 51](https://user-images.githubusercontent.com/38226281/89421989-07a95d80-d735-11ea-9307-6da8b7efa7d3.png)
Such as what's happening here for example.
This quest was set to start in 5 days, but already displays on the list.

I wouldn't say this is a big deal in general, but it'd be a nice feature to have when it's needed.


If it were to get added it should function in a way to where it hides the quest from the /quest list, while the start date has not yet passed.
That way they shouldn't be hidden during a cycle of more common quests such as daily quests.

Since it doesn't change any of the internal gameplay or contents, I wouldn't be disappointed if it won't get added.
But if it's something small and doesn't cost a lot of time, I'd still like to see it.

**Comment by PikaMug** [comment]
In this situation, would it not then become impossible for players to check when a (out-of-planning) quest will next become active? Rather than hide, the quest, what if it was just grayed out? So instead of yellow text, use gray to indicate inactivity.

**Comment by DateInJapanese** [comment]
Well, if the quest was active before it would no longer be hidden.
Only the quests that have never been active yet, would be hidden.

But now that you mention the indicator for inactive quests, I do think that would be a nice addition as well.

Making quests that have a start date that hasn't passed yet be invisible/hidden.
And making the quests that have been active before, but are not active at that moment, be greyed out.
