### ISSUE TITLE
End planner doesn't work

### ISSUE THREAD

**Issue by Starkitobonito** [PikaMug/Quests#1363]
**Where else have you looked for answers to this question?**
-QUests discord
**Share your question with as much detail as possible?**
Players on my server can take quests that are already over. I put a mission that starts and ends on Monday the 20th, and restarts on Monday of the following week. Today is Thursday and the players can continue taking the mission on Monday, and they get the message that the mission can be taken again in 3 days, and they can still take it.

This is the planner configuration of the quest:
    planner:
      start: 20:6:2020:1:0:0:America/Chicago
      end: 20:6:2020:23:59:59:America/Chicago
      repeat: 604800

**If applicable, which class or method is this in reference to?**
![afsafaf](https://user-images.githubusercontent.com/68711129/88334304-2cdeaa80-ccf7-11ea-88d6-b9197745391f.JPG)

**Comment by PikaMug** [comment]
That message is saying that the quest will become active in 3 days; not that the player will be able to take it again. As long as you don't set a player cooldown, the quest cannot be taken more than once.

**Comment by Starkitobonito** [comment]
Okey, i'm setting a player cooldown, but i'm taking the quest today (thursday 23) and in the planner i set the quest to end on monday 20 at 23:59:59. Why i can take the quest on thursday ir in theory the opportunity ended on monday?

**Comment by PikaMug** [comment]
@Starkitobonito If you were to set a cooldown, that would make the quest repeatable. So if you do not want players to take your quest a second time, do not set a cooldown.
