### ISSUE TITLE
Quests Compass

### ISSUE THREAD

**Issue by CaptainAlienHD** [PikaMug/Quests#1365]
**Where else have you looked for answers to this question?**
I've tried to look into code
I've also talked to Quests Discord, nobody was aware how to help me
**Share your question with as much detail as possible?**
Question is all about a newer function added to the Quests.
Abillity to use Compass to track quests. I'd like to see the docs about it. How to enable/disable it
How to use it, What are the commands for it. and so on. As for now i'm able to just Right click the compass and it tells me:
"Set Compass target to quest Iron Miner" and i do not know how to continue of there.
**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
Permission is `quests.compass` as shown in https://github.com/PikaMug/Quests/wiki/1-%E2%80%90-Commands-&-Permissions#player-commands

There are no commands associated. Simply right-click on any compass to change the "target" quest it points to, or left-click to reset. Read more at https://www.spigotmc.org/resources/quests.3711/update?update=324922
