### ISSUE TITLE
Why am I not seeing the ask or complete messages?

### ISSUE THREAD

**Issue by VimaMT** [PikaMug/Quests#1366]
**Where else have you looked for answers to this question?**

**Share your question with as much detail as possible?**

**If applicable, which class or method is this in reference to?**

**Comment by VimaMT** [comment]
I am not seeing the ask or complete message to my quest. Instead, I see: "Server: Showing new title for <myname>" and "Server: Showing new subtitle for <myname>"  I am running PaperMC 1.16.1 #111.
![2020-07-26_10 14 06](https://user-images.githubusercontent.com/46653361/88483034-cb068680-cf2a-11ea-9eed-9f29cecf17e2.png)

**Comment by VimaMT** [comment]
More info: I have the latest version of Quests from Spigot:  3.9.5
I did not have this issue in the past with 1.15.2.
This is a new quest.

**Comment by PikaMug** [comment]
Closing as OP did not follow issue template. Please use the "Report a bug" option.

Also, you can disable Server messages with `/gamerule sendCommandFeedback false`
