### ISSUE TITLE
MyPet Compatibility

### ISSUE THREAD

**Issue by malicomrade** [PikaMug/Quests#1368]
I'm not sure if this can be done by the creators of Quests, but it's worth asking. Is there a way you guys can make MyPet compatible with Quests so if a player's pet kills a mob the player gets that kill in the quest. MyPet is also a very popular plugin and I think this would really help people that use MyPet plugin.

This feature would give an admin a option to enable kill progress made by a pet. Maybe some other stuff could also be added, but I think this would be the main thing.

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#need-support-for-other-plugins

Also, I do not see a death/kill event in https://github.com/xXKeyleXx/MyPet/tree/master/modules/API/src/main/java/de/Keyle/MyPet/api/event so you'll likely want to request one from the developers of MyPet first.
