### ISSUE TITLE
No requirement message for "Set quest requirements"

### ISSUE THREAD

**Issue by Potentiate5** [PikaMug/Quests#1372]
**What is your Quests version / build number (do _not_ say "latest")?**

Version 3.9.5

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

I've created two quests that require you to race to a certain point and return. I'm using "Set quest requirements" to make the the first quest a prerequisite to the second. Whenever the player gets to the list of quests, if you try and press 2 to complete the second one before the first quest, it doesn't show any message. No error is printed to console either.

Upon doing /questadmin reload, this gets printed in console:
https://pastebin.com/FAsveKnc

It mentions the default Iron Miner quest but I've already deleted it, and I'm not sure if it's related but it's the only console error messages I'm getting.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/e7PaEEiv

**Comment by PikaMug** [comment]
Thanks for the report, I'll look into this. In the meantime, please check your _quests.yml_ file for any mention of Iron Miner requirements. Even though you've deleted the quest, that error indicates that another quest still references it and ought to be edited out.

**Comment by PikaMug** [comment]
This should be effectively resolved by the commit for #1361 in combination with the aforementioned file correction(s).
