### ISSUE TITLE
Quest plugin issue with Tracking

### ISSUE THREAD

**Issue by DeadlyBladez** [PikaMug/Quests#1373]
I have latest Build 3.9.5 and seem to have a issue where every time a player moves on the server it sends permissions info on my verbose  saying Quests.* , Quests.Quest.

If 10 people run around it can cause tps to drop using 8gb of ram running on a KVM 2693 Mhz 8 Core Logical Processer
With A pci super express ssd drive that goes over 6k  mbps and still get alittle lag from this issue ive changed the strick player movement from -1 to 200 and none of these seem to change the checker for this if u have a verbose on your server like luck perms or spartan u could see these as well

**Comment by PikaMug** [comment]
Thanks for the report. Would you mind checking if the issue still occurs on the latest development build? https://ci.codemc.io/job/PikaMug/job/Quests/

Also, you've enabled _advanced_ tracking by setting `strict-player-movement` to any value other than -1, so you may wish to revert that as your new setting will cause a (small) spike every 200 seconds.

**Comment by DeadlyBladez** [comment]
yes this problem still Happens every time a player moves also changing the strict-player-movement dosnt affect this issue for it happens no matter what u set that two... another issue we seem to not be able to fix is the prefix for Money being Dollars cant seem to find why it cant be changed to something else but dont see it on your jar file as an item is it using vault or another plugin to read the dollar prefix when u get payed for a quest

**Comment by PikaMug** [comment]
It doesn't affect this issue because the setting isn't related - but setting it to anything other than -1 will negatively impact the server in exchange for more precise tracking when riding Armor Stands. So unless you're running a vehicles plugin, set it back to -1.

The money prefix is determined by Vault in most cases, but you may wish to adjust the `money:` setting in your Quests language file as well.

Anyway, I'll look into the issue shortly.

**Comment by PikaMug** [comment]
@DeadlyBladez Please try the latest development build and let me know whether or not it improves performance.

https://ci.codemc.io/job/PikaMug/job/Quests/141/

Note that the build may not be fully compatible with QuestsGUI if you have that installed.
