### ISSUE TITLE
Is there any way I can display someone's current objective for their quest using PlaceholderAPI?

### ISSUE THREAD

**Issue by Carreb** [PikaMug/Quests#1374]
My users are only allowed one quest at a time, I want to be able to display their currently active quest along with their current objective on the scoreboard. However you can only list objectives for a specific quest, how can I make it so that it will show the objective for the currently active quest?

**Comment by malicomrade** [comment]
As of now, you can't do it for the currently active quest, but if you put the placeholder for every quest it would work the same, I use this:

'%quests_player_current_objectives_#1C1 Important News%%quests_player_current_objectives_#2C1 No Time%%quests_player_current_objectives_#3C1 A Real Hero%'

And if the player doesn't have one of those quests active they are left blank. Simple as that.

**Comment by PikaMug** [comment]
This is not available because a player can have multiple objectives per stage (as well as multiple quests) simultaneously.
