### ISSUE TITLE
Grown Crops requirement

### ISSUE THREAD

**Issue by LotusDemon** [PikaMug/Quests#1376]
**Where else have you looked for answers to this question?**
On the plugin page at the spigot and in the plugin config

**Share your question with as much detail as possible?**
Im setting a quest objective as break block: Potatoes. I would like to set it so only fully grown crops counts towards this objective. Is this possible?
**If applicable, which class or method is this in reference to?**

**Comment by DateInJapanese** [comment]
Break block: Potatoes
Amount: Whatever you want.
`Block durability: 7`
As 7, is the age value of a fully grown crop on soil.
