### ISSUE TITLE
Quests error when player disconnects

### ISSUE THREAD

**Issue by lceDr0p** [PikaMug/Quests#1378]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v3.9.5(latest on spigot)
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The problem occurs when a player disconnects, the console outputs an error saying about a PlayerQuitEvent and the quests goes back to the start (sometimes quest disappears when server is restarted)
more info here :https://pastebin.com/QqVWuNS1
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/LqkgFWkJ

**Comment by PikaMug** [comment]
> "Kill me some..."

Quest names may not contain periods or commas. This is both explained and prevented via the editor.
