### ISSUE TITLE
Delivery Items

### ISSUE THREAD

**Issue by InFiNiX2231** [PikaMug/Quests#1380]
**What is your Quests version / build number (do _not_ say "latest")?**

```Quest 3.9.5```

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

```So basically, I created a quest via VS code and not in game since I prefer an efficient way to work on it since in game you have to exit an option to be able to edit another option. So since I worked on VS code I normally would test the quest I made in my test server and for some reasons, the requirements to deliver an item isn't showing in game chat as well as quest journal. But whenever I edit the quest through in-game editor it shows the requirements to finish the quest. And since then I tried copying the format that was shown and still after testing it again it doesn't work. There wasn't any error given in the console.```

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

```Here is an example quest``` https://pastebin.com/wTmSByWN

**Comment by DateInJapanese** [comment]
You can't have a delivery amount higher than a stacks worth in a Singulair stage.
If you want to deliver more than a stacks worth; you'd have to split them up in stages.
Or find a different way to 'collect' the items from the player.

Such as having a woodworking npc, that will take the 4 stacks and in return the gives the player a token of the sorts, which they then deliver to the final npc.

**Comment by InFiNiX2231** [comment]
> You can't have a delivery amount higher than a stacks worth in a Singulair stage.
> If you want to deliver more than a stacks worth; you'd have to split them up in stages.
> Or find a different way to 'collect' the items from the player.
> 
> Such as having a woodworking npc, that will take the 4 stacks and in return the gives the player a token of the sorts, which they then deliver to the final npc.

so basically I have to created 4 stages in order to satisfy the 256 items?

**Comment by DateInJapanese** [comment]
That's one way to do it.
If you use a trading plugin like shopkeepers or similar, you could let the player trade a stack of logs for a token item.
And then let them deliver the tokens as proof of completing the task.

**Comment by PikaMug** [comment]
Thanks @DateInJapanese
