### ISSUE TITLE
Error at loading

### ISSUE THREAD

**Issue by divios** [PikaMug/Quests#1381]
**What is your Quests version / build number (do _not_ say "latest")?**
I'm using quest 3.9.5
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
It happens when the plugin is loading, it throws this error and althought when i press an npc with a mission it says that not mission is avariable, when i try and use a command. replies: "plugin is currently loading".

 https://pastebin.com/MmDHa3Np 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. This should be resolved in the latest development build at 
https://ci.codemc.io/job/PikaMug/job/Quests/

If you find this is not the case, reply below with the newly formed error.
