### ISSUE TITLE
"delivery-messages" section is duplicated after saving the quest

### ISSUE THREAD

**Issue by piotrskibapl** [PikaMug/Quests#1383]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.5

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Whenever I save a quest using the in-game editor, the "delivery-messages" section is being duplicated in the quests.yml file.

Steps to reproduce:
1. Create any quest with delivery-messages, save it and make sure it is loaded in game.
2. Enter the in-game editor and edit the quest you made before. Don't make any changes, but make sure to save it.
3. Observe the "delivery-messages" in quests.yml - all messages are duplicated.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/Xk2X3GUp

**Comment by PikaMug** [comment]
@piotrskibapl This fix is now available in https://ci.codemc.io/job/PikaMug/job/Quests/142/

Note that QuestsGUI may not be compatible with this development build.
