### ISSUE TITLE
Completed missions

### ISSUE THREAD

**Issue by Luisomar0361** [PikaMug/Quests#1384]
**What is your Quests version / build number (do _not_ say "latest")?**

Build 141 (Tue Aug 04 02:34:19 UTC 2020)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
the error I am going to report does not appear in the console

It happens when you cook an item in any oven, if one of the missions requires melting iron, for example, you fill your inventory with any object and try to drag or place it in your inventory with shift click, the item will remain in the oven but it will have taken you as mission completed. this is annoying if the mission is done daily.

Example
https://youtu.be/J2KP7Yp2npo

this error happens with everything that is melted / baked
also with crafts

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/FFAU74gM

**Comment by PikaMug** [comment]
Thanks for the report. Just to clarify, this only happens if the player's inventory is full, correct?

**Comment by Luisomar0361** [comment]
Yes, in this way the item stays in the oven, and the mission appears as completed, if the mission is repeatable they can leave the oven and do it daily, it can also be done with crafting

**Comment by PikaMug** [comment]
So I've looked into this and it seems the only options are to cancel the click event (which may disrupt other plugins) or drop the item on the ground (less likely to disrupt other plugins, but the player may not realize this has occurred and the item could be left to despawn or get pickup up by another player). Therefore, it seems most preferable that the item should stay within the Furnace, which is hopefully protected by a lock or anti-grief plugin. Alternatively, consider using a backpack plugin which can transfer the item to an additional player inventory.
