### ISSUE TITLE
I can make turkish tutorials 

### ISSUE THREAD

**Issue by xxpatatesfirlatan3000** [PikaMug/Quests#1385]
Hey! I can make turkish tutorial of your DeluxeCombat plugin if you want.

**Comment by xxpatatesfirlatan3000** [comment]
i just want to deluxecombat license.
i have video editing experience, i have nice mic, my PC is good. so i can make high quality turkish tutorial.
also i can translate admin menu GUI or any messages.

**Comment by PikaMug** [comment]
I am not the developer of DeluxeCombat; you have the wrong issue tracker.
