### ISSUE TITLE
effect-locations bug

### ISSUE THREAD

**Issue by Prebuz** [PikaMug/Quests#1389]
**What is your Quests version / build number (do _not_ say "latest")?**

Mainly using version 3.9.5. Tried build #141 also and had the same issue.

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

The problem occurs when you create an action with effects. It gives you an error with the effect-locations and disables the action entirely.

Basically just having this in the config:

  Prebtest:
    effects:
    - GHASTSHRIEK
    effect-locations:
    - world 1297.0 171.0 -1252.0

https://pastebin.com/tjDzUXqv

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for your report. I was unable to replicate this issue on the latest development build.

Please share your example quest & actions using Pastebin to reopen this issue, as this is likely a formatting problem.

**Comment by PikaMug** [comment]
@Prebuz Nevermind, I was able to replicate it after all. Please try the following build:
https://ci.codemc.io/job/PikaMug/job/Quests/142/
