### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by HelpMePleaseI** [PikaMug/Quests#1391]
**Where else have you looked for answers to this question?**
Google
**Share your question with as much detail as possible?**
Hello
I can't figure out how to work with modules. Can you use them to link quests with other plugins? Or how does it work?
**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
> Can you use them to link quests with other plugins?

Yes.

What modules are:
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules

How to create modules:
https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API
