### ISSUE TITLE
generated an exception whilst handling conversation input

### ISSUE THREAD

**Issue by kinukin** [PikaMug/Quests#1393]
**What is your Quests version / build number (do not say "latest")?** 
3.9.5

**Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?**
Sometimes when I'm trying to create a quest (/quests editor) the chat glitches out and I can't choose/type any of the quest editor options and on the console I get this error:

generated an exception whilst handling conversation input 

(Sorry I couldn't post the console error into pastebin because I restarted the server and now the error is gone, but I do get it frequently/sometimes.)

**If applicable, can you provide an example quest from quests.yml using Pastebin.com?**

**Comment by PikaMug** [comment]
Thanks for your report. Unfortunately, I need the exception in order to diagnose this. It should be available in your server's `logs` folder as a .gz file you can unzip with WinRAR or 7zip. Feel free to reply with a Pastebin link to re-open this issue.

**Comment by kinukin** [comment]
@PikaMug 
Thanks for the tip,

I uploaded the exception to  pastebin.com.

https://pastebin.com/E2YyxrLh

**Comment by kinukin** [comment]
> Thanks for your report. Unfortunately, I need the exception in order to diagnose this. It should be available in your server's `logs` folder as a .gz file you can unzip with WinRAR or 7zip. Feel free to reply with a Pastebin link to re-open this issue.

@PikaMug
Thanks for the tip,

I uploaded the exception to pastebin.com.

https://pastebin.com/E2YyxrLh

**Comment by PikaMug** [comment]
@kinukin It seems that you're editing an invalid item reward. Please try the following development build and, if the issue still occurs, reply with the new console error/warning.

https://ci.codemc.io/job/PikaMug/job/Quests/143/

Note that QuestsGUI may not be fully compatible with this build.
