### ISSUE TITLE
How to give a quest to a player instead of 'forcing it'?

### ISSUE THREAD

**Issue by kinukin** [PikaMug/Quests#1394]
**Where else have you looked for answers to this question?**
Quests Community Discord

**Share your question with as much detail as possible?**
How to give a quest to a player instead of 'forcing it'?

So I know you can give a quest to a player (/questadmin give %username% quest) but it 'forces them into doing quest' meaning that you can repeat the quest again. However what I want is to just give the quest to the player as if accepting the quest from an 'NPC'.

Is there a way to do this?

**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
Consider running _/quests take <quest>_ with the `command-on-entry` flag of [WorldGuard Extra Flags](https://www.spigotmc.org/resources/worldguard-extra-flags.4823/) (not affiliated). Alternatively, keep an eye on #1245
