### ISSUE TITLE
Unexpected exception, we believe its causing considerable lag on our server

### ISSUE THREAD

**Issue by oplegoman** [PikaMug/Quests#1398]
**What is your Quests version / build number (do _not_ say "latest")?**
 Plugin Quests v3.9.6+4bdd689
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
at this point have no idea how to replicate it, but we updated to 1.16 today and we get thrown this error;
[06:51:00] [Craft Scheduler Thread - 3386/WARN]: [Quests] Plugin Quests v3.9.6+4bdd689 generated an exception while executing task 6048802
https://pastebin.com/S9ekbdAX
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
None

**Comment by PikaMug** [comment]
Thanks for the report. Unfortunately, that does not appear to be the full error. There should be references to specific lines of code either before or after the section you posted. Please either provide the relevant section, or the full log.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
