### ISSUE TITLE
2+ Item requirements true, itemput in offhand/head then take quests,items in inventory that meet requirement will be taken but cannot take quest

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1402]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-3.9.6#143

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No console errors

In the following graph, there are two items requirement and if player meet the requirement, the item will got taken andn the quest be can taken.
However during my test i tried to put item A(shull) in my head and item B(skull) in inventory slot, the quests did the following things:
1took my item B and didn't take item A
2show error message that i got item in head/offhand
3quest did not successfully received 

For simple, if there is multiple item requirement and needs to be removed, if the player put 1 item in head/offhand and other item that is required in inventory then take the quest, the quest will take all other required items but the 1 in head/offhand and show warning message. The player didn't take the quest but items were taken by the quest.

![image](https://user-images.githubusercontent.com/61608872/91935883-3fe69080-ed21-11ea-9270-3befc875b410.png)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/vCK6SD5t

**Comment by PikaMug** [comment]
This is not a bug; it is intentional that Quests will not remove items from the player's armor or off-hand slots.

**Comment by hkkongou** [comment]
> This is not a bug; it is intentional that Quests will not remove items from the player's armor or off-hand slots.

read my sentence again, i am not talking about quest "NOT REMOVEING" items from player's armor or off-hand slots.
Lets say there is 2 items, 1 put in head/offhand , 1 put in otherplaces, quest of course cannot remove items from offhand/head, but it removed things from otherplaces.

I will post this bug again if you not trying to read or fix this bug again

**Comment by PikaMug** [comment]
@hkkongou In the quests.yml graphic you shared, there are 2 item requirements. So, it makes sense that 1 item would be taken, while the other 1 would not and shows the warning message. Moving the remaining item into a normal inventory slot and trying again should start the quest.

**Comment by hkkongou** [comment]
> @hkkongou In the quests.yml graphic you shared, there are 2 item requirements. So, it makes sense that 1 item would be taken, while the other 1 would not and shows the warning message. Moving the remaining item into a normal inventory slot and trying again should start the quest.

sorry, no it doesn't, it still asking me to give the one item which has given to to the quest

**Comment by hkkongou** [comment]
> @hkkongou In the quests.yml graphic you shared, there are 2 item requirements. So, it makes sense that 1 item would be taken, while the other 1 would not and shows the warning message. Moving the remaining item into a normal inventory slot and trying again should start the quest.
Thats the problem i am saying.
because thats no way for me to give item to the quests again as it already took my item but don't count me finished half of the requirement and require me to give the another one.

So the one given item is wasted.

**Comment by PikaMug** [comment]
@hkkongou Thanks for the deeper explanation. Please try https://ci.codemc.io/job/PikaMug/job/Quests/145/

Note that this build may not be compatible with [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) if you are using that currently.

**Comment by hkkongou** [comment]
> @hkkongou Thanks for the deeper explanation. Please try https://ci.codemc.io/job/PikaMug/job/Quests/145/
> 
> Note that this build may not be compatible with [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) if you are using that currently.
thank you for you hard work to debug.
I will check that out soon.

Once again, many thanks, I am much obliged to you for your help.
