### ISSUE TITLE
Quest API Access

### ISSUE THREAD

**Issue by itsaderm** [PikaMug/Quests#1403]
**Where else have you looked for answers to this question?**
Discord & The Wiki

**Share your question with as much detail as possible?**
How can I get the current quest a player is doing or just a method to cancel it?

**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
Players may hold multiple quests simultaneously. See https://github.com/PikaMug/Quests/blob/cff11e2dae66f6446798fa57638cb84d77638db3/main/src/main/java/me/blackvein/quests/Quester.java#L292

I'm not sure what you meant by "cancel it" but there is a #quitQuest method if the quest has already been started, or a number of cancellable events which may interest you https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Bukkit-Event-API
