### ISSUE TITLE
Daily Quests that change each day.

### ISSUE THREAD

**Issue by Klawdek** [PikaMug/Quests#1404]
**What does your feature do?**
Daily Quests like there is in battlepass.   The quests do not have to be joined by the player.   Every 24 hours new quest(s) begin. If any player meets the quests goals within the time frame  they get the reward.  The quests change each day.

**How would people use it?**
Players would not have to select and join these quests like they usually do.  They win the rewards if they complete the tasks within the time frame.  Some kind of notice could be given in chat letting them know what the daily quest is and of course there would be the ability to see it with commands.

**Comment by PikaMug** [comment]
I do not know what "battlepass" is, but it sounds like you want to assign all players a quest simultaneously. This can be accomplished with a Denizen script, perhaps alongside Depenizen.
