### ISSUE TITLE
NPC Deliveries with Enchanted Items ignore Durability

### ISSUE THREAD

**Issue by nelluc9** [PikaMug/Quests#1408]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.6
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
For the NPC Deliver objective, durability will be ignored on enchanted items with a max durability value. Meaning if the required Diamond Pickaxe quest item needs to have Curse of Vanishing, all diamond pickaxes with Curse of Vanishing, whether they are at full or low durability, count for the quest.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/DC1wptwK

**Comment by PikaMug** [comment]
Thanks for the report. What is your server's Minecraft version?

**Comment by nelluc9** [comment]
We’re running 1.16.3.

**Comment by PikaMug** [comment]
I have been unable to replicate this issue on Minecraft 1.16. Using your example quest, I spawned a Diamond Pickaxe with Curse of Vanishing, proceeded to damage a few blocks of stone with it, and then tried to turn it in for the quest. The item was refused on grounds of durability not matching.

![vanishing](https://user-images.githubusercontent.com/2267126/96229165-89eba480-0f64-11eb-97f1-49e5a5bfefa3.png)

Feel free to request re-open should more information come to light. Thanks!
