### ISSUE TITLE
New Release Candidate Crashing On Startup

### ISSUE THREAD

**Issue by P-paj** [PikaMug/Quests#1409]
Task #901 for Quests v4.0.0-rc.1-b146 generated an exception
18.09 11:09:18 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: -1
18.09 11:09:18 [Server] INFO at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_252]
18.09 11:09:18 [Server] INFO at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_252]
18.09 11:09:18 [Server] INFO at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2461) ~[?:?]
18.09 11:09:18 [Server] INFO at me.blackvein.quests.Quests.loadQuests(Quests.java:1483) ~[?:?]
18.09 11:09:18 [Server] INFO at me.blackvein.quests.Quests$2.run(Quests.java:542) ~[?:?]
18.09 11:09:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-191]

Plugin Versions: Newest RC of Quests and Quest GUI (4.0.0-rc.1, 0.19)
Server Version - Paper (191)

It shows green and working in the /plugins list - but says "Plugin is currently loading. Please try again later!" when any command is used.

**Comment by PikaMug** [comment]
Thanks for the report. The problem seems to be one of your Deliver an Item quests is missing a delivery message. I'll push a commit which should modify the error to tell you which quest is affected.

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/147/
