### ISSUE TITLE
Bug Report - Internal Error and Console errors

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1412]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.0-rc. 1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Hello the quest plugin seems to work fine when I tested it out but it doesn't work on my public production server. When I type /quest an internal error shows up.

Console Error: https://gyazo.com/3f173e255ad1e3cb0034724487b3c21c

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

N/A (I provided the screenshot above)

**Comment by PikaMug** [comment]
@AccioAce Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/149/
