### ISSUE TITLE
MMO Items delivery Quest No Longer Works.

### ISSUE THREAD

**Issue by Ayon224** [PikaMug/Quests#1413]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.0-rc.1
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No Errors
Since updating to 1.16.2 and then 1.16.3 my quests that involve either a MMOItem to start or an MMOItem Delivery item, No longer work. I am using the npc delivery option and the item requirement options. im not using any moduals
This has worked in all previous versions.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/8wC8H3HC

**Comment by PikaMug** [comment]
Thanks for the report. Unfortunately, either the item data or the way in which MMOItem process the item data has changed during your upgrade. You will need to reassign the items to each of your quests.

Please note that using items generated by other plugins without a module is not officially supported.
