### ISSUE TITLE
Is it possible to play sound through actions.yml?

### ISSUE THREAD

**Issue by Faishun** [PikaMug/Quests#1416]
So, I want to create an action that allows server to play sound as a Finish Quest action in "Edit Stages".
I've tried something like playsound minecraft:entity.player.levelup ambient <player> <player_x> <player_y> <player_z>, playsound minecraft:entity.player.levelup ambient <player> ~ ~ ~ , playsound minecraft:entity.player.levelup ambient <player> %player_x% %player_y% %player_z% using placeholders, but they don't work. It says that "The Sound is too far away to be heard" whenever I use "~" and "Error in command string" or something like that whenever I try to use player coordinates placeholder. Any suggestions?

**Comment by Faishun** [comment]
I have "Player" placeholders in Papi list downloaded, those placeholder coordinates work in another plugin, but not in actions.yml for Quests

**Comment by PikaMug** [comment]
Thanks for your inquiry. Only the sounds/effects available under the Effects submenu are currently available. I'll look into whether other sounds are an option and get back to you.

**Comment by Faishun** [comment]
> Thanks for your inquiry. Only the sounds/effects available under the Effects submenu are currently available. I'll look into whether other sounds are an option and get back to you.

Actually, the problem has been solved by finding a command with variables which include <player> only from your plugin. One and only I could find is /execute at <player> run playsound minecraft:... <player>. In such case, parameter "at" specifies the location, so there is no need for placeholders in such case for this command for this plugin.
