### ISSUE TITLE
Straightforward indication NULL

### ISSUE THREAD

**Issue by BearLeonLight** [PikaMug/Quests#1418]
**Where else have you looked for answers to this question?**
GOOGLE、The settings of the installed software are compatible with the search

**Share your question with as much detail as possible?**
He kept popping up a message repeatedly. I tried all my known methods and checked on the Internet, but I couldn't find any problems. I want to ask you here. Is there a way to deal with this?
Below is the message that keeps popping up
```
Task #703 for Quests v4.0.0-rc.1-b150 generated an exception
java.lang.NullPointerException: null
```
This is an error message, the entire log file has too much text to paste
https://pastebin.com/raw/0JkVDtXC

**If applicable, which class or method is this in reference to?**
I don't know what I want to fill in

**Comment by PikaMug** [comment]
Thanks for the report. Please give the following build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/151/

**Comment by BearLeonLight** [comment]
Thank you, there is no problem in the current test.
