### ISSUE TITLE
Paper 1.14.4 - Quests 4.0.0-rc.1

### ISSUE THREAD

**Issue by EmnichtdaYT** [PikaMug/Quests#1419]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.1
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
On SpigotMC it says 4.0.0 is compatible with MC 1.14.4 but when I start the server it doesn't work, the plugin can't find ItemStack. Default configs, default everything.

https://pastebin.com/ctuAQ2eB

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. It would appear you used an item for a Condition, then downgraded your server from a newer version of Minecraft. This is not supported by CraftBukkit/Spigot and is not something Quests can overcome. You must remove the item Condition from your _quests.yml_ and _conditions.yml_ files to alleviate the issue.

**Comment by PikaMug** [comment]
On second thought, it's possible the default _conditions.yml_ file is the cause, so I'll re-open the ticket. The aforementioned solution is still recommended.

**Comment by EmnichtdaYT** [comment]
As said, default configs.

**Comment by PikaMug** [comment]
@EmnichtdaYT Sorry for the confusion. Please try the following build. If you have not already done so, remove the item condition from the _conditions.yml_ first (or delete the file entirely).

https://ci.codemc.io/job/PikaMug/job/Quests/153/
