### ISSUE TITLE
When I set an multiple types of items to be delivered to an NPC in an action, it says "All required lists must have the same number of entries!"

### ISSUE THREAD

**Issue by Hunt231** [PikaMug/Quests#1422]
I'm using Quests version 4.0.0-rc.1 on Minecraft 1.16.3
When I set an action for a quest, and choose multiple items to be delivered to an NPC, it says "All required lists must have the same number of entries!"

I'm kinda new to quests, but please help.

For example, I'll press add items, load item in hand, and then press done. Then repeat the same process but with a different item. Then the error message shows up.

**Comment by PikaMug** [comment]
You must set an equal number of NPC IDs as the number of items selected/loaded.
