### ISSUE TITLE
Support For Custom BlockDatas

### ISSUE THREAD

**Issue by BurakDorman** [PikaMug/Quests#1424]
**What does your feature do?**
Custom BlockDatas support. Mushroom blocks, Chorus plants and some other blocks contain BlockDatas.

**How would people use it?**
We are able to adjust different textures to different block states of some blocks. We would be able to use these blocks in quests, if it is supported.

**Comment by PikaMug** [comment]
Thanks for the request. This is best left a module, which you can learn more about at https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules
