### ISSUE TITLE
/questadmin reload not working with questsgui

### ISSUE THREAD

**Issue by Avold** [PikaMug/Quests#1426]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.0-rc.1 and QuestsGUI-0.19

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The plugin sent this error in console and said to check console from in game:
19.10 23:50:56 [Server] INFO AnonymousAlexa issued server command: /questadmin reload
19.10 23:50:56 [Server] WARN java.lang.NullPointerException
19.10 23:50:56 [Server] WARN at me.blackvein.quests.Quester.getBaseData(Quester.java:3003)
19.10 23:50:56 [Server] WARN at me.blackvein.quests.Quester.saveData(Quester.java:2821)
19.10 23:50:56 [Server] WARN at me.blackvein.quests.Quests$3.run(Quests.java:1251)
19.10 23:50:56 [Server] WARN at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
19.10 23:50:56 [Server] WARN at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
19.10 23:50:56 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
19.10 23:50:56 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19.10 23:50:56 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by PikaMug** [comment]
Thanks for the report. At what point are you running the command? Is a GUI window still open?

**Comment by Avold** [comment]
So my moderator said they were doing the command while the GUI window was closed.

**Comment by PikaMug** [comment]
@Avold Please give this build a try and, if the issue persists, reply with the newly-generated error:
