### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by lemsol69** [PikaMug/Quests#1433]
**What is your Quests version / build number (do _not_ say "latest")?**
v4.0.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The console is spamming the following messages: https://pastebin.pl/view/9953ddc0
Any idea how to fix this? Just tried installing quests yet it won't let me run simple commands like /quests editor.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for your report. The partial error you've shared is typically preceded by more detailed output, which I don't see in your paste. Please try the latest Quests 4.0.0-rc.2 and, if that doesn't resolve the issue, check again for the full error.

**Comment by lemsol69** [comment]
We are using the latest version of the plugin and running on 1.16.2. 

The console is connected to our discord, where it shows up as this: https://pastebin.pl/view/7d181485
(Should have probably included that to begin but console is very messy at the moment). This is the only error message we are receiving.

**Comment by PikaMug** [comment]
@lemsol69 That is no longer the latest version. Quests 4.0.0-rc.**2** is the latest.

**Comment by mercurialmusic** [comment]
Getting the exact same spam on Quests 4.0.0-rc.2 using Paper 251 (1.16.3). There was another report on the plugin discussion thread as well: https://www.spigotmc.org/threads/quests.47772/page-84#post-3981919. There is no error other than exactly what is shown in OP's paste. The plugin was entirely non-functional, no commands work. Had to roll back to 3.9.5.
