### ISSUE TITLE
https://hastebin.com/upuxajorit.md 

### ISSUE THREAD

**Issue by ducdzz61** [PikaMug/Quests#1435]
error spam: https://hastebin.com/upuxajorit.md 

My server version: paperspigot 1.12.2
ver pl: 4.0.0-rc.2

**Comment by PikaMug** [comment]
@ducdzz61 Thanks for the report. Please backup your _Quests/data_ folder and give the following build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/158/
