### ISSUE TITLE
Visibilty of quests with planner

### ISSUE THREAD

**Issue by Skyfighter1** [PikaMug/Quests#1438]
**What does your feature do?**
It would be good if there would be an option for quest to deactivate the visibility if players can't take the quest because of the planner.
Example:

If sb. want to make daily quests and every day it should be visible only the one/or more from the day it isn't possible at the moment...
It would be a cool feature and option for the quest.
This option could in the planner look like:
visible-if-locked

**How would people use it?**
Owners can decide if they want to use it or not, but I think for multiple things this feature would be good.

**Comment by PikaMug** [comment]
Thanks for the suggestion. While it is global in _config.yml_, and not in the Planner, I believe `ignore-locked-quests: true` is what you're looking for.

**Comment by Skyfighter1** [comment]
No sry but this isn't what this I am searching. I already have this option on zrue but still quests which I can't do because of the planner are visible...

**Comment by PikaMug** [comment]
@Skyfighter1 Sorry for the misunderstanding. It seems what you are requesting is a duplicate of #1361
