### ISSUE TITLE
Console Spam 

### ISSUE THREAD

**Issue by mercurialmusic** [PikaMug/Quests#1439]
**What is your Quests version / build number (do _not_ say "latest")?** Quests v4.0.0-rc.2-b158 on Paper 259 (1.16.4)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** Massive console spam again: https://gist.github.com/mercurialmusic/92c32888557ee5f8dc8d9c9211a455d0 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
N/A

**Comment by PikaMug** [comment]
@mercurialmusic Thanks for the report. Please backup your entire Quests folder and try https://ci.codemc.io/job/PikaMug/job/Quests/159/

**Comment by SlimeDog** [comment]
Errors still exist with
Spigot 1.16.4
Quests 4.0.0-rc.2-b159

The errors occur on player connect.

**Comment by mercurialmusic** [comment]
Confirming still present and on player connect. It's not every player, so I'm guessing it's just those with active quests (had some minor issues with the same before), but I can't confirm because the entire plugin just fizzles out at that point.

**Comment by PikaMug** [comment]
@mercurialmusic Thanks for your patience. The issue mainly applies to servers with a large player count, making this difficult to test solo. Please give the following build a try and let me know of any new errors:

@SlimeDog Thanks for tuning in. Please try the following build and share any new errors:

https://ci.codemc.io/job/PikaMug/job/Quests/160/

**Comment by SlimeDog** [comment]
I encountered this issue with no players, but inconsistently.

I have not encountered the issue with two restarts of build 160.

**Comment by mercurialmusic** [comment]
So far so good on b163, will update if that changes. Thanks!
