### ISSUE TITLE
Ability to disable message from NPC

### ISSUE THREAD

**Issue by itslukemango** [PikaMug/Quests#1443]
**What does your feature do?**
Disables a message that doesn't need to pop up under certain circumstances.
We'd request the ability to disable this: https://lukemango.com/mZCXO.png

**How would people use it?**
In the config preferably, toggle it with true or false.

**Comment by PikaMug** [comment]
Could you explain further what those “certain circumstances” are? Generally speaking, the player should receive feedback as to whether or not a quest was previously available.

**Comment by itslukemango** [comment]
> 
> 
> Could you explain further what those “certain circumstances” are? Generally speaking, the player should receive feedback as to whether or not a quest was previously available.

We're using NPC's that are essentialls Vendors (have GUIs not associated with quests) in our spawn that are linked to quests, and everytime a player wants to use the NPC, that message will appear.

**Comment by CaptainAlienHD** [comment]
You can prevent that in stage instead talking to NPC. Just set-up reach location infront of NPC +- 3 blocks radius. And it would work the same without using the NPC's

**Comment by PikaMug** [comment]
I've thought about this some, and I really can't imagine a positive experience for players whom forget they've already taken a quest to not receive feedback. This situation is more easily remedied by the idea from @DeadlykillOfficial or by simply having a separate NPC for the quest - perhaps a shopkeeper's assistant or pet animal.

**Comment by Maitlans** [comment]
@itslukemango Use https://www.spigotmc.org/resources/message-editor.82154/ It allows you to change or remove unchangeable text.
