### ISSUE TITLE
Quest Actions Issue

### ISSUE THREAD

**Issue by emohobo** [PikaMug/Quests#1445]
Version - 4.0.0 - rc2
 
Using Quest Actions to give specific items to players. For whatever reason, several of the actions won't execute. They'll execute properly one time if you make a new quest purely to test, however after that it will no longer work. Items range from paper to tripwire hooks etc. With or without lore as well. Will post the main quest that I'm using for this plus the actions.yml if needed for verification.

Actions > https://pastebin.com/tyJBtYye
Quest in question > https://pastebin.com/DrqaKg6r

**Comment by PikaMug** [comment]
Thanks for the report. Not sure I completely understand. Are you saying an Action linked to multiple quests only works for one quest?

**Comment by emohobo** [comment]
So it's gonna be a lengthy description lol.

A quest has a stage where for instance it runs the action QuestsSeal. This action is a give player item. Item is a piece of paper named Quest Master's Seal. It's set up as a finish action so that once the player has talked to the NPC, action runs to give them their piece of paper. However, either the action is failing to run or it's running but not giving the paper. I've tried with multiple different actions *recreating the action, creating a new action etc.* and it won't run. I then created a completely new quest as a test. Set up the steps just the same, and the first time the quest was ever ran it completed the action. However after both resetting my quest progress and retrying it and having a completely different player attempt it, it would no longer run the action correctly. So it will work one time for one player, then never work again whether its the old quest or a new one I made in order to test its functionality. No matter the item, lore, display name etc. I'd be happy to run through the whole process should you need it whether in discord or however you'd like in case you're unable to replicate it for any reason!

**Comment by PikaMug** [comment]
I followed your description by creating an Action of the same name and type, with a Paper renamed to Quest Master's Seal. However, after speaking to an NPC the item was given, then I reset and got the same thing multiple times without issue.

![paper](https://user-images.githubusercontent.com/2267126/98591162-d85b3d00-229d-11eb-800a-f2a1dac90ab1.png)

The quest I created was only a single stage/objective, but you provided an example quest, so I'll try adapting that and get back to you. Since the Action was identical, it may have something to do with the quest itself.

**Comment by emohobo** [comment]
I rewrote the quest in its entirety and it still is having the issue. I made a test quest to test each individual action and they all executed perfectly, yet for some reason no matter what when doing the quest I provided it fails to execute a single action the whole time.

**Comment by PikaMug** [comment]
@emohobo Thanks for your patience. The issue was that, if a stage has a delay but is not the final stage, the plugin would forego running the finish action entirely. This has been corrected in the following development build:
https://ci.codemc.io/job/PikaMug/job/Quests/164/
