### ISSUE TITLE
Are players able to give out quests?

### ISSUE THREAD

**Issue by 0H4rl3qu1n0** [PikaMug/Quests#1446]
**Where else have you looked for answers to this question?**
The Discussion on SpigotMC
**Share your question with as much detail as possible?**
Is it possible for players to give quests to other players with both of the players's consent?
Like if one player needs 1000 stone blocks and they'd pay money for someone to do it. And someone else finishes that quest and claims the reward. So it's more like exchanging jobs for money obo.
**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
Assuming a quest has already been created by an administrator, one could give their players the `quests.admin.give` permission which would allow them to hand out quests with _/questadmin give [player] [quest]_. Bear in mind, however, that this would allow them to give out **any** quest, whether they have actually been paid to or not. For a system better tailored to what you're trying to do, consider using the [Jobs](https://www.spigotmc.org/resources/jobs-reborn.4216/) or [BountyHunters](https://www.spigotmc.org/resources/bountyhunters-legacy.40610/) plugins (not affiliated).

**Comment by 0H4rl3qu1n0** [comment]
Jobs was exactly what i was looking for. Thank you!
