### ISSUE TITLE
spam (1.12.2) pls fix

### ISSUE THREAD

**Issue by ducdzz61** [PikaMug/Quests#1447]
link: https://hastebin.com/izupixakoz.properties
ver server: paperspigot 1.12.2
ver pl: Quests v4.0.0-rc.2-b158 (download by #1435)

from the time I used the quests plugin until now all versions have bugs with 1.12.2
Can you fix it please? I have been waiting for several months to use it but still have continuous errors

**Comment by PikaMug** [comment]
This has already been resolved, see #1444
