### ISSUE TITLE
Override Objective Counter

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1448]
**What does your feature do?**

You're able to write %count% within your custom objective name so players know the amount of a certain task they have to do or have left.

**Comment by DeadlykillOfficial** [comment]
This could also be usefull for Override Display function whenever you have like objective "Kill Zombie 0/10" You can change it to
"Find and kill some zombies: %count%/10" - It could be also usefull for Mythicmobs Expansion if you have Rare mobs instead just saying "Kill mobname 0/10" You could specify more the objective and still provide progress of it.

**Comment by PikaMug** [comment]
I agree that an overridden objective display should show a progress count (regardless of a variable), but the way it's coded right now doesn't make this super easy. If anyone cares to make a Pull Request, the relevant method is https://github.com/PikaMug/Quests/blob/327770a2b71828492cd83aa32b328b805260b138/main/src/main/java/me/blackvein/quests/Quests.java#L794-L1324

**Comment by PikaMug** [comment]
Closing due to lack of community interest. Best solution at the moment is to use a module which allows setting the progress count for a given objective type (i.e. https://lectern.browsit.org/resources/resource/22-craft-objective-improved/).
