### ISSUE TITLE
 Hello, how do I make a reward from the quests to be a command to be written by the console?

### ISSUE THREAD

**Issue by s7an1slaw** [PikaMug/Quests#1450]
Hello, how can I make a reward from the quests to be a command to be written by the console and each quest to be passed only once, and not to be repeated?

**Comment by PikaMug** [comment]
There is an option for command rewards under Edit Rewards. The command(s) will be run from the console. So long as you do _not_ set a player cooldown under Edit Planner, the quest cannot be repeated.
