### ISSUE TITLE
Questpoints?

### ISSUE THREAD

**Issue by Maxderdachs** [PikaMug/Quests#1452]
Hey guys,
I like ur Quest Plugins very much!
But one Question:
What can I do with the QuestPoints? Is it able to create a shop with this, where you can buy heads ore something?
If there are some possibilitys please answer :D

~Max

PS: I already searched for an answer on YouTube and Google, but there is no Answer.
PPS: I´m so sorry for my bad english :)

**Comment by PikaMug** [comment]
A minimum number of Quest Points can be set as a Requirement for a quest. There is no other functionality at this time, however API methods do exist for which a developer could easily make a plugin to function as you've described.
