### ISSUE TITLE
silk touch returning chat errors

### ISSUE THREAD

**Issue by elaineandsparky** [PikaMug/Quests#1453]
**What is your Quests version / build number (do _not_ say "latest")?**

dev build 164, a dev build i uploaded yesterday and 4.0.0-rc.2 from spigot. version 3.9.5 does not have this issue (but i'm stuck with the month issue from yesterday again).

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Quests are returning chat errors when using silk touch. Even if i'm not trying to do a quest, if i have a quest loaded and use a silk touch tool, it returns the error. For example, selecting a quest to break birch logs returns the error if i use silk touch on birch logs, oak logs and even using shovel to get grass. Not having any quests active removes the errors.  

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

![image](https://user-images.githubusercontent.com/69724087/99039734-c6b8b480-257f-11eb-9837-9c0ea0d10d23.png)

**Comment by PikaMug** [comment]
This is intentional design, advising the player that the Break Block objective cannot be progressed using Silk Touch. The player may either switch to a different tool or quit the quest to return to it later.

If you would prefer to disable this functionality, you may do so under Edit Options in the quest editor. In doing so, players will be able to break blocks during that quest using Silk Touch, which may yield unexpected results.

**Comment by elaineandsparky** [comment]
that may be an intentional design but should only really be suited for the quest they are trying to do. if someone wants to get grass blocks with a silk touch shovel they shouldn't be told they can't complete the birch quest! they are not trying to complete that quest!
People do not take a quest and then complete it straight away without doing anything else inbetween doing the quest. they do a bit then do something else then come back to it later.
This is going to be a major problem for us as we have over 100 quests which people load up many of at the same time. it pretty much means that if players chose to engage with quests then silk touch tools are useless as nobody wants that message every time they break a block!
Please reconsider this as it was just fine they way it was before
