### ISSUE TITLE
no option to turn off the silk touch spam

### ISSUE THREAD

**Issue by elaineandsparky** [PikaMug/Quests#1454]
**What is your Quests version / build number (do _not_ say "latest")?**

4.0.0-rc.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

No option to turn off the silk touch spam (it should be option 3 in the general section but has null instead)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

![image](https://user-images.githubusercontent.com/69724087/99060539-173c0c00-2598-11eb-8478-17e7f9f7ee05.png)

**Comment by PikaMug** [comment]
This is not a bug; your language file needs to be updated. Either copy the lines from _strings_new.yml_ into _strings.yml_ for your desired language, or just regenerate the _/lang_ folder.

Regardless, the Option will work just fine even if the language string displays NULL.
