### ISSUE TITLE
QuestPoints

### ISSUE THREAD

**Issue by Maxderdachs** [PikaMug/Quests#1456]
Hey guys,
I am so sorry that I ask another question,
but I hope you can answer me! :)

I will do a quest, in which the Player must pay some Points. 
When the Player has 100 Points and he want to do a task, is it able, that he has to pay 50 Points for this quest?
That he has after the quest only 50?
I am so sorry for my bad Englisch.
Thanks ~Max

**Comment by PikaMug** [comment]
Thanks for the question. During normal use, Quest Points can only be added to the player's balance, not removed. If you really want to take away points, you could create an Action which runs the command _/questadmin takepoints [player] [amount]_

However, bear in mind that the Points will not be given back if the player decides to quit your quest.
