### ISSUE TITLE
item requirement amount >127 will turn in to air 

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1457]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests-4.0.0-rc.2.jar #164

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
item requirement > 128 will fail and become air requirement

if the item requirement is 127 or below, it works fine, however, if it is >128, it becomes air and turns out the requirement become don't care.
I understand that usually using the in game editor may not able to set 128 or above, however , i use yml to make quest usually and most of my quests will require hand in 128+ items to the npc, this "bug" will make almost half of my quests (more than 100) will have to re make 

![image](https://user-images.githubusercontent.com/61608872/99138319-d8c35180-266a-11eb-9ebf-a114485a7fba.png)

![image](https://user-images.githubusercontent.com/61608872/99138314-d3660700-266a-11eb-80ad-0bbff84105c4.png)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/JaBD6AMj

**Comment by PikaMug** [comment]
Use two stacks of 64. This "bug" is a limitation of Bukkit serialization.

**Comment by hkkongou** [comment]
> Use two stacks of 64. This "bug" is a limitation of Bukkit serialization.
two stacks of 64 works for stage but not for item requirement.
it is impossible for using multiple item requirement to set requirement >64, repeating item requirement will only check for maximum amount of 64 but not 65+
![image](https://user-images.githubusercontent.com/61608872/99340559-35b94480-28c3-11eb-8c65-837af91ff0d2.png)

**Comment by hkkongou** [comment]
> Use two stacks of 64. This "bug" is a limitation of Bukkit serialization.

as you added won't fix tag, does that mean item requirement that >64 is impossible in 1.16?

I understand stage can use multiple submitting to reach total of 64+ items submitted, but requirement does not work like that.

**Comment by PikaMug** [comment]
Any stack greater than 64 is considered invalid.

Item requirement should accept multiple stacks; I'll look into it.

**Comment by hkkongou** [comment]
> Any stack greater than 64 is considered invalid.
> 
> Item requirement should accept multiple stacks; I'll look into it.

thank you for reopen the this post

i understand stacking greater than 64 is invalid, as it is impossible for normal player to hold that amount of item.
i have tried using in game editor to type number >64, it does not work, which make sense. 
I can only try 64 and multiple requirement which cannot create a requirement of holding 64+ items at the same time( the above one mentioned)

**Comment by PikaMug** [comment]
@hkkongou Should be working as of https://ci.codemc.io/job/PikaMug/job/Quests/173/

**Comment by hkkongou** [comment]
![image](https://user-images.githubusercontent.com/61608872/101269429-cd66d000-37a9-11eb-95eb-348dcdaa8623.png)
this happen 

the requirement is not showing and people cannot take the quest
https://cdn.discordapp.com/attachments/696002416239444008/784961940359086161/2020-12-06_09.57.38.png

**Comment by PikaMug** [comment]
@hkkongou Did you re-set the Requirement? It still won't work with a value of 128 - you must use multiple stacks of 64.

**Comment by hkkongou** [comment]
i did re-set the requirement before this fix version release, i turned all requirement > 127 into single 64 requirement for all quest in quest.yml
however it is showing the above error.
i haven't try requirement >65

**Comment by PikaMug** [comment]
Try https://ci.codemc.io/job/PikaMug/job/Quests/177/

If that doesn't improve things, I'll need to see your _quests.yml_ file.

**Comment by hkkongou** [comment]
is fine now
