### ISSUE TITLE
More Quest particles customization

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1459]
**What does your feature do?**
Reworks how "new-quest" setting works, basically it will only appear for when the NPC has a new quest, after the quest is picked up the particle will stop to indicate that the NPC has no more quests, instead a new "active-quest" particle would be used indicating that you have an active quest from that NPC. Another new particle called "finished-quest" would introduce a particle that shows up when you've finished reached a certain point in the quest preferably this setting should be set within a stage.

Each setting has a priority meaning one will show over the other if there's more than one active.
"active-quest" = 0
"redo-quest" = 1
"new-quest" = 2
"finished-quest" = 3

Also another setting to set the amount & speed of particles that are shown per option.
**How would people use it?**

It would make users understand more what's going on, usually MMORPG's quests have something similar to this, I had a few users get confused on why the NPC wasn't giving more quests because it just showed "new-quest" for when there was a new quest and for when it was active.

______
Thanks, keep up the awesome work!

Edit: Had another interesting idea, perhaps all this can be done via "Actions" that change the particles displayed on the NPC. Thought I'd also put it on here as it could be worth it.

**Comment by PikaMug** [comment]
Related to #455 

I will consider shading EffectLib for extended particle support.

**Comment by PikaMug** [comment]
https://lectern.browsit.org/resources/resource/45/
