### ISSUE TITLE
Custom Mobs Suport ? 

### ISSUE THREAD

**Issue by MrJack025** [PikaMug/Quests#1461]
**Where else have you looked for answers to this question?**
-Youtube

**Share your question with as much detail as possible?**
-I Use another plugin caller "BloodNight" on my server to generate custom mobs at night, Your Quest plugin support add custom mobs to the missions ? like: "Kill 5 EnderCreepers in BloodNight" The BloodNight Mobs have id like ToxicCreeper in the config 

**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#need-support-for-other-plugins
