### ISSUE TITLE
Unique quest / add new quests to npcs

### ISSUE THREAD

**Issue by MrJack025** [PikaMug/Quests#1462]
**Where else have you looked for answers to this question?**

Youtube

**Share your question with as much detail as possible?**
I have a little problem

When I create a new quest and add to an npc which already had some they all restart and the player can do all of them again

Is there a way to set a quest to only be done once?

Or add the quests to an npc without it being reset?

**If applicable, which class or method is this in reference to?**

**Comment by PikaMug** [comment]
Iirc if your new quest uses another quest as a requirement or block, that quest will be restarted for all players that have it to avoid them potentially getting stuck if the new terms of the quest are impossible to meet.

If you believe this is not the issue, open a new ticket as a Bug with specific instructions on how to replicate it.
