### ISSUE TITLE
Option for Deliver items while not holding in hand

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1463]
**What does your feature do?**

You're able to deliver items by simply right clicking the NPC if they're in your inventory, if you're tasked with delivering multiple items in a single stage they all would be taken at the same time from your inventory.

**How would people use it?**

Overall makes it easier for end users. And it's sort of how it works in most MMORPG's when delivering items.

___
Thank you.

**Comment by PikaMug** [comment]
Duplicate of #966
