### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by DarkJIuck** [PikaMug/Quests#1464]
When I give myself a quest by the admin team an error occurs and when I reload the plugin or take the quest the NPC gets a warning
![image](https://user-images.githubusercontent.com/74608766/99403891-f243f200-2925-11eb-80c1-cb20699e0205.png)

**Comment by PikaMug** [comment]
"Help me" does not assist me with understanding the issue. I will update your title to something more descriptive.

It appears your _quests.yml_ file may be corrupted. Try running it through a YAML parser such as [this](https://yaml-online-parser.appspot.com/) (not affiliated).
