### ISSUE TITLE
Downloading the source-code

### ISSUE THREAD

**Issue by zManuu** [PikaMug/Quests#1466]
Hey! So I tried coding a dialogue objective for the plugin, but when following this guide (https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Plugin-Compilation) (with InteliJ), some errors appear. 
![Screenshot_15](https://user-images.githubusercontent.com/60520810/99775514-aa80be80-2b0f-11eb-8514-bbfc7c10fa06.png)
Can you maybe help me with that?

**Comment by PikaMug** [comment]
This project is undergoing POM file changes while I implement MySQL. Try compiling against an older version, namely 4.0.0-rc.2

**Comment by zManuu** [comment]
Can you maybe send me, how it would look (something like that: git@github.com:PikaMug/Quests.git)? I'm sorry, but I am not that familiar with Github...

**Comment by PikaMug** [comment]
Just checked and there doesn't seem to be any standing issues with compiling the source. Make sure your IDE is downloading the entire source and not just the dist/main folders.

Also, if you're making a custom objective, consider simply depending on Quests and following https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API#objectives-api
