### ISSUE TITLE
Text spam in worlds not in condition list

### ISSUE THREAD

**Issue by Grievous07** [PikaMug/Quests#1467]
So when I accepted a quest in a valid world, all is good. But if I go to an invalid world thru /mv tp creative. Anytime I do anything (break blocks, right-click blocks, place blocks) it says something along the lines of "You have not met the conditions for [quest]"

**Comment by PikaMug** [comment]
You are missing your Quests version. Please follow the issue template next time.

This is not a bug; the player should simply quit the quest. Alternatively, the "Fail the quest" setting can be enabled in the Condition Editor.

**Comment by Grievous07** [comment]
can there be an option in config to turn that off then, please? I'd like my players to be able to switch from survival to creative worlds and not be spammed with quests chat, and not have to lose all progress.
