### ISSUE TITLE
How to stop quests from being replayed

### ISSUE THREAD

**Issue by mrconno** [PikaMug/Quests#1469]
Hey, so I set up about 5 quests, had my test subject complete them all, everything worked well and dandy, set 1 quest point per quest, anyways when they pulled up the journal it showed all the quests they have completed and 5 quest points. A little bit later they opened up the journal to it saying 5 quest points but no quests done, and when they clicked the npc assigned to the quests they had already done it said they could do it again. I assume it's because there is some kind of timed before you can do a quest again? What I am wondering is how to turn that off and make it so certain quests are one time quests if that makes sense.
Thanks!

**Comment by mrconno** [comment]
would I simple type this in the quests.yml folder?
----------------------------------
 planner:
 redo-delay: -1
----------------------------------

**Comment by PikaMug** [comment]
There is potential for it to be an issue with the Planner settings, but setting -1 value is unlikely to fix the problem. Try having the player log out and back in after completing a quest (which should cause the plugin to save their progress to file). If the quest later reset despite doing that, open a new ticket under "Report a bug" and include all relevant information.
