### ISSUE TITLE
Quests reset after re-log

### ISSUE THREAD

**Issue by mrconno** [PikaMug/Quests#1470]
Hi, 

When a player completes a quest and the server restarts, it says they can do the quest again, however they keep the quest point they got from completing it the first time. I tried what you suggested in my earlier **post[https://github.com/PikaMug/Quests/issues/1469](url)** which was too have the played log out and make in before restarting the server. The quests were still reset, as if they had never done them (besides still having the rewards/ quest points) 
I just want to make it so certain quests can not be replayed.
Thanks!

**Comment by mrconno** [comment]
I'd like to add that the server restarts on its own daily so the issue is all the players would get to redo all the quests everyday ruining the economy of the server and the quest progressions via quest points.

**Comment by PikaMug** [comment]
Thanks for the report. However, you did not follow the issue template. Please create a new ticket including Quests version, example quest, et al.
