### ISSUE TITLE
Where do i get the Quest Object?

### ISSUE THREAD

**Issue by crashback-exe** [PikaMug/Quests#1474]
I need to increment a quest in my Quest Module but i cant figure out where to take the `Quest` object for the fourth argument of `incrementObject()` which takes four arguments. Where do i get the `Quest` Object so?

**Comment by PikaMug** [comment]
If you want to iterate over a player's current quests, see `Quester#getCurrentQuests`

Otherwise, see `Quests#getQuestById` and `Quests#getQuestByName`
