### ISSUE TITLE
addData() is not a method inherited from CustomObjective, how to do so?

### ISSUE THREAD

**Issue by crashback-exe** [PikaMug/Quests#1476]
**Where else have you looked for answers to this question?**
[Here](https://github.com/Blackvein/Quests/wiki/Quests-API#objectives-api)

**Share your question with as much detail as possible?**
I want the quest to prompt the player the block to break to increment the objective, in the example is shown the method `addData()` inherited from `CustomObjective`, but in real the method does not exist, as i see the wiki is not updated. How can i prompt for another value so?

**Comment by PikaMug** [comment]
`addData()` must be specified in the constructor. See the second example.
