### ISSUE TITLE
MySQL bug on b171

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1479]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.3-b171

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/DXyeZQt7
Pretty self explanatory i entered the server literally did nothing then disconnected and error appeared. 
What i've tried:
Regenerating config files and database. Error still persist.
Also there was no record recorded in table.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. Is the lastKnownName field populated in for that player? Or is it in fact null?

**Comment by PikaMug** [comment]
Either way, please try https://ci.codemc.io/job/PikaMug/job/Quests/172/

**Comment by DeadlykillOfficial** [comment]
I've tested it out and it finally does what it is supposed to do. It does record data properly also `lastknownname` is being also recorded while before it was not. So i guess this issue has been resolved.
