### ISSUE TITLE
Using the NPC-Riding feature 

### ISSUE THREAD

**Issue by enterih** [PikaMug/Quests#1480]
**What does your feature do?**
Hello, Since NPC's a rideable and controllable, it gave me the idea to use that in the plugin. For example: Bring NPC A zu XYZ or Bring NPC B to NPC A (And the npc respawn or  after the quest is finished or whatever to go back to the old place.)

**How would people use it?**
They would use it in the Editor in the category NPC's. It gives much possibilities to create awesome quests

**Comment by PikaMug** [comment]
Added in 6b7bcc207fe4c1ec1d47d77a27ae929b39a36623

Use https://ci.codemc.io/job/PikaMug/job/Quests/199/
