### ISSUE TITLE
Command task that supports command executing plugins

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1481]
I didn't know how to call this idea but the whole idea behind this suggestion is a task that can be used with every plugin out there that can execute commands, a sort of supporting unsupported plugins.

Here's an example of how everything would work.
User selects the "Command Variable" task
These options appear:
1 - Set variable name
2 - Set variable amount
3 - Objective Name  [What appears in the quest journal things like %count% would work to show progress]
4 - Notify (true/false) [It'll post in chat the notify message]
5 - Notify message [%count% would work on it]

Now after they've set up their task they'll be able to setup their plugin to use a command such as "/qa variable give playername variablename" on said player and their task would go up by 1 so if they set a variable amount of 5 it'd be at 1/5, after the same action within their plugin is done 5 times the stage would be completed and go to the next. The command would only work on users who have any active stage on any quest with a variable of the same name.

This could be used on so many plugins like Denizen to setup unique scripts which the progress awarded by the plugin via the variables to go to the next stage. Another one could be MMOItems Stations you can execute commands on players for creating an item from their recipes and that could count towards a quest. I think the unique possibilities that players can come up with their already existing plugins that execute commands are endless.

I hope this can be considered, if not I'd like maybe some feedback on why it's not a really good system, thanks!

**Comment by PikaMug** [comment]
Thanks for the suggestion. Sounds like a novel idea, but this type functionality is currently designated to modules. I would suggest that, if you have the ability to hire a developer or do this yourself, release this idea as a resource on SpigotMC or elsewhere. The type of universal integration you've detailed isn't within the scope of Quests, at least not at this time.
