### ISSUE TITLE
Config data Bug

### ISSUE THREAD

**Issue by zprxme** [PikaMug/Quests#1482]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.3
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When i open a Quest in the Editor with questrequirements and then Save it   then all my quests are Vanished or "Ingame not playable". It saves the Quest in the Config with a Java Class and not with the Quest name.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
 https://pastebin.com/EhRr28kw

**Comment by PikaMug** [comment]
Use the latest development build https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by zprxme** [comment]
The Bug comes from the QuestGUI Plugin

**Comment by PikaMug** [comment]
QuestsGUI is an overlay for Quests; not a replacement. Update to the latest development build of Quests.

If you then still experience an issue and are certain it's from QuestsGUI, support for that plugin is here:
https://www.spigotmc.org/threads/questsgui-paid.399346/
