### ISSUE TITLE
Specified enchantment cannot be applied to this itemstack error when enchanting books.

### ISSUE THREAD

**Issue by DrakePork** [PikaMug/Quests#1483]
**What is your Quests version / build number (do _not_ say "latest")?** 4.0.0-rc.3-b168

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Yeah after updating to the newest version on spigot, it seems to throw this error anytime someone enchants a book.
https://pastebin.com/CMC190jf

**Comment by PikaMug** [comment]
Thanks for the report. Does this still occur on the latest development build? https://ci.codemc.io/job/PikaMug/job/Quests/

Also, what is a specific item and enchantment combination that causes this error?

**Comment by DrakePork** [comment]
I'll test out the build, but from what I saw its any enchant getting enchanted onto a book.

**Comment by DrakePork** [comment]
Error still popping up when trying with the latest build

**Comment by PikaMug** [comment]
Thanks. Again, could you please share a _specific_ item and enchantment combination that you've tested causes the error?

Fire Aspect? Sharpness? Protection?

Book? Book and Quill? Written Book? Enchanted Book?

**Comment by DrakePork** [comment]
The specific item is a normal book getting enchanted in an enchant table and turned into an enchanted book. As far as my testing goes, it seems its any enchant.

**Comment by PikaMug** [comment]
Resolved in https://ci.codemc.io/job/PikaMug/job/Quests/176/
