### ISSUE TITLE
HashMap error upon reload while using MySQL

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1488]
**What is your Quests version / build number (do _not_ say "latest")?**
rc.3-b173
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/Vhr3H19h - Console Log + error.
Replication. Right click NPC take the quest once quest accepted do /qa reload
Error appears. Database saves some weird data and quest ingame is no longer playable.
![image](https://user-images.githubusercontent.com/12415714/100906003-f5fc7a80-34c8-11eb-9bdc-410111d3ad36.png)
![image](https://user-images.githubusercontent.com/12415714/100906031-00b70f80-34c9-11eb-871c-c7943155bb3c.png)
Quest `test` is being tested.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/AZ3USt9n

**Comment by DeadlykillOfficial** [comment]
![image](https://user-images.githubusercontent.com/12415714/100906435-791dd080-34c9-11eb-8fd4-628b3f3bbc2c.png)
Following message shows outcome without /qa reload after accepting quest.

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/174/

**Comment by DeadlykillOfficial** [comment]
Hashmap error is gone. But quest is not working still after reload.
![image](https://user-images.githubusercontent.com/12415714/101156190-80a7bb80-3628-11eb-832b-15840ee09720.png)

**Comment by DeadlykillOfficial** [comment]
![image](https://user-images.githubusercontent.com/12415714/101156274-a2a13e00-3628-11eb-8231-b7d808ac1512.png)
No errors at all but not functionally either. Replication is simple accept quest type /q then you can see it's working type /qa reload and then /q and it's no longer working.

**Comment by PikaMug** [comment]
@DeadlykillOfficial Thanks for the followup. This issue seems to be limited to the MySQL implementation.

Do you have EssentialsX installed? They do some sort of player UUID correction and removing it temporarily alleviated the problem for me. Still looking for the underlying issue within Quests.

**Comment by DeadlykillOfficial** [comment]
I do use EssentialsX indeed. But my server is online mode? I don't think this should affect UUID at all? Unless it's backstage cause my UUID is always the same regardless with or without EssentialsX.

**Comment by PikaMug** [comment]
Turns out I came across a separate but somewhat-related bug regarding UUIDs while testing. This build should address both that and the _/quest_ problem.

https://ci.codemc.io/job/PikaMug/job/Quests/175/

Please note that _/questadmin reload_ may cause online players to lose progress on their current objective (so their 5/10 broken Stone might reset to 0/10). This will be considered an acceptable side-effect of using MySQL for the time being.
