### ISSUE TITLE
Auto rank isn't finding my quests since updating version.

### ISSUE THREAD

**Issue by DrewRichard** [PikaMug/Quests#1489]
**Where else have you looked for answers to this question?**
I've been looking for the answer on the quests wiki and autoranks wiki.
**Share your question with as much detail as possible?**
So we updated for a 1.16.1 version of quests to a 1.16.4 version and now the quests aren't being found by autoranks for ranking people up.

**Comment by DrewRichard** [comment]
We updated to Quests-4.0.0-rc.3 from Quests-3.9.5 

This is what we have in autoranks
masterToKnight:
  prerequisites:
    in group:
      value: master
  requirements:
    time:
      value: 20h
    votes:
      value: 12
    quests complete quest:
      value: "Road to Knighthood - Final"

This is what we have in the quest
  custom13:
    name: Road to Knighthood - Final
    ask-message: '[Alecks] Do you have all 5 letters of Approval? Please give them
      to me.'
    finish-message: '[Quests] You have completed the quest line: Road to Knighthood.'
    npc-giver-id: 17
    requirements:
      quests:
      - Berryl's Approval - Road to Knighthood
      - Brandt's Approval - Road to Knighthood
      - Brandy's Approval Attempt 2 - Road to Knighthood
      - Heathrow's Approval - Road to Knighthood
      - Stuart's Approval Attempt 2 - Road to Knighthood
Don't want to bore you with the contents of the quest.

**Comment by PikaMug** [comment]
Quests does not depend on that plugin, so seek help from its developer.
