### ISSUE TITLE
A bug most likely caused by Quests GUI.

### ISSUE THREAD

**Issue by loganhtz** [PikaMug/Quests#1490]
My Quests version is 4.0.0-rc.3-b173 but the same thing happened with the version that is current on SpigotMC. My Quests GUI version is 0.22. 

The issue is caused by the THIRD stage on my custom4 quest "A Miner's Fatigue." It is replicated easily by remaking the quest and everything works fine until Stage 3 is created. (I did every other stage, doing /questadmin reload in between and there were no problems until stage 3.) It then spits out these errors in the console upon the entering of /questadmin reload:

https://pastebin.com/zmKFA2Nq

This is what happens when you add Stage 3 when the server is up. If you add it via the config and restart, the plugin NEVER starts up, and the message, "Please wait, the plugin is starting up," or something to that effect is said in chat if you execute ANY /quests commands.  Also, when adding this stage from Quests GUI, it won't let you leave the stage or save until you click an item in your inventory, which is pretty glitchy and imagine this is the cause for the error. All of these errors have been verified by me before adding any MMOItems quest rewards, so I believe it is an issue separate to that plugin. 

Attached is the quests.yml that has the error, the quest is again is custom4, A Miner's Fatigue Stage 3. Please let me know if you can help!

https://pastebin.com/gqQ6VMtw

**Comment by loganhtz** [comment]
Update: I discovered through more testing that it is the THIRD Item in the 3rd stage that breaks the plugin. If I only set 2 items to deliver, the plugin functions normally, but if I specify 3, it breaks.

**Comment by PikaMug** [comment]
Thanks fro the report. The third stage of your quest is missing data for the Deliver Item objective. You specified 3 items, but only 1 NPC IDs and 1 delivery messsage. You need 3 IDs and 3 messages in total.

The editor does not permit missing data like this, so either the file was edited manually or the safeguards were circumvented somehow. If you're able to demonstrate if and how the later was achieved, feel free to create a new issue.
