### ISSUE TITLE
Error when killing a zombie

### ISSUE THREAD

**Issue by zMario34** [PikaMug/Quests#1491]
When killing a zombie doing a quest, it doesn't count it and leave this error in console: https://pastebin.com/Hu7sQpgb
Plugin version: latest (4.0.0-rc.3)
I've crackshot and 1.8.8 spigot for the server version.. I believe that isn't a crackshot problem because if I kill a mob using a vanilla item it shows the same error.

**Comment by PikaMug** [comment]
Thanks for the report. I'm unable to replicate this error. Do you have a quest to share from _quests.yml_ using Pastebin?

**Comment by Lunatik934** [comment]
hey I have this error also

https://hastebin.com/uqiyawuwam.properties

**Comment by PikaMug** [comment]
@Lunatik934 Same question applies. Do you have a quest to share from _quests.yml_ using Pastebin?

**Comment by zMario34** [comment]
> @Lunatik934 Same question applies. Do you have a quest to share from _quests.yml_ using Pastebin?

Nope, I just created a new quest and added to kill some zombies.

**Comment by PikaMug** [comment]
Closing as OP appears unwilling to share quest for testing.

Feel free to try the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/
