### ISSUE TITLE
Enchant items stages not working (4.0.0-rc.3)

### ISSUE THREAD

**Issue by ame94** [PikaMug/Quests#1492]
Hi there!

Either by loading the item to enchant by hand, or specifying item & enchantment type manually in the quest editor menu, I can't seem to trigger the event when applying the enchant with anvil / table

Thanks!

**Comment by ame94** [comment]
is onEnchantItem used in the listeners for enchant related aspects? I see that onCraftItem is, but for enchant related quests that handler isn't. I cloned and put a quick little "item was crafted", "item was enchanted" message for the server log right at the top of the handlers and i didn't see anything happen for onEnchantItem. Is this type of event handled elsewhere?

**Comment by PikaMug** [comment]
Yes, that handler is used for enchantment objectives. It was working last I checked with an Enchantment Table. Are you certain another plugin is not canceling/altering the event?

**Comment by ame94** [comment]
on this test server i only have citizens and wg installed

**Comment by ame94** [comment]
I just realized i'm testing the wrong handler (i was using anvil with enchanted book + item). when i use enchant table IllegalArgumentException is thrown in EnchantItemEvent, which now makes this issue a duplicate of issue #1483
