### ISSUE TITLE
Quests b173 doesn't fully load or recognize commands in game.

### ISSUE THREAD

**Issue by mercurialmusic** [PikaMug/Quests#1493]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v4.0.0-rc.3-b173 running on Paper 312 (1.16.4).

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
So I was seeing the same as #1488 on the 4.0.0rc3 release and tried build 173 in hopes it had been fixed, but it turns out that was a bad idea since I can't do anything with it now. Every command run in game returns an error only in game, nothing in console, stating "Plugin is currently loading. Please try again later!"

There was an error on startup at least: https://gist.github.com/mercurialmusic/07be1ab60889619cdbd101665cc467a8

But that's all I got.

**Comment by PikaMug** [comment]
Closing as duplicate

Please try https://ci.codemc.io/job/PikaMug/job/Quests/174/
