### ISSUE TITLE
Quest Editor Deletes Quests

### ISSUE THREAD

**Issue by KaijuCoffeeShop** [PikaMug/Quests#1494]
I've been using the Quests editor for a few weeks now, and I'm crafting a storyline for my Minecraft world. I've learned how to give them to NPCs Via the Citizens 2 Plugin, and I was on step 4 of the Story, each having new quest titles and rewards after completing a step. However, I ran into a huge issue when I tried to update one of my quests, I accidentally made the quest itself a requirement to access said quest, which means No one could access it. I tried to fix it after one of my players couldn't move on to the next part in the story, and the GUI didn't show up when trying to access the Requirements tab (Which is selecting 9 in the menu). I was guessing from that point and found what I was looking for, I cleared the list of quests from the Requirements Tab and went to put them back in, so that the User could start the next segment in the story. When I tried to put the names in, I got an error, so I reloaded the plugin with 'questadmin reload'. Now there's nothing, no side quests, none in the main storyline. Nothing, everything's gone.

My server crashed shortly after, as I reloaded EVERY plugin once I realized everything was gone. I don't know what to do, this is the fourth time this has happened and It's getting frustrating.

**Comment by PikaMug** [comment]
Hello, and thanks for using Quests. You mentioned you got an error before reloading - would you mind sharing that as a bug report? It should be in your server's _/logs_ folder. Make sure to follow the Report a bug template when creating the new issue.

Backing up your data is crucial for any server, especially if you've experienced this type of problem before. How you do this will vary depending on your host/OS, but SpigotMC has a related help forum if you have any questions (not affiliated):
https://www.spigotmc.org/forums/server-community-management.6/

**Comment by KaijuCoffeeShop** [comment]
Yeah, Here's the log for the day

[2020-12-03-3.log.gz](https://github.com/PikaMug/Quests/files/5647893/2020-12-03-3.log.gz)
