### ISSUE TITLE
How do I compile a custom objective?

### ISSUE THREAD

**Issue by joshjh2002** [PikaMug/Quests#1496]
Just as a test, I have tried using your sample custom objective provided on the QuestAPI page, the one about gaining emough XP to proceed. How would I go about compiling that so I can use it in my server? I plan to program a quest that randomly selects an objective so my server can have daily quests and stuff but there's no point in that if I cannot even test it xD. Assuming that is something I can do with the provided tools.

Any help would be much appreciated! 

I added the class to where the CustomObjective class is and compiled it as instructed in the last part of the document. I put that into the modules folder and it didn't show up in the Custom Objectives section in the in-game editor

**Comment by PikaMug** [comment]
Export it as a Jar file. In Eclipse, this would be right-click project -> Export... -> JAR file. Make sure that "Export generated class files and resources" is ticked.

If your jar fails to be loaded by Quests, there should be a warning at startup stating why this is.
