### ISSUE TITLE
Quests not load.

### ISSUE THREAD

**Issue by Naghell** [PikaMug/Quests#1497]
Quests-4.0.0-rc.3#174

Basically the plugin starts "without problems", at the end this message appears.
https://pastebin.com/shggdq4E
When I use any command of the plugin, another message appears indicating that the plugin continues to load.

There's my Quests.yml and I haven't a problem with it in version 3.9.5. That's beginning from 4.0.0-rc.1 onwards.
https://pastebin.com/HwXLyXMU

**Comment by PikaMug** [comment]
Your quest "Objetos para Astronomía" must have an equal amount of delivery messages as there are items-to-deliver and NPC IDs.

**Comment by SoraShiunin** [comment]
I got this in a fresh instalation of quests + quests gui. Just quests works fine... On the same version. Spigot 1.16.4

**Comment by PikaMug** [comment]
@SoraShiunin Make your own ticket.
