### ISSUE TITLE
After /questadmin reload , All quests deleted?

### ISSUE THREAD

**Issue by Chlorinexd** [PikaMug/Quests#1500]
Hello PikaMug,

First I wanted to say I love the Quests Plugin. It is fun, exciting, and adds so much to the gameplay on the server I admin for. Unfortunately, I ran into an issue today. I was creating a new quest, and had it set up pretty well for my liking, then saved and reloaded the plugin. After saving the first time, I realized I forgot to set a GUI item for the quest, and went into the quest editor to set one. After setting a GUI item, I saved and /questadmin reload. After this second reload, every quest, including the ones I didn't edit were deleted. I checked my console to see if it was something on my side that corrupted or perhaps didn't save properly. Console looked fine, so I am suspecting a bug within the plugin. If you have any suggestions to prevent this from happening in the future I would love to hear them. I enjoy using the plugin and don't want to stop using it because of a little mishap. 

Thank you for your time!
Chlorinexd

**Comment by PikaMug** [comment]
Thanks for the report. Since you did not follow the template, reply below with your Quests version / build number.

By "deleted" did you mean to say they no longer appear in-game? Is the _quests.yml_ file missing or empty? What about actions and/or conditions?

**Comment by Chlorinexd** [comment]
I am using 4.0.0-rc.3. 
They are not appearing in-game. I believe we use MySQL. The _quests.yml_ also will not open in console, but needs to be downloaded and opened in an outside source, but is in console. Actions and Conditions can be opened in console.

**Comment by PikaMug** [comment]
Please try the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by DeadlykillOfficial** [comment]
https://pastebin.com/V7n3CAZi - This is quick follow up of the latest build 178 from CodeMC.
To clarify the issue i have noticed. Whenever User is using MySQL option and start a quest for example break 50 Stone. But player does break 30 Stone then /questadmin reload is being used. Then the quest itself is no longer counted or playable for the player. Whenever he relogs the progress is being wiped to 0/50 and yet not playable only way to make it work is /qa reset player and then let him accept the quest, finish it without relogging at all. Main issue is being Progress saving

**Comment by DeadlykillOfficial** [comment]
As addition build 178 entirely breaks Quests Placeholders. And error apparently whenever player right click NPC and tries to open GUI to accept a quest.

**Comment by austin652** [comment]
This is also a bug using the default YAML instead of mySQL, upon reloading the plugin with "/questsadmin reload" quests no longer show up in-game (using the current latest dev build 4.0.0-rc.3)

**Comment by PikaMug** [comment]
This issue should be fixed in https://ci.codemc.io/job/PikaMug/job/Quests/181/

Please note that the reload message was benign; no quests were actually deleted.
