### ISSUE TITLE
QuestPostObjectiveUpdateEvent

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1501]
**What does your feature do?**
It's QuestsAPI feature that would fire and give updated values of LinkedList<String> from getQuester()#getCurrentObjectives()
As for right now `QuesterPostStartQuestEvent` and `QuesterPostChangeStageEvent` provide only Initial String of quest Objectives but not progressive one. For example if player start a Quest and Objective is Break Stone 0/50. It would always remain 0/50 and there is no way to obtain updated value for example whenever player break 30 stone. It would still be 0/50 for the plugin using API.
**How would people use it?**
It can be used as updateEvent for custom plugins that use QuestsAPI ex:
Placeholders where plugin can register a placeholder according to the last updated objective per player.
Where for example player has 10 accepted quests, Break,Place,Kill,Fish once quest accepted the custom plugin can register for example String of `Break Stone 0/50` but later on it cannot update the placeholder values whenever player progresses into quests. How this will help would be. OnObjectiveUpdate getQuest#getCurrentObjective would return 1/50 , 2/50, 3/50 etc.. for Breaking stone and this way people can actually register into Scoreboards last known objective that player worked on and visualize it in there.

**Comment by PikaMug** [comment]
This request necessitated a long overdue change to what an "objective" is code-wise. There's still work to be done as always, but the QuesterPreUpdateObjectiveEvent and QuesterPreUpdateObjectiveEvent should be functional. I will leave testing that up to you.

https://ci.codemc.io/job/PikaMug/job/Quests/179/
