### ISSUE TITLE
[Request]Quest gui with custom position setting

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1503]
**What does your feature do?**
I wish to have a setting which can set a quest gui display item to display in certain place in a chest, take a 6x9 chest as example, if i want to make the following gui align, i must fill something, a placeholder quest to fill the gap, this is annoying, also, if the quest is one time quest, the entire GUI will shift left if the quest is finish, which the gui will fail.
![image](https://user-images.githubusercontent.com/61608872/102010801-4dc59c00-3d7b-11eb-9e5f-ccb9c16f2e2e.png)

**How would people use it?**
If this function works, people can set quest gui easily.
If we other external menu plugin, it will not able to show whether the quest is finished or not. So the only why i think is that to have a setting for this.

**Comment by DeadlykillOfficial** [comment]
QuestsGUI is being handled in Spigot, Github is mainly only for Quests. Me personal opinion on this topic is, it's cool. But would not be possible just because quests List is being pulled in order and availability.

**Comment by hkkongou** [comment]
> QuestsGUI is being handled in Spigot, Github is mainly only for Quests. Me personal opinion on this topic is, it's cool. But would not be possible just because quests List is being pulled in order and availability.

wait... QuestsGUI is a GUI plugin for editing quest...
This is Quest "GUI" should be build in function in quest, so it should be quest instead questgui plugin suggestion?

**Comment by DeadlykillOfficial** [comment]
My bad then. Either way they function the same. You can only set up the material and Quests are picked up in order and availability. You cannot set up desired place of the Quest and i doubt it will be possible anytime in feature.

**Comment by DeadlykillOfficial** [comment]
The GUI Factory system is built this way. So it picks up quests.yml per NPC in order and then check if quest is available to player and add it to GUI. Adding customization to that would affect too many things on Quests but i suppose you should wait on Pika giving you an answer to that himself.

**Comment by hkkongou** [comment]
yeah i know, i have been using the build in GUI system for display quest so long and i wish this can work so that i don't have to think so long for making a good GUI

**Comment by DeadlykillOfficial** [comment]
You can make Custom GUI's the way you want. I highly doubt Quests GUI would change but we shall wait and see on what Pika's answer would be. Most likely it will remain as it is. Because it would requires too many unnecessary changes.

**Comment by PikaMug** [comment]
There are two versions of the NPC GUI display: the one included with Quests (which is not configurable), and the improved version if QuestsGUI is installed (which is somewhat configurable).

If you are asking to improve the Quests version, there are no plans to do so at this time.

If you are asking to improve the QuestsGUI version, make your request https://www.spigotmc.org/threads/questsgui-paid.399346/
