### ISSUE TITLE
CustomRequirement %count% feature

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1504]
**What does your feature do?**
QuestsAPI into CustomRequirement adding a option %count%.

**How would people use it?**
Adding Custom RPG Level requirements for plugin could be "RPGLevel: %count%" 
Then rather just being "RPGLevel Requirement"

**Comment by PikaMug** [comment]
While a CustomRequirement doesn't guarantee a numeric count like a CustomObjective, it should still permit you to use string prompt titles as variables (see `%Title%` in the [Rewards API example](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API#rewards-api), or `%Item Name%` in [Objectives API example 2](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API#objectives-api)). Let me know if this does not satisfy this issue.
