### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by MarlePG** [PikaMug/Quests#1506]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.1 b-42
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/W5pmN3bF
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/wWPRS7q1

**Comment by DeadlykillOfficial** [comment]
Quests provide support only for latest Spigot release or Dev build. At the moment of this message the version is (4.0.0 rc3 b178)

**Comment by PikaMug** [comment]
Update to the latest version, preferably a development build https://ci.codemc.io/job/PikaMug/job/Quests/
