### ISSUE TITLE
tp command using ~ ~ ~ takes spawn as reference point

### ISSUE THREAD

**Issue by benja854** [PikaMug/Quests#1512]
I want to create an action that teleports the player a number of blocks in one direction to enter a new room at the end of every stage of the quest

I have the action written

tp <player> ~ ~ ~-10

have also tried:
tp:minecraft <player> ~ ~ ~-10

with same result that it teleports me to 0 0 -10

**Comment by PikaMug** [comment]
Commands are run from the console, so that result is not surprising. You must explicit teleport the player to their new location.

There is an Action specifically for teleporting players, or iirc you could try
`tp <player> ~ ~ ~-10`

**Comment by benja854** [comment]
I found a command that works to teleport based on the players current coordinates each time.

/execute as @p run execute at @s run tp @s ~ ~ ~-10

but I put it into a command block that the quest triggers by running a setblock stone_button[powered=true] x y z command as an action because I am not sure how to write each selector in the quest interface for actions.
