### ISSUE TITLE
Error: Plugin is currently loading. Please try again later

### ISSUE THREAD

**Issue by tashak700** [PikaMug/Quests#1513]
WARN in console:
18.12 12:07:01 [Server] Server thread/WARN Task #34 for Quests v4.0.0-rc.3-b179 generated an exception
18.12 12:07:01 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
18.12 12:07:01 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_211]
18.12 12:07:01 [Server] INFO at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_211]
18.12 12:07:01 [Server] INFO at me.blackvein.quests.Quests.loadQuestStages(Quests.java:2268) ~[?:?]
18.12 12:07:01 [Server] INFO at me.blackvein.quests.Quests.loadQuests(Quests.java:1609) ~[?:?]
18.12 12:07:01 [Server] INFO at me.blackvein.quests.Quests$2.run(Quests.java:634) ~[?:?]

**Where else have you looked for answers to this question?**
Github
**Share your question with as much detail as possible?**

**If applicable, which Java class or API method does this reference?**

**Comment by PikaMug** [comment]
One or more of your block objectives is missing a durability value. Either correct this, or update to this development build:
https://ci.codemc.io/job/PikaMug/job/Quests/182/

Also, please use the "Report a bug" option when creating a bug report next time. Thanks!
