### ISSUE TITLE
Required quests are considered NULL

### ISSUE THREAD

**Issue by Danifoxe** [PikaMug/Quests#1514]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests-4.0.0-rc.3#182

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Only in Quests version 4.0.0-rc.3, I have an error with the required missions, the plugin considers the name as NULL when the mission name is spelled correctly. When I go back to Quests 4.0.0-rc.2, the error doesn't happen. I have tried deleting the requirement and putting it back by the editor, but the result is the same.
Console:
https://pastebin.com/BnTxURnA

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/c7xnUx8x

**Comment by PikaMug** [comment]
Update to the latest development build https://ci.codemc.io/job/PikaMug/job/Quests/

Delete the Requirement, then create it again.
