### ISSUE TITLE
Kill Mob objective not visualizing properly 

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1516]
**What is your Quests version / build number (do _not_ say "latest")?**
rc.3 - b182

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
 There is somewhat missalignment on the Kill Mob Message why using /quest to see objective.
![image](https://user-images.githubusercontent.com/12415714/102761258-f9bc4800-4376-11eb-9577-2f22c5ef0983.png)
It's not properly spaced. I've tried to find it within lang files, but couldn't

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/yQXs8Q7T - quests.yml

**Comment by PikaMug** [comment]
Thanks for reporting this. Please let me know if you find any other formatting concerns.
