### ISSUE TITLE
quests journal stuck in enderchest

### ISSUE THREAD

**Issue by elaineandsparky** [PikaMug/Quests#1517]
My players have the quests.admin.drop perms so that staff can view their journals if they are stuck on what they need to do next.

One of my players has somehow managed to get the quests journal stuck in their enderchest (she can't remember how she got it in there).

I can't take it out either when viewing their enderchest.

Any ideas how to get the journal out? (they can still do /quests journal and get another one)

Using 4.0.0-rc.3

**Comment by PikaMug** [comment]
You will likely need to remove all other items, clear/delete their Ender Chest, and then add the items back.

Generally speaking, that permission is intended as a convenience for administrators only. For players, should be given and revoked only as necessary; not 24/7.

**Comment by elaineandsparky** [comment]
Thank you for your reply. We had to give that command to players as it was the only way staff could see other players quest journal to help them when they say quests aren't working but they just don't know what they are doing.

I know this isn't your area, but any help would be apprieciate, I had tried clear enderchest command before but can't get it to work. I wonder if it is an old command. We are a paper server using essentialsx and the /cec /cecp /clearenderchest etc commands return unknown or incomplete command errors.

**Comment by PikaMug** [comment]
I'm afraid you'd want to ask the developers of EssentialsX about their commands.

You might be able to use this vanilla command if you know which slot the journal is in (the first slot being 0):
`/replaceitem entity <playerName> enderchest.0 dirt`
Might want to test this on yourself first since there's probably no undoing it.
