### ISSUE TITLE
Plugin not loading correctly in game.

### ISSUE THREAD

**Issue by SirTCSS** [PikaMug/Quests#1518]
**Where else have you looked for answers to this question?**
On your wiki page and minecraft forums
**Share your question with as much detail as possible?**
Plugin not loading correctly in game. Just says "plugin is currently loading. Please try again Later!"
**If applicable, which Java class or API method does this reference?**
I use latest version of java.
![Screenshot 2020-12-21 132949](https://user-images.githubusercontent.com/76452692/102819414-a820b700-4390-11eb-8f7d-a59cf0abc21d.png)

**Comment by PikaMug** [comment]
Thanks for the report. What version of Quests are you using? This can be caused by a number of reasons, so I'll need to see a startup log for your server. This is typically located in the _/logs_ folder.

**Comment by PikaMug** [comment]
Feel free to try the latest development build and report back with a log if you still have the issue:
https://ci.codemc.io/job/PikaMug/job/Quests/
