### ISSUE TITLE
Error on logs with mob kills quest

### ISSUE THREAD

**Issue by Lunatik934** [PikaMug/Quests#1520]
**What is your Quests version / build number (do _not_ say "latest")?**
182
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I have this error in my log: https://pastebin.com/P6WNFNYY
I use the crackshot plugin too, is that a problem?
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/MmEHxe6S

**Comment by PikaMug** [comment]
Thanks for the report. Try https://ci.codemc.io/job/PikaMug/job/Quests/183/

Note that QuestsGUI may not be fully compatible with that build.
