### ISSUE TITLE
Wrong repeat cycle for 31536000 

### ISSUE THREAD

**Issue by PappoYT** [PikaMug/Quests#1523]
Quests 4.0.0-rc.3-b168
Paper version git-Paper-311 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

If I setup set repeat cycle to 31536000 (once every year) I get 17 days 40 minutes and 28 seconds instead (see screenshot).

quests.yml: https://pastebin.com/ruKq15kX (look custom15).
![Cattura](https://user-images.githubusercontent.com/74958346/103158097-81acb280-47ba-11eb-9f44-1922c1f8157c.PNG)

**Comment by PappoYT** [comment]
I installed latest Quests build but bug is still present.

26.12 22:09:29 [Server] INFO Quests 4.0.0-rc.3-b184

**Comment by PikaMug** [comment]
@PappoYT Use https://ci.codemc.io/job/PikaMug/job/Quests/185/
