### ISSUE TITLE
Start event doesn't trig

### ISSUE THREAD

**Issue by PappoYT** [PikaMug/Quests#1528]
Quests v4.0.0-rc.3-b185
Paper version git-Paper-311 (MC: 1.16.4)
Citizens-2.0.27.jar
MythicMobs-premium-4.10.1.jar

I setup phases in this way:
- phase 1
- objective > talk to npc
- phase 2
- custom objective > kill mythicmobs objective
- actions > start actions > player > command > mm mobs spawn MYMOBNAME

mob MYMOBNAME doesn't spawn
in console I get this error right after talk to npc (phase 1):

[11:21:20] [Server thread/INFO]: Showing new title for xXP01lastr0Xx
[11:21:20] [Server thread/INFO]: Showing new subtitle for xXP01lastr0Xx
[11:21:20] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Quests v4.0.0-rc.3-b185
java.lang.NullPointerException: null

I checked custom event syntax direclty in console and it works.

Does "- events > start evets > player > command >" run commands as admin/op?

**Comment by PikaMug** [comment]
Thanks for the report. I believe there should be more lines to that error - please check again and post the full error if it exists.

**Comment by PappoYT** [comment]
Deadlykill in Discord help me to understand that the problem is not connected to Quests plugin.
So I close this issue.
The Could not pass event NPCRightClickEvent error remains, but it is not connected to actions trigger.
