### ISSUE TITLE
Error on log

### ISSUE THREAD

**Issue by Lunatik934** [PikaMug/Quests#1532]
**What is your Quests version / build number (do _not_ say "latest")?**
186
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://hastebin.com/jiluroseco.properties
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Resolved in 200a10efaac31a053d8a7f837347ae4cd2358691

Use https://ci.codemc.io/job/PikaMug/job/Quests/187/
