### ISSUE TITLE
Unable to complete quest that require you to kill a Citizens NPC

### ISSUE THREAD

**Issue by iTemmy** [PikaMug/Quests#1534]
**What is your Quests version / build number (do _not_ say "latest")?**
Build 187
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Created a quest that would require the player to kill an npc, but when the player would kill the npc it wouldn't complete the stage, it would mark down that the player had killed the npc but it wouldn't complete the quest. Tried to do this on the server with multiple other plugins then also tried it on test server with only Citizens(Build b2197), Quests(Build 187) and NPC Destinations(Version 2.4.2)
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/k3LQ69Pn

**Comment by PikaMug** [comment]
Thanks for the report. Does this still occur without NPC Destinations installed?

**Comment by iTemmy** [comment]
When I didn't have npc Destinations installed every time I ran a command it would just say "this plugin is still starting"

**Comment by iTemmy** [comment]
It appears to be fixed with Build number 189.
