### ISSUE TITLE
Catch Fish not progressing

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1535]
**What is your Quests version / build number (do _not_ say "latest")?**
b188

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The problem with that is. Whenever you have a stage to Catch Fish the server does count each fish counted to a point where Task is technically completed but it doesn't process to next stage or finish a quest.
The following picture shows up how the quest progress looks like:
![image](https://user-images.githubusercontent.com/12415714/103447971-e7a1aa00-4c92-11eb-9f1d-923819d45443.png)
After reaching 2/2 and message is grayed out as "finished". There is nothing else happening in there.

Replication is simple. Use b188 join the server then /quests editor -> Create Quest -> Name it -> Stages -> add new stage -> Mobs -> Catch fish -> Specify amount -> Save quest -> Reload -> start quest -> catch desired number of fished and here you go nothing happens nothing progresses.

Tested:
whenever Catch fish is just single stage of a quest
Whenever Catch fish is somewhere in middle of a quest Stages.
whenever Catch fish is last Stage of a quest.
None works.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Wondering if this might be caused by 200a10efaac31a053d8a7f837347ae4cd2358691

**Comment by DrakePork** [comment]
Im having the same issue on b185

**Comment by PikaMug** [comment]
@DeadlykillOfficial @DrakePork Use https://ci.codemc.io/job/PikaMug/job/Quests/189/
