### ISSUE TITLE
finish-event doesn't drop WRITTEN_BOOK

### ISSUE THREAD

**Issue by PappoYT** [PikaMug/Quests#1536]
Quests-4.0.0-rc.3-build-185.jar
MythicMobs-premium-4.10.1.jar

I have a problem with finish-event: it should drop a WRITTEN_BOOK but sometimes it doesn't.

_quests.yml_

> '5':
>           custom-objectives:
>             custom1:
>               name: Kill MythicMobs Objective
>               count: 1
>               data:
>                 Objective Name: ''
>                 Conditions: NONE
>                 TargetConditions: NONE
>                 Internal Mobnames: GRIR
>                 Mob Level: '0'
>                 Mob Faction: ANY
>                 Notifier enabled: false
>                 Notifier msg: ''
>           finish-event: Ordini Grir
>           start-message: Uccidi Grir.
>           complete-message: 'Hai ucciso Grir. Hai trovato un oggetto: Ordini di Grir.'

_actions.yml:_

> Ordini Grir:
>     items:
>     - ==: org.bukkit.inventory.ItemStack
>       v: 2584
>       type: WRITTEN_BOOK
>       meta:
>         ==: ItemMeta
>         meta-type: BOOK_SIGNED
>         title: Ordini Grir
>         author: paladinodeimari
>         pages:
>         - |-
>           Mio federe Grir,
> 
>           la formula è esatta ma il rituale esige un'ingente quantità di cuoio per poterlo riportare nella nostra dimensione.
> 
>           Non perdere tempo, procura tutto il cuoio che trovi nei villaggi e portalo alla torre.
>         - |-
>           Io sarò la ad aspettarti, per fare quello che devo.
> 
>           5341 87 2539
> 
>                          Mutuh-Zuf

**Comment by PikaMug** [comment]
File data must be shared using Pastebin/Hastebin. Please correct this and request re-open.
