### ISSUE TITLE
Enchant item not working

### ISSUE THREAD

**Issue by DrakePork** [PikaMug/Quests#1538]
**What is your Quests version / build number (do _not_ say "latest")?**
b189 (wasnt working on previous builds too, just didnt report until this one)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Set up a quest with enchant item (can be any item) objective. No errors pop up in console.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
[Quest Example](https://pastebin.com/4uhzC6Gw)

**Comment by PikaMug** [comment]
Works just fine for me. Make sure you're applying the correct enchantment, in your case Sharpness II.

**Comment by DrakePork** [comment]
The sharpness 2 isnt for objective, thats for the GUI display item

**Comment by DrakePork** [comment]
Ah so I just edited the quest to have a specified enchantment, and now it works. Is there any way of having it work with any enchantment?

**Comment by PikaMug** [comment]
Sorry, I misread your quest. I'll look into not requiring a specific enchantment.

**Comment by PikaMug** [comment]
I've addressed two issues here, the first being that the objective goal should show the enchantment when one is specified. You will need to regenerate your language file for it to appear correctly.

The second is you can now use an item without an enchantment (effectively meaning "any" enchantment). However this was never the intended functionality - all item objectives expect you to use the _resulting_ item (i.e. smelt ingots, not ore). If this new functionality creates any issues that didn't arise in testing, be advised I may remove it in a future commit.

Use https://ci.codemc.io/job/PikaMug/job/Quests/190/
