### ISSUE TITLE
Bug in console editing a mission

### ISSUE THREAD

**Issue by WilsarX** [PikaMug/Quests#1539]
**What is your Quests version / build number (do _not_ say "latest")?**
Misiones-4.0.0-rc.3 # 182

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
when I edit a mission and type "cancel" it doesn't go back and I get an error in the console.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
This is the issue tracker for Quests. Never heard of Misiones.

Also, if you have a console error it must be included using Hastebin or Pastebin.
