### ISSUE TITLE
Quests don't save anymore

### ISSUE THREAD

**Issue by Natal12321** [PikaMug/Quests#1540]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.0-rc.3
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
First time i created a custom quest it worked. Second time i created a custom quest all the quests dissapeared while in the quests.yml folder it still says the quests are existing while they arent loaded in the game. What do?
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by Natal12321** [comment]
UPDATE! It doesn't save anymore when i click 1. (yes)

**Comment by DeadlykillOfficial** [comment]
You are most likely having Null error while configuring your quests. 99% of cases people spell wrong material or anything else that prevent Quests from loading all quests.

**Comment by Natal12321** [comment]
I just looked at another bug issue from someone else, they replied to try another version (3.8.9) so im doing that now. Ill let yall know if it worked or not

**Comment by Natal12321** [comment]
It worked! Problem solved. People who have the same problem, just download the 3.8.9 version and it should work!

**Comment by DeadlykillOfficial** [comment]
By downgrading you lose any support from Github. Just gonna let you know
