### ISSUE TITLE
Jobs Reborn Module

### ISSUE THREAD

**Issue by Thommii** [PikaMug/Quests#1541]
**What does your feature do?**
Create a module to connect Quests Plugin with the [Jobs Reborn](https://www.spigotmc.org/resources/jobs-reborn.4216) Plugin.
[Jobs Reborn API](https://github.com/Zrips/Jobs/wiki/API)
You can complete Quest successfully if you have successfully completed certain tasks in Jobs Reborn.

**How would people use it?**
Get Access to (based on player):
- Number of jobs at the moment
- Join a Job
- Leave a Job
- Level of a Job
- Level of all jobs from the player

Possible Quests:
1. Have joined none/one/two/X jobs at the moment.
2. Join the job by name.
3. Leave the job by name.
4. Achieve the defined job level from the job with the name.
5. Achieve the defined job level from all joined jobs.

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#need-support-for-other-plugins
