### ISSUE TITLE
No NPC message when he gets an item

### ISSUE THREAD

**Issue by resteqs** [PikaMug/Quests#1542]
Hi, when a player delivers an item message is not send.

There is a message, but it's not displayed

![image](https://user-images.githubusercontent.com/65457699/103491578-53b41780-4e25-11eb-9b60-8bbd79e0024d.png)
![image](https://user-images.githubusercontent.com/65457699/103491600-865e1000-4e25-11eb-80a7-971146bf998c.png)

**Comment by DeadlykillOfficial** [comment]
This report is invalid due to not following the provided layout and required information.

**Comment by DeadlykillOfficial** [comment]
Also the message is displayed whenever you deliver the items to the NPC not before that.

**Comment by PikaMug** [comment]
Closing as OP did not follow issue template.
