### ISSUE TITLE
Unsupported Enchantments

### ISSUE THREAD

**Issue by zagambill** [PikaMug/Quests#1546]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.3-b168
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
We don't have a quest monitoring enchantments, but it looks like Quests monitors player inventories for new enchanted items regardless. We use custom items to give people firecharges (enchanted with kb2) that, when opened, give a broken enchanted item (boots with sharpness and silk, for example; runs through Mythic Drops). It seems that, when players who have joined any quest either 1) get one of these items (via command), or 2) open the fire charge to get a broken enchanted tool (also via command), Quests throws the following enchanting error.
[https://pastebin.com/T0K9F71P](https://pastebin.com/T0K9F71P)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
We only have a couple very basic quests at the moment, like "kill 3 players", and none of them use enchants.

**Comment by DeadlykillOfficial** [comment]
You are running way way too outdated Quests Version.

**Comment by PikaMug** [comment]
Thanks for the report. As @DeadlykillOfficial alluded to, most 4.0.0-rc.3 users were being advised to run the latest development build. However, 4.0.0-rc.4 released on SpigotMC earlier today, so please upgrade and let us know if the issue persists.
