### ISSUE TITLE
items don't auto translate

### ISSUE THREAD

**Issue by oski32166** [PikaMug/Quests#1548]
My Quests version is 4.0.0-rc.4.
Items in quests/commands are displayed in english although everything other is correctly translated. It's like that for every player on server.
![2021-01-08_04 42 36](https://user-images.githubusercontent.com/77134938/104013400-adb03680-51b1-11eb-90d4-6102ee21f5e3.png)
![2021-01-08_13 01 19](https://user-images.githubusercontent.com/77134938/104013403-aee16380-51b1-11eb-8e05-e9886a079979.png)
![2021-01-08_13 01 31](https://user-images.githubusercontent.com/77134938/104013406-b0129080-51b1-11eb-8765-8cf592f92576.png)

**Comment by PikaMug** [comment]
Thanks for the report. Only the first image has to do with Quests. The other two do not appear to be from Quests and are thus not something I can address.

Please try https://ci.codemc.io/job/PikaMug/job/Quests/192/

**Comment by oski32166** [comment]
It works now. Thank you so much 😄
