### ISSUE TITLE
Can't save the quests AGAIN

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1549]
**What is your Quests version / build number (do _not_ say "latest")?** 
version quests 4.0 -rc4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
My probleme is same that's post https://github.com/PikaMug/Quests/issues/1540#issue-777702486
You say you solved the problem but i have the latest version (rc4) i can't save but in rc3 i can 

Ps: The bottom "exit" works but "save" works too but he make the same command that for "exit"

**Comment by DeadlykillOfficial** [comment]
You must recreate your QuestsGUI folder in order for it to work.

**Comment by DeadlykillOfficial** [comment]
In case this is not to QuestsGUI related. Check your console for errors. The "Bug" you are experiencing can't be replicated by anyone to confirm if it's actual bug.

**Comment by Beubeux74** [comment]
I tested with your rc4 version
When clicking on the "save" button the plugin sends me the message "you have quit" instead of the usual message "quete save questadmin reload ..."
In addition, you have removed the "initial event" button but the item associated with it is not deleted suddenly all the actions no longer correspond to their initial items because the actions have shifted by a notch

**Comment by DeadlykillOfficial** [comment]
So it's QuestGUI related. As i said. Regen your QuestGUI folder and it would work about right. 
"regen" means delete and let plugin 0.24 generate new one

**Comment by Beubeux74** [comment]
Ok thanks you for your help, i try this when players on my server leave.
can you leave the post open until tomorrow?

**Comment by PikaMug** [comment]
I have added a notice about this to the QuestsGUI 0.24 update notes on SpigotMC.
