### ISSUE TITLE
add Step block on goal

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1550]
**What does your feature do?**

add a "click / use a block" functionality in a quest step like the "starting block" function so that players can "look for / search" the blocks during the steps

because the function "to go to a radius" around a block is not suitable for research or excavation during exploration for example

**How would people use it?**

the players doing the quest

**Comment by PikaMug** [comment]
Thanks for the suggestion. It appears there was an error in the Wiki page description for this, so let me clarify:

![CreateQuest](https://i.imgur.com/HeG9w9K.png)

In the Quests Editor, selection `5 - Set block start` is for right-clicking a chosen block to start the quest, while `6 - Set region` requires the player to stand in a particular area (as small as 1x1) if WorldGuard is installed.
