### ISSUE TITLE
Option to remove chat messages for quest starting/Option to use CitizensBooks (or just book menus) as quest text.

### ISSUE THREAD

**Issue by michaalbo** [PikaMug/Quests#1553]
**What does your feature do?**
Option to remove chat messages for quest starting/Option to use CitizensBooks (or just book menus) as quest text.
**How would people use it?**
By turning off messages (with objectives), and then, by actions, manually adding the book texts at the beginning of individual stages. This would allow for WOW-like quests and/or nicer looking npc texts describing the quest.

Some implementation that would make that easier would also be nice.

**Comment by PikaMug** [comment]
Thanks for your suggestion. I am not keen on the idea of not notifying the player of their objectives. Perhaps the developer of CitizensBooks could assist you with this matter, otherwise feel free to elaborate on what you mean by "some implementation."

**Comment by michaalbo** [comment]
Something like making the strings have "\n" in the beginning, so that removing them would be just a tad bit easier (by that I mean, if the string is empty, the message would not send at all). I know it sounds stupid, but I really like the idea of having the "book-like displays" for quest objectives and the description, but now the strings just return empty lines on the chat.

**Comment by DeadlykillOfficial** [comment]
Check #1545
