### ISSUE TITLE
Beginning action of the 1st stage does not set off.

### ISSUE THREAD

**Issue by michaalbo** [PikaMug/Quests#1554]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.4-b193
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When I add a beginning action for the 1st stage (so the beginning of the quest), the action does not set off. However, when used in the ending action (the last one, which sets off at the end of the stage), the action works smoothly.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/DL5DTnsG

**Comment by PikaMug** [comment]
While I don't have _/npcbook_ installed, I tested your quest with the default RunCommand action and it works fine. Make sure the player does not have a GUI or another book open, as perhaps the _/npcbook_ plugin does not account for that.
