### ISSUE TITLE
Permission node exceptions on startup

### ISSUE THREAD

**Issue by Sylensky** [PikaMug/Quests#1556]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v4.0.0-rc.4-b191

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Well the steps were quite simple:
- previous installation was rc.3
- downloaded rc.4-b191 above
- restart and watch the logs with the following error logs
https://pastebin.com/EmcRkFXt

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Not necessary, the quests do work so far.

**Comment by PikaMug** [comment]
It would appear the _plugin.yml_ file within your Quests jar has been modified somehow. Try to re-download Quests, perhaps with a different browser. If the issue still occurs, use a tool such as WinRAR or 7-Zip (neither affiliated) to open the jar archive. Share the _plugin.yml_ file here using Pastebin or Hastebin.

**Comment by Sylensky** [comment]
this is the plugin.yml from the jar that throws the errors:
https://hastebin.com/lulevamubi.yaml

**Comment by PikaMug** [comment]
@Sylensky Thanks. It looks fine at first glance, but do try downloading the plugin again, perhaps the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/

Are you using a permissions plugin like LuckPerms? If so, which one?

**Comment by Sylensky** [comment]
The latest dev build did the trick. Not sure what exactly caused that behaviour but i proceeded the same way as last time.
Using LuckPerms by the way.
