### ISSUE TITLE
unable to save 6th stage

### ISSUE THREAD

**Issue by Biggsen** [PikaMug/Quests#1558]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0 rc4.
QuestsGUI 0.24 

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
After creating the 6th stage in my quest, I'm unable to exit out of the 'Stages' panel. When I click on 'Done', it does nothing but relocate the mouse pointer to the middle. I've checked the chat log, and there's no errors. The only way to get out of the GUI is by deleting the 6th stage. I tested this on 2 servers and they both had the same issue.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/HF26ERhQ

**Comment by PikaMug** [comment]
@Biggsen Does this occur without QuestsGUI installed?

Issues with QuestsGUI should be reported in the discussion thread at https://www.spigotmc.org/resources/questsgui.71666/

**Comment by Biggsen** [comment]
Nope. Works fine without QuestsGUI. I'll report this on the discussion thread.
