### ISSUE TITLE
dispatching KILL_PLAYER for fish

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1559]
**What is your Quests version / build number (do _not_ say "latest")?**
rc.4 b194
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/fb28jJSc - Error
This following error is being send whenever i kill player but my quest doesn't even has anything to do with Kill Player objective

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/jDQYYTyv - Quest

**Comment by PikaMug** [comment]
Probably an incorrectly assigned variable. Couldn't find where exactly so I've added null checks for you in the meantime.

https://ci.codemc.io/job/PikaMug/job/Quests/195/
