### ISSUE TITLE
Option to Execute Denizen Script coming from an NPC

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1560]
**What does your feature do?**
Instead of currently just executing the script on the player, the script would be executed tied to the NPC along with the player.

**How would people use it?**
It expands the possibilities so that the NPCs can be targeted and make them perform actions such as moving around, do animations and more.

**Comment by PikaMug** [comment]
This should be possible, but is something I would prefer to see a PR for. Quests supports older versions of Denizen via reflection, so it would need to be tested on those as well.

**Comment by PikaMug** [comment]
I've added the framework for this, but considering there hasn't been much interest, I'll leave it to future PRs to determine which NPC is "tied" to the quest.
