### ISSUE TITLE
Delivery messages does not work properly.

### ISSUE THREAD

**Issue by DisPie** [PikaMug/Quests#1564]
Build #196 
Quests-4.0.0-rc.4.jar
--

Having a delivery message prevents my quests from being loaded and locks the entire plugin up until the quest or the message are deleted.

`'14':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2584
            type: HONEY_BOTTLE
            amount: 2
          - ==: org.bukkit.inventory.ItemStack
            v: 2584
            type: SLIME_BALL
            amount: 4
          npc-delivery-ids:
          - 19
          delivery-messages:
          - Thank you!
          delay: 6`

**Comment by PikaMug** [comment]
Thanks for the report. However, the issue template stated you must provide your quest using Pastebin (or Hastebin) to retain formatting. Please reply as such in order to receive support.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
