### ISSUE TITLE
Enhance PlaceholderAPI Hook for functional usage like what Deluxemenu do

### ISSUE THREAD

**Issue by kn-km** [PikaMug/Quests#1566]
**What does your feature do?**
I suggest to add new quest requires typed Papi.
We can then check %papi% >= 0, equals "xxx" , etc. Just like what Deluxemenu do.
And other addons like mcMMOAddon requirement will be unnecessary and no longer needed to develop.
**How would people use it?**
For example, to check whether a player has 100 money or not, just use this:
%vault_eco_balance_fixed%>=100

**Comment by PikaMug** [comment]
I'm not sure I understand your request. Placeholders for anything other than Quests does not make sense to me as there's no guarantee they'll be installed. Requesting one from the other plugin's developer is a better route.

At any rate, requests for new placeholders should be made at https://github.com/PikaMug/PlaceholderExpansion-Quests

**Comment by kn-km** [comment]
> I'm not sure I understand your request. Placeholders for anything other than Quests does not make sense to me as there's no guarantee they'll be installed. Requesting one from the other plugin's developer is a better route.
> 
> At any rate, requests for new placeholders should be made at https://github.com/PikaMug/PlaceholderExpansion-Quests

I do not mean add more placeholders.
I make a small addon to show you what I mean. See[this](https://github.com/kn-km/ExampleQuestsRequirement/blob/master/src/main/java/me/knkm/examplequestsrequirement/ExampleQuestsRequirement.java)

**Comment by PikaMug** [comment]
@kn-km Something like that is already possible as a "Check placeholder" condition:
https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Condition-Editor
