### ISSUE TITLE
Quests no longer teleports player to the quest location

### ISSUE THREAD

**Issue by Klawdek** [PikaMug/Quests#1569]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests version 4.0.0-rc.4-b191
 git-Paper-413 (MC: 1.16.4)
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I had a quest that was not in for a long time.  I recently put it back in by copying it from backups.
That quest would teleport the player to the location of the quest where a mythicmob boss is located and that boss is the quest objective.
It no longer teleports the player.  The teleport was done with an event and the events seems to have been removed.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/53prKhig
I am pretty sure the line:  event: mrpumptp1 is what did the teleporting.
Also the documentation show a menu entry for initial action and that has also been removed from the current version.

**Comment by PikaMug** [comment]
Thanks for the report. I would need to see your _actions.yml_ file to look into this further. Initial Actions were removed from the editor as they are equivalent to setting a Start Action on Stage 1, but existing ones should still function regardless.

**Comment by PikaMug** [comment]
I created and attached my own teleport action to the quest as an Initial Action - worked just fine. Tried it as a Start Action for Stage 1 was well, all good. Let me know if you're still having issues.
