### ISSUE TITLE
Enchantments warning on Items delivery

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1575]
**What is your Quests version / build number (do _not_ say "latest")?**
rc.4 b202

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/jgrrNw4D - Warning/error

The issue appears whenever you have so to say "custom items" to deliver to NPC. It should be also doing the same for Items with enchants. Whenever player login into server and has deliver quest active it does pop the warning above in console.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/x63amFDc - quests.yml

**Comment by PikaMug** [comment]
Looks like your quest named "item" is trying apply illegal enchantments, such as Multishot on a Diamond Sword.
