### ISSUE TITLE
NPC#Deliver Items not sending NPC delivery message

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1576]
**What is your Quests version / build number (do _not_ say "latest")?**
rc.4 b202
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
With the following Quest listed below you have to deliver 3 items to npc with message configured to `test1,test2,test3` to be send upon delivery. sadly the outcome of the quest it's the following as the picture shows below:
![image](https://user-images.githubusercontent.com/12415714/104968149-5c8c1800-59e5-11eb-9055-6d3ced20c21b.png)
No message has been send ever to player. 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/x63amFDc - quests.yml

**Comment by PikaMug** [comment]
Delivery message(s) only show if you hand over less than the required amount of an item, always been that way. Not possible to see as there's only 1 item in this case. Also looks like the same number of delivery messages isn't mandatory. Must've changed that somewhat recently. Here's the code block:
https://github.com/PikaMug/Quests/blob/e77a3ccefea2fe81ca25056cd558374e1b6d66c3/main/src/main/java/me/blackvein/quests/Quester.java#L2370-L2411
