### ISSUE TITLE
Delivering Item to NPC causes Quest GUI to open

### ISSUE THREAD

**Issue by tsureo** [PikaMug/Quests#1577]
**What is your Quests version / build number (do not say "latest")?**: 3.0.0-rc.1

I've been making a few quests for a while trying to figure out the extent to which I can intertwine NPCs. I ran into a problem while doing this. The problem being when I have an objective to deliver to another NPC (who also has quests to do), when I right click to deliver, the quest GUI opens up. Is there any way to prevent this or maybe fix it? I've been going at it for an hour or 2 trying to figure it out. 

This quest:
[capella.txt](https://github.com/PikaMug/Quests/files/5839553/capella.txt)
is meant to make you to retrieve a map from an NPC and return it.

The problem is that this quest:
[akis.txt](https://github.com/PikaMug/Quests/files/5839561/akis.txt)
is from the NPC who you recieve the map from, and it shouldn't show until after the map delivery quest is done.

**Comment by PikaMug** [comment]
You may be able to prevent this by setting the first quest as a requirement of the second, under Edit Requirements in the Quests Editor. Then, perhaps set `ignore-locked-quests: true` in your _config.yml_ file.

Also, please consider updating to the latest version of Quests.
