### ISSUE TITLE
Splash Potion Brewing

### ISSUE THREAD

**Issue by Revanrose6** [PikaMug/Quests#1578]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.0-rc.4.jar

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When you put brewing or using a Splash Potion as the objective it does not have the word 'Splash' so players have no way of knowing you want a splash potion. That being said, it still requires you to brew a splash potion.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/utAPKYLi
https://imgur.com/a/pROYzp0

**Comment by Revanrose6** [comment]
It also doesn't say which specific potion for 'Consume'
https://imgur.com/a/XbpFJv4``

**Comment by PikaMug** [comment]
@Revanrose6 Thanks for the report. Please answer the following:

- What is your server's Minecraft version (and client's if using ViaVersion/ViaBackwards)?
- Is `translate-names` set to `true` or `false` in your _config.yml_ file?

**Comment by Revanrose6** [comment]
1.16.4 MC Version and 1.16.4 Client.

Config Part:
translate-names: true
translate-subcommands: false
