### ISSUE TITLE
Error trying to start a quest D:

### ISSUE THREAD

**Issue by Drakemlumme** [PikaMug/Quests#1579]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.4
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
(I use paper) I created a mission with an npc (it was a test mission because it was the first mission I did, I was testing the plugin, since I had downloaded it a few hours ago) and then I deleted that test mission, and I created a new one, but when I right click on npc, nothing happens.
I look at the console and I get this error.
https://pastebin.com/raw/15dsv1Ya
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Sure
https://pastebin.com/raw/N7Rz3j9n

**Comment by Drakemlumme** [comment]
by the way, I was reading the console error ... and now I remember that the first thing I did with the plugin was to try to delete the missions that come by default, which are 4 missions. when deleting the first one, the plugin made a bug (I think) and instead of showing me 3 remaining missions, it only showed me one.

**Comment by Drakemlumme** [comment]
I deleted the other quests that come by default and the error no longer appears in the console. however I still cannot start any quest, I have created other quests with other conditions with other npc's and it tells me that there is no quest available :/

**Comment by Drakemlumme** [comment]
I used the /quests admin reset command and was able to go back to doing missions again! So maybe it's my mistake that I misconfigured the plugin? do players have a limit of missions that they can do? because once I complete a mission I can't do any more missions. is it some value in config? pls help T_T

**Comment by DeadlykillOfficial** [comment]
`Requirement quests has invalid quest name Iron Miner, see quest of ID default2` - Error is briefly explained. You have deleted missions from file itself. Instead of using the Editor ingame.

**Comment by Drakemlumme** [comment]
> I deleted the other quests that come by default and the error no longer appears in the console.
hello sir, i've already done that
but the problem is that I can't do more than one mission, is it some value in the plugin configuration file?

**Comment by Drakemlumme** [comment]
> 
> 
> I deleted the other quests that come by default and the error no longer appears in the console. however I still cannot start any quest, I have created other quests with other conditions with other npc's and it tells me that there is no quest available :/

hello sir, i've already done that
but the problem is that I can't do more than one mission, is it some value in the plugin configuration file?

**Comment by PikaMug** [comment]
Issue has been resolved. As for the config question, see `max-quests` https://github.com/PikaMug/Quests/wiki/2-%E2%80%90-Configuration
