### ISSUE TITLE
Potion Brew Creates Potion Consume

### ISSUE THREAD

**Issue by Revanrose6** [PikaMug/Quests#1580]
**What is your Quests version / build number (do _not_ say "latest")?**
<img width="530" alt="Screen Shot 2021-01-22 at 4 07 20 PM" src="https://user-images.githubusercontent.com/6682989/105561581-f1379400-5ccb-11eb-955a-7e72ab8ab4f3.png">
This also happened when I was using the Quests-4.0.0-rc.4.jar
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When I make quests that have 'Brew a Potion' when I reload, it adds 'Consume' to the same Potion.
<img width="626" alt="Screen Shot 2021-01-22 at 4 01 20 PM" src="https://user-images.githubusercontent.com/6682989/105561644-35c32f80-5ccc-11eb-98d8-221167e91cce.png">

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
You are using an official build. Please try the latest at https://ci.codemc.io/job/PikaMug/job/Quests/

If the issue still occurs, reply with the quest from your _quests.yml_ file (use Pastebin or Hastebin) and I'll re-open.

**Comment by Revanrose6** [comment]
I updated to the build you showed 
<img width="542" alt="Screen Shot 2021-01-23 at 12 39 37 PM" src="https://user-images.githubusercontent.com/6682989/105617113-9d8f7e00-5d91-11eb-972f-33ade9e0b841.png">


and removed the 'Consume' part. Waited a bit, reloaded a few times while editing other quests, opened up that quest, and the Consume part was back. It also keeps showing back up in the Quests.yml config.

<img width="348" alt="Screen Shot 2021-01-23 at 3 43 36 PM" src="https://user-images.githubusercontent.com/6682989/105617161-358d6780-5d92-11eb-89d3-27aebc8c5119.png">
<img width="676" alt="Screen Shot 2021-01-23 at 3 44 49 PM" src="https://user-images.githubusercontent.com/6682989/105617162-39b98500-5d92-11eb-922b-181132308adf.png">

https://pastebin.com/6nuvZeNu

**Comment by PikaMug** [comment]
Fixed in f7cb0d2

Use https://ci.codemc.io/job/PikaMug/job/Quests/206/
