### ISSUE TITLE
Consuming items does not save when re-editing the quest

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1582]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.0-rc.4-b191
![image](https://user-images.githubusercontent.com/74351200/105579407-b0e91c00-5d86-11eb-88d1-1374d41788be.png)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When I add the objective "to consume items", like bread.
![image](https://user-images.githubusercontent.com/74351200/105579073-89914f80-5d84-11eb-9ef2-e41fa5c17073.png)
![image](https://user-images.githubusercontent.com/74351200/105579348-4932d100-5d86-11eb-9369-c554f8f4e93b.png)
![image](https://user-images.githubusercontent.com/74351200/105579358-62d41880-5d86-11eb-9418-bec5bd9e0901.png)
_consume items_

I save the quest and reload it.
If I have to re-edit the quest because something is missing.
The objective is deleted. "Consume bread" is no longer there and it says nothing has been defined.
![image](https://user-images.githubusercontent.com/74351200/105579086-9f9f1000-5d84-11eb-92af-646a483f2f3b.png)
![image](https://user-images.githubusercontent.com/74351200/105579369-70899e00-5d86-11eb-8080-3daf876bb2ae.png)
_consume items before re-edit_

On the other hand if the quest is saved with the objective, players can accomplish that objective.
I think the problem appears when editing the quest.

**Comment by PikaMug** [comment]
Thanks for the report. Please confirm whether or not this still occurs on the latest development build:
https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by Beubeux74** [comment]
Thanks for your answer, i wait my server's administrator who's to update the plugin,  and i answer again when i try it with the latest version (b205).
Thanks for waiting and try to patch this.

**Comment by Beubeux74** [comment]
So, i retry to edit my quests and the bug is still present
![image](https://user-images.githubusercontent.com/74351200/105707952-030b7800-5f14-11eb-989f-b5bbb909332d.png)
After reload
![image](https://user-images.githubusercontent.com/74351200/105707952-030b7800-5f14-11eb-989f-b5bbb909332d.png)

**Comment by PikaMug** [comment]
Duplicate of #1580 

Use Use https://ci.codemc.io/job/PikaMug/job/Quests/206/
