### ISSUE TITLE
The description text loses its colors in the npc gui menu

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1584]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.0-rc.4-b191 (French language)
![image](https://user-images.githubusercontent.com/74351200/105631092-e8220080-5e4c-11eb-8660-9eb0bc75ce47.png)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

When we write a long description like this
`&6For example, when we write a long description, the color change and become purple but i start with yellow`
![image](https://user-images.githubusercontent.com/74351200/105631130-1d2e5300-5e4d-11eb-8d81-44cbee9651a7.png)

If the text is too long, it continues on the second line of the item's lorename.
But if we want to put color like the with & 6, when it comes back to the line the color is reset by default.
You can work around this problem by putting &6 back in front of the word that appears on the line, but it's a bit annoying.
`&6For example, when we write a long &6description, the color change and &6become purple`
![image](https://user-images.githubusercontent.com/74351200/105631250-d8ef8280-5e4d-11eb-8f17-6afcfa233066.png)

unless it is not intended that we use colors in this function?

**Comment by DeadlykillOfficial** [comment]
This is sadly how Minecraft lore works. Whenever it's too long it get's split into multiple lines to be able to fit on screen. Therefor it reset color codes for it. But i'm sure Pika would be able to find solution to that.

**Comment by PikaMug** [comment]
Unfortunately, there's no way to programatically tell where the Minecraft client is going to split the text (afaik). One would think you could count characters, but some are wider than others (like 'i' is wider than 'o'). The workaround that OP proposed is really all that can be done.
