### ISSUE TITLE
When trying to select a quest from an NPC using the GUI, it doesn't respond

### ISSUE THREAD

**Issue by bluesensei** [PikaMug/Quests#1585]
When trying to select a quest from an NPC using the GUI, it doesn't respond. The GUI flashed and doesn't let you exit out of it, resulting in you having to quit the game
![QuestGUIBug](https://user-images.githubusercontent.com/41272366/105643923-b6c82580-5e8a-11eb-83e5-5f950cd47121.gif)

**Comment by Beubeux74** [comment]
Pika needs your plugin version for an better help, write the command `/quests info` in game and edit your post

**Comment by PikaMug** [comment]
Issues with QuestsGUI must be reported in the discussion thread at https://www.spigotmc.org/threads/questsgui-paid.399346/
