### ISSUE TITLE
Can't Use Command to get Journal

### ISSUE THREAD

**Issue by GeneralGigan** [PikaMug/Quests#1586]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0rc

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When I try and use the command /quest journal and it says an internal server error and the console spits this out: 

25.01 18:16:39 [Server] INFO GeneralGigan issued server command: /quests journal
25.01 18:16:39 [Server] ERROR null
25.01 18:16:39 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'quests' in plugin Quests v4.0.0-rc.4-b191
25.01 18:16:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.57]
25.01 18:16:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.57]
25.01 18:16:39 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.57]
25.01 18:16:39 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
25.01 18:16:39 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
25.01 18:16:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
25.01 18:16:39 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/blackvein/quests/item/QuestJournal
25.01 18:16:39 [Server] INFO at me.blackvein.quests.listeners.CmdExecutor.questsJournal(CmdExecutor.java:690) ~[?:?]
25.01 18:16:39 [Server] INFO at me.blackvein.quests.listeners.CmdExecutor.questsCommandHandler(CmdExecutor.java:267) ~[?:?]
25.01 18:16:39 [Server] INFO at me.blackvein.quests.listeners.CmdExecutor.onCommand(CmdExecutor.java:91) ~[?:?]
25.01 18:16:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.57]
25.01 18:16:39 [Server] INFO ... 13 more

Also! I run a modded server and when I try and make it so you must kill Modded Mobs it says you have to kill "null"
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. Do you have [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) installed?

**Comment by GeneralGigan** [comment]
> Thanks for the report. Do you have [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) installed?
> 
> EDIT: Which release of Quests are you using? -rc4? -rc3?

I tried with and without Quests GUI and it didn't work and the version is 4.0.0-rc.4-b191

**Comment by PikaMug** [comment]
Thanks for that information. QuestsGUI does not support 1.7.x protocol (see Tested Minecraft Versions on [the Spigot page](https://www.spigotmc.org/resources/questsgui.71666/)). Please double check that is not installed; as it appears to be the cause of this error. Often multiple versions may be installed by mistake.

I was unable to replicate the issue with only Quests 4.0.0-rc.4 and Citizens 2.0.13-SNAPSHOT (build 1130) installed on a 1.7.9 server:

![journal](https://user-images.githubusercontent.com/2267126/105776992-9609d980-5f37-11eb-9bca-0f3a8dea913f.png)

Even after accepting a quest, there were no issues. If you have any additional information that may be useful in replicating the error, please feel free to reply below.
