### ISSUE TITLE
Completed-Quests after restart server will disappear 

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1589]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.0-rc.4#200

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No console error

After the server restart, a player found out that part of his completed quests have been disappear from his quests stats. This problem have occur not only once but multiple times. before i was using rc.3#170 don't have this problem.

The following google drive link provided quest.yml , a bugged quest data and a backup-ed normal quest data of same player , Eternal_Power. The backup start at 2021/01/28 after server stopped at 0930am, so the normal one is a extracted from zipped backup file, the bugged one is a copy ~10:00 when server is restarted.

Quest data normal:
https://pastebin.com/phC9u2Gy

Quest data bugged:
https://pastebin.com/vJ0PkcbC

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
The file is too big, paste bin don't allow me to upload
https://drive.google.com/drive/folders/1cFDPHEw0CgmeIDY33o8DORHodCeJFx6U?usp=sharing

**Comment by DeadlykillOfficial** [comment]
Use pastebin instead. So nobody has to download any kind of files.

**Comment by hkkongou** [comment]
the problem is pastebin say my quest.yml is too big and don't allow me to upload :(

**Comment by hkkongou** [comment]
![image](https://user-images.githubusercontent.com/61608872/106083471-849f1800-6157-11eb-9aa5-ddd82cfc77c2.png)

**Comment by hkkongou** [comment]
the two quest data i have uploaded to pastebin, but the quest.yml cannot

**Comment by DeadlykillOfficial** [comment]
I've run the ymls through compare tool and Before -> After seems like Extremely different files
![image](https://user-images.githubusercontent.com/12415714/106083638-1b021800-611d-11eb-8139-abb9b469eb36.png)
We are speaking about lots of changed data. Not sure if Quests is even touching that part of data.

**Comment by DeadlykillOfficial** [comment]
![image](https://user-images.githubusercontent.com/12415714/106083820-6fa59300-611d-11eb-83d7-9f802948a8ec.png)
have you finished other quests after the backup or what exactly did you did?

**Comment by hkkongou** [comment]
This is my server player, i assume they just normally finish quests in game like normal, as usual i close the server, use zip the entire plugin folder then restart the server, after restart the server the player say his data got lost and i saw his quest data by "/qa stats " is missing a large part of quest which is totally different from yesterday

**Comment by DeadlykillOfficial** [comment]
Yeah lots of data is different in both files but weird thing is Timestamps as well. I guess Pika would have to check this out and see what eventually reason could be.

**Comment by hkkongou** [comment]
![image](https://user-images.githubusercontent.com/61608872/106084065-8a492d80-6158-11eb-87fb-49b4dafe270d.png)

The arrow one means unlock LV10, the quest is designed that player have to finish LV1 -> LV2 .... LV9 so that he can unlock LV10, thats no way for him to unlock LV10 without doing the previous quest. And i have the record that the player have LV1 - LV10 unlock yesterday and before, just don't no why this morning LV1 -LV9 and all other finished data is missing

**Comment by DeadlykillOfficial** [comment]
Keep in mind there are major changes from rc.3 to rc.4. in player files and bug fixes. You can even see that your plugin is missing strings therefor it output "NULL"

**Comment by hkkongou** [comment]
> Keep in mind there are major changes from rc.3 to rc.4. in player files and bug fixes. You can even see that your plugin is missing strings therefor it output "NULL"

yes i know, i have read the quest jenkin update info
these all problem seems started when the quest data change from store ``Quest id`` instead of ``quest name``

**Comment by hkkongou** [comment]
This is another player called Anson_104 , two record from 20210114 and 20210128, as you can see 0128 version (today) have missed the entire completed-quests but the complted redoable quests exist.

20210114
https://pastebin.com/4G2egFrw
20210128
https://pastebin.com/WZVx1QRt

**Comment by PikaMug** [comment]
In reference to the original pastes, the two files are effectively identical except that ids from `custom1104` to `sarenluckydraw` have been removed from `completed-Quests`. While the other lists appear modified at a glance, they are simply in a different order. Same goes for the second set of paste just posted, but all `completed-Quests` bullets were removed instead of just some.

Something is causing the `completed-Quests` list to be modified or reset.

@hkkongou Can you obtain the server logs from both before and after the restart, and filter for any messages from [Quests]? Of particular interest are errors and command logging from staff. Anything not from [Quests] can be deleted.

**Comment by hkkongou** [comment]
i try my best, there are many messages need to be filtered

**Comment by hkkongou** [comment]
These are the [quests] log after server restart:
https://pastebin.com/imrSYtTP

**Comment by hkkongou** [comment]
These are the [quests] log before server restart, start from 00:00am to 09:30 restart 
https://pastebin.com/XJeiAFzB

**Comment by PikaMug** [comment]
Thanks for the additional information. I was hoping to find a lead there, but the logs seem ordinary.

I've spent several hours trying to replicate this - taking and quitting quests, resets and restarts. Nothing remotely similar happened. At this point, I'll likely be placing a bounty on this bug via https://www.spigotmc.org/forums/hiring-developers.55/

**Comment by hkkongou** [comment]
this problem again, happened today.
i checked the backup i suspect crash of server/ kill server (due to plugin freeze during server stop) will lead this to occur.

However, the backup after server killed  seems normal , but after the server restart (and running now) , the file corrupted.
Bugged,copy when server currently loading
https://pastebin.com/873HQ5VQ 

backup of today after server killed (same as yesterday)
https://pastebin.com/E155RS60

**Comment by PikaMug** [comment]
@hkkongou Thanks for that info. Please give this development build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/219/

Continue to perform regular backups for the time being.

**Comment by hkkongou** [comment]
thank you, i will install that quick and continue check for anything if the problem happens

**Comment by elaineandsparky** [comment]
Just going to jump in here and say I am having similar problems. I'm using version 4.0.0-rc4 and from what I can see, 2 of our quests (we have over 100) are also resetting when a player logs off or the server restarts

**Comment by DeadlykillOfficial** [comment]
It's been few weeks i believe since 4.0.0 is released. You should consider updating. Preferably to latest dev build from CodeMC.

**Comment by elaineandsparky** [comment]
just did :) it still isn't happy but it appears putting the quest journal away and getting it back out solves the issue. So it seems like it is the journal that has the problem and not the quests itself as after getting it back out from putting it away the quests were loaded again partially completed

**Comment by DeadlykillOfficial** [comment]
From what i've looked few days ago in the code about Journal it seems like coded to update objectives constantly. But there were also parts of the code i couldn't understand and made no logic for me. Since i have never used the journal you should wait for Pika to technically reply on that. But it's very possible that it's buggy.

**Comment by hkkongou** [comment]
For my server
I have questGUI installed , so it load the quest GUI journal instead of the quest build in journal.

I have purchased questGUI and used it for more than 3 months, the report I made above and all the record above are record installed with questGUI, so I am not sure will quest build in journal affect the data 
(Just go give some info , don't know can help or not
And updating the dev build given before, I am still waiting for my players to report for any missing data, hopefully this bug is gone, I am still watch

**Comment by PikaMug** [comment]
Closed pending any further issues.

**Comment by hkkongou** [comment]
another player's quest data got TOTALLY reset today( 1 hour ago from now), the player reported that after a server restart, all of the quest recorded data is gone. This have been confirmed by me checking the files:

bugged files, still loading in server, restart at UTC+8 18:00:
https://pastebin.com/WGvXPGUL

normal file, backup today 09:30
https://pastebin.com/6W3p6RXu

**Comment by PikaMug** [comment]
@hkkongou Please update to [Quests 4.0.1](https://www.spigotmc.org/resources/quests.3711/) as that improved how player data is reloaded.

**Comment by hkkongou** [comment]
sure, i will update today
Thank you

**Comment by hkkongou** [comment]
update:this issue is still exist in #230 build released 12 days ago
there is no server crash / kill during these day, all server start up and shut down are normal

nomal backup, 1 day before 2021/03/27
https://pastebin.com/NdiYRGRJ

bug 2021/03/28
https://pastebin.com/AEfPgm4k

i will try to update #233 (which is the latest build today) and keep watching for the situation

**Comment by hkkongou** [comment]
this problem occured today again
2 players reported the same problem after them have been unjailed (essX) and luckperms permission set back to normal (without * permission false)
would this be related to the this problem
