### ISSUE TITLE
Malicious villager

### ISSUE THREAD

**Issue by szumielxd** [PikaMug/Quests#1591]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.4-b191 (4.0.0-rc.1 also)

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When you setup villager as a mob to kill in stage and type /quest, console will print stack traces due to null extra data in message. The same think happens when you kill villager in valid radius or complete the previous stage.
Short StackTraces:
>Caused by: java.lang.NullPointerException: Name is null
>        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_242]
>        at org.bukkit.entity.Villager$Profession.valueOf(Villager.java:90) ~[spigot.jar:git-Paper-1618]
>        at me.blackvein.quests.util.LocaleQuery.sendMessage(LocaleQuery.java:268) ~[?:?]
>        at me.blackvein.quests.Quests.showObjectives(Quests.java:1220) ~[?:?]
>        at me.blackvein.quests.listeners.CmdExecutor.questCommandHandler(CmdExecutor.java:210) ~[?:?]
>        at me.blackvein.quests.listeners.CmdExecutor.onCommand(CmdExecutor.java:89) ~[?:?]
>        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Paper-1618]
>        ... 15 more

Full StackTrace: https://pastebin.com/iFqCT11y

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/A2zLSjkV

**Comment by PikaMug** [comment]
Thanks for the report. What is your Minecraft server version?

**Comment by szumielxd** [comment]
Paper-1.12.2-b1618

**Comment by PikaMug** [comment]
Please give the following build a try. Note that it may not be compatible with the current version of QuestsGUI, if installed.
https://ci.codemc.io/job/PikaMug/job/Quests/212/
