### ISSUE TITLE
Toggling the silk touch alert

### ISSUE THREAD

**Issue by Sidewardduke** [PikaMug/Quests#1592]
There's no way that I could find to disable the _optionSilkTouchFail_ alert. It gets kind of annoying when trying to mine with silk touch with a quest. From what I found it's within BlockListener.java at about line 69, hardcoded to alert for every time they mine. It would be nice if we were able to toggle the alert or how many blocks it takes before the alert goes off within the config as it currently spams the crap out of chat each time you use it.

**Comment by PikaMug** [comment]
Edit [Options](https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Options) -> General -> Ignore blocks broken with Silk Touch: false
