### ISSUE TITLE
Quests Editor not working with BungeeChat

### ISSUE THREAD

**Issue by CCedDev** [PikaMug/Quests#1594]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests-4.0.0-rc.4 # 212

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
The Quests Editor (/quests editor) chat selector not working with BungeeChat. You get into the editor, but then you can't enter a number and you can't get out of the editor.
No errors in console.

**Comment by PikaMug** [comment]
Thanks for the report. Quests does not officially support BungeeCord or BungeeChat at this time, but I'll try looking into it soon. Can I get your BungeeCord and BungeeChat version numbers, please?

**Comment by CCedDev** [comment]
BungeeCord: BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT
bungeeChat: 2.2.3.1241

**Comment by PikaMug** [comment]
For those interested, it seems this fork is attempting to support BungeeChat:
https://github.com/jely2002/Quests

**Comment by PikaMug** [comment]
https://github.com/WiIIiam278/HuskChat/issues/102#issuecomment-1435691862
