### ISSUE TITLE
i cant modify quests

### ISSUE THREAD

**Issue by Kebabo20** [PikaMug/Quests#1595]
Massive Update Pre-Release 4

when i modify a quest and do /questadmin reload, ALL the quests will be eliminated

**Comment by PikaMug** [comment]
Thanks for the report. I'm unable to replicate the issue. Please provide your _quests.yml_ file for testing (use Hastebin/Pastebin.com).

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
