### ISSUE TITLE
Quests not loading saved quests

### ISSUE THREAD

**Issue by zkislow** [PikaMug/Quests#1600]
**Where else have you looked for answers to this question?**
See last issue

**Share your question with as much detail as possible?**
The only error the console shows for quests plugin is "cannot load configuration from stream" We still  have all the plugin data and saved quests but they do not show up or run in game.
How do I fix the issue of "cannot load configuration from stream"?

**Comment by PikaMug** [comment]
Sounds like your _config.yml_ file may have been corrupted. Try moving/deleting the file and letting the plugin regenerate it.

If that doesn't work, make sure that your _/plugins_ folder has full read permissions. See the Troubleshooting guide at https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting
