### ISSUE TITLE
send the same message twice

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1602]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.00-rc.4-b206
![image](https://user-images.githubusercontent.com/74351200/107281508-1103e180-6a5a-11eb-9bc3-007fcddce399.png)

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When I ask for the id of a npc, while editing a quest by clicking on the npc, I see the message twice.
I also have this problem when a time limit before resuming the quest is set. 
I just click one time
![image](https://user-images.githubusercontent.com/74351200/107281608-2e38b000-6a5a-11eb-9c6a-c481fdcf3840.png)
![image](https://user-images.githubusercontent.com/74351200/107281714-4d374200-6a5a-11eb-963d-079b161ce6fe.png)

**Comment by PikaMug** [comment]
Already resolved in the latest development build (not compatible with QuestsGUI):
https://ci.codemc.io/job/PikaMug/job/Quests/
