### ISSUE TITLE
Action: Timer is not accepting my input

### ISSUE THREAD

**Issue by terakasel** [PikaMug/Quests#1604]
**What is your Quests version / build number (do _not_ say "latest")?** 
Quests-4.0.0-rc.4-b191

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I'm trying to set the time for the Action Timer, but it won't accept the input.
It's telling me to enter, in seconds, the length of the timer.  I'm putting in 180 for 3 minutes, but it just repeats the same message telling me to put in the time I want and doesn't accept the input.  There are no errors in the console.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
It's an Action.

https://pastebin.com/D1dVi3Xs

**Comment by terakasel** [comment]
So apparently, just using 180 doesnt work, but using 180seconds does.  Strange.  
I also updated to the latest build (b213), so that's not any issue.

**Comment by PikaMug** [comment]
Thanks for the report. Please try the following build (not compatible with QuestsGUI):
https://ci.codemc.io/job/PikaMug/job/Quests/214/
