### ISSUE TITLE
Some quests aren't showing the entire reward list.

### ISSUE THREAD

**Issue by Simkets** [PikaMug/Quests#1606]
**Quest version:** 
Quests-4.0.0-rc.4

**Issue:**
I've just noticed one 'weird' thing on my server. I was casually testing out the quests, spotting some grammar mistakes, and so on when I've noticed that some quests don't show the entire reward list. For example, I have a **Quest A** that rewards: 200€, 1 quest point, and 1 command reward. Then I have a **Quest B** that rewards: 150€, 1 quest point, and 1 command reward. BUT! The **Quest A** shows the entire list of rewards like this while the **Quest B** shows only the command reward (But still gives the player the money and quest points, it just doesn't tell them). Picture of the **Quest A** reward list:

![questA](https://user-images.githubusercontent.com/78814693/107401874-98f1f600-6b03-11eb-9882-a1889de41df5.png)

**Quest B** Here you can see that I've gained 1 quest point, 150 money and 2 potions. Yet only the command reward is announced

![QuestB](https://user-images.githubusercontent.com/78814693/107401870-97c0c900-6b03-11eb-8a6e-ebe35d9433b0.png)

This is the quest.yml log of **Quest A**
https://pastebin.com/K5LN7Yv2

This is the quest.yml log of **Quest B**
https://pastebin.com/pYhJy4uj

Thank you for your help!

**Comment by PikaMug** [comment]
Thanks for the report. Quest A is using a "commands-override-display" which is used to override the default reward text for command rewards. Quest B is using a "details-override" which overrides _all_ reward text. In other words, things are working as expected.

It looks like the editor prompt for setting commands-override-display is suppressed in recent builds; not sure why. For now, just copy over that section in your config from Quest A to Quest B, and either _/qa reload_ or restart the server.

**Comment by Simkets** [comment]
Thank you so much for your dedication to this plugin and for your hard work!
It worked! Have a nice day. ^^

**Comment by PikaMug** [comment]
You're welcome. Just as a follow-up, I found the following information from the SpigtoMC update notes for Quests 3.9.0:

> Editors can now set text overrides for rewards and requirements. As such, command-specific overrides can no longer be set, however, existing ones will continue to work as expected.
