### ISSUE TITLE
Server crush

### ISSUE THREAD

**Issue by slatterslatty** [PikaMug/Quests#1607]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.0
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
as soon as i type the command /quests my server lags and kicks me for "Timed Out"
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by DeadlykillOfficial** [comment]
We provide support only for latest Quests. You are using quite outdated one. I'd highly suggest you update your pluign before reporting bugs.

**Comment by slatterslatty** [comment]
I had the 4.0.0-rc.4 version and it did the same thing so i figured i would chose the one closest to my server's version.

**Comment by DeadlykillOfficial** [comment]
Every Quest version support 1.7.10-1.16.5
You would want to always update to latest development build and test it out. Providing error logs would be also quite useful.

**Comment by PikaMug** [comment]
Will re-open once OP has upgraded to 4.0.0-rc.4 and shared whatever console message/error they get when kicked.
