### ISSUE TITLE
My quests have disappeared but only in game

### ISSUE THREAD

**Issue by percyjacksons** [PikaMug/Quests#1608]
**Where else have you looked for answers to this question?**
- I've googled and searched the spigot forum but thus far have been unable to find anyone with an answer to my dilemma.

**Share your question with as much detail as possible?**
So, basically, I've been making quests on my server for many months now and on different servers for years but somehow, as I was finishing up this one quest and ran /questadmin reload it deleted all of the quests. Forced me and others on the server out of already active quests and has wiped all contents of /quests list. However, in the console all of the quest information is still there in the quest.ytml thing. The only missing data in console is player data i.e. who has taken what quests. I don't know if this is an unsolvable issue or a bug or what. I'm happy to give more information if need-be but I'm not sure what else might be needed!
Thanks.

**Comment by PikaMug** [comment]
Please re-submit this as a Bug Report instead of a Question. Include all relevant information.
