### ISSUE TITLE
Translation concerns

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1609]
**What is your Quests version / build number (do _not_ say "latest")?** Quests 4.0.0-rc.4-b214

**What does your feature do?**
I noticed that 2 prerequisite features have unclear translations and despite your updates it still does not seem to be fixed.
The translations are not very exact but above all are reversed
![image](https://user-images.githubusercontent.com/74351200/107874810-7f163180-6ebc-11eb-979c-cf78ca32239c.png)
**"Define quest requirements" (définir les exigence de quests)** in french
to be replaced by
**"Define the prerequisite quest" (Définir la quête prérequise)** in french

and the second
![image](https://user-images.githubusercontent.com/74351200/107874846-cb617180-6ebc-11eb-88d2-f8e15bdd4b2c.png)
**"Define the requirements of the deposit request" (Définir les exigence de la quête de consigne)** in french
to be replaced by
**"Require a number of quest points" (Exiger un nombre de points de quête)** in french

If you can also replace
**"To milk the cows"  (Pour traire les vaches)** in french
by
**"To milk cows" (Traire des vaches)** in french

**Comment by PikaMug** [comment]
Translations must be submitted on Crowdin. See https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations
