### ISSUE TITLE
Hide the quest if the prerequisite is not validated

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1610]
**What does your feature do?**
Add an option in the prerequisite menu "hide the quest if the player does not have the prerequisites"
This would allow the continuation of a quest to be hidden, but also to make the quest more realistic.
A npc tells you that he needs your help but in the end he doesn't know you enough to help him. 
![image](https://user-images.githubusercontent.com/74351200/107877321-f4d5c980-6ecb-11eb-9594-7a31dc4ba1f6.png)

**How would people use it?**
When a player clicks on a npc, if he has the prerequisites for example enough quest points, the quest is visible in the list of quests offered.
Otherwise it is hidden 
![image](https://user-images.githubusercontent.com/74351200/107877254-91e43280-6ecb-11eb-855b-bd892ee5f937.png)

**Comment by DeadlykillOfficial** [comment]
This option already exist in config.yml `hide-locked-quests`

**Comment by Beubeux74** [comment]
Would it be possible to hide only certain quests ? (for example if the prerequisite is to have blocks that would allow the player to get them)

**Comment by DeadlykillOfficial** [comment]
You can either hide ALL quests or no. It's based on testRequirement. If player meet req. It does show it, if it doesn't it does not show it.

**Comment by Beubeux74** [comment]
Ok too bad, you can put the question tag and remove the enhancement and close the post if that is not possible, put the choice for each quest.
thank you for your reply
