### ISSUE TITLE
Can someone help me an unknown error occurred

### ISSUE THREAD

**Issue by harispoppylatip** [PikaMug/Quests#1611]
Can someone help me

[Mon, 15. Feb 2021 00:12:36 UTC INFO] harispopmie issued server command: /questadmin reload
[Mon, 15. Feb 2021 00:12:36 UTC INFO] Loaded language en-US. Translations via Crowdin
[Mon, 15. Feb 2021 00:12:36 UTC WARN] java.lang.NullPointerException
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at me.blackvein.quests.util.ConfigUtil.checkList(ConfigUtil.java:48)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at me.blackvein.quests.Quests.loadQuestRewards(Quests.java:1742)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at me.blackvein.quests.Quests.loadQuests(Quests.java:1606)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at me.blackvein.quests.Quests$3.run(Quests.java:1530)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Mon, 15. Feb 2021 00:12:36 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:834)
![16133483907855360952746503593803](https://user-images.githubusercontent.com/36255874/107893502-a590a700-6f66-11eb-8bdf-c1d8ca7d5e01.jpg)

**Comment by DeadlykillOfficial** [comment]
Firstly you are not following Github layout and your ticket is invalid.
Secondly as i have told you in Discord. The issue is called by having a null items in your Rewards. As you are prompted "see console output" normally Quests should tell you which quest is that. If not you would have to find which quest you put null item in.

**Comment by PikaMug** [comment]
Would need to see the _quests.yml_ file, but it sounds like OP has already received support via Discord.
