### ISSUE TITLE
Region Not Working In 1.15.2

### ISSUE THREAD

**Issue by JavaDevep** [PikaMug/Quests#1613]
build Quests 4.0.0-rc.4,using 1.15.2 paper spigot. When Setting a quest that use a region the player does not start the quest when he enter the region im fast-async-worldedit and the last 1.15.2 version of world guard bukkit build.is it possible to fix this or is it just me doing something wrong.(Yes I Reloaded server /reload confirm & /questadmin reload ) 
thx a lot Amazing plugin 5/5
**What is your Quests version / build number (do _not_ say "latest")?**

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by PikaMug** [comment]
Thanks for the report. Please share your WorldGuard version number as well as the example quest via pastebin.

**Comment by DeadlykillOfficial** [comment]
I'm afraid you understood the Region option wrongly. Setting up region for Quest do not mean the quest will automatically start when player enter the region instead. It would allow player to only `/quests take <quest name>` this particular quest inside the region.

**Comment by JavaDevep** [comment]
@DeadlykillOfficial Oh my fault then its working I misunderstand this feature of the plugin but now I get it ;)
Then I would like to add a suggestion that allows to auto start quest when you enter a region or is there already a way to do that?

@PikaMug 
-Request (Add A Way To Reorganize GUI when connecting them with citizen, because sometime quest are not showing up in the order you would like too)

**Comment by DeadlykillOfficial** [comment]
There might be a way doing that. But i'm afraid it must be 3rd party plugin doing that.

**Comment by DeadlykillOfficial** [comment]
As i highly doubt such option would ever be added to Quests. Basically due to fact it keeps track of "PlayerMoveEvent" Which is quite laggy to check... Soo it would lag out servers quite much.

**Comment by JavaDevep** [comment]
Ok @DeadlykillOfficial  I Think you are right

Thx for informing me
