### ISSUE TITLE
Quests Is Reporting An Issue. I Will Put My Latest Log...

### ISSUE THREAD

**Issue by Grallow** [PikaMug/Quests#1614]
My server is paper spigot 1.16.2.

Im using Quests version 4.0.0

I just saw it was giving an error in the console. My server keeps crashing for an unknown reason so im checking all the errors from plugins to see if that is whats causing the crashes.
Other than that, the quests seem to be fine (i think) but there is some error i'd like to fix, thanks.

My log before crash...
https://pastebin.com/QSs2yp3r

**Comment by PikaMug** [comment]
Thanks for the report. First, your language file needs to be updated. You can do this manually, or just delete the _/lang_ folder and let the plugin regenerate it.

Second, I see a number of errors with other plugins you should address, but as for Quests your quest IDs custom32-35 reference NPCs which do not exist (either Citizens didn't load it or the NPC was deleted). Either restore the NPCs or edit/delete the quests within the _quests.yml_ file.
