### ISSUE TITLE
Supporting SimpleClans

### ISSUE THREAD

**Issue by TomLewis** [PikaMug/Quests#1615]
You have supported Parties as a Clan system or your v4 which is brilliant, I used to use Parties years ago. But SimpleClans is superior in every single way.
Lots of people do not realize that it was picked up and activity developed by a new developer!
https://www.spigotmc.org/resources/simpleclans.71242/

Please can you support SimpleClans in the same way you do with Parties.

**Comment by PikaMug** [comment]
Thanks for the suggestion. It is my intention to support more of these plugins, but I'd like to first find a way to do so without overcrowding the options. My initial idea is an API similar to Vault but for party/group/clan plugins, but that's nothing concrete. Will update this ticket as my thoughts progress.

**Comment by TomLewis** [comment]
Sounds awesome! SimpleClans is one of the OG's, it was there before Parties and it far surpasses Parties. I temporarily used Parties when SimpleClans got abandoned years ago, but luckily SimpleClans was picked up and is updated regularly again from a new developer, it already has an API to easily call.

Its always an uphill battle getting developers to use another developers API, as they always say "I will create my own API that the other dev can use"! For speed, the SimpleClans API is ready to go and add support for!

Obligatory xkcd: https://xkcd.com/927/

**Comment by PikaMug** [comment]
Now waiting on https://github.com/RoinujNosde/SimpleClans/issues/291

**Comment by TomLewis** [comment]
Exciting!
