### ISSUE TITLE
Adding formats to language ymls

### ISSUE THREAD

**Issue by CubBossa** [PikaMug/Quests#1616]
**What does your feature do?**
There are some chat formats that could be pretty useful that are not messages but just formats.
For example, when someone starts a quest he will get the message "%gold%- %magenta%<quest> %gold%-"
I changed the other heading messages and didn't realise this one was missing in the language files. Now the whole other format doens't look complete.
I would love this to be added to the messages ymls.

**How would people use it?**
I would use "%gray%⚌⚌ %magenta%<quest> %gray%⚌⚌" for example so it will work with the other headings

**Comment by PikaMug** [comment]
Thanks for the suggestion. Could you provide a screenshot of the message in question?

**Comment by CubBossa** [comment]
I hope you dont mind that its german. The first message block has an already configured heading and for the second one (- Wettmeister Piglinintrige -) I could find a configuration option.
![Unbenannt](https://user-images.githubusercontent.com/66269026/108589426-71e6c000-735e-11eb-8f37-e243243b94cc.png)
