### ISSUE TITLE
Ambiguous Mob Killing

### ISSUE THREAD

**Issue by TCGCardcast** [PikaMug/Quests#1617]
Is there a way for the Kill Mob Objective, to make it so I can have my players need to kill 5 of ANY mob, instead of 5 of EVERY mob. 

I have tried over and over again, and looked in many places for the answer, and Cannot find it. 

If anyone has the answer, please respond asap.

**Comment by PikaMug** [comment]
No, there is not. The solution is to have a module created for that purpose. See the last section of this article for more information:
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#need-support-for-other-plugins

If you would like to tackle this yourself, see Example 3 of the Objective API:
https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API#objectives-api
