### ISSUE TITLE
Journal can be moved to other inventories with hotkey

### ISSUE THREAD

**Issue by J0hnL0cke** [PikaMug/Quests#1620]
I was playing around with this plugin on a server, and I noticed this bug. I made a plugin that restricts putting the dragon egg into ender chests and ran into the same bug, so I wanted to share my solution. I made #1619 to fix it, this is just the bug report so you can reproduce the issue.

**What is your Quests version / build number (do _not_ say "latest")?**
Not sure, it was on a server where I am not an admin, but looking at the source code, the bug still appears to be there.

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Quest journals can be put into inventories like chests, ender chests, furnaces, etc. To reproduce, put the journal in any hotbar slot and press the hotkey that goes along with it, while hovering over any item slot in the target inventory. The journal will swap places with the item in the target slot (if any). The current implementation of the InventoryClickEvent only handles the current item being interacted with, evn.getCurrentItem(). It does not consider the possibility of hotkeying, where the current item is the one being hovered over, not the one in the hotbar.

**Comment by PikaMug** [comment]
Thanks for your submission, but creating a separate issue was not necessary. Closing.
