### ISSUE TITLE
1.16.5 Quest 4.0.0 Conditions message

### ISSUE THREAD

**Issue by Wazored** [PikaMug/Quests#1622]
Is there any way to remove conditionFailRetry message?

**Comment by PikaMug** [comment]
Set your quest to fail if the condition is not met.

**Comment by Wazored** [comment]
> Set your quest to fail if the condition is not met.
This would cause the player to abandon the mission. I'm trying to avoid repeating the message "Condition not yet met for this stage of FireWill" every time I perform an action without having the condition weapon in my main hand.
![2021-02-23_15 52 14](https://user-images.githubusercontent.com/79492310/108919040-a397a980-7632-11eb-950b-65f2be84c227.png)

**Comment by Wazored** [comment]
> Set your quest to fail if the condition is not met.


This would cause the player to abandon the mission. I'm trying to avoid repeating the message "Condition not yet met for this stage of FireWill" every time I perform an action without having the condition weapon in my main hand.
![2021-02-23_15 52 14](https://user-images.githubusercontent.com/79492310/108919101-bc07c400-7632-11eb-89c6-ea1b054e8b8a.png)
