### ISSUE TITLE
quests spam chat

### ISSUE THREAD

**Issue by Zalaee** [PikaMug/Quests#1623]
![quests spam chat](https://user-images.githubusercontent.com/79696158/109289564-11a8c000-782f-11eb-9725-638f3bf39ead.jpg)

**Share your question with as much detail as possible?**
Hello, i want to delete a line in lang files so it doesnt pop in chat upon action happening. Problem is even after i delete the line and leave it empty it still pops up as empty lines in chat.
If i leave the spacing without '' '' completely empty it just says NULL in chat instead 
Is there any way to deny it pushing chat messages?

**Comment by PikaMug** [comment]
No, the plugin will still display a blank line.

Consider toggling the Silk Touch under Edit Options -> General
https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Options
