### ISSUE TITLE
Optional Notifier for Conditions

### ISSUE THREAD

**Issue by TyBraniff** [PikaMug/Quests#1624]
**What does your feature do?**
When creating a condition can we have an option whether to notify an individual about that particular condition? This will bypass the chat spam caused by not filling a condition that isn't detrimental. I.e. Leaving a world to do something else while a quest is active. 

**How would people use it?**
[https://camo.githubusercontent.com/23267d859c71ffcb3cd6f4123060c813a2d75817eb8c8a1f535f17c7f4fc2338/68747470733a2f2f692e696d6775722e636f6d2f455379363872492e706e67](url)
Add it as an option when editing conditions:
1 - Set name
2 - Entity
3 - Player
4 - World
5 - Check placeholder
6 - Fail the Quest: No
**7 - Notify if conditions not met: Yes**
8 - Save
9 - Exit

**Comment by TyBraniff** [comment]
Obviously Yes by default and it would function identically as it does now.

**Comment by PikaMug** [comment]
Set your quest to fail if the condition is not met.
