### ISSUE TITLE
Revers Region option

### ISSUE THREAD

**Issue by lucariojb** [PikaMug/Quests#1628]
Hi there,

I would love a feature where yould configure a condition so the player is not allowed to enter a specific region instead of not allowed to leave one.

If this is already possible and I'm just to stupid to find it, please let me know!

Thanks!

**Comment by Beubeux74** [comment]
You can use quests condition
https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Condition-Editor
![image](https://user-images.githubusercontent.com/74351200/113909542-14a4b200-97d8-11eb-8ead-7937e5c92e33.png)

**Comment by PikaMug** [comment]
Thanks for the suggestion. Built-in conditions are designed to be inclusive, not exclusive. However, you might find success with https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#want-support-for-other-plugins-or-features
