### ISSUE TITLE
Delay breaks after leaving the server and rejoining it

### ISSUE THREAD

**Issue by Styssen** [PikaMug/Quests#1629]
(Mostly written in broken english from a german guy, sry in advance ;) )

Hello dear Mr.PikaMug, Ladys and Gentlemen,

I have found myself a Bug in Quests, which I would like to report to you. Please have a look and see if you can find out if myself is just an idiot and doesn´t konw how to use your plugin or if this is not intendet and can be fixed.

At first the ordered Informations:

**What is your Quests version / build number (do _not_ say "latest")?**

Quests 4.0.0-b223

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

A working delay for a stage to finish will break after trying to left and rejoin the server. I´m using it for longer delay, where the error was found.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

https://pastebin.com/buKvF1Fw 

Also down below two pictures, one with working delay and another after the Rejoin

Before:
![2021-03-03_03 01 56](https://user-images.githubusercontent.com/79951576/109741379-37d2b500-7bcd-11eb-9c31-19f677abcb17.png)

After:
![2021-03-03_03 02 19](https://user-images.githubusercontent.com/79951576/109741406-44570d80-7bcd-11eb-9ff6-5e82adbce568.png)

Thank you very much for your help 

Gratefully 
Styssen

**Comment by PikaMug** [comment]
@Styssen Thanks for the report. Fixing this required a significant change to how player data is loaded. Please backup your _/Quests/data_ folder and try the following build:
https://ci.codemc.io/job/PikaMug/job/Quests/226/

**Comment by Styssen** [comment]
Thank you for your help, sir. The Build 226 was problematic at first, but with the following build 227 it worked fine. Thank you for the Help.
