### ISSUE TITLE
maximum radial distance not working

### ISSUE THREAD

**Issue by MikeIceKidd** [PikaMug/Quests#1630]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests Version 4.0.0-b218

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I'm having an issue where when setting the "maximum radial distance" in the options for a quest its causing the quest to be unable to be saved and throws me an error in the console, I don't know why as it was working  a couple days ago when I set up my other quests but now all my quests radial distances have also been defaulted back to zero.

https://pastebin.com/BurXRmLL

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Although the share distance is showing as 100 in the quest on the editor in game it shows zero.
 
https://pastebin.com/x6Pg74Qt

**Comment by PikaMug** [comment]
Thanks for the report. This has already been fixed as of https://github.com/PikaMug/Quests/commit/f7b34dcac02bcbeb9568beba0f6d4cbaa533044f

Use the latest development build at https://ci.codemc.io/job/PikaMug/job/Quests/
