### ISSUE TITLE
Could not pass event InventoryClickEvent to Quests v4.0.0-b223

### ISSUE THREAD

**Issue by SmrdutyOrangutan** [PikaMug/Quests#1631]
**What is your Quests version / build number (do _not_ say "latest")?**
v4.0.0-b223

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Hey guys, me again ( #1626 ). I tried the 223 build of your plugin and while the problem from previous report is gone, our console is under spam-attack of the following error. 

Basically, it started the moment we updated the plugin, we get the error message every few seconds. Originally I thought there is a problem with one of my item-giving events/actions, but even after removing everything and leaving only the default 4 quests and actions, problem persists.  We do not have the visual interface of Quests and everything else is up to date.

https://pastebin.com/mfsG6smu

**Comment by PikaMug** [comment]
Quests uses the InventoryClickEvent for smelting and brewing objectives. Do you have any quests which might apply? Also, check where the spam begins in your server log for any more descriptive errors.

**Comment by SmrdutyOrangutan** [comment]
> Quests uses the InventoryClickEvent for smelting and brewing objectives. Do you have any quests which might apply? Also, check where the spam begins in your server log for any more descriptive errors.

I did have few smelting objectives, but the error showed up even after I removed every custom quest/action. 

Anyway, I believe this is the exact moment when the problem started.
https://pastebin.com/fUfxHaFX

**Comment by PikaMug** [comment]
Problem appears to stem from https://github.com/PikaMug/Quests/pull/1619

Looking into it.

**Comment by PikaMug** [comment]
@SmrdutyOrangutan Give https://ci.codemc.io/job/PikaMug/job/Quests/224/ a try
