### ISSUE TITLE
Mob Spawn in /quests events

### ISSUE THREAD

**Issue by UltimaIsHere** [PikaMug/Quests#1632]
**What does your feature do?**
Tbh, I don't really know if this suggestion should go here. 
But I just wanted to suggest being able to spawn more than 2 types of mobs in more than 2 types of locations in /quests events
I remember being able to do it before while I was teaching myself how to operate the plugin. I would be able to spawn 4 zombies in a location and 4 skeletons in another location, all in 1 stage. I believe this would make things more diverse and not stale.
**How would people use it?**
They would be given the option to add more than 2 locations for "Mob spawn location"
and given the option to spawn more than 2 "Mob types"

**Comment by PikaMug** [comment]
Thanks for the suggestion. Actions (_/quests actions_ or _/quests events_) aren't currently designed to perform more than a single task. In your case, spawning _one_ type of mob. That said, you could opt to execute a spawn command or create a Denizen script to handle the spawning of multiple entities.

I'm not opposed to changing this, however, and will keep the issue open as low priority.
