### ISSUE TITLE
Conversation and Dialogue

### ISSUE THREAD

**Issue by enterih** [PikaMug/Quests#1633]
Hello everyone! This is a Feature, that i missing a lot in die Plugin. Dialogue and Conversation. 

**What does your feature do?**
There should be a Conversation Editor where the player can choose different options. It should be possible, that every end has different effects (for example end the Quest, start an event,  set it so the next stage, give a next Item and brings to the next stage or bring the player back to the beginning of the conversation. Quests creator could create more individual storys and the player could have a better feeling and its more interactive. Imo a must have for a Questplugins. 
A good example to show what i mean and example how to do is  https://www.spigotmc.org/resources/interactions-create-complex-conversations-with-npcs-1-8-1-16.87762/
... or maybe a collaboration with the Pluginauthor instead??

**How would people use it?**
With a editor like conditionseditor, questeditor, eventeditor.

**Comment by PikaMug** [comment]
Thanks for the suggestion. This has been submitted before (#1062) but is outside the scope of the plugin. A module, bridge plugin, or Denizen script would best accomplish this.

**Comment by DeadlykillOfficial** [comment]
It's fully possible to make that possible as custom module.
Infact I have already coded such modules.

**Comment by PikaMug** [comment]
@enterih https://github.com/Browsit/InteractionsQuestsModule
