### ISSUE TITLE
Time condition

### ISSUE THREAD

**Issue by Gornemant** [PikaMug/Quests#1634]
**What does your feature do?**
Add a world time condition, like the world/biome/region but instead a time frame where the condition is met in the 24 hours minecraft day of a specific world.
**How would people use it?**
Create a new world condition where world option is a time of day range of a specific world between two set times. Examples would be night time when monsters spawn between 19:12 and 04:48, sunrise between 05:00 and 05:59, noon between 11:50 and 12:10 and so on. However instead of fixed time options a time range would provide more flexibility.

**Comment by PikaMug** [comment]
Thanks for the suggestion. If I were to do this, it would be during predefined times (selecting "sunrise" or "noon" as opposed to actual time values). Let me know if you find that acceptable and I'll look into it.

**Comment by Gornemant** [comment]
Would also work, though do you think it would be possible to add custom predefined times? I can imagine that there are a lot of possible times when people would like to set a time condition. But what ever works.

**Comment by Beubeux74** [comment]
I think this is a good feature, but can we select a world where the timer is located ? 
But I think it will be better for the player to choose a minecraft tick slot for example
Like the planner:
![image](https://user-images.githubusercontent.com/74351200/110387184-8961c080-8061-11eb-9524-e7b780b10e3e.png)
"**Define the departure time in ticks**
![image](https://user-images.githubusercontent.com/74351200/110387495-f70dec80-8061-11eb-955e-63b2035f6d41.png)

"**Define the end time in ticks**"
![image](https://user-images.githubusercontent.com/74351200/110387252-a0a0ae00-8061-11eb-8a5f-8737cebe6827.png)

Or we can define "**time in ticks**" and "**delay in ticks after starting**"

**Comment by Gornemant** [comment]
> 
> 
> I think this is a good feature, but can we select a world where the timer is located ?
> But I think it will be better for the player to choose a minecraft tick slot for example
> Like the planner:
> ![image](https://user-images.githubusercontent.com/74351200/110387184-8961c080-8061-11eb-9524-e7b780b10e3e.png)
> "**Define the departure time in ticks**
> ![image](https://user-images.githubusercontent.com/74351200/110387495-f70dec80-8061-11eb-955e-63b2035f6d41.png)
> 
> "**Define the end time in ticks**"
> ![image](https://user-images.githubusercontent.com/74351200/110387252-a0a0ae00-8061-11eb-8a5f-8737cebe6827.png)
> 
> Or we can define "**time in ticks**" and "**delay in ticks after starting**"
> 
> Ideally, this would be added as a prerequisite, as well as a step condition
> here (**basic menu**)
> ![image](https://user-images.githubusercontent.com/74351200/110387843-81565080-8062-11eb-8acb-8818121f28ea.png)
> and here if you can (**steps of the quests**)
> ![image](https://user-images.githubusercontent.com/74351200/110387884-916e3000-8062-11eb-9304-aec295eb9da8.png)

The timer should be world based as servers can run different worlds with different times of course, though the problem I see using ticks is, if I understood it correctly, that it doesn't stop at 24000 ticks, but goes well beyond that because of the different moon phases: https://minecraft.gamepedia.com/Daylight_cycle#Moon_phases
You could use that to specify a moon phase, but as a general rule for night, you would need to add all possible night cycles, which would be a bit cumbersome.

**Comment by TheCrazyCreepr** [comment]
> Thanks for the suggestion. If I were to do this, it would be during predefined times (selecting "sunrise" or "noon" as opposed to actual time values).

If you were to do this, you could take a similar approach to how MythicMobs handles its spawn conditions. MythicMobs checks the time (in ticks) to see if a custom mob is capable of spawning based on the time at that moment. It appears in the configuration as follows. While I haven't dug into the code myself, it may be a good way to go about doing this.

![ticktime](https://user-images.githubusercontent.com/63975624/132103747-d596906e-fd06-4927-b1fd-a66b49b31104.PNG)

**Comment by PikaMug** [comment]
Ended up doing ticks as you all recommended. My initial concern was how it would appear in chat, but that can hopefully be rectified with #1957
