### ISSUE TITLE
Quest won't continue beyond Password stage

### ISSUE THREAD

**Issue by SmrdutyOrangutan** [PikaMug/Quests#1635]
**What is your Quests version / build number (do _not_ say "latest")?**
4.00 b224 (and thank you for the bugfix from #1631, it works without errors)

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
No console errors.

I'm setting up a password objective in one of my quests and this is what I did (using in-game quests editor)
Create new quest -> Quest name -> ask message -> finish message -> stages -> add stage ->password -> hint & password -> and then proceed with the rest of the questline.

When I tested it, I got to the password stage, I typed in the password, prompt showed up notifying me about completed objective and then I got stuck without advancing to the next stage. This problem happens with all of my quests if there's a password objective and if I use /questadmin nextstage command, the rest of the quest(s) run smoothly.

I don't have any issues with chat actions (such as default RodStart or few of my custom ones), only the chat objective

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Here is the quest, the problem is in first two stages: https://pastebin.com/bSQXRpLh

**Comment by PikaMug** [comment]
Thanks for the report. Does this still occur if you remove the stage delay?

**Comment by SmrdutyOrangutan** [comment]
> Thanks for the report. Does this still occur if you remove the stage delay?

Delay removed, added, increased, decreased, added delay message, added another objective. No change on the outcome. Still get stuck on this stage.

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/225/

**Comment by PikaMug** [comment]
@nesttle Please create a new ticket with example quest.
