### ISSUE TITLE
Warn console to QuestUpdateCompassEvent

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1636]
What is your Quests version / build number (do _not_ say "latest")? **Quests 4.0.0-b224**
![image](https://user-images.githubusercontent.com/74351200/110539509-a4960400-8125-11eb-9d3a-4f4b5081aa0a.png)

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

When I restart a quest with / questadmin reload I have an error in the chat, and in the console chat I have this.
All my quests are reloaded, I hope.
I'm sure the new quests are working, and I can create and use all quests, as well as quest events.
I don't see any other problem 
> [Tue, 9. Mar 2021 22:19:06 CET INFO] [me -> Beubeux74] 33Les quêtes sont rechargées33
> [Tue, 9. Mar 2021 22:19:06 CET INFO] Loaded language fr-FR. Translations via Crowdin
> [Tue, 9. Mar 2021 22:19:06 CET WARN] java.lang.IllegalStateException: QuestUpdateCompassEvent may only be triggered synchronously.
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at me.blackvein.quests.Quest.updateCompass(Quest.java:396)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at me.blackvein.quests.Quester.checkQuest(Quester.java:3812)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at me.blackvein.quests.Quests$3.run(Quests.java:1539)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [Tue, 9. Mar 2021 22:19:06 CET WARN] at java.lang.Thread.run(Thread.java:748)
> [Tue, 9. Mar 2021 22:19:06 CET INFO] Une erreur c'est produite. Veuillez vérifier la sortie vidéo de la console.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
I convert it to zip
[quests.zip](https://github.com/PikaMug/Quests/files/6111607/quests.zip)

**Comment by PikaMug** [comment]
Thanks for the report. Fixing this required a significant change to how player data is loaded. Please backup your _/Quests/data_ folder and try the following build:
https://ci.codemc.io/job/PikaMug/job/Quests/226/
