### ISSUE TITLE
Add potions effect to player at the end of the quests

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1637]
Quests 4.0.0 -b224
**What does your feature do?**
Add a button to add potions effects to the player as a final reward without going through commands, or a quests events
![image](https://user-images.githubusercontent.com/74351200/110556893-b84e6400-813f-11eb-852f-2e961c8def01.png)

i thinks it's not hard to add, i hope you do it

**Comment by PikaMug** [comment]
Already possible as a Finish Action: https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Action-Editor
