### ISSUE TITLE
Entities Not Recognized In Quests Conditions GUI

### ISSUE THREAD

**Issue by size14pants** [PikaMug/Quests#1640]
**What is your Quests version / build number (do _not_ say "latest")?**
**Version:**4.0.0-rc.4-b191
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When in the /quests conditions gui, you are given the option to create a condition for a player riding an entity. Of the list of entities given, only the animal entities (pig, donkey, etc.) are recognized while all other entities (MinecartCommand, Minecart, etc.) prompt me with a message saying "X is not a valid mob name". Manually entering in the unrecognized entities does not work either and leads to the entire condition being "removed" from ingame. 
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
N/A

**Comment by PikaMug** [comment]
Pretty sure I only accounted for "living" entities. Will look into this.

**Comment by PikaMug** [comment]
@size14pants Try https://ci.codemc.io/job/PikaMug/job/Quests/228/
