### ISSUE TITLE
Quests not allowing the same GUI item to be used in creation of quests

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1641]
**What is your Quests version / build number (do _not_ say "latest")?**

3.9.1-b85 (Can update if needed)

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

No console errors. Just try to assign an identical GUI item display that any other quest is using. It will report "Cannot use this item as GUI display item it is already being used by %NPC Name% for quest %quest name%" into the chat.

I have checked the lang file, cannot find a way to disable/enable this, using the US-EN lang setting.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

I have attached my lang file to show how this is still an issue, I submitted a ticket like this months ago, however was told it had to be a lang file config issue, yet cannot find the setting anywhere.
[strings.zip](https://github.com/PikaMug/Quests/files/6135761/strings.zip)

**Comment by DeadlykillOfficial** [comment]
Support is always given when the bug appears on the latest Quests version. Preferably latest Dev build.

**Comment by Larskei-dev** [comment]
Updated too 4.0.0-b218 issue still persists.

**Comment by PikaMug** [comment]
This is not a bug; the GUI is limited to one material type per NPC by design.
