### ISSUE TITLE
Paper in quests causes quest corruption/failure to reload

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1642]
**What is your Quests version / build number (do _not_ say "latest")?**

3.9.1-b85

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

Surprisingly no errors come up in console for this issue, but if you make a quest that has the GUI item display as paper, delivery of paper to NPC, or essentially any action that involves the item of paper, it will not load the quest at all and in chat says there is a error, but does not send a error to the console.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

The quest will not save to the config so I can't give an example quest.

**Comment by DeadlykillOfficial** [comment]
Support is always given when the bug appears on the latest Quests version. Preferably latest Dev build.

**Comment by Larskei-dev** [comment]
Updated too 4.0.0-b218 issue still persists.

**Comment by PikaMug** [comment]
Try https://ci.codemc.io/job/PikaMug/job/Quests/229/
