### ISSUE TITLE
I can't do use lore anymore

### ISSUE THREAD

**Issue by Threshian** [PikaMug/Quests#1644]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests 4.0.0

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

Since i updated the plugin to the last version (4.0.0) all my lore transform to this <https://i.imgur.com/qufmkxk.png>.
Now I tried to create new quests by doing usually, everything works except using the line "lore" <https://i.imgur.com/C8Olte6.png>.
What i want is to set rewards in the GUI <https://i.imgur.com/KImuWzq.png>.

I don't know if it's me doing something wrong or not.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

New Quests i made : https://pastebin.com/canPxp6W 
Old Quests i made : https://pastebin.com/ey1CfMhK

**Comment by PikaMug** [comment]
The `meta:` tag appears to have been removed from your item. Just copy it over from the old file and it should work fine. Otherwise, add lore to the item in-game as normal.
