### ISSUE TITLE
How Would I Make This Condition?

### ISSUE THREAD

**Issue by size14pants** [PikaMug/Quests#1645]
Hi! I have a server that utilizes the [Vehicles Plugin](https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/). I wanted to make a quest where you needed to be in a vehicle to complete the quest. I figured I could use the conditions editor to make a condition where the player must ride an entity. The problem is, I don't know what entity the vehicles are. I tried every entity and the condition was still not met when I was inside of a vehicle so I think the vehicle entities might be armor stands. My question is, is there any way that I could make a condition for riding these vehicles? Would I be able to do it within the quest plugin or would I need to implement my own custom module/code and if so, how would I do so?

**Comment by PikaMug** [comment]
That condition is for default Minecraft entities only. Setting a `strict-player-movement` value in _config.yml_ will let players complete objectives in your vehicles, as well as without. If you want to necessitate the use of vehicles, you'll want a custom module:
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#want-support-for-other-plugins-or-features
