### ISSUE TITLE
Blocks/Items of the same type progress simultaneously

### ISSUE THREAD

**Issue by SmrdutyOrangutan** [PikaMug/Quests#1646]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0 b225

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

No console errors. Objective is counted simultaneously for more items/blocks of the same ID (only for the **Item** category in Objectives). 

_Stage -> New Stage -> Item  -> one of the five -> Add item -> Load  item from hand/Type the name -> Amount -> Done -> Add Item -> add item of the same ID -> Amount -> Done._

At this moment, players will be asked to create 2 stacks of something, finishing the first stack will automatically complete any following stack.

For example:
- if the objective is to brew 2 awkward potions and then consume then, brewing and drinking only one will do.
- if the player has to smelt 8 stacks of stone (512 pcs) and then craft 8 stacks of stone bricks (512 pcs), 1 stack (64pcs) will complete the quest.
- if I want players to enchant 10 swords, 1 is enough to progress through this stage

**Comment by SmrdutyOrangutan** [comment]
I forgot to mention. I've tried **blocks** objective as well and placing/breaking doesn't have a limit (1-64) like **items** do and I don't have any problems with that. I can simply ask players to break 128 blocks instead of 2x 64 and it works fine.

**Comment by PikaMug** [comment]
This may be limited by how items are saved (using Bukkit implementation which limits ItemStack size to 64) but I'll look into it.

**Comment by SmrdutyOrangutan** [comment]
> This may be limited by how items are saved (using Bukkit implementation which limits ItemStack size to 64) but I'll look into it.

I'm not sure about this. As I said, I used several items with stack limit 1 (tools, weapon, potions) and the problem was present only in "Items objective". Blocks, NPCs, Mobs behave completely fine. The problem is present only in quests that asks the player to use one of the crafting blocks (such as crafting table, enchanting table, brewing stand, furnace and possibly all the other).

I've just double checked the NPC - item delivery option. It works as expected, maybe the answer is in the coding of NPC? :-D

Anyway, if you need anything from me, let me know. I'll be more than happy to help to fix it. I didn't figure out any workaround for this problem yet... :(

**Comment by PikaMug** [comment]
@SmrdutyOrangutan Sorry for the delayed response. The issue stems from how item objective progress is stored and iterated. I've corrected the Consume items objective, but ask that you please test it thoroughly before I update the others. Simply download and install the following development build after backing up your _plugins/Quests/_ directory. Awaiting your response.

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/241/
