### ISSUE TITLE
Do not change the Stage by NPC kill

### ISSUE THREAD

**Issue by oneboyreal** [PikaMug/Quests#1647]
Hello,

i have the problem, that the Stage will not change if the npc is killed. Bevor a week all works fine and now it is so bad :(

The problem affects all quests where the goal of a stage is to kill an npc. In the chat it says that it is finished but the stage is not changed.

**Comment by oneboyreal** [comment]
[quests.txt](https://github.com/PikaMug/Quests/files/6153365/quests.txt)
Quest "Jonas der lästige", "Ein Fischerdorf in Nöten" and some more

**Comment by PikaMug** [comment]
@oneboyreal Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/231/
