### ISSUE TITLE
Error on player join to the server

### ISSUE THREAD

**Issue by steveq7** [PikaMug/Quests#1648]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.1
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Join player to the server

https://pastebin.com/TLDEjiNL
![image](https://user-images.githubusercontent.com/75625135/111477516-7b7e0080-872f-11eb-8d41-50f24bb50a13.png)

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/eNMiUgne

**My plugins:**
![image](https://user-images.githubusercontent.com/75625135/111477639-9cdeec80-872f-11eb-8508-5605f996bb2f.png)

**Comment by PikaMug** [comment]
Already resolved in 09cf625a8aac9401651cc6470124d12c62dd1ab7

Use latest dev build https://ci.codemc.io/job/PikaMug/job/Quests/
