### ISSUE TITLE
keep getting this warning on a clean installation

### ISSUE THREAD

**Issue by iielijah** [PikaMug/Quests#1649]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests 4.0.1 (Non-dev build)

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

>.... [14:07:52 WARN]: java.lang.NullPointerException
>.... [14:07:52 WARN]: at me.blackvein.quests.listeners.PlayerListener$3.run(PlayerListener.java:853)
>.... [14:07:52 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [14:07:52 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [14:07:52 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [14:07:52 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>.... [14:07:52 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>.... [14:07:52 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by steveq7** [comment]
#1648

**Comment by steveq7** [comment]
#1648

**Comment by DeadlykillOfficial** [comment]
Me looking into the code of Quests it seems like Quester from Storage is null. This could happen either because player joins the server for first time or eventually Pika has changed something in regard #1589. I'm sure once Pika see it, it will be fixed quick enough.

**Comment by PikaMug** [comment]
Already resolved in 09cf625a8aac9401651cc6470124d12c62dd1ab7

Use latest dev build https://ci.codemc.io/job/PikaMug/job/Quests/
