### ISSUE TITLE
Getting spammed with error, might have issues with another plugin that changes enchantments

### ISSUE THREAD

**Issue by OliverJaas** [PikaMug/Quests#1654]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests v4.0.0-b218

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

No idea, getting spammed with console errors, I believe that the Enchantment Solution plugin is messing with the Quests.

https://pastebin.com/dzPHXNfD
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

I don't have any quests related to enchanting ect

**Comment by PikaMug** [comment]
Thanks for the report. Please confirm whether this still occurs on the latest development build (and if so, post the new error from that version): https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by OliverJaas** [comment]
https://pastebin.com/hGMMEb91

Found out that it happens when you use the enchantment table (possibly still an error due to Enchantment Solution plugin)
It uses a custom GUI enchantment table with custom enchantments

**Comment by PikaMug** [comment]
It appears the developer has no intention of reviewing pull requests. I'm afraid all you can do is comment on https://github.com/crashtheparty/EnchantmentSolution/pull/124 requesting that they take a look.
