### ISSUE TITLE
Can't save edited quests

### ISSUE THREAD

**Issue by LordyZa** [PikaMug/Quests#1657]
Version: Quests 4.0.1 (Naughty Update)

Problem: Basically, cannot save edited quests, I can create quests but when trying to edit, the plugin doesn't let me press "yes" when saving. Also, this pops up in console when I press it: https://pastebin.com/4AGR2YWH

It affects EVERY quest.

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/232/

**Comment by LordyZa** [comment]
> Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/232/

Worked, thank you so much
