### ISSUE TITLE
My Console is getting spammed and im getting this "An unknown error occurred. see console output."

### ISSUE THREAD

**Issue by CanadianKareem** [PikaMug/Quests#1658]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.1

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
An unknown error occurred. see console output.
https://pastebin.com/GLHpNNKF
https://pastebin.com/DgweZ2HC
https://pastebin.com/6feVe8B2

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/EKs0ZE2R

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/233/

**Comment by CanadianKareem** [comment]
i can't find the download link

**Comment by PikaMug** [comment]
@CanadianKareem It's "Quests-4.0.1.jar"
