### ISSUE TITLE
Negative time delays for quests

### ISSUE THREAD

**Issue by ProtoX37** [PikaMug/Quests#1659]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.1
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Random stages of quests are delayed -1 seconds, causing the quest to get permanently stuck. The delay for these stages are actually set at a positive number (i.e. 1, 2 3 seconds).

When reaching the stage that causes the negative delay the console spits out:
_[Wed, 24. Mar 2021 20:27:52 GMT WARN] Task #1147572 for Quests v4.0.1-b233 generated an exception_

When quitting the quest it spits out
_[Wed, 24. Mar 2021 20:28:43 GMT INFO] prototypeX37B issued server command: /quests quit Ship Rigging
[Wed, 24. Mar 2021 20:28:43 GMT INFO] b94bfded-99d5-45df-9d57-eff740af8992 quit quest Ship Rigging_

When using /questadmin reload the console reads
_[Wed, 24. Mar 2021 20:30:07 GMT INFO] prototypeX37B issued server command: /questadmin reload
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Loaded language en-US. Translations via Crowdin
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Loaded Module: Kill MythicMobs Objective by BerndiVader
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Registered events for custom objective "Kill MythicMobs Objective"
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Loaded Module: MythicMobs Item Require by BerndiVader, idea Wahrheit
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Loaded Module: MythicMobs Item Reward by BerndiVader
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Loaded Module: MythicMobs Conditions Require by BerndiVader, idea Wahrheit
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Loaded Module: MythicItem NPC Deliver Objective by BerndiVader, idea Wahrheit
[Wed, 24. Mar 2021 20:30:07 GMT ERROR] Plugin Quests v4.0.1-b233 has failed to register events for class com.gmail.berndivader.mythicmobsquests.MythicItemDeliverObjective because net/citizensnpcs/api/event/NPCRightClickEvent does not exist.
[Wed, 24. Mar 2021 20:30:07 GMT INFO] Registered events for custom objective "MythicItem NPC Deliver Objective"_

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by Gornemant** [comment]
Note: we reverted back from build #233 to build #230 and that fixed the issue with the negative delays.

**Comment by PikaMug** [comment]
Thanks for the report. Would need to see an example quest for testing.

>**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by Gornemant** [comment]
> 
> 
> Thanks for the report. Would need to see an example quest for testing.
> 
> > **If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

Sure, that's one of the easier quests where it was confirmed to go into negatives.
https://pastebin.com/5D6A4Cpp
We got a few other ones confirmed but probably better to get the simplest one.

**Comment by PikaMug** [comment]
I was unable to replicate the "delayed -1 seconds" issue, but I did run into #1662 which is now fixed. Hoping this will inadvertently resolve your issue as well:
https://ci.codemc.io/job/PikaMug/job/Quests/234/
