### ISSUE TITLE
questadmin reload breaks

### ISSUE THREAD

**Issue by MisterCookie1234** [PikaMug/Quests#1660]
**Quests 4.0.1**

Hey.
My Questadmin reload always breaks... 
it tells me to look into the console

`[21:08:47 WARN]: java.lang.IllegalArgumentException: Cannot create section at empty path [21:08:47 WARN]: at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) [21:08:47 WARN]: at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:269) [21:08:47 WARN]: at org.bukkit.configuration.MemorySection.createSection(MemorySection.java:296) [21:08:47 WARN]: at me.blackvein.quests.Quester.getBaseData(Quester.java:2895) [21:08:47 WARN]: at me.blackvein.quests.Quester.saveData(Quester.java:2826) [21:08:47 WARN]: at me.blackvein.quests.Quests$3.run(Quests.java:1240) [21:08:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) [21:08:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [21:08:47 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [21:08:47 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [21:08:47 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [21:08:47 WARN]: at java.lang.Thread.run(Thread.java:748)`

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

No Quests get saved in the quests.yml

**Comment by DeadlykillOfficial** [comment]
Invalid format of Github ticket report.

**Comment by PikaMug** [comment]
Sounds like a formatting problem. Try running your _quests.yml_ through a YAML parser like [this one](https://yaml-online-parser.appspot.com/) (not affiliated) and fix the issues.

Also, update to the latest [development build](https://ci.codemc.io/job/PikaMug/job/Quests/). If you still have the issue, respond here with the new error.
