### ISSUE TITLE
Unknown Issue, Says Custom Objective Is Null... I have not made a custom objective before?

### ISSUE THREAD

**Issue by Grallow** [PikaMug/Quests#1661]
Hello. I get this error when my quest loads, in the console.

28.03 00:17:05 [Server] WARN [Quests] Unable to load custom objectives because quest for custom41 was null

I've asked on the discord and had a moderator look into it for me but we can't find the issue. Here is the code for the quest. There is another quest that also has this error and idk what's causing it. Help?

Here is the code for custom41

https://pastebin.com/TLTC8PBf

**Comment by PikaMug** [comment]
Thanks for the report. Which modules do you have installed (in the _/modules_ folder)?

**Comment by PikaMug** [comment]
Please try the latest development build and report back if the issue persists:
https://ci.codemc.io/job/PikaMug/job/Quests/234/

**Comment by call911nowplz** [comment]
Same thing here, I am getting 
https://pastebin.com/bMTRgCpu

I am also using the development buid. Same issue!

Custom modules i am using are MythicMobs quests addon. just upgraded it from the official repository but that does not fix the issue

**Comment by PikaMug** [comment]
@call911nowplz Please create a separate issue as that's a different error. Thanks!
