### ISSUE TITLE
Could not pass event NPCRightClickEvent to Quests v4.0.1-b233 java.lang.IllegalStateException: QuesterPreCompleteQuestEvent may only be triggered asynchronously

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1662]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests v4.0.1-b233

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
cannot right click NPC, when clicked, this error shows 
This problem does not occur when i was using b230 version

https://paste.gg/p/anonymous/53c5abec20a7481d94019215ced3d3c1
![image](https://user-images.githubusercontent.com/61608872/112777004-a17e9b80-9073-11eb-8122-f73d4b045913.png)

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

https://paste.gg/p/anonymous/da22036804ef49178f3844da213b6487

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/234/
