### ISSUE TITLE
Initial Action

### ISSUE THREAD

**Issue by HMRFlame** [PikaMug/Quests#1663]
**Where else have you looked for answers to this question?** google, reddit

**Share your question with as much detail as possible?** I create a quest and name it, I then go into the editor but there is no option for Intinal Action. i can not set one. is there a way to fix this?

**Comment by PikaMug** [comment]
Initial Action was removed for redundancy. Use a Start Action instead (Edit Stages -> set an objective -> Actions).

**Comment by HMRFlame** [comment]
The only custom onjective i have is Kill mobs?

**Comment by HMRFlame** [comment]
I want the message to appear before you accept or decline the quest. Is that possible still?
