### ISSUE TITLE
Plugin has seemingly bricked, quests do not advance, can't reload the plugin.

### ISSUE THREAD

**Issue by Minerboybp** [PikaMug/Quests#1665]
**What is your Quests version / build number (do not say "latest")?**
4.0.1-b230
**Describe the problem and how to replicate it. Any console errors to post _using_ a pastebin?**
I logged on the server to edit a quest, I edited said quest, and when I attempted to reload I was met with "An unknown error occurred. See console output." I don't really know how to replicate this, all I did was edit a quest and use /qa reload. The quest had a blank stage in it before I edited it, if that's of any revelation.
Quest:
https://pastebin.com/rZg0EHPN
Here's the errors it gave on startup.
https://pastebin.com/6u3Ne2Yj

**Comment by DeadlykillOfficial** [comment]
Your post is firstly invalid. Please use the template

**Comment by PikaMug** [comment]
@Minerboybp Something is wrong with the stages of one of your quests. Could be an administrator deleted a stage that a player was currently taking or had previously taken. This development build will not fix this issue, but will inform the console of which quest is the problem one next time it occurs: https://ci.codemc.io/job/PikaMug/job/Quests/235/
