### ISSUE TITLE
Action - Mobs - Not spawning with items

### ISSUE THREAD

**Issue by MsRusha** [PikaMug/Quests#1666]
What is your Quests version / build number (do not say "latest")?
Quests-4.0.1-b233

Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?
No console error

I am editing an action where i need to spawn mobs. Everything works fine, they spawn where they are supposed to. But the things i put on them (hand and full armor) wont work. they wont spawn with the items, i even tried to put on droprate, still wont spawn with the stuff.

- In the picture ive put on SET ITEM IN HAND but it wont show. it will not spawn with it either
![quests](https://user-images.githubusercontent.com/79415189/113507211-6d125000-9549-11eb-99ca-dd76d53c8060.PNG)

- and on a another quest they do spawn with the stuff. but this quest is a 2 weeks old.
![quest1](https://user-images.githubusercontent.com/79415189/113507288-cbd7c980-9549-11eb-82f4-9adb2cf1ebdc.PNG)

**Comment by DeadlykillOfficial** [comment]
You should edit your post to fulfill required data using the Template provided otherwise your post would be invalid and no action would be taken for it

**Comment by MsRusha** [comment]
and?

**Comment by PikaMug** [comment]
Please note that while the next release of Quests will contain this fix, I fully intend to overhaul this to support more complex items in the not-so-distant future.
