### ISSUE TITLE
Quests stage resets

### ISSUE THREAD

**Issue by Xverion** [PikaMug/Quests#1667]
Version 4.0.1.

We've been testing our server and if people are in the middle of a quest and leave the server and it then restarts it seem that it also resets their quest progress. There is no issue in the console. This happens to all our quests.

**Comment by DeadlykillOfficial** [comment]
This is because you are most likely using MySQL and it's not a bug but a normal behaviour. At the moment MySQL does not save player progress only player current stage.

**Comment by Xverion** [comment]
My apologies. Will do next time. So switching back to flatfile should fix the problem?

**Comment by DeadlykillOfficial** [comment]
Switching will fix the problem yes. At least till MySQL is full capable of saving all data including quests and etc. 
As for now this is known Limitation of Quests MySQL options.

**Comment by Xverion** [comment]
Thank you very much. I'll keep an eye on the updates and see when it's working fully for now yml it is.
