### ISSUE TITLE
Give npc id, when i click on npc 

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1668]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.1-b230 + Quests gui Version 0.26 (Language French)
![image](https://user-images.githubusercontent.com/74351200/113557199-ee2b1f00-95fd-11eb-85fe-069bbe3b703e.png)

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
No error in the console.
When i edit a quests, and i miss click to choice a function, and i click on "Talk to npc" or "First npc (starting)", and i write cancel. And i no edit another function " npc " when i click to the npc to take a quests, he say me her id.
![image](https://user-images.githubusercontent.com/74351200/113557173-e1a6c680-95fd-11eb-9de2-1060f45239f7.png)

To soluce this i do create/edit a quests and write npc id in the objective

**Comment by PikaMug** [comment]
You cannot take a quest while using the editor's NPC selector. Exit that part of the editor before taking quests.

**Comment by Beubeux74** [comment]
> You cannot take a quest while using the editor's NPC selector. Exit that part of the editor before taking quests.
Sorry I misspoke,
I meant, when we edit an action talk to an npc, and cancel this action with the word "cancel", and save the quest.
When we talk to any npc (to start a quest) he does not talk to us, but gives us his id
I think that writing cancel brings us back to the menu without closing the id request loop.

**Comment by PikaMug** [comment]
@Beubeux74 Thanks for the clarification. Please try https://ci.codemc.io/job/PikaMug/job/Quests/236/

**Comment by Beubeux74** [comment]
> @Beubeux74 Thanks for the clarification. Please try https://ci.codemc.io/job/PikaMug/job/Quests/236/
Nice the problem has been corrected

**Comment by Beubeux74** [comment]
> @Beubeux74 Thanks for the clarification. Please try https://ci.codemc.io/job/PikaMug/job/Quests/236/
I Have a warn when i reload my quests, can you help me ?
https://pastebin.com/PHV221i2
