### ISSUE TITLE
English wiki translation (french)

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1669]
**What does your feature do?**
**In the first page of the wiki, at the height of the page, we can select another language.**
![image](https://user-images.githubusercontent.com/74351200/113844808-2ca71200-9795-11eb-8ef9-dc9394989978.png)

**In French for example, people translate the page.
And the permission, for example, is also translated.**
![image](https://user-images.githubusercontent.com/74351200/113846649-fff3fa00-9796-11eb-82e2-dc2bbacaac29.png)

**Your plugin is probably the best (like "beton-quests" but it's too difficult to use), and a lot of people use it.
So I can do the translation in French (with screenshots) if you want.**
![image](https://user-images.githubusercontent.com/74351200/113846763-1ac66e80-9797-11eb-8ace-6bc96a82100b.png)

**And another suggestion while we talk about the wiki,
I haven't seen your "quests-gui" and "dynmap-quests" projects in the plugins** 
_https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Dependencies_

**Comment by PikaMug** [comment]
Thanks for the suggestion. I would very much like to have a wiki in multiple languages, but Github does not support this to my knowledge. You would have to suggest an alternative free wiki host, preferably one with crowdsource integration.

As for QuestsGUI and Dymap-Quests, they are listed in https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Bridge-Plugins

**Comment by Beubeux74** [comment]
> Merci pour la suggestion. Je voudrais beaucoup avoir un wiki en plusieurs langues, mais Github ne supporte pas cela à ma connaissance. Vous auriez à suggérer un hôte wiki gratuit alternatif, de préférence celui avec l’intégration crowdsource.
> 
> Quant à QuestsGUI et Dymap-Quests, ils sont [répertoriés dans https://github.com/PikaMug/Quests/wiki/Casual%E2%80%90-Bridge-Plugins](https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Bridge-Plugins)

![image](https://user-images.githubusercontent.com/74351200/113909190-b24bb180-97d7-11eb-87b6-410d8dbee8bf.png)

I found this, there are multiple language

https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Setting-up

**Comment by Beubeux74** [comment]
I missclick sorry i won't close it x)

**Comment by PikaMug** [comment]
Sorry for the late reply. That project's wiki is impressive, but I'm unsure of how they setup and manage user submissions. I'll try to locate or request a guide at some point.

**Comment by PikaMug** [comment]
I've opted to go with Gitbook, which you can view at https://pikamug.gitbook.io/quests/

Translations may be submitted via pull request at https://github.com/PikaMug/QuestsDoc

**Comment by Beubeux74** [comment]
I have started, would it be possible to publish them so that I can see the ones that are already finished. I think I do about 3-5 pages per week. 
![image](https://user-images.githubusercontent.com/74351200/143663097-4a0be33b-542b-4e87-8904-93c80623117e.png)

**Comment by PikaMug** [comment]
@Beubeux74 Sure, just submit the Pull Request at https://github.com/PikaMug/QuestsDoc/pulls

Let me know if you have any questions.
