### ISSUE TITLE
Whats is "quests conditions" ?

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1670]
**Where else have you looked for answers to this question?**
In the issues with the key word "quests condition" label questions, on google (search, picture)

**Share your question with as much detail as possible?**
![image](https://user-images.githubusercontent.com/74351200/113847832-25353800-9798-11eb-9cbf-553c417e633b.png)
I'm just looking at the commands we can use to do a quest, and I found "quest conditions" and in the description it says "create, modify or delete conditions", what can this command do?

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Condition-Editor
