### ISSUE TITLE
Quest stuck on Complete

### ISSUE THREAD

**Issue by Vanheden** [PikaMug/Quests#1672]
**What is your Quests version / build number (do _not_ say "latest")?** 4.0.1-b236

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?** No errors at all. It gets stuck upon completion such as 5/5 and I get no reward tried with Mining Block quest and Killing Zombie/Skeleton/Creeper Quest. When I recieve the correct amount of what I need to complete the quest it says the quest is done but get stuck at default Stage and no reward is pointed out.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?** https://pastebin.com/382u0A2t

**Comment by PikaMug** [comment]
I didn't see a quest named "Mining Block" but your Killing Zombie quest works fine. Note that you have a stage delay of 43200 set, so you'll have to wait 720 minutes before rewards are issued.
