### ISSUE TITLE
Small details but which disturbs

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1673]
**What does your feature do?**
![image](https://user-images.githubusercontent.com/74351200/113880098-773b8500-97bb-11eb-8625-6c5436b1011b.png)
I have some details that would make the difference in a next update, like here, the **] ->** or **] :** is not the same color as the 1st.
And as we can see it does not take into account the previous color
![image](https://user-images.githubusercontent.com/74351200/113881661-e9f93000-97bc-11eb-937f-7e76dd4961cb.png)

This appears during a message from / npc text
And when ordering / npc speak

I saw other small details but I remember which ones, I will let them know as soon as I see them

**Comment by PikaMug** [comment]
Those messages are from Citizens; not Quests. Seek help from the developers of Citizens.
