### ISSUE TITLE
Error: All required lists must have the same number of entries!

### ISSUE THREAD

**Issue by Jaminb2030** [PikaMug/Quests#1674]
![Screenshot_309](https://user-images.githubusercontent.com/1007069/113988071-0f1d8b00-981d-11eb-94af-7f98ea43de27.png)

Getting this when trying to setup a quest to the same NPC. Could not find a discord where i could ask so posting here.

**Comment by DeadlykillOfficial** [comment]
"All required lists must have the same number of entries"
List 1 has 2 Entries
List 2 has 1 Entry
list 3 has 4 Entries

They all need to be either 2:2:2 or 4:4:4 or 1:1:1 or 3:3:3.
Always same number of entries.

**Comment by Jaminb2030** [comment]
Ok, I got it to work with 2 stages, since you can only set 1 NPC im guessing you can only do 1 item at a time, perhaps something for a future update.

**Comment by DeadlykillOfficial** [comment]
@Jaminb2030 You have to read messages more carefully. It does allow you to set unlimited amount of NPCs you just have to check for the separator.

**Comment by PikaMug** [comment]
@DeadlykillOfficial This ticket is closed.
