### ISSUE TITLE
Normal players can't start a quest using block (blocks-start)

### ISSUE THREAD

**Issue by lipemo** [PikaMug/Quests#1675]
**What is your Quests version / build number (do _not_ say "latest")?**
v4.0.2-b237

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I did a fresh install, I gave players all necessary permissions, I created a new quest using chat commands and setup a start block to the quest. I did not setup any NPC nor requirements. The message to accept the quest on chat only appear for op! It doesn't work with normal players.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
[quests.yml](https://pastebin.com/8K5znSvD)

**Comment by PikaMug** [comment]
Thanks for the report, but your quest works fine for me. Make sure that you don't have another plugin cancelling the click event (such as region protection).

**Comment by lipemo** [comment]
Hey, I discovered the problem, It is spawn-protection in server.proprieties. It was setup with 16 and I changed to 0.
I defined the player world spawn inside the region! So the region was overlapping with the world spawn conflicting with vanilla spawn-protection. When this happens only op can do things in the region. I have just disabled Spawn Protection and it worked!
There is no bug.
