### ISSUE TITLE
how the remove this annoying silk touch error spam?

### ISSUE THREAD

**Issue by StilesClover** [PikaMug/Quests#1676]
**Where else have you looked for answers to this question?** 
Google and on spigotmc

**Share your question with as much detail as possible?**
Well, it makes sense that a mine quest can't be done with silk touch but if a user like me is using only silk touch it's more than annoying to have my chat spammed with this error message -.- So how can we remove this message? If we can't then pls add a function for it because it's more than annoying

**Comment by PikaMug** [comment]
Quests Editor -> Edit Options -> General -> Ignore blocks broken with Silk Touch

**Comment by StilesClover** [comment]
Well that makes sense but with that, you can break a block and place it again.... that would kill the entire idea for a quest :/ It would be great if there would be an option to just stop the message from showing up.
