### ISSUE TITLE
Error spamming on mob kills

### ISSUE THREAD

**Issue by call911nowplz** [PikaMug/Quests#1677]
Version 4.0.1

Error: https://pastebin.com/JBfR7hAm

Quests: https://pastebin.com/1RRM99zr

Error did not happen before i updated my modules and quests plugin to 4.x
Happens whenever a player kills a zombie from MythicMobs

**Comment by PikaMug** [comment]
> Version 4.0.1

Thanks for the report. You are using a different version than reported (error shows 4.0.0) but the latest version is 4.0.2 anyway. Feel free to create a new ticket once you've generated an error on the new update.
