### ISSUE TITLE
Quests 4.0.2 spams console with errors

### ISSUE THREAD

**Issue by call911nowplz** [PikaMug/Quests#1678]
Version: Quests 4.0.2

https://pastebin.com/fSe8xKMU 
I was told to update to latest Quests version to fix my previous issue. But updating to latest version spams my console with the following errors. I cannot reset my quests due to having over 1k active players doing them as the main part of my gameplay

https://pastebin.com/1RRM99zr
This is my quests file!

**Comment by PikaMug** [comment]
Thanks for the report. If your players are not experiencing issues, these warnings could be ignored.

Based on your file's material names, it appears you're using Minecraft 1.12 or below. If this is not the case, please update the names in accordance with https://bit.ly/2BkBNNN

You may also wish to check that the NPC IDs for affected quests are valid. For example, the "Auction House" quest references an NPC of ID 68. If this NPC does not exist, adjust the ID accordingly.

**Comment by call911nowplz** [comment]
I have confirmed that all the block names are are correct, And the NPCs are all there. 
It's spamming 

> [22:15:25 WARN]: [Quests] Current stage was null when getting objectives for Jurastic Quests

The Jurastic Quests is to talk to an NPC with the ID of 165, Which i just checked exists, And kill Spiders and Skeletons. With a finsh event that also exists. 

The error only appeared after 4.0.0-rc.3, But i had to update to receive support

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/238/
