### ISSUE TITLE
Re-log will complete current stage of a quest.

### ISSUE THREAD

**Issue by SmrdutyOrangutan** [PikaMug/Quests#1679]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.2-b237

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Accept a quest -> log out -> wait for a while -> log in. Quests will force the next stage.
It's not consistent for me, it happened only few times, but some players experience it all the time.

Error, not sure if related:
https://pastebin.com/A0sD5M4v

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Few quests:
https://pastebin.com/K4YaE2F7
https://pastebin.com/F9hH01Uu
https://pastebin.com/p3RwAkPt

**Comment by DeadlykillOfficial** [comment]
This is because all your stages have delay on them. It auto completes it. Remove delay and it will work

**Comment by SmrdutyOrangutan** [comment]
> This is because all your stages have delay on them. It auto completes it. Remove delay and it will work

It actually worked. Thank you.

**Comment by PikaMug** [comment]
The (unrelated) error should be resolved by ebda39975e32971d93095bd6823965f6c3612a2a
