### ISSUE TITLE
Weekly quests and cooldown override

### ISSUE THREAD

**Issue by SmrdutyOrangutan** [PikaMug/Quests#1680]
**Where else have you looked for answers to this question?**
Discord, here

**Share your question with as much detail as possible?**

I would love to create rotation of daily quests. So far I have 2 questlines (7 quests each), first quest starts on monday and lasts until sunday. Seventh quest (the last one) starts on sunday 0:00 and ends at 23:59:59. Rinse and repeat.

The idea was, that once you finish a quest, you won't be able to take it again until it's available. Both cooldown and repeat cycle are set on 604800 seconds (7 days) and cooldown override is set to true.

Planner settings from one weekly rotation:
https://pastebin.com/dUq78vGc

And here is my problem... The quests are not available again, it's almost like override doesn't work. Some players have to wait even 6 days for quests. Is there something wrong with my settings?

**Comment by PikaMug** [comment]
Thanks for your query. If you set a repeat cycle of 7 days, the quest won't be available again until those 7 days have elapsed (and then pending any cooldowns, unless override is enabled), making it a weekly quest; not a daily one. If you want to create daily quests, see the example at https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner#daily-quest

**Comment by SmrdutyOrangutan** [comment]
> Thanks for your query. If you set a repeat cycle of 7 days, the quest won't be available again until those 7 days have elapsed (and then pending any cooldowns, unless override is enabled), making it a weekly quest; not a daily one. If you want to create daily quests, see the example at https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner#daily-quest

I'm sorry, I didn't express myself properly. I don't have 7 daily quests a week. I have 7 weekly quests, as you can see in attached sample.

My intention was to create:
Quest 1
Quest 1
Quest 1
Quest 1

**Comment by SmrdutyOrangutan** [comment]
> Thanks for your query. If you set a repeat cycle of 7 days, the quest won't be available again until those 7 days have elapsed (and then pending any cooldowns, unless override is enabled), making it a weekly quest; not a daily one. If you want to create daily quests, see the example at https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner#daily-quest

I'm sorry, I didn't express myself correctly in the first place. I don't have 7 daily quests, I have 7 weekly quests that "act" as daily ones.

Quest 1: Active from monday to sunday.
Quest 2: Active from tuesday to sunday.
Quest 3: Active from wednesday to sunday
Quest 4: Active from thursday to sunday
Quest 5: Active from friday to sunday
Quest 6: Active from saturday to sunday
Quest 7: Active on sunday

I've set the repeat cycle and cooldown for each of these to 7 days and override to true.

I was under the impression, that players will be able to accept all active quests if override is set on true, but that is not the case. They still have to wait for their cooldown.

**Comment by PikaMug** [comment]
I'm still not entirely sure what you're trying to accomplish, but try setting a repeat cycle of 1 day (86400 seconds). If that doesn't give satisfactory results, try asking around the community Discord at https://discord.com/invite/QdJAv2G7qg
