### ISSUE TITLE
Quests Became Bugged, Won't Load in List

### ISSUE THREAD

**Issue by Foxersthe** [PikaMug/Quests#1681]
**What is your Quests version / build number (do _not_ say "latest")?**

4.0.2.

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

The quests I tried worked, but after setting a quest requirement and trying them out later the first quest disappeared from the quest list. I tried to check on the other quests but they disappeared as well. It's still in the quests.yml, but the errors suggest something is wrong with it. I found an error for the lang files and I did as it said which was to regenerate the string file. I also updated the plugin from a previous version but I can't remember what exactly it was. I think it was rather recent though according to the version number. Only the most recently made quests are affected, though I didn't mess with the older quests yet.
`https://pastebin.com/cLNsyHU8`

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

`https://pastebin.com/fTAjUaNd`

**Comment by PikaMug** [comment]
Thanks for the report. Do you have any [modules](https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules) installed (even if they're not in use)?

**Comment by Foxersthe** [comment]
I have Heroes and DungeonsXL modules installed with it.

**Comment by PikaMug** [comment]
I'm not aware of a Heroes module. Could you provide a link to their resource page?

**Comment by Foxersthe** [comment]
Ah, sorry. I must have meant the mcmmo module addon.
I have that installed, but I removed mcmmo from the server.

**Comment by Foxersthe** [comment]
I just found it simpler to just remake the quests. I plan to have the quests tested today, sorry.

**Comment by PikaMug** [comment]
Sorry for the delayed response.

The quests you provided all seem to have invalid messages. For example...

```
start-message: Okay, listen. Use what we have available here to brew some
            regular Potions of Speed. We need 6 of them.
```

...should be...

`start-message: Okay, listen. Use what we have available here to brew some regular Potions of Speed. We need 6 of them.`

A new line was created where there shouldn't be, which I can only assume was from manual editing of the file.
