### ISSUE TITLE
Cannot set date in planner (start/end)

### ISSUE THREAD

**Issue by HauserGrim** [PikaMug/Quests#1682]
Just try save start/end date and see warn
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.2-b237 and latest commit build
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
https://pastebin.com/MWHTbrCK
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
any quest

**Comment by PikaMug** [comment]
Error shows different version than reported.

**Comment by HauserGrim** [comment]
I wrote about the versions I tested. 
4.0.2
https://pastebin.com/m189NsFY
compilied
https://pastebin.com/htwxrp07

**Comment by HauserGrim** [comment]
This is probably due to time zones.
By choosing random time zones, sometimes it was possible to select, but it was successfully saved only once.
https://pastebin.com/Fvdv2XnU
Also, they display strangely.
![image](https://user-images.githubusercontent.com/37507220/115019380-d12a0200-9ec1-11eb-92da-32d62abfb055.png)

**Comment by PikaMug** [comment]
It seems to be caused by an invalid ISO code for the `language:` setting of the _config.yml_ file. Specifically, either the country or dash is missing (i.e. "fr-FR" not just "fr"). I'll try to compensate for this, but the setting ought to be corrected.
