### ISSUE TITLE
Planner: Cooldown override doesn't work

### ISSUE THREAD

**Issue by SmrdutyOrangutan** [PikaMug/Quests#1683]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.2-b237
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

For reference, this is planner settings of one of my weekly quest.
Start: 5/4/21, 00:00:00
End: 11/4/21, 23:59:59
Repeat Cycle: 604800 seconds
Cooldown: 604800 second
Override: True

After finishing the quest for the first time, a player should be able to take the quest again on monday, 12/4/21, ignoring the cooldown (override: true). That is not the case.

I have many players that finished the quest on saturday, 10/4/21 and now have to wait until tomorrow 17/4/21 (= 7 days, the whole cooldown period).

Moving on to daily quests and some testing, the first quest was working as intended, because both cooldown and availability of the quest didn't overlap. Its settings are:
Start: 12/4/21, 09:00:00
End: 12/4/21, 21:00:00
Repeat Cycle: 86400 seconds
Cooldown: 43200 second
Override: True

After that, I increased the cooldown to 15 hours, just for the purpose of the test. Settings:
Start: 12/4/21, 09:00:00
End: 12/4/21, 21:00:00
Repeat Cycle: 86400 seconds
Cooldown: 54000 second
Override: True

If I finish the second quest at 21:00, I have to wait 15 hours (54000 seconds) to take the quest again. Instead of expected 9:00, I can take the quest again at 12:00...

Judging by a description of the override function on the [wiki](https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner), I believe that is not intended behavior.

Quote from the tutorial:
_> If you want players to be able to take the quest at 9:00 AM the next day regardless of whether their cooldown has expired, you may set the ignore cooldown after repeat override to true._

No error messages.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

Planner settings of 14 affected weekly quests: https://pastebin.com/uN4DnT1L
Planner settings of test daily quests: https://pastebin.com/gs9DQ70E

And 7 quests, full settings: https://pastebin.com/m6G1NDjx

**Comment by Maie13** [comment]
I'm glad I found this report linked in the discord. I saw the same issue trying to set up a weekly quest and couldn't figure out what I was doing wrong.

**Comment by PikaMug** [comment]
Thanks for the report. Do you get a particular message during the period where you should be able to take the quest despite cooldown? If so, a screenshot would be helpful.

**Comment by Maie13** [comment]
![quests repeat cycle](https://user-images.githubusercontent.com/43486435/118970722-8aa24a00-b93c-11eb-8ef3-31d9fe6b26fe.png)

What I remember from trying to get it working last week was that if the repeat cycle was very short (5minutes) it worked as expected. But if it were a longer duration (I tried 1 day but it could be shorter) it allowed the player to pick up the quest even if the player cooldown should have still been in effect if the Ignore cooldown after repeat was true (false seemed to work as expected). There’s no unusual messages, nothing in the console. 

My intent is to make quests which reset every Sunday evening that the players can’t pick up again until after the weekly reset but would allow them to do the quest again as soon as it resets even if they had previously completed the quest just before the weekly reset.

**Comment by PikaMug** [comment]
Thanks for that information. So the player doesn't get any message when trying to take the quest? Not even something like "you're too early/late"? That's what I'd like a screenshot of.

**Comment by Maie13** [comment]
I could have sworn it was letting me pick it up again earlier but now it's just saying the cooldown is 7 days, etc. even though the repeat cycle is 1 day.
![quests active in 7 days](https://user-images.githubusercontent.com/43486435/119050304-a97dfc00-b98f-11eb-8cb6-d3a5d0f57ba9.png)
