### ISSUE TITLE
Only showing the particles when you can actually do the quest, and keeping passwords a secret.

### ISSUE THREAD

**Issue by Ellendyra** [PikaMug/Quests#1684]
**What does your feature do?**
If you don't meet the requirements to start a quest the NPC offers, then they won't whistle (Particle effect) and/or offer it to you.

Also, is there a way so that when you say the passwords to the NPCs it doesn't show in chat?
**How would people use it?**
Passively, I suppose. It would help on servers like mine which are more story-driven so players aren't running into a whole bunch of quests they can't do yet, frustrating and confusing them.

the password thing is because it's a password and those are supposed to be secret.

**Comment by PikaMug** [comment]
Pretty sure `ignore-locked-quests: true` in _config.yml_ should resolve the first problem. I'll look into the password concern.
