### ISSUE TITLE
Disconnecting then reconnecting to server advances stages without meeting requirements

### ISSUE THREAD

**Issue by Toritos** [PikaMug/Quests#1685]
**What is your Quests version / build number (do _not_ say "latest")?** 4.0.2

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When a player disconnects and then reconnects while on a quest stage with a delay set, the stage advances even when the objectives have not been completed.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Example quest: https://pastebin.com/ZhmKTL6L

Start the quest, disconnect and reconnect to server. Wait a few seconds, then repeat disconnect/reconnect. Observe that you will eventually finish the quest and get a free reward with not killing a single zombie.

**Comment by DeadlykillOfficial** [comment]
Remove Delay

**Comment by Toritos** [comment]
> Remove Delay

Not an ideal solution, it'd be much better if there was a check when the player reconnects to ensure they have actually satisfied the stage tasks. Using the delay is great for breaking up the wall of text that would otherwise be shown without a delay there.
