### ISSUE TITLE
Quest not showing up but exists.

### ISSUE THREAD

**Issue by Grallow** [PikaMug/Quests#1686]
Quests Version - 4.0.1

One of my quests, specifically 'custom41' has stopped working. Its in the quests file but it doesnt show up in game or in the quests list.

In the console I found this for the quest:
[09:07:30] [Server thread/WARN]: [Quests] Unable to load custom objectives because quest for custom41 was null
Full console latest log:
https://paste.helpch.at/icufebuyer.makefile

My 'Modules' folder is empty.
I do not believe I have created a 'custom objective' before.

The quest that isn't working:
https://paste.helpch.at/ahigexokam.sql

Also if I don't see this immediately you could contact my discord: Grallow#2464
Please don't close this issue super quick I'll check it once a day until you answer.

**Comment by PikaMug** [comment]
Sorry for the late response.

CitizensAPI has failed to load (probably shouldn't be in your _/plugins_ folder at all). Please correct this before attempting to take quests linked to NPCs. You may also want to fix the issues with CitizensPlaceholderAPI.
