### ISSUE TITLE
Item lore not following what is loaded 

### ISSUE THREAD

**Issue by jugxd** [PikaMug/Quests#1687]
Quest version/Build number: Quests 4.0.2-b237

Problem: 

Hello, I'm having trouble doing a delivery quest where I loaded my custom items (MMOItems) using the available "Load item in hand" feature. I noticed something strange as it is saying that "the item" isn't required when I'm trying the quest. I am also using a QuestsGUI plugin and I noticed a change in the lore of the item after being loaded into the quest. 

I noticed there was "(" in the beginning and ")" in the end of the lore.

Here's a screenshot:

Original item lore
![2021-04-22_20 57 05](https://user-images.githubusercontent.com/66807402/115719104-5c1d6780-a3ae-11eb-9afe-e6b1ebf2505b.png)

Item lore after loaded in hand
![2021-04-22_20 55 29](https://user-images.githubusercontent.com/66807402/115718695-f29d5900-a3ad-11eb-9ec1-fab308b75c80.png)

I don't know if this is my server's problem or the plugin itself. I am hoping to get an explanation to this.

Example quest: https://pastebin.com/7P0vGLTr

Thanks!

**Comment by PikaMug** [comment]
Sorry for the late response.

Load from hand will not work for items from plugins which track using their own system, as opposed to metadata. You didn't mention whether you're using MMOItems Legacy or Premium, but I suspect neither will function as you desire. Tighter integration would be necessary in the form of a module. See https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#want-support-for-other-plugins-or-features
