### ISSUE TITLE
/quests take and Take quests with any ways

### ISSUE THREAD

**Issue by BlueStarKNG** [PikaMug/Quests#1690]
I use /quests take or take quests, it always show "Requirement" in below the Quest accept yes/no
- I didn't add any Requirement or go there,
When I add a Requirement, I have anything it need but it not work too
Someone help me! Thanks a lot
~ sorry for my bad english

**Comment by DeadlykillOfficial** [comment]
Could you provide example quest?

**Comment by PikaMug** [comment]
Closing as this is not a question. Feel free to create a new issue following the "Report a bug" instructions.
