### ISSUE TITLE
Quest displaying sorting method according to quest id instead of position in file

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1691]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.2#239 Quests-4.0.2#240

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
after upgrade from version 239 to 240, the sorting method seems changed, back in the data, the quest gui display according to the position of the quest inside quest.yml, the front one will show add front position in quest gui, but after chaning to # 240, the display changes to id. (i don't know how to explain this better than using word, so i use a photo instead)

This is what looks like in version 239 or before
![image](https://user-images.githubusercontent.com/61608872/118601259-721f1c00-b7e4-11eb-8052-7543bbeb6eb0.png)

This is version 240 
![image](https://user-images.githubusercontent.com/61608872/118601019-5451b700-b7e4-11eb-95e5-1f84febc92ad.png)

the difference:
![image](https://user-images.githubusercontent.com/61608872/118602259-07221500-b7e5-11eb-8dfd-e02f01e77b9a.png)
for circled red one, ids are 
custom1110 
custom1111 
custom1112

by chaning the sorting method, it makes the gui totally messed up. In my server, i designed the gui by placing the quest up/down in the quest.yml to get the gui working, but in 240 build, it read by quest id which totally change how it looks.

no error

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

https://paste.gg/p/anonymous/3a53957d39504dcebb1876e84d8513c7

**Comment by PikaMug** [comment]
Thanks for the report. This is because the internal map no longer maintains a guaranteed order (the change was necessary to begin extending MySQL support). I'm also hopeful that it might resolve #1589

Which prompt is it that you have pictured? Is that from _/quests list_ ?

**Comment by hkkongou** [comment]
> Thanks for the report. This is because the internal map no longer maintains a guaranteed order (the change was necessary to begin extending MySQL support). I'm also hopeful that it might resolve #1589
> 
> Which prompt is it that you have pictured? Is that from _/quests list_ ?

this is the gui build in in main quest plugin, 
set npc start + gui item display

if the internal map no longer maintain, i am afraid that will create a very big problem on files. As the files are according to the id, if i still want to maintain the same gui as before, then i need to change all quest id, which may potentially collide with other id used before, I am worrying that the stored player data will messed up if changing the id just for the gui come back in newer versions

**Comment by PikaMug** [comment]
That might not be a good use of time, since there's no guarantee that quests will be sorted by ID; the order is essentially random.

One option is to continue using build # 239 for now. However, a better choice - and one I can actually support - is to start using [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) (which sorts the quests by name). As long as you use some sort of prefix for the quest names like "LV1" or "🌟" you can control the order regardless of where the quest is in file.

Feel free to leave your SpigotMC username below if you would like a courtesy copy.

**Comment by hkkongou** [comment]
> That might not be a good use of time, since there's no guarantee that quests will be sorted by ID; the order is essentially random.
> 
> One option is to continue using build # 239 for now. However, a better choice - and one I can actually support - is to start using [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) (which sorts the quests by name). As long as you use some sort of prefix for the quest names like "LV1" or "🌟" you can control the order regardless of where the quest is in file.
> 
> Feel free to leave your SpigotMC username below if you would like a courtesy copy.

actually i have already purchased questgui for a long time, however even i checked the gitbook, i still don't see any tutorial on how to sort the order.

i don't mind to pay money for a plugin (i already paid), the only thing i wish is to make it work like before 😢

this is my spigot profile:
https://www.spigotmc.org/members/hk_kongou.838430/
