### ISSUE TITLE
How to disable all Notifications from the Quests Plugin?

### ISSUE THREAD

**Issue by DragonIllya** [PikaMug/Quests#1692]
I want to disable all outputs and notifications from the Quests Plugin. I do it all on my own and I just want to use the stages and so on. I have already deactivatet everything I could in the config file, but these outputs are still there, Is it somehow possible?

**That are the outputs, that are still there:**

When you Start a Quest:
![Unbenannt](https://user-images.githubusercontent.com/45066860/118634105-76423e00-b7d2-11eb-8bee-2e43290cafbc.png)

When you complete a stage:
![grafik](https://user-images.githubusercontent.com/45066860/118634338-b30e3500-b7d2-11eb-9b6d-fd72f9891044.png)

When you complete the quest:
![grafik](https://user-images.githubusercontent.com/45066860/118634439-d2a55d80-b7d2-11eb-8cab-1724e26a2d9e.png)

**Comment by PikaMug** [comment]
This is not possible (except that you could hide the quest rewards with an override display in the editor). Furthermore, it is this project's belief that players should always be notified in some manner.

To achieve the level of customization you're after, you would need to remove the messages from the source code and compile the plugin yourself. See https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Plugin-Compilation
