### ISSUE TITLE
mythicmobs item serialization issues

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1693]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.2#239

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Background info: This problem should only able to replicate with mythicmobs premium dev Build higher than 3645,  as they claimed to have "Fixed item serialization issues when using old color codes and new hex colors making text italicized", free version is older version so cannot test.(download link below for debug use only)

With mythicmobs new dev build, they changed the coding to support 1.16 item serialization, however, i found out that quest cannot properly read mythicmobs created item after this update, mythicmobs used to have similar problem before they add 1.16 serialization , item cannot hand-in , but people can relogin to make the item get serialized and quest can take the item, but after this mythicmob serialization update, quest no longer able to detect mythicmobs item.

steps to replicate the problem:
1. make a mythicmobs items with color lore and color names
2. use quests plugin to make a quest
3. add item requirement or item hand-in stage using mythicmobs  
4. assume the item requirement has been set, use the same item to try to accept the quest, the quest will not able to take.

*i have also checked to make sure the item works by making a shopkeeper npc to trade with the item, shopkeeper can detect the item nicely, the shopkeeper item format is identical to the one made by quest, but only quest cannot detect the item.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

Sample quest here:
https://paste.gg/p/anonymous/2a2a4e1dcd43468ebca92ca56897a7a5

Sample mythicmobs item, used to create the above quest:
https://paste.gg/p/anonymous/6257200b7e124f2cad1f55896c117a0b

This server is running Purpur version git-Purpur-1117 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

mythicmobs premium dev build download link version 3650
(this is a paid plugin, plz do not spread, but for fixing bug, i post a link here, i will remove this link if quest staff have downloaded this plugin for debug use, i am not here to pirate this plugin)
https://drive.google.com/file/d/15j6d6JTyGj3ZfTEfRxNsingjlNiAdpWB/view?usp=sharing

Shopkeeper for reference:
https://paste.gg/p/anonymous/be5810b6267c427791b8b4d5bb35854b

**Comment by PikaMug** [comment]
The download link you shared is broken, but please do not distribute such content, even for debug use.

Similar to #1687 loading items from hand does not work on items which use external tracking methods. It would be up to the MythicMobs developers to either ensure their serialization can be loaded in-game or to update their module to handle tracking.

**Comment by hkkongou** [comment]
yea i deleted the file as i realized that is not good...
i have already made a ticket in discord with this post link.

**Comment by hkkongou** [comment]
> The download link you shared is broken, but please do not distribute such content, even for debug use.
> 
> Similar to #1687 loading items from hand does not work on items which use external tracking methods. It would be up to the MythicMobs developers to either ensure their serialization can be loaded in-game or to update their module to handle tracking.

here comes a problem, i have personally tested mythicmobs new version items with shopkeerps, mangoquest or other similar system that accept and read items, they can do the job well, from the mythicmobs ticket in their discord, the helpers and staff also checked using denizen.

It looks like only quests plugin does not work with mythicmobs items, other plugin works fine

**Comment by PikaMug** [comment]
@hkkongou If you want to describe how to test with Shopkeepers or MangoQuest (haven't used either), I'd be glad to compare.

**Comment by hkkongou** [comment]
> @hkkongou If you want to describe how to test with Shopkeepers or MangoQuest (haven't used either), I'd be glad to compare.
here is a video for me to compare shopkeeper, mangoquest and quest detect items.
https://youtu.be/PfF0jM-WMD4


shopkeeper save.yml file in video
https://paste.gg/p/anonymous/9f33018a9816440eaa925000802cfc93

mangoquest globlaquest.yml file in video
https://paste.gg/p/anonymous/1b9215888419428685bbc032052d9371

mangoquest download link (this is a plugin made by Taiwanese so most of the words are chinese, you can compare shopkeeper first , basically the result from mangoquest detech item is same as shopkeeper) 
https://github.com/Cutiemango/MangoQuest/releases/tag/1.9.8

quests.yml file in video
https://paste.gg/p/anonymous/68d67fdde2ab4e518f93784bf30df5b4

**Comment by PikaMug** [comment]
Thanks for that information. Item data in all of your files looks good, as well as in the video. I've confirmed that loading your Nether Star item works fine when spawned with _/mm i give ChangeL6_ and that it loads from hand correctly with the free version of MythicMobs. As for the premium version, you may want to try the Item Require of their [module](https://github.com/BerndiVader/MythicMobsQuestsModule), but after comparing this definitely seems like a fault on their end. You can find their Discord at https://discord.com/invite/K3tqXfT

**Comment by hkkongou** [comment]
> Thanks for that information. Item data in all of your files looks good, as well as in the video. I've confirmed that loading your Nether Star item works fine when spawned with _/mm i give ChangeL6_ and that it loads from hand correctly with the free version of MythicMobs. As for the premium version, you may want to try the Item Require of their [module](https://github.com/BerndiVader/MythicMobsQuestsModule), but after comparing this definitely seems like a fault on their end. You can find their Discord at https://discord.com/invite/K3tqXfT

maybe i have to say again, the free version is old version of mythicmobs , which uses old version of item serialization and the premium dev version that i am using is the latest mythicmobs version, which will become free version soon.
You cannot test this problem with free version, they haven't change the serialization.

For mythicmobsquest module, i have already installed in my server provided in the video.

One thing i do not understand is why shopkeeper and mangoquest can get the same item code but quest does not. It maybe the same in your end because the version you are using cannot reproduce the issue. :(

I think this problem will be asked by many people soon when mythicmobs release a new free version which have a serialization change.

**Comment by PikaMug** [comment]
I understand, but its up to the developers of MythicMobs to correct their serialization change. Unlike Quests, MangoQuest appears to integrate with MythicMobs directly so they seem to have avoided the issue. I wasn't sure why Shopkeepers continues to work, but further investigation led me to https://github.com/Shopkeepers/Shopkeepers/issues/578 so try updating to the very latest version of Spigot/Paper?

**Comment by hkkongou** [comment]
> I understand, but its up to the developers of MythicMobs to correct their serialization change. Unlike Quests, MangoQuest appears to integrate with MythicMobs directly so they seem to have avoided the issue. I wasn't sure why Shopkeepers continues to work, but further investigation led me to [Shopkeepers/Shopkeepers#578](https://github.com/Shopkeepers/Shopkeepers/issues/578) so try updating to the very latest version of Spigot/Paper?

Yes i have make sure i use latest version of spigot/paper, the video in use is already using latest version of spigot/paper fork, purpur1025 1.16.5.
for the shopkeeper ticket you find, it is a old. The new dev version which involve new mythicmobs serialization is just uploaded last week.

i know it sounds confusing, mythicmobs have similar bug in previous patches lasted for a year before, and the new dev version released  last week is to fix the problem, but it caused quests problem which i mention here :(

**Comment by hkkongou** [comment]
> I understand, but its up to the developers of MythicMobs to correct their serialization change. Unlike Quests, MangoQuest appears to integrate with MythicMobs directly so they seem to have avoided the issue. I wasn't sure why Shopkeepers continues to work, but further investigation led me to [Shopkeepers/Shopkeepers#578](https://github.com/Shopkeepers/Shopkeepers/issues/578) so try updating to the very latest version of Spigot/Paper?

Mythicmobs help team staff reply this:
![image](https://user-images.githubusercontent.com/61608872/119231414-59e82d80-bb53-11eb-9f4e-a8cc54a9a047.png)

**Comment by PikaMug** [comment]
That almost certainly wouldn't help. Adventure (by [Kyori](https://github.com/KyoriPowered)) is a library that predominately handles chat text, and what little item serialization it does appears to be for mouse hover events. Paper started using Adventure back in February (according to their Discord), so if it were the issue I'd think this would've shown up much sooner.

I'll reach out to you on Discord to discuss further, but my conclusion that MythicMobs is at fault hasn't changed.
