### ISSUE TITLE
can i edit - ?

### ISSUE THREAD

**Issue by thedarkcookieez** [PikaMug/Quests#1694]
**Where else have you looked for answers to this question?**
Can i edit  - ?
http://prntscr.com/133xpqd
I can't work on it in that lang

**Share your question with as much detail as possible?**
Can you get rid of this line and if it doesn't work why not?

**Comment by PikaMug** [comment]
Not sure what I'm looking at. Try the community Discord support at https://discordapp.com/invite/QdJAv2G7qg
