### ISSUE TITLE
Idea suggest for Sharing quests

### ISSUE THREAD

**Issue by SliderKP** [PikaMug/Quests#1697]
Hi for first, thanks for this amazing free plugin, im use this plugin for first when the minecraft release the 1.6 version, now im going to use them again :D!

I create this "issue" because i think a command like "/quest share UserName" be amazing to share the quest status, because on my server i cant use Parties Plugin, so this way a user can share with our friends the quest, maybe this need to set a limit of friends to share them.

Thanks for read, srry for my bad english xd.

**Comment by PikaMug** [comment]
Thanks for the suggestion! Plans to support additional party plugins are being considered, but there is no intention to include a built-in mechanic at this time.
