### ISSUE TITLE
Possibility to disable item enchant when quest is tracking

### ISSUE THREAD

**Issue by matteobaldassarre** [PikaMug/Quests#1698]
Hi I would like to ask if it's possible to remove or at least add a config option to disable the fact that an item is enchant when you're tracking/doing a quest, I don't like it very much.

(Also if it's possible to remove the armor and tools info like damage +4 ecc... so they won't fill the lore with non changeable strings)

**Comment by PikaMug** [comment]
Quests 4.0.3 released Thursday which is supposed to do just that. If you find it's not working correctly (and you're sure it's not a QuestsGUI issue), create a bug report here.
