### ISSUE TITLE
How to get Permission Requirements for a Quest to work with Luckperms

### ISSUE THREAD

**Issue by DragonIllya** [PikaMug/Quests#1699]
I want to prevent users from accepting a quest without a certain permission that I gave them using Luckperm. This is the command that I use to give the permission:

/lp user USER parent set lichtalle

It is not recognizing it and is always permitting to accept this quest even if you don't belong to this permission group.

Here is where I add the required permission:
![Screenshot 2021-05-25 000940](https://user-images.githubusercontent.com/45066860/119413301-a7000700-bced-11eb-9cd5-3aad8e9e96c0.png)

I don't know what I do wrong, can somebody help me?

**Comment by TyBraniff** [comment]
Visit the Community Discord and ask in the #community-support channel
https://discordapp.com/invite/QdJAv2G7qg

**Comment by PikaMug** [comment]
That accepts a permission node, not a group. You can use a node which only that group has.
