### ISSUE TITLE
player off-hand hold required item then take quest will cause quest system take money

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1700]
**What is your Quests version / build number (do _not_ say "latest")?**

Quest 4.0.3 # 241

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
For a quest that have item requirement and money requirement, if the player put item in offhand, the quest cannot take, which is nornal, but the money will still be taken by the system, even he did not take the quest.

1. make a quest with money and item requirement
2. wear an item in offhand
3. take the quest
4. the quest system will show a message to the player, the quests cannot take due to item in offhand/wearing, but money was also taken by the system

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://paste.gg/p/anonymous/33d2178913344f58a1c45847d23772a3

**Comment by PikaMug** [comment]
This is intentional, because older versions of Minecraft (which Quests still supports) do not use an off-hand mechanic.
