### ISSUE TITLE
Error + Crash server me (pls help)

### ISSUE THREAD

**Issue by ducdzz61** [PikaMug/Quests#1701]
Paperspigot: 1.16.5
https://pastebin.com/LgdKFgHh
version pl: Quests v4.0.2-b237

**Comment by ducdzz61** [comment]
bonus: https://pastebin.com/nxL8f0UG

**Comment by PikaMug** [comment]
Closing as OP did not follow issue template. Also, please update to version 4.0.3 or latest.
