### ISSUE TITLE
Location in quests

### ISSUE THREAD

**Issue by TheoDkr** [PikaMug/Quests#1702]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.3
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
i put a location where the player need to go and it doesn't work. When i go to the location, the step 2 doesn't launch
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by PikaMug** [comment]
Fixed in a88213cd17d8d8fc4d462005f9f4dbce488bc085
