### ISSUE TITLE
Auto start of a quest

### ISSUE THREAD

**Issue by MrBrainBusta** [PikaMug/Quests#1703]
I'm trying to get a quest to automatically start once a player joins the server. And then in order to complete that quest the player would need to reach an specific location. For the life of me I can't figure it out, is this possible to do? 

Also, I would like to have specific quest start once a player reaches a location and not having to type in an command to start the quest.

**Comment by PikaMug** [comment]
I think the closest you could get is to put a Start NPC or a Start Block in front of the player when they first spawn in. Of course, with external plugins like Denizen+Depenizen or something that could run the _/questadmin give_ command (or _/quests take_ on behalf of the player), that's no problem.

Unfortunately, starting a quest based on location would be too resource intensive for this project. If you use WorldGuard, consider a plugin which uses a region entry flag to run the command.

For more basic usage questions, please visit https://discord.com/invite/QdJAv2G7qg
