### ISSUE TITLE
Hardcoded values disallow customization

### ISSUE THREAD

**Issue by xJoeyv** [PikaMug/Quests#1706]
**Where else have you looked for answers to this question?**
The internet but with own debugging I figured out the issue.

**Share your question with as much detail as possible?**
When starting a question I would like to change the style of messages therefore I styled it and saw there was still a hardcoded yes/no behind.
![image](https://user-images.githubusercontent.com/13612647/120204063-aead3780-c228-11eb-9be8-c6a303abe009.png)
![image](https://user-images.githubusercontent.com/13612647/120204050-aa811a00-c228-11eb-8087-38388aaa3651.png)
I tried changing it in the language `yesWord` and `noWord` to empty what left us with only the hardcoded `/`. This also created a issue with the Yes and No message in the chat so I changed it to this:
![image](https://user-images.githubusercontent.com/13612647/120204350-ffbd2b80-c228-11eb-8b6f-abaec8aaed90.png)
![image](https://user-images.githubusercontent.com/13612647/120204371-0481df80-c229-11eb-8c0f-e4f7ec68672a.png)
Coloring the answers should not effect the choice.

**Comment by PikaMug** [comment]
You've submitted this under "Ask a question" but there isn't one? Feel free to resubmit using either "Suggest a feature" or "Report a bug"
