### ISSUE TITLE
Incomplete "reach location" quest spamming console when player is in another world.

### ISSUE THREAD

**Issue by mercurialmusic** [PikaMug/Quests#1709]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.4 (release) running on git-Paper-764 (Java 16).

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Incomplete "reach location" quest spamming console with errors when player is in another world from the quest (here "gallifrey" vs "resource"). Error example below (but x1000):
https://gist.github.com/mercurialmusic/a7d20872606654412b9268fda91482cb

Forcing the player to quit the quest in question solved the error spam.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
The quest in question, a simple get to this place and deliver a thing to an NPC:
https://gist.github.com/mercurialmusic/b5fca5a3121b382a0d6aeabbe4d4b6ea

**Comment by PikaMug** [comment]
@mercurialmusic Try https://ci.codemc.io/job/PikaMug/job/Quests/244/
