### ISSUE TITLE
Conditions to end a quests

### ISSUE THREAD

**Issue by BrannStark** [PikaMug/Quests#1712]
Hi, I got a question, I've been using your plugin and, I would like to do a system of "tickets" that you would have to buy, to have acess to particular NPC that trades items for money. We can do this with the quest plugin, we make a npc quest where u buy the "ticket" and then u can trades with an other guy. But what I would like to do, is make a "renting system", so I would like that the "ticket" disapear when a time is completed like, 2 days in game for example, and after 2 days if u wanna trade again, u gotta buy again the ticket. But the thing is, I didn't see any options to end a quest that says that in a time given, the quests that have been completed will have to be completed again to use the benefit of it. So does the option exists or if not have u got any ideas of how could I do to do that please ?
Thanks

**Comment by PikaMug** [comment]
Use an Action timer which fails the quest https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Action-Editor

**Comment by BrannStark** [comment]
Thanks for responding so quickly, I've tried this, but the thing is, I want to permit people in a time given, to access to a particular shop. But in the stages options, we can only deliver items to NPCs but we can't recieve any unless the quest is completed... So like I want players to trades as much as they want in a time given it's quite complicated ... :/
