### ISSUE TITLE
NPC names not colour-formatted with "&" in objective completion messages

### ISSUE THREAD

**Issue by TheosisOfficial** [PikaMug/Quests#1714]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.4
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
If an NPC has a coloured name, Quests does not format it 100% of the time. The only case I've come across is inside objective completion messages. An example is shown in this screenshot:
![1](https://user-images.githubusercontent.com/26799016/121784351-781dd800-cbab-11eb-847c-4cc475f091b0.png)
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
N/A

**Comment by PikaMug** [comment]
Quests does not format NPC names; that task falls on Citizens. However, my testing shows that Citizens automatically converts `&e` to `§e` when creating a NPC in-game. Make sure your _saves.yml_ file is in UTF-8 encoding and manually correct any such instances. Starting a string with `&` can have unexpected consequences as it is considered an anchor symbol in YAML files.

**Comment by TheosisOfficial** [comment]
> Quests does not format NPC names; that task falls on Citizens. However, my testing shows that Citizens automatically converts `&e` to `§e` when creating a NPC in-game. Make sure your _saves.yml_ file is in UTF-8 encoding and manually correct any such instances. Starting a string with `&` can have unexpected consequences as it is considered an anchor symbol in YAML files.

I get what you're saying. However, my issue is that I manually go into _saves.yml_ and change the "§" symbol to "&".

The reason I do this is because on my server, I have a scoreboard feature enabled that shows players' health above their heads as you can see in this screenshot:
![image](https://user-images.githubusercontent.com/26799016/121893208-9acc0000-cd15-11eb-8707-07151163bff3.png)
When creating an NPC, they also have this, and I don't want it to be the case:
![image](https://user-images.githubusercontent.com/26799016/121893266-acada300-cd15-11eb-94a3-0ad134292947.png)
As well as this, if the NPC name matches that of an actual Minecraft account, if they have a cape, the cape will show, and I don't want that to be the case either.

I have no idea why, but I've figured out that using the "&" symbol instead of "§" in their names fixes both of these issues. Hence why I use it. I understand that it is a bit of a duct tape solution, but I can't think of anything else.

**Comment by PikaMug** [comment]
> However, my issue is that I manually go into _saves.yml_ and change the "§" symbol to "&".

That is likely not supported by Citizens. Seek help from its developers at https://github.com/CitizensDev/Citizens2
