### ISSUE TITLE
Is there any way to create a choice between quests anymore?

### ISSUE THREAD

**Issue by Alexz1008** [PikaMug/Quests#1715]
**Where else have you looked for answers to this question?**
Nowhere, but I promise this is unique!

**Share your question with as much detail as possible?**
Because of the update where quests now load in order, there's a specific issue I've encountered. I have a setup where the player can choose between a "good" and "evil" quest, and choosing one blocks the other out. But because of this, the good quest references the evil one, and the evil quest references the good one. In other words, no matter which one I load first, they're not going to load because of the circular dependency. Is there any way around this?

**Comment by PikaMug** [comment]
Thanks for your question. When was this update that changed load order? There was a recent update that altered order _in memory_ but that didn't affect loading.

That situation doesn't sound like something that was ever supported, but I might be interested in getting it working.

**Comment by Alexz1008** [comment]
I was previously using version 4.0.0 build 146, and I updated to version 4.0.4 build 243. According to the spigot update logs, it seems this is the first update that actually did this, though if it only altered the order in memory I'm not sure when it was changed. That being said, it for sure worked on the previous version, but no longer works now. If needed, I can send logs, and I'm sure it's also simple enough to reproduce, just have quest 1 blocked by quest 2 and quest 2 blocked by quest 1.

**Comment by DeadlykillOfficial** [comment]
Why don't you just use Custom module that would allow you to make the decision which side to choose inside of a Single quest.
Basically you just run a quest called "Make a Choice" And based on player answer in this quest it would give him either Good or Evil quest line.

**Comment by Beubeux74** [comment]
We can also make choices with quests events, with a few small commands it works well
First, create a quest then an event "answer yes or no or / yes / no" which 1) will complete the quest of choice with questadmin finish <player> <quests> then give the quest chosen, or the permission required to your choice, or any other command(s) of your choice

**Comment by PikaMug** [comment]
https://lectern.browsit.org/resources/resource/12-decisions-objective/
