### ISSUE TITLE
re-publication of a previous question

### ISSUE THREAD

**Issue by BrannStark** [PikaMug/Quests#1716]
Hi again, my previous question was if we could had a time function during quest in order to create a rent system of tickets that gives u acces to special npc trade, and when a certain time is reached, u have to rent again the ticket to access to the shop.

So I've used the timmer in a stage, but the thing is, I want people to pay a rent-ticket, what I did buy a GUI on a npc to begin the quest. Once u bought the ticket, the quest begins, and I know that I can make the 1st stage with a timer and when the timer end, the quest end also, and if u want to enjoy the advantages of the quest u gotta do it again, and to do it again it never completes, it will always "quest failed" when the timer is up. Now what I don't know how to do, is to make markets that u can access only during this quest. Cause I know I could create a second quest saying that u need the first one to access to the second, but if I do that, I don't know how to put a timer on this. So my point is: I want to make a market that is accessible only during a time given by those who bought the right to access to it and at the end of the timer, the access is no longer available, unless u buy again the rent.
Sorry to ask a lot of question but I really need this system.
Thanks

**Comment by DeadlykillOfficial** [comment]
I think you need completely different plugin for that.
Also i got quite confused by the explanation of you.
You could just make it Permission based Market where upon start of Quest It gives player permission and upon fail or finish it does take this permission back. You can include planner and then players would be still able to redo quest later on.

**Comment by BrannStark** [comment]
yeah u right but the big partI can't solve is the market part ... and I was wondering if we could do what I want to do with the quest plugin, if not I'll search an other plugin ^^

**Comment by DeadlykillOfficial** [comment]
This is quests github not market plugins github. If your Market doesn't allow the above things to be done this way. You should change your market plugin. I have told you what you should do on side of Quests to make it. But if your Market plugin its holding you back not allowing such things. There is nothing we can do about it.

**Comment by PikaMug** [comment]
As @DeadlykillOfficial said there is no market functionality within Quests. The only scheduling provided is within the [Planner](https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner), which does not apply to your idea. If you decide to use Quests for your ticket system, you may request integration with whatever market plugin you chose via https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#want-support-for-other-plugins-or-features

**Comment by BrannStark** [comment]
The thing is, I don't have market plugin, and I was using a quest to create a NPC shop, but it works if I don't talk about timers, cause you buy the "ticket" what complete a quest 1, and to trade (quest 2) you have to complete the quest 1. But like I want to do someting with a timmer. I'll search for market plugins cause ur plugin is not a market one, but still it's a greate one really, a lot of options and above all, a github kind, where there is quick responses. Thanks a lot, have a nie day !
