### ISSUE TITLE
Error appearing in console

### ISSUE THREAD

**Issue by CrispyDairy** [PikaMug/Quests#1717]
**Quests 4.0.4**

**https://pastebin.com/Fpe49aG0 Just got this error, saying to send it here**

Also, some quest steps can be skipped by logging off and back on.

**Comment by PikaMug** [comment]
Thanks for the report. Does this still occur on the latest development build?
https://ci.codemc.io/job/PikaMug/job/Quests/244/

**Comment by CrispyDairy** [comment]
Quests 4.0.4? Yes it keeps happening

**Comment by PikaMug** [comment]
While the version number is the same, the build number is different than what you might have downloaded elsewhere. So just to be clear, what is the build number you have installed? Such as 4.0.0-**b218**

**Comment by CrispyDairy** [comment]
How do I check that? The jar file is just called 4.0.4

**Comment by CrispyDairy** [comment]
4.0.4-b243

**Comment by PikaMug** [comment]
> 
> 
> 4.0.4-b243

That is one build behind the version I linked to. Update at your earliest convenience.
