### ISSUE TITLE
Add comma separation for money reward values

### ISSUE THREAD

**Issue by TheosisOfficial** [PikaMug/Quests#1719]
**What does your feature do?**
When receiving a money reward from a quest, the value should be comma-separated. For example, "80000" would become "80,000".
**How would people use it?**
N/A

**Comment by PikaMug** [comment]
Not everywhere in the world uses commas. You might be able to adjust the formatting through Vault or Essentials.

**Comment by TheosisOfficial** [comment]
> Not everywhere in the world uses commas. You might be able to adjust the formatting through Vault or Essentials.

I don't use Essentials, I use my own Vault-based economy plugin, which _does_ format using comma separation, but Vault's [Economy#format()](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java) method has to be called to do so.

I'm pretty sure there is no other way to make plugins format economy amounts besides doing it themselves manually.

**Comment by PikaMug** [comment]
Try https://ci.codemc.io/job/PikaMug/job/Quests/245/

**Comment by TheosisOfficial** [comment]
> Try https://ci.codemc.io/job/PikaMug/job/Quests/245/

Seems to work! There are a couple of instances where it isn't formatted (i.e. in the editor), but this isn't a big deal because players of course will never see that.

Thanks for adding :D
