### ISSUE TITLE
i watch the youtube tutorial video,but when i press 4 and enter, nothing happen, there is no npc spawn, then the option 4 say "npc start (not installed)) sorry for bad english,how to fix this? 

### ISSUE THREAD

**Issue by KayeAja** [PikaMug/Quests#1720]
**Where else have you looked for answers to this question?**

**Share your question with as much detail as possible?**

**Comment by TyBraniff** [comment]
For general help and support I suggest visiting the discord.
https://discordapp.com/invite/QdJAv2G7qg

**Comment by TyBraniff** [comment]
To answer you more directly; It looks as if you don't have Citizens installed. Citizens is required to utilize NPC support.
https://pikamug.gitbook.io/quests/beginner/dependencies
