### ISSUE TITLE
Not all Quests should be loaded in RAM

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1721]
**What does your feature do?**
As you know Quests are stored in a hashmap in RAM when the plugin runs, however this causes a lot of ram usage especially when the server has a LOT of quests (Like my server) when you start getting over 1000+ quests, this becomes extremely ram heavy, and reloading quests takes a pretty significant amount of time. This is a pretty simple thing to say and not "do" per se, since it would require loading and unloading quests in and out of ram dynamically. However I do think it would be a significant performance improvement when a server has a very significant amount of quests like I do.

Simply only load the quests display item (including name, and initial ask), and requirements. When a quest is actually selected, load the actual quest by calling it from the quests.yml file. You could further optimize this by also adding mySQL or MongoDB support for quests storage so that we can store the quests in a database that would be able to call the data whenever it is needed. Keep the quest loaded while the player is Online, and Currently has that quest. If there are no players online that have that quest, or if nobody has the quest at all, unload it out of the hashmap.

**How would people use it?**
This would dynamically be used all the time, and not a specific point. It would make ram usage on larger servers decrease dramatically. Also if this was in a database then synchronizing quest progress, quest information, and other quest related info would be easy by just connecting several servers to the same Database, if you added player data to the mysql/mongodb playerbase.

**Comment by DeadlykillOfficial** [comment]
Just to clarify. Your idea seems "Good" in mind. But from performance perspective. Memory performance it's the fastest.
If we remove Memory and have to use file I/O. It would cause massive performance leak to the server. Exactly because quests.yml can become a huge file. 
Doesn't matter how you look it up. Memory would be fastest and only way to handle 1000 Quests or more.
Either way nowadays every server rocks at least 32 GB up to 256 GB ram.

**Comment by PikaMug** [comment]
Although the memory used will increase with each new quest, the amount should be inconsequential as Deadlykill pointed out. Only reloading from disk (_/qa reload_) would cause significant overhead. Your idea is certainly something I wouldn't mind seeing a Pull Request for, but is not something I consider high priority. Database support would be a superior workaround, the progress of which you can currently follow at #1707
