### ISSUE TITLE
Improve silk touch message in quests

### ISSUE THREAD

**Issue by Espantonius** [PikaMug/Quests#1722]
Hello,
I have come to propose an improvement for one of the announcements of the quests. Specifically with the silk touch.

When you do a quest to break blocks, when you break any block the chat is filled with that phrase.
I leave a small example: https://gyazo.com/78925163262bf249fe84ed25133c79dc

My improvement would be to add only that phrase in the blocks that are added to the quest.
Example: If in a quest you have to take wood, that message only appears when you are going to break the wood with a silk touch.

Thanks!

**Comment by PikaMug** [comment]
While I agree that would be preferable, the way it's coded now the block type cannot be verified before issuing objective progress (as that would break multiplayer quests). I'm open to a Pull Request if anyone can work out another way, but it's not something I'm interested in pursuing.

https://github.com/PikaMug/Quests/blob/fc612f5a943933f0c57b2ceeabd900f03aa25f35/main/src/main/java/me/blackvein/quests/listeners/BlockListener.java#L72-L87
