### ISSUE TITLE
Console error when a New Player Joins

### ISSUE THREAD

**Issue by Renzoez** [PikaMug/Quests#1724]
Hello, 

I'm using the 4.0.1-b230 version of Quests.

So i noticed on my server that when a new player join to my server, this always appear on my console.

[Log Console Error](https://pastebin.com/BdkBVwSW)

> [02:54:38] [Server thread/INFO]: Pukuu[/###.##.###.##:47152] logged in with entity id 634 at ([world]-215.2698836644371, 83.0, 184.10837814079744)
> [02:54:38] [Craft Scheduler Thread - 6/WARN]: java.lang.NullPointerException
> [02:54:38] [Craft Scheduler Thread - 6/WARN]:   at me.blackvein.quests.listeners.PlayerListener$3.run(PlayerListener.java:853)
> [02:54:38] [Craft Scheduler Thread - 6/WARN]:   at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
> [02:54:38] [Craft Scheduler Thread - 6/WARN]:   at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
> [02:54:38] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> [02:54:38] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> [02:54:38] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.lang.Thread.run(Thread.java:834)

This is my config file.

[Config File Quests Plugin](https://pastebin.com/M9SmVrBk)

and the Quests.yml file:

[Quests.yml File](https://pastebin.com/1A9AMbfm)

**Comment by PikaMug** [comment]
Thanks for the report. Please check if the error still occurs on the following development build (and if so provide the new error, even if it looks similar):
https://ci.codemc.io/job/PikaMug/job/Quests/246/

**Comment by Renzoez** [comment]
Thanks.

It got fixed! Please, if you can try to publish it at Spigotmc where i download the plugin.

Thanks again.

**Comment by DeadlykillOfficial** [comment]
> Thanks.
> 
> It got fixed! Please, if you can try to publish it at Spigotmc where i download the plugin.
> 
> Thanks again.

You should use the Build provided above. Uploading to SpigotMC would take some time.
