### ISSUE TITLE
Force Quests Journal to stay in inventory

### ISSUE THREAD

**Issue by Geph** [PikaMug/Quests#1726]
**What does your feature do?**
A configuration option to force the journal to stay in a given inventory slot - not allowing players without a certain permission level to remove it.

**How would people use it?**
The little kids who use our server are often not very good at remembering or understanding how to type commands into chat (like /quests journal) but they do know how to do things like throw their journal into lava or off a cliff in protest. It would be nice to prevent them from being able to lose it.

**Comment by DeadlykillOfficial** [comment]
https://github.com/PikaMug/Quests/blob/a8412c948dfa0d4456559109a48c6544ccc761b4/main/src/main/java/me/blackvein/quests/listeners/PlayerListener.java#L167

This code makes sure player cannot drop it's Journal from inventory. Which means if it's not working either your players have permissions to bypass that OR another plugin it's interfering.

**Comment by PikaMug** [comment]
It's also possible they somehow have the `quests.admin.drop` permission, so make sure that they don't.
