### ISSUE TITLE
Quests Journal specific requirements in addition to custom descriptions

### ISSUE THREAD

**Issue by Geph** [PikaMug/Quests#1727]
**What does your feature do?**
Right now if you add a custom description for a stage or quest it over-writes the criteria-based descriptions, like coordinates to reach or blocks to acquire. It would be great to have BOTH - a page explaining some of the details and story of the quest but then also a page showing how far they've progressed along (talked to 2 of these 3 NPC's etc). 

**How would people use it?**
Probably a config option to allow custom objectives in addition to standard objectives, instead of in place of.

**Comment by DeadlykillOfficial** [comment]
You can already over-write objectives. Inside of Stages use List Override option. And it would appear in Journal and /quest
As what you write in there

**Comment by PikaMug** [comment]
As Deadly implied, stage detail overrides intentionally hide the progress. Lore of the quest can be defined separately under start/complete messages. If you're not satisfied with how this applies to the Quests Journal, please consider https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#want-support-for-other-plugins-or-features
