### ISSUE TITLE
Unable to load module from file: SkillAPIModule.jar

### ISSUE THREAD

**Issue by toponeme** [PikaMug/Quests#1730]
Quests4.0.5 and 3.9.5
The version of SkillAPI is 1.8.7
https://pastebin.com/Ksqb7BgW
quest.yml:https://pastebin.com/Ehwijfze

**Comment by DeadlykillOfficial** [comment]
You must provide the information required in the layout.
I'm afraid your ticket will not be answered and it will be tagged invalid with the information you have provided.

**Comment by PikaMug** [comment]
Having multiple versions of Quests installed is not supported. SkillAPI has never released a version 1.8.7 to my knowledge.

Disregarding that, this is an error with their module. Seek help from its developers; not Quests.
