### ISSUE TITLE
Changed strings.yml only works on local server

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [PikaMug/Quests#1731]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.5-b246
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Changed strings.yml only works on local server. Changed several lines, mostly just added custom color formatting.
It works fine on a local copy of my live server, but once on the live server, exact same files, plugins etc., it doesn't work and defaults the strings. I have even tried removing the lang files. I was then told by Deadlykill in discord that the server doesn't have access to the server files and defaults to using Crowdin instead.
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

Here is the live server with default formatting and strings
![2021-06-30 16_19_03](https://user-images.githubusercontent.com/36818957/123982925-bb59b280-d9c3-11eb-9118-2daca4872f09.jpg)

Here is the edited local server which works fine
![2021-06-30 16_21_55](https://user-images.githubusercontent.com/36818957/123982930-bc8adf80-d9c3-11eb-925f-6c89f1b742e2.jpg)

Edited strings like Go to task, string about console forcing the quest to a player etc.

**Comment by PikaMug** [comment]
Yes, it sounds like a file permissions issue. If it's a Windows machine, you can try https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting

Otherwise, look up the equivalent steps for your operating system online.
