### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by thisisnotkj** [PikaMug/Quests#1732]
**What is your Quests version / build number (do _not_ say "latest")?**

 v4.0.5-b246

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
console error on launch, plugin wont load

https://pastebin.com/eWcgVqNX

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
dont have any, plugin wont load

**Comment by PikaMug** [comment]
This is an error with the [NPCDestinations](https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#npcdestinations) plugin, seek help from its developer.
