### ISSUE TITLE
MythicMobs support...

### ISSUE THREAD

**Issue by Keopsfenks** [PikaMug/Quests#1734]
Hi Mr. Developer, I have contacted Discord and it is said that MM support is difficult to do. The current MM module looks a little old. Even if MM support does not come, if we can add a name nbt tag in the Mob Kills category, it will be as much as MM support.

For example, your item category is also magic, name, lore adjustment.

**Comment by PikaMug** [comment]
If my MM, you mean MythicMobs, then no, it is not difficult to do. Just use the module https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#mythicmobs

NBT editing would require NMS code which is not ideal given the range of Minecraft versions currently supported by Quests.
