### ISSUE TITLE
No Permission to do that.

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1737]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.5 b247

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
There are no errors available in console. The only thing that's happening it' whenever you go to editor you have all the access and you can edit quest no worries. But once you get to the place where you want to save your quest it does prompt you with the following error.
![image](https://user-images.githubusercontent.com/12415714/124939099-22e9b080-e009-11eb-9f10-15e97887f843.png)

Having OP.
Also having Permission node *
Thought it might require specific node. I've jumped into Wiki and gave all Quests permission nodes to Player and yet. You don't have permission to do that.

It doesn't let Creating new quests, It doesn't let Editing Quests. Nothing helps out at this point.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by DeadlykillOfficial** [comment]
Thought it could be my plugin itself or QuestsGUI or any folder.
Therefor i've deleted all Quests related folders. Deleted QuestsGUI entirely.
Tried on completely fresh build and folder.
![image](https://user-images.githubusercontent.com/12415714/124939793-b58a4f80-e009-11eb-9c54-c4bf237214be.png)
Those are the results.

**Comment by PikaMug** [comment]
Probably related to https://github.com/PikaMug/Quests/commit/5d9a9e8c976e774bb82c474ce530855d7762d37b which isn't documented yet. Since you're using * permission try also setting `quests.admin.trial false` for LuckPerms or `-quests.admin.trial` for PEX / others.
