### ISSUE TITLE
Setting to add custom SQL connection properties

### ISSUE THREAD

**Issue by Zimoune** [PikaMug/Quests#1740]
**Where else have you looked for answers to this question?**
- https://pikamug.gitbook.io/quests/expert/storage
- On Discord with Deadlykill

**Share your question with as much detail as possible?**
Since I've upgraded my MariaDB server to version 10.5, I have trouble with the MySQL connection. 
I'm using Quests 4.0.5, MariaDB 10.5 and paper 1.17.1-98 (jdk16)

`sslhandshakeexception: no appropriate protocol (protocol is disabled or cipher suites are inappropriate)`

I've found a workaround by adding the properties below in the MysqlConnectionFactory class
`properties.putIfAbsent("verifyServerCertificate", "false");`
`properties.putIfAbsent("useSSL", "false");`

Luckperms plugin describes the issue [here](https://luckperms.net/wiki/Storage-system-errors#mysql-ssl-errors).

I would like to add these properties directly in the config.yml file instead of my fork :)
Is there a way to do that? Or do I have to create a ticket to ask for this feature?

Thank you

**Comment by PikaMug** [comment]
The link to the LuckPerms wiki you shared appears unrelated to this issue. More likely you're using a Java Development Kit which does not support the same SSL/TLS protocol as your database. While disabling SSL does circumvent the issue, it does so in a less secure way. The proper solution is to ensure that both the JDK and database use the same TLS protocol version. Check the version in use by your database under [this system variable](https://mariadb.com/kb/en/ssltls-system-variables/#tls_version), then either update it (recommended) or follow one of the solutions detailed [here](https://support.azul.com/hc/en-us/articles/360061143191-TLSv1-v1-1-No-longer-works-after-upgrade-No-appropriate-protocol-error).
