### ISSUE TITLE
Console Error for Quests

### ISSUE THREAD

**Issue by Spleggeti** [PikaMug/Quests#1741]
11.07 11:41:54 [Server] ERROR [Quests] An error has occurred with Quests. Please report on Github with info below
11.07 11:41:54 [Server] WARN [Quests] quest = custom5
11.07 11:41:54 [Server] WARN [Quests] index = 0
11.07 11:41:54 [Server] WARN [Quests] location = Location{world=CraftWorld{name=skyblock},x=-400.0,y=201.85489329934836,z=-2000.0,pitch=0.0,yaw=0.0}
11.07 11:41:54 [Server] WARN [Quests] locationsToReach = 1
11.07 11:41:54 [Server] WARN [Quests] locationsReached = 1
11.07 11:41:54 [Server] WARN [Quests] hasReached = 1
11.07 11:41:54 [Server] WARN java.lang.IllegalArgumentException: Cannot measure distance between world and skyblock
11.07 11:41:54 [Server] WARN at org.bukkit.Location.distanceSquared(Location.java:510)
11.07 11:41:54 [Server] WARN at me.blackvein.quests.Quester.reachLocation(Quester.java:2583)
11.07 11:41:54 [Server] WARN at me.blackvein.quests.listeners.PlayerListener$4$1.run(PlayerListener.java:993)
11.07 11:41:54 [Server] WARN at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
11.07 11:41:54 [Server] WARN at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
11.07 11:41:54 [Server] WARN at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1354)
11.07 11:41:54 [Server] WARN at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372)
11.07 11:41:54 [Server] WARN at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267)
11.07 11:41:54 [Server] WARN at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
11.07 11:41:54 [Server] WARN at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
11.07 11:41:54 [Server] WARN at java.lang.Thread.run(Thread.java:748)

I believe it might be an issue with the Reach Locations requirement, Would i be better off denying commands for these quests so they have to finish them before going to the plot world.

**Comment by PikaMug** [comment]
Thanks for the report. What is your Quests version and build number?

**Comment by Spleggeti** [comment]
So i can't specifically find the version for it, buti t was the version of the Quadratic Update and idk where to find the Build number.

**Comment by DeadlykillOfficial** [comment]
type /about Quests
And you will see the version and build

**Comment by Spleggeti** [comment]
4.0.4-b243 - Is that it?

**Comment by DeadlykillOfficial** [comment]
Yeah but you are bit outdated.

**Comment by PikaMug** [comment]
Please update to 4.0.5 and create a new ticket if the issue persists.
