### ISSUE TITLE
Quests Locking Thread & Causing Crash?

### ISSUE THREAD

**Issue by Jurz21** [PikaMug/Quests#1742]
Hi,

**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.2

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Possible server crash after Quests locked a thread?

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Crash log: https://pastebin.com/EvZmwNEt

Can you please confirm if quests caused this and if there is anything i can do about it. Currently Quests is on the server for future development, no quests are live atm, except for the example permission based ones.

Thanks,

**Comment by PikaMug** [comment]
Wrong plugin, looks like you want https://github.com/LMBishop/Quests
