### ISSUE TITLE
Quests work in craft of UltraSkyblockCore

### ISSUE THREAD

**Issue by SliderKP** [PikaMug/Quests#1743]
plugin quests listens for normal spigot events?
it is for a plugin that has a system that changes the crafting table and quests cannot be performed

**Comment by SliderKP** [comment]
i dont want to create a QUEST with API, im using a plugin, with a modified crafting table, but have the default crafts too, so, i want to detect on the plugin ( im speaking with the dev ) the crafts maded with the new crafting table to make possible end quests, if i create a quest, called "craft a iron helmet" and i craft iron helmet with the modified crafting table, its not recognized by quests to end the "craft a iron helmet" quest

srry for my bad english

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/blob/1644f18549c417c3d72f5c00bec794e47c917b1e/main/src/main/java/me/blackvein/quests/listeners/ItemListener.java#L78
