### ISSUE TITLE
The Plugins commands aren't working at all.

### ISSUE THREAD

**Issue by MRRyanKun** [PikaMug/Quests#1744]
**What is your Quests version / build number (do _not_ say "latest")?**

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by MRRyanKun** [comment]
1.17
4.0.5
The Plugins commands aren't working at all.

**Comment by DeadlykillOfficial** [comment]
This is not enough information at all for anyone here to help you. As for commands they are working on 1.17.
You can check "play.browsit.org" on 1.17. It's official Quests test server.
