### ISSUE TITLE
No Chatmessage when have a Error in Config

### ISSUE THREAD

**Issue by Klotzlutscher** [PikaMug/Quests#1745]
**What is your Quests version / build number (do _not_ say "latest")?**
-4.0.3 DEV 242

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
So we changed something, missed an space in an line, reloadet it and it dosnt tell it ingame that there was something wrong.Was the normal Message with the Quests are Reloadet.

2 Days later the Intern Datastorage that we used was broke and we get this Error in Log:
https://pastebin.com/0KkM4qqr

Some Progress would be reset (we used a backup then), and we had to Switch to MYSQL now.
I dont know if the problem comes only from 1 missing space in the config that we forgot, or its an bigger problem.
If you need more information, i can bring it.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Example from Quests: https://pastebin.com/9rqgrGRb

**Comment by DeadlykillOfficial** [comment]
You are running outdated Quests. Try to update it and see if the error persist.
Also the error you have posted it's based on YAML syntax.
You don't have the correct YML syntax therefor it cannot load the file. Try http://www.yamllint.com to find the issue.

**Comment by Klotzlutscher** [comment]
Thanks for the fast reply, i will update it and see if the problem still acure.
We know allready that we missed the one Space in the line.Depend on http://www.yamllint.com/ the file is valid that we used.
But why  there was not an Error message ingame after reloading? And why broke it the Intern Database. The Error i posted was the only one we getting  and only after 2 days. Shouldnt been an warning ingame that something is wrong when you reload? like at other stuff.

**Comment by PikaMug** [comment]
Editing files manually is not recommended. Use a YAML parser such as [this one](https://yaml-online-parser.appspot.com/) (not affiliated) to discover the issue.
