### ISSUE TITLE
Quests Incompatibility with Latest Citizens Version

### ISSUE THREAD

**Issue by RocketManKian** [PikaMug/Quests#1746]
**What is your Quests version / build number (do _not_ say "latest")?** 4.0.5

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?** When updating to the Latest Citizens Version (2.0.28) Quests fails to load. Here is the console error https://paste.gg/p/anonymous/5b644ec9c4f94918b41e150bc1007df7

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?** N/A

**Comment by PikaMug** [comment]
Has nothing to do with Citizens and everything to do with NPCDestinations. Contact the developer of that plugin.
