### ISSUE TITLE
Unknown error when using /questsadmin reload

### ISSUE THREAD

**Issue by DoodlesEpic** [PikaMug/Quests#1747]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests: 4.0.5
Paper: 1.17 build number #108

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I am not sure how to replicate it, however, I feel it has to do with me dying while doing a quest that spawned lots of mobs, while the quest had the ability to leave disabled. The following error appears now when trying to reload the plugin after modifying this same quest:

PASTE: https://pastebin.com/BrveEFda
PASSWORD: idrMCrb2uw

I have already restarted the server, other quests are working fine, but I can't start this one anymore, the in-game chat says there are no active quests (in Portuguese so I'm not sure this is the original message string)

Note: I did replace my actual Minecraft username with USERNAME in the Pastebin, just because.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

The quest strings are in Brazillian Portuguese, however the quest itself should still be possible to understand, you basically just have to enter a dungeon, kill two waves of mobs, and return to the NPC that gave you the quest.

PASTE: https://pastebin.com/Zn0gBCBG
PASSWORD: q9jK9tr2YK

CUSTOM ACTIONS: https://pastebin.com/bTRHvyau 
PASSWORD: Z0BSYkhVrc

**Comment by DoodlesEpic** [comment]
Managed to understand better what caused this. After all players on the server dropped all quests the error stopped appearing.

**Comment by PikaMug** [comment]
Thanks for the report. Please confirm whether the issue still occurs on the latest development build and, if so, report back with the new error (even if it looks similar):

https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by DoodlesEpic** [comment]
As I said I'm not exactly sure how to reproduce it, however, I will notify you if the error reappears :)

**Comment by PikaMug** [comment]
Closed pending further issues.
