### ISSUE TITLE
FATAL error in console

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#1748]
pastebin:
https://pastebin.com/hJDvmzHy

Version: 4.0.5 (Spigot)

Server Version:
[08:37:47 INFO]: This server is running Tuinity version git-Tuinity-21 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bdd7bb4 on HEAD)

**Comment by PikaMug** [comment]
Thanks for the report. Please confirm whether the issue still occurs on the latest development build and, if so, report back with the new error (even if it looks similar):

https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by PikaMug** [comment]
Closed pending further issues.
