### ISSUE TITLE
Feature: Display multiple lore lines & rewards when players hoover over the title.

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#1749]
Feature: Display multiple lore lines & rewards when players hoover over the title.

Basically, allow multiple lines on the lore in the config so text isnt too long it comes off the player's screen.

The other one was, allowing option for DisplayReward on the title or something. Basically so when someone hovers over a quest in a GUI they are able to see the reward before claiming the quest.

Thanks for listening :)

**Comment by PikaMug** [comment]
Consider using [QuestsGUI](https://browsit.gitbook.io/questsgui/) for enchanced GUI functionality.
