### ISSUE TITLE
1.17.1 - Multiple Errors on startup

### ISSUE THREAD

**Issue by Kruize1** [PikaMug/Quests#1751]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests: 4.0.5-b246

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

Start Server and observe console logs:

https://pastebin.com/w8WYGDgR

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by PikaMug** [comment]
Thanks for the report. This is an error with the MythicsMobs module, please seek help from its developer.
