### ISSUE TITLE
Quests plugin crash with parties

### ISSUE THREAD

**Issue by DoodlesEpic** [PikaMug/Quests#1752]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.5 - b246

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
After I installed the compatible parties plugin and tested some quests with it the quests plugin crashes my server almost daily. It seem to be related to parties since it appears in the stack trace, but the error is thrown in quests first. After that the server tries to stop and quests seems to have problems stopping correctly.

https://pastebin.com/JMAe6WEQ

**Comment by PikaMug** [comment]
The multiplayer code which this error references was improved in version 4.0.6 of Quests. Please update, then reply with a new stacktrace should the issue persist.
