### ISSUE TITLE
Consuming defective after logging in again

### ISSUE THREAD

**Issue by Loiytzia** [PikaMug/Quests#1754]
What is your Quests version / build number (do not say "latest")?
Quests-4.0.5 Build-249

Describe the problem and how to replicate it.
We created a quest to eat a custom created Cookie. If the player accepts the quest and then changes the server (BungeeCord) or logs out completely, the quest can still be viewed under / quest, but he no longer registers the eat. We thought it was the custom created cookie at first, but it doesn't work with a regular cookie either. We are using a .yml to save the quests. 

Any console errors to post using a pastebin?
No errors in the log.

If applicable, can you provide an example quest from quests.yml using a pastebin?
https://pastebin.com/z0TKLt85
X7yzsBwvTW

**Comment by PikaMug** [comment]
As of writing, player progress doesn't transfer across servers. [Development builds](https://ci.codemc.io/job/PikaMug/job/Quests/) make this possible, but only for SQL storage (and even then, you'll have to sync the _quests/actions/conditions.yml_ files across servers yourself.
