### ISSUE TITLE
1.17.1 quest editor does not work

### ISSUE THREAD

**Issue by Loiytzia** [PikaMug/Quests#1756]
What is your Quests version / build number (do not say "latest")?
Quests-4.0.5 Build 251 // Paper-116 (MC: 1.17.1)

**Describe the problem and how to replicate it.**
We have installed the latest build #251. With "/quest editor" the editor can be opened, but with input "1" I do not get into the area create quest. The number is simply written in the local chat. If I try it again, I am told that I am already in the editor.
![2021-07-28_16 43 00](https://user-images.githubusercontent.com/69648980/127350420-bdf1f758-89cc-44f4-a470-41dff45ea506.png)
The error only occurs with 1.17. With the 1.16.5 everything works.

Any console errors to post using a pastebin?
No errors in the log.

**Comment by PikaMug** [comment]
The reason for that is you can only open the editor once. As for "1" not working, it's most likely you have another plugin interfering with the chat input. Try removing all non-critical plugins and, if that resolves the issue, add them back one-by-one until you find the conflict. If that doesn't help, reply with a list of the remaining critical plugins you had.
