### ISSUE TITLE
Consuming defective after logging in again

### ISSUE THREAD

**Issue by Loiytzia** [PikaMug/Quests#1757]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.5 Build-251

**Describe the problem and how to replicate it.**
We have now installed build #251 on our two 1.16.5 servers and adapted our Datebnak to MySQL in the configs. Unfortunately after the quest has been accepted, the counter still does not went up after changing server or relog.
Since the plug-in is installed on both server, many warnings are written to the log. The NPC for these quests is currently only on one server.

**Any console errors to post _using a pastebin_?**
https://pastebin.com/FbvPPmt4

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/dJwzZcVm

**Comment by PikaMug** [comment]
If you are using NPCs for quests, then NPCs of the same ID would need to be present on both servers. Either create the NPCs on all servers or remove the NPC attachment from those quests.
