### ISSUE TITLE
Leaving and rejoining rewards quest.

### ISSUE THREAD

**Issue by DomDoesGitHub** [PikaMug/Quests#1759]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.5
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I have a quest that consists of catch 10 fish then you are awarded 300$. This quest allows you to do it every 12 hours. 
This issue does not occur on quests that only happen once.
After starting the quest if the player leaves and joins again it will instantly give them the quest completed.
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

Here is the quests.yml entry
  custom1:
    name: Catch Some Fish
    ask-message: Hey! Can you catch some fish for me?
    finish-message: Well done!
    npc-giver-id: 12
    stages:
      ordered:
        '1':
          fish-to-catch: 10
          delay: 3
          complete-message: Great! Now head back to me.
    rewards:
      money: 300
    planner:
      cooldown: 43200
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false

**Comment by PikaMug** [comment]
Possibly related to #1685

**Comment by PikaMug** [comment]
Confirmed duplicate - remove the 3-second delay. Also please use a pastebin for your quest next time.
