### ISSUE TITLE
Displaying the correct answer in the chat

### ISSUE THREAD

**Issue by Fildaa** [PikaMug/Quests#1760]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.1.jar

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I'm copying a quest discord message from where they sent me here.

Hi, I'd like to ask how to turn off the correct chat answers. I understand that it will classically write the wrong answer in the chat, but when the player wrote the correct answer, it sent him to the next stage or ended the quest and gave him a reward.

I remember that I completed quests about a year ago and every time I wrote the correct answer to the quest, the answer was no longer written in the chat but remained as if hidden. It fulfilled my quest and gave me a reward. Or moved to the next stage.

Now, even if I write the correct answer, it will be written in the chat. So then other players can know the correct answers. They can just copy the answers and easily complete quests like this.

I also asked a friend, and he remembers that it was the way I write it here. If you guessed or wrote the correct answer. It no longer appeared as a bad answer in the chat and it fulfilled your quest.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://ctrlv.cz/nlIQ

**Comment by PikaMug** [comment]
I'm assuming this is about a Password objective. Simply update to a newer version of Quests.
