### ISSUE TITLE
[13:28:37 ERROR]: Could not pass event EntityDeathEvent to Quests v4.0.5-b246

### ISSUE THREAD

**Issue by NickThuan** [PikaMug/Quests#1762]
Mythicmobs verison : MythicMobs-4.4.1 and MythicMobsQuests-391-SNAPSHOT
Quests: Quests-4.0.5
Bug:
I did a quest that was killing pig mythicmobs, when I finished and received that quest, I went to kill pig but it shows error like this? . How do I fix it?
My error console : https://pastebin.com/EW4bqKu3
My pig mythicmobs : https://pastebin.com/x2ZjJqrm

**Comment by PikaMug** [comment]
This is an issue with the module; not Quests. Seek help from its developer.
