### ISSUE TITLE
Subfolder and multiple files for quests

### ISSUE THREAD

**Issue by SlyyJacob** [PikaMug/Quests#1763]
**What does your feature do?**
For better organization, especially when creating 10s or even 100s of quests of the same type with few variations, having the quests.yml in subfolder and being able to create as many files as you like, would be amazing addition. Say I could have a .yml file for quests in area1, area2, area3... or categorized by the NPCs/quest givers.

**Comment by PikaMug** [comment]
Thanks for the suggestion. Having separate files could present an issue for larger servers with hundreds or thousands of quests where heavy file operations may result in latency when saving/reloading. Eventually, quest/actions/conditions will support MySQL storage, which is a superior solution that can be easily sorted with a database editor.
