### ISSUE TITLE
Number range in objectives

### ISSUE THREAD

**Issue by SlyyJacob** [PikaMug/Quests#1764]
**What does your feature do?**
Using ranges in objectives where a number is used - ie. break stone block x amount of times, where x would be a given range, 10-30, out of which a random number is picked. Allowing ranges to be used in modules as well.

**Comment by PikaMug** [comment]
Thanks for the suggestion. I would not be opposed to a Pull Request, but otherwise this is something best left to a module. In fact, I'm certain you could submit a request to the author of https://lectern.browsit.org/resources/resource/19-break-blocks-objective-improved/
