### ISSUE TITLE
[mysql] Data saving issue when stopping server/paper watchdog shutdown (crash)

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1765]
**What is your Quests version / build number (do _not_ say "latest")?**

v4.0.5-b247

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

paper watchdog will stop server when server is not responsing for too long , it is normal, however, one time when the server is stopped by the paper watch dog, the server cannot full shutdown.

The server cannot shudown seems due to quests plugin is storing something to the sql database, but the connection to the database is closed before the storage.

Log:

https://paste.gg/p/anonymous/5e9ee4ba94f946308e2580179aa708e5

and then server is stuck for 2hours until i use ctrl+C in ubuntu to kill the process

**Comment by hkkongou** [comment]
not sure is this related but this is an error when i use stop command to stop server
it does not happen everything tho
![image](https://user-images.githubusercontent.com/61608872/128956475-fe1f4d5b-bd54-4f19-8e43-40b3aad0fdb2.png)

**Comment by hkkongou** [comment]
and afterwards some of my players say their quest progress is lost .

**Comment by PikaMug** [comment]
Please check if this issue still occurs on https://ci.codemc.io/job/PikaMug/job/Quests/280/
