### ISSUE TITLE
Items tasks buged in the plugin. You can't reach the task after a items task like crafting, smelting, brewing......

### ISSUE THREAD

**Issue by elbo8** [PikaMug/Quests#1766]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.6 - b253

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
it is when you testing the quest, you finish a task and it must show the next task but it don't, it shows just task completed but not new objectives. And the task which it stops after are the items task like craft or enchant or brew . 
example:  i have a kill mob task - craft iron block - reach location .
when i test this kill mob location work coorectly also then craft iron block but here it show task craft block done and it don't show new objective: reach location.
that's it

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://www.youtube.com/watch?v=Qd4EqB5QAmI 
this is a recorded video as a clear example.

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/254/
