### ISSUE TITLE
Execute command with current player username tag

### ISSUE THREAD

**Issue by danielramirezm** [PikaMug/Quests#1767]
Hi, I want to teleport an user with a tp command in actions.yml but I don't know the tag for that kind of command to display the current username.

For example:

-tp **%playername%** X Y Z

Can u help me with this?

Sorry for my bad english

**Comment by PikaMug** [comment]
Try `<player>` but if that doesn't work this is a question best asked in [Discord](https://discord.com/invite/QdJAv2G7qg).
