### ISSUE TITLE
Explinations

### ISSUE THREAD

**Issue by Amalissia** [PikaMug/Quests#1772]
**What does your feature do?**
Provides explanations for what each feature does as well as how to use it.

**How would people use it?**
Some of the current GUI features are a bit hard to understand and its hard to play with them if you dont really understand what they do -  I've read over the spiggot and Bukkit pages as well as watched a few tutorials. I understand it a bit better but there are still several features I'm confused on and will likely never use because i dont know what they do.

**Comment by PikaMug** [comment]
Thanks for your input, but I'm not sure I understand. Which GUI are you referencing? If it's part of QuestsGUI, then this is the wrong issue tracker. There's also Gitbook wikis for both Quests and QuestsGUI which explain most features in detail.
