### ISSUE TITLE
Error when killing mythic mobs when having taken a quest to kill other mythics. Also error on plugin load.

### ISSUE THREAD

**Issue by Momshroom** [PikaMug/Quests#1774]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.6-b254

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When a player has an active quest to kill one type of mythic mobs, I get this error when they kill any mythic mobs (whether or not that mythic is a quest objective).  Players without the quest do not cause the error.  The error did not occur in Minecraft 1.16.5, but does in 1.17.1 (paper 190): 
https://paste.gg/p/Momshroom/b0b20046c6f341d2ace35f4c25ea2046

I also get this error on loading the plugin:
https://paste.gg/p/Momshroom/55960053142d43a68bd25eaf9ea7db0f

I realize it might well be an issue with the Mythic Mobs Objective module and am sorry for bothering you if that's the case.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://paste.gg/p/Momshroom/8f41f5e58c3349fda461906c792ccf0c

**Comment by PikaMug** [comment]
This is an issue with the MythicMobs module, seek help from its developer.

**Comment by Momshroom** [comment]
Thank you.
For anyone else who might be following this in the future, here's my ticket with MythicMobsQuests: https://github.com/BerndiVader/MythicMobsQuestsModule/issues/49
