### ISSUE TITLE
Could not pass event EntityDeathEvent to Quests 

### ISSUE THREAD

**Issue by Grievous07** [PikaMug/Quests#1775]
Quests 4.0.5

17.08 19:26:43 [Server] ERROR Could not pass event EntityDeathEvent to Quests v4.0.5-b246
17.08 19:26:43 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 73, Size: 16
17.08 19:26:43 [Server] INFO at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
17.08 19:26:43 [Server] INFO at java.util.LinkedList.get(LinkedList.java:480) ~[?:?]
17.08 19:26:43 [Server] INFO at me.blackvein.quests.Quester.killMob(Quester.java:2465) ~[?:?]
17.08 19:26:43 [Server] INFO at me.blackvein.quests.listeners.PlayerListener.preKillMob(PlayerListener.java:651) ~[?:?]
17.08 19:26:43 [Server] INFO at me.blackvein.quests.listeners.PlayerListener.onEntityDeath(PlayerListener.java:620) ~[?:?]
17.08 19:26:43 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1379.execute(Unknown Source) ~[?:?]
17.08 19:26:43 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:850) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1598) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1520) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityEnderman.damageEntity(EntityEnderman.java:389) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1196) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2022) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2413) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1395) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-"e04368045"]
17.08 19:26:43 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
17.08 19:26:43 [Server] ERROR Could not pass event EntityDeathEvent to Quests v4.0.5-b246

**Comment by PikaMug** [comment]
Thanks for the report. Most likely, you have a greater number of mob types versus kill location, or vice versa. Reply with your _quests.yml_ file in a pastebin should this issue persist.
