### ISSUE TITLE
Branching Quests

### ISSUE THREAD

**Issue by Attila144** [PikaMug/Quests#1776]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests version 4.0.5-b246

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

So I tried to make a quests that branches off other quests but once I have done that I have ran into a problem. this is what my console has to show.
https://pastebin.com/BXxSBdEF
I tried to branch From custom1 to custom2 and it will not work for some reason which is odd because it used to work back then.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

https://pastebin.com/4yjCKKEF

My server is a Spigot server and the version is 1.16.5

**Comment by Attila144** [comment]
I have found a resolve which was not to add colour code to the quest names at the start (example: When you start to create the quest it will tell you to give it a name and I gave it a colour code, &aQuestNameInsert)

**Comment by PikaMug** [comment]
This should be effectively resolved by 9b402c28bf9fc084ea54c6ab490a3702c0bd5729
