### ISSUE TITLE
No action executed when failing due to conditions or /quests quit

### ISSUE THREAD

**Issue by FrankSchepers24** [PikaMug/Quests#1777]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.5-b246

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When people quit the quest using /quests quit {quest} they don't get the standard "Quest failed" action, nothing happens. (except leaving the quest). The same thing happens when people fail the quest due to not meeting a condition.

So there is two possible fixes:
- Add an action variable in the stages that applies when people quit using either of these two options
- Make it so that when "/quests quit" is performed, or when people fail it due to conditions, they get the "fail" action applied on them.

To me personally, the latter seems the easiest. But either works. 😄 

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
-

**Comment by PikaMug** [comment]
By definition, quitting is not the same as failing - you may disable quitting under `Edit Options -> Allow quitting during quest` in the quests editor. As for conditions, I'll look into it.
