### ISSUE TITLE
Commands on rewards won't work (1.17.1 - 4.0.6)

### ISSUE THREAD

**Issue by WhiteFrost06** [PikaMug/Quests#1778]
**What is your Quests version / build number (do _not_ say "latest")?**

4.0.6

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

I can't add some commands on my rewards's quests because the button (the command block by the way) is not working. Is it a compatibility problem or something? I hope you will fix it in next patchs.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by WhiteFrost06** [comment]
PS: Now I constated that the save button is not work too. So I can't make new quests! Plz help! Thanks.

**Comment by DeadlykillOfficial** [comment]
This ticket will most likely be tagged as invalid due to not enough information provided

**Comment by WhiteFrost06** [comment]
Wait wait wait, who are you? You're not Piky? Thanks.

**Comment by DeadlykillOfficial** [comment]
Sure thing. Good luck

**Comment by PikaMug** [comment]
> the button (the command block by the way)

There is nothing like this within Quests to my knowledge. Perhaps you're using QuestsGUI, in which case this is not the correct place to report issues. See https://browsit.gitbook.io/questsgui/faq#where-can-i-get-support-for-questsgui
