### ISSUE TITLE
Slimefun Functionality Causing Console Error

### ISSUE THREAD

**Issue by Azakaturan** [PikaMug/Quests#1781]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When using the new slimefun functionality in defining items, quests generates an error in console when trying to load them.
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/RKqVpBVL - Item
https://pastebin.com/SBCmJ2iu - Quest
https://pastebin.com/43NEAQXt - Console Error

**Comment by PikaMug** [comment]
Wrong issue tracker. You want https://github.com/LMBishop/Quests
