### ISSUE TITLE
Self-null Adder

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1782]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.6 b257

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Once you enter the section Rewards it does self-add a null into Rewards#ListOverride and it tends to be adding a `null` on every enter of Rewards section
![image](https://user-images.githubusercontent.com/12415714/132545937-5f402963-3be7-469a-b7e5-166705fd78a1.png)

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
No Quest preview required for this.

**Comment by DeadlykillOfficial** [comment]
Add-on. It ignores 'clear' chat execution as well
![image](https://user-images.githubusercontent.com/12415714/132546153-38211b25-62cb-45ee-a796-ea5759f46374.png)
Instead it adds it on top of it

**Comment by PikaMug** [comment]
Use https://ci.codemc.io/job/PikaMug/job/Quests/258/
