### ISSUE TITLE
NPCs Cannot Give Quests in 4.0.7

### ISSUE THREAD

**Issue by mercurialmusic** [PikaMug/Quests#1791]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.7 (release) and Citizens 2.0.28.6 on git-Paper-263 (MC: 1.17.1).

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Ever since the update to 4.0.7, quests can no longer be given through an NPC. The plugin loads without error, no errors are shown in console, and NPCs will show their quest in the GUI when clicked, but clicking the quest itself does nothing. Quests can still be given and completed through admin commands.

At first I thought this was something I might have missed in the changelog but I see a few reporting the same on the Spigot discussion page.

**Comment by PikaMug** [comment]
Thanks for the report. Does this still happen with https://ci.codemc.io/job/PikaMug/job/Quests/264/ ?

**Comment by mercurialmusic** [comment]
Yes, that did it! Thanks!
