### ISSUE TITLE
NPCs can't accept the item

### ISSUE THREAD

**Issue by jeffry1829** [PikaMug/Quests#1793]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.7-b259
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
No error now.
However, this error shows up occasionally: (for example, after I reload the quests)
![image](https://user-images.githubusercontent.com/6897769/134126254-232e198a-3459-4eae-a2b5-6d22aec25292.png)

Main problem:
![image](https://user-images.githubusercontent.com/6897769/134125726-77faccf1-32bd-44fb-bfca-4a0793f9c50c.png)
I hold 64 sea_lanterns, and right-click the NPC, it says:
![image](https://user-images.githubusercontent.com/6897769/134125973-439c65cd-ea4e-47ea-934c-282a0f44727e.png)

Thank you!

**Comment by PikaMug** [comment]
Please provide the example quest as a pastebin, per the issue template.

You may also wish to try the latest Jenkins build https://ci.codemc.io/job/PikaMug/job/Quests/
