### ISSUE TITLE
NPC can't accept item

### ISSUE THREAD

**Issue by jeffry1829** [PikaMug/Quests#1794]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.7 #264
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
![image](https://user-images.githubusercontent.com/6897769/134131160-38e16612-608d-41ec-9ec7-507f90bf8cc2.png)
I hold 64 sea_lanterns, and right-click the NPC, it says:
![image](https://user-images.githubusercontent.com/6897769/134131188-568391a5-95e1-41d6-a0a6-1b74b08cfe43.png)

Thank you!
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/gVe8P4LG

**Comment by jeffry1829** [comment]
SORRY, I didn't notice that I downloaded the latest version to the wrong folder.
The problem is solved now. Thank you!

**Comment by PikaMug** [comment]
Duplicate of #1793
