### ISSUE TITLE
Menu not responding to chat input

### ISSUE THREAD

**Issue by MrWobz** [PikaMug/Quests#1797]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.7.jar
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

After entering editor,  editor does not respond to input from chat. 
Numbers do not work, cant exit.

[12:25:18 INFO]: This server is running Paper version git-Paper-266 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d19cd7

Chat plugins,  Paper side:  Essentials Chat  /  Bungee side  : HuskChat

Plugin is installed on Paper/spigot server side only.
Able to progress further using the questsgui plugin but does not save.

Believe same/similar issue as per #1594 that the plugin isnt reading from chat correctly.

tried to use /say to continue and unfortunately still same issue.
Could we get the menu clickable as per worldguard region flags ?

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by PikaMug** [comment]
Thanks for the report. Quests does not officially support BungeeCord or BungeeChat at this time, but I'll leave this open pending a deeper look at that older ticket.

**Comment by PikaMug** [comment]
Confirmed that BungeeChat and HuskChat are not compatible and will close this in favor of the original ticket.
