### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Safarival** [PikaMug/Quests#1798]
Hello,

Plugin: https://www.spigotmc.org/resources/quests.3711/
Version of Quests: 4.0.7

When I do / quests or other command (except admin permissions) the command works even though I have no permissions and am not OP.

On the documentation it is however written that you need the permission "quests.quests" (This is an example but it is the same for all other commands)

Thanks

**Comment by PikaMug** [comment]
Those permissions are enabled by default. Simply disable them as desired using your permissions handler.
