### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by Safarival** [PikaMug/Quests#1799]
Hello,

Could you add the possibility to put different quests in different categories please?

**What does your feature do?**

This would allow quests to be created for different worlds or different ranks.

**How would people use it?**

Just put a feature in quests.yml to choose the category of the quest.
Example:
  default1:
    name: 'Iron Miner'
    categoty: vip

also add a placeholders for it
Example: %quests_player_completed_quest_[categoryname]_amount%
This placeholder displays the number of quests validated in the defined category

Thank you

**Comment by DeadlykillOfficial** [comment]
You can use Requirements and use Permission requirement to split them up.

**Comment by DeadlykillOfficial** [comment]
Feel free to submit PR if you think it's much easier this way.
There is already a solution available.

**Comment by Safarival** [comment]
The idea of ​​giving a category for a specific grade was an example, plus my grades don't pay with irl money so I don't have a problem with that.

**Comment by DeadlykillOfficial** [comment]
Either way there is a solution to the category question you can easily use permissions to sort quests out by permission requirement as for.
It sounds like a nice to have such leader board placeholder tho. I just assume it would never be added as it requires significant recode of Quests plugin and currently there is more important matter in Developer task list that such feature. Either way I guess we shall wait both to see what his reply will be
