### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by paolosasso** [PikaMug/Quests#1801]
**What is your Quests version / build number (2.6)?**

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
It gives me this error [14:30:42 ERROR]: Could not pass event PlayerMoveEvent to Quests v2.6
java.lang.NullPointerException: null

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by paolosasso** [comment]
it is spamming it

**Comment by DeadlykillOfficial** [comment]
You are several years behind in Quests Updates.
The only supported Quests it's 4.0.7 b266 at this moment.

**Comment by paolosasso** [comment]
Do you need to redo the quests?

Il sab 25 set 2021, 14:45 Deadlykill ***@***.***> ha scritto:

**Comment by DeadlykillOfficial** [comment]
When updating from 5 Years old version. Most likely you would have to - yes.
It is your responsibility to keep your server up to date, and being 5 years behind in builds it is totally your fault i must say.

**Comment by paolosasso** [comment]
If I update version from version, you can convert them?

Il sab 25 set 2021, 14:53 Deadlykill ***@***.***> ha scritto:

**Comment by DeadlykillOfficial** [comment]
No, you have to do it yourself.

**Comment by paolosasso** [comment]
Ok, thanks for the clarification.

Il sab 25 set 2021, 14:55 Deadlykill ***@***.***> ha scritto:

**Comment by PikaMug** [comment]
Please note there is legacy documentation if you intend to upgrade - https://github.com/PikaMug/Quests/wiki/Ye-Ol'-Legacy-Documentation
