### ISSUE TITLE
Animal Breed Quests Objective

### ISSUE THREAD

**Issue by MeepTortoise** [PikaMug/Quests#1802]
**What does your feature do?**
Allows you to make quests that have objectives of breeding animals to complete the quest. Can set which animals that you need to breed and how many times you have to breed them.

**How would people use it?**
For farming quests or animal caretaking quests.

**Comment by PikaMug** [comment]
Unfortunately, the Bukkit API doesn't provide a way to know whom the breeder is. Perhaps a module could be written which keeps track of the last player to feed an animal before it breeds, in which case please see https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features

**Comment by DeadlykillOfficial** [comment]
![image](https://user-images.githubusercontent.com/12415714/134789335-5bc952ac-a301-4885-b8b9-c97ec63045d9.png)
In fact Spigot does provide EntityBreedEvent#getBreeder which can be instance of Player.

**Comment by PikaMug** [comment]
@DeadlykillOfficial Thanks for the correction. Does the EntityBreedEvent exist on MC 1.7.9?

**Comment by DeadlykillOfficial** [comment]
Ah right i forgot Quests it's looking for 1.7.9 - 1.17.1 compatibility.
This Event exist in 1.16.5 tho :D

**Comment by PikaMug** [comment]
No problem. If the project ever drops 1.7.9 support I'll reconsider this.
