### ISSUE TITLE
NPC that need to be spoken to say "no more quests avalible" after completing the quest.

### ISSUE THREAD

**Issue by MeepTortoise** [PikaMug/Quests#1804]
**What is your Quests version / build number (do _not_ say "latest")?**
4.07 b264

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Create a quest in which the objects are to talk to NPCs. After you complete that quest, those npc's will say "no more quests available" despite no quests starting at them.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by PikaMug** [comment]
Please update to Quests 4.0.8 and, if the issue still occurs, reply with an example quest using a pastebin.
