### ISSUE TITLE
Quest Condition "Own Permission" error on creating one

### ISSUE THREAD

**Issue by YazeSan** [PikaMug/Quests#1805]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 4.0.8
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Create a quest condition and add "own permission" condition. After saving the condition, this appears in the console (https://pastebin.com/F38MSXuZ) and the condition will not appear in the quests editor but still appears in the conditions.yml.
*It makes all quests malfunction after creating one in my main server.
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by PikaMug** [comment]
Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/268/
