### ISSUE TITLE
Optional Permission Check for every (ticks/seconds)

### ISSUE THREAD

**Issue by YazeSan** [PikaMug/Quests#1807]
**What does your feature do?**
Add an optional permission check for permission condition. I would like to be able to use
Luckperms temporary permission for quests. If the player's temp. permission runs out, quest will fail.
**How would people use it?**
Maybe it can be toggled in the condition editor in own permission, add an option for "check for every (seconds), null / 0 being 
the default to stop checking.

**Comment by PikaMug** [comment]
The current "own permission" condition already checks rather frequently for whether a player has a specific condition. I have no interest in handling timed permissions; there are a number of second timers within Quests you can use instead.

**Comment by YazeSan** [comment]
I just wanna state that I was just dumb suggesting this.  As you stated, it already checks for conditions. I just recently realized I was op-ed when i tried the permission timer thingy. No need for fix / additional features. Well, I appreciate the fast reply! Keep up the good work man
