### ISSUE TITLE
Quest Data Resetting

### ISSUE THREAD

**Issue by Grallow** [PikaMug/Quests#1811]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.5
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
So basically, player's data resets seemingly randomly.
I have had it happen to multiple players, some who have done like maybe 4 quests, and some that have done over 60 quests.
I don't know what causes it, I've never found the precise time that it resets.
I went into the player who's quest data reset, who was at 60+ quests completed and his data was completely wiped. I went into a backup of the server, got his data and replaced it with his current one and he got his progress back. Then sometime within a week he told me that his quest points had reset once again.
Other random players have had their quest data reset not even a week after starting on the server, some have had it reset 10 months after playing on the server.
The only questadmin command me and my admins have used is pretty much just /questadmin reload. We have restarted the server while players in the middle of quests, I'm not sure if this would disrupt anything.

I need to know what I can do going forward, what can I provide to help try and find the source of the issue?
My server is on 1.16.5, Java 16.
Please reply with information you'd need or what I can do to try and find the issue since it just seems to happen at random
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

**Comment by PikaMug** [comment]
Thanks for the report. Are you using YAML or MYSQL for player data?

**Comment by Grallow** [comment]
> 
> 
> Thanks for the report. Are you using YAML or MYSQL for player data?

Idk... The plugin has a data folder

**Comment by PikaMug** [comment]
I'll assume you're using YAML, but to check this look at the `storage-method.player-data` node in your _config.yml_ file.

**Comment by PikaMug** [comment]
https://pikamug.gitbook.io/quests/setup/configuration

**Comment by PikaMug** [comment]
Unable to replicate. Possibly related to #1707

**Comment by tygh78071388** [comment]
> 無法複製。可能與[#1707有關](https://github.com/PikaMug/Quests/issues/1707)

I have the same problem.

SERVER:
This server is running Paper version git-Paper-362 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 485d15f)
You are 26 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-353 (MC: 1.17.1)

BUNGEE:
This server is running Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:9d0ca6a:451 by md_5

QUEST:
Quests-4.1.2-b283

MYSQL:
![image](https://user-images.githubusercontent.com/28720564/143788654-05825031-d2e8-463e-8f2f-7a17da5b3e4e.png)

info:
(use mysql)

Quests-4.0.5 using it no problem.

but 4.0.8 ~ 4.1.2 There will be problems.  Player data will reset...OMG

I may have found the reason, a player during this time(2021-11-28-11.56.49~2021-11-28-15.56.49) reset occurred.

During this time he never switched servers(Bungee server), and not use quest plugin(take,delete).

Only admin use /questsadmin reload

There are log files and config files below.
[LOG.log](https://github.com/PikaMug/Quests/files/7614550/LOG.log)

Sorry my english not good
PLS help me....I'm going crazy

**Comment by tygh78071388** [comment]
Additional supplement:
spigot.yml 
save-user-cache-on-stop-only    i use true (Maybe this may also be the problem?)

**Comment by tygh78071388** [comment]
Additional supplement:
If in quests.yml No such quest number will not reset.

EX:
![image](https://user-images.githubusercontent.com/28720564/143789776-47adffe1-beb2-4f72-a7c9-2ac7d05373fd.png)

moon , one-1, one-2 not in quest.yml Player data is fine

custom1 custom2.. in quest.yml quests_player_completedquests will disappear

**Comment by PikaMug** [comment]
> Additional supplement: If in quests.yml No such quest number will not reset.

Feel free to share your quests.yml file (or at least those quests which you mentioned).

**Comment by tygh78071388** [comment]
[quests.log](https://github.com/PikaMug/Quests/files/7615071/quests.log)
lobby server quest, have custom1 custom2.... no one-1, one-2


[quests.log](https://github.com/PikaMug/Quests/files/7615074/quests.log)
pve server quest have one-1, one-2 no custom1 custom2




> > 附加補充：如果在 quests.yml 中沒有這樣的任務號不會重置。
> 
> 隨意分享您的 quests.yml 文件（或至少您提到的那些任務）。

**Comment by KoltaiArmy** [comment]
Hi!
I just found out that using /restart wasn't the source of my problem (or not the only one).
I have the same problem as described above. People are losing seemingly totally randomly all their quests progress. Is there a fix or any soultion to not delete the player's progresses randomly?

**Comment by PikaMug** [comment]
In order to fix this either I need to be able to replicate it, or have an error to work with. I've tried a few times to replicate, but since there aren't any specific steps to take and it seems to happen to both YAML and SQL users, we're currently at an impasse.

**Comment by KoltaiArmy** [comment]
One ultimate solution would be that if the plugin would be much more careful with deleting data. I assume its working with temporary loaded user datas, but a simple "if" condition would be cool something like a "dont regenerate the yaml file or delete 500 rows of mysql data, if they already exist, when the admin didn't even run the reset command" 

A simple check that the user already exists, and a much more careful user regeneration system would be a cool improvement.

**Comment by PikaMug** [comment]
I can assure you that there is nowhere in the code that intentionally deletes that much user data. In fact, the only line that knowingly deletes user data (this being on a _per-user_ basis), is when running the _/qa reset [player]_ command, as shown here:

https://github.com/PikaMug/Quests/blob/bd1f0b83899064ece98ee20ce463abd09f8044b3/main/src/main/java/me/blackvein/quests/listeners/CmdExecutor.java#L1342

That method is not called anywhere else, and applies to both YAML and SQL storage. It is not called when loading data, so I'm afraid your simple fix can't really be applied here.

On networks, it's possible that another server in the network might save an old copy of the data on top of  the newer changes. Of course I would have no way to test that theory or prevent it on my end.

**Comment by KoltaiArmy** [comment]
That sounds great, but still, we have only 1 server, it is running in only one session, and still players are losing all their progress totally randomly. I still assume it has something to do with **/questadmin reload** command, but the whole process looks totally random.

And as I can see I'm not the only one having this problem. So if not a fixed version, but a debug version would be cool, so we could track the problem, and why it is resetting randomly the users.

**Comment by MrShiluk33** [comment]
I got the same issue in my server. The only person at the moment who got his quests reseted (on more than 700 players) managed to duplicate his Quest Book so maybe it is something to orientate for that issue.

**Comment by PikaMug** [comment]
The working theory is that _/qa reload_ was not saving player data fast enough for it to be properly loaded. This build will attempt to resolve this, but must be tested. As always, backup your files before using experimental versions of Quests.
https://ci.codemc.io/job/PikaMug/job/Quests/288/

If this does not resolve the issue, reply below and/or follow the [SpigotMC thread](https://www.spigotmc.org/threads/open-eliminate-a-bug.538251/).
