### ISSUE TITLE
[sql/yml]Submit progress behaving strange (counting)

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1821]
**What is your Quests version / build number (do _not_ say "latest")?**
#275
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
if a quest have to submit a item more than 64, and the item in your hand are unstacked into different slot, then submit it, the counting system of quest will count more than submitted.

1. make a quest with submit item progress >64
https://paste.gg/p/anonymous/363828e412954260a0f1f6ecb7c425c1
2. take the quest
3. the quest require submit oak log 64 64 64
4. place oak log in your hand like, 16 8 8
5. right click the quest with anyone of the 8 oak log, two of the 8 will be taken
6. then right click the 16
7. the quests system say submitted 24 24 , but instead you only have 32 item

*note, i have tested this in mysql and yaml storage mode, both can reproduce

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://paste.gg/p/anonymous/363828e412954260a0f1f6ecb7c425c1

video:
https://youtu.be/0xUuvzPMdVw

**Comment by hkkongou** [comment]
> Related to #1753

update, #1792 problem still exist for item delivery, which will cause players submit progress to be stuck and cannot submit more items, or the quest system will think that the item trying to submit is incorrect.

**Comment by PikaMug** [comment]
@hkkongou https://ci.codemc.io/job/PikaMug/job/Quests/279/
