### ISSUE TITLE
Enchanting books in quests dosn't count

### ISSUE THREAD

**Issue by Sl4sh3z** [PikaMug/Quests#1825]
**What is your Quests version / build number (do _not_ say "latest")?**
4.1.1

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I've created a quest where a player had to enchant a book to "Sharpness I". However after enchanting the book with sharpness I in the enchantment table, it dosn't get marked as "done" in the quest. 

For the quest I used the option "enchant object" where I selected an enchanted book with sharpness I. That failed, as I explained above. After that I tried it with a normal book and choosed an enchantment (Damage All I) from the build in menu through "add enchantment". This also wasn't working. 
At the end I once again selected an already enchanted book with "Sharpness I", but this time also choosed "Damaga All I" through "add enchantment". Once again, it wasn't working.

Is there any way in the current version to let other players enchant books in a quest with the enchantment table?

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
This is the example that I used at the beginning, before taking a deeper look into the issue and testing around. As I've explained I selected an enchanted book with "Sharpness I" under "items to enchant".

quests:
custom001:
    name: Test
    ask-message: Test
    finish-message: Test
    npc-giver-id: 1
    requirements:
      quests:
    stages:
      ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: BOOK
            amount: 46
          - ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: BOOKSHELF
            amount: 15
          complete-message: Verzaubere nun das übrig gebliebene Buch auf Schärfe 1
            und bringe es anschließend dem Auftraggeber, um die Quest abzuschließen.
        '2':
          items-to-enchant:
          - ==: org.bukkit.inventory.ItemStack
            v: 2730
            type: ENCHANTED_BOOK
            meta:
              ==: ItemMeta
              meta-type: ENCHANTED
              stored-enchants:
                DAMAGE_ALL: 1
          npc-ids-to-talk-to:
          - 17
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: EXPERIENCE_BOTTLE
        amount: 21
      money: 3000
      quest-points: 1
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false

**Comment by PikaMug** [comment]
@Sl4sh3z Thanks for the report. Please try https://ci.codemc.io/job/PikaMug/job/Quests/278/
