### ISSUE TITLE
[sql]Item submit stage detection problem

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1830]
**What is your Quests version / build number (do _not_ say "latest")?**
`# 278`
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

for any quest will item submit stage, if a player too a quest, the relogin the server, his stage progress counting is freezed

similar to issue #1753
but this issue much bigger because #1753 only have problem if the item submitted reach 64, but this time, just after relogin, the quests does not detect item submitting to npc on click.

similar to #1792 but that time only have issue to mob killing

1. use sql
2. make a quest to submit item ~~with more than 64~~, make sure name and lore of the item is changed so that the item is non vanilla
3. take the quest
4. leave server with out submit anything
5. join server
6. you cannot submit the item.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://paste.gg/p/anonymous/df38c95bc17c4460a894b4e1c5b00c10

**Comment by PikaMug** [comment]
I wasn't able to replicate this. Could you please provide an example quest from quests.yml using a pastebin?

**Comment by hkkongou** [comment]
> I wasn't able to replicate this. Could you please provide an example quest from quests.yml using a pastebin?

here:
https://paste.gg/p/anonymous/df38c95bc17c4460a894b4e1c5b00c10

i also record a video to reproduce the bug
https://youtu.be/DWAolpZhd18

item in video for testing.
![image](https://user-images.githubusercontent.com/61608872/140716150-ed71171e-d770-4a6e-a6fe-17a277942b1d.png)

test with SQL storage method

**Comment by PikaMug** [comment]
@hkkongou https://ci.codemc.io/job/PikaMug/job/Quests/280/

**Comment by hkkongou** [comment]
checked, it work, thank you so much
