### ISSUE TITLE
Quest progress is not shared even if you have a party.

### ISSUE THREAD

**Issue by EyatMC** [PikaMug/Quests#1833]
**What is your Quests version / build number (do _not_ say "latest")?**
Quest : 4.1.2-b283
Party : https://www.spigotmc.org/resources/proskillapi-parties.96932/

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
I am using the party plugin.
I received the same quest as a party member, and the progress is not shared.

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/X98ntaCw

**Comment by PikaMug** [comment]
The plugin you linked is not supported. Use https://github.com/AlessioDP/Parties
