### ISSUE TITLE
Condition Message when accepting Quest

### ISSUE THREAD

**Issue by Back1tUp** [PikaMug/Quests#1835]
I had my fair share with Quests Plugin and I ended up needing to have a placeholder as a condition on couple of quests. My problem is that when the player accepts those quests, there is a big "Conditions message" showing the exact name of the placeholder and everything. I'd like to hide that message but I don't seem to find a way to do that. Any suggestions? Something that I might missed?

**Comment by PikaMug** [comment]
Would you might sharing the exact message? Typically, there needs to be a way to inform the player of the condition, but maybe we can adjust the formatting.

**Comment by Back1tUp** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/36410223/143968025-22508760-891c-4dd6-b9e7-b09895bc084f.png)

So this is what the user sees when he/she accepts the quest. I'd want to be able to hide this completely but a simple rename would be good enough as well.

**Comment by PikaMug** [comment]
Addressed in e68a8858e80b6624d6f87652d3e4da51b7b5e3a5

Condition text will not be shown if a stage details list override message is set in the Quests Editor.
