### ISSUE TITLE
[SQL]cooldown of quest is reset after relogin to server (only some players)

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1836]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.1.1#280

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**

Quest can be configured to have cooldown after players finished their quest. 

In my server, some players(~10% of my players) will have their quest cooldown got reset after they re-login to the server. Not all players can reproduce this issue, but for people that can reproduce this issue, they can reproduce the cooldown reset issue by relogin at any time.

So for players having a quest that need to wait 24hrs to do again, they have to stay inside the server 24 hours after login to do it, if they log off and come back, the count down reset back to 24 hours.

I haven't try in YML storage mode, but i have tried to restart server, this issue appear for a long time more than a month but i still cannot figure out so i report it here.

Video from player reproducing this issue in my server
https://www.youtube.com/watch?v=b7wGSS9mOKA&feature=youtu.be

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Quests.yml , the following is the quests shown in the video

A quests that can get wither skeleton spawner after killing 800 wither skeleton, reset every 5 days
https://paste.gg/p/anonymous/aeea36378bc94e5ca723a3f7ae868a85

**Comment by hkkongou** [comment]
player also report that daily quest CD is also reseted after day switch
following code is used
```
    planner:
      start: 27:1:2020:0:0:0:Asia/Hong_Kong
      end: 27:1:2020:23:59:59:Asia/Hong_Kong
      repeat: 86400
      cooldown: 86400
      override: true
```


https://youtu.be/87k45KciENg


the quest is set to be repeatable after 23:59:59 everyday
like the above cooldown one.

the cooldown always exist..

do you want to check check my mysql database data? i can export one

**Comment by PikaMug** [comment]
In the video you provided, the player uses a command to switch to another server, then back again. Does the issue still occur if they disconnect from the network entirely, then join again?

**Comment by hkkongou** [comment]
> In the video you provided, the player uses a command to switch to another server, then back again. Does the issue still occur if they disconnect from the network entirely, then join again?

yeah , the second video provided >> https://youtu.be/87k45KciENg 
is disconnect from network entirely

**Comment by PikaMug** [comment]
Thanks, sorry for overlooking that second link.

I've just attempted to recreate this on a server using SQL, but without success. I tried the example quest from your initial report, as well as modifying it with the planner details from your second post. Whether switching worlds or logging out/in, the cooldown continued working as expected. Perhaps the servers in your network are on different timezones or have their system time out of sync? For now, there doesn't seem to be much I can do without knowing the conditions under which this problem occurs.

**Comment by hkkongou** [comment]
> Thanks, sorry for overlooking that second link.
> 
> I've just attempted to recreate this on a server using SQL, but without success. I tried the example quest from your initial report, as well as modifying it with the planner details from your second post. Whether switching worlds or logging out/in, the cooldown continued working as expected. Perhaps the servers in your network are on different timezones or have their system time out of sync? For now, there doesn't seem to be much I can do without knowing the conditions under which this problem occurs.

I don't know how to reproduce too

But I the SQL database and the server are running on same dedicated computer,
In my server network, have 2 ubuntu computer, both of them have same time zone. There are server not hosting at the same computer as database, but in the video, the server involved is the same computer as the database

**Comment by hkkongou** [comment]
i still don't know how to reproduce, however i found a way to "fix" this problem by player

This problem should be caused by some corrupted quests data in mysql database, my solution to help the player is to use ``/qa remove <quests>``  command to remove the only quests have this cooldown problem, and then the problem is solved.

Still don't know why this will happen (maybe a server crash, or quests converter exception since i should be the first group of people to use qs converter)
At least, remove the progress and tell the player redo again, the cooldown works normal again.

**Comment by PikaMug** [comment]
@hkkongou I'd like you to test the following in your Bungeecord environment with MySQL enabled.

For your Spigot/Paper servers: https://ci.codemc.io/job/PikaMug/job/Quests/305/artifact/dist/target/Quests-4.2.2.jar
on your Bungeecord server: https://ci.codemc.io/job/PikaMug/job/Quests/305/artifact/bungee/target/Quests-Bungee-4.2.2.jar

**Comment by hkkongou** [comment]
> @hkkongou I'd like you to test the following in your Bungeecord environment with MySQL enabled.
> 
> For your Spigot/Paper servers: https://ci.codemc.io/job/PikaMug/job/Quests/305/artifact/dist/target/Quests-4.2.2.jar For your Bungeecord server: https://ci.codemc.io/job/PikaMug/job/Quests/305/artifact/bungee/target/Quests-Bungee-4.2.2.jar

Is there a check list for the test?

For this issue, my player is still experience with 303 build , a few days ago, the same person as before. But I cannot find the cause of this problem. So I may not be able to reproduce this problem in my dev server first to have a control test, and verify this new build can fix the problem.

**Comment by hkkongou** [comment]
> @hkkongou I'd like you to test the following in your Bungeecord environment with MySQL enabled.
> 
> For your Spigot/Paper servers: https://ci.codemc.io/job/PikaMug/job/Quests/305/artifact/dist/target/Quests-4.2.2.jar For your Bungeecord server: https://ci.codemc.io/job/PikaMug/job/Quests/305/artifact/bungee/target/Quests-Bungee-4.2.2.jar

oh btw, what is quests bungee do? how to use it? seems like is a new thing
