### ISSUE TITLE
Quests deleted themselves 

### ISSUE THREAD

**Issue by Slothsc** [PikaMug/Quests#1837]
Hi, so we’ve been having this issue with our server for a very long time where we will have a perfectly functioning quests that suddenly just disappear from the list having deleted themselves without anyone ever touching them. It’s been an issue we’ve had for quite a while we’re functioning quest that I’ve never had issues spontaneously delete themselves and I’m wondering if anyone else has had this issue or if anyone has any fix because I’m very sick of remaking quests multiple times because they delete them selves without anyone touching them or without them having had any problems before they disappear

**Comment by PikaMug** [comment]
Quests version / build number? Do not say "latest".

**Comment by Slothsc** [comment]
4.0.0 rc.4-b191

**Comment by PikaMug** [comment]
Update to Quests 4.1.2 and, if the issue persists, create a new ticket.
https://github.com/PikaMug/Quests#download

**Comment by Slothsc** [comment]
What mc version  is that for. Will it work on 1.16.4?

**Comment by PikaMug** [comment]
> Will it work on 1.16.4?

Yes.
