### ISSUE TITLE
Quests not returning progress

### ISSUE THREAD

**Issue by Ste4lth7722** [PikaMug/Quests#1841]
**What is your Quests version / build number (do _not_ say "latest")?**
4.1.2
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When attempting to complete a quest, the /quest command does not return the quest progress for the current objective, e.g. blocks broken. Apparently it could be due to LocaleLib, but I'm not expert so I have no idea.
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/sMM6MheR

**Comment by PikaMug** [comment]
Thanks for the report. What version of Minecraft are you using?

**Comment by Ste4lth7722** [comment]
My version of Minecraft is 1.18 (server running on paper). And okay, I will try to remove the spaces in both of those.

**Comment by JetString** [comment]
No objectives are being shown to players in MC 1.18 with your Last build (#285), 
In console the following error is shown:

[16:07:18 ERROR]: [LocaleLib] Unable to query Material:

For every material and block connected to quests, e.g.: rewards, blocks to break, and items/blocks to hand in.

**Comment by JetString** [comment]
quests do however work. I tested it and when you do break blocks for example once you have the amount of blocks broken the quest stage will complete, however again, no further objectives are being shown (second stage in this case handing in the items at the NPC) was not shown to player, but when you hand in the quest completes.

**Comment by PikaMug** [comment]
Thanks for chiming in. A temporary fix for this would be setting `translate-names: false` in the _config.yml_ file.

**Comment by Ste4lth7722** [comment]
Thanks, this worked and fixed the problem.
