### ISSUE TITLE
Progress between playes with the same quest active doesn't share

### ISSUE THREAD

**Issue by ItsYuriil** [PikaMug/Quests#1842]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.1.2 with Citizens-2.0.29-b2416
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
First of all, I'm using spigot 1.18-R0.1 
I'm trying to share quests progress  with other plsyers, such as if one player kills one specified entity, its progress share.
It seems the sharing conditions (Altough I've tried with all type of settings, ojective only, stage only, everything) it stills doesn't share with other players with the same quest. 
It turns out that it isnt only with npcs, even the "Go to a location" ojective doesnt share. All I've tried doesnt share between players, even if one completes the quest it doesnt finish for the rest of them.
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/vHAYb48s

**Comment by DeadlykillOfficial** [comment]
Do you have Parties Plugin installed?

**Comment by ItsYuriil** [comment]
> Do you have Parties Plugin installed?

I don't, but I have it disabled while doing it (either way it didnt work)

**Comment by DeadlykillOfficial** [comment]
You need the Parties plugin in order to share progress.

**Comment by DeadlykillOfficial** [comment]
Sharing only works for players that are in the same party through Parties Plugin made by AlessioDP

**Comment by ItsYuriil** [comment]
Is it compulsory? My server is running tight on capacity

**Comment by DeadlykillOfficial** [comment]
Without Parties. You cannot share progress and every Quest it's per player

**Comment by ItsYuriil** [comment]
Alright, thanks for the info, maybe it could be written in the wiki that you need it in order to share progress

**Comment by DeadlykillOfficial** [comment]
![image](https://user-images.githubusercontent.com/12415714/144940631-8644280d-cdd3-4368-9240-303e81706a26.png)

It is written

**Comment by ItsYuriil** [comment]
> ![image](https://user-images.githubusercontent.com/12415714/144940631-8644280d-cdd3-4368-9240-303e81706a26.png)
> 
> It is written

I know, what I meant was it sould be written that without it, you cant share progress at all, making all options useless

**Comment by DeadlykillOfficial** [comment]
I mean it makes sense that it would not work.
How would the plugin otherwise know with whom to share Quest progress.

**Comment by ItsYuriil** [comment]
Maybe like using global objectives? Anyways I was thinking of adding the Parties plugin either way

**Comment by DeadlykillOfficial** [comment]
Global objectives makes no sense. Because in public servers. Not all players play together so there is no point of increasing progress for someone you do not play with. But yeah either Parties or DungeonXL plugin is required in order to have any Party System that would allow sharing of Quests progress.

**Comment by ItsYuriil** [comment]
That solved the Issue. My bad for thinking it had support for sharing progress without any external plugins
