### ISSUE TITLE
PlaceholderAPI failed to load class

### ISSUE THREAD

**Issue by Strovo** [PikaMug/Quests#1844]
**What is your Quests version / build number (do _not_ say "latest")?**
4.1.3

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
the error occurs when downloading the Placeholder expansion 

https://pastebin.com/k13e9zfY

**Comment by PikaMug** [comment]
I'll look into this, but please open future such issues at https://github.com/PikaMug/PlaceholderExpansion-Quests/issues

**Comment by PikaMug** [comment]
Either you have the wrong Quests plugin installed or Quests failed load.
