### ISSUE TITLE
Add a command to write in chat when edit quests

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/Quests#1848]
**What does your feature do?**

I would like to talk with my friends when i edit or make a quests. But i can't because the chat is using by quests so i need a command

**How would people use it?**
(Sorry i don't put < around message and player)

/questschat <message
# aliases:
 /qc <message
 /qchat <message
 /questsc <message
 
 # Chat 
&e[&bQuests&e] <player <&bmessage

# Screenshots
![image](https://user-images.githubusercontent.com/74351200/146490688-ada936e4-6266-4afb-8c83-eef13c0aad22.png)

![image](https://user-images.githubusercontent.com/74351200/146490406-fb5e57b5-faae-4f55-9454-50330bab726f.png)

(I use the broadcast but it's not great)

**Comment by PikaMug** [comment]
Use the _/say [message]_ command.

**Comment by Beubeux74** [comment]
I tried it and I have a little suggestion to make, just add a space between the prefix and the nickname (queteur and beubeux74)
 ![image](https://user-images.githubusercontent.com/74351200/146648887-efd1fdbe-f8f6-4191-9974-4ed1aa99b43f.png)

**Comment by PikaMug** [comment]
_/say_ is a built-in Minecraft command. There might be plugins out there which can modify its format, but that's outside the scope of Quests.
