### ISSUE TITLE
Parties setting not working

### ISSUE THREAD

**Issue by CyberZeta** [PikaMug/Quests#1850]
**What is your Quests version / build number (do _not_ say "latest")?**
4.1.3-b287

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
Alright, so I was trying to make my quests share-able through the party, but when I enable the setting it doesn't work
It was working fine before when I enabled it, but suddenly it doesn't work. There are no console errors or anything, I just enable it, t ry to complete the quest for my alt and it doesn't work at all

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
https://pastebin.com/7HL0bWLn

**Comment by PikaMug** [comment]
Which party plugin are you using? Any errors at startup?

**Comment by CyberZeta** [comment]
Im using this parties plugin: https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/
I have not seen any errors on start up, and I'm currently unable to check
The party sharing feature was working fine before but I disabled it, so I re-enabled it for all my quests and it appears to not be working all of the sudden

**Comment by PikaMug** [comment]
Thanks. Parties integration is per quest, so in what manner did you go about disabling it? Did you simply remove the Parties plugin?

**Comment by CyberZeta** [comment]
I disabled it by going into the individual quests settings

**Comment by PikaMug** [comment]
Are you using [Unite](https://www.spigotmc.org/resources/unite.95217/) as well? If so, remove it. If not, try it. If there's no improvement, we'll have to check your startup log.

**Comment by CyberZeta** [comment]
So after installing Unite, now im getting this error spammed: 
![image](https://user-images.githubusercontent.com/96308244/146642161-1cea02e7-04e0-4cab-a9c3-50e9e763b5a9.png)

**Comment by PikaMug** [comment]
It looks like Parties isn't loading properly. This is hard to confirm without seeing your startup log. Barring that, reaching out to the developer @AlessioDP might be best.
