### ISSUE TITLE
Handing in of Items stopped working

### ISSUE THREAD

**Issue by JetString** [PikaMug/Quests#1851]
**What is your Quests version / build number (do _not_ say "latest")?**
4.1.3  #287
**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
hand in any item/block in a stage is not possible.
It says there is a difference between the item names. Although they are the items in question.
(these quests worked already, they stopped working somewhat between last week and today)
**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**

https://pastebin.com/GtMBpDs1

**Comment by JetString** [comment]
no console errors btw.

**Comment by PikaMug** [comment]
Reported to be resolved on Discord.
