### ISSUE TITLE
Quests Warning

### ISSUE THREAD

**Issue by KhrysAK47** [PikaMug/Quests#1853]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.1.3.jar

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
The problem is the console warning which appears on startup or quest reload - https://pastebin.com/XqtgjXDR

**If applicable, can you provide an example quest from quests.yml _using a pastebin_?**
Not applicable

**Comment by DeadlykillOfficial** [comment]
It is because you are using unsupported Quests Module.
The mythicmobs module which you are using works only till 4.0.6. Then it is deprecated and no longer working.

**Comment by KhrysAK47** [comment]
> It is because you are using unsupported Quests Module. The mythicmobs module which you are using works only till 4.0.6. Then it is deprecated and no longer working.

So what can I do exactly?

**Comment by DeadlykillOfficial** [comment]
> > It is because you are using unsupported Quests Module. The mythicmobs module which you are using works only till 4.0.6. Then it is deprecated and no longer working.
> 
> So what can I do exactly?

Source: Wiki 
You can use the following module for Quests 4.0.6+ MythicMobs Kill Objectives: https://lectern.browsit.org/resources/resource/32-kill-mythic-mobs-multiplayer-improvement/
