### ISSUE TITLE
Event fired when Player completes Quest

### ISSUE THREAD

**Issue by IllegalNatrium** [PikaMug/Quests#1854]
Hello, I'm trying to use this API to synchronize two servers but maybe this is irrelevant, going straight to the point i'm searching a **Event that fires when a Player completes a Quest**. I've searched even in deep in the documentation but found nothing..

**Comment by DeadlykillOfficial** [comment]
https://github.com/PikaMug/Quests/tree/main/api%2Fsrc%2Fmain%2Fjava%2Fme%2Fblackvein%2Fquests%2Fevents%2Fquester

**Comment by PikaMug** [comment]
Specifically the QuesterPreCompleteQuestEvent and QuesterPostCompleteQuestEvent

Note that Quests does offer [MySQL support](https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Storage#mysql).
