### ISSUE TITLE
NullPointerException on disconnect

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1858]
### What is your Quests version / build number (do _not_ say "latest")?

quests 4.1.3 # 288 

### Describe the problem and how to replicate it.

when a player log of server, this error triggers
seems related to saving player data.

i am using mysql mode

### Any console errors to share?

```shell
https://paste.denizenscript.com/View/91834
```

**Comment by PikaMug** [comment]
This is likely due to manual changes to your database.

Make sure that all rows of the `amount` column of the `_player_redoablequests` use integers (numbers) and is not NULL. Default value is 1.

**Comment by hkkongou** [comment]
> This is likely due to manual changes to your database.
> 
> Make sure that all rows of the `amount` column of the `_player_redoablequests` table use integers (numbers) and is not NULL. Default value is 1.

i know i have been talking about migration of database these day but so far i haven't been actually migrating or merging two database using any of the methods.

and
i have searched the player_redoablequests, none of the value is null

![image](https://user-images.githubusercontent.com/61608872/148339166-4f41d23c-3297-427b-9ff5-75028459c38c.png)

**Comment by PikaMug** [comment]
Here's the line your error stems from:
https://github.com/PikaMug/Quests/blob/de50d3aa0815c715517ad3419b753ef8060f825c/api/src/main/java/me/blackvein/quests/storage/implementation/sql/SqlStorage.java#L331

I suppose the other possibility is one of the `questid` in either that table or `_player_completedquests` could reference a non-existant quest. I'll add a null check and output some debug information and get back to you.

**Comment by PikaMug** [comment]
@hkkongou Please try https://ci.codemc.io/job/PikaMug/job/Quests/289/ and let me know what sort of console output you get.

**Comment by hkkongou** [comment]
> @hkkongou Please try https://ci.codemc.io/job/PikaMug/job/Quests/289/ and let me know what sort of console output you get.

got these new error, not sure related or not

![image](https://user-images.githubusercontent.com/61608872/148508900-f9489493-ebfe-4b6b-8af0-c3dc30083596.png)

![image](https://user-images.githubusercontent.com/61608872/148508943-82cae0b7-c675-4935-9da1-f0097c038916.png)

**Comment by PikaMug** [comment]
Not related. Please heed the instructions for existing MySQL tables at https://www.spigotmc.org/resources/quests.3711/update?update=428067

**Comment by hkkongou** [comment]
> Not related. Please heed the instructions for existing MySQL tables at https://www.spigotmc.org/resources/quests.3711/update?update=428067

just saw an error when player are force finished
jar is 289 and have done the type change

![image](https://user-images.githubusercontent.com/61608872/149295117-08dd6055-9bb1-42a0-82b4-a7159aed9f97.png)

**Comment by PikaMug** [comment]
Thanks. Can I see the quest named in the exception?

**Comment by hkkongou** [comment]
> Thanks. Can I see the quest named in the exception?

sure
it is 

quests
https://paste.denizenscript.com/View/92170

action
https://paste.denizenscript.com/View/92171

**Comment by hkkongou** [comment]
also some other errors..

![image](https://user-images.githubusercontent.com/61608872/149452564-7c433c2a-4803-4dae-a94d-75201f22f36c.png)

**Comment by PikaMug** [comment]
> quests https://paste.denizenscript.com/View/92170

Why does stage 1 have a delay of 0?

> also some other errors..

Did you adjust your mobs_killed column? https://www.spigotmc.org/resources/quests.3711/update?update=428067

**Comment by hkkongou** [comment]
> > quests https://paste.denizenscript.com/View/92170
> 
> Why does stage 1 have a delay of 0?
> 
> > also some other errors..
> 
> Did you adjust your mobs_killed column? https://www.spigotmc.org/resources/quests.3711/update?update=428067

Idk
Maybe typo of mine
Is that the cause of error?
If so I will remove the delay: 0


For the SQL, mobs_kill
Yes, all 4 of them adjusted from int to varchar when this build is used

**Comment by PikaMug** [comment]
There's a good chance it is. Let me know if removing it helps.

I'll look into the mob killed issue further.

**Comment by PikaMug** [comment]
Please use https://ci.codemc.io/job/PikaMug/job/Quests/290/ and create a new ticket if you need further assistance.
