### ISSUE TITLE
[mysql]Error occur during server crash

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1859]
### What is your Quests version / build number (do _not_ say "latest")?

4.1.3 #b289

### Describe the problem and how to replicate it.

crash a server (i don't know how)

### Any console errors to share?

```shell
full error
https://paste.denizenscript.com/View/91975
```

**Comment by PikaMug** [comment]
This is not an issue with Quests but with the connection to the MySQL database. One thing you can try is changing `storage-data.address` in _config.yml_ from "localhost" to the actual IP address of your database. You should also check that your MySQL max connections limit is not being exceeded. By default, Quests will use 10 connections per server. If you have lots of plugins connecting to the same server, you will need to increase this limit.

**Comment by hkkongou** [comment]
> This is not an issue with Quests but with the connection to the MySQL database. One thing you can try is changing `storage-data.address` in _config.yml_ from "localhost" to the actual IP address of your database. You should also check that your MySQL max connections limit is not being exceeded. By default, Quests will use 10 connections per server. If you have lots of plugins connecting to the same server, you will need to increase this limit.

my database actually have 2000 max connection set all the time, is already 10 times more than default mysql limit , would it be enough 🤔🤔

**Comment by DeadlykillOfficial** [comment]
> > This is not an issue with Quests but with the connection to the MySQL database. One thing you can try is changing `storage-data.address` in _config.yml_ from "localhost" to the actual IP address of your database. You should also check that your MySQL max connections limit is not being exceeded. By default, Quests will use 10 connections per server. If you have lots of plugins connecting to the same server, you will need to increase this limit.
> 
> my database actually have 2000 max connection set all the time, is already 10 times more than default mysql limit , would it be enough 🤔🤔

You would have to monitor the MySQL Connection terminal and see how they react in there. Because PING may affect those things too.
