### ISSUE TITLE
Reach location quests don't work when a world resets

### ISSUE THREAD

**Issue by Alv5ro** [PikaMug/Quests#1860]
### What is your Quests version / build number (do _not_ say "latest")?

4.1.3-b286

### Describe the problem and how to replicate it.

I have a world that auto regenerates every 6 hours, so it deletes and copy pastes the original world as the same name as the previous generation of the world, i.e. I believe the UUID is identical. When this happens, Quests doesn't recognise that the world name is the same, and so it won't recognise when someone reaches a location set, and doesn't give them a reward once they've completed the mission.

### Any console errors to share?

```shell
None as it doesn't recognise that the player has actually reached the location.
```

### If applicable, can you provide an example quest from quests.yml?

```shell
#Scavenge is the name of the world and it doesn't change when the worlds 'reset'
        '1':
          locations-to-reach:
          - Scavenge 2531.0 255.0 2343.0
          reach-location-radii:
          - 4
          reach-location-names:
          - The Peaks of Scavenge
```

**Comment by PikaMug** [comment]
Either the plugin being used to regenerate the world isn't properly adding the world information back into the server's world list, or you simply haven't reached the location. I see the Y value is rather high. If that is indeed correct, try using a larger location radius.

**Comment by Alv5ro** [comment]
It's my own created plugin, I programmed it to output the multiverse delete, copy and paste commands. The Y coordinate is correct and it does give players a reward when they reach it (before the world 'resets').

This is the code that copy-pastes: https://www.toptal.com/developers/hastebin/exoyawimag.css
Do you think it could be the way multiverse handles the worlds?

**Comment by PikaMug** [comment]
@Alv5ro I would assume the _/mv clone_ command does not automatically register the world. However, this is a question for either the Multiverse developers or a help forum like SpigotMC.

**Comment by Alv5ro** [comment]
Thank you, I will look there. I appreciate the professional help and timely response rate!
