### ISSUE TITLE
"Maximum number of quests a given player can have at any time" could be upgradable

### ISSUE THREAD

**Issue by KoltaiArmy** [PikaMug/Quests#1864]
### What does your feature do?

So basically that would be a great feature if people could upgrade their "max-quests". 

### How would people use it?

For eg. if you could have only 5 quest, and then you buy an upgrade, then you can have 6 accepted quests at one time. 

This could be done with permissions, or with an upgrade system. It would be a great implementation for an RPG server.

**Comment by PikaMug** [comment]
While there is a `max-quests` setting in the configuration file, restricting individual players to a specific number of quests is generally done by estimating Quest Points and/or utilizing quest requirements. If this is still something you desire, consider enlisting third-party support https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features
