### ISSUE TITLE
[suggestion]confirmation for quit a quest

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1866]
### What does your feature do?

Allow players to quit a quest after typing an extra confirmation command.

This is made for QuestGUI, since QuestGUI support quit quest by pressing button, if players click button mistakenly, they will immediately quit a quest.

### How would people use it?

add ``/quests confirm`` or ``/qs confirm`` command
with setting in yml toggle this extra function(?)
when player type /quests quit xxxx , then player need to type ``/qs confirm`` to confirm the quit of a quests

for QuestGUI, just pop up a fixed confirmation 1x9 GUI that have 2 buttons, the confirm one hook to /qs confirm and the deny hook back to quest journal .

**Comment by PikaMug** [comment]
Thanks for your suggestion. I'll consider adding a confirmation prompt to the `/quests quit` command, so that such a GUI could appear when quitting a quest. This will probably tie into the `ask-confirmation` config setting.

**Comment by hkkongou** [comment]
> Thanks for your suggestion. I'll consider adding a confirmation prompt to the `/quests quit` command, so that such a GUI could appear when quitting a quest. This will probably tie into the `ask-confirmation` config setting.

plz do not tie into ``ask-confirmation`` , it is because i am disabling this ``ask-confirmation`` setting so that i can use external GUI to make quests accept button with other external function i want, without players typing yes/no
