### ISSUE TITLE
editor gui

### ISSUE THREAD

**Issue by Like178** [PikaMug/Quests#1869]
### What is your Quests version / build number (do _not_ say "latest")?

Quests 4.1.3

### Describe the problem and how to replicate it.

whenever I type in /quests editor it pops up with the regular quests GUI and only allows you to click on a preset quest, we cannot edit the quests in any way, dont know how to fix it

### Any console errors to share?

```shell
N/A
```

**Comment by PikaMug** [comment]
There is no inventory GUI included for the quests editor. If you would like one, consider installing [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/). If you need help with QuestsGUI, comment in the SpigotMC discussion thread or use its [support discord](https://discord.gg/zk4fWvJSuB).

**Comment by Like178** [comment]
that is not what I meant, sorry. the in game chat menu for editing quests where it gives you the options does not show up, instead it gives you the entire quest gui and allows you to start a quest

**Comment by PikaMug** [comment]
@PikaMug Can you share a screenshot of what happens after typing _/quests editor_?

**Comment by PikaMug** [comment]
@Like178 Can you share a screenshot of what happens after typing _/quests editor_?

**Comment by Like178** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/33073435/151488496-b1b0790d-0679-408e-98af-8b13c919a909.png)

**Comment by PikaMug** [comment]
@Like178 That's the wrong Quests plugin. This repository is for https://www.spigotmc.org/resources/quests.3711/

**Comment by Like178** [comment]
> @Like178 That's the wrong Quests plugin. This repository is for https://www.spigotmc.org/resources/quests.3711/

it is? I got here directly from that page and this is the only quests plugin I have in my server.

**Comment by PikaMug** [comment]
@Like178 Yes, another resource is conflicting. Possibly MMOCore.

**Comment by Like178** [comment]
I do not believe mmocore has a quests system though 

Sent from Yahoo Mail for iPhone


On Friday, January 28, 2022, 12:18 AM, PikaMug ***@***.***> wrote:




@Like178 Yes, another resource is conflicting. Possibly MMOCore.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PikaMug** [comment]
It does, and it uses the same command. You might be able to access the "right" Quests using the shorthand _/qs_ command.
