### ISSUE TITLE
[mysql][bug]stage progress is not saving fast enough so that player move to other mysql sync server will have progress loss

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1871]
### What is your Quests version / build number (do _not_ say "latest")?

Quests-4.1.3#290
paper 164 1.18.1

### Describe the problem and how to replicate it.

Youtube video:
https://youtu.be/S4_AiS5DNSE

found a problem for quests data not saving/ data loss.
in the video, i took a mining quests which need to mine 8 type of ores by breaking them, i finished to the stage 2, and then i go to another quests database synced server, my progress is gone.

step:
1. take a quests , for my case, is break block , alot
2. finish the stage
3. go to another server with have synced quests sql databse

i also tried with other things like custom modules or item delivery stage, they works fine seems like, but still have bug as the title say. The data is saved but have delay caused some data loss sometimes 50%~ , but for the block break above is 100% loss in my case. 

For the saving test, i tested by taking and finish a random delivery/custom module quests stage 1(lets say i am in server A), then immediately go to another database synced server(server B), sometimes, the stage stuck in stage 1 (server B) even i have finished stage one in another server (server A)

### Any console errors to share?

```shell
no error
```

### If applicable, can you provide an example quest from quests.yml?

```shell
quests in the video:
https://paste.denizenscript.com/View/92937

quests used to test stage saving( delivery/ custom)
https://paste.denizenscript.com/View/92938
https://paste.denizenscript.com/View/92939
```

**Comment by PikaMug** [comment]
As I recall stage progress is not saved unless the player logs out or someone uses _/qa reload_, so this would be expected behavior.

**Comment by hkkongou** [comment]
> As I recall stage progress is not saved unless the player logs out or someone uses _/qa reload_, so this would be expected behavior.

errr... but the impact is too much for some cases, the entire finished stage progress is gone even is finished, which is sad for players.
anyway to prevent?

**Comment by PikaMug** [comment]
At a glance it looks like we would want to call Quester#saveData somewhere in

https://github.com/PikaMug/Quests/blob/7eaedf079f18589975036b41f1e25c6d14f5d9cd/core/src/main/java/me/blackvein/quests/Quest.java#L305

This would of course need to be tested thoroughly but the plugin is currently undergoing some significant changes in preparation of the next major release so I can't guarantee I'll have time soon.

**Comment by hkkongou** [comment]
> At a glance it looks like we would want to call Quester#saveData somewhere in
> 
> https://github.com/PikaMug/Quests/blob/7eaedf079f18589975036b41f1e25c6d14f5d9cd/core/src/main/java/me/blackvein/quests/Quest.java#L305
> 
> This would of course need to be tested thoroughly but the plugin is currently undergoing some significant changes in preparation of the next major release so I can't guarantee I'll have time soon.

hi, i just remember something might be related.
mysql not syncing very fast should be a very command issue for plugin that need to be sync between servers, such as, MySQL playerdata bridge, it is almost 100% for server that use mysql sync to have this plugin.

There are plugin that sync instantly like marriagemaster because have partner inventory , but for mysqlplayerdatabridge, they have like a few mins also save/backup player data to database, but the most important part is that, it must safe correctly when player go offline from one sync server , fast enough ,and send data to another server , so that the item are transferred nicely. Mysql player databridge did it very well(although sometimes , a few player report item loss, but very rare).

I don't know how did their developer made it, but i am sure sometime must be able to done preventing data loss.

**Comment by PikaMug** [comment]
I'm not certain that speed is a concern for this particular issue, rather progress isn't saved when progressing stages at all. I've added this to the [roadmap for 4.2.1](https://github.com/PikaMug/Quests/projects/7#card-77347083) but again I need to find the time for testing.

It looks like the premium MySQL Player Data Bridge plugin offers integration with other resources. You might ask the developer if they would be willing to add a custom implementation for Quests. They would likely want to use https://github.com/PikaMug/Quests/tree/main/core/src/main/java/me/blackvein/quests/storage/implementation/custom

**Comment by PikaMug** [comment]
@hkkongou Had no issues in testing but still make sure to back up your server first.
https://ci.codemc.io/job/PikaMug/job/Quests/298/
