### ISSUE TITLE
Quest placeholders do not update properly without OP/ADMIN

### ISSUE THREAD

**Issue by NadeSwiiv** [PikaMug/Quests#1872]
### Where else have you looked for answers to this question?

Community Support / Quests Community Discord

### Share your question with as much detail as possible.

Hello,

I am using your quests plugin with PlaceholderAPI & PlaceholderExpansion-Quests addon. Together with a scoreboard plugin to visualize quest progress.

My issue is that the compass stops tracking the current quest every time I advance a stage.

Example:
**WITH OP/ADMIN,** while I advance stages:
Start of Quest: https://prnt.sc/26o7bx7 --------->>>> Next stage of quest: https://prnt.sc/26o7c8w (**Text works like intended**)

**WITHOUT OP/ADMIN**, while I advance stages:
Start of Quest: https://prnt.sc/26o7bx7 --------->>>> Next stage of quest: https://prnt.sc/26o7de3 (**Text does not work like intended**)

If I do /papi parse NadeSwiiv %quests_player_compass_quest_objectives%  I get no feedback when I use this as non-op, but I do have access to the command & the placeholder. It just returns value "null".

I also get this error in the console constantly:
![image](https://user-images.githubusercontent.com/19294814/152456553-7e7ee6db-c4c7-44ef-a04d-cd3b6faf6327.png)

I have already talked to PlaceholderAPI & 2 developers of the scoreboard plugin. Both say it has the be an issue with Quests or the Quests PAPI addon.

Could you please take a look and let me know?

Thanks alot!

Greetings,

Nade

**Comment by NadeSwiiv** [comment]
Just to calrify, it happens with every quest, not just 1 specific quest

**Comment by PikaMug** [comment]
Thanks for the report. Although you said it occurs with every quest, please provide at least one quest that you've replicated the issue on from your _quests.yml_ file using a service like Pastebin.

**Comment by NadeSwiiv** [comment]
https://pastebin.com/nd8j7Amx

**Comment by NadeSwiiv** [comment]
I really hope you can find a solution, because we really like the plugin :)

**Comment by NadeSwiiv** [comment]
And just to clarify, that quest I've posted fully works. The only thing that doesn't work is the tracking throug placeholderAPI, and it only doesn't work when the user is not OP.

**Comment by NadeSwiiv** [comment]
https://pastebin.com/stEaAW8i 

It also has the same issue with this quest, one of the most basic quests you can make

**Comment by NadeSwiiv** [comment]
https://github.com/PikaMug/PlaceholderExpansion-Quests/issues/7

This guy seems to have the same issue as me

**Comment by NadeSwiiv** [comment]
%quests_player_compass_quest_name%

%quests_player_compass_quest_objectives%

These are the placeholders I am using, they only advance with the stages when I am OP.

**Comment by PikaMug** [comment]
@NadeSwiiv I've released version 1.5 of the expansion which should address the console errors. Non-OP players must have the `quests.compass` permission. The other issues had to do with Quests itself and have been addressed in https://ci.codemc.io/job/PikaMug/job/Quests/295/

Note that development builds are experimental and backing up your server first is highly recommended.

**Comment by NadeSwiiv** [comment]
Seems to be working fine now & the error is gone!

Gonna rate 5 stars for your amazing support! 

Have a good day :)
