### ISSUE TITLE
gamerule sendCommandFeedback

### ISSUE THREAD

**Issue by Equimunity** [PikaMug/Quests#1875]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.0

### Describe the problem and how to replicate it.

When restarting the server with Quests plugin in, the gamerule sendCommandFeedback automatically gets set to false, whereas the default is true. This happens every time the server gets restarted, no matter how many other plugins are in. Issue stops when the plugin is removed. It does give a warning about custom objectives not being set, however the gamerule already got changed upon first adding the plugin (so before any quests were even created)

### Any console errors to share?

```shell
No errors, just this:[Sun, 6. Feb 2022 13:06:28 UTC INFO] Gamerule sendCommandFeedback is now set to: false
```

### If applicable, can you provide an example quest from quests.yml?

```shell
This is one of the quests we got a warning about, but again I don't think this is the reason
quests:
  custom1:
    name: Save Neighbelline
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          use-block-names:
          - glass_pane
          use-block-amounts:
          - 1
          locations-to-reach:
          - world -7914945.0 62.0 7582079.0
          reach-location-radii:
          - 2
          reach-location-names:
          - Inspection-zone
          start-message: '"Hmm.. Looks like a fire broke out, lets inspect further"'
          complete-message: '"Cow-ard seems to be a bit hungry but overal he''s fine"'
        '2': {}
```

**Comment by PikaMug** [comment]
There is already a way to disable this; toggle `disable-command-feedback` in your _config.yml_ file.
