### ISSUE TITLE
Can you add a license to your project?

### ISSUE THREAD

**Issue by kapuastudio** [PikaMug/Quests#1880]
### Where else have you looked for answers to this question?

I have looked through your github files and one is not present. 

### Share your question with as much detail as possible.

I would like to have a license added to the files so we are clear on which license this project and code fall under. Thank you for your time.

**Comment by PikaMug** [comment]
Thanks for your inquiry. Generally speaking, code without an explicit license is protected by copyright and is by default All Rights Reserved. If you have questions regarding the use of Quests in a specific application, please do not hesitate to ask.
