### ISSUE TITLE
Stage support multiple counter/repeated custom objective 

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1881]
### What does your feature do?

I am currently using  Kill Mythic Mobs (Multiplayer improvement) custom objective, link:
https://lectern.browsit.org/resources/resource/32-kill-mythic-mobs-multiplayer-improvement/

I would like to design quests stage that can count multiple type of mythicmobs kill into different corresponding counter.

However, the current limitation is that I can only make 1 custom objective in 1 stage, cannot repeat the same object. Seems like custom objective can only use 1 counter at a time.

I have asked Deadlykill, the author of the addon, here is his reply

![image](https://user-images.githubusercontent.com/61608872/153737996-b5ce07de-638b-457b-bd7f-66402c4c49ed.png)

I also noticed that custom_counts use varchar(100) instead of INT, so that, it is possible to make more than one counter, but so far, custom_count is only counting 1 only.

![image](https://user-images.githubusercontent.com/61608872/153738050-06475fd1-99f3-40b1-bdbe-a6bf9dd59a2a.png)

### How would people use it?

This can help people that use custom objective to have a much flexible way designing a quest.

Currently, if i want to count players to kill mythicmobs mob A x10, mythicmobs mob B x8 in same stage is impossible for the custom objective. i can only split in to 2 seperate stage, either finish mob A then go to B, or finish B then go to finish A.

**Comment by PikaMug** [comment]
Sorry for the late reply. This is done for consistency with other objectives; every stage can have only one objective of each type, even if it's technically possible. What I would consider, however, is a Pull Request to add MythicMobs integration to Quests. This could support different counters per mob type.
