### ISSUE TITLE
Close external chest GUI after each npc interact objective

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1882]
### What does your feature do?

I have added function to npc so that when players click on NPC, they will have a chest pop up windows from GUI system(i use deluxemenus and GUIPlus)

If i have a quests that need to deliver items or right click npc (maybe talk objective), it will also open the GUI , which is not good.

So my suggestion is that, after each objective, like, submit item, the quests system will send a close GUI function to close a external GUI.

### How would people use it?

add two config for people to set
1. enable close external chest inventory GUI function after npc click objective
2. change the delay time

* actually this function i have asked deadlykill to implement for its talk to NPC conversation custom modules and it work great, in his module, he added a 4 tick delay after each NPC click

**Comment by PikaMug** [comment]
This may not be desirable for all users, such as those that issue rewards through inventories. A custom plugin (using the event API) or the module you spoke of are good solutions here. One cleaner way I can think of adding this to Quests itself would be letting Actions be triggered by an objective update, at which point one could run a Denizen script to open/close an inventory. You could also request such functionality from [Depenizen](https://github.com/DenizenScript/Depenizen). Another might be the ability to create custom Actions/Conditions, which I thought there was an open ticket for but I can't find it. Anyway, I cannot consider this in the manner requested.
