### ISSUE TITLE
New Placeholders

### ISSUE THREAD

**Issue by Threshian** [PikaMug/Quests#1888]
### What does your feature do?

Hi, it would be great to add few new placeholders for peoples who make menu with quests placeholders.
All the following placeholders are based on 10 points equaling 1 level.

To know the level of the player : %quests_player_level%
To know the number of points missing before the next level : %quests_player_missing%
To know the actual number of points of the player : %quests_player_points% (Example: Progression : %quests_player_points%/10)

I don't know if a different placeholder is needed but %quests_player_points% could be use in progressbar.

### How would people use it?

Like i said in first paragraph, it would be for the people who make menu and use placeholders. But this placeholders are more precise.

**Comment by PikaMug** [comment]
Wrong issue tracker. Please visit https://github.com/PikaMug/PlaceholderExpansion-Quests/issues
