### ISSUE TITLE
[Quests] Module error!

### ISSUE THREAD

**Issue by ErythroCraft** [PikaMug/Quests#1892]
### What is your Quests version / build number (do _not_ say "latest")?

>quest info
[21:30:20] [Server thread/INFO]: This operation may only be performed in-game.

Please update your plugin to enable this command in server console.

Build Number:  4.2.1-b300

### Describe the problem and how to replicate it.

Quests can not find the class net.livecar.nuttyworks.npc_destinations.api.Navigation_NewDestination

Is this exist in NPC_Destination 1.18.x ?

[latest - Kopie.log](https://github.com/PikaMug/Quests/files/8200658/latest.-.Kopie.log)

### Any console errors to share?

```shell
java.lang.NoClassDefFoundError: net/livecar/nuttyworks/npc_destinations/api/Navigation_NewDestination

Caused by: java.lang.ClassNotFoundException: net.livecar.nuttyworks.npc_destinations.api.Navigation_NewDestination
```

**Comment by PikaMug** [comment]
This is an issue with NPCDestinations - please reach out to its developer.
