### ISSUE TITLE
What Did You Expect?

### ISSUE THREAD

**Issue by RockyStockyT** [PikaMug/Quests#1893]
### What is your Quests version / build number (do _not_ say "latest")?

3.10

### Describe the problem and how to replicate it.

I started the quest "What did you expect" and the "progress" for the scoreboard doesn't work and gives me a long line of text saying that it cannot be used with a progress bar

I'm looking in the config and am unsure how to resolve it

### Any console errors to share?

```shell
No errors in console
```

**Comment by DeadlykillOfficial** [comment]
You are running unsupported quests version.

**Comment by PikaMug** [comment]
Not just unsupported; version 3.10 does not exist. There isn't even a 3.1.0 release.
