### ISSUE TITLE
/qs editor and other commands. Ru Landg

### ISSUE THREAD

**Issue by ZelefRU** [PikaMug/Quests#1895]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.2

### Describe the problem and how to replicate it.

/qs editor is replaced by /qs редактор in Russian, but writes that there is no such command, if you write manually /qs editor, then everything is fine
![Screenshot_1](https://user-images.githubusercontent.com/95104322/158047951-c6577332-ba05-414f-be24-6547643d763e.png)
.

### Any console errors to share?

```shell
no errors
```

**Comment by ZelefRU** [comment]
All of these commands are not working
![Screenshot_2](https://user-images.githubusercontent.com/95104322/158048003-b5d97512-fcf2-4f9b-a71c-74bc6bedbb38.png)

**Comment by PikaMug** [comment]
@ZelefRU Try https://ci.codemc.io/job/PikaMug/job/Quests/304/

**Comment by ZelefRU** [comment]
> @ZelefRU Try https://ci.codemc.io/job/PikaMug/job/Quests/304/

It's work, thx
