### ISSUE TITLE
[mysql][bug]stage progress loss/ sync problem

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1896]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.2-b303

### Describe the problem and how to replicate it.

moving from different server cause data loss , same as #1871 
1. take a quests from server a
2. submit 2 item for  quests
3. go to server b, can see progress reset to 0
4. try to submit 1 item in server b
5. data is sometimes saved

video demo:
https://youtu.be/wh-62_Ly2iI

This problem have been causing many of my players to  leave server, I have made a survey for player who left by asking in dc, most of them complaining that progress loss is the biggest pain for them , which cause them to not play anymore. : (

### Any console errors to share?

```shell
no error
```

### If applicable, can you provide an example quest from quests.yml?

```shell
https://paste.denizenscript.com/View/94358
```

**Comment by PikaMug** [comment]
Thanks for the report. As we discussed in #1871 the issue was resolved by saving at the end of each stage. However, saving after _every_ item delivery or block break could be very taxing on the server. In other words, the amount of precision you want may cause lag. Since item delivery occurs less frequently, the best solution in your scenario would be to split up the objective across multiple stages.

**Comment by hkkongou** [comment]
i understand your point and i just have some idea that may fix this problem..

instead of replacing the current number after each of the mysql saving when player disconnect, sum the number from mysql stage progress to current server progress then save it back when player disconnect.

in case player join server, in mysql, delay progress loading mysql progress by a few seconds (adjustable by playing in config maybe) so that the quests system have enough time to load the updated progress from mysql system.

I don't know whether quests stage progress is adjustable during the plugin is loading, but i think the code can be modify if is not support now for the delay i mentioned above.

**Comment by hkkongou** [comment]
> Thanks for the report. As we discussed in #1871 the issue was resolved by saving at the end of each stage. However, saving after _every_ item delivery or block break could be very taxing on the server. In other words, the amount of precision you want may cause lag. Since item delivery occurs less frequently, the best solution in your scenario would be to split up the objective across multiple stages.


maybe I will have to make a suggestion issue instead , humm

**Comment by hkkongou** [comment]
![image](https://user-images.githubusercontent.com/61608872/158543391-8f4d3d9b-d624-42b0-b887-b460e3f4567e.png)

just realized that MPDB check sync by using this additional boolean call sync completed
