### ISSUE TITLE
Can't save and quit

### ISSUE THREAD

**Issue by dorori123** [PikaMug/Quests#1898]
### What is your Quests version / build number (do _not_ say "latest")?

Quests-4.0.6 

### Describe the problem and how to replicate it.

Hello

Recently I changed the bukkit from magma to catserver, since magma is unavailble in using the skript plugin.

After the change, I gave one quest a very slight modification.
Its reward was origianally a paper with a name and lore, but I wanted it with a different name, and that was all.
Suddenly, the plugin does not allow the save and quit feature anymore.
All I can do is just exit without saving the changes.

I tried to remove the problematic quest from the yml file and remake it, and it was successful.
I can see the quest is working now in the server.
But the plugin itself is still not functioning. Everything else is fine, but only 'save and quit' doesn't work.

Is there anyone who knows why and how to fix it?

I will be tremendously grateful.

Dorori

### Any console errors to share?

```shell
There is nothing shown in the console
```

### If applicable, can you provide an example quest from quests.yml?

```shell
custom13:
    name: 유리병을 만들자
    ask-message: 일감을 받을까요?
    finish-message: 돈과 경험치를 받았습니다.
    npc-giver-id: 2
    requirements:
      quests:
      - 공방에 취직하자
    stages:
      ordered:
        '1':
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            type: GLASS_BOTTLE
            amount: 30
          start-message: '"유리병을 30개 만들어서 가져다주세요."'
          complete-message: (이제 유리병을 배달합시다.)
        '2':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            type: GLASS_BOTTLE
            amount: 30
          npc-delivery-ids:
          - 2
          delivery-messages:
          - 유리병을 배달했습니다.
          complete-message: '"유리가 아주 반짝거리네요! 고맙습니다."'
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        type: PAPER
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: 수표 4000원
          lore:
          - 우클릭 시 수표를 환전합니다.



This is the one that caused the issue.
```

**Comment by PikaMug** [comment]
Unsupported server software.
