### ISSUE TITLE
When abandoning the mission, he will disconnect

### ISSUE THREAD

**Issue by gary81013** [PikaMug/Quests#1902]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.2-b303

### Describe the problem and how to replicate it.

/quests quit
When abandoning the mission, he will disconnect
and prompt message
translation 'illegal_chat_characters' missing

### Any console errors to share?

```shell
21:54:01 [INFO] [alskdjfh8282] disconnected with: <translation 'illegal_chat_characters' missing>
21:54:01 [INFO] [alskdjfh8282] -> UpstreamBridge has disconnected
```

**Comment by PikaMug** [comment]
I haven't been able to replicate this. Which other plugins are present on the server?

**Comment by gary81013** [comment]
> 我無法複製這個。服務器上還有哪些其他插件？

![111](https://user-images.githubusercontent.com/43038433/159142092-b183e0cb-7870-4892-b6a4-8c9d114bffc9.PNG)
![222](https://user-images.githubusercontent.com/43038433/159142093-628116fb-3b82-410c-a9c7-9e8ee0580745.PNG)
![333](https://user-images.githubusercontent.com/43038433/159142094-a321a4fb-4776-4e24-90d0-fbaa25084760.PNG)
![444](https://user-images.githubusercontent.com/43038433/159142095-2cf412f3-74c6-4e19-8175-711871731118.PNG)
![555](https://user-images.githubusercontent.com/43038433/159142096-664db21b-0c6f-4ba2-94a6-bd5c0df9363e.PNG)
![666](https://user-images.githubusercontent.com/43038433/159142097-9daf54d8-c3be-4ed1-8835-32b7f3db7382.PNG)
