### ISSUE TITLE
fi-FI locale throws NPE when loaded

### ISSUE THREAD

**Issue by Kopo942** [PikaMug/Quests#1904]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.2-b303

### Describe the problem and how to replicate it.

1. Set language to `fi-FI`
2. `/qa reload`
3. Observe exception being thrown and "NULL" printed to chat

Encountered a different row number with `Lang.java` after adding some missing translations to the file, so two different stacktraces below.

### Any console errors to share?

```shell
[Quests/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
[Quests/WARN]: 	at java.base/java.lang.String.replace(String.java:2956)
[Quests/WARN]: 	at Quests-4.2.2.jar//me.blackvein.quests.util.Lang.init(Lang.java:216)
[Quests/WARN]: 	at Quests-4.2.2.jar//me.blackvein.quests.Quests.lambda$reload$5(Quests.java:1688)
----------------
[00:21:47] [Server thread/ERROR]: Error occurred while enabling Quests v4.2.2-b303 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.lang.String.replace(String.java:2956) ~[?:?]
	at me.blackvein.quests.util.Lang.init(Lang.java:193) ~[Quests-4.2.2.jar:?]
	at me.blackvein.quests.Quests.setupLang(Quests.java:753) ~[Quests-4.2.2.jar:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:210) ~[Quests-4.2.2.jar:?]
```

**Comment by PikaMug** [comment]
@Kopo942 Finnish is not a fully supported language at this time. The next release of Quests will allow you to use what little translations are present. If you would like to contribute to translation, please do so at https://crowdin.com/project/translate-quests
