### ISSUE TITLE
[mysql] saving problem is not fixed in #307 with questsbungee

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1906]
### What is your Quests version / build number (do _not_ say "latest")?

Quests-4.2.3#307

### Describe the problem and how to replicate it.

just have time to check the new questsbungee and quests version but the problem still exist.

Quests data are still not syncing correctly between servers, and if the player left the server, the data is gone. And with this new questsbungee plugin, it further limits server owners to have only one bungeecord , but most of the big server network have more than one bungeecord so is not good.

To replicate data loss problem:
1. login server A
2. take a quests
3. submit / do some progress
4. go to server B, you can see progress is saved to mysql, but in server B is not loaded
5. go to server A, you can see progress is saved to mysql but in B is 0, so mysql shows 0 progress, but in server A, the progress is still the submitted one, so if you swap back to B, it repeats number4
6. and if you leave the server, all progress is gone 

Youtube video:
https://youtu.be/g9pf61pUU48

#1901 is a very good fix but i understand it may break #1796 , however both of the problem should be solved, not sure is it possible but you may try apply 1901 fix and at the same time, add an extra method to temperately capture quests given to player before the 1 second delay load , and then execute the quests take again 

### Any console errors to share?

```shell
no error
```

### If applicable, can you provide an example quest from quests.yml?

```shell
same as previous tickets....
```

**Comment by PikaMug** [comment]
Although I can't imagine most servers - even large ones - would need to run multiple Bungeecord instances, it should be no problem as long as QuestsBungee is installed on each instance.

For the second server in your video which showed 0 items, is the config setup properly for MySQL?

**Comment by hkkongou** [comment]
> 

The second server in the video did set up correctly, the config.yml in both servers are same. 
And, as you can see in the video(around 2:15), when jumping from server 2 to server 1, the server 2's "0" record did save to MySQL.

**Comment by PikaMug** [comment]
Thanks. Please give https://ci.codemc.io/job/PikaMug/job/Quests/309/ a try

**Comment by hkkongou** [comment]
> Thanks. Please give https://ci.codemc.io/job/PikaMug/job/Quests/309/ a try

still not working well
quests is saving the data to database for the first quests progress, and then if player go to another server, the progress is still 0 . And will no be saved

**Comment by hkkongou** [comment]
just recorded another video for 309 version bungee and quests 
since it is little bit different from this ticket's original problem, but instead, some reading problem from #1901 somethgin
https://youtu.be/BixLcFR0u6w

**Comment by PikaMug** [comment]
@hkkongou https://ci.codemc.io/job/PikaMug/job/Quests/310/ (make sure to update both jars)

**Comment by hkkongou** [comment]
> @hkkongou https://ci.codemc.io/job/PikaMug/job/Quests/310/ (make sure to update both jars)

@PikaMug 
The problem still exist : (

server1
![image](https://user-images.githubusercontent.com/61608872/160284773-abb2dd8f-6c61-4505-a30d-15486a15296a.png)

server 2
![image](https://user-images.githubusercontent.com/61608872/160284793-1e3e42b0-add0-497a-a192-96ab33292751.png)

bungee
![image](https://user-images.githubusercontent.com/61608872/160284782-51d4a39f-50f1-40ec-9720-2f458fa24b5f.png)

**Comment by PikaMug** [comment]
Working on my end. Which Bungee plugins do you have installed?

**Comment by hkkongou** [comment]
> Working on my end. Which Bungee plugins do you have installed?
@PikaMug 
These
FlameCord0.6.6
plugins:

![image](https://user-images.githubusercontent.com/61608872/160308920-77a37842-88d0-46fd-ab42-634f35bfc347.png)

**Comment by hkkongou** [comment]
> Working on my end. Which Bungee plugins do you have installed?

i have also tried waterfall-1.18-482 just now, and the behavior is the same?

do you have a remote mysql database that can produce some ping delay? localhost mysql database may not able to create this problem.

And for my case testing, i tested by submit item from server a to server b, the FIRST time is ok, but when i submit server b then go to server a, server a is not updated.

**Comment by hkkongou** [comment]
> I've added a delay before before loading, try https://ci.codemc.io/job/PikaMug/job/Quests/311/

Tested 311...
Took a quests from server a then go to server b, the quests progress got wiped when joined to server b

**Comment by PikaMug** [comment]
Ensure that your player has at least one `quests.` permission on all servers.
https://ci.codemc.io/job/PikaMug/job/Quests/312/

**Comment by hkkongou** [comment]
> Ensure that your player has at least one `quests.` permission on all servers. https://ci.codemc.io/job/PikaMug/job/Quests/312/
> 
> Are you able to contact me on Discord?

yeah i am the tester and i have op and * permission in these 2 test server
build 312 is still not working

data is storing now and go between server will not wipe the data of each other , but no instant sync after swapping server, data is still using old database record
