### ISSUE TITLE
When abandoning the mission, he will disconnect

### ISSUE THREAD

**Issue by gary81013** [PikaMug/Quests#1907]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.3-b307

### Describe the problem and how to replicate it.

/quests quit
When abandoning the mission, he will disconnect
and prompt message
illegal characters in chat

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```shell
custom6:
    name: '§a[每日]§e肌肉鍛鍊'
    npc-giver-id: 12
    redo-delay: 86400
    ask-message: §6[系統] §d為了鍛鍊肌肉,請依照順序§f左鍵黑曜石、右鍵石製按鈕§d各100次
    finish-message: ''
    stages:
      ordered:
        '1':
          damage-block-names:
            - OBSIDIAN
          damage-block-amounts:
            - 100
          damage-block-durability:
            - 0
        '2':
          use-block-names:
            - stone_button
          use-block-amounts:
            - 100
          use-block-durability:
            - 0
    rewards:
      commands:
        - mi give MATERIAL A73 <player>
```

**Comment by gary81013** [comment]
![擷取](https://user-images.githubusercontent.com/43038433/159736309-a8ebab2e-0ca8-4d80-b700-2bc0f4a3302e.PNG)

**Comment by PikaMug** [comment]
Continued from #1902

I haven't been able to replicate this with the 4.2.3 release. What is your Minecraft server version?

**Comment by gary81013** [comment]
> Continued from #1902
> 
> I haven't been able to replicate this with the 4.2.3 release. What is your Minecraft server version?

Paper-216 (MC: 1.18.1)

**Comment by PikaMug** [comment]
I found the issue - the `§` symbol is not allowed in chat. Will update this ticket once I push a solution.

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/308/
