### ISSUE TITLE
Quests Points has been reset

### ISSUE THREAD

**Issue by PappoYT** [PikaMug/Quests#1911]
### What is your Quests version / build number (do _not_ say "latest")?

Quests 4.2.4-b310

### Describe the problem and how to replicate it.

Suddenly all quests points of all players has been reset to zero.
No operators issue any command to do this.
Is there a way to restore them?

### Any console errors to share?

```shell
Nope.
```

**Comment by PikaMug** [comment]
This should not be possible. Are you using YAML (default) or MySQL?

Restoring from a server backup would be the only recourse.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
