### ISSUE TITLE
Breed, collect, and break stages suggestions

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1913]
### What does your feature do?

Hello,

I would like to suggestion 3 stages for you to add to the quests. There should be like a **breed, collect, and break** stages.

Here are examples of each stage:
1. Breed: allow players to breed mobs.
2. Collect: allow players to collect like flowers and such.
3. Break: allow there to break other blocks or items instead of just mining ores or stones.

### How would people use it?

I have explained above and given each stage an example.

**Comment by PikaMug** [comment]
Bukkit/Spigot API doesn't provide a way to tell whom initiated the breeding to my knowledge. Collecting flowers would be a Break Block objective. Breaking other types of blocks should already be possible.
