### ISSUE TITLE
Reward QTY changing after set

### ISSUE THREAD

**Issue by CordlessDeWalt** [PikaMug/Quests#1914]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.4-b310

### Describe the problem and how to replicate it.

I set a reward for a item turn in quest as named Iron_Ingots with a qty of 64. The quest gives the correct amount once, then coming back to do it later (after a 10 minute cooldown) give what ever number it feels like (I have gotten 6, 9, 31, 12)

Everything else about the quest works fine, the required qty never changes. I have edited the quest back to the original amount each time and it still changes.

### Any console errors to share?

```shell
None that I could fine. Everything boots fine and closes down fine. When running the quest, nothing shows up in the console.
```

### If applicable, can you provide an example quest from quests.yml?

```shell
custom1:
    name: We Need Copper
    ask-message: We need Copper for a Kingdom Project, we will give you Iron in return.
      Please bring me 64 Copper Ingots.
    finish-message: Well done!
    npc-giver-id: 4
    requirements:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: COPPER_INGOT
        amount: 64
      remove-items:
      - false
    stages:
      ordered:
        '1':
          items-to-deliver:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COPPER_INGOT
            amount: 64
          npc-delivery-ids:
          - 4
          delivery-messages:
          - Perfect, we need this copper for a project!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: IRON_INGOT
        amount: 64
      money: 500
    planner:
      cooldown: 600
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
```

**Comment by PikaMug** [comment]
Is your server in offline mode? Could be a player UUID conflict.

If you're in a party with other players, could also be they're making progress while you're locked out of the quest.

**Comment by CordlessDeWalt** [comment]
online-mode=true -- The server is online.

I have no party system installed. I have checked on 3 different characters and they all get less reward than I originally set the quest for.

**Comment by CordlessDeWalt** [comment]
Is there any other information I can provide to troubleshoot this issue?

**Comment by PikaMug** [comment]
Are you using YAML storage (default) or MySQL? I haven't been able to replicate this using your quest.

**Comment by CordlessDeWalt** [comment]
I have been using default storage, nothing else. I am more than happy to show it to you if that would help? I am on your discord under the same name.

**Comment by CordlessDeWalt** [comment]
I am unsure, I will update and test in the next few days and report back.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
