### ISSUE TITLE
Stage Bug - Potion Brewing

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1915]
### What is your Quests version / build number (do _not_ say "latest")?

I was told to open a bug report and would had figure this would be a bug as well. It seems like the potions brewing stage is buggy. I have a quest stage to setup where players has to brew **16 water breathing potions** but the quest journal isn't being specific which can confuse the players out on what kind of potions to brew.

I'm using Quests 4.2.2-b304 build.

screenshot: https://gyazo.com/7d66505b95c3eb9c36a58576d9455785 

### Describe the problem and how to replicate it.

I've explained above. ^^

### Any console errors to share?

```shell
There isn't any console error.
```

**Comment by PikaMug** [comment]
Will need an example quest from _quests.yml_ to test with.

**Comment by AccioAce** [comment]
> Will need an example quest from _quests.yml_ to test with.

Alright here is the quests.yml -> https://bin.birdflop.com/nedubewuyu.yaml

**Comment by PikaMug** [comment]
Using [Quests 4.2.4-b316](https://ci.codemc.io/job/PikaMug/job/Quests/316/) the quest shows "Brew Potion of Water Breathing: 0/16" for me.

Make sure that `translate-names: true` is set in your _config.yml_ file.

**Comment by PikaMug** [comment]
While chat will show "Brew Potion of Water Breathing: 0/16" this isn't currently possible for the Quests Journal because the [translation library](https://github.com/PikaMug/LocaleLib) only works for chat messages.

**Comment by PikaMug** [comment]
Additionally it appears that setting book pages with BaseComponents isn't supported on Spigot/Paper 1.8, so unless Quests were to support 1.9+ only this isn't currently possible.

**Comment by AccioAce** [comment]
> @AccioAce I was able to get this working after all using a separate library. Please try https://ci.codemc.io/job/PikaMug/job/Quests/317/ and let me know if you run into any issues.

Hello, when I typed **/quests journal** it seems pop out the book but didn't given it to me. I guess that the new update for it? And as for quests journal I think I see a bug where there is only **one page** when the quests has a long list? Shouldn't there be more then one page? https://gyazo.com/c03a6950d5855efb88e0043f160e8ef7

**Comment by PikaMug** [comment]
Yes, that feature was added in 2db149067d30e6f94dfb0dc8ab1cfb27acfb6be3 and if you're like to switch back just set `give-journal-item: true` in your _config.yml_ file. As for the list not carrying over, I'll have to look into it.

**Comment by AccioAce** [comment]
> Yes, that feature was added in [2db1490](https://github.com/PikaMug/Quests/commit/2db149067d30e6f94dfb0dc8ab1cfb27acfb6be3) and if you'd like to switch back just set `give-journal-item: true` in your _config.yml_ file. As for the list not carrying over, I'll have to look into it.

ah I see and thanks! Keep me updated when the bug is fixed for the list not carrying over.

Thanks!
