### ISSUE TITLE
EntityDeathEvent make a problem inside MythicMobs Quests Module

### ISSUE THREAD

**Issue by WhiteFrost06** [PikaMug/Quests#1918]
### What is your Quests version / build number (do _not_ say "latest")?

4.2.4

### Describe the problem and how to replicate it.

I can't make quests with custom objective: Kill MythicMobs Objective because Quests start an error about EntityDeathEvent, here is in this pastebin: https://pastebin.com/34nfBZ5a

### Any console errors to share?

```shell
https://pastebin.com/34nfBZ5a
```

**Comment by PikaMug** [comment]
You are using an incompatible module. See https://pikamug.gitbook.io/quests/casual/modules#mythicmobs
