### ISSUE TITLE
quests stopped working suddenly?

### ISSUE THREAD

**Issue by CaptainSnickerz** [PikaMug/Quests#1919]
### What is your Quests version / build number (do *not* say "latest")?

quests-4.3.0
paper 1.18.2

### Describe the problem and how to replicate it.

bug 1:
Reach location

Bug2:
kill last entity on quest

All buggs revolve around finishing stages and moving to next stage of quest

### Any console errors to share?

```shell
error on completing go to location stage:
https://pastebin.com/ZN32pmUF

error on entity death event on completing kill entity zombie:
https://pastebin.com/jXKnrcCa
```

### If applicable, can you provide an example quest from quests.yml?

```shell
https://pastebin.com/mbRqUuSq
```

**Comment by PikaMug** [comment]
Already fixed in 11ffbf46be5b514b418161545633f4cb093f9caa

Use https://ci.codemc.io/job/PikaMug/job/Quests/320/
