### ISSUE TITLE
Goal Spam

### ISSUE THREAD

**Issue by Shaworley** [PikaMug/Quests#1926]
### What is your Quests version / build number (do *not* say "latest")?

Quests Version : Latest

Here is an image of the issue to help you understand what the player is seeing regarding the 'Place Blocks' quests : 

![Complété2](https://user-images.githubusercontent.com/87674043/162990205-ca67671a-5fe3-4131-b894-89383a3027bd.png)

The message that explains the problem was translated with google translate.

### Describe the problem and how to replicate it.

Hello,

I have been using the Quests plugin for quite a few days now for the development of a Minecraft server.

Following the opening of a beta organized in the new quests that I created, a player pointed out to me that in objectives such as "Place blocks", the chat is spammed with a "Complete Place" message. dirt" (or other block)/x" when it breaks and puts back blocks requested by the objective.

This happens especially when a stage contains 2 or more objectives to accomplish and the player does not want to do the whole stage at once and therefore place these blocks concerned for other personal projects.

This issue is not reciprocated for "Break Blocks" quests which are not affected by this message.

Finally, I would like to know if it is possible to remove these messages that harass the player in his chat?

Thank you, have a nice day.

### Any console errors to share?

```shell
No errors in the console, just remove the message that spams the chat of the players.
```

### If applicable, can you provide an example quest from quests.yml?

```shell
I don't have access to the server files, I'm not the founder of the server that owns this plugin.
```

**Comment by PikaMug** [comment]
Breaking one of the required blocks reduces the count to 99/100. Placing one back to down completes the goal to 100/100. This is intended functionality.
