### ISSUE TITLE
bug on reload

### ISSUE THREAD

**Issue by CaptainSnickerz** [PikaMug/Quests#1927]
### What is your Quests version / build number (do *not* say "latest")?

quests 4.3.1+hotfix
paper 1.18.2

### Describe the problem and how to replicate it.

reload the plugin

### Any console errors to share?

```shell
https://pastebin.com/d8NbUXbz
```

### If applicable, can you provide an example quest from quests.yml?

```shell
Latest quest added
https://pastebin.com/aLJ2ASa3
```

**Comment by PikaMug** [comment]
"hotfix" is not a build number. Please share your build number from _/quests info_

**Comment by CaptainSnickerz** [comment]
hey sorry its quests 4.3.1 build b3222, the recent update with the hotfix
Actions.yml:
https://pastebin.com/ZJ9Wzs68

**Comment by CaptainSnickerz** [comment]
it is okay to send pastebin right? most people ask to put it in pastebin so i just thought would be better to do it for you already

**Comment by PikaMug** [comment]
I'll assume you meant 322 and not 3222.

Seems the plugin isn't correctly processing the `charged` state of your action mob spawns' crossbows. I'll look into it.

**Comment by PikaMug** [comment]
@CaptainSnickerz Try <https://ci.codemc.io/job/PikaMug/job/Quests/323/>

**Comment by CaptainSnickerz** [comment]
testing, thank you

**Comment by CaptainSnickerz** [comment]
its helped with the bug but now i cant pick up any items

**Comment by CaptainSnickerz** [comment]
> @CaptainSnickerz Try https://ci.codemc.io/job/PikaMug/job/Quests/323/
