### ISSUE TITLE
[Suggestion]Extra item delivery system with NBT detection

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1935]
### What does your feature do?

Most of the RPG or MMORPG system comes with item creation system, such as MMOITEMS, Mythicmobs, Executable items, advanced enchantment, crazy enchantments and bra bra bra. 

These plugin comes with system that can change the item's name and Lore.

In quests item delivery system, it read and check an item's name , lore, enchantments and attributes. For plugin listed above, if a player modified a item (which is very normal for RPG server , players can do some small modification on item such as enchanting and add some gems), the item will not be able to read by quests system and will be treated as a different item.

The above is the problem.

My suggestion is that , there can be a new way to detect and take item away from players, by using only NBT checking as a extra item delivery stage.

Please check the picture below.

![image](https://user-images.githubusercontent.com/61608872/164170392-adf0b357-7e38-4ac0-8f9f-4d4a9d5e8847.png)
![image](https://user-images.githubusercontent.com/61608872/164170428-046b8d7d-d64a-40e8-83ff-90f4c2716862.png)
![image](https://user-images.githubusercontent.com/61608872/164170470-6e29ad8e-55a5-4e8c-9326-e202a48a28f2.png)

These 3 screenshots are items from MMOitems, Mythicmobs and executable items, they all use  NBT to save their item's internal ID, so that even if the item's name and lore be modified, the item can still do its job, such as activating a skill, do upgrades.

[My suggestion]
Compare item by NBT, for example
Mythicmobs use ``MYTHIC_TYPE: "mythicmobs item internal ID"`` to store item's ID, quests can check whether an item have such NBT data in an item and take it away.

### How would people use it?

Users can type the corresponding NBT they want to check in an item. When quest from such part is in the item, the item will be taken.

I use NBTTooltip mod to see what NBT is inside an item.

[big brain time]
A more big brain idea is that, not only check NBT, quests will check the entire item including name, lore , and player input a string such as "+4.8", if quests check and found that such string is in any part of the item, such as item name and item lore, the item will be detected and taken.

This suggestion can really help simplified the item checking process and support items modifying plugin.

**Comment by PikaMug** [comment]
Items are saved in _quests.yml_ using Bukkit's serialization for ItemStack, which does not include NBTs or persistent data containers to my knowledge. Therefore, these situations are best left to module.

A module for MythicMobs is currently available at https://lectern.browsit.org/resources/resource/32/
