### ISSUE TITLE
[suggestion]force questsgui open when there is only 1 quests

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#1942]
### What does your feature do?

With original quests GUI or addon questsGUI, if a NPC have only 1 quests, the gui will not open, players will not be able to see what the gui item's lore or name, thus, player right click npc , the quests will be taken instantly if requirement is met.

This is bad, set up gui when there is only 1 quests on an NPC is useless.

Therefore, i suggest to **add a setting in quests config or quests gui config**, forcing quests npc gui to open even though there is only 1 available quests, or even 0 available quests on an npc.  (still need to make sure this function does not interfere other non quests npcs, but i think quests already have message that pop up when an npc have no quests available so there must be a method for it )

### How would people use it?

This allow npc with only 1 quests can still show important information by displaying in the lore, users can write the message in the lore.

If some quests server owner don't want this function to be enable, they can just don't turn on such setting in config.

**Comment by PikaMug** [comment]
Either GUI should open when there is only 1 quest, which it does in my test environment. Feel free to report this as a bug with an example quest.
