### ISSUE TITLE
Admin command to open a GUI for an NPC that displays their quests for specific players

### ISSUE THREAD

**Issue by MarxminSD** [PikaMug/Quests#1945]
### What does your feature do?

Adds a command like `/questsadmin opengui <npcUUID> <playername>`

Currently, if an NPC is used as a quest-giver, right clicking on them opens up the questing menu directly and instantly. In our server we use Interactions as well as Denizen to create an environment where players can interact with an NPC and choose to:

- Chat with NPCs about the town
- Choose to open the NPC's shop
- Ask the NPC about available work (Quests)

With Interactions, we can accomplish the first two with no problem! For the quests feature, I've been working on some workarounds, but have had iffy results so far. 

- For the chatter portion, we use the "random dialogue" function with Interactions
- For shops, we use dtlTradersPlus and `console_command: dtltraders open %player% blacksmith` to open the shops GUI via Interactions as well

For quests, I've made a few flowcharts to test theories and workarounds, but it's super linear, and as the amount of quests scales up or we want to implement additional quests aside from one questline e.g.:

- A linear questline to unlock higher tiers (additional pages) in the NPC's shop
- Repeatable quests for the NPC
- One-time quests that are unlocked by default, or that have unique requirements, but are not tied to the NPC's main shop questline

With how things are currently set-up, I don't know if it's possible.

Currently it looks like:
If quest1 isn't complete, show quest1
If quest1 is complete, show quest2
If quest2 is complete, show quest3
If quest3 is complete, show quest4 ... and so on using Conditional Dialogues with Interactions. I've been testing things out but don't think I could show repeatable quests, or scale it very efficiently. 

Flowchart: (may need to enlarge)
![image](https://user-images.githubusercontent.com/96161173/166118287-286bc74a-deca-43f9-a4d4-6b7ab6a42b5e.png)

With this workflow, I've been running something like `console_command: questadmin give %player% Prototyping`, which returns a "CONSOLE force you to take... quest" message in chat. If I were to give the player permission to use /quests take, we would have to add specific permission nodes for each quest, or use player flags via denizen, of which we would have a few hundred.

![image](https://user-images.githubusercontent.com/96161173/166118695-528986ad-21e6-460b-bcd4-89f731846d6a.png)

Instead of this spaghetti, we could use a command like `/questsadmin opengui <npcUUID> <playername>` to simply show all quests tied to that NPC when they choose the "Work" option.

### How would people use it?

When utilizing another plugin like Interactions or Denizen - or anything that would have an NPC be used for multiple purposes other than just Quests, server owners and devs could create more lifelike NPC's with additional functionality, rather than just a quest-giver.

**Comment by PikaMug** [comment]
Thanks for the suggestion. Since this is a very specific use case, I'm hesitant to add a new command, especially where typing an entire UUID would be necessary for casual use. This level of integration should either be with a custom plugin of your own or something like [Depenizen](https://github.com/DenizenScript/Depenizen). You might also consider hiring a developer for this purpose.

**Comment by MarxminSD** [comment]
Right on - thank you for the quick response!

**Comment by PikaMug** [comment]
https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features
