### ISSUE TITLE
Add an option to hide from player commands ran as rewards

### ISSUE THREAD

**Issue by PapiCapi** [PikaMug/Quests#1954]
### What does your feature do?

It would be great to have an option in the config or inside the rewards editor of a quest to disable this output ( that shows when we finish a quest )
![image](https://user-images.githubusercontent.com/49530141/167292357-ee2c74fa-a3bb-4b93-a0fb-ed1cc17f0544.png)

### How would people use it?

It would be used because some commands don't have any interest to be shown to player because they already have a feedback included in them.

**Comment by PikaMug** [comment]
Use the override under the Edit Rewards prompt.
