### ISSUE TITLE
Disable NPCs being a quest-giver by default or if they have no quests assigned to them

### ISSUE THREAD

**Issue by MarxminSD** [PikaMug/Quests#1956]
### What does your feature do?

As of right now, once Quests is installed, every NPC regardless of entity type will say "No more quests available." when a player right-clicks on them. 

For servers that have other uses for NPCs (Sentinel, custom Denizen scripts, Interactions, etc.), the message can get in the way of natural dialogue or actions - especially if a player is fighting a Sentinel NPC; say they're using a shield to block; it's almost a constant spam of:

```
No more quests available.
No more quests available.
No more quests available.
No more quests available.
No more quests available.
No more quests available.
No more quests available.
No more quests available.
```

You can go to the lang file and remove the message, but the player will still see a blank chat message like so in the above example: 

![Screenshot_7](https://user-images.githubusercontent.com/96161173/167345468-91863147-8e79-435c-a836-b9772c1b7187.png)

If it's possible, I think it would be a really cool feature if this message were only shown when a player right clicks on an NPC who has had a quest assigned to them, or an option in the config to disable this message entirely.

### How would people use it?

For servers that have multiple uses for NPCs - Sentinel, Interactions, Denizen -, it would help conversations flow better, as well as other interactions not be interrupted by the message.

**Comment by PikaMug** [comment]
Try https://ci.codemc.io/job/PikaMug/job/Quests/331/ with `noMoreQuests: ""`

**Comment by MarxminSD** [comment]
Thank you! Trying this now for both issues!
