### ISSUE TITLE
Override a condition's default message

### ISSUE THREAD

**Issue by MarxminSD** [PikaMug/Quests#1957]
### What does your feature do?

In `/quests conditions` admins would have an additional option to override the default message format for a (each) condition (seen below)

![image](https://user-images.githubusercontent.com/96161173/167486918-c947136d-d04c-4b2e-8ebd-d009ff041069.png)

and instead be able to specify a custom message that would be shown. For example; the above condition requires that chainmail armor be worn for a Zombie kill to count toward objective progress. Instead, I could make a custom message that is more user friendly. For example:

![image](https://user-images.githubusercontent.com/96161173/167487540-df1c5052-876e-4180-a10e-a8cea9c1b7b9.png)

If the condition doesn't specify a custom message, the default would instead be used.

### How would people use it?

I think this would allow server owners/quest makers to create a more user friendly experience - especially for newer players who aren't familiar with placeholders, and don't understand what they mean. Could also definitely be used for ease of explanation and a bit of a cleaner message!

**Comment by PikaMug** [comment]
I agree this could use better formatting but also this should be a request for an armor condition instead of using placeholders. In the meantime, this third-party resource might be useful: https://lectern.browsit.org/resources/resource/42/

**Comment by PikaMug** [comment]
Solution is to describe conditions as desired in the stage's details list override.
