### ISSUE TITLE
action bug

### ISSUE THREAD

**Issue by xXluxiano777Xx** [PikaMug/Quests#1962]
### What is your Quests version / build number (do *not* say "latest")?

4.4.1

### Describe the problem and how to replicate it.

when you put an action in a mission this action is put, in clear inventory automatically, when you edit the action and remove the clear inventory, it is not really removed and also the fail quest is activated in true and everything is bugge
![Captura de pantalla (7717)](https://user-images.githubusercontent.com/105582348/168463387-49bdc31f-b68d-4def-ac20-7d79335a70a3.png)
d

### Any console errors to share?

```shell
no
```

**Comment by TheBlockForge** [comment]
I am having almost the exact same issue.

When the action is set to spawn just one zombie, this issue does not occur. but when i change it to spawn 10 zombies the quest auto fails me and clears inventory. after checking the action editor, i notice the setting are force changed even after I manually change them.

Let me know if I should open a separate ticket so i can fill out the formalities or if there's any additional information i can provide

**Comment by xXluxiano777Xx** [comment]
Do it
