### ISSUE TITLE
Multiple path options in 1 quest

### ISSUE THREAD

**Issue by Abstractleaf** [PikaMug/Quests#1968]
### Where else have you looked for answers to this question?

Documentation 

### Share your question with as much detail as possible.

If I wanted to give players the choice to attack the castle or defend the castle, how would this be done within the confines of this plugin? My goal is to have a quest that players need to pick a side and they will get rewards based on side picked.

**Comment by PikaMug** [comment]
Quest block requirement https://pikamug.gitbook.io/quests/beginner/requirements
