### ISSUE TITLE
Hide quest from showing up when typing /quest

### ISSUE THREAD

**Issue by dylan0114** [PikaMug/Quests#1971]
### Where else have you looked for answers to this question?

the quest discord under community support a mod named Deadlykill sent me here for more help.

### Share your question with as much detail as possible.

when typing /quest in chat it shows the available quest but I would like to hide them if possible.
![image](https://user-images.githubusercontent.com/65750991/172614683-ec396dc9-c6fe-4c8e-a96f-fb4c1fcff16c.png)

**Comment by PikaMug** [comment]
This is not currently possible. If you would like to submit a new issue, please explain why someone would want this in greater detail under the "Suggest a feature" option.
