### ISSUE TITLE
Cannot load configuration from stream (All Quests Not Loading)

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#1972]
### What is your Quests version / build number (do *not* say "latest")?

[15:28:26 INFO]: This server is running Paper version git-Paper-378 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 4b27254)

Build # 343 

### Describe the problem and how to replicate it.

none of our quests are loading suddenly since updating paper. I have tried resetting the config and creating a new quest, still loads 0 quests. server files are set to read ect 

### Any console errors to share?

```shell
log: https://www.toptal.com/developers/hastebin/esunotoqub.yaml
```

**Comment by PikaMug** [comment]
Could be an issue with that particular build of Paper and/or the `quests.yml` file might have got corrupted in the update process. Regardless, I have no way to investigate further without seeing the file.

**Comment by Castiella** [comment]
I'm pretty sure it was one of the recent Paper Builds that broke it.

I've just deleted my Quests folder and added a normal quest in, and it's still not loading on /questadmin reload.

```  custom211:
    name: Kill 500 Ghasts
    ask-message: Kill 500 Ghasts
    finish-message: Well done!
    npc-giver-uuid: 1a9fe86d-a97a-443a-a006-589eea188267
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 2975
      type: DIRT
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - GHAST
          mob-amounts:
          - 500
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: CRIMSON_FUNGUS
        amount: 2
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Nether
            Root"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"For
            use in the "},{"italic":false,"color":"red","text":"NetherStore"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Worth
            "},{"italic":false,"color":"red","text":"100 Nether Droppings"}],"text":""}```


0 console errors at all.

**Comment by Castiella** [comment]
Closing as we found this issue.
since the recent update that uses NPC UUID rather than NPC-ID - when we deleted the NPC with the GUI's linked, it broke them/prevented from taking them. (Fix = removing the NPC UUID info from the config)
