### ISSUE TITLE
Quests password multiple answers

### ISSUE THREAD

**Issue by benja854** [PikaMug/Quests#1980]
### What is your Quests version / build number (do *not* say "latest")?

quests 1.19  4.5.0-b345

### Describe the problem and how to replicate it.

I previously reported a problem with quests not accepting multiple answers to a password as it had done when I started using it around 1.16 linked below

https://github.com/PikaMug/Quests/issues/1823

Since then the code has obviously been changed but now the semi-colon functions differently. It is once again no longer possible to have multiple correct answers to one password prompt by using the semi-colon to separate the possible answers.

For example if I have the single password question "What is one + one?"

And I enter in the answer field in the editor "2;two" and try to save it, it creates password answers as if for two different prompts and I get :

"all required lists must have the same number of entries."

I believe this was done in error because you can already add multiple password and answers without the semi-colon using the editor.

The former functionality was very useful for accepting multiple correct answers, for spelling variations, or for word choice variations between countries.

### Any console errors to share?

```shell
No console error only red text in the editor:
"All required lists must have the same number of entries"
```

**Comment by PikaMug** [comment]
It seems like this was reverted once again because of how the MySQL integration was finalized. I'm afraid it isn't in the best interest of the project to create an edge case for this one objective. You might consider having a module created via https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features
