### ISSUE TITLE
quest not registering while breaking wood

### ISSUE THREAD

**Issue by alexanderb25** [PikaMug/Quests#1981]
### What is your Quests version / build number (do *not* say "latest")?

4.5.1-b346

### Describe the problem and how to replicate it.

I have a plugin called "tree feller" and when players break the tree with an axe the wood doesn't count, on another server when breaking one block from the tree it counts towards the quest even when the whole tree falls but my server doesn't count any blocks.

### Any console errors to share?

```shell
There are no errors in console
```

**Comment by PikaMug** [comment]
Unable to investigate without example quest.
