### ISSUE TITLE
Quest console error

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1983]
### What is your Quests version / build number (do *not* say "latest")?

 Quests version 4.5.1-b348
Paper: 1.19

### Describe the problem and how to replicate it.

Console error I've found -> https://gyazo.com/9aebc09c2711b1731a9ea0f273ba1d7b?token=7749eaa82961ca14f9ccea6cd56401a6

(I'm not sure what is causing it.)

### Any console errors to share?

```shell
Is above ^
```

**Comment by PikaMug** [comment]
This typically occurs as a result of manual _quests.yml_ edits. Would need to see the file to investigate further.

**Comment by AccioAce** [comment]
> This typically occurs as a result of manual _quests.yml_ edits. Would need to see the file to investigate further.

Hello, here it is!

# For non-English characters, this file MUST stay encoded in UTF-8
quests:
  custom1:
    name: Spring
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - gold_ore
          break-block-amounts:
          - 320
          break-block-durability:
          - 0
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: CAKE
            amount: 16
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GOLD_INGOT
            amount: 64
          items-to-consume:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKIE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: MILK_BUCKET
          cows-to-milk: 16
          fish-to-catch: 16
          mobs-to-kill:
          - WitherSkeleton
          - Slime
          - witch
          - irongolem
          - wither
          - enderdragon
          mob-amounts:
          - 16
          - 16
          - 16
          - 16
          - 1
          - 1
          sheep-to-shear:
          - White
          - Orange
          - Magenta
          - LightBlue
          - Yellow
          - Lime
          - Pink
          - Gray
          - LightGray
          - Cyan
          - Purple
          - Blue
          - Brown
          - Green
          - Red
          - Black
          sheep-amounts:
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
          - 16
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: TRIPWIRE_HOOK
        amount: 2
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Spring
            Crate Key"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Right-Click
            on a \""},{"italic":false,"color":"white","text":"Spring"},{"italic":false,"color":"gray","text":"\"
            crate"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"to
            win an item!"}],"text":""}'
          - '{"text":""}'
          enchants:
            DURABILITY: 1
  custom2:
    name: Easter
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          - DEEPSLATE
          - TUFF
          - DIRT
          - SAND
          - SANDSTONE
          break-block-amounts:
          - 256
          - 256
          - 256
          - 256
          - 256
          - 256
          break-block-durability:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LEATHER_HELMET
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LEATHER_CHESTPLATE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LEATHER_LEGGINGS
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LEATHER_BOOTS
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BOOKSHELF
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: WHITE_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: ORANGE_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: MAGENTA_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LIGHT_BLUE_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: YELLOW_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LIME_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: PINK_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GRAY_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LIGHT_GRAY_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: CYAN_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: PURPLE_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BLUE_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BROWN_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: RED_DYE
            amount: 16
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BLACK_DYE
            amount: 16
          items-to-smelt:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GOLD_INGOT
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GREEN_DYE
            amount: 64
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: POTION
            amount: 16
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:water_breathing
          items-to-consume:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: APPLE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: MUSHROOM_STEW
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BREAD
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKED_PORKCHOP
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GOLDEN_APPLE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKED_COD
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKED_SALMON
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKIE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: MELON_SLICE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKED_BEEF
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKED_CHICKEN
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: CARROT
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BAKED_POTATO
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: PUMPKIN_PIE
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKED_RABBIT
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: RABBIT_STEW
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COOKED_MUTTON
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: BEETROOT_SOUP
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SWEET_BERRIES
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GLOW_BERRIES
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: HONEY_BOTTLE
          mobs-to-kill:
          - Cow
          - Rabbit
          - Chicken
          mob-amounts:
          - 20
          - 20
          - 20
          mobs-to-tame:
          - Wolf
          - Cat
          - Parrot
          mob-tame-amounts:
          - 1
          - 1
          - 1
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: TRIPWIRE_HOOK
        amount: 2
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Easter
            Crate Key"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Right-Click
            on a \""},{"italic":false,"color":"white","text":"Easter"},{"italic":false,"color":"gray","text":"\"
            crate"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"to
            win an item!"}],"text":""}'
          - '{"text":""}'
          enchants:
            DURABILITY: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
  custom3:
    name: Force
    ask-message: Challenge objectives!
    finish-message: Well done!
    stages:
      ordered:
        '1':
          break-block-names:
          - OAK_LOG
          - BIRCH_LOG
          - DARK_OAK_LOG
          - SPRUCE_LOG
          - JUNGLE_LOG
          - ACACIA_LOG
          - WARPED_STEM
          - CRIMSON_STEM
          - COAL_ORE
          - IRON_ORE
          - COPPER_ORE
          - LAPIS_ORE
          - REDSTONE_ORE
          - DIAMOND_ORE
          - EMERALD_ORE
          - END_ROD
          break-block-amounts:
          - 384
          - 384
          - 384
          - 384
          - 384
          - 384
          - 384
          - 384
          - 1024
          - 1024
          - 1024
          - 1024
          - 1024
          - 1024
          - 1024
          - 64
          break-block-durability:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          place-block-names:
          - STONE
          - SPRUCE_PLANKS
          place-block-amounts:
          - 576
          - 288
          place-block-durability:
          - 0
          - 0
          items-to-craft:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COAL_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: IRON_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: COPPER_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: LAPIS_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: GOLD_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: DIAMOND_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: EMERALD_BLOCK
            amount: 64
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SPYGLASS
            amount: 16
          items-to-brew:
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: SPLASH_POTION
            amount: 18
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:leaping
          - ==: org.bukkit.inventory.ItemStack
            v: 2975
            type: POTION
            amount: 18
            meta:
              ==: ItemMeta
              meta-type: POTION
              potion-type: minecraft:healing
          mobs-to-kill:
          - Ghast
          - Villager
          - Axolotl
          - Horse
          - Donkey
          - Mule
          mob-amounts:
          - 25
          - 25
          - 25
          - 25
          - 25
          - 25
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2975
        type: TRIPWIRE_HOOK
        amount: 2
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"Force
            Crate Key"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Right-Click
            on a \""},{"italic":false,"color":"white","text":"Force"},{"italic":false,"color":"gray","text":"\"
            crate"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"to
            win an item!"}],"text":""}'
          - '{"text":""}'
          enchants:
            DURABILITY: 1
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false

**Comment by PikaMug** [comment]
Thanks. In your case, it seems a player joined using a client language which is only partially translated. This build should prevent the error: https://ci.codemc.io/job/PikaMug/job/Quests/352/
