### ISSUE TITLE
Interactions Quest Module don't work

### ISSUE THREAD

**Issue by sSwpl** [PikaMug/Quests#1987]
### What is your Quests version / build number (do *not* say "latest")?

Quests - 4.5.1
Interactrions Quests Module - 1.2
Interactions - 1.29.2

### Describe the problem and how to replicate it.

When I put Module in modules folder and then start server quests plugin just doesn't see it. It says that I can download modules from the website. I tried with other modules like mcmmo etc and it worked, but with Interactions, it won't work.

### Any console errors to share?

```shell
Nope. No errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
I didn't create any.
```

**Comment by PikaMug** [comment]
This issue tracker is for Quests only. For help with that module, click the `Ask Questions / Get Support` button at https://www.spigotmc.org/resources/92421/
