### ISSUE TITLE
how can i give someone a random quest. 

### ISSUE THREAD

**Issue by StealthFeather** [PikaMug/Quests#1990]
### Where else have you looked for answers to this question?

everywhere

### Share your question with as much detail as possible.

like daily quest, randomly pick a quest from several quests and give it to player

**Comment by DeadlykillOfficial** [comment]
You need a custom plugin in order to make that. Either completely new or bridge that adds this functionality

**Comment by PikaMug** [comment]
Unofficial, third-party resource: https://lectern.browsit.org/resources/resource/16/
