### ISSUE TITLE
Unavailable planner quests in npcs

### ISSUE THREAD

**Issue by KingofAnomaly** [PikaMug/Quests#1991]
### What does your feature do?

Hide or label quests that are not available inside npcs like when quests are on cool down or only available at certain times. like how quests are able to be hidden when they don't meet requirements in the requirements section.

### How would people use it?

It could be used to have certain quests appear at certain times and make it easier for players to know which quests are available at the time. Weather they are on cool down or just set to only appear at certain times having these quests hidden makes it more user friendly for players so they don't click on them just to find out they can't do them.

**Comment by Beubeux74** [comment]
you can do this if you want, but it work for all quests
![image](https://user-images.githubusercontent.com/74351200/180280361-289c12cf-251c-4b1a-a70c-1a44a9f3426c.png)

**Comment by PikaMug** [comment]
@Beubeux74 I'm afraid `ignore-locked-quests` doesn't apply to Planner denials. 

Hiding quests with lack of Requirements makes sense as there's no way to take those, but with Planner denials it's currently the only way for Quests to inform the player how much time is left until it becomes available. Is there a just-as-good way to relay that information without third-party intervention? If not, then something like QuestsGUI would be better suited to handling this.

**Comment by KingofAnomaly** [comment]
maybe having planner quests that are not available could be a different color

**Comment by KingofAnomaly** [comment]
I am currently using the planner to have certain quests be available during certain days to give the daily quests more variety. Being able to toggle weather they show up or not would be helpful so they can't see all the quests the npc has and can only see them on the days they are available.

**Comment by PikaMug** [comment]
> maybe having planner quests that are not available be a different color like gold or red

Many servers already color-code their quest names, so that may not fly on some. We could append something like "(Unavailable)" to the name but I'm concerned about potential length and that users would be discouraged from clicking to reveal the time left. Perhaps we could add the time left "under" the lore of the item? That would definitely need a new config setting, in which case I'm again leaning toward QuestsGUI handling this. If users want more control over what appears in the lore, the future number of settings could get out of scope.

**Comment by KingofAnomaly** [comment]
maybe there could be another option for a quest to have a name when it is unavailable. By default this property could just be set to the quest name but it would give a lot more customization to how quests are displayed. You could also have a setting for the quest to not appear when unavailable.

**Comment by PikaMug** [comment]
A form of this has been added to QuestsGUI 0.47.
