### ISSUE TITLE
Delivery Items Name

### ISSUE THREAD

**Issue by MisterLolxd2** [PikaMug/Quests#1998]
### Where else have you looked for answers to this question?

I have a problem that I have a "deliver" quest created to an NPC, the item to be delivered is the player's head, the thing is that the quest won't accept a head that has a name (NBT). Is it possible for Quests to bypass the name check (NBT) of these player heads?

Sorry for my english.

### Share your question with as much detail as possible.

-

**Comment by PikaMug** [comment]
Same vein as https://github.com/PikaMug/Quests/issues/1929
