### ISSUE TITLE
Confirmation is not clickable

### ISSUE THREAD

**Issue by jnijland** [PikaMug/Quests#1999]
### What is your Quests version / build number (do *not* say "latest")?

4.5.2-b355

### Describe the problem and how to replicate it.

Server: git-Purpur-1748 (MC: 1.19.1)

I've created a quest with an NPC as starting point. I want users to be able to accept or deny the quest. The chat message which asks for confirmation is not clickable:
![image](https://user-images.githubusercontent.com/9889834/184003402-0a86e7cf-caf8-4e2f-8f57-c22ccae92f27.png)

No console errors are shown. I am using a chatmanager (ChatControl Red) but I also tried it without chat manager, and that also doesn't work. I have clickable prompts set to true in the config (```clickable-prompts: true```). 

### Any console errors to share?

```shell
No
```

**Comment by PikaMug** [comment]
Thanks for the report. It wasn't designed to be clickable.

**Comment by jnijland** [comment]
> Thanks for the report. It wasn't designed to be clickable.

Oh seriously? On Discord a moderator said the following: "It should be clickable already". 

But thank you :-)

**Comment by PikaMug** [comment]
I was wrong; this text was modified to be clickable late last year, but 1.19 appears to have broken this functionality.
