### ISSUE TITLE
 A bug where a page like a quest tutorial is displayed

### ISSUE THREAD

**Issue by gillthim** [PikaMug/Quests#2004]
### Where else have you looked for answers to this question?

already tried

・Search on the Internet
・Swapping plug-ins
・Delete user data
・Restart the server

### Share your question with as much detail as possible.

The quest plugin was working fine on my server, but suddenly I had a problem.

・"The Exotic Fruit" when you type the /quests editor command
You'll probably see a sample quest screen such as "a whole new world"

・The same screen will be displayed for quests started with commands set to walk with a plug-in called Script Block Plus.

・Things that have selected NPCs that start with the Quests function work without problems.

I didn't do anything in advance, and this symptom suddenly started to appear.

thank you.

**Comment by gillthim** [comment]
https://gyazo.com/e68a65cb8c0a8de9007da9393a3c8c8b

I have QuestsGUI installed.
This screen will appear
These BOOK icons are the

"The Exotic Fruit"
"a whole new world" quest

**Comment by PikaMug** [comment]
Please re-submit this as a Bug Report (not a Question). Also, this issue tracker is for Quests only; not QuestsGUI.

**Comment by gillthim** [comment]
sorry i will try again
