### ISSUE TITLE
A bug where a page like a quest tutorial is displayed

### ISSUE THREAD

**Issue by gillthim** [PikaMug/Quests#2005]
### What is your Quests version / build number (do *not* say "latest")?

Quests-4.5.2

### Describe the problem and how to replicate it.

already tried

・Search on the Internet
・Swapping plug-ins
・Delete user data
・Restart the server

The quest plugin was working fine on my server, but suddenly I had a problem.

・"The Exotic Fruit" when you type the /quests editor command
You'll probably see a sample quest screen such as "a whole new world"

・The same screen will be displayed for quests started with commands set to walk with a plug-in called Script Block Plus.

・Things that have selected NPCs that start with the Quests function work without problems.

I didn't do anything in advance, and this symptom suddenly started to appear.

thank you.

### Any console errors to share?

```shell
None
```

**Comment by PikaMug** [comment]
Thanks for the report. Can you please further explain the issue you are having? If translation is difficult, a screenshot might help.

**Comment by gillthim** [comment]
I understand

https://gyazo.com/2decb4f085a982dc54584784b4a04e6d
After typing /quests editor, a screen like this appears
I am unable to create or edit new quests.

Even if I restore the plugin and plugin folder to the previous state (backup)
This symptom does not improve

Thank you for your support

**Comment by PikaMug** [comment]
That screen is not part of this plugin (https://www.spigotmc.org/resources/3711/)

You appear to be using https://www.spigotmc.org/resources/23696/ instead.

**Comment by gillthim** [comment]
Thank you

I didn't care for the idea

Apparently it conflicted with the MMOCORE quest function

By using the full path, the original screen opened!
