### ISSUE TITLE
Rewards Message

### ISSUE THREAD

**Issue by WhosthisJulian** [PikaMug/Quests#2006]
### What does your feature do?

Hey, 
I would like to have a feature where the message that shows the rewards can be turned on and off. Would something like that be possible? Command rewards as message don't look so good :)

### How would people use it?

In Quests to look better

**Comment by PikaMug** [comment]
Use the details list override (selection 12 in image at https://pikamug.gitbook.io/quests/beginner/rewards).

**Comment by WhosthisJulian** [comment]
Thank you very much :)
