### ISSUE TITLE
Do you compile a Quests API plugin that goes into a quest folder, using IntelliJ, as a Spigot module? or a vanilla jar module?

### ISSUE THREAD

**Issue by badbabywentaway** [PikaMug/Quests#2007]
### Where else have you looked for answers to this question?

Spigot site, github, raw Google searches, Discord sites.

### Share your question with as much detail as possible.

I have my own plugin which I want to allow Quests to be able to access for requirements/goals. The code which accesses my plugin and the Quests API goes into Quests folder, granted that, but wanted to know if it's a raw jar that goes into the Quests folder or a jar compiled as a "separate spigot plugin." I'm using Intellij btw. 

If so, anything special that is needed for it to be built (other than including the API of course, and the maven/gradle resource additions lol)?

**Comment by PikaMug** [comment]
I'm not sure I understand the question. Quests will not attempt to interact with any plugin for which it is not already designed to hook into. If you are referring to a module (not a plugin), those would go in the /plugins/Quests/modules folder.

**Comment by badbabywentaway** [comment]
I was talking about the module that reides in Quests/modules.

I misphrased probably when I called the module I make for Quests/modules "plugin"

I have my own plugin that I'm trying to access from s Quests module. The question is do I compile the module as a Minecraft plugin or a vanilla java artifact?

**Comment by PikaMug** [comment]
You would compile the module as a Java archive (jar), same as a plugin, although a plugin.yml file is not necessary.
