### ISSUE TITLE
Can't use hex color codes but I was able to do

### ISSUE THREAD

**Issue by TheLaoming** [PikaMug/Quests#2009]
### What is your Quests version / build number (do *not* say "latest")?

Tested on 4.5.1-b348 & 4.5.3 latest from spigot.

### Describe the problem and how to replicate it.

So my problem is about **hex color codes** and using colors overall. Few weeks ago I was able to use hex colors in **strings.yml** like that:
§x§b§0§7§f§0§c (#b07f0c), but for some reason this bukkit method is not functional anymore. I didn't even updated quests so I don't know what changed since I started to work with Quests again. This code §x§b§0§7§f§0§c now take the last symbol and ignore the rest. So instead of this hex I get §c. Same with %#c89664% for example, it will be **c** color.
**Important note:** It works in quests.yml, it doesn't work in strings.yml.

So DeadlyKill told me, I have to use minimessage cuz Quests using it. But even minimessages doesn't work for me.
None of this works for me [https://docs.adventure.kyori.net/minimessage/format.html](url) Classic hex like on Quests wiki does not look functional as well (<#c89664>). Only functional method for me right now, is %green%, %blue%, %yellow% etc.
But how to use hex? I've tried also to restore lang folder, without changes. 
Everything from minimessage, or with hex codes looks like this: [https://i.imgur.com/3CuHohR.png](url)

### Any console errors to share?

```shell
No, there are no errors at all.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
I'm actually trying to use all of those in language file (string.yml), not in quests.yml. In quests.yml all of above methods works fine.
```

**Comment by PikaMug** [comment]
Thanks for the report. Quests does not currently use MiniMessage. Please see https://pikamug.gitbook.io/quests/casual/translations#formatting (hex color format is specified under the chart).
