### ISSUE TITLE
Allow hex code in strings.yml

### ISSUE THREAD

**Issue by TheLaoming** [PikaMug/Quests#2010]
### What does your feature do?

Basically in **strings.yml** you can use only %green%, %yellow% etc. format for colors. So my suggestion is pretty simple. Allow hex color codes in lang files. I don't know what happened in Quests past few months, but hex color codes doesn't work for me anymore (As I wrote here: [https://github.com/PikaMug/Quests/issues/2009](url)). I used bukkit method (§x§b§0§7§f§0§c). I can use hex codes in quests.yml, but not in strings.yml. That's the problem. My strings.yml contains a lot of bukkit hexes and those are broken now and displaying default colors.

### How would people use it?

**Possible formats:**
§x§b§0§7§f§0§c
<#b07f0c>
&#b07f0c
Or basically allow everything here in strings.yml:
[https://pikamug.gitbook.io/quests/casual/translations#formatting](url) not only %color% format.

**Comment by PikaMug** [comment]
Continued from #2009 

It appears there was a typo in the documentation. Example of current hex format is `%#c89664%`.

**Comment by TheLaoming** [comment]
> It appears there was a typo in the documentation. Example of current hex format is `%#c89664%`.

May I ask why hex codes doesn't work even with a new given format on github?
This should be brown color %#c89664% but in-game looks like red. This should be green color %#5fbd40% and it's black. It always takes the last letter from the code. Again as I said, It works only in **quests.yml** (tried rn). Can you take a look on it PikaMug ? Or I can also provide screenshots. For some reason I always get the default color, not hex.  There must be a difference betweeen these files.

**Comment by PikaMug** [comment]
@TheLaoming I've tested that and had no issues. `%#c89664%` appears brown and `%#5fbd40%` appears green.

Some things to try:
- Make sure there are no color codes interfering with the new color.
- Try placing `%reset%` just before your hex code.
- Check that your monitor settings are color accurate.
- Remove any chat-related client mods.
- Test another string in case the one you're using isn't supported.

**Comment by TheLaoming** [comment]
@PikaMug well from my testing, i've tried everything recommended from you.
I'm able to use hex for example in **goTo:** but not in **enterAnOption:**. For some reason in this dialogue my brown hex %#b07f0c% appears as the color of the last symbol (c). Also in goTo: i'm able to use old hex format §x§b§0§7§f§0§c. In enterAnOption I can't. 

But this is not only about this one string. I can't use it for example in questNPCListTitle or redoCompleted etc.
I can provide my strings.yml file if needed.

**Tested now without plugins.**
**Plugins:** Citizens, Quests (with Mythicmobs kill module), QuestsGUI, Forceresourcepakcs
[https://i.imgur.com/e20E9dw.png](url)
