### ISSUE TITLE
Quest Markers over Npc Head

### ISSUE THREAD

**Issue by apatuka** [PikaMug/Quests#2013]
### What does your feature do?

Greetings, i wondering if its possible to add Quest Markers as 
Attaching example
![imagen](https://user-images.githubusercontent.com/1668954/188273813-e606aa37-ccd7-4a52-a775-8a1b6808f085.png)

And make it customizable through config so we can modify what to show over NPC (Im intending to use Resource Pack glyphs to use icons)

If no Quest Market Customization is made through config, the custom Noteblock particle can be used

Thank you very much

### How would people use it?

This adds an amazing flavour to players eyes. I hope it can get added.

**Comment by PikaMug** [comment]
This already exists under the `npc-effects` node in your _config.yml_ file. If you're not seeing them in-game, make sure all particles are enabled in your Minecraft client settings.
