### ISSUE TITLE
Confirmation is (still) not clickable on 1.19.2

### ISSUE THREAD

**Issue by jnijland** [PikaMug/Quests#2017]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.5.3-b359

### Describe the problem and how to replicate it.
```
Server version: 
Current: git-Purpur-1778 (MC: 1.19.2)*
Previous: git-Purpur-1777 (MC: 1.19.2)
```

Unfortunately, I made an Git issue before, for the same problem #1999 .. The solution provided sounded promising, but it didn't fix the problem for me 😞 

I am using a chatmanager (ChatControl Red). When a user clicks an NPC with a quest, the confirmation message is not clickable (the "Accept quest? Yes / No" message). Of course players can enter 'yes' or 'no' in the chat, and that works fine, but when looking at UX I prefer the message to be clickable. 

This problem might be ChatControl related, I'm not sure. I've tried a bunch of random things myself to fix this problem. For example, I've tested every CHAT LISTENER PRIORITY level possible in the ChatControl Red configuration. Nothing seems to work.

### Any console errors to share?

```shell
Nope
```

**Comment by PikaMug** [comment]
Have you tried temporarily removing ChatControl? Please do so to affirm whether this is a plugin conflict.

**Comment by jnijland** [comment]
> Have you tried temporarily removing ChatControl? Please do so to affirm whether this is a plugin conflict.

I've tried it on a empty server, unfortunately it still does not work. The issue doesn't seem to be ChatControl Red related.

**Comment by PikaMug** [comment]
Thanks for the information. Please also check whether the player has the `quests.choice` permission.

**Comment by jnijland** [comment]
> Thanks for the information. Please also check whether the player has the `quests.choice` permission.

I've checked this, player has the permission so it doesn't seem to be a permission issue unfortunately:
![image](https://user-images.githubusercontent.com/9889834/190672076-3c208467-f6db-47c3-a071-de06aa2c80d5.png)

**Comment by PikaMug** [comment]
Just tested with git-Purpur-1778 and clicking editor prompts work but, as described, the Yes / No for accepting a quest from NPC does not. Will investigate this issue further soon.
