### ISSUE TITLE
Mining Quest

### ISSUE THREAD

**Issue by XxTroy90xX** [PikaMug/Quests#2019]
### What is your Quests version / build number (do *not* say "latest")?

1.19.1 
Curseforge/fabric

### Describe the problem and how to replicate it.

So, i was the first in my server to try out the questing system. i got the fishing and mobs one to work but i cannot get the mining one to work. i dont know what im doing wrong. 
At first i was confused, it stated i needed a stone pickaxe to start. I had one but not a FRESH pickaxe(that should be stated or changed). i made one then was able to get the quest. So now i need to break 2 iron ore blocks. i broke 10 and no advancement or anything. 

### Any console errors to share?

```shell
N/a
```

**Comment by PikaMug** [comment]
1.19.1 is not a valid Quests version and we do not currently support Fabric.
