### ISSUE TITLE
questbook ist very buggy

### ISSUE THREAD

**Issue by Paddiii-Pixeltopia** [PikaMug/Quests#2024]
### What is your Quests version / build number (do *not* say "latest")?

4.6.0-b361

### Describe the problem and how to replicate it.

Not all tasks are displayed in the quest book, only as many as fit on one book page

### Any console errors to share?

```shell
no
```

**Comment by Paddiii-Pixeltopia** [comment]
![image](https://user-images.githubusercontent.com/71345116/199352736-9bc4c0fd-c7dc-46c8-ba31-0c552acfc53e.png)

**Comment by PikaMug** [comment]
Duplicate of #1946
