### ISSUE TITLE
 translation bug

### ISSUE THREAD

**Issue by ProGaspar146** [PikaMug/Quests#2025]
### What is your Quests version / build number (do *not* say "latest")?

The version used is "Quests 4.6.0-b361" last update

### Describe the problem and how to replicate it.

My problem is that some messages are not translated. Example, the title or the objective messages of when a mission begins is not translated into Spanish, although the file (strings) continues to show that it is... And the other commands/messages are well translated
-Google Translate

### Any console errors to share?

```shell
no
```

**Comment by PikaMug** [comment]
Can you provide an example of one of the strings not being translated? Either a screenshot or just copy/paste.

**Comment by ProGaspar146** [comment]
![image](https://user-images.githubusercontent.com/117217032/200129115-a5b9fb39-d62f-4c6a-93b9-26069d4420e0.png)
![image](https://user-images.githubusercontent.com/117217032/200129125-89c38403-1fa3-4ffd-a73f-2e802bbf9ec1.png)
These are some messages, they are not all but there are more...

**Comment by PikaMug** [comment]
Please share your config.yml file (remove any sensitive information).

**Comment by ProGaspar146** [comment]
![image](https://user-images.githubusercontent.com/117217032/200211962-abc1ac10-18fe-4064-a478-d2e3ab021215.png)
I don't know what the sensitive options are but I think they are the ones I deleted

**Comment by PikaMug** [comment]
Thanks for sharing. As of recent versions, the `language` is for editor/administrative strings only. Text which is shown to all players, like those in your screenshot, are controlled by the client language (in your case, English). You can override this behavior and force everyone to see Spanish by setting `language-override-client: true`.
