### ISSUE TITLE
saving quests.yml no quests showing ingame

### ISSUE THREAD

**Issue by evinxnl** [PikaMug/Quests#2026]
### Where else have you looked for answers to this question?

quests.yml

### Share your question with as much detail as possible.

hi there i made many quest in chat but after my last quest there was only 1 quest visible ingame

so i opened quests.yml to see if there was something wrong after saving that file no all quests are gone ?

what am i doing wrong ?

attachment screenshot of chat 0 quest
attachment quest.yml with 3 quests in it
![2022-11-10_19 31 45](https://user-images.githubusercontent.com/81700899/201178781-45a46ef9-7de6-4c44-a157-d5f5e4155da8.png)

[redacted]

**Comment by PikaMug** [comment]
Please submit this as a bug report. If you decide to include quests, copy/paste or use Pastebin/Hastebin instead of uploading. Check your startup log for any console errors and include them in your report.
