### ISSUE TITLE
Please Readd Custom Item Names Inside Quest Journal

### ISSUE THREAD

**Issue by Superfudge247** [PikaMug/Quests#2028]
### What does your feature do?

The Quest journal is super confusing as I cannot see the correct item sort of

For Example it will say "Deliver Raw Cod to <NPC>"

However I have a server with custom items and a custom fishing plugin
which has over 100 types of fish that all use the same 4 textures/items pufferfish, raw salmon, tropical, raw cod

In older versions of the Quest plugin the items custom name would show inside the journal which meant if I had to catch a Bream or a Eel or some other fish I knew what to catch!

I ask that you please consider readding custom item names to the journal.

### How would people use it?

It would work the same as item type but just consider showing the item name as priority

**Comment by PikaMug** [comment]
@Superfudge247 Thanks for the suggestion. Please try https://ci.codemc.io/job/PikaMug/job/Quests/372/
