### ISSUE TITLE
The console is getting flooded with 'Party provider not found'

### ISSUE THREAD

**Issue by RetroB** [PikaMug/Quests#2030]
### What is your Quests version / build number (do *not* say "latest")?

The version is 4.6.0-b361 . Used in a 1.19 Spigot server.

### Describe the problem and how to replicate it.

I installed the Parties plugin and Unite. Since the Parties install the console has been flooded with '[Quests] Party provider not found.'
![image_2022-11-19_124311272](https://user-images.githubusercontent.com/57542645/202859062-b4402a82-1495-4785-a43c-f66ae096f82e.png)

### Any console errors to share?

```shell
[Quests] Party provider not found.
[Quests] Party provider not found.
[Quests] Party provider not found.
[Quests] Party provider not found.
And it goes for hours...
```

**Comment by DeadlykillOfficial** [comment]
Which parties plugin you installed?

**Comment by PikaMug** [comment]
Parties integration is included in Quests. Only use Unite if another plugin needs it.

**Comment by RetroB** [comment]
.-. bruuh
