### ISSUE TITLE
"That player cannot be found"?

### ISSUE THREAD

**Issue by MisterLolxd2** [PikaMug/Quests#2033]
### Where else have you looked for answers to this question?

What may be a problem that players after starting the task and end of quest and checking the progress under the command /quest displays the message: "That player cannot be found", and progress didn't be send.

Server version: PapierSpigot 1.8.8
Java version: 17
Quest Version: 4.6.1-b373

### Share your question with as much detail as possible.

 [19:21:32 INFO]: [Quests] 93942c05-29ca-3811-a67e-160fb7371cdb started quest EAT THE GOLDEN APPLE
 [19:21:32 INFO]: That player cannot be found

**Comment by PikaMug** [comment]
Those strings are not from this plugin. Another resource must be overriding the command.

**Comment by MisterLolxd2** [comment]
Interesting, after the update to 4.6.1, these messages began to show...

**Comment by PikaMug** [comment]
That first message is from Quests, but has been for several versions now. You should be able to adjust it by setting `console-logging` as described at https://pikamug.gitbook.io/quests/setup/configuration#config.yml

Second one is likely from a default Minecraft command (i.e. /tellraw, /give).
