### ISSUE TITLE
/Questsadmin reload  doesnt seem to work

### ISSUE THREAD

**Issue by Flowishloz** [PikaMug/Quests#2034]
### Where else have you looked for answers to this question?

![Screenshot_20221125_232220](https://user-images.githubusercontent.com/107678277/204062788-8b407fe8-70fa-4723-afaf-5736412e8190.png)

### Share your question with as much detail as possible.

I then restart my server to try and get my new quest to appear that way. But when i do /quests i get this new message instead.

![image](https://user-images.githubusercontent.com/107678277/204081994-c1e72fae-213e-43a7-aeda-a692b08f5893.png)

Really don't know what else to do.

Love the plugin btw

**Comment by PikaMug** [comment]
One of your quest requirements is broken, perhaps from having edited the file manually. Feel free to share your _quests.yml_ file if you'd like further support.

**Comment by Flowishloz** [comment]
Thanks a bunch, here's the link to the download https://mega.nz/file/bYBRxKzI#i7Ko3cbEho3-ErqPm5i3trLvN2T8bVo_ncUSGGO8GUM

**Comment by PikaMug** [comment]
@Flowishloz Please either upload the file directly or use a service like Pastebin/Hastebin.

**Comment by Flowishloz** [comment]
https://pastebin.com/LJyn4K7L

**Comment by PikaMug** [comment]
Thanks for that. Observe the following text from the `default1` quest:
```yml
requirements:
  items:
    - null
  remove-items:
    - false
```

Items are null, which is not right. Remove all of the above lines from above, leaving no space, then save it and restart (not /reload) your server. Add a new item requirement if desired.

**Comment by Flowishloz** [comment]
Thank you!
