### ISSUE TITLE
leave the game the quest resets  1.19.2

### ISSUE THREAD

**Issue by danyadanya2005** [PikaMug/Quests#2035]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.6.1
logs https://pastebin.com/q2mdrrHp
Purpur version git-Purpur-1833 (MC: 1.19.2) 

### Describe the problem and how to replicate it.

hi people help me please
I take the quest for 20 hours. but if i leave the game the quest resets i need to take the quest again
How to fix it? so that the quest resets after 20 hours?
https://youtu.be/4GX6VI-9mzg

### Any console errors to share?

```shell
no
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/4nxWZLkP   does not work. when leaving the server, the quest is deleted from the player
```

**Comment by PikaMug** [comment]
You have not specified a start and end date. Also, since you have a player cooldown of only 9 hours, the quest might be available again once that cooldown expires. Read more at https://pikamug.gitbook.io/quests/beginner/planner
