### ISSUE TITLE
Chat message validation failure

### ISSUE THREAD

**Issue by mrawesome35700** [PikaMug/Quests#2038]
### What is your Quests version / build number (do *not* say "latest")?

4.6.0-b361

### Describe the problem and how to replicate it.

everyone got kicked from server with the message "Chat message validation failure" when someone clicked on an NPC to accept a quest.

### Any console errors to share?

```shell
I don't have any codes since the owner is unable to reach his computer.
```

**Comment by PikaMug** [comment]
Assuming this has anything to do with Quests, it's not something I can easily diagnose without a console error. Request that the owner open a new issue when ready (also tell them to update to version 4.6.1).
