### ISSUE TITLE
Quest Quit Options

### ISSUE THREAD

**Issue by CraftXpNetwork** [PikaMug/Quests#2039]
### What does your feature do?

As I understand the plugin currently, when a player quits a quest, it simply ends the quest and allows the player to then re-initiate it as soon as they quit.

I think it would be helpful to have an option for when players quit quests, similar to the rewards options for when a player completes a quest, where it can run a special dialogue, execute commands, and also maybe institute a delay for when the player can try again after quitting.

### How would people use it?

Right now, for "fetch quests", we have to be very careful on how we design them or what items we use, as when given items to deliver, players can quit a quest and simply restart it and just get many duplicates of the item they are meant to deliver. 

With options like the ones listed above- we could implement a cool down so that players will still have to wait until the usual cool down reset before attempting the quest again, encouraging them to simply complete the quest instead of using it to farm items.

And if we want quests to include vary valuable items, we could have it run commands upon quitting that charge the player for the item's value, maybe throw -em in the prison for a minute, and a fun little message about trying to steal the merchandise :)

**Comment by PikaMug** [comment]
Finish Action https://pikamug.gitbook.io/quests/casual/action-editor

**Comment by CraftXpNetwork** [comment]
Maybe I'm misunderstanding something, but the "finish action" feature does not activate when a player quits a quest- it activates when the player completes a stage. Not sure if it is supposed to activate when a player quits/abandons a quest? I was referring to having a way to activate some kind of action upon specifically quitting an active quest, but only if the player quits, not if they complete the stage or disconnect etc.

**Comment by PikaMug** [comment]
Sorry, I should have explained. Disable quitting under Edit Options, then use Finish Actions at the end of stages where you would like to to insert dialogue, execute a command, etc. For anything complex, use a Denizen script. Use the Edit Planner selections for cooldowns.
