### ISSUE TITLE
chat message validation failure

### ISSUE THREAD

**Issue by JeremyMilam1** [PikaMug/Quests#2043]
### What is your Quests version / build number (do *not* say "latest")?

4.6.1 running on Paper version: Paper version git-Paper-131 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 2da891f)

### Describe the problem and how to replicate it.

Upon addition of the "latest" version of 4.6.1 to my 1.19.2 paper server, I began messaging in chat after a previous attempt gave the error of "chat message validation failure" and booted everyone from the server. With this attempt I used a brand new clean installation of Quests and a freshly generated folder for the config. At this time, no "quests" were written. Upon using the in-game chat Quest creation, I made and completed a quest to break 10 "Oak_Log" blocks and gained reward of "64 Red Sand." The quest worked as expected, without error. Seconds after completion of the quest I typed "Test" into chat and the server disconnected everyone again with message of "chat message validation failure." 

### Any console errors to share?

```shell
[Sat 19:17:30 INFO  Quests] Player 69ccecd9-1a0d-44f3-b59f-5ef735645e42 saved quest Lumbermill
  [Sat 19:17:34 INFO  Server/PlayerConnection] JeremyMilam1 issued server command: /questsadmin reload
  [Sat 19:17:34 INFO  Quests] Loaded language en-US. Translations via Crowdin
 (edited)
[2:17 PM]
  [Sat 19:17:38 INFO  Quests] 69ccecd9-1a0d-44f3-b59f-5ef735645e42 started quest Lumbermill
  [Sat 19:17:49 INFO  Server/PlayerConnection] JeremyMilam1 issued server command: /gms
  [Sat 19:17:54 INFO  Server/PlayerConnection] __LampShade__ lost connection: Disconnected
  [Sat 19:17:54 INFO  Server] __LampShade__ left the game
  [Sat 19:18:29 INFO  Server] [OOC][Borin] Sky God Castiel_Deorum: Test
  [Sat 19:18:29 INFO  Server/PlayerConnection] JeremyMilam1 lost connection: Disconnected
  [Sat 19:18:29 INFO  Server] JeremyMilam1 left the game
  [Sat 19:18:29 INFO  Server/PlayerConnection] WaxFlower110098 lost connection: Disconnected
  [Sat 19:18:29 INFO  Server] WaxFlower110098 left the game


Console shows us as having "lost connection: Disconnected" however what we as users see on client screen is "chat message validation failure."
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
I do not believe it is applicable, as it has happened regardless of the quest or components of a quest that I used. I can write a new quest to test and upload here if need be.
```

**Comment by PikaMug** [comment]
Similar to #2038 but still not convinced this has anything to do with Quests.
