### ISSUE TITLE
Quest Actions - Revised

### ISSUE THREAD

**Issue by JeremyMilam1** [PikaMug/Quests#2045]
### What is your Quests version / build number (do *not* say "latest")?

4.6.1 with "Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version"

### Describe the problem and how to replicate it.

The quests.actions.* permission does not appear to work with the above versions. I gave a user quests.actions.* as well as each individual permission node associated with "actions" without success. It is met with the standard "No permission" message. When the user is given OP, it works without issue, which indicates (at least to me) that it is something on the end of the permission node. I additionally checked the discord and attempted to give quests.actions permission node without success. I additionally tried with quests.* without success.

### Any console errors to share?

```shell
Not applicable, as it is a permissions issue.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
It does not call on a specific quest as it is a permissions issue.
```

**Comment by PikaMug** [comment]
Thanks for the report. What are you using for permissions? LuckPerms?

**Comment by JeremyMilam1** [comment]
I am using GroupManager for permissions.

**Comment by JeremyMilam1** [comment]
Update: Attempted with legacy permissions as well, and no success.

**Comment by PikaMug** [comment]
I had no issues with this permission node through LuckPerms or GroupManager. The commands used were:

GroupManager
`/manuaddp <player> quests.actions.*`

LuckPerms
`/lp user <player> permission set quests.actions.*`

Make sure you have spelled the permission node correctly and that there are no conflicting negative permissions.

**Comment by JeremyMilam1** [comment]
I just, to confirm, copy and pasted the command that you provided and it still does not work. It states the user already has access to that permission node.

**Comment by PikaMug** [comment]
What is the "no permission" message that you get? Can you please share it verbatim.

**Comment by JeremyMilam1** [comment]
The user can open up the actions list (options 1-4) but upon typing any of the numbers receives "You do not have permission to do that." in response.

**Comment by PikaMug** [comment]
Here's the code where you're getting stuck:
https://github.com/PikaMug/Quests/blob/df2716074fc9ea9f6d3621934147dfbae7af0fbc/core/src/main/java/me/blackvein/quests/commands/quests/subcommands/QuestsActionsCommand.java#L60-L75
Note that "noPermission" is the string you're getting. As you can see, the command will work as long as your permission handler claims that the player has one of those permissions (which OPs have by default). So perhaps the next course of action is to backup your permissions database and start fresh.

**Comment by JeremyMilam1** [comment]
I converted our GM over to Luckperms and it now works. Thank you.
