### ISSUE TITLE
QuestsGUI bug 

### ISSUE THREAD

**Issue by sciqni** [PikaMug/Quests#2050]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.6.1
QuestsGUI 0.51

### Describe the problem and how to replicate it.

When in the config of questGUI in list: i put click-to-take: true, the lore of the item i put in the config quests.yml disappears and is replaced by the text in questGUI config.yml.

### Any console errors to share?

```shell
No
```

**Comment by PikaMug** [comment]
This issue tracker is for Quest support only. If you need help with QuestsGUI, use the SpigotMC discussion thread or the associated Discord.

I'll leave your other ticket open pending further investigation.
