### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by sciqni** [PikaMug/Quests#2051]
### What does your feature do?

Can you add in QuestsGUI a config to edit /quests list and /quests journal gui?

### How would people use it?

whit a file yml and edit the gui as they want.

**Comment by PikaMug** [comment]
This issue tracker is for Quests support only. If you need help with QuestsGUI, use the SpigotMC discussion thread or the associated Discord.

I'll leave your other ticket open pending further investigation.
