### ISSUE TITLE
NPC talking during quests

### ISSUE THREAD

**Issue by DavidCepak** [PikaMug/Quests#2056]
### Where else have you looked for answers to this question?

I looked for this everywhere and cant find a good fix

### Share your question with as much detail as possible.

I could not figure out how to make npcs talk at like stage1 of the quest. There is an option in quests plugin that lets you select "talk to npc" but that only commands you to right click it... how would i make it talk there?

**Comment by PikaMug** [comment]
Citizens has a text editor (https://wiki.citizensnpcs.co/Editors#Text_Editor), or you can use Interactions (https://pikamug.gitbook.io/quests/casual/modules#interactions) or a similar resource.

For questions that are not complex or code-related, use the community Discord (https://discordapp.com/invite/QdJAv2G7qg)
