### ISSUE TITLE
Blocking commands for commands with subparameters

### ISSUE THREAD

**Issue by XGNRen** [PikaMug/Quests#2057]
### What does your feature do?

Not sure if this is necessarily a bug or simply a lack of feature, but for quests which are designed to block commands or fail users for running commands during quests, the quest will not block subparameters. This is incredibly annoying when trying to fail users for teleporting away via something like an EssentialsX warp or Factions3 faction warp.

### How would people use it?

Right now blocking commands with Quests is extremely limiting, and I don't really see any drawbacks with adding a feature like this to better allow adjustment of limitations for quests.

Example: Quest is set to block the command "/f warp go". User runs "/f warp go WarpName". Quests will not fail/command is not blocked.

Proposal: Add a toggle for including anything following the base command in the command input, so if the command set to be blocked is "/f warp go", the user will not be failed if running "/f warp" or "/f", but will be failed for running "/f warp go" or "/f warp go WarpName".

**Comment by PikaMug** [comment]
Please describe how you're blocking commands with Quests, or share the relevant files.

**Comment by XGNRen** [comment]
I have a command-events list and the commands I want to block are listed under command-event-triggers, like this:

command-events:
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
          - CommandFailDelivery
command-event-triggers:
          - home
          - f warp go
          - warp
          - spawn
          - mv tp
          - mvs
          - plot tp
          - plot home
          - plot visit
          - tpa
          - tpaccept


The CommandFailDelivery action is set to fail the quest, and print a message.

**Comment by PikaMug** [comment]
@XGNRen Please try https://ci.codemc.io/job/PikaMug/job/Quests/381/

**Comment by XGNRen** [comment]
Thanks! I'll give this a try right now!

**Comment by XGNRen** [comment]
That fixed it! Thank you so much, this has been a very big problem for me for a long time!
