### ISSUE TITLE
Make Quest Completeable once

### ISSUE THREAD

**Issue by Drizzt11** [PikaMug/Quests#2059]
### Where else have you looked for answers to this question?

I looked through the wiki and expecially in planner and couldnt find my answer.

### Share your question with as much detail as possible.

I dont know how to make a quest only completable once. Do I ignore setting planner? Or do I have to put a value in it.

**Comment by PikaMug** [comment]
For questions that are not complex or code-related, use the community Discord (https://discordapp.com/invite/QdJAv2G7qg)
