### ISSUE TITLE
SkillAPI Module Error

### ISSUE THREAD

**Issue by jayofearth** [PikaMug/Quests#2060]
### What is your Quests version / build number (do *not* say "latest")?

4.6.1

### Describe the problem and how to replicate it.

I'm running a paper 1.19.3 server with the latest file from Spigot directory.

Install the plugin and start the server

### Any console errors to share?

```shell
https://pastebin.com/un6KJWbZ
```

**Comment by PikaMug** [comment]
The SkillAPI module is very old and no longer compatible. Reach out to its developer.

**Comment by jayofearth** [comment]
The SkillAPI module is included in the download of your plugin. It's no longer developed and has been picked up as ProSkillAPI. This error will occur for anyone downloading your plugin. Please reconsider and remove the module from the plugin's default download.

**Comment by PikaMug** [comment]
> The SkillAPI module is included in the download of your plugin. It's no longer developed and has been picked up as ProSkillAPI. This error will occur for anyone downloading your plugin. Please reconsider and remove the module from the plugin's default download.

No, it is not. The module is included in SkillAPI; not Quests.
