### ISSUE TITLE
New reset command

### ISSUE THREAD

**Issue by 1Pootis1** [PikaMug/Quests#2067]
### What does your feature do?

Make it possible to reset the statistics of a specific quest for a player, and not all, as is done now (/qa reset [player])

### How would people use it?

People would be much more comfortable with this.

**Comment by PikaMug** [comment]
`/questadmin remove [player] [quest]`

**Comment by 1Pootis1** [comment]
> `/questadmin remove [player] [quest]`

but no, after entering this command, the player can never take the quest at all

**Comment by 1Pootis1** [comment]
after entering this command, I can no longer take the quest that I "reset"

**Comment by PikaMug** [comment]
All that command does is remove the quest from that player. It should not prevent them from taking it again. Perhaps the quest has a [Requirement](https://pikamug.gitbook.io/quests/beginner/requirements) set that they would no longer meet.

**Comment by 1Pootis1** [comment]
> All that command does is remove the quest from that player. It should not prevent them from taking it again. Perhaps the quest has a [Requirement](https://pikamug.gitbook.io/quests/beginner/requirements) set that they would no longer meet.

![image](https://user-images.githubusercontent.com/73141732/215007645-670173e9-9f1a-4c33-812a-28ae8be95ef9.png)

Here is the requirement in the screenshot: "cheaters.quest.get", I have it, before that I could take the quest, after the command was written, I can no longer take the quest
Here is a screenshot, at first a message about the execution of the command is on it and after that it writes to me "there are no more available tasks", this is not when the player does not have permission, but simply there are no tasks, although I could take this quest BEFORE writing the command

![image](https://user-images.githubusercontent.com/73141732/215007744-7e57f375-d82e-4a15-9f27-324e50acbda7.png)
