### ISSUE TITLE
Beacon Highlight Current Objective

### ISSUE THREAD

**Issue by TheSowut** [PikaMug/Quests#2069]
### What does your feature do?

During each stage of the quest add the possibility to place a custom beacon location that will help the players find the objective easier. Imo this would be universal for all types of quests, since it fits any use case. Here are some examples:

> The player has to do a fetch quest, during the Item fetching part, mark the Item location with a beacon. During the delivery part, mark the npc to be delivered to with a beacon.

> The player is tasked with slaying Monsters found in a specific zone. Mark the zone with a beacon.  

### How would people use it?

It's of passive use. The player sees the beacon, the player follow it to complete the quest.

**Comment by PikaMug** [comment]
This seems outside the scope of Quests. Simply use a Reach Location objective at the site of your beacon.

If you want a beacon effect without the block present, that would be suited to a module.
https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features
