### ISSUE TITLE
Make player not able to choose a quest

### ISSUE THREAD

**Issue by akex06** [PikaMug/Quests#2075]
### Where else have you looked for answers to this question?

I've tried to search on the documentation/wiki but haven't found anything as well as some youtube tutorials for the plugin

### Share your question with as much detail as possible.

I've made multiple quests for an npc, when I click the npc it makes me choose a quest although I've esablished quest requirements so you need to complete them in an order, is there a way for not making hte player choose and giving the player the quest directly?
![image](https://user-images.githubusercontent.com/67469268/221383588-fda7a59b-7918-453b-a071-424923fc353d.png)

**Comment by PikaMug** [comment]
You might be able to do this by setting `ignore-locked-quests: true` in your _config.yml file, but otherwise restrict your NPCs to a single quest.

**Comment by akex06** [comment]
Yep, it was that, thanks
