### ISSUE TITLE
Plugin is currently loading. Please try again later.

### ISSUE THREAD

**Issue by timothykra** [PikaMug/Quests#2082]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.7.2

I tried doing /quests info and it does not work so that is all the information I have from my file access

### Describe the problem and how to replicate it.

When the server loads up and you do any quests command, it says "Plugin is currently loading. Please try again later". You cannot do any quests or run any questadmin command. The console error says that custom6 needs to before custom7 or something like that so I moved around the order and tried to get them in the the correct number order but then all the quests disappeared

### Any console errors to share?

```shell
https://pastebin.com/BYu56EkL
```

**Comment by PikaMug** [comment]
Re-ordering your quests should not make them disappear as long as the formatting is kept accurate (correct number of space, no tabs, et al.). Using a YAML parser like [this one](https://codebeautify.org/yaml-parser-online) (not affiliated) can help check your work.

I'll leave this opening until I can take a look at the code for quest requirement loading, but as I recall there wasn't a good way to resolve this issue last I checked. Pull requests welcome.

**Comment by PikaMug** [comment]
Was able to find some time for this. Should be resolved in this build, but if you have any quest requirements saved by name rather than ID (which only happened in old versions of Quests), you'll have to update them manually:

https://ci.codemc.io/job/PikaMug/job/Quests/399/

**Comment by timothykra** [comment]
Oh wow thank you so much
