### ISSUE TITLE
Follow-up on Spigot review 

### ISSUE THREAD

**Issue by KayaLambrechts** [PikaMug/Quests#2086]
### Where else have you looked for answers to this question?

not applicable

### Share your question with as much detail as possible.

I mentioned the language file's odd approach to colour coding, and I was asked to open an issue on GitHub.

The issue I had, was, that Quests uses multiple different ways of colour-coding things. For quests.yml, the format used in the lang file doesn't work (<colour> vs %colour%). If an option is coloured, like the section below;

delay: "Delay"
save: "Save"
exit: "Exit"
exited: "Exited"
cancel: "Cancel"
cancelled: "Cancelled"
questTimeout: "Cancelled."
yesWord: "Yes"
noWord: "No"
"true": "true"
"false": "false"
clear: "Clear"
cleared: "Cleared"
none: "None"
done: "Done"

it causes the options to not work properly, as tabcompleting them would include the colour.
Besides that, I'm glad you're open for feedback. Some messages are hardcoded in the plugin, and when I asked if that could be changed, I was told to change it myself and submit the changes to GitHub. Though I'd love to, I don't have the knowledge to do so. If possible, that'd be nice to have changed.

**Comment by PikaMug** [comment]
Just to note, the formatting for language files is described at https://pikamug.gitbook.io/quests/casual/translations#formatting

Although the decision to use `%` in language files was made before my time with the plugin, it does help differentiate between formatting and string replacements like `<cancel>`, `<clear>`, et al. Is there a different character you would prefer for formatting, or did you have another solution in mind?

Also, none of those strings you shared are available for tab completion afaik. Only a few such as `COMMAND_LIST` are, to my knowledge, and you wouldn't want to add formatting to those anyway.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
