### ISSUE TITLE
Linkage error

### ISSUE THREAD

**Issue by robtbs** [PikaMug/Quests#2089]
### Where else have you looked for answers to this question?

05.04 04:30:40 [Server] INFO [Quests] Enabling Quests v4.8.0-b400
05.04 04:30:40 [Server] INFO [Quests] Loaded language en-US. Translations via Crowdin
05.04 04:30:40 [Server] WARN [Quests] Citizens was detected, but is not enabled! Fix Citizens to allow linkage.
05.04 04:30:40 [Server] WARN [Quests] WorldGuard was detected, but is not enabled! Fix WorldGuard to allow linkage.
05.04 04:30:40 [Server] WARN [Quests] mcMMO was detected, but is not enabled! Fix mcMMO to allow linkage.
05.04 04:30:40 [Server] INFO [Quests] Loading storage implementation: YAML
05.04 04:30:40 [Server] WARN [Quests] Citizens was detected, but is not enabled! Fix Citizens to allow linkage.

### Share your question with as much detail as possible.

Someone knows whats going on?

05.04 04:30:51 [Server] INFO [Citizens] Enabling Citizens v2.0.31-SNAPSHOT (build 2979)
05.04 04:30:52 [Server] INFO [Citizens] Loading external libraries
05.04 04:30:52 [Server] INFO [PVP Arena] PVP Arena is up to date
05.04 04:30:52 [Server] INFO [PVP Arena] PVP Arena modules are not detected
05.04 04:30:52 [Server] INFO [PlaceholderAPI] Successfully registered expansion: citizensplaceholder [1.0.0]
05.04 04:30:52 [Server] INFO [Citizens] Loaded economy handling via Vault.
05.04 04:30:52 [Server] INFO [Shopkeepers] Enabling Shopkeepers v2.16.5
05.04 04:30:52 [Server] INFO [Shopkeepers] Citizens found: Enabling NPC shopkeepers.
05.04 04:30:52 [Server] INFO [TradeSystem] Enabling TradeSystem v2.3.0

other plugins are able to link

**Comment by PikaMug** [comment]
Most likely there are startup errors that haven't been addressed. Please check your server log.
