### ISSUE TITLE
Quests requirements doesn't work!

### ISSUE THREAD

**Issue by MisterLolxd2** [PikaMug/Quests#2091]
### What is your Quests version / build number (do *not* say "latest")?

4.8.1-b404

### Describe the problem and how to replicate it.

As in the title, the quest requirements don't work.
In the video you can see how I take quest 9, which requires the configuration to perform the previous quest 8, but it is not taken into account at all, so I can take any quest, and the requirements for these quests are simply ignored ;-;

Video: https://www.youtube.com/watch?v=9Z8BOdRetDI&ab_channel=Trawka

### Any console errors to share?

```shell
Nope. 0 errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/ZEkLvcbJ
```

**Comment by PuppyNomNom** [comment]
Yah I have the exact same issue

**Comment by PikaMug** [comment]
Should be resolved in https://ci.codemc.io/job/PikaMug/job/Quests/405/
