### ISSUE TITLE
Yes and no word keys translation

### ISSUE THREAD

**Issue by CptToastey** [PikaMug/Quests#2094]
### Where else have you looked for answers to this question?

Documentation

### Share your question with as much detail as possible.

Is it possible to translate the yes- and no word keys? If I change it to something else, the plugin says, my choice is invalid

yesWord: "Yes"
noWord: "No"

thanks in advance!

**Comment by PikaMug** [comment]
It is possible, yes. Just changed noWord to "Nah" and was able to enter that for the quest accept prompt (_/quests take <quest_). If you're on the latest version of Quests and still having trouble, please create a new ticket as a Bug Report and make sure to mention which prompt you're entering text into.
