### ISSUE TITLE
Unknown Error Occured

### ISSUE THREAD

**Issue by Foxersthe** [PikaMug/Quests#2097]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.8.1

### Describe the problem and how to replicate it.

I'm getting a "An Unknown Error has occured. See Console output" error when interacting with some Quests npcs. I cannot start certain quests because of it and requirements listed on some quests are incorrect. I check the console but there's no new output from where I interacted with the npc.

### Any console errors to share?

```shell
https://pastebin.com/zqgZ2x5n
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/0Cm3BtTv
```

**Comment by PikaMug** [comment]
@Foxersthe Thanks for the report. Please confirm whether this occurs on the latest development build:
https://ci.codemc.io/job/PikaMug/job/Quests/406/

**Comment by Foxersthe** [comment]
It fixed most of the quests I had trouble with. I just redid the one that didn't work, which I edited to clear a module I wasn't using; it was giving that error and like before it seemed to open up the editor. So so far it seems to work. Thank you!
