### ISSUE TITLE
Multi-economy & multi-currency support

### ISSUE THREAD

**Issue by RGG200** [PikaMug/Quests#2098]
### Where else have you looked for answers to this question?

I looked for it on your repository

### Share your question with as much detail as possible.

Hello. So I made an economy plugin that is based upon local economies & multiple local currencies. So, I was wondering if your plugin support multiple currencies and economies and if not could you add support for that or my plugin please ?

**Comment by PikaMug** [comment]
Quests supports economy plugins through [Vault](https://www.spigotmc.org/resources/vault.34315/).
