### ISSUE TITLE
Players can only have 1 active quest regardless of max-quests value

### ISSUE THREAD

**Issue by xStellarOne** [PikaMug/Quests#2101]
### What is your Quests version / build number (do *not* say "latest")?

4.8.1

### Describe the problem and how to replicate it.

Players can only have 1 active quest regardless of max-quests value. Tried with default value and with the value set to 3. Message in chat is "Requirements" and nothing else. Running Paper server with Geyser.

### Any console errors to share?

```shell
N/A
```

**Comment by PikaMug** [comment]
Sounds like a duplicate of #2091
