### ISSUE TITLE
No translation of item names

### ISSUE THREAD

**Issue by chelminski** [PikaMug/Quests#2103]
### What is your Quests version / build number (do *not* say "latest")?

4.8.1

### Describe the problem and how to replicate it.

The players use the Polish language. The plugin supports the Polish language. After creating a quest to deliver items to an NPC, item names are displayed in English.

I even tried to change it and change the display name (5). But unfortunately, then the plugin thinks it's about a different item.

### Any console errors to share?

```shell
nope
```

**Comment by chelminski** [comment]
`accept-timeout: 20
allow-command-questing: true
allow-command-quests-with-npcs: true
allow-pranks: true
clickable-prompts: true
condition-interval: 10
confirm-abandon: true
confirm-accept: true
console-logging: 2
disable-command-feedback: false
generate-files-on-join: true
give-journal-item: false
ignore-locked-quests: false
kill-delay: 600
language: pl-PL
language-override-client: false
max-quests: 0
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: heart
show-completed-objectives: true
show-requirements: true
show-titles: true
storage-data:
  address: localhost:3306
  database: minecraft
  username: root
  password: ''
  table_prefix: quests_
  pool-settings:
    max-pool-size: 10
    min-idle: 10
    max-lifetime: 1800000
    keepalive-time: 0
    connection-timeout: 5000
    properties:
      useUnicode: true
      characterEncoding: utf8
storage-method:
  player-data: yaml
strict-player-movement: 0
top-limit: 150
trial-save: false
translate-names: true
translate-subcommands: true
update-check: true
`

**Comment by chelminski** [comment]
![image](https://github.com/PikaMug/Quests/assets/62246121/88b317ce-69e7-4551-b1cb-91d83d87fcf4)
![image](https://github.com/PikaMug/Quests/assets/62246121/7042bb11-1686-45fa-b06e-91cb365b3f21)

**Comment by PikaMug** [comment]
Item names are translated to the client's language. Either tell players to change their Options -> Language or you can set `language-override-client: false` to force the desired language.

**Comment by chelminski** [comment]
Hi
The client language is set to Polish. I also changed the config. Still the same problem. I even rewrote the quest.
![image](https://github.com/PikaMug/Quests/assets/62246121/c9da053b-d3d5-4a89-8f81-b31bfa434d7c)

**Comment by PikaMug** [comment]
@chelminski Strange that setting client language didn't work, but your config still has `language-override-client` set true

**Comment by chelminski** [comment]
Still not working for me :(

**Comment by PikaMug** [comment]
@chelminski See #2116
