### ISSUE TITLE
⚠️ Code freeze in effect ⚠️

### ISSUE THREAD

**Issue by PikaMug** [PikaMug/Quests#2105]
As of 2023-05-15, contributions to Quests have been halted in order to focus efforts on the next major release. Please continue to open issues as needed, but be aware that response times may be slow and, barring any game-breaking bugs, no development builds will be provided should your issue get resolved.

**Comment by NekaouMike** [comment]
What's the status so far?

**Comment by PikaMug** [comment]
No ETA, but you can see changes at https://github.com/PikaMug/Quests/tree/develop
