### ISSUE TITLE
quest reset 4.8.2

### ISSUE THREAD

**Issue by danyadanya2005** [PikaMug/Quests#2106]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2

### Describe the problem and how to replicate it.

make a quest for 24 hours. get the quest and exit the server. login to the server and see get quests. that quest for 24 hours will no longer be in the list

### Any console errors to share?

```shell
No
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/0WstJJbb
```

**Comment by PikaMug** [comment]
@danyadanya2005 What do you mean by "see get quests"? Are you running a command?

**Comment by danyadanya2005** [comment]
Yes. I write "/quests take Fighter Newbie". then I disconnect from the server. after a few seconds, I connect to the server again and write the command "/quests stats". and the Fighter Newbie quest is not there

**Comment by danyadanya2005** [comment]
planner:
      override: false
      if written like this. the quest is not reset. it is understandable. the quest is given indefinitely

**Comment by danyadanya2005** [comment]
but what about quests that have to be completed a couple of days? players will not sit on the server for 2 days without leaving

**Comment by PikaMug** [comment]
Your example quest is missing a start and end time (this should not be possible through the editor). See https://pikamug.gitbook.io/quests/beginner/planner

**Comment by danyadanya2005** [comment]
Yes, I'm sorry in my example, this is missing. but this also does not affect the error above. you yourself test your example? i tested. the quest is deleted after exiting the game!
    planner:
      start: 11:1:2020:9:0:0:SystemV/EST5
      end: 11:1:2020:17:0:0:SystemV/EST5
      repeat: 86400
      cooldown: 32400
      override: true
