### ISSUE TITLE
Add in abilty to register Objectives / Requirements / Rewards from a plugin rather than a module

### ISSUE THREAD

**Issue by nicholasrobertm** [PikaMug/Quests#2107]
### What does your feature do?

It'd be beneficial to not have to either split a project in 2 (One project for the custom objectives / requirements / rewards, and the other for plugin related logic) or to have to mixin inside `Quests#loadModules` to be able to have both plugin and custom quest related code live in the same jar.

### How would people use it?

This could be done a few ways such as
- A registration event that lets you add to what gets assigned in CustomRequirement, CustomReward or CustomObjective
- Allowing the user(dev) to call Quests#register and it taking in one of the above

This would be beneficial for simplifying integrating quests with other projects.

Also wanted to say appreciate the project!

**Comment by PikaMug** [comment]
Thanks for your input. Custom quests are intentionally limited to modules for user transparency. Attempting to add quests from other plugins is discouraged. If said plugins become abandoned, integration may suffer or break entirely, creating a problem for the end user (ex. [NPCDestinations](https://www.spigotmc.org/resources/npcdestinations-create-living-npcs.13863/update?update=452818), [SkillAPI](https://github.com/promcteam/proskillapi/issues/461)).

**Comment by nicholasrobertm** [comment]
Hey there,

Thanks for the feedback. Understandable to want to keep compatibility. I suppose for now I'll go the mixin route! For reference I'm creating an Arclight plugin to add support for Pixelmon actions (Defeating / catching pokemon, etc) and since for Arclight to register the forge events it needs the spigot plugin to be available there isn't an alternative that I'm aware of for now. Appreciate the discussion either way!
