### ISSUE TITLE
quest is deleted after exiting the game  4.8.2

### ISSUE THREAD

**Issue by danyadanya2005** [PikaMug/Quests#2109]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2

### Describe the problem and how to replicate it.

make a quest for 24 hours. get the quest and exit the server. login to the server and see get quests. that quest for 24 hours will no longer be in the list
 I write "/quests take Fighter Newbie". then I disconnect from the server. after a few seconds, I connect to the server again and write the command "/quests stats". and the Fighter Newbie quest is not there
 don't close the ticket until I reply. Quests don't work for you, that's a fact! you need to find the reason. repeat my description see for yourself. i changed "planner:". "start: end: " I deleted because it didn't work

### Any console errors to share?

```shell
No
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/GHEUT5MA
```

**Comment by PikaMug** [comment]
Continuation of #2106 

I tried your above quest and was not able to replicate this. The quest appears each time in _/quests stats_ under Current Quests.

Since you are manually editing the quests.yml file (which is not supported), make sure that you do not have any stage delays set, as those may exhibit the behavior you described. Also, try removing the Failure event and see if that helps.

**Comment by danyadanya2005** [comment]
![image](https://github.com/PikaMug/Quests/assets/51532656/289b9d1f-599c-436e-b0fd-00c9ac30a582)
nothing works for me
I don't understand why it says that the quest will be available in 30 days? where did the plugin get those 30 days from? I have 4 days written in the config

**Comment by danyadanya2005** [comment]
planner:
      start: 21:5:2023:9:0:0:SystemV/EST5
      end: 25:5:2023:23:0:0:SystemV/EST5
      #repeat: 1814400
      #cooldown: 32400
      override: true

**Comment by danyadanya2005** [comment]
please give me a working config with any quest that runs during the week

**Comment by danyadanya2005** [comment]
standard config. I just added the start time and the end of the quest
https://youtu.be/GEwHkVXh2aY
actions and quests https://pastebin.com/8Tv7vP0K
as soon as i leave the server the quest is deleted

**Comment by PikaMug** [comment]
> nothing works for me I don't understand why it says that the quest will be available in 30 days? where did the plugin get those 30 days from? I have 4 days written in the config

There is a known issue where the months for start and end time are saved to the config incorrectly. For example, `21:5:2023:9:0:0:SystemV/EST5` should actually be `21:4:2023:9:0:0:SystemV/EST5` in order to function properly.
