### ISSUE TITLE
Using the NextStage command more than once causes the quest to exit.

### ISSUE THREAD

**Issue by nuttapillar** [PikaMug/Quests#2111]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2

### Describe the problem and how to replicate it.

I'm trying to test a certain stage in my quest, but when I give myself the quest, and use the nextstage command, it successfully goes to the next stage, but once I use it again, the quest exits, and it tells me "[user] does not currently have any active quests" Even though the quest has 6 stages.
I then tested with other quests, and they are behaving exactly the same. I cannot skip past the second stage without it quitting.

### Any console errors to share?

```shell
No, it doesn't produce any console errors.
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/zuuYqubG
```

**Comment by PikaMug** [comment]
@nuttapillar Thanks for the report. I was not able to replicate this; every `/qa nextstage <player> Spiderbook` progressed the quest by one stage. However, I did have to remove the start-event and finish-event actions from your quest as you did not include them. Could be an issue with one of those?

**Comment by nuttapillar** [comment]
Well all of these quests are valid enough to be completed by any player, so I assume they must be good enough to skip stages with the command. Those events were just playsounds, but I also tried this with other quests that do not have such events at all, and had the same issue.

**Comment by PikaMug** [comment]
Feel free to share some other quests that are affected.
