### ISSUE TITLE
quest is deleted after exiting the game 4.8.2

### ISSUE THREAD

**Issue by danyadanya2005** [PikaMug/Quests#2113]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2

### Describe the problem and how to replicate it.

make a quest for 24 hours. get the quest and exit the server. login to the server and see get quests. that quest for 24 hours will no longer be in the list
I write "/quests take Fighter Newbie". then I disconnect from the server. after a few seconds, I connect to the server again and write the command "/quests stats". and the Fighter Newbie quest is not there
don't close the ticket until I reply. Quests don't work for you, that's a fact! you need to find the reason. repeat my description see for yourself. i changed "planner:". "start: end: " I deleted because it didn't work

Please don't ignore the issue. your quests close early. just log out of the server. I will give you my quests. do at least one so that when the player leaves the server the quest does not disappear? I can't do it because it doesn't work. and the problem is clearly not about me https://pastebin.com/ftBTYXRJ

### Any console errors to share?

```shell
No
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
standard config. I just added the start time and the end of the quest
https://youtu.be/GEwHkVXh2aY
actions and quests https://pastebin.com/8Tv7vP0K
as soon as i leave the server the quest is deleted
```

**Comment by danyadanya2005** [comment]
allow-quitting: true what does this command give:?

**Comment by PikaMug** [comment]
Even though ticket #2109 was closed, you can still reply. However, I did address the issue - you manually edited the quests.yml file (not supported) which caused unexpected behavior. Unless you provide the "Newbie Fighter" quest which you must update according to my last comment, I consider the matter closed.

Looking at https://pastebin.com/8Tv7vP0K your "Iron Miner" quest has identical start and end time. This means your quest will last 0 seconds. I expect that is not what you want, so use a later end time. Also, you have two colons at `end::` which might be problematic, change to `end:`.

If you need further support, consider joining [our Discord](https://discord.com/invite/QdJAv2G7qg). Bug reports without console errors are best handled there.

> allow-quitting: true what does this parameter give?

You may read more about that setting at https://pikamug.gitbook.io/quests/beginner/options#general

**Comment by danyadanya2005** [comment]
these settings are created automatically in the game. I didn't edit them manually https://pastebin.com/8Tv7vP0K 
I don't know why there are two colons.

**Comment by danyadanya2005** [comment]
if the quest has this parameter "start-event: TimerStart" then the quest will be deleted from the player if the player leaves the server, regardless of what time is in the "start-event"
also start: and end: do not affect anything if the quest has "start-event:" and "finish-event:". I'm waiting for a fix
I want the quest not to be deleted from the player if he exits the "start-event: TimerStart" server. in this case "start-event:" and "finish-event:" are not needed.

**Comment by danyadanya2005** [comment]
did I make myself clear?

**Comment by danyadanya2005** [comment]
![image](https://github.com/PikaMug/Quests/assets/51532656/1293ff8a-2067-48c8-8ca3-8cbe5d88288d)
where does it say "allow-quitting: "? what does it mean?
in any case, if I understand correctly what this parameter is, then
allow-quitting: true, allow-quitting: false value does not work. the quest is deleted in any case if the player leaves the server

**Comment by PikaMug** [comment]
> these settings are created automatically in the game. I didn't edit them manually https://pastebin.com/8Tv7vP0K I don't know why there are two colons.

It is not possible for Quests to output two colons like this. Perhaps one of your administrators or another plugin/task made the changes. Regardless, make sure to correct it to a single colon.

> if the quest has this parameter "start-event: TimerStart" then the quest will be deleted from the player if the player leaves the server, regardless of what time is in the "start-event" also start: and end: do not affect anything if the quest has "start-event:" and "finish-event:". I'm waiting for a fix I want the quest not to be deleted from the player if he exits the "start-event: TimerStart" server. in this case "start-event:" and "finish-event:" are not needed.

I understand now, this seems to be intentional to prevent players from abusing wait times, as most servers prefer that the player stay logged in for the entire duration. If you want to limit how long players have to complete your quest, but allow them to leave, you could only use the Planner. But I'll consider changing this.

> -pic- where does it say "allow-quitting: "? what does it mean? in any case, if I understand correctly what this parameter is, then allow-quitting: true, allow-quitting: false value does not work. the quest is deleted in any case if the player leaves the server

That is a completely different page from the one I linked. It's on the Options page, under General. "Allow quitting during quest"

**Comment by danyadanya2005** [comment]
"That is a completely different page from the one I linked. It's on the Options page, under General. "Allow quitting during quest""
why is this setting not working?
does the Planner notify the player in the chat the end time of the quest if I delete "start-event:" and "finish-event:"?

**Comment by danyadanya2005** [comment]
I fixed the colon, of course

**Comment by PikaMug** [comment]
> why is this setting not working?

This setting stops players from quitting during the quest, but the plugin can (and as you've seen, does) override this. In other words, it is only meant to stop the player from using _/quests quit_ for that quest.

> does the Planner notify the player in the chat the end time of the quest if I delete "start-event:" and "finish-event:"?

No, it does not. I'll consider changing the timer functionality to do what you're looking for.
