### ISSUE TITLE
Issue with the languages...

### ISSUE THREAD

**Issue by Treshyyy** [PikaMug/Quests#2117]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2

### Describe the problem and how to replicate it.

Hello I kinda have a problem. I use this plugin in Hungarian language and it seems pretty cool, but I found some bug. 

The problem is that when I click on the 'Nem (It means no)' it's working but when I click on the 'igen (it means yes)' This error pops up. I would really like this issue to be solved.
Image

![image](https://github.com/PikaMug/Quests/assets/116669607/97088d8a-fecc-4196-80fc-02dc124edffb)

### Any console errors to share?

```shell
No error
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
For exemple: I want to accept the quest
```

**Comment by Treshyyy** [comment]
Nevermind! Close this thread. The problem was that I changed the language, but `language-override-client` was on false and my game language was on English so it was kinda buggy!

**Comment by Treshyyy** [comment]
Oh wait I found another problem! I set the language to en-US by default but I want to translate messages by the client language, but it just mixes everything

**Comment by PikaMug** [comment]
@Treshyyy Please try https://ci.codemc.io/job/PikaMug/job/Quests/422/
