### ISSUE TITLE
Players able to take display items

### ISSUE THREAD

**Issue by NekaouMike** [PikaMug/Quests#2120]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2-b416

### Describe the problem and how to replicate it.

The issue is when setting a NPC as a quest starter and opening the GUI. By simply shift+left clicking. The player is able to take the quest GUI item. 

### Any console errors to share?

```shell
N/A
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
N/A
```

**Comment by PikaMug** [comment]
I was not able to replicate this on a 1.19.4 server with a Start NPC and GUI item display set. What is your Minecraft version? Do you have QuestsGUI installed? Can you provide an example quest?

**Comment by NekaouMike** [comment]
My Minecraft version is 1.19.4 no Via Version or anything. I have only the Quests Plugin installed not QuestsGUI

**Comment by NekaouMike** [comment]
If this helps I am using 
`git-Purpur-1976 (MC: 1.19.4)`
as my server version

**Comment by PikaMug** [comment]
Thanks. I was testing on Paper, but will give Purpur a try once I find the time.

**Comment by PikaMug** [comment]
I was able to replicate this on Purpur. Looking into a solution.

**Comment by PikaMug** [comment]
@NekaouMike Please try https://ci.codemc.io/job/PikaMug/job/Quests/424/
