### ISSUE TITLE
support folia fork

### ISSUE THREAD

**Issue by hkkongou** [PikaMug/Quests#2123]
### What does your feature do?

Add support for folia fork (A new offical fork from papermc) , so that quests can run on folia servers.

### How would people use it?

create quests on folia servers.
Currently there is none of quests plugin support folia platform, quests plugin can become the first one.

**Comment by PikaMug** [comment]
See https://github.com/sponsors/PikaMug

**Comment by hkkongou** [comment]
> See https://github.com/sponsors/PikaMug

does that mean i need to sponsor to get this request?
Which tier should i go for in this case 🤔🤔
