### ISSUE TITLE
Multiple block types as one task

### ISSUE THREAD

**Issue by chelminski** [PikaMug/Quests#2124]
### What does your feature do?

Hi
How does it currently work?
In the case of a quest, for example, "destroy a block", it is counted only when the player destroys the mentioned block. Of course, this is very logical to me. The problem arises when, for example, the task says "destroy 500 dirt" and grass blocks are not counted.

How would it work?
I would like to be able to specify several types of blocks that would be included in the task. E.g. "destroy dirt, or grass_block or sand x500". It is also important to me because new blocks have appeared in minecraft. I would like to be able to include in the quest, for example, "Mine Diamond Ore, or Deepslate Diamond Ore"

**Comment by PikaMug** [comment]
Not technically a duplicate, but I'm afraid the same principle applies as https://github.com/PikaMug/Quests/issues/789#issuecomment-507416132
