### ISSUE TITLE
Lifting the x64 limit

### ISSUE THREAD

**Issue by chelminski** [PikaMug/Quests#2125]
### What does your feature do?

hi ;)
I would like to ask that somehow the 64 block/item limit for delivering to NPCs, smelting and other activities be lifted. Currently, to get around this, I have to do it in such a way that, for example, instead of x100 blocks, I split it into 2 tasks x64, and x32. It doesn't look good. In the case of RPG servers, where quests play a key role, lifting the limit of 64 would be very helpful.

![image](https://github.com/PikaMug/Quests/assets/62246121/d14f2a72-bc35-4135-9f35-d9cee50add7b)
//Polish (Przetop przedmioty-->Smelt items)

Thanks <3

**Comment by PikaMug** [comment]
Thanks for the suggestion. Unfortunately, this is a limitation of how Bukkit serializes ItemStack. Some have had success in editing the _quests.yml_ file to values higher than 64, but no support will be provided if something goes wrong.
