### ISSUE TITLE
rewards 

### ISSUE THREAD

**Issue by davsla12** [PikaMug/Quests#2126]
### Where else have you looked for answers to this question?

I looked for the answer in the documentation but couldn't find it.

### Share your question with as much detail as possible.

how to set money reward with Vault?

**Comment by PikaMug** [comment]
https://pikamug.gitbook.io/quests/beginner/rewards
Selection 1 in picture, provided Vault and an economy plugin are installed.

**Comment by davsla12** [comment]
I installed vault but it says not installed
