### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by davsla12** [PikaMug/Quests#2128]
### Where else have you looked for answers to this question?

I looket to documentation

### Share your question with as much detail as possible.

I installed vault but it says not installed

**Comment by PikaMug** [comment]
Duplicate of #2126 

As mentioned in previous issue, you need an economy plugin, as well.

**Comment by davsla12** [comment]
Which economic plugin?

**Comment by PikaMug** [comment]
@davsla12 Any that are compatible with Vault. For example, https://www.spigotmc.org/resources/fe.723/
