### ISSUE TITLE
Placeholder language

### ISSUE THREAD

**Issue by kfirmowe7** [PikaMug/Quests#2129]
### What is your Quests version / build number (do *not* say "latest")?

Quests 4.8.3-b422

### Describe the problem and how to replicate it.

Regardless of the selected language in config.yml, in the case of placeholders, it always shows items in English.

### Any console errors to share?

```shell
//
```

**Comment by PikaMug** [comment]
Assuming you mean those through PlaceholderAPI, they are not translatable.
