### ISSUE TITLE
GeyserMC

### ISSUE THREAD

**Issue by ComingFlex** [PikaMug/Quests#2132]
### What does your feature do?

Дайте возможность принять квест командой, чтобы  игроки с телефонов тоже могли участвовать (GeyserMC)

Give the opportunity to accept the quest as a team, so that players from phones can also participate (GeyserMC)

### How would people use it?

Дайте возможность принять квест командой, чтобы  игроки с телефонов тоже могли участвовать (GeyserMC)

Give the opportunity to accept the quest as a team, so that players from phones can also participate (GeyserMC)

**Comment by PikaMug** [comment]
Use https://www.spigotmc.org/resources/parties-an-advanced-parties-manager.3709/
