### ISSUE TITLE
Some suggestions after using numerals Quests plugins that are available on Spigot

### ISSUE THREAD

**Issue by StevenGoh-YH** [PikaMug/Quests#2135]
### What does your feature do?

This is an excellent plugin, however it does have some shortfalls that make it really the one stop shop option.

Some suggest that would really make this plugin even more awesome:

1. Quest progress configurable notification on chat/textbox
(e.g., for Stone breaking quests, an option to notify the quester on the progress per interval).

2. Support for Scoreboard Quest tracking
(e.g., tracks for the accepted quests, tracks active quest progress)

3. Provide PAPI support so that other plugins can pick up quest progress and etc.,

Thank you

### How would people use it?

For users/players to track their progress either on scoreboard or chat/text

**Comment by PikaMug** [comment]
Thanks for the input. I think you'll find these resources useful, in response to your list:

1. https://www.spigotmc.org/resources/questsbar.100634/
2. https://www.spigotmc.org/resources/placeholderexpansion-quests.69357/
3. https://www.spigotmc.org/resources/placeholderexpansion-quests.69357/
