### ISSUE TITLE
About GUI

### ISSUE THREAD

**Issue by fenlincao** [PikaMug/Quests#2140]
### What does your feature do?

Obviously, this is a very good plugin, but unfortunately the lack of a complete GUI, if you can join the complete GUI, it will be very convenient for players to use, they do not need to input instructions, they  can complete various operations through simple clicks, which will bring convenience to players.
Finally, I hope you can take my advice, thank you!

### How would people use it?

Open the GUI panel, then click to complete the task view, take, discard, etc

**Comment by PikaMug** [comment]
https://pikamug.gitbook.io/quests/casual/bridge-plugins#questsgui
