### ISSUE TITLE
Failed to complete quests

### ISSUE THREAD

**Issue by AndyFer2** [PikaMug/Quests#2142]
### What is your Quests version / build number (do *not* say "latest")?

4.8.3

### Describe the problem and how to replicate it.

Why was I completing a mission and when I logged out of the server and logged back in, I don't see what I have to continue doing? I get mission not found or something like that.

### Any console errors to share?

```shell
No.
```

**Comment by PikaMug** [comment]
Without a console error or example quest, here is nothing for me to investigate. If you can at least provide the exact message you get, the Discord may be able to help you.
