### ISSUE TITLE
command to reset quests from all players

### ISSUE THREAD

**Issue by Razorxd1993** [PikaMug/Quests#2144]
### Where else have you looked for answers to this question?

Documentation

### Share your question with as much detail as possible.

Hello :)
would it be possible to add a command that deletes all quests of all players ? like the command /questadmi reset [playyer] only in the variant /questadmin resetall 

Kind regards

**Comment by PikaMug** [comment]
I've given this some more thought, and it really shouldn't ever be necessary to reset all players at once. If a server owner really must do this, they should already have file access to either delete the 'data' folder or purge the column in MySQL.
