### ISSUE TITLE
Which permissions i need to leaving from quests?

### ISSUE THREAD

**Issue by lubaskinc0de** [PikaMug/Quests#2147]
### Where else have you looked for answers to this question?

In discord, docs

### Share your question with as much detail as possible.

I’m trying to give my players ability to leave quest, seems like permission for command leave it’s not working, when it answer me “Yes or No” i don’t have permissions to choose the answer.

**Comment by PikaMug** [comment]
Should be `quests.quit` https://pikamug.gitbook.io/quests/setup/commands-and-permissions

If that doesn't help, provide a _screenshot_ of the error message you get.
