### ISSUE TITLE
Bug validating quests via NPC

### ISSUE THREAD

**Issue by zabilotero** [PikaMug/Quests#2152]
### What is your Quests version / build number (do *not* say "latest")?

V5.0.0-rc.1-b430

### Describe the problem and how to replicate it.

Quests where you have to talk to an npc to validate the step do not validate. So you can't go to the next step if you have to talk to an NPC I created a quest that and gave it to the player through an npc. This quest asks us to go talk to another NPC, as a reward there is a Diamond Sword and $, except that when the player goes to talk to the NPC request, the quest does not validate and the player cannot complete this quest

### Any console errors to share?

```shell
I'm not mistaken in the consol
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
I'm not an example of a quest to give you, I'm currently creating an RPG server, I just have to create a quick basic quest to make a test
```

**Comment by PikaMug** [comment]
Typically I would close this due to lack of example quest, and you did not state which NPC plugin you're using, but I'll leave it open pending investigation.

**Comment by zabilotero** [comment]
Hello, please excuse me for the lack of information.
I created the subject quickly via my phone because I was not at home.
Thank you for answering my problems.
I am currently not at home I will send you more details this evening after work.
I will send you the quests file as well as my logs if necessary
I use the Google translator because I am French

Le 2023-10-25T03:33:19.000+02:00, PikaMug ***@***.***> a
écrit :

**Comment by zabilotero** [comment]
# For non-English characters, this file MUST stay encoded in UTF-8

quests:

  custom1:

    name: 1-teste

    ask-message: Vas parler au marchand d'arme

    finish-message: Bien jouÃ©Â !

    npc-giver-uuid: 0c6cca22-321b-4d17-a3df-e57883a06165

    stages:

      ordered:

        '1':

          npc-uuids-to-talk-to:

          - 00d97816-b868-4489-8dd6-0daf30708545

          finish-event: NiceFinish

    rewards:

      money: 500

**Comment by PikaMug** [comment]
Please try https://ci.codemc.io/job/PikaMug/job/Quests/431/
