### ISSUE TITLE
Stage with Reach Locations

### ISSUE THREAD

**Issue by misterjst** [PikaMug/Quests#2154]
### Where else have you looked for answers to this question?

Documentation

### Share your question with as much detail as possible.

Is it possible to complete the quest if I only have a stage that need to reach the location? I tried to make it but when I already reached the location the quest is still on going and does not complete.

**Comment by PikaMug** [comment]
Already fixed in 162db479d2571323502afa095d7a78969850163a

Use latest Jenkins build
