### ISSUE TITLE
Add "Use items" option in "Stages" menu

### ISSUE THREAD

**Issue by Floodo** [PikaMug/Quests#2157]
### What does your feature do?

Simply it will bring for people another way how to use items in certain stages.

### How would people use it?

When somebody will be in "/quests editor" -> edit some quest -> edit stages -> Items , there could be another way how to handle items, and that would be "Use items" .... soo like in certain stage they would need to use like horn/throw snowball/right click with hoe/right click with axe/fishing rod  and etc., .... I think it would be really handy :) .......now the only close thing to that is "Consume items", which doesn't work for that jobs obviously

**Comment by PikaMug** [comment]
Thanks for the suggestion. The Bukkit/Spigot API doesn't offer a method to test whether an item is usable, to my knowledge. So we'd probably need a list of all usable items to compare against, which would need to updated each version, and that's not desirable. So this is probably best left to a custom module.

**Comment by Floodo** [comment]
Oh, okay, understadable. And is there a chance that you will make it as module? :)

**Comment by PikaMug** [comment]
> Oh, okay, understadable. And is there a chance that you will make it as module? :)

https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features
