### ISSUE TITLE
Multi outcome quests for npcs

### ISSUE THREAD

**Issue by majster2nn** [PikaMug/Quests#2162]
### What does your feature do?

This new feature would add the decision option for quests that would lead to different paths in quests etc

### How would people use it?

To create different paths adding immersion to quests

**Comment by PikaMug** [comment]
Duplicate of #454

**Comment by majster2nn** [comment]
i meant it for npcs in citizen 2 forgot to add that anyway

**Comment by majster2nn** [comment]
and its not even quite multi otcomes cuz you dont make the decision you just complete quest and it blocks other
