### ISSUE TITLE
Quest points can be negative value

### ISSUE THREAD

**Issue by Raava3** [PikaMug/Quests#2167]
### What is your Quests version / build number (do *not* say "latest")?

5.0.0-rc.2-b435

### Describe the problem and how to replicate it.

Players can have negative quest points. When you use /Questadmin takepoints `Player` `Amount` it can go into negative numbers. I was trying to use it as currency that players can exchange between each other for in-game money. Unfortunately it was subtracting past zero.

### Any console errors to share?

```shell
None
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Not applicable
```

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/437/
