### ISSUE TITLE
Quests data keeps whipping player progress. 

### ISSUE THREAD

**Issue by thewigit** [PikaMug/Quests#2169]
### What is your Quests version / build number (do *not* say "latest")?

latest 

### Describe the problem and how to replicate it.

Every time a server restart happens player data is erased. all of the quests and everything remains (thank God), but player quest progress is wiped. 

### Any console errors to share?

```shell
none
```

**Comment by PikaMug** [comment]
> do not say "latest"

**Comment by thewigit** [comment]
Is it standard policy to be rude and to close a valid issue instead of just
simply asking in a polite way "can you please provide the version number
you are using?" or something along those lines.

**Comment by PikaMug** [comment]
There was no intent to appear rude, but the issue was not valid for the reason quoted. You are more than welcome to create a new issue with the necessary information. An example quest you know had been wiped would also help.
