### ISSUE TITLE
Player quests data (progress) is not saving after server restart

### ISSUE THREAD

**Issue by thewigit** [PikaMug/Quests#2170]
### What is your Quests version / build number (do *not* say "latest")?

5.0.0-rc.2

### Describe the problem and how to replicate it.

Quests log player data is not saving quest progress and is wiping after the server is restarted. 

### Any console errors to share?

```shell
none
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
N/A
```

**Comment by PikaMug** [comment]
Thanks for the report. An example quest you know had been wiped would also help.

**Comment by thewigit** [comment]
There are no quests being wiped. The quests themselves are fine. Lile I
stated, the player data is being reset. So it is not saving quest progress
for the players.

**Comment by PikaMug** [comment]
I mean, a quest that the player had in-progress or completed before their data was reset.

**Comment by thewigit** [comment]
Every single quest gets wiped. but here is one of the 79 quests in the game. All of the quests work. just the player progress is not being saved after server restart

  custom10:
    name: The Hunters
    ask-message: I belong to a group called "the Hunters". You should join us! Talk
      to our leader at the Wild Life Preserve to the west.
    finish-message: Welcome to the Preserve! We hunt monsters to protect the innocent
      creatures of this world!
    npc-giver-uuid: 146269aa-42c6-41c4-abb0-83a150f047d8
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: BOW
    stages:
      ordered:
        '1':
          locations-to-reach:
          - world -517.0 70.0 -231.0
          reach-location-radii:
          - 10
          reach-location-names:
          - Hunting Grounds Tunnel
          start-message: You can find the entrence to the preserver at -514 71 -231
          complete-message: Well done! Following simple instructions is key to becomeing
            a Hunter! Go talk to Hunter Morty
        '2':
          npc-uuids-to-talk-to:
          - 48d82932-560d-4ca2-bbce-f70ed09a5539
          complete-message: erase
    rewards:
      money: 50
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true

**Comment by PikaMug** [comment]
I'll proceed under the assumption that you have verified the quest was active or completed when the player's wipe occurred.

**Comment by thewigit** [comment]
Yes, please proceed. That is correct. I myself has tested this many times.
Completed several quests only for it to be wiped the next day after I had
to restart the server for a fix (not related to the quests)

**Comment by thewigit** [comment]
Thank you so much for any help!

**Comment by PikaMug** [comment]
I haven't been able to replicate this, but 5.0.0-rc.3 fixes two bugs which could theoretically contribute to this issue. Please upgrade and, if this happens again, simply reply to re-open the issue.
