### ISSUE TITLE
Npc quests

### ISSUE THREAD

**Issue by Qekker** [PikaMug/Quests#2171]
### Where else have you looked for answers to this question?

I have searched around for information on google for the last 1 hour and cant seem to find an answer

### Share your question with as much detail as possible.

Is it possible to make the quests stay in the gui after being completed but just get the enchanted effect? And how would i do this?

**Comment by PikaMug** [comment]
Assuming you mean the built-in NPC GUI, there is not a way to accomplish this. You could request this functionality in something like QuestsGUI.
