### ISSUE TITLE
Players unable to see any further quests after having completed one.

### ISSUE THREAD

**Issue by VirgilGunder** [PikaMug/Quests#2173]
### What is your Quests version / build number (do *not* say "latest")?

Quests-5.0.0-rc.2

### Describe the problem and how to replicate it.

For some reason out of nowhere players can no longer accept/see the next quest...

Here is my quests.yml: 
https://pastebin.com/9rLNRQMn

My config:
https://pastebin.com/am8FrWhr

### Any console errors to share?

```shell
Nothing
```

**Comment by VirgilGunder** [comment]
I have the updated version now

**Comment by VirgilGunder** [comment]
Updated to latest version and still does not work

**Comment by PikaMug** [comment]
What is the version you updated to? Need the exact version number.

Also, which quests specifically can be used to replicate the issue?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
