### ISSUE TITLE
Console error from uploading backuped quests.yml

### ISSUE THREAD

**Issue by timothykra** [PikaMug/Quests#2175]
### Where else have you looked for answers to this question?

I looked through the code and I believe I have fixed this issue myself before but not sure. I also looked through the other questions and did not seem to see anything there about this

### Share your question with as much detail as possible.

https://pastebin.com/M6q8cfZw 

Above, I pasted the console error it gives me, saying that there is a configuration error in the code. Some help would be gladly appreciated. I also attached my quests.yml file
[quests (1).txt](https://github.com/PikaMug/Quests/files/13800076/quests.1.txt)

**Comment by PikaMug** [comment]
Looks like you have some tabs instead of spaces. Use a YAML parser such as https://codebeautify.org/yaml-parser-online (not affiliated)
