### ISSUE TITLE
Warps permission

### ISSUE THREAD

**Issue by Jefersonth1996** [PikaMug/Quests#2176]
### Where else have you looked for answers to this question?

github

### Share your question with as much detail as possible.

How do I ensure that when the player finishes the quest he receives permission (luckperms) to access the advanced warp (warp goldminer)

    name: Ajude o Mineiro
    ask-message: Estou precisando de uma mãozinha por aqui. Minha picareta está quase
      dando o último suspiro, e ainda tenho alguns blocos preciosos para coletar.
      Se alguém puder me ajudar a arrancar os últimos recursos das entranhas desta
      mina, seria incrível!
    finish-message: Missão cumprida! Conseguimos arrancar até o último pedacinho dos
      preciosos minérios lá nas profundezas da mina. As veias de carvão estão agora
      nas nossas mãos, prontos para serem utilizados.
    npc-giver-uuid: 8a0052cb-fde2-4141-b512-17bd918ca57f
    region: mina
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3463
      type: COAL
    stages:
      ordered:
        '1':
          break-block-names:
          - COAL_ORE
          - COPPER_ORE
          break-block-amounts:
          - 300
          - 300
          break-block-durability:
          - 0
          - 0
          start-message: Quebre 300 bloco de carvão e 300 de cobre
          complete-message: Entregue a missão ao Mineiro
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3463
        type: DIAMOND
      money: 1000
      quest-points: 10
      exp: 10
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true

**Comment by PikaMug** [comment]
Use a permission reward for whatever node that "advanced warp" plugin requires.
https://pikamug.gitbook.io/quests/beginner/rewards

For basic questions like this, please visit the Quests Community [Discord server](https://discordapp.com/invite/QdJAv2G7qg).

**Comment by Jefersonth1996** [comment]
able to make the command work, so I wanted to know if there is a way to hide the command that appears in the quest

**Comment by Jefersonth1996** [comment]
rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3463
        type: DIAMOND
      money: 1000
      quest-points: 10
      exp: 10
      commands:
      - lp user <player> permission set essentials.warps.goldminer true
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
