### ISSUE TITLE
 permission

### ISSUE THREAD

**Issue by Jefersonth1996** [PikaMug/Quests#2179]
### Where else have you looked for answers to this question?

discord

### Share your question with as much detail as possible.

How can I make the permission not appear in rewards, but apply
rewards:
      items:
      
==: org.bukkit.inventory.ItemStack
      v: 3463
      type: DIAMOND
    money: 1000
    quest-points: 10
    exp: 10
    permissions:
'essentials.warps.goldminer'

Sorry for the inconvenience, I've been trying for days to find a way

**Comment by Jefersonth1996** [comment]
![Captura de tela 2024-01-12 184258](https://github.com/PikaMug/Quests/assets/156003911/431f2f67-5fd9-4493-8344-1705663bda22)

**Comment by PikaMug** [comment]
Details list override
