### ISSUE TITLE
Hook process to Znpcs (i dont have it) & request dependency disable

### ISSUE THREAD

**Issue by Godivctor** [PikaMug/Quests#2180]
### What is your Quests version / build number (do *not* say "latest")?

Quests-5.0.0-rc.3 b 440

### Describe the problem and how to replicate it.

it wouldnt be easy/fast to disable dependencies that i do not want in the config?

I am not using Znpcs, but the hook and its processes are still enabled and visible in spark report
![image](https://github.com/PikaMug/Quests/assets/34318105/6c0dbd63-6447-4206-b027-d76861cdbd95)

### Any console errors to share?

```shell
no responses
```

**Comment by PikaMug** [comment]
Thanks for the report. First, know that we do not support ZNPCs. We do support [ZNPCsPlus](https://www.spigotmc.org/resources/znpcsplus.109380/).

Effects for NPCs will always have _some_ impact on performance, but try this build:
https://ci.codemc.io/job/PikaMug/job/Quests/445/
