### ISSUE TITLE
znpc ticks bug

### ISSUE THREAD

**Issue by Astolate** [PikaMug/Quests#2191]
### What is your Quests version / build number (do *not* say "latest")?

5.0.0

### Describe the problem and how to replicate it.

Quests ZnpcPlus creating lag and possible memory leak issues.

### Any console errors to share?

```shell
no, but providing current spark report. https://spark.lucko.me/BMBNrY2ODp
```

**Comment by PikaMug** [comment]
This is not a bug and the spark report you provided does not indicate persistent lag nor memory leaks. There was a momentary pause when looking for ZNPCsPlus, probably when an NPC was created. If you insist on avoiding this, disable `npc-effects` in the _config.yml_ file. You might also want to look at improving RAM usage by removing unnecessary and/or memory-intensive plugins.
