### ISSUE TITLE
Function canAcceptQuest and Stage npc particles

### ISSUE THREAD

**Issue by Grandicek** [PikaMug/Quests#2197]
### Where else have you looked for answers to this question?

In Code :)

### Share your question with as much detail as possible.

Hi, can I ask about the canAcceptQuest function that currently returns true even if the conditions for starting a quest are not met? Is that good or just an unfinished condition? Then the particles are also displayed above the npc that can't currently give the quest because it doesn't meet the conditions. The second question is about particles above npcs in stage 1,2,3... I don't see particles above them because it's not in the code (at least I didn't find it :)).

thank you in advance for your reply and for your hard work :)

**Comment by PikaMug** [comment]
As far as I know, that function works as intended. Did you have a specific situation where it does not? If so, please describe how to replicate that.

Particles are not shown for individual stages, that is intentional.

**Comment by Grandicek** [comment]
> As far as I know, that function works as intended. Did you have a specific situation where it does not? If so, please describe how to replicate that.

if I set a required quest, the particles will appear even if the player cannot accept it (because he has not completed the quest before)

**Comment by Grandicek** [comment]
Now i try it wih OP/witout OP

`
public boolean canAcceptQuest(final UUID npc) {
        for (final Quest q : plugin.getLoadedQuests()) {
            if (q.getNpcStart() != null && !getCompletedQuests().contains(q)) {
                if (q.getNpcStart().equals(npc)) {
                    final boolean ignoreLockedQuests = plugin.getConfigSettings().canIgnoreLockedQuests();
                    if (!ignoreLockedQuests || q.testRequirements(this)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }
`

there is nothing here to check if the player meets the conditions for accepting the quest. Of course, if it's meant to be, I won't say anything anymore =)

**Comment by PikaMug** [comment]
There is a difference between "[Conditions](https://pikamug.gitbook.io/quests/expert/condition-editor)" and "[Requirements](https://pikamug.gitbook.io/quests/beginner/requirements)" in Quests. I'll assume you're referring to Requirements as that's what would be checked here.

However, I suspect the issue you're running into is `ignoreLockedQuests` is most likely false, as that's the default config value. If the issue's deeper than that, please share the quest you're testing with (from _quests.yml_).

**Comment by Grandicek** [comment]
> There is a difference between "[Conditions](https://pikamug.gitbook.io/quests/expert/condition-editor)" and "[Requirements](https://pikamug.gitbook.io/quests/beginner/requirements)" in Quests. I'll assume you're referring to Requirements as that's what would be checked here.
> 
> However, I suspect the issue you're running into is `ignoreLockedQuests` is most likely false, as that's the default config value. If the issue's deeper than that, please share the quest you're testing with (from _quests.yml_).

Ooooooooooh 🗡️ 

and this solves my question :)
ignore-locked-quests: true

Thank you!

**Comment by Grandicek** [comment]
and this solves my question :)
ignore-locked-quests: true
