### ISSUE TITLE
Colors of plugin placeholders <time>,<quest>,<mob>,<item> etc are not changable

### ISSUE THREAD

**Issue by StKillReal** [PikaMug/Quests#2202]
### What is your Quests version / build number (do *not* say "latest")?

4.8.2-b414

### Describe the problem and how to replicate it.

The plugin has strings.yml file for translating and it convinient and easy to use, but for some reasons we can't change color of <time>,<quest>,<mob>,<item> etc placeholders. Of course we can change the color using %color% before quest name, but what about other placeholders? Even if I change color of every single quest, I still can't change color of <time>,<mob>,<item> etc. 
![image](https://github.com/PikaMug/Quests/assets/60330193/f572d7c3-8cc7-42a3-8a98-e070a1cf8069)
![image](https://github.com/PikaMug/Quests/assets/60330193/21a53d27-b2d5-4ad0-ae2a-10389f777d76)
![image](https://github.com/PikaMug/Quests/assets/60330193/599b09b8-567e-4f1e-ad21-1a46e8325033)
![image](https://github.com/PikaMug/Quests/assets/60330193/dc163970-7ec4-4f7c-bda6-cf93114dce2d)

I'm using 57 plugins on my server and seems like Quests is the only one plugin which can't change placeholders colors. May you fix it please. I'm not the only one person who noticed it, because I saw a lot of questions about it in Discord

### Any console errors to share?

```shell
No errors
```

**Comment by PikaMug** [comment]
> ![image](https://private-user-images.githubusercontent.com/60330193/326580454-f572d7c3-8cc7-42a3-8a98-e070a1cf8069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjgwODQsIm5iZiI6MTcxNDQ2Nzc4NCwicGF0aCI6Ii82MDMzMDE5My8zMjY1ODA0NTQtZjU3MmQ3YzMtOGNjNy00MmEzLThhOTgtZTA3MGExY2Y4MDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5MDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzI4NjRjMjAyZWU2ZDViY2E4OWMzYWIwMDFlMDA2NzM0NmI3ZjhkYTBhZWVkNGUwNTUxYTYwZjJiMTBhNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4HFGSKxyS14r1rw9r9Wv1yuSGC2LiCIHCgFOoIgZwzY) 

What is the entire text? It looks like you've only changed portions of this to green.

As for items, these are a special case as they are translatable components. I'll check if anything can be done, but it may not be possible.

**Comment by StKillReal** [comment]
> > ![image](https://private-user-images.githubusercontent.com/60330193/326580454-f572d7c3-8cc7-42a3-8a98-e070a1cf8069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjgwODQsIm5iZiI6MTcxNDQ2Nzc4NCwicGF0aCI6Ii82MDMzMDE5My8zMjY1ODA0NTQtZjU3MmQ3YzMtOGNjNy00MmEzLThhOTgtZTA3MGExY2Y4MDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5MDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzI4NjRjMjAyZWU2ZDViY2E4OWMzYWIwMDFlMDA2NzM0NmI3ZjhkYTBhZWVkNGUwNTUxYTYwZjJiMTBhNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4HFGSKxyS14r1rw9r9Wv1yuSGC2LiCIHCgFOoIgZwzY)
> 
> What is the entire text? It looks like you've only changed portions of this to green.
> 
> As for items, these are a special case as they are translatable components. I'll check if anything can be done, but it may not be possible.

The image you sent is broken, but I suppose it was iamge with "Beacon" text on it. The text was `%white%Craft %green%<item>`, but color of item was not green even when I changed color code before it. It's just an example, because doesn't matter which placeholder it is, it can be a <mob> or <time>. Actually I've already replaced every single `ChatColor.DARK_PURPLE` and `ChatColor.AQUA` with `ChatColor.GREEN` in plugin code and compiled it myself and now it looks better, but the main issue of this replacing is I changed **every single** purple and aqua color with green

**Comment by PikaMug** [comment]
No, I'm asking about the image containing "23 4., 41" - I need to see the entire text. I will look into the "Beacon" example separately.

**Comment by StKillReal** [comment]
![image](https://github.com/PikaMug/Quests/assets/60330193/21317ccf-4264-4dfc-805d-1124b7eb9731)
it changes the color after `%green%`, but hours timer is before `%green%hours`

**Comment by PikaMug** [comment]
I'm not asking about `timeDays:` - I need to know what string you're using for white text. Or did you just add it in front of the %green% on `timeDays:`? If so, that's no surprise that it's not working, as it's not meant for that internally.

**Comment by StKillReal** [comment]
571: questTooEarly: "%white% Квест %green%<quest> %white%будет доступен для повторного прохождения через %green%<time>"
%green% doesn't work here. I need to add it before every quest name and before every time abbrevitation (it doesn't work properly as you can see)

**Comment by PikaMug** [comment]
I see the problem, but unfortunately it will take much time to fix all of the strings which have this issue. Since you're able to compile the plugin, you might consider simply removing the ChatColor from code. For `questTooEarly`, you would go to BukkitPlayerListener.java and change this code...

```java
String early = BukkitLang.get(player, "questTooEarly");
early = early.replace("<quest>", ChatColor.AQUA + bukkitQuest.getName()
    + ChatColor.YELLOW);
early = early.replace("<time>", ChatColor.DARK_PURPLE 
    + BukkitMiscUtil.getTime(quester.getRemainingCooldown(bukkitQuest))
    + ChatColor.YELLOW);
```

...to this...

```java
String early = BukkitLang.get(player, "questTooEarly");
early = early.replace("<quest>", bukkitQuest.getName());
early = early.replace("<time>", BukkitMiscUtil.getTime(quester.getRemainingCooldown(bukkitQuest)));
```

**Comment by StKillReal** [comment]
Okay, but I think it should be fixed anway. Not everybody have ability to change parts of code just to change color of text
