### ISSUE TITLE
Potion Duration Not listed

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2205]
### What is your Quests version / build number (do *not* say "latest")?

5.0.2-b462

### Describe the problem and how to replicate it.

If you have a quest to brew a potion, the duration is not listed in the objectives given to the player, but quests does indeed care what duration is brewed. It just doesn't tell the player what duration to brew so they have to guess. It will complete the quest as expected, but it should tell the player what duration they're meant to be brewing.

In the screenshot, potions 2, 4 and 6 are all the longer durations of those potion types. If this was a stage based quest, Stage 1 being Brew Short Duration night vision and Stage 2 Brew Long Duration night vision, you'd have no idea.

Using the /quests editor and using the option 0 to load the item in hand to create the quest makes no difference (as mentioned in #954 ) Opening new issue as requested.

![image](https://github.com/PikaMug/Quests/assets/64336395/b320658e-4098-48d3-b877-af87afab98d1)

### Any console errors to share?

```shell
N/A
```

**Comment by PikaMug** [comment]
So I've been looking into this, and unfortunately it appears older versions of the Bukkit/Spigot API don't have a way to get the duration time (which is a problem since we support back to 1.8 as of writing). I can get the level (I, II, III, IV) instead, but some potions have an enhanced version that doesn't upgrade the level but _does_ extend the duration time (so there'd be no way to distinguish Potion of Leaping (3:00) from Potion of Leaping (8:00), and there's still Potion of Leaping II (1:30), for example). Could take me a while to sort something out.

**Comment by HorusApl** [comment]
It does seem to differentiate in the item meta as potion_name vs long_potion_name. The same seems to apply for tipped arrows and lingering potions as well, I can see this from the config if I use the load from hand via the quests editor. Unsure if this helps you, but thought it'd be relevant to comment.

**Comment by PikaMug** [comment]
Yes, but this has to be done through the API, and not reading the item's metadata directly. I was also looking to get the duration as your ticket stated, but I suppose just tacking "(Long)" or "+" on the end could work. Thanks for your input.

**Comment by PikaMug** [comment]
@HorusApl Please **delete or move your /Quests/lang** folder and give this build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/463/

Note the changes will only be apparent on Minecraft 1.9 or above.

**Comment by HorusApl** [comment]
Definitely doesn't look quite right. Using 1.20.4 so should be compatible with whatever method you're trying. As well, I think doing the + would be just as confusing for a player as not listing a duration at all. Can the exact duration of each item not be listed? Potion, tipped arrow, etc?

![image](https://github.com/PikaMug/Quests/assets/64336395/01e2c541-90ff-4e09-8eba-50c14404f4e5)

**Comment by HorusApl** [comment]
The + could mean Instant Health II, or for example the Jump Boost potion has the extended duration variant, and the II variant.

**Comment by HorusApl** [comment]
I have tried using the details list override for stages, but it doesn't track progress as there doesn't seem to be a placeholder or any such means to tell the player how far in the quest they are if I use this method of doing things. Otherwise, this would be a good fit.

![image](https://github.com/PikaMug/Quests/assets/64336395/9cd8f16a-9c8a-4db5-99f4-e5e62290ce62)

**Comment by PikaMug** [comment]
Looks like I neglected to account for Splash and Lingering Potions. The "+" or roman numeral is based off of how the [Minecraft Wiki](https://minecraft.fandom.com/wiki/Potion#Effect_potions) differentiates them. I'm open to alternatives but again, no, the exact duration is [not accessible via API](https://www.spigotmc.org/threads/get-any-potion-duration.647332/) (at least pre-1.14).

Overrides are a good alternative, but the progress count is a separate issue #2194

**Comment by PikaMug** [comment]
@HorusApl https://ci.codemc.io/job/PikaMug/job/Quests/465/

**Comment by HorusApl** [comment]
Can confirm this has worked for potions and I see the + for all potion types, and the II correctly. Tipped arrows do not appear to have been affected by your changes and still appear pre-changes.
![image](https://github.com/PikaMug/Quests/assets/64336395/bc6efa2e-90f4-45f8-905f-4f12d384cb78)

**Comment by HorusApl** [comment]
Each of these are the lower duration, longer duration and Swiftness II, in the order pictured.

**Comment by PikaMug** [comment]
At this point go ahead and make a separate ticket for arrows.
