### ISSUE TITLE
Further Brewing quest manipulation

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2206]
### What is your Quests version / build number (do *not* say "latest")?

5.0.2-b462

### Describe the problem and how to replicate it.

When doing any brew X potion quest, open the brewing interface with the objective potion needed to complete the quest in your inventory and a regular water bottle. Pick up the water bottle via left or right click so you can move it around, then while the water bottle is held, shift-click the desired quest objective potion. See attached video.

https://github.com/PikaMug/Quests/assets/64336395/c2f7de0c-3dcb-4fca-b8ed-543b94662e50

### Any console errors to share?

```shell
N/A
```

**Comment by PikaMug** [comment]
@HorusApl https://ci.codemc.io/job/PikaMug/job/Quests/464/

**Comment by HorusApl** [comment]
Can confirm this is fixed on build 464.
