### ISSUE TITLE
Tipped arrows duration/level not shown

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2208]
### What is your Quests version / build number (do *not* say "latest")?

5.0.2-b465

### Describe the problem and how to replicate it.

Tipped arrows should show their given potion effects to display like the recent potion effect changes in the latest build version.

![image](https://github.com/PikaMug/Quests/assets/64336395/d9245644-2071-4421-8de1-ebb65d018e94)

### Any console errors to share?

```shell
n/a
```

**Comment by PikaMug** [comment]
@HorusApl https://ci.codemc.io/job/PikaMug/job/Quests/466/

**Comment by HorusApl** [comment]
Once again looks good. Ty for the work and fast fixes.

![image](https://github.com/PikaMug/Quests/assets/64336395/e860ba91-f80d-48ef-86fb-2d33c26101f4)
