### ISSUE TITLE
/quest editor not working

### ISSUE THREAD

**Issue by joppiesaus123** [PikaMug/Quests#2209]
### What is your Quests version / build number (do *not* say "latest")?

5.0.2

### Describe the problem and how to replicate it.

When i try /quest editor it says "quest not found"

### Any console errors to share?

```shell
Only my username issued server command /quest editor
```

**Comment by PikaMug** [comment]
@joppiesaus123 Hello, the command is `/quests editor` not `/quest editor` :)
