### ISSUE TITLE
Error in log when trying to use reach block stage

### ISSUE THREAD

**Issue by gamelamp** [PikaMug/Quests#2217]
### What is your Quests version / build number (do *not* say "latest")?

Quests 5.0.3-b471

### Describe the problem and how to replicate it.

When I try to add a stage to a new quest about reaching a location, I get thrown a lot of errors. Same with set block start

### Any console errors to share?

```shell
https://paste.gg/p/anonymous/465914dd9148413d80723699a35fa02f
```

**Comment by PikaMug** [comment]
Looks like this problem was introduced recently in a7e9e41d68f3dc7c4a5844fbd44e59146e24d2aa and I'm working on a solution.

**Comment by gamelamp** [comment]
> Looks like this problem was introduced recently in [a7e9e41](https://github.com/PikaMug/Quests/commit/a7e9e41d68f3dc7c4a5844fbd44e59146e24d2aa) and I'm working on a solution.

wonderful :) thank you!!

**Comment by PikaMug** [comment]
@gamelamp I _think_ I've fixed this, but please make sure you're actually able to complete the objective.

https://ci.codemc.io/job/PikaMug/job/Quests/472/
