### ISSUE TITLE
Sending empty messages to the chat. and a few more problems...

### ISSUE THREAD

**Issue by barannnnnns** [PikaMug/Quests#2219]
### What is your Quests version / build number (do *not* say "latest")?

5.0.2-b469

### Describe the problem and how to replicate it.

1- I set some messages in the language file to empty but they continue to be sent to the chat as empty. This obviously doesn't make sense because why would I want to send an empty message to the chat :D.

for example:
When I set it to [objectives: ""] an empty message is sent to the chat.

2 - The reload command for messages does not work. So when I edit the messages, they do not reload. For this I need to restart the server. At the same time, I think there is an automatic language detection feature in the configuration. I don't know if there might be something related to this. 

I didn't make any changes to the configuration regarding this. My minecraft language is Turkish. I don't know if this is a bug or not.

3- I noticed that some texts were not edited.for example, when the task is completed, you can enter the chat 

Rewards: [line 1]
- (none) [line 2]

A text like  appears. but this "- (none)" part cannot be edited. Because there is no such option in the configuration. I want to delete this. 

My goal is to not send any messages when the task is completed or received. I am working on complex configurations and need such features. 
I may have said or misunderstood some things, please feel free to correct me on this. My English is not very good and I started using the plugin recently.

I hope I opened this topic under the correct heading. And also thank you for the plugin, it is a very nice plugin.

### Any console errors to share?

```shell
nope
```

**Comment by PikaMug** [comment]
Going forward, please limit problems to one per issue.

1 - This is a known issue. Simply open a "Suggest a feature" issue with a complete list of the string keys you want addressed. Note that certain keys like `journalTitle` and those considered "crucial" are not eligible.

2 - I believe `/questadmin reload` only reloads the default language designated in the config.yml file. I can look into this further if you open a "Report a bug" issue with step-by-step how to recreate the issue (including an example quest), but the simple solution is to just restart your server.

3 - It is the philosophy of this project that players must be notified of changes to their quest progression. This not only provides a consistent experience across servers, but also ensures that players are made aware that they are, in fact, making some progress. While we can discuss formatting in a new, dedicated issue, it is not in the interest of Quests to remove crucial messages.
