### ISSUE TITLE
A configuration option for messages that cannot be edited from the configuration.

### ISSUE THREAD

**Issue by barannnnnns** [PikaMug/Quests#2222]
### What does your feature do?

There is no configuration option for messages listing goals and rewards. In the picture, messages that do not have any configuration options are boxed in red.

I have two suggestions for this.

1. A true/false configuration can be offered to hide these.
2. These can be added to the language file as a message text and edited accordingly.

<img width="484" alt="1" src="https://github.com/PikaMug/Quests/assets/102471068/cd3520ec-6bfc-4b5b-bf4f-e31d175041c0">

<img width="502" alt="2" src="https://github.com/PikaMug/Quests/assets/102471068/b8fdfbef-5a00-499e-b23d-e277fcdecff5">

thanks <3

### How would people use it?

The main purpose of hiding or editing this is to allow more customization of message texts.

**Comment by PikaMug** [comment]
It is the philosophy of this project that players must be notified of changes to their quest progression. However, I will leave this open for discussion per #2219

**Comment by PikaMug** [comment]
Closing as there has been no further discussion after 5 months.
