### ISSUE TITLE
Command alias editing

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2224]
### What does your feature do?

Just looking to have a section in config.yml where we can disable/add aliases. Looking to both add /questing & /questlog and remove /qs which conflicts with Quickshop. I know I can edit the plugin.yml directly, but re-doing it every update isn't ideal.

### How would people use it?

Using external methods like commands.yml, MyCommand or other alias plugins cannot fix the above, and I think it'd be an appreciated feature.

**Comment by PikaMug** [comment]
As far as I know, there isn't a way to adjust aliases dynamically (or via config as you say)—whatever is in plugin.yml will be loaded at startup and that's that. However, I'd be more than open to reviewing a Pull Request that shows otherwise.

**Comment by HorusApl** [comment]
Not skilled enough to do that, but I have seen this done via other plugins. The most notable and open source being QuickShop itself that is causing the /qs command conflict:

https://github.com/Ghost-chu/QuickShop-Hikari/tree/hikari/quickshop-bukkit/src/main/java/com/ghostchu/quickshop/command

If it cannot be done or if it can be done on commission, then at least I tried. Thanks again.

**Comment by PikaMug** [comment]
@HorusApl If QuickShop can do this (the class you linked doesn't indicate whether it can) wouldn't the easy solution here be to change QuickShop's command alias?

If you want to consult with a developer, here's one option - https://www.spigotmc.org/forums/hiring-developers.55/
