### ISSUE TITLE
McMMO Skill Reward Allowing beyond max level

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2226]
### What is your Quests version / build number (do *not* say "latest")?

5.0.3-b474

### Describe the problem and how to replicate it.

McMMO has a config option to cap the max level of X skill at a certain number. If a quest gives a skill reward, it will take them above what should be the max level. It shouldn't be possible and just removing the quests from being completeable by those with a max level would remove it from those who don't have it as well.

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Any quest will do this if you are at max level of an McMMO skill, and complete a quest that gives an McMMO Level reward.

https://mclo.gs/MjtFzuU
```

**Comment by PikaMug** [comment]
What is the config option? This may be something mcMMO has to fix on their end.

**Comment by HorusApl** [comment]
Config option for what? In McMMO, you just set a max power level for any given skill. Normally a player cannot go above the max level unless an admin manually sets it, which is what appears to be happening here. As long as it does this, can't really use McMMO skill rewards as players can cheat mcmmo leaderboards, etc.

**Comment by PikaMug** [comment]
> Config option for what? In McMMO, you just set a max power level for any given skill. Normally a player cannot go above the max level unless an admin manually sets it, which is what appears to be happening here. As long as it does this, can't really use McMMO skill rewards as players can cheat mcmmo leaderboards, etc.

Right, what is the config option called? I'm not familiar with their configuration.

**Comment by HorusApl** [comment]
Under the main config.yml, each skill has its own option called Level_Cap: # Each skill can be set individually for a different cap, but mine is 7000. So it'd appear as Level_Cap: 7000
