### ISSUE TITLE
McMMO Skill Level rewards are not granted

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2227]
### What is your Quests version / build number (do *not* say "latest")?

5.0.3-b474

### Describe the problem and how to replicate it.

When doing a quest that has any skill reward of any type, the reward is not given if a details-override is set. Without it, it works fine. With it, it doesn't give anything.

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Example Quest:
https://mclo.gs/GoXd2dw
```

**Comment by PikaMug** [comment]
In your Quests config, try setting `console-logging` to 3 or higher, then try again. Let me know whether you see a "{player} was rewarded {skill} x {levels}" in your console.

**Comment by PikaMug** [comment]
Direct all Overhaul module inquiries to their issue tracker: https://github.com/Browsit/mcMMOQuestsModule
