### ISSUE TITLE
Tipped Arrow Crafting issues

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2228]
### What is your Quests version / build number (do *not* say "latest")?

5.0.3-b474

### Describe the problem and how to replicate it.

Tipped arrow crafting appears to be bugged. In a previous report (#2205), the tipped arrows has the "+" added to distinct for the different times available. No matter what time you actually craft, it will only count as the lesser version, and not the + version.

As well, shift-clicking the arrows out of the crafting table will prevent any progress to the quest. The same is not true for any other crafting quests.

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Example: https://mclo.gs/IrbKJc4

Skip to Stage 3, the first 2 stages work fine
```

**Comment by PikaMug** [comment]
https://ci.codemc.io/job/PikaMug/job/Quests/489/
