### ISSUE TITLE
Mohist 

### ISSUE THREAD

**Issue by rainbowboii** [PikaMug/Quests#2230]
### What is your Quests version / build number (do *not* say "latest")?

Quests 5.0.2-b469

### Describe the problem and how to replicate it.

using core Mohist 1.20.1-596 , when I tested this in another version of mohist everything worked as I described.
When i try to create quest or edit no one command like a input "1- Create new quest" or "2 - Edit a quest", not working.
When i try to input 1, 2 ,3  to chat nothing happens, but when i click on them it works, and when i input a quest name its too not working.

### Any console errors to share?

```shell
no errors
```

**Comment by PikaMug** [comment]
Mohist is not officially supported, but I'll try to find time to replicate this.

**Comment by rainbowboii** [comment]
> Mohist is not officially supported, but I'll try to find time to replicate this.

Thank you!

**Comment by PikaMug** [comment]
I've submitted a bug report to Mohist's issue tracker, linked above. Please direct further inquiries to that ticket.
