### ISSUE TITLE
Unable to Craft at all

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2247]
### What is your Quests version / build number (do *not* say "latest")?

5.0.6-b484

### Describe the problem and how to replicate it.

Not 100% sure how to re-produce, but having about 80% of my players reporting they can't craft anything. I am sure this is from my previous report #2245 , but the fix that was applied seems to completely break vanilla behavior even if you aren't on a quest. As seen in the video, there is no reason the player should be denied to crafting this item.

https://github.com/PikaMug/Quests/assets/64336395/e0f0e150-261c-4a4c-bdb7-c75ef1b65ec3

I see from the Discord https://discord.com/channels/506992958894243860/510222124237979674/1258803493897240606 I am not the only one with this issue. 

### Any console errors to share?

```shell
n/a
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Any crafting quest
```

**Comment by PikaMug** [comment]
@HorusApl This build should fix it for players whom do not have a craft objective:
https://ci.codemc.io/job/PikaMug/job/Quests/485/

**Comment by HorusApl** [comment]
Will test that as soon as able, but that just passes the issue. Players on the quest or off the quest will never understand why they are being prevented from crafting something. Would it be possible to only do the limiting check for the same item the quest calls for? If not, I think everyone would prefer the patch just be reverted.

**Comment by HorusApl** [comment]
Unlike the same issue I reported with brewing, where players will sort of know why, they won't with this type of quest
