### ISSUE TITLE
Integration with MythicMobs for Quest Initiation

### ISSUE THREAD

**Issue by tylerking** [PikaMug/Quests#2249]
### What does your feature do?

If MythicMobs is installed (and Citizens is not used), you can set an NPC as a MythicMob to start a quest. This feature allows for more dynamic and engaging quest interactions by utilizing MythicMobs advanced NPC capabilities.

### How would people use it?

People would use this feature to create more interactive and challenging quests by leveraging the advanced NPC behaviors and customization provided by MythicMobs. This would benefit all users by enhancing the game-play experience, making quests more immersive and varied. Server administrators can craft unique quest scenarios that require players to engage with specialized NPCs, thereby increasing player engagement and satisfaction.

**Comment by PikaMug** [comment]
Hello, I presume you're talking about https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Guides/Making-an-NPC

Unfortunately, these are just Armor Stands; not actual player entities. So while it would be possible, I'm afraid it's not within the scope of Quests to support these.

**Comment by tylerking** [comment]
I actually don’t make them that way. I make regular player mobs and change their ai movements to what I want and prevent them from being hurt. So they aren’t armor stands.
