### ISSUE TITLE
Crop Names Invalid

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2256]
### What is your Quests version / build number (do *not* say "latest")?

5.0.6-b491

### Describe the problem and how to replicate it.

Attempt to do any quest with carrots, potatoes or beetroot (I am sure there are others, but this is what's effecting me atm). In the past, my potato quests needed the name "POTATOES" for fully grown potato harvesting. This no longer works, I have tried POTATO, POTATOES, POTATOS and it either errors out or doesn't count quest progress.

### Any console errors to share?

```shell
[08:01:41 WARN]: POTATOES x 128 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: POTATOES x 1000 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: POTATOES x 3000 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: POTATOES x 9000 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: POTATOES x 18000 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: BEETROOTS x 320 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: POTATOES x 64 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: CARROTS x 64 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
[08:01:41 WARN]: BEETROOTS x 64 is invalid! You may need to update your quests.yml or actions.yml in accordance with https://bit.ly/2BkBNNN
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000016':
    name: Carrots Go Brrr # Tested
    ask-message: Finish <quest>
    finish-message: '&8&l[&x&7&6&8&b&f&5&lBOT&8&l]&r &fTake another quest with &x&f&f&d&5&7&e&l/quests&f!'
    stages:
      ordered:
        '1':
          break-block-names:
          - CARROTS
          break-block-amounts:
          - 320
          break-block-durability:
          - 7
          start-event: 24HrTimer
    rewards:
      money: 15000
      quest-points: 1
      custom-rewards:
        req1:
          name: mcMMO Overhaul Skill Reward
          data:
            Skill Amount: '10'
            Skill Type: Herbalism
      details-override:
      - '&x&3&1&f&7&6&6$15,000'
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: false
```

**Comment by PikaMug** [comment]
Which version of Minecraft is this on?

**Comment by HorusApl** [comment]
1.21

**Comment by PikaMug** [comment]
Looks like yet another Paper change. Blocks that don't have an obtainable item equivalent can no longer be represented as an ItemStack. Not quite sure how to work around this, but I'll keep you posted.

**Comment by PikaMug** [comment]
@HorusApl Please try https://ci.codemc.io/job/PikaMug/job/Quests/493/

**Comment by HorusApl** [comment]
@PikaMug That build does recognize the item, but it doesn't recognize the age. So if I have a carrot quest at age 7 (max growth) it will count if the player breaks it at any age. Example quest:

  '000016':
    name: Carrots Go Brrr # Tested
    ask-message: Finish <quest>
    finish-message: '&8&l[&x&7&6&8&b&f&5&lBOT&8&l]&r &fTake another quest with &x&f&f&d&5&7&e&l/quests&f!'
    stages:
      ordered:
        '1':
          break-block-names:
          - CARROTS
          break-block-amounts:
          - 320
          break-block-durability:
          - 7
          start-event: 24HrTimer
    rewards:
      money: 15000
      quest-points: 1
      custom-rewards:
        req1:
          name: mcMMO Overhaul Skill Reward
          data:
            Skill Amount: '10'
            Skill Type: Herbalism
      details-override:
      - '&x&3&1&f&7&6&6$15,000'
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: false

**Comment by PikaMug** [comment]
@HorusApl https://ci.codemc.io/job/PikaMug/job/Quests/494/

**Comment by HorusApl** [comment]
Alright that seems to work for carrots & potatoes, but nothing seed based. So beetroots and wheat either don't count at all, or don't count any progress. I imagine the same would be true for nether wart. I have tried BEETROOT, BEETROOTS, BEETROOT_SEEDS, etc. and either no progress or it doesn't respect the age.

  '000016':
    name: Carrots Go Brrr # Tested
    ask-message: Finish <quest>
    finish-message: '&8&l[&x&7&6&8&b&f&5&lBOT&8&l]&r &fTake another quest with &x&f&f&d&5&7&e&l/quests&f!'
    stages:
      ordered:
        '1':
          break-block-names:
          - CARROTS
          - POTATOES
          - BEETROOTS
          break-block-amounts:
          - 320
          - 320
          - 320
          break-block-durability:
          - 7
          - 7
          - 3
          start-event: 24HrTimer
    rewards:
      money: 15000
      quest-points: 1
      custom-rewards:
        req1:
          name: mcMMO Overhaul Skill Reward
          data:
            Skill Amount: '10'
            Skill Type: Herbalism
      details-override:
      - '&x&3&1&f&7&6&6$15,000'
    planner:
      cooldown: 604800
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: false
      use-parties-plugin: false
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: false

**Comment by PikaMug** [comment]
@HorusApl Please try https://ci.codemc.io/job/PikaMug/job/Quests/495/ which is increments the build number. If you should encounter any issues, please open a new ticket.
