### ISSUE TITLE
Compatability with FancyNPCS plugin

### ISSUE THREAD

**Issue by Reflect-good** [PikaMug/Quests#2259]
### What does your feature do?

I have a server that recently changed to FancyNPCS for our npcs, since it handles better than citizens, I was wondering if it is possible to get the plugin possibly compatible with that other npc plugin so I can use it for quests, thanks.

### How would people use it?

Deliver Items to NPC, things like that.

**Comment by PikaMug** [comment]
Quests does not currently support FancyNpcs. You can either use [ZNPCsPlus](https://www.spigotmc.org/resources/znpcsplus.109380/) (which also uses packets) instead, or [hire a developer](https://pikamug.gitbook.io/quests/casual/modules#want-support-for-other-plugins-or-features) to add integration via pull request or other means.
