### ISSUE TITLE
named mobs

### ISSUE THREAD

**Issue by mpmpTV** [PikaMug/Quests#2263]
### Where else have you looked for answers to this question?

Hello, im trying to make quest when  you  need to kill zombie but this zombie has nametag.
there is a chance to add mob name in quest like Kill zombie Named:blabla bcs when i make it like regular zombie it doesnt count.

### Share your question with as much detail as possible.

Hello, im trying to make quest when  you  need to kill zombie but this zombie has nametag.
there is a chance to add mob name in quest like Kill zombie Named:blabla bcs when i make it like regular zombie it doesnt count.

**Comment by PikaMug** [comment]
I'm afraid Quests is not designed to do this. You might consider one of the many [modules](https://pikamug.gitbook.io/quests/casual/modules) available or [having someone] code your own.
