### ISSUE TITLE
Finishing a quest objective can trigger a chat spam of exclamation marks.

### ISSUE THREAD

**Issue by nuttapillar** [PikaMug/Quests#2264]
### What is your Quests version / build number (do *not* say "latest")?

5.06 b490

### Describe the problem and how to replicate it.

Several players have been reporting this issue, but I had no idea what it was caused by. Then I finished a quest objective, and I started getting it too.
Now I'm getting a constant spam of "!" in the chat.
![image](https://github.com/user-attachments/assets/dccfcf28-5e75-4c19-ab41-3ac644009ced)

### Any console errors to share?

```shell
No errors.
```

**Comment by nuttapillar** [comment]
Advancing to the next stage fixed the issue for now.

**Comment by PikaMug** [comment]
I've searched through all of Quests files and there isn't any logging that would just output an exclamation point. I suppose it could be some bug that's repeating the last character of that sentence, but I couldn't find any evidence of that either.

I'd ask that you remove all other non-essential plugins to make sure whether Quests is behind this. If you find that it is, please update your ticket with an example quest and reply below.
