### ISSUE TITLE
MySQL Usage vs YAML

### ISSUE THREAD

**Issue by HorusApl** [PikaMug/Quests#2277]
### Where else have you looked for answers to this question?

Didn't find much on Discord

### Share your question with as much detail as possible.

I have a ton of quests (230+) and players pretty addicted to completing them, I am finding reloading the plugin, especially on server startup, Quests really struggles to load all of it. Would this problem be improved by switching to MySQL vs YAML? Or is this just a reality of this many quests/etc? 

I see there is already an add-on to convert progress, and have heard of bugs resetting all quests progress when using MySQL. Is the progress issue still around, or is that not related to MySQL vs yaml?

**Comment by PikaMug** [comment]
At this time, only player data is eligible for MySQL. It would be nice to offer more storage options for quests/actions/conditions in the future.

That said, and assuming a good connection to your MySQL server, you will see a marginal improvement when players join (or when they start their first quest if `generate-files-on-join` is off). It may help a little at startup, but not significantly. As said in #2273 this "struggle" is temporary, and its speed largely dependent on available resources.

I assume you're referring to [QuestsConverter](https://github.com/PikaMug/QuestsConverter). I have not heard of that bug (unless you mean [this](https://github.com/PikaMug/Quests/issues/2201)), but backing up your data before a large operation is always a smart move.
