### ISSUE TITLE
Memory Leak 1.21 

### ISSUE THREAD

**Issue by julianvdhogen** [PikaMug/Quests#2283]
### What is your Quests version / build number (do *not* say "latest")?

5.1.2
5.1.1
5.1.0
5.0.5
5.0.4

### Describe the problem and how to replicate it.

Quest Plugin Performance Issue

When generating new chunks, the Quest plugin continuously checks for quest updates via the YAML file. This process results in an endless loop of loading, causing excessive server RAM usage and tick rate overload. Consequently, the server crashes.

The plugin consumes 100% of the server's ticks, RAM, and CPU resources.

I tested multiple server setups, all yielding the same outcome:

RAM configurations: 6 GB, 10 GB, 20 GB, 60 GB
CPU configurations: AMD Ryzen 7 (12 threads), Intel i7 11th Gen (6 threads), AMD Ryzen 9 (24 threads)
Server versions: Purpur 1.21 (builds 2284, 2283, 2282) and Paper 1.21 (builds 130, 129)
These issues seem to occur exclusively on version 1.21, and the presence of other plugins does not affect the outcome. The problem persists even when only the Quest plugin and chunk generation are enabled.

### Any console errors to share?

```shell
Error Trace:

me.pikamug.quests.BukkitQuestsPlugin.lambda$delayLoadQuestInfo$3()
me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.init()
me.pikamug.quests.storage.implementation.file.BukkitQuestYamlStorage.loadQuest()
Error Description: Java heap out of memory.
```

**Comment by PikaMug** [comment]
Reminds me of #2273 

> When generating new chunks, the Quest plugin continuously checks for quest updates via the YAML file

How did you come to this conclusion? The `delayLoadQuestInfo` method from your error is only called once at startup.

> Error Description: Java heap out of memory.

This indicates that the server does not have enough heap space. You can assign this for your server using `java -Xms<initial heap size> -Xmx<maximum heap size>` options.
