### ISSUE TITLE
The menu with the conditions in the stage does not open

### ISSUE THREAD

**Issue by 4ebyrek99** [PikaMug/Quests#2284]
### What is your Quests version / build number (do *not* say "latest")?

5.1.2-b501

### Describe the problem and how to replicate it.

I created the conditions, they have been preserved. But when creating a quest in a stage, I can't open a list with conditions.

### Any console errors to share?

```shell
There are no mistakes
```

**Comment by PikaMug** [comment]
Hello, I'm afraid I don't understand your meaning. Please try rephrasing or including a screenshot.

**Comment by 4ebyrek99** [comment]
I'd better upload a video
[Google Drive](https://drive.google.com/file/d/1D9jDXB-Fsxg0bauw5WQYFiOEyl3zHbys/view?usp=drivesdk)

**Comment by PikaMug** [comment]
@4ebyrek99 You must set at least one stage objective (i.e. break blocks) before opening the conditions menu.
