### ISSUE TITLE
Break Blocks Quest

### ISSUE THREAD

**Issue by Killablez** [PikaMug/Quests#2288]
### What does your feature do?

let people break Iron Ore and other kinds of Ore In the blocks for stages.
( I Tried Typing in Iron Ore it does not work so i dont even think I can choose iron ore or even any ore as it does not know that block)

### How would people use it?

It will allow players to complete their quest by breaking this block

**Comment by PikaMug** [comment]
This is already a feature. Ask for help in Discord or create a bug report with quest example.

**Comment by Killablez** [comment]
My bad cz I did try adding the Iron Ore and it did not work i did try with other ores but i think i will test out again if really cant i will ask for help in discord
