### ISSUE TITLE
[Quests] NPC UUID was null for Denizen script named ....

### ISSUE THREAD

**Issue by ilClaun** [PikaMug/Quests#2289]
### Where else have you looked for answers to this question?

i tried to receive support from Denizen's Discord, Quest's Discord,

### Share your question with as much detail as possible.

The error is: [Quests] NPC UUID was null for Denizen script named dialogueMike1

this is my Denizen Script:
dialogueMike1:
  type: task
  script:
    - narrate "<npc.name> dice: Ciao, come posso aiutarti oggi?"
    - narrate "§61. §7§n<element[Hai delle missioni?].on_click[1].on_hover[Clicca per rispondere]>"

**Comment by PikaMug** [comment]
This is not a question; please create a new issue using Report a bug. Make sure to include steps to recreate this.
