### ISSUE TITLE
add hide attribute option to categories

### ISSUE THREAD

**Issue by AlFr3on111** [PikaMug/Quests#2291]
### What does your feature do?

it hide the info that appears on tools/armors
![image](https://github.com/user-attachments/assets/20f499cf-eb72-468d-9ad9-974eea6fe1dd)

### How would people use it?

by config

hide_attributes: true

**Comment by PikaMug** [comment]
Quests does not offer fine-tuned settings for its NPC GUI. Either use QuestsGUI, or open a bug report with example quest if you want a fix applied globally.
