### ISSUE TITLE
the plugin loads infinitely

### ISSUE THREAD

**Issue by RomainFerr** [PikaMug/Quests#2300]
### What is your Quests version / build number (do *not* say "latest")?

5.1.3

### Describe the problem and how to replicate it.

hello, i have this problem : 

the plugin loads infinitely
moreover, it is not detected by Autorank

Thank you in advance for your help

### Any console errors to share?

```shell
[08:28:18 INFO]: Plugin is currently loading. Please try again later!
```

**Comment by PikaMug** [comment]
Thanks for reporting this. Will need to see your startup log. Also try updating to Quests 5.1.4

**Comment by PikaMug** [comment]
That's not your startup log, but the error does indicate you have a number of quests with invalid data. Could be from manually editing quests.yml (which is not supported) but regardless you'll need to open the file to correct the issues. For example:

`.StageFormatException: 'break-block-names' has invalid item name minecraft:emerald_ore, see quest Mineur d'émeraude stage 1`

This one is telling you that "minecraft:emerald_ore" is invalid formatting for an item associated with the first stage Break Block objective of quest Mineur d'émeraude. Either delete the stage/quest or change it to something valid (I believe it should be "EMERALD_ORE"). You can try asking on the community discord if you need more help, but generally this is something you'll need to address on your own.

**Comment by RomainFerr** [comment]
what is the startup log ?
