### ISSUE TITLE
ZNPCsPlus GUI Not Working

### ISSUE THREAD

**Issue by imlaptev** [PikaMug/Quests#2304]
### What is your Quests version / build number (do *not* say "latest")?

5.1.4-b507
ZNPCs version 2.0.0-SNAPSHOT
Server version 1.21

### Describe the problem and how to replicate it.

Right clicking an assigned NPC does not trigger any gui opening. Heres a quick detailed video for everything I'm doing:

https://imgur.com/a/4Z8iRyH

### Any console errors to share?

```shell
N/A
```

**Comment by PikaMug** [comment]
My initial thought is there's possibly another plugin blocking the NPC interact event. I'll try to replicate this soon.

**Comment by PikaMug** [comment]
I was able to get a GUI without issue on 1.21 using the latest 2.0.0-SNAPSHOT build of ZNPCsPlus. Make sure that you've set a GUI item display in addition to choosing an NPC. If you're still having trouble, edit your original post to include an example quest and request the ticket be re-opened below.
