### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by enterih** [PikaMug/Quests#312]
Hello

Today i have a great idea.... Ok i stop with this text :P 

Do you can add a MySQL Support? Maybe with the rewrite for 1.13? 

I don't find any issue about mysql. If i'm blind, so link me to an issue.

**Comment by FlyingPikachu** [comment]
What would you use it for?

**Comment by Sprungente** [comment]
Maybe for required quests from another server.
Quests rows who is going around different servers
Questpoints who are on every server the same

It sound special and its special. I don‘t know if other people who has a network it needing too



Am 24.02.2018 um 23:37 schrieb FlyingPikachu <notifications@github.com<mailto:notifications@github.com>>:


What would you use it for?

**Comment by Cerexus** [comment]
MySQL Support would be a great thing! Please add this to your Plugin :)

**Comment by Kisstehflo** [comment]
I think that database support should be added that it transfer everything that is flat filed into the database. That way you can have the same quests cross servers and keep updating them. I feel like the reason for database has been increasing. Think about having a network with multiple servers that track the same goals. Cross-Server questing!

**Comment by DestinyMC** [comment]
Please implement this ASAP, willing to pay for functionality.

**Comment by DeniedINC** [comment]
Would love MySQL support especially since my rpg server will be running on shards.

**Comment by JPotyka** [comment]
> The database will have to contain the completed quests, which stage they are on for their current quests, active quests, tracked quests, stuff that is probably all contained flat files.

> I'm running an RPG server that has multiple servers. I want the players to be able to do a quest on one server and it will update for all the other servers.

I have the same problem on my RPG server, MySQL would be nice!

**Comment by PikaMug** [comment]
This ticket has not been forgotten, but is currently very low priority. PRs welcome!

**Comment by Kryniowesegryderiusz** [comment]
It would be awesome to see mysql integration. Not only for networks, but also for normal players - there are a lot of files in there :C

**Comment by Gamer05HD** [comment]
A MySQL database Support would be realy usefull i would be glad to see it because i need it for a Server Network where we have a Towny World and a Farmworld and i need it to connect both for Quests

**Comment by GerwinVerkerk** [comment]
I am also looking for a Quest plugin with MySQL support. Please implement this feature! Would definitely pay for it or donate.

**Comment by Qfrijters** [comment]
Looking for this too, pls update <3

**Comment by Ayon224** [comment]
Please add this!! its been 2 years since this request D:

**Comment by PikaMug** [comment]
MySQL support for player data has been implemented as of https://ci.codemc.io/job/PikaMug/job/Quests/166/

Backup your _/Quests/data_ folder before use. Support for other types of data may be added at a later date. There is currently no way to convert existing YAML data to MySQL. Keep an eye on the [Community Discord](https://discordapp.com/invite/d56CQ6e) for updates.

**Comment by Cerexus** [comment]
@PikaMug 

What exactly is possible with the mysql feature?
Possible to sync quests and playerdata between servers?
Is the sync fast enough to handle the server switch of the player? (is there a delay or something like that)
..

**Comment by PikaMug** [comment]
@Cerexus https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Storage#mysql

**Comment by Cerexus** [comment]
@PikaMug Is Quest sync planned too?

**Comment by PikaMug** [comment]
@Cerexus Eventually. No ETA
