### ISSUE TITLE
Quest GUI for nonNPC

### ISSUE THREAD

**Issue by SeussCZ** [PikaMug/Quests#322]
Hi, is possible to make quest GUI for blocks, signs etc?

**Comment by FlyingPikachu** [comment]
Elaborate? What would this GUI look like and how would it function?

**Comment by SeussCZ** [comment]
The same inventory GUI for view quests like NPC.

**Comment by FlyingPikachu** [comment]
Since you wouldn't have NPCs to assign quests to, which quests would show up in this GUI? All of them?

**Comment by SeussCZ** [comment]
Yes, i want to set all quests on the signs with title. Signs can show quests without GUI now (in chat only).

**Comment by FlyingPikachu** [comment]
You've lost me again. I get that you want a GUI that...

- isn't linked to NPCs, and
- shows all available quests

...but what are you saying about Signs? I don't understand.

**Comment by FlyingPikachu** [comment]
Ah I see. It shouldn't be too difficult to add the GUI. If it were accessible by using _/quests take_, then you could just use a plugins that links commands to Signs like https://www.spigotmc.org/resources/command-signs.10512/

**Comment by SeussCZ** [comment]
But with this command i cant open the GUI. "/quests take name" can open quests in chat only (not with GUI).

**Comment by FlyingPikachu** [comment]
The sign from that plugin would run the command for you.

**Comment by SeussCZ** [comment]
yes i know, but this command cant open the GUI.

**Comment by FlyingPikachu** [comment]
I would change the command so it opens the GUI.

**Comment by PikaMug** [comment]
With the release of QuestsGUI v0.2, this feature is available through the _/quests list_ command.
https://www.spigotmc.org/resources/questsgui.71666/
