### ISSUE TITLE
Quest Pathlines Suggestion

### ISSUE THREAD

**Issue by Redzilla22** [PikaMug/Quests#454]
Multiple choice quest -
Allowing you to choose a direction in quests such as one npc might give you a followup quest to kill/maim while another npc would choose a passive side and you decide to talk your way out of everything.

Pathlines -
Instead of improving on quests by doing certain quests to progress, certain quests you choose will reject any further progress of certain quests.
(So you can have certain pathlines and force them to continue that path, so you can have a good and evil kind of quest play)

**Comment by Worlfy** [comment]
I wonder how the pathline restriction will work out. In my head, it could easily be restricted to simply not being able to accept any other quest until that one is finished, and have the rest just labeled with the "must've finished x quest" requirement, if you know what I mean

**Comment by Redzilla22** [comment]
I mean depends how you've set out the quests. My quests speak from npcs such as "Lilian: Hello!" so it would work along the lines for me "Lilian: You are not fit for this quest" and such, it works the opposite of requiring to complete specific quests in some sort of areas.
So if you have completed quest A you cannot do quest B and so forth.

**Comment by PikaMug** [comment]
Looks as though this should already be possible with Quest blocks:

![req](https://user-images.githubusercontent.com/2267126/57876659-e680e800-77e3-11e9-9a4e-fe51f2d9f3b0.png)
