### ISSUE TITLE
Quest Journal as a GUI instead

### ISSUE THREAD

**Issue by BytedByte** [PikaMug/Quests#570]
Would be extremely nice having your current quests show up in a gui instead of the book journal. 
Especially when you have multiple active quests at once. Gets annoying and kind of messy having to click through a book constantly.

Thanks

**Comment by trungbmt** [comment]
I really like it
Hope it will be done
And the other thing is, let's add an option to open quests journal by command instead of opening a journal book

**Comment by KsuKsuKsu** [comment]
Yes, please, i want it too!

**Comment by ArathiaMC** [comment]
Agreed!

**Comment by PikaMug** [comment]
It is now possible for an external resource to cancel the QuestsCommandPreQuestsJournalEvent, then open some GUI as a replacement, using Quester#getObjectives() as the sort of information. My hopes are to provide such a resource through Spigot sometime in the near future.
