### ISSUE TITLE
Player kills bug when log out and log in

### ISSUE THREAD

**Issue by SeDark** [PikaMug/Quests#605]
Quests 3.5.8-b580

https://i.gyazo.com/d36dc59c8dcab1e12d046fbc8f62750d.png

This error is referenced with the one of yesterday but is not the same, apparently when you are in the game the progress is shown correctly but if you come out in between visually it puts back that you have 0.

https://i.gyazo.com/6db6bc2acb4ed8c674838ad9734b7f5f.png

That is to say, I had killed a player, I have left the server and my score has been saved, but upon entering I put back that I have 0.

I have continued testing, I killed 3 players when in the file I had 1 but in the game it was reset, I left and it has been saved that I have killed 3 players and not 4, also when entering it resets to 0.

Apparently it does not load the progress of the player when entering the game.

Thanks for reading and forgive my bad English

**Comment by Segysmundo** [comment]
To add up on this bug, I tested it out myself and if you leave the server and rejoin, additionally from having your count reset to 0, if you keep getting kills and then use /quest to check on the status it will still display 0 regardless of the progress done since rejoining the server.

**Comment by Srborjaa** [comment]
Hi there,

I have also seen this error recently, I was using the plugin and I didn't get noticed until now by the users.
I have only 1 mission of this type, but yes, the stats are reset everytime the players log off of the server.

Greetings.

**Comment by FlyingPikachu** [comment]
Possibly related to the recently fixed #649

**Comment by FlyingPikachu** [comment]
Closing as issue should be resolved per my last comment. Contributors to this ticket may comment to re-open. Otherwise, please open a new ticket if you have a similar issue.

**Comment by Segysmundo** [comment]
Just tried it out with latest plugin version. Same problem occurs, don't think that fix was related to this bug.

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/744/ once its available

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/745/ once it's available.
