### ISSUE TITLE
Heroes Exp for Current Classes Only?

### ISSUE THREAD

**Issue by Foxersthe** [PikaMug/Quests#607]
**What does your feature do?**
Currently, when a quest gives Heroes exp to multiple classes, the player gets that exp for ALL of those classes, even if they've never used that class. How about a way for exp points for only classes the player has active?
**How would people use it?**
When a player finishes a quest they'll get exp for only the Heroes classes they have active.
Of course, there should an option to toggle between this mode or the original way, either in the config or through the in-game editor.

**Comment by PikaMug** [comment]
Sorry for the late reply. The solution here is to set a Heroes class Requirement for the quest to encourage that the player have it active. If you don't want the player to switch classes during the objectives, use a recent version of Quests to disable commands during the quest in the Edit Options window.
