### ISSUE TITLE
arrow bug when there is 2 reach locations objectives for gps

### ISSUE THREAD

**Issue by ozm8** [PikaMug/Quests#611]
**What is your Quests version / build number (do _not_ say "latest")?** 
Quests-3.5.9 

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Make a quest to reach a location then make another objective strait after it to reach another location

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Basically what happens the gps works for the first reach location but then when the next reach location objective needs to be done the arrow just sits there for some reason.

Here is a screenshot:  https://i.imgur.com/2NmGFn4.png

**Comment by FlyingPikachu** [comment]
Just want to say hasn't gone ignored, but rather it's a difficult fix since it appears to be a problem with GPS itself. Since I do not have access to its source code to confirm that, I've left this ticket open pending a solution.

**Comment by PikaMug** [comment]
Preparing to request a solution from the author. To recap, here are the steps to replicate with GPS v2.7.2:

1. Create a new quest with a reach-location-objective in each stage.
2. Navigate to first destination/stage successfully.
3. The moment navigation for second destination/stage begins, error spam:

![gps_error](https://user-images.githubusercontent.com/2267126/57878307-bd625680-77e7-11e9-9513-fa1716e00d5a.png)

Relogging does not clear the issue. Here's where Quests calls startGPS(): https://github.com/PikaMug/Quest/blob/706f47c14a8a456d3fa375857d59004c75b1f531/main/src/main/java/me/blackvein/quests/Quest.java#L315

**Comment by PikaMug** [comment]
This turned out to be GPS requiring a more unique internal name for each point.

Use http://ci.ac3-servers.eu/job/Quests/747/ once it's available.
