### ISSUE TITLE
Force cooldown timer when players quit quests

### ISSUE THREAD

**Issue by DragaoNimhe** [PikaMug/Quests#615]
**What does your feature do?**
Currently, when people quit quests, it does not initiate the set cooldown. This means that players can start my delivery quest, get the event that gives them an item (in this case potion) for delivery, quit the quest, and start it over and over again to get the potion each time.
**How would people use it?**
Perhaps you could add a config setting to disable this if people prefer, like "cooldown-on-quit: true".

**Comment by FlyingPikachu** [comment]
Can you provide an example quest from quests.yml from to test this with? Please use Pastebin

**Comment by DragaoNimhe** [comment]
Not sure how much this will help because it's fairly long and relies on delivery to 3 other npcs, but here you go!

Quest: https://pastebin.com/JDq8qHsN

and relevant Events: https://pastebin.com/Kag4ZjAy

**Comment by DragaoNimhe** [comment]
Here it is without the random japanese characters lol, apologies; i was working on a project that required japanese locale.

New Quest: https://pastebin.com/JKZmwh1Q

New Events: https://pastebin.com/Vb0Rp42p

**Comment by SXRWahrheit** [comment]
A suggestion to accompany this user's use-case: A quit-event for quests. They could use a script to check for and take the item (but it would also be useful for many other purposes).
