### ISSUE TITLE
Suggestion: EpicBosses support

### ISSUE THREAD

**Issue by nicuch** [PikaMug/Quests#616]
**What does your feature do?**
The same features that MythicMobs adds.
With [EpicBosses ](https://www.spigotmc.org/resources/epicbosses-the-ultimate-bosses-plugin.34159/)you can add custom mobs.

**How would people use it?**
The same features that MythicMobs adds.

Note: I'll try adding it. :)

**Comment by FlyingPikachu** [comment]
Thanks for your suggestion!

A module would be the only way I could do this as, unlike GPS, I do not have the developer's permission to write and upload a slave jar for remote compilation. Even if I did, the low level of integration would likely be better suited to a module, anyway.

That said, I'll reach out to the developer on Spigot and see if they'd be willing to provide a jar for local compilation.

**Comment by nicuch** [comment]
Even if is a premium plugin, the source code is available [here](https://gitlab.com/Songoda/EpicBosses).
So I guess `[anyone](https://gitlab.com/Songoda/EpicBosses/blob/master/LICENSE)` can.

**Comment by Sprungente** [comment]
Feel free to add support for Boss https://www.spigotmc.org/resources/sale-%E2%98%9B-boss-unbelievable-custom-monsters-1-8-9-1-13-2.46497/ too, kangarko is a friendly dude. 

in my eyes it is more powerful than EpicBosses
for example see reviews
![image](https://user-images.githubusercontent.com/15361899/50868078-1dff0400-13ae-11e9-8227-ba9bcf534e96.png)

**Comment by FlyingPikachu** [comment]
@Sprungente that’s a different plugin, so please open a new issue if you’d like to request it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PikaMug** [comment]
After observing development of the plugin, I've decided it is not in my best interest to support EpicBosses. Its authors appeared to restart their version numbering after the plugin reportedly came under new management. Although it does contain a robust events system, recent reviews of the plugin lead me to believe that a Quest module would not gain much traction beyond this request.
