### ISSUE TITLE
Boss Support

### ISSUE THREAD

**Issue by Sprungente** [PikaMug/Quests#622]
Feel free to add support for Boss https://www.spigotmc.org/resources/sale-%E2%98%9B-boss-unbelievable-custom-monsters-1-8-9-1-13-2.46497/ too, kangarko is a friendly dude.

**Comment by arturek1666** [comment]
Yeah I would love the Quests to support this plugin the API is available as well :)
https://github.com/kangarko/Boss/wiki/Developer-API

**Comment by PikaMug** [comment]
Thanks for your suggestion. Boss appears to have a robust events system that would be suitable for a Quests module. I may look into creating one at a later date.

**Comment by PikaMug** [comment]
@Sprungente @arturek1666 Available now at https://www.spigotmc.org/resources/boss-quests-module.66973/
