### ISSUE TITLE
Skills Pro Support

### ISSUE THREAD

**Issue by JTGgamer** [PikaMug/Quests#623]
If you could add support to Skills Pro ( https://www.spigotmc.org/resources/skills-pro-1-7-x-1-13-full-recode-complete.8981/ ) it would be much appreciated.

**Comment by PikaMug** [comment]
Looking at the [Lite version](https://www.spigotmc.org/resources/skills-lite-try-out-a-smaller-version-of-skills-pro-1-7-x-1-8-x.2142/) of the plugin, it appears possible to support its party system.

However, documentation for the API is scarce (there's a SkillLevelUpEvent and SkillImproveEvent - no discernable difference between the two and the skill being reported on isn't visible). That, combined with Skill Pro's high price (9.99 USD at time of writing) versus its low download count lead me to believe that developing a Quests module for it would not be in my best interest.
