### ISSUE TITLE
Suggest: A 'symbol' that allows you to go to next line

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#661]
**What does your feature do?**

Allow into the Objective-displays a way to go to the next line into the explanations.
Then Objectives-displays could be more explicit, and way more cool with many indications, instead of actually.
+ The quests journal will be more easy to use and to understand, and more configurable for the Admin.

**How would people use it?**
Without this feature 'next line' insertion:

[https://i.imgur.com/AIv8DFH.png](https://i.imgur.com/AIv8DFH.png)

With the feature enabled:

[https://i.imgur.com/UH68gSu.png](https://i.imgur.com/UH68gSu.png)

As you can see, it's way better with the next-line ^^
You already can do that with many and many spaces, but if some1 have a resource-pack, it change everything, + you have to calculate every little spaces + do 10 to 15 Quests reload to have exactly what you want ... for each quests that you create xD
And It's easier to code, and to understand.

It could be a symbol like colours, but that go to the next line, like "§w"
Thanks for the answer =)

Ps: Thanks for the new updates, it finally works xD i finally have a stable version of quests+ MMQuestsObjectives, i've waited it since 4 months =)

**Comment by FlyingPikachu** [comment]
Glad you're enjoying the plugin.

A few ways come to mind that might already made this possible. First, are you using objective-overrides? These can be set per stage in the editor and essentially overwrite the built-in format. Second, assuming you have the right code, have you tried '&w'? I believe the Quests might translate codes that start with `&`. Lastly, please check to see if the line break placeholder from the following link is supported. If not, I'll look into possibly adding it:
https://github.com/FlyingPikachu/Quests/wiki/Casual-%E2%80%90-Translations#formatting

**Comment by tiradorus** [comment]
Hi!
"&w" was an example ^^', it's not existing in the minecraft-game.
I said &w because the "w" isn't used as format or color.

But i know that is possible because another plugin use a special character like this to go to the next line.
This plugin is 'Automessage' and it use "\n" to go to the next line

Ps: i use objective-Overide yes ^^on many stages and many quests. And i've juste tried to use %br% ... It's not working :S It write in the journal %br% and in the chat it write %br%.
I've tried on "Objective Overide", and on MytchiMob Extension, "Objective name"

I think that thoses format (With %%) are allowed only on language files, not on Objective-displays =)

**Comment by FlyingPikachu** [comment]
Alright. Have you confirmed `\n` doesn't work? That _is_ Java's new line character for Unix/Linux/New Mac. If your server is on Old Mac try `\r` and Windows try `\r\n`

Source - https://www.baeldung.com/java-string-newline

**Comment by tiradorus** [comment]
Confirmed, i've tryied months ago, and tried again now.
I've tried   \n  , \r,   \r\n ...
All of thoses try have write in the chat \n etc etc ... Same in the quest journal.
I've tryied it into "Objective-display-Overide" and into "MythicMobs Objective-name"

**Comment by tiradorus** [comment]
Hi, i'll come back few days later =)
Here for having some news, to taste the heat a bit :D

Could you tell me if my suggestion could be implemented in few days, or it would take long? Or was it just an enchancement?
'Cause i'm waiting this update to entierely rework my whole quests's files ^^ That's why i ask you this ;)

Did i have to wait a bit more tohave the new update?
Or did i have to start the quests-rework now instead if i have to redo-it after?
Need an answer :D 

Have a nice day! =)

**Comment by Endothelium** [comment]
Hello,

I agree, \n and equivalents are not working for anything message in quest related ( finish message, display etc).

Since in the plugin all happen with text, more options for text formatting would be really good.

**Comment by tiradorus** [comment]
Bump =)

Ps: i've seen that minecraft use \\n to go to the next line
C'ause when you try to give you a book with next line messages, it appear like that:
"/give @p written_book{pages:["{\"text\":\"Line1\\nLine2\\nLine3\\nLine4\"}"],title:"Quests test",author:"",display:{Lore:["Quests"]}}"

As you can see, Line1,2,3 and 4 are separated by a \\n, you can try ingame, it gives you a book with Separated lines ^^

**Comment by i9hdkill** [comment]
Any news on this?

We are using white spaces for this for years and it's not fun
http://prntscr.com/ni3mli

**Comment by PikaMug** [comment]
The next release of Quests will support line break in the objective override, start message, complete message, and delay message. You must use **\n** as the line break character. The plugin should save your message in the file as such:

`objective-override: "line1 \n line2"`

If it doesn't work after upgrading, check your quests.yml and ensure the double quotes (") are present. If not, add them, as they're required for this to work.
