### ISSUE TITLE
Change Partie Support

### ISSUE THREAD

**Issue by kleinesgumi** [PikaMug/Quests#679]
Current parties works any players that have the name quest just one need to finish the quest and both have it done.

Change it pls to progress, if player has be same quest like "kill 5/5 Zombies" one player kills one the another get the kill to shared progress like any another MMO Partie system.

And the solo quest feature, thats means the Quest progress not get shared.

Requirement:
 You need to be in a Party (of 2 players or more) for Stage and Quest Requirement.

that would be good for Big Boss Quests.

**Comment by Garrarop** [comment]
Quests only for parties.
That it is required to be at a party so that they can begin the quest, and also that it depends on the size of the party.
To make a quest specifically for 2, 3 or any number of people. and the quest of 1 person only count for him.

**Comment by PikaMug** [comment]
The next release of Quests will allow you to set a level between 1 and 4 for how often you want Quests to share progress with fellow party/group members. It will be under the Edit Options -> Multiplayer menu and may require you update your strings.yml to see it.

Levels will function as follows:
1 = Everything; constantly share progress. If one player breaks a block, all players break a block.
2 = Objectives; if one player completes an objective, all members advance to the next objective.
3 = Stages; if one player completes a stage, all members advance to the next stage.
4 = Quests; similar to previous functionality. All members finish when one completes a quest.
