### ISSUE TITLE
/quest information while Questdelay

### ISSUE THREAD

**Issue by kleinesgumi** [PikaMug/Quests#692]
Example:
          delay: 600
while the delay is counting with /quest the quest not apearing until the delay  runs out.

My suggestion: display the "stageEditorDelayMessage" while the delay is running with /quest

**Comment by FlyingPikachu** [comment]
Although I'm able to replicate this, I'm not quite sure yet whether it's intentional or not. Hope to return to this with more information soon.

**Comment by FlyingPikachu** [comment]
Likely applicable code block:
https://github.com/FlyingPikachu/Quests/blob/575e4d011daf9021571808967f4a16cdcaab5fa2/src/main/java/me/blackvein/quests/listeners/CmdExecutor.java#L168

**Comment by kleinesgumi** [comment]
Mhhh.

**Comment by KsuKsuKsu** [comment]
I would also like to know when the quest will be available to me again.
You can show this in the list of quests in gray and opposite this display the remaining time. If the player is online, then at the end of the timer, you can send him a message that the quest is available again.

**Comment by PikaMug** [comment]
The next release of Quests will show the time remaining. I'm still not entirely sure this should be revealed to the player, but I'm open to making an option to hide it should that be requested in the future.
