### ISSUE TITLE
PlaceholderAPI placeholder

### ISSUE THREAD

**Issue by kleinesgumi** [PikaMug/Quests#709]
some placeholder for Quests in PlaceholderAPI.
https://www.spigotmc.org/resources/placeholderapi.6245/
like:
%quests_questpoints% = shows questpoints as a number.
%quests_currentquestsN% = shows the total number of accepted current quests.
%quests_questsdone% = shows the total number of quests done.

**Comment by FlyingPikachu** [comment]
Thanks for the suggestion. Something like this would be low priority, but I'll consider it.

**Comment by Diclo** [comment]
you could also add:
%quests_time_until_available_<quests>% = time to repeat the quest.
%quests_is_available_<quests>% = quests avaible (true / false), for complex menus.

**Comment by PikaMug** [comment]
This is now being worked on. Please submit suggestions for placeholders.

**Comment by nkuczm** [comment]
Has there been any progress on placeholders? I would like for there to be a placeholder in which you can show the name of the current quest or the description.

**Comment by PikaMug** [comment]
@nkuczm It’s essentially done, just need suggestions. What do you mean by “the description”?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nkuczm** [comment]
The current progress, like: "Break Stone: 0/10." So basically the output from /quest.

**Comment by PikaMug** [comment]
Consider it done. Anything else?

**Comment by nkuczm** [comment]
Not that I can think of, that seems like a good start for now having the name and the current progress.

**Comment by PikaMug** [comment]
Available as of Quests 3.7.5
