### ISSUE TITLE
Quests with fail timers and no progress quit on dc

### ISSUE THREAD

**Issue by DragaoNimhe** [PikaMug/Quests#712]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.3-b655

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
- Create a timed fail event.
- Add it to the initial Event section of the quest. 
- Accept the quest. The timer will pop up in chat to let you know you have ___ seconds to finish the quest.
- Log out of the server.
- Log back in. The quest will now be quit.
- If any progress is made on the quest before the player exits, the quest will not quit.

This is a problem for us because we currently have player quitting disabled, as we have some quests that begin by giving the player an item to deliver to another npc... so now they can just bypass that by taking a quest, logging out, then logging back in.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Here's the same timer event and quest I sent last time, but this occurs with every single quest on my server, as we added timers to all of them: https://pastebin.com/RZFhgqWe
Not sure if you saw my reply on the previous closed ticket, but as I stated there I have -not- manually edited my quests.yml. All of my quests are created and edited in-game using the editor.

**Comment by PikaMug** [comment]
This would be resolved by the suggested fix in my Jan 7 comment from OP's other ticket, #615. As such, I am closing this in favor of the complimentary ticket.
