### ISSUE TITLE
Gui doesn't seem to display all available quests

### ISSUE THREAD

**Issue by FuneralSuits** [PikaMug/Quests#715]
Hello,
So to start,
### Quests Version: 3.6.3-b668

The issue is that not all of my quests that I should be able to view in an NPC's gui are there.
[Here is a screenshot](https://i.imgur.com/Y3jC04y.png) of the NPC (number 26)'s gui looks like

In the screenshot there are 7 quests shown in the gui, on my server I have a total of 10 quests. 9 of which should be displaying on NPC 26's gui.

[Here's a pastebin](https://pastebin.com/5yZJQiJK) of my quests.yml to see if it was some error on my part, when the screenshot was taken I had 28 questpoints.

The two quests that are missing are called "The Enchanters Potions" (custom 3) and "Too Many Crops" (custom 5)

Thank you for looking into this,
- Funeral

**Comment by FlyingPikachu** [comment]
What is your Minecraft server version?

**Comment by FuneralSuits** [comment]
1.13.2, running Paper Spigot

**Comment by FlyingPikachu** [comment]
Sorry for the delay in response. Could you please post your data.yml file?

**Comment by FuneralSuits** [comment]
Sure thing!
https://pastebin.com/pRNpeGUL

**Comment by FlyingPikachu** [comment]
That looks right to me.

I think what's happening is that some quests are set to be given by NPC 25 rather than 26. If I set all the quests to use the same NPC id, I get the full loadout:

![jeff](https://user-images.githubusercontent.com/2267126/54053141-5c4d4f80-41b4-11e9-9f30-cb48a336fbe9.png)

**Comment by FuneralSuits** [comment]
Interesting, so if you don't have all the quests coming from the same NPC are you having the same issue as me?

**Comment by FlyingPikachu** [comment]
No, just if I set a few quests to a different NPC, it works as expected.

Could it be you've completed some of the quests already without realizing? To check, follow these steps:

1. Visit https://mcuuid.net/ and enter your Minecraft username
2. Go to the _/plugins/Quests/data_ folder
3. Find the .yml file with named with your UUID
4. Look for info on competed quests. For example, here's what mine looks like:
```yaml
completed-Quests:
- Help the Desk Assistant
completedRedoableQuests:
- Help the Desk Assistant
completedQuestTimes:
- 1552077147714
amountsCompletedQuests:
- Help the Desk Assistant
amountsCompleted:
- 1
```

It could also be you're currently taking (but haven't finished) the problematic quests. To check this, just use the _/quest_ command in-game.
