### ISSUE TITLE
Delivery Questinformation and suggestion

### ISSUE THREAD

**Issue by kleinesgumi** [PikaMug/Quests#716]
Current are Items that need to be deliverd are:
"Deliver MATERIAL-NAME to NPC: 35/35"

but i using cool items with displayname that need to be:
"Deliver 35 of DISPLAY-NAME to NPC"

Language file: deliver: "Deliver <item> to <npc>"
better would be: "Deliver <item> to <npc> <count>"

or make it possbile to objective-override: 'Deliver <item> to <npc> of <count>'

**Comment by PikaMug** [comment]
So I sat down to start working on this, but it looks like I already did at some point! In recent versions of Quests, you'll find this node in the language files:

`deliver: "Deliver <item> to <npc>"`

Which you can obviously rearrange to satisfy this ticket. Enjoy!
