### ISSUE TITLE
Kill multiple mobs stage, only one mob showing up with /quest

### ISSUE THREAD

**Issue by RedMachete** [PikaMug/Quests#723]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.8-b668
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When creating a stage where you must kill multiple entities, only the first one shows up when viewing quest objectives through /quest. However, all the objectives can be seen through journal.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

screenshots
https://cdn.discordapp.com/attachments/506994379378917385/552590585106661396/2019-03-05_15.33.46.png
https://cdn.discordapp.com/attachments/506994379378917385/552590582866771971/2019-03-05_15.33.26.png
https://cdn.discordapp.com/attachments/506994379378917385/552590580631470080/2019-03-05_15.33.15.png

**Comment by FlyingPikachu** [comment]
I'm thinking this have been related to #720 

Please try the latest dev build and let me know if it resolves the issue:
http://ci.ac3-servers.eu/job/Quests/692/

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
