### ISSUE TITLE
Second Delay got skipped

### ISSUE THREAD

**Issue by kleinesgumi** [PikaMug/Quests#726]
Quests version 3.6.4-b689
Paper Spigot: 1.8.8

When the first delay running out and again the delievery then no delay and can deliver again and then comes the third delay.

>   custom69:
    name: Some Dirt
    npc-giver-id: 54
    ask-message: ''
    finish-message: ''
    gui-display: name-BOOK_AND_QUILL:amount-1
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-DIRT:amount-1
          npc-delivery-ids:
          - 54
          delivery-messages:
          - y
          delay: 1
        '2':
          items-to-deliver:
          - name-DIRT:amount-1
          npc-delivery-ids:
          - 54
          delivery-messages:
          - y
          delay: 30
        '3':
          items-to-deliver:
          - name-DIRT:amount-1
          npc-delivery-ids:
          - 54
          delivery-messages:
          - y
          delay: 1

**Comment by FlyingPikachu** [comment]
Please use Pastebin or Hastebin for the example quest. I can't do anything with the way Github formats your copy/paste.

**Comment by kleinesgumi** [comment]
https://pastebin.com/wCagkrrr

**Comment by KsuKsuKsu** [comment]
i had the same problem. I refused to use delays :(
Help us someone please

**Comment by KsuKsuKsu** [comment]
Up. Please fix it, i need it so much

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/743/

There's a chance this fix could cause unintended side effects with delays. As always, please make a new Github issue should new problems arise.

**Comment by KsuKsuKsu** [comment]
Thank you so much!!!!!! <3
