### ISSUE TITLE
objective-override not working anymore.

### ISSUE THREAD

**Issue by kleinesgumi** [PikaMug/Quests#730]
Quests version 3.6.4-b692
PaperSpigot 1.8.8
-------------------
objective override not working anymore since some updates,
the original objective showed up.

Only on (Completed) gets the objective-override message.

Tested with Delivering, Custom Kill, Location Reach and Talking
-------------------

>   custom80:
    name: Test
    npc-giver-id: 42
    ask-message: ''
    finish-message: ''
    gui-display: name-BOOK_AND_QUILL:amount-1
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-WOOD_SWORD:amount-1
          npc-delivery-ids:
          - 42
          delivery-messages:
          - Delivered!
          objective-override: §aGive a Woodsword!
          start-message: ''
        '2':
          npc-ids-to-talk-to:
          - 42
          objective-override: §aTest B
        '3':
          locations-to-reach:
          - farmmap -42.0 50.0 563.0
          reach-location-radii:
          - 3
          reach-location-names:
          - Test
          start-message: ''
          objective-override: §aTest C
        '4':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 1
              data:
                Objective Name: test
          objective-override: §aTest D

**Comment by FlyingPikachu** [comment]
Please use Pastebin or Hastebin for the example quest. I can't do anything with the way Github formats your copy/paste.

**Comment by kleinesgumi** [comment]
https://pastebin.com/TrwSztPw

**Comment by Garrarop** [comment]
I have the same problem

**Comment by trungbmt** [comment]
I have the same problem

**Comment by PikaMug** [comment]
Looking into this now. Where is it that the override isn't showing? In the Quest Journal?

**Comment by Garrarop** [comment]
I sent an example in discord.
Wait a minute and i will share it to you here

**Comment by Garrarop** [comment]
![Captura](https://user-images.githubusercontent.com/30799098/55354415-11191a80-549c-11e9-9a59-cb94dd8f4f32.png)

**Comment by PikaMug** [comment]
@Garrarop Thanks!

This should now be resolved in http://ci.ac3-servers.eu/job/Quests/716/ (it may take a few minutes before the build becomes available).
