### ISSUE TITLE
Quitting and finishing quests bugged (not found)

### ISSUE THREAD

**Issue by SXRWahrheit** [PikaMug/Quests#735]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.4-b697

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Attempt to quit or force finish a quest

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

1-week expiry

https://pastebin.com/mFVNpEzB

**Comment by PikaMug** [comment]
Need more info. Does the attempt fail? For which quest?

**Comment by SXRWahrheit** [comment]
Any of em.
![2019-03-16_18 54 17](https://user-images.githubusercontent.com/774463/54483143-f0ef2780-481c-11e9-883d-e6ed76cb41bc.png)

**Comment by PikaMug** [comment]
I picked the first one in the file test with and had no problem quitting the quest.

Did you include "(Daily)" in the quest name? Must be an exact match.

![nav](https://user-images.githubusercontent.com/2267126/54484094-9adaae00-4835-11e9-93fa-7cc4df71c7ed.png)

**Comment by SXRWahrheit** [comment]
Huh. Previously it would auto-complete and/or infer what quest was being referenced if there was a partial match. Works with the full name; thanks.

**Comment by PikaMug** [comment]
Not sure if something’s changed but I know it works that way for Edit a Quest in the Quest Editor. I’ll look into expanding that functionality.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PikaMug** [comment]
Try http://ci.ac3-servers.eu/job/Quests/703/ once available

**Comment by andinis** [comment]
I have kind of the same issue, I noticed that if you add colorcodes to quests its impossible to quit them since version 3.6.0, even if you add the colorcode to the quit command it doesn't  recognize the quest
