### ISSUE TITLE
Crafting stage is not showing up.

### ISSUE THREAD

**Issue by itaquito** [PikaMug/Quests#737]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.6.3-b668
Paper spigot: Paper version git-Paper-564 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When you make a quest with a stage where the player needs to craft a item, the plugin doesnt shows that stage when the player is doing the quest.

![image](https://user-images.githubusercontent.com/30180886/54484514-04ef5500-482e-11e9-938c-60423f2ab3dd.png)
It only shows the messege after the player crafts the item, not before. For example when a player needs to break some blocks the plugin does send the ""objective"" to the player
![image](https://user-images.githubusercontent.com/30180886/54484519-1fc1c980-482e-11e9-8977-478e3a60ca97.png)
But when the player needs to craft something that doesnt happen.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/e6FfYSiT

**Comment by PikaMug** [comment]
If what you're trying to say is that Craft Diamond Block should say 0/1 rather than 1/1, then yes I was able to replicate the issue on Quests 3.6.4 and will look into a fix.

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/701/ once available
