### ISSUE TITLE
Suggestion: Be able to put a name to a command reward

### ISSUE THREAD

**Issue by itaquito** [PikaMug/Quests#738]
**What does your feature do?**
If a quest only has commands as rewards, when a player finishes the quest the messege will look empty:
![image](https://user-images.githubusercontent.com/30180886/54484906-f48ea880-4834-11e9-992f-014deff58cb8.png)
My suggestion is to make names for the commands, so for example if I want the command "kill player" to be the reward, I can set that command a name: "1x suicide" so that name is shown on the messege.
```
Rewards;
 1x suicide
```
Of course, setting a name for the command would be optional, so if the owner of the server doesnt want to show which command is executing he can just leave it blank and nothing will show when the player finishes the quest.
**How would people use it?**
People would use it so their quests look a little better, also those people that only have commands as rewards would really like this feature.

**Comment by PikaMug** [comment]
As of e2a37fbb4cc883bf6d3d278b5858cefa00123662 Quests will show the command in the rewards list, but I realize this isn't exactly what you asked for. Will keep this ticket open as it's considered.

**Comment by PikaMug** [comment]
It just occurred to me that you should be able to use Objective display override to accomplish this.

**Comment by PikaMug** [comment]
Looks like I was mistaken.

**Comment by PikaMug** [comment]
This will be available in the next release of Quests.
