### ISSUE TITLE
Maven compile project issue

### ISSUE THREAD

**Issue by CodeGod000** [PikaMug/Quests#739]
Hello, I just followed the instructions to compile a fork of quests but every time I try to compile I get an error with heroes. It is: could not resolve dependencies for project me.blackvein.quests:quests-main.jar:3.6.5 failure to fine com.herocraftonline.heroes:heroes-stripped:jar:4dd3dd85 in https://jitpack.io resolution will not be re-attempted until updated.

**Comment by PikaMug** [comment]
You’d want to reach out to that fork’s maintainer, then. Did you mean to say you cloned this repository and it failed?

**Comment by CodeGod000** [comment]
Yeah I cloned it and when I tried to compile it there was a build failure.

**Comment by PikaMug** [comment]
Please clone again and let me know the results.

**Comment by CodeGod000** [comment]
It worked! Thanks again!
