### ISSUE TITLE
Sudden console issues...

### ISSUE THREAD

**Issue by Busigbanan** [PikaMug/Quests#743]
Hi.
I am having some issues in my console from Quests all of a sudden. I don't know if its a conflict caused by another plugin but I have tried removing that since I got the issues.  I installed the latest release fresh but still the same problems.

https://pastebin.com/GBx52mU3

Thanks!

**Comment by PikaMug** [comment]
Please give http://ci.ac3-servers.eu/job/Quests/706/ a try and let me know the results.

**Comment by Busigbanan** [comment]
Did that and now its still a lot of issues.. but not quests.. Im starting  to believe its the spigot jar file from yesterday..
https://pastebin.com/nRdSZPP3

**Comment by PikaMug** [comment]
Possibly, although I see there's also new updates available for Simple Elevators and Lib's Disguises. Good luck!

**Comment by Busigbanan** [comment]
thanks
