### ISSUE TITLE
Quests with requirements not met shown in /quests list

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#747]
Hi! My Quests version is latest (sorry xD) **v3.3.4-b316**
And `CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)`

I have in my config file that:
`ignore-locked-quests: true`

But when player executes the command **/quests list**, he can see all quests, even they are not yet available to him (due to conditions). Can you fix it?

When a player clicks on the NPC, everything works well here. He sees only those quests that he can take right now.

**Comment by SXRWahrheit** [comment]
Please follow the support format and include a pastebin of your quests.yml file.

**Comment by KsuKsuKsu** [comment]
https://pastebin.com/2xk2WZVU

**Comment by SXRWahrheit** [comment]
Thanks! I can confirm that quests show up in `/quests list` regardless of whether the requirements are met. It also shows quests that have already been completed.

I'm guessing PikaMug will say that this is working as intended and that your request is for an enhancement, so that's how I'm going to label this issue - of course he can change it if he wants.

**Comment by KsuKsuKsu** [comment]
I also checked it on the version v3.6.4-b697.

Thank you! He could have made a new command that would take into account the requirements. And also remove from the list quests that are temporarily unavailable (if the time has not come yet) and quests that are completed.

But now how can a player find out if a quest is available for him? If a player sees a new quest in the list, he will go to look for an NPC, and when he finds it, he will be upset because he cannot take this quest.

These are two problems I do not know how to solve:
1) How will the player find the NPC he needs if he only knows the name of the quest from the command /quests list?
2) How does a player learn about a new quest or that he can repeat the old one?

**Comment by KsuKsuKsu** [comment]
Up

**Comment by PikaMug** [comment]
The `ignore-locked-quests: true` setting was added by @BlockCat in 813462e4583fd6490bad4e2e2679c4103e431a51

"Added ignore-locked-quests config-option, when a player tries to take a quest from a npc, if the player can't take the quest, then don't display the quest in the list."

It was never intended to prevent seeing them in /quests list, but rather the list of available quests when you click an NPC. However, it stands to reason that it should probably do both. I'll look into it.

**Comment by PikaMug** [comment]
Done. Will be available in the next release of Quests.

**Comment by KsuKsuKsu** [comment]
Oh my god. I love you Pika!!!!!!!
