### ISSUE TITLE
Written Books Don't Play Nice w/ NPC Delivery

### ISSUE THREAD

**Issue by mythicman95** [PikaMug/Quests#750]
**What is your Quests version / build number (3.6.4)?**

**While setting up what item will be delivered under NPC/Delivery, choosing a written book causes the quest to not be saved.**

**No example as I cannot save and reload to create it**

**Comment by PikaMug** [comment]
When you say "choosing a written book", are you loading it from hand or just entering Written_Book for the item name?

**Comment by mythicman95** [comment]
Loading from hand with the 0 option.

**Comment by PikaMug** [comment]
Apologies for the delay in reply. It seems Written Books are working fine. However, using a colon (':') in the book's title or text is likely what broke. YAML (the config format for most Bukkit plugins) uses colons as data separators, so using one in a book breaks the plugin when it tries to read from file.

I'll look into denying books that contain colons, but in the meantime the recommended fix is to remove all colons from Written Books before loading from hand.

**Comment by mythicman95** [comment]
Kind of related while you're poking around there, the length of the characteristics of the book seemed to cause a problem in the plugin. Something about the unique stats of the book made the data so long that I think it overloaded something and made a duplicate quest that's only reachable from the config. Again, doesn't break anything but there you go

**Comment by PikaMug** [comment]
Resolved with recent dev builds which use an improved method for storing Itemstacks. After updating, you'll have to open the quest in the editor, then save it and run _/questadmin reload_.

https://ci.codemc.org/job/PikaMug/job/Quests/

**Warning:** The builds linked above are experimental. Make sure to back up your Quests folder before attempting to use it.
