### ISSUE TITLE
Consider answer choices

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#751]
When we offer answers, it doesn’t matter that a player chose from several options. Can you make the response dependent and able to react on a specific answer in a special way?

Example:

```
Will you go to the farmer or the police?
- Farmer
- Police

If a player chooses a farmer, then he goes on one branch of events and quests. 
If a player chooses the police, then he goes on another branch.
```

**Comment by SXRWahrheit** [comment]
You can do this with Denizen.

**Comment by KsuKsuKsu** [comment]
I did not know about that. Where can I find an example of dialogue with a choice of answer and different consequences and interaction with the "Quests" plugin? Denizen looks like a heavy and complicated plugin.

**Comment by SXRWahrheit** [comment]
Set up a simple dialogue with an NPC to have the player make the choice of profession, and then give them a permissions node that is required for the next quest, like `profession.farmer` or something. Denizen is a scripting language, and it takes a little learning, but it is very powerful. If you join the Denizen Discord server, the helpers there will link you to the tutorial videos.

**Comment by KsuKsuKsu** [comment]
Thank you a lot, you're so nice!
