### ISSUE TITLE
Command to enable or disable a specific quest

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#752]
Create a command that will enable or disable a specific quest without rebooting the server.
Now this is only possible if you add or remove the permission.

**Comment by SXRWahrheit** [comment]
Why can't you just use permissions for this?

**Comment by KsuKsuKsu** [comment]
Because I want to make some quests available only at a certain point. I have a plugin that can execute commands at the right time. Although I can use it to issue a permit. Okay, you are right. Sorry so much!

**Comment by SXRWahrheit** [comment]
A future update will also likely allow you to use Denizen tag placeholders via PlaceholderAPI in Quest requirements, which will make it easier to enable/disable quests like this.
