### ISSUE TITLE
start-message

### ISSUE THREAD

**Issue by DenisJ9798** [PikaMug/Quests#754]
how to divide the text with a new line?

**Comment by PikaMug** [comment]
What text? Please be more specific.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DenisJ9798** [comment]
Well, for example in some plugins, in order to make a new line you need to enter \n

**Comment by PikaMug** [comment]
Yes, but what text are you trying to alter? Something in the quest editor? Item name? NPC name?

**Comment by PikaMug** [comment]
According to [this thread](https://bukkit.org/threads/how-to-make-new-line.94159/), using "\n" should work if your string isn't too long. If that doesn't work for you, let me know and I'll look into a solution.

**Comment by DenisJ9798** [comment]
It didn't help

**Comment by PikaMug** [comment]
@DenisJ9798 Please give http://ci.ac3-servers.eu/job/Quests/715/ a try once available

**Comment by DenisJ9798** [comment]
> @DenisJ9798 Please give http://ci.ac3-servers.eu/job/Quests/715/ a try once available

Not help
