### ISSUE TITLE
Console Error Spam - Task #135 for Quests v3.6.4-b697 generated an exception java.lang.NoClassDefFoundError: org/bukkit/Particle

### ISSUE THREAD

**Issue by DriftingZero** [PikaMug/Quests#756]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.4-b697

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Console error : https://pastebin.com/m29CJ7Jy

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Please check whether the latest dev build resolves the issue:
http://ci.ac3-servers.eu/job/Quests/715/

**Comment by PikaMug** [comment]
Appears to already have been fixed in 0146ce1f4163f8083c0809fb799dc1f5afbe0c3c
