### ISSUE TITLE
Feature request: Configuration option to remove message formatting

### ISSUE THREAD

**Issue by SlimeDog** [PikaMug/Quests#757]
Please implement configuration option to specify formatting for all messages. In particular, red console/log messages do not read well on my blue console screen. The message file should include all messages, as well as plugin prefixes.

**What does your feature do?**
Allow operator to specify message content, including colors and other formatting.

**How would people use it?**
Incorporate Quests messaging seamlessly into server design.

**Comment by PikaMug** [comment]
Thanks for your interest in Quests!  This suggested doesn't seem ideal, as it wouldn't cater to those looking to simply change colors rather than disable them. Therefore, it's my opinion that the best solution would be to add console messages to the language files, which could then be formatted with color to your liking per https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#formatting

However, given that one could simply change the background color of one's console screen, this doesn't seem very high-priority. I'll leave this open until such time it warrants further attention.

**Comment by SlimeDog** [comment]
I much prefer entries in the language file. That is what I meant by "configuration" but perhaps that wasn't clear (I appreciate that it could be interpreted as applying to _config.yml_).

I do not intend to change the color of my screen. In particular, I will not change it to white, just to satisfy bad color choices enforced by a plugin.

**Comment by PikaMug** [comment]
Took a second look at this and realized that, regardless of whether we add to the language files or include an option to format all messages, there are hundreds of hardcoded strings that would need to be addressed, most of which do not use ChatColor.RED, and more than half of which are only displayed in the console if/when an error occurs. It became apparent that adding these to the language files would be a unreasonable overhead for translators, and future bug reports would likely necessitate converting errors back to English before I can even get started on them.

As such, I've decided not to proceed with this ticket, however you're welcome to come up with a list of specific messages which bother you and I'll try to address them individually.

**Comment by SlimeDog** [comment]
I assume messages to the console are routed through a single path. I think you could just wrap that appropriately to manage a configuration option to remove all formatting. Other plugins have done so (often at my request).

**Comment by PikaMug** [comment]
While editor and chat messages are routed, console messages are output directly through the Bukkit or JavaPlugin logger. As you say, wrapping them would be useful if adding a config option for formatting, but requires the same amount of work. I'd still prefer to simply correct whichever few console messages have formatting and let the window app use its default color.

**Comment by SlimeDog** [comment]
OK. For starters, **questsadmin** itself (ie., help).

**Comment by PikaMug** [comment]
You originally requested a solution for "console/log messages" and while /questsadmin is _accessible_ by the console, it is not a logging message. As such, its colors can already be modified in the language files by following https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#formatting

**Comment by SlimeDog** [comment]
My language file contains no color format codes (eg, %red%). I didn't realize that I should use %reset% to remove the default colors. That doesn't resolve all the color codes, but it helps a lot. Thanks.
