### ISSUE TITLE
Feature request: Support useful commands at the console

### ISSUE THREAD

**Issue by SlimeDog** [PikaMug/Quests#758]
Please implement execution of useful commands at the console. "Useful" should include most of the quests commands, especially:
- quests editor
- quests info
- quests list
- quests _quest_
- quests stats _player_
- quests top _n_

**What does your feature do?**
Allow management of most Quests functionality at the console.

**How would people use it?**
Allow management of most Quests functionality at the console, without having to connect a client.

**Comment by PikaMug** [comment]
Some of these like _/quests stats [player]_ would be easy, but I have no interest whatsoever in re-coding _/quests editor_ as there are too many prompts which have options for things like loading items from hand or right-clicking NPCs to get their ID. I'd be glad to review a PR, though.

**Comment by SlimeDog** [comment]
I have no issues with the editor being limited to in-game.

**Comment by PikaMug** [comment]
This commit I've just pushed supports the use of the following commands in the console:

- /quests
- /quests info
- /quests list
- /quests top [number]

Per prior discussion, _/quests editor_ is not supported. The _/quests stats_ command is ineligible as no statistics can be given (the console is not a player), however, a followup commit will aim to support _/questadmin stats [player]_ from the console.

**Comment by SlimeDog** [comment]
Thanks.
