### ISSUE TITLE
Could not pass event PlayerMoveEvent to Quests v3.6.5-b717

### ISSUE THREAD

**Issue by Jakey401** [PikaMug/Quests#763]
Hey! Haven't played MC in a while so i'm unsure if this is a simple fix or not, however i am getting this error: 
07.04 00:42:15 [Server] ERROR Could not pass event PlayerMoveEvent to Quests v3.6.5-b717 https://pastebin.com/J0LBVLmh

it happens when i'm trying to use citizen commands to create an NPC and when the plugin loads

**Comment by Jakey401** [comment]
Another thing to mention not sure if i may probably just need to update however:

I am on the latest spigot build, but i'm 24 versions behind in what i assume are development builds?

**Comment by PikaMug** [comment]
Try http://ci.ac3-servers.eu/job/Quests/719/ once available

**Comment by Jakey401** [comment]
Hey not sure if i should make a new thread or not however, https://pastebin.com/KxRfUE61 on the latest version (5 hours ago) i get another PlayerMoveEvent error as seen in the pastebin

**Comment by PikaMug** [comment]
Although it couldn't hurt to update Spigot, the issue appears to be that your Citizens NPC registry is returning null. Perhaps your file is corrupted or Citizens needs updating? I'm not sure of the cause, so I can't actually test anything.

Try http://ci.ac3-servers.eu/job/Quests/721/ to see if that stops the errors. Note that this build will not allow use of Citizens until the NPC registry is fixed. Seek help from the developers of Citizens if necessary.
