### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by jeannen** [PikaMug/Quests#766]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.5

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The plugin isn't loading. I'm using a custom-updated version of PhatLoots for 1.13
https://pastebin.com/4KdALXTj

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Quests only support the official version of PhatLoots. However, since integration can't be disabled, I'll look into mitigating the error.

**Comment by jeannen** [comment]
Okay, thanks ! :)

**Comment by PikaMug** [comment]
@jeannen Use http://ci.ac3-servers.eu/job/Quests/723/ once it's available
