### ISSUE TITLE
Custom item data not working

### ISSUE THREAD

**Issue by jeannen** [PikaMug/Quests#767]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.5

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When I set a custom item as requirement, and then /questadmin reload, it does not works

```
Config file:
   requirements:
      items:
      - 'name-DIAMOND_SWORD:amount-1:data-2:displayname-§9Empalroz:lore-:lore-§f鏤
        §cDégâts: §712:meta-type-UNSPECIFIC:attribute-modifiers-{GENERIC_ATTACK_DAMAGE=[AttributeModifier{uuid=00000000-3e2c-d31e-0000-000024fee45e,
        name=generic.attackDamage, operation=ADD_NUMBER, amount=11.0, slot=HAND}]}:ItemFlags-[HIDE_ATTRIBUTES,
        HIDE_UNBREAKABLE]:Unbreakable-true:Damage-2:internal-H4sIAAAAAAAAAGWOQQuCQBCFR6iQIIiCrl06dFkwM1xvjTnE4i7K7prUZSHT//8TsiALmsM7fG/evJkC+LBQqhCWlHGYCimsIAMwgdUXW4un3GWo8EzHLbzHh9mw0Ec0jDRq8mE+0Jc6kYFPqkSpi5sHy8GshZQu1YS558F6wJkwmEr6VJZojLiQ9/vk+6y9lgRjUxc6+/Oqqi/dxHESR1EYsIY/DizaRzvGm46ztuVtkIRNl9w5PAGPzFzIAAEAAA=='
      
```

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/jqNEfN0w

**Comment by jeannen** [comment]
Custom items data doesn't work neither for the Item GUI Display (it just remove datas)

**Comment by PikaMug** [comment]
You cannot use colons (‘:’) in your lore. I’ll look into preventing this in the future.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
