### ISSUE TITLE
entity.enderman.namen

### ISSUE THREAD

**Issue by Garrarop** [PikaMug/Quests#770]
![image](https://user-images.githubusercontent.com/30799098/56181861-c3e19080-5fe5-11e9-92bb-a6111169cdcd.png)
Once again, I'm sorry for my bad English.
on kill mobs, if the mob is an enderman the name is not displayed correctly.

And I have another question. 

How can I implement the "parties" plugin?
in your wiki this plugin appears ( https://github.com/PikaMug/Quests/wiki/Beginner-‐-Dependencies ), but it does not say how to use it correctly and in the wiki of that plugin it does not have data about quests.

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/724/ once it's available

Just drop the Parties jar into your server as usual and Quests will take care of the reset. Whenever a member of a party completes a quest, it will auto-complete that quest for other party members which have also taken that quest. There is currently a request to use a progress system instead, feel free to leave input in #679 if desired.
