### ISSUE TITLE
People can take items from gui

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [PikaMug/Quests#771]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.6
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Hi, ive problem with quests on 1.13.2 with gui. If you click on item in gui you take the item and then you could take it to inventory :/

https://pastebin.com/4YVTN3dD
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/gXiEvNtv

**Comment by PikaMug** [comment]
I wasn't able to replicate this, but the error should now be caught in a way that will allow the inventory to close before any items can be taken.

Use http://ci.ac3-servers.eu/job/Quests/730/ once it's available

**Comment by Johannes173** [comment]
This happend for me one 1.14.4 too. I have 2 quests NPC's. One I can pick items from the GUI and one I can't

**Comment by PikaMug** [comment]
@Johannes173 Please open a new ticket including your Quests version and a copy of the problematic quest.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
