### ISSUE TITLE
Quest with multiple wood types in the same stage.  The count for all types except those with 0 data value are lost when logging out and back in.

### ISSUE THREAD

**Issue by Klawdek** [PikaMug/Quests#772]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.5-b717
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I have a quest with all 6 wood types in one stage.  When player logs off and back on again the count for all wood types except Oak and Acacia goes to 0.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/fbCgKzED
![Screenshot (7925)](https://user-images.githubusercontent.com/45950944/56238886-3178d580-6055-11e9-87cc-8706b81e5622.png)
![Screenshot (7926)](https://user-images.githubusercontent.com/45950944/56238902-39387a00-6055-11e9-9d0d-67591b487034.png)
The first picture show the count before logging off and then back on. The second show the count after logging back on.

**Comment by PikaMug** [comment]
Thanks for the report. Could you check whether this is a placebo? Like after logging out/in, are you still able to complete the quest after getting the remaining wood?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Klawdek** [comment]
I just did the following experiment.  I did the quest and I broke 100 of all wood types except dark oak where I broke only 98 (out of the 100 to complete).  This leaves only 2 dark oak blocks needed to complete the quest.  I then logged out and back in again.  I then broke 2 dark oak logs and the quest did NOT complete. I broke a few more dark oak logs to be sure and the quest did not complete.

**Comment by Klawdek** [comment]
The problem still exists with the latest version 3.6.6-b734.  I also experimented again to confirm it is not just a display issue it is really loosing the count.

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/742/
