### ISSUE TITLE
Quests editor bugging out randomly while editing quests 

### ISSUE THREAD

**Issue by t0xic1** [PikaMug/Quests#773]
Console error : 18.04 17:44:43 [Server] WARN [Quests] Plugin Quests v3.6.5-b717 generated an exception whilst handling conversation input
18.04 17:44:43 [Server] INFO java.lang.NullPointerException: null
18.04 17:44:43 [Server] INFO at me.blackvein.quests.prompts.ItemsPrompt.getPromptText(ItemsPrompt.java:73) ~[Quests-3.6.5.jar:?]
18.04 17:44:43 [Server] INFO at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:236) ~[spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1177) [spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection$2.run(PlayerConnection.java:1471) [spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:909) [spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-51d62de]
18.04 17:44:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

Quest version : 3.6.5-b717

To re-create this issue make a new quest named example and set a new stage, go to the items option and after that this issue appears.

**Comment by PikaMug** [comment]
Does this still occur on the latest dev build? I've been unable to replicate.

**Comment by Klawdek** [comment]
The problem still exists with the latest version 3.6.6-b734

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
