### ISSUE TITLE
Quests journal able to work between servers

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#774]
I'm not sure if it's an idea, or a bug xD

**What does your feature do?**
The /quests journal should work both on server 1 and 2 (3, 4 5 etc etc) without having 1 journal per server, but only 1 that display all the taken quests of the server (where the journal is opened)

**How would people use it?**

Just having 1 journal for the whole server-system, instead of 1 journal working per server and 2/3 journal bugged non removable in their inventory
Servers that are using Bungeecord (Just as me) need this so much. 
I have 3 worlds of quests, every worlds is a whole server, so players have 3 journal, non removable, 2 aren't working and many of the new players don't understand why their journal isn't working while they change the world ... And it take many places in the inventory for nothing

So:
Could you make a journal, working in every server, without having to change the journal each time you change a server?
(1 journal could work on 7/8 different servers)

Have a nice day! =)

**Comment by PikaMug** [comment]
This is essentially a request for database support, see #312
