### ISSUE TITLE
Bug quests 3.4.5 citizens

### ISSUE THREAD

**Issue by TwerkRekt** [PikaMug/Quests#775]
hi sorry for my bad english im french

Version server : 1.12.2
Version quests : 3.4.5

Problem: Citizens are not downloading
No error in console

https://pastebin.com/6JEK9h39

**Comment by PikaMug** [comment]
Thanks for the report. What is your Citizens version?

**Comment by TwerkRekt** [comment]
2.0.24 (MC 1.10-1.13.2)
--

**Comment by PikaMug** [comment]
Thank you. It seems this issue is only with that particular version of Quests. Since we don't backport, I've confirmed that updating to the latest version resolves the issue.

Download the latest version of Quests from https://www.spigotmc.org/resources/quests.3711/update?update=271570
