### ISSUE TITLE
quests can't be quit because of colors or other symbols

### ISSUE THREAD

**Issue by andinis** [PikaMug/Quests#776]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.6-b725 (but this issue has been since 3.6.0) Server: Spigot 1.12.2 R01-Snapshot

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
if you have quests that have any colors or any special characters in the name cant be quit not even from console you always get "Quest not found" message

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/XsCk0kAN

**Comment by PikaMug** [comment]
It's my understanding that color codes aren't supposed to be used in quest names to begin with, but I'll take a closer look soon.

**Comment by andinis** [comment]
it did work before when the plugin also autofilled the names when you quit them, so yeah i didn't see a reason why not to use color codes

**Comment by PikaMug** [comment]
Fixed in 2360f68edaaebe6e6e9b001d642f0ddf40ef19d9

The dev build server is down, so I'm afraid you'll have to wait until the release of Quests 3.7.2
