### ISSUE TITLE
Citizen 2 requirement

### ISSUE THREAD

**Issue by elektrikliadam** [PikaMug/Quests#779]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.5
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/raw/hUcyWJ2d

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
When player was slain by another player even if player isn't in the quest , plugin gives this error.

**Comment by PikaMug** [comment]
Just to be sure, do you have Citizens installed? And if so, what version?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP. Possible duplicate of #775
