### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by Darkweasam** [PikaMug/Quests#781]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests version 3.6.5-b717
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://hastebin.com/ayecoquqeh.sql
https://hastebin.com/uxebaxopus.sql
Two errors, the second is literally spamming my console 24/7
I have no idea whats the problem or how to replicate it.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
This is an issue with the MythicMobsQuestsModule by BerndiVader. Seek help from its developer here: https://github.com/BerndiVader/MythicMobsQuestsModule

**Comment by Darkweasam** [comment]
https://hastebin.com/ewusopowas.sql

I get an other kind of Quests error aswell
