### ISSUE TITLE
Problem with worldguard in the src

### ISSUE THREAD

**Issue by NetzkroneHD** [PikaMug/Quests#782]
the boolean in the Quest.class isInRegion does not work even though i imported the worldguard plugin in my buildpath.

https://pastebin.com/wCpw8V0Y

`	private boolean isInRegion(Player player) {
		if (region == null) {
			return true;
		} else {
			ApplicableRegionSet ars = 	plugin.getDependencies().getWorldGuardApi().getRegionManager(player.getWorld()).getApplicableRegions(player.getLocation());
			Iterator<ProtectedRegion> i = ars.iterator();
			while (i.hasNext()) {
				ProtectedRegion pr = i.next();
				if (pr.getId().equalsIgnoreCase(region)) {
					return true;
				}
			}
			return false;
		}
	}`

this is the problem `plugin.getDependencies().getWorldGuardApi().getRegionManager(player.getWorld()).getApplicable`

The type com.sk89q.worldedit.math.BlockVector3 cannot be resolved. It is indirectly referenced from required .class files

**Comment by PikaMug** [comment]
It should work just fine. BlockVector3 is present in WorldGuard 7 (not 5 or 6), so chances are your IDE didn't/couldn't import WG7 correctly. Update the project or just add a WG7 jar to your build path.
