### ISSUE TITLE
Shift-click crafting not tracking all crafted items

### ISSUE THREAD

**Issue by MercerK** [PikaMug/Quests#788]
**What is your Quests version / build number (do _not_ say "latest")?**
3.6.5

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

I have a quest with the following:
```
          items-to-craft:
          - name-BREAD:amount-5
          - name-OAK_BOAT:amount-1
          - name-IRON_SWORD:amount-1
          - name-LEATHER_BOOTS:amount-1
          - name-LEATHER_CHESTPLATE:amount-1
          - name-LEATHER_LEGGINGS:amount-1
          - name-LEATHER_HELMET:amount-1
```

When you craft multiple bread and shift-click the result (to get 5 bread in a single click), it only tracks that "one craft" and not the "newly 5 crafted items" in the quest journal.  

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/HKNYH4r9

**Comment by PikaMug** [comment]
This is actually an issue with Spigot itself https://hub.spigotmc.org/jira/browse/SPIGOT-1009

Workaround exist, I'll look into using one of them soon.

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/740/ once it's available

**Comment by MercerK** [comment]
> Use http://ci.ac3-servers.eu/job/Quests/740/ once it's available

Thank you! Updated, tested, and it works.
