### ISSUE TITLE
questadmin stage info player?

### ISSUE THREAD

**Issue by Garrarop** [PikaMug/Quests#790]
Sometimes the players get lost in the Quests and I have to ask them to tell me what they say in "/quest". It can be easier if I can see this with a command like the "/questadmin stats player"
-----Quest name----
Stage number - Player nick
Objective (Progress)

**Comment by PikaMug** [comment]
Done as of c2bccb8fd6ead5f1a6a2909a3de22d83c0810912 - plugin will now show the player's current stage number next to the quest.

![stage](https://user-images.githubusercontent.com/2267126/57586613-0f446d00-74c6-11e9-9b0a-b56894ed3cc1.png)

You may download the build here once available - http://ci.ac3-servers.eu/job/Quests/738/
