### ISSUE TITLE
When using an event to give a signed book with multiple pages errors out 

### ISSUE THREAD

**Issue by Nosneross** [PikaMug/Quests#791]
**What is your Quests version / build number (do _not_ say "latest")?**
1.13.2 
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**So I cannot for the life of me figure out why I cannot use a book with multiple pages apawn event start it just says there was an error with the item and to contact admin idk why. 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
yes

**Comment by PikaMug** [comment]
Thanks for the report. Please provide the example quest from quests.yml using Pastebin or Hastebin

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.

**Comment by PikaMug** [comment]
Potentially a duplicate of #750
