### ISSUE TITLE
Feature Request: MCmmo Overhaul support

### ISSUE THREAD

**Issue by Nericu** [PikaMug/Quests#794]
**Same things as the MCmmo classic but with overhaul**

**Skill requirements for quest, Skill Level requirements for quest, Skill/ability rewards for quests**

**Comment by PikaMug** [comment]
Supporting two version of the same plugin is difficult (though not impossible, i.e. WorldGuard 6/7). Will update once I have a plan on how to approach this.

**Comment by RednedEpic** [comment]
Would like to see this implemented too.

> Supporting two version of the same plugin is difficult (though not impossible, i.e. WorldGuard 6/7). Will update once I have a plan on how to approach this.

Just break it into two different modules, similar to how you have it with the ParticleProviders.

**Comment by Nericu** [comment]
I think that is more so the plan to split it in too but it would require building an entire module for MCoverhaul due to the amount of changes the dev made to that plugin. Def gonna take a good while to get done I imagine but glad to hear more then just I would like to see it.

**Comment by RednedEpic** [comment]
> I think that is more so the plan to split it in too but it would require building an entire module for MCoverhaul due to the amount of changes the dev made to that plugin. Def gonna take a good while to get done I imagine but glad to hear more then just I would like to see it.

I've successfully compiled a version that works with the overhaul version. Tested and can confirm it works without bugs. It does not have support for the original (classic) version. It's on my server GitHub organization.

**Comment by Nericu** [comment]
Do you mean you have the 3.7.0 quests working with MCmmo overhaul? I was trying to do it so that you need to have a certain level in a skill to do a quests but cant until it is support.

**Comment by RednedEpic** [comment]
> Do you mean you have the 3.7.0 quests working with MCmmo overhaul? I was trying to do it so that you need to have a certain level in a skill to do a quests but cant until it is support.

Yep. Just take a look at the GitHub page for my server and go to the overhaul branch.

**Comment by Dynamite99** [comment]
I would love to see this. The classic is not as supported and the current mcmmo overhaul does not work with quests in 1.14.3

**Comment by PikaMug** [comment]
Quests has recently made an effort to use only free plugins as dependencies, hence moving GPS support to a module. To wit, the plan is now to create a (free) module for the premium mcMMO Overhaul. This will satisfy this issue while also maintaining support for mcMMO Classic, in-line with the project’s goals.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Dynamite99** [comment]
This would be awesome. Is there an estimate or is this just an idea for now?

**Comment by PikaMug** [comment]
Module is now available at https://www.spigotmc.org/resources/mcmmo-overhaul-quests-module.69548/
