### ISSUE TITLE
Quests.yml not being read with spigot 1.14.1

### ISSUE THREAD

**Issue by Nericu** [PikaMug/Quests#795]
**Quests 3.6.7 and 3.6.8-dev, Latest Spigot build tools version 1.14.1**

**Server starts up with spigot 1.14.1 and there are no quests listed there. When I check the quests.yml file all custom quests are still listed there. Also it resets all player quest info as well (quests completed and being worked on) Only thing that sticks is the quest points it seems**

**Comment by PikaMug** [comment]
Just tried this with my own file and everything worked fine. Could you share your pre-upgrade quests.yml so I could test it? Upload or use Pastebin, please.

**Comment by Nericu** [comment]
quests.yml
https://pastebin.com/eEZkTed9

**Comment by Nericu** [comment]
Seems it was due to citizens being outdated, however it did wipe all player quest data that they were currently doing....

**Comment by PikaMug** [comment]
Yes, if a quest NPC isn't present at startup, the quest won't load. This is noted in the console. So if Citizens isn't working, none of the quests containing NPCs will appear.

Glad you found the issue!
