### ISSUE TITLE
Quest Groupings

### ISSUE THREAD

**Issue by Nericu** [PikaMug/Quests#796]
**The ability to group quests together in a named group ex-"Quest Group A"**

**Could make it so that you can only have one active quests from that group at a time. Would work well for "daily or weekly" quests that you don't want users to stack up together**

**Comment by PikaMug** [comment]
Thanks for the suggestion. One can just use the Planner to set the same start/end date & time for the quests you want to have active together. As for only being able to take one at a time, see #454

**Comment by Nericu** [comment]
I wouldnt put this with that one, this one would be more so for lets say 4 quests: 
Group A Quests:
Kill 10 creepers
Kill 10 skeletons
Kill 10 zombies
Kill 10 spiders

For this I only want them to lets say only be able go choose a max of 2 of these and when they complete lets say 1 of them a 24hr cooldown starts for that one and they can choose one of the other 2 but they can only have a max of 2 of these 4 quests at a time on them.

That would be the ruling for This group but still allow them to choose quests from another group following different rulings.

Hope that makes more sense

**Comment by Nericu** [comment]
Can this still be looked into? I posted a comment before this one thinking that the ticket you submitted wasent similar to what I am requesting.

**Comment by PikaMug** [comment]
Sorry for the late reply. What you’re asking for in your second comment is slightly different from the original request in that being able to take 2 at a time isn’t possible. However, only being able take 1 at a time is possible using quest blocks, as shown in #454


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
