### ISSUE TITLE
 Failed loading lang files for en-US because they were not found. Using default en-US

### ISSUE THREAD

**Issue by asdfgh456** [PikaMug/Quests#797]
I have added everyone permission, but this is how I do it.

![擷取](https://user-images.githubusercontent.com/3489874/57973489-fb27d080-79db-11e9-875b-f07530080489.PNG)
![a](https://user-images.githubusercontent.com/3489874/57973589-c3ba2380-79dd-11e9-8595-6d8b801a5469.PNG)

**Comment by PikaMug** [comment]
First, open
![button](https://user-images.githubusercontent.com/2267126/58070707-13c4f180-7b68-11e9-9d7c-81ab0eb21c74.png)
and make sure all boxes are ticked.

If that doesn't work, try removing the character from your "Minecraft" folder
![c](https://user-images.githubusercontent.com/2267126/58070812-7ae2a600-7b68-11e9-83fb-897adcb08c7d.png)
