### ISSUE TITLE
Dynmap-Quests not working properly (1.13.2)

### ISSUE THREAD

**Issue by andinis** [PikaMug/Quests#798]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests Version 3.6.8-B747
Citizens v2.0.24-SNAPSHOT (build 1636)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
The markers for the NPCs are all messed up, and 99% of the markers are on the same spot not where the npcs are. not showing any errors but I have screenshot of dynmap: http://prntscr.com/nqz3u1

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report! Would you be able to provide your Citizens saves.yml file via Pastebin or Hastebin? If you'd prefer not to share it here, let me know your Spigot or Discord username so that I can reach you directly.

**Comment by andinis** [comment]
the whole saves file doesn't fit in a pastebin, you can message me on discord andinis#1709 or I can copy only a part of the saves file

**Comment by PikaMug** [comment]
Looking at the part you've provided, it appears most NPCs are within 50 blocks of each other:

`NPC 71      location:
        world: FullWorldTest5
        x: '17572.4729'
        y: '83.0'
        z: '9686.5691'`
`NPC 74      location:
        world: FullWorldTest5
        x: '17567.9431'
        y: '97.5'
        z: '9726.7453'`
`NPC 73      location:
        world: FullWorldTest5
        x: '17562.3466'
        y: '87.5'
        z: '9700.5455'`
`NPC 72      location:
        world: FullWorldTest5
        x: '17555.0027'
        y: '82.0'
        z: '9689.2132'`
`NPC 70      location:
        world: FullWorldTest5
        x: '17565.1065'
        y: '82.0'
        z: '9680.7075'`

This would support the map you provided being accurate. Could it be that you're expecting the markers to move with the NPCs as they walk away from their home location? This isn't currently a feature, but I could look into adding it if that's the issue.

**Comment by andinis** [comment]
I have 66k npcs, all quest npcs dont move arround and are on their right spot, the markers are still placed on one place. The npcs that quests quests or have anything to do with quests dont move and arent supposed to move if you would message me on discord I could send you the whole saves and quest file and check yourself.

**Comment by PikaMug** [comment]
Alright. Seems like you may have messages disabled:

![discord](https://user-images.githubusercontent.com/2267126/58121704-02b2c980-7bd6-11e9-9f67-bc4e78c8708f.png)

**Comment by andinis** [comment]
uhm it should be possible if we are on the same discord server and I'm in the Quests discord. I'm sure people can message me because I get messages from alot of people im not friended with. I sent you a friendrequest

**Comment by PikaMug** [comment]
Could be my settings, since I haven't got a request from you. Just sent one your way, let me know whether you get it :)

**Comment by PikaMug** [comment]
Resolved via Discord. Fix is contained within DynmapQuests v1.2.
