### ISSUE TITLE
Server Restarted when i tried to /questadmin

### ISSUE THREAD

**Issue by andinis** [PikaMug/Quests#799]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests Version 3.6.8-B747
paper 1.13.2 build 626

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When i tried to reset a players stats with the command "/questadmin reset", I got this error https://pastebin.com/mAUMWEUn and the server restarted. This has happend a couple of times inconsistantly don't know how to replicate it.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
I could send the quests.yml on discord if needed (andinis#1709)

**Comment by PikaMug** [comment]
Resolved in http://ci.ac3-servers.eu/job/Quests/747/

Please note that recent builds of Quests contain major changes, so download at your own risk or wait until the next Spigot release.
