### ISSUE TITLE
Users can't accept the Quests.

### ISSUE THREAD

**Issue by GermanY1337** [PikaMug/Quests#800]
**What is your Quests version / build number (do _not_ say "latest")?**
Version : 3.6.8 

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When i try to Accept the Quest it works. But if other users try it i get an error in my Console : https://pastebin.com/8pwVCFH0

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/Qp1HvJL5
I'm using Citizens for the NPC's and LuckPerms

**Comment by PikaMug** [comment]
Give http://ci.ac3-servers.eu/job/Quests/748/ a try and let me know what you get for console output.

Please note that recent builds of Quests contain major changes, so make sure to backup any important Quests files before attempting.

**Comment by GermanY1337** [comment]
When i click on the link i get an Error 404 http://prntscr.com/nthkh0

**Comment by PikaMug** [comment]
It appears the Jenkins server is offline. I'm afraid I'll have to ask you to wait until the next release on Spigot (in a few days).

**Comment by GermanY1337** [comment]
It looks like that the error from the plugin is gone. I reinstalled the Server yesterday with the latest Spigot version and now everything is running.
