### ISSUE TITLE
Delivery Quest bug, featuring custom named/lore on items.

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#802]
**What is your Quests version / build number (do _not_ say "latest")?**
Version 3.6.8-b747

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
A delivery quest, to multiple npcs, having to deliver custom items; such as coupons, custom lores and names. Allows players to give all custom items to any npc that wants even just 1 type of custom item.
Example:
Npc 1 wants 1 Custom Cookie
Npc 2 wants 2 Custom Carrots
Npc 3 wants 3 Vanilla Golden Apples
Npc 4 wants 4 Custom Potato's
Then Npc 1, 2 or 4 would accept the delivery that was supposed to be given to either 1, 2 or 4.

However, Npc's 1, 2 and 4 will not accept the items that is supposed to be given to npc 3.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/5ASpf3zr <--- Not sure if this helps though.

**Comment by PikaMug** [comment]
Thanks for your report. I’m confused about what the bug is? NPCs are supposed to only accept the item they were assigned. In other words, this is expected behavior.

Were you trying to request a new feature that would permit any item?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Technodate** [comment]
The bug is, that NPCs also accept items that have been assigned to other npc.

**Comment by Technodate** [comment]
And no, I wasn't trying to request that.

**Comment by Technodate** [comment]
Found something else which might have to do with it;
When npc request the following:
NPC A wants 4 Apples
NPC B wants 4 Apples,

You only have to give out a total of 4 apples to one npc, and that also completes the delivery for the other npc.

**Comment by PikaMug** [comment]
I'm able to replicate the issue. Giving an Apple to any NPC involved in that stage of the quest works, even if it shouldn't. The temporary solution is to split the delivery objectives into separate stages, but I don't anticipate this will be hard to fix. Thanks for your patience.
