### ISSUE TITLE
I can´t take my quest

### ISSUE THREAD

**Issue by Skyfighter1** [PikaMug/Quests#805]
**What is your Quests version / build number (do _not_ say "latest")?**
My quests version is 3.6.8.

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I get this Error: https://pastebin.com/FiEHpMY6

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
My quests.yml: https://pastebin.com/bCYZuxKh

**Comment by GermanY1337** [comment]
Are you running Craftbukkit or Spigot on your server ? If you are running Craftbukkit switch to Spigot  there it should be running. You just have to switch the Server jar.

**Comment by PikaMug** [comment]
No, this error is caused by an incompatible or missing WorldGuard. Quests supports both CraftBukkit and Spigot.

@Skyfighter1 What version of WorldGuard are you running?

**Comment by Skyfighter1** [comment]
I use spigot and that WG version :

worldguard-legacy-7.0.0-beta-03 (3).jar

**Comment by PikaMug** [comment]
@Skyfighter1 Try downgrading to WG [Beta 2](https://dev.bukkit.org/projects/worldguard/files/2642132). If that doesn't work, upgrade to the current [Release](https://dev.bukkit.org/projects/worldguard/files/2710977) and provide the error from that build.
