### ISSUE TITLE
Nextstage upon join

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#810]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.8-b747

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

The problem is that when users have started a quest, no matter how long, they sometimes get forced to the next stage, without completing the previous one.

I have no clue why this is done, so I won't be able to tell you how to replicate it.
Basically what happens is;
1. Player accepts a quest
2. Player leaves the server and rejoins
3. Upon join the player is ALWAYS forced to the next stage.
3.5 This also counts for the last stage, meaning that the player can finish a quest without completing it.

No console errors show up, nor does an execution of /questadmin nextstage

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

It's not applicable due to it being done for multiple quests.

**Comment by Technodate** [comment]
I'd love to request a hot fix for this one x.x

**Comment by PikaMug** [comment]
Please do not bump tickets within 24 hours of last comment.

Have you confirmed that this issue still occurs in Quests 3.7.0?

**Comment by Technodate** [comment]
The issue still occurs in Quests 3.7.0

However I've found out that it doesn't do it for every quest.

**Comment by Technodate** [comment]
This issue does not occur for every quest/stage, but I also noticed that it forces a next stage upon join if a player has custom26 stage 1 as the current set stage. upon join it will force them over to stage 2

**Comment by PikaMug** [comment]
I had different results just now using your custom26 quest. No matter what I tried, I couldn't get stage 1 to advance to stage 2 by relogging.

However, I was able to get stage 2 -> 3 and also stage stage 4 -> 5. From what I can tell, it only seems to happen if the current stage before quitting has a delay (so stages 2 and 4). Hope to find a solution soon.
