### ISSUE TITLE
Delivery 

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#813]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.8-b747

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

These might be considered 2 different problems.

#1 The player cannot deliver the items to the npc
#2 The player only has to deliver the items to 1 npc

The problem happens for the following;

#1 
If a player has accepted 2 different quests, both needing the same items for different npcs
then the player can only give it to the npc, assigned to the quest which is first in the quests.yml list
quest 1; give 1 apple to B
quest 2; give 1 apple to A
Then they can only give their apple to B before they can give 1 to A. Because quest 1 is on the list before quest 2.

#2 
If the player has to complete a stage of a quest, where they have to give 1 item type to multiple npcs, they only have to give it to 1 of those npcs in order to complete it for both;
give 1 apple to C
give 1 apple to D
Will make them only have to give 1 apple to either C or D, in order to complete the whole stage.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

This can be done at any time with any quest, and was also a problem from a version 3 years ago. (don't exactly remember which one possibly 2.5.6)

**Comment by PikaMug** [comment]
How is this different than #802?

**Comment by Technodate** [comment]
#802 states that 1 npc with a designated item can accept completely different items that are assigned to other npcs within the same quest stage.

**Comment by PikaMug** [comment]
Although technically a different bug, this should be resolved by the fix for #802
