### ISSUE TITLE
Ticket #799 not fixed and Start-events don't work anymore

### ISSUE THREAD

**Issue by andinis** [PikaMug/Quests#818]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.7.0
Paper 1.3.2
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?
Sometimes when I perform an questadmin command, the server sends me a message that an internal issue occured and restarts the server same as i described in ticket #799 and now since the update, I had to change all my quests to "finish-event/action" because "start-event/action" doesn't trigger and all tp events/actions were gone in the file I had to remake all of them again. https://pastebin.com/xritX3Gw

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Closed accidentally. Reopening.
