### ISSUE TITLE
Quests Completed list deleted for no reason

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#819]
**What is your Quests version / build number (do _not_ say "latest")?**

3.7.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

No console errors,
The problem is that randomly, for no reason at all, my completed quests list got cleared.
Not just mine, but several lists from various players.
I cannot tell you how to replicate it, as it doesn't always happen with a reason.

*Sometimes* when players get muted using Litebans, their quests completed list gets cleared.
but that doesn't always happen.
Though I did not get muted, nor did anyone clear my list by editing the data files or using commands. But for some reason, my list still got cleared.

It sucks that I can't tell you how to replicate it, but I just thought that I'd report this.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
All quests completed got cleared.

**Comment by PikaMug** [comment]
Cannot duplicate. Please give Quests 3.7.1 a try, which was just released on Spigot, and report back if you continue to experience this issue.
