### ISSUE TITLE
Smelting quest failing

### ISSUE THREAD

**Issue by mmuziek** [PikaMug/Quests#822]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
i created a smeling quest smelt 4 times 64 Sand to glass
(marked as smelt sand)
strange enough it did not detect smelting.
could it be that im using epic furnaces? or ? 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/DP3unueR

**Comment by PikaMug** [comment]
I believe you want to specify the end product. So it’d be Glass, not Sand.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mmuziek** [comment]
Tried that no change

**Comment by PikaMug** [comment]
Seems to be working for me, using Glass.

![smelt](https://user-images.githubusercontent.com/2267126/59154195-f5516800-8a3a-11e9-9e94-c278d960a9d5.png)

Try removing EpicFurnaces temporarily and see if that resolves it.

**Comment by Nericu** [comment]
I am currently having this issue as well but with ores/ignots not glass. I have tried setting it to BOTH the ore and the ignot as the product but neither work. I have also tried in both the blast furnace and the regular furnace with no luck either.

**Comment by PikaMug** [comment]
@Nericu Your situation is also working just fine for me. Used an Iron Ingot for the smelt objective.

![iron](https://user-images.githubusercontent.com/2267126/59971362-b6e29f80-9548-11e9-996e-e36e5e024749.png)

At this point, I'd need to see your quest from quests.yml to continue assistance. Feel free to make your own ticket.
