### ISSUE TITLE
locationReached Quests won't work

### ISSUE THREAD

**Issue by SchattenritterX** [PikaMug/Quests#825]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Actually I don't really know to replicate that. But I can give you the Console ERROR.

https://pastebin.com/f8Cpx4bm

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/ML0f9wgy

**Comment by PikaMug** [comment]
I wasn't able to replicate this, so similar to #646 I've pushed a workaround that should patch the issue until a proper solution is found. Since the Jenkins server is down, look forward to this commit in Quests 3.7.2
