### ISSUE TITLE
How to automatically set quest on first join

### ISSUE THREAD

**Issue by nkuczm** [PikaMug/Quests#826]
I would like if when a player first joins the server or even when they create an island to automatically start a certain quest. I'd want this to be shown on the scoreboard and then once that quest is completed, it automatically starts the next one and that is thus shown on the board. Is this possible to do currently? and if so how?

**Comment by PikaMug** [comment]
This is something you would employ the use of other plugins to do. There are plenty of plugins out there (like [this one](https://www.spigotmc.org/resources/first-join-commands.16188/)) that will run a command on first join. You could either have the player execute a _/quests take_ command, or have the server execute a _/questadmin give_ command.

As for the island, find a plugin that runs the command when they enter the island world or region. Use something like Featherboard or any scoareboard plugin that supports PlacerholderAPI then keep an eye on #709

**Comment by nkuczm** [comment]
So if I wanted it to go in a certain order I would just have the reward as a command?
Also, if I wanted to show the name of the quest in the scoreboard is there a placeholder for that?

**Comment by PikaMug** [comment]
If by “certain order” you mean force the player to take quests back-to-back, yes you could do it that way. Denizen scripts are another option. 

There will be a placeholder for that, yes, but it hasn’t been added yet. So keep an eye on the ticket I linked.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
