### ISSUE TITLE
Player name on message

### ISSUE THREAD

**Issue by Garrarop** [PikaMug/Quests#827]
![quest1](https://user-images.githubusercontent.com/30799098/59900040-48c59d80-93cd-11e9-882f-794ebd8cb381.PNG)
![quest2](https://user-images.githubusercontent.com/30799098/59900042-48c59d80-93cd-11e9-9250-c054792ec0fb.PNG)

**Comment by PikaMug** [comment]
Not a native option at this time. Use PlaceholderAPI accomplish this.
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#placeholderapi
