### ISSUE TITLE
Quest Journal from /Quests Journal command stuck in inventory slot

### ISSUE THREAD

**Issue by BakuretsuLa** [PikaMug/Quests#828]
I used the command /quests journal while my inventory slots were all filled and it was placed in my armor slot and wasn't registered to my username so it's now stuck there and i can't seem to get rid of it and inventory clearing commands don't work either.

**Comment by PikaMug** [comment]
Confirmed. Working on a solution.

For now, if you have EssentialsX, run `/clear <player> *` to wipe the entire inventory _including_ armor slots.

**Comment by PikaMug** [comment]
The next release of Quests will resolve the armor slot issue. It will also remove duplicates of the Quests Journal when using _/quests journal_ to put away the book.
