### ISSUE TITLE
Quests planting issue

### ISSUE THREAD

**Issue by PirateKalypso** [PikaMug/Quests#829]
Quests version 3.7.2

Made planting quests and having some issues getting them to function properly. 
1. Seems to only work when done in order, however crafting comes after placing. So the first crafted hoe won’t work until all things are planted. 

2. I will complete tasks on said quest and as I progress, previous progress goes down. So if I’ve already completed wheat, it will deduct even though I don’t break any. 
![D97C6D05-D250-4026-9DFF-175F108E3C76](https://user-images.githubusercontent.com/52140445/59983164-3c6a5c00-95ea-11e9-8c8a-cd749eae6117.jpeg)

3. I can’t seem to get carrots and potatoes to count. I will plant them and they don’t count. We need to figure out what the id is for these objects to create the quest correctly or if these objects aren’t supported.  

![6242BFD3-A39B-4057-9CB0-DE9154CCF365](https://user-images.githubusercontent.com/52140445/59983341-63299200-95ec-11e9-9dca-6ae8038ed63e.jpeg)

**Comment by PikaMug** [comment]
Would you please provide the relevant quest from your quests.yml (using Pastebin or Hastebin)? In your seconds photo, I see the plugin refers to the item as "Wheat" in stage 1 and "Wheat Seeds" in stage 2, which shouldn't happen, but I can't replicate it.

**Comment by PirateKalypso** [comment]
We changed them, changing the "Block" "Place" requirement from "wheat?seeds" to "wheat" made the quest plugin recognize them being broke.  However we cannot find a different block name to call carrot and potato to make the quest plugin recognize them being placed (planted)

**Comment by PikaMug** [comment]
I think it’s CARROT_ITEM and POTATO_ITEM

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PirateKalypso** [comment]
Awesome thank you
