### ISSUE TITLE
Smelting Quest Not Calulating

### ISSUE THREAD

**Issue by Nericu** [PikaMug/Quests#830]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
We have a quest to smelt 64 gold and iron. However the quest is not tracking the smelting process. I have tried in both a furnace and blast furnace. I have tried setting the quest to just iron ore/gold ore and iron ingot/gold ingot and it doesn't track regardless.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
This is just the smelting quests portion
https://pastebin.com/qqKdL5AY

This is the entire quests.yml
https://pastebin.com/emwGhWQn

**Comment by PikaMug** [comment]
Unable to replicate using the provided quest.

![s1](https://user-images.githubusercontent.com/2267126/60062804-b113c800-96c8-11e9-8a41-d76606400449.png)
![s2](https://user-images.githubusercontent.com/2267126/60062807-b2dd8b80-96c8-11e9-8185-e2c51a3aa782.png)

Note that normal Furnaces were used for testing. Smelting with Blast Furnaces was not tested.

Perhaps you have another plugin blocking Bukkit's smelting event? Try backing up your server, then temporarily removing any plugins which might conflict (such as inventory handlers).
