### ISSUE TITLE
Quest Region/GUI Error

### ISSUE THREAD

**Issue by Kiilo1** [PikaMug/Quests#831]
Quests 3.7.2
Hi, I'm new to using plugins and I'm still getting the hang of using quests. I'm trying to create a quest that's region specific, but upon clicking the gui item to accept it, the gui item acts as a regular inventory item that can be moved around and placed and the quest doesn't accept. The error code from the logs and the quest itself can be found here: https://pastebin.com/38T3fyGx

**Comment by PikaMug** [comment]
Thanks for the report. What’s is your WorldGuard version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kiilo1** [comment]
I have worldguard 7

**Comment by Kiilo1** [comment]
I also have Citizens 2 and have an NPC that hands out quests, the gui item mentioned in the original post is from that inventory menu

**Comment by PikaMug** [comment]
Thanks. Can I get the full version number of WorldGuard, please?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kiilo1** [comment]
7.0.0

**Comment by Kiilo1** [comment]
stable version

**Comment by Kiilo1** [comment]
7.0.0-SNAPSHOT;1914-75bb0ad <- from the server /worldguard version

**Comment by PikaMug** [comment]
It seems recent versions of WorldGuard changed something critical. I'll look into a workaround. In the meantime, consider downgrading to a slightly older version to restore functionality.

**Comment by Kiilo1** [comment]
alrighty, thanks for looking into it.
