### ISSUE TITLE
Can't see "Quest available" particles.

### ISSUE THREAD

**Issue by Subsidie** [PikaMug/Quests#832]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I can't see the Particles above a NPC when a quests is available. I turned the feature on in the config file of the Quests folder but I still can't see them.

I have Particles turned on "All" but still can't see the Particle I set up.

**Comment by PikaMug** [comment]
Thanks for the report. What is your MC server version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Subsidie** [comment]
> Thanks for the report. What is your MC server version?
> 
> Sent with [GitHawk](http://githawk.com)

Spigot 1.12.2

**Comment by PikaMug** [comment]
I'm having trouble creating any fault on my test server. Could you please provide the quest from quests.yml that you're using (via Pastebin or Hastebin)?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
