### ISSUE TITLE
start-action does not run at the start of the stage

### ISSUE THREAD

**Issue by Garrarop** [PikaMug/Quests#834]
The start action is executed at the end of the stage. not in the beginning

**Comment by PikaMug** [comment]
Closing as OP did not follow issue template.

@Garrarop Tested working. Chances are you set the action to trigger following a stage. To trigger it at the beginning of a quest, use the option shown here:

![action](https://user-images.githubusercontent.com/2267126/60317201-ff7ccd00-993b-11e9-8abb-bae5146565c4.png)

**Comment by Garrarop** [comment]
https://pastebin.com/hTX5cB6M

**Comment by PikaMug** [comment]
Looks like I misunderstood - you meant beginning of a stage, not beginning of a quest. Still, you'll have to open a new ticket since you're still missing info from the template (such as your Quests version).
