### ISSUE TITLE
Quest's not showing up with mcmmo rewards

### ISSUE THREAD

**Issue by joguerreiro** [PikaMug/Quests#836]
What is your Quests version / build number (do _not_ say "latest")?
3.7.2
Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?
http://prntscr.com/o7zjlm most of the quests dont show up and it gives that error witch have rewards from mcmmo
Server version: Spigot 1.14.3 http://prntscr.com/o7zlka 
If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?

**Comment by PikaMug** [comment]
Only mcMMO Classic is supported at this time. See #794

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
