### ISSUE TITLE
Initial Quest

### ISSUE THREAD

**Issue by lKhyst** [PikaMug/Quests#837]
**What does your feature do?**
The first time someone login on to the server, get an initial quest to understand the system, a lot of my players have no idea how to get on the server.
Its like an option: Initial Quest?

**How would people use it?**
Because its very usefully to players who dont know the quests system.

**Comment by PikaMug** [comment]
Thanks for your suggestion. It's not within this project's goals to force a quest onto a player based on conditions, as there are already countless ways to accomplish this without a native option in Quests. Here are just a few:

- Use a plugin like [this one](https://www.spigotmc.org/resources/deluxejoin.4846/) to run /questadmin give [player] [quest] on join
- Place a [Command Block](https://bukkit.org/threads/can-the-command-block-work-with-bukkit-commands.121685/) within range which runs the aforementioned command
- Create a [Citizens 2](https://www.spigotmc.org/resources/citizens.13811/) NPC at the spawn location that advertises the quest to the player
- Put up [Command Signs](https://www.spigotmc.org/resources/command-signs.10512/) which runs /questadmin give [player] [quest] when clicked
- Have someone [write a plugin](https://www.spigotmc.org/forums/hiring-developers.55/) or module which accomplishes your task
