### ISSUE TITLE
Quests start/end event bug

### ISSUE THREAD

**Issue by trungbmt** [PikaMug/Quests#838]
Quests version 3.7.3

    stages:
      ordered:
        '1':
          npc-ids-to-talk-to:
          - 4
          start-event: start1
          finish-event: end1
        '2':
          npc-ids-to-talk-to:
          - 4
          start-event: start2
          finish-event: end2

As you can see, there are 4 events: start1, end1, start2, end2
but when you do it, event start1 is executed when receiving quests, after completing stage 1 it will execute end1 and add once start1, after completing stage 2 it will execute end2, not appearing start2 in here.
so start1 appears twice and start2 does not appear once.
Is that a bug?
Sorry for my english

**Comment by KsuKsuKsu** [comment]
I had the same bug
