### ISSUE TITLE
Per World function

### ISSUE THREAD

**Issue by Straiker123** [PikaMug/Quests#839]
**What does your feature do?**
Can enable quests in specified worlds or fully disable for all quests specified worlds for Eg. Creative world
**How would people use it?**
Players can't complete quests in worlds that are disabled for Eg. Creative world

**Comment by PikaMug** [comment]
Thanks for your request.

Although permissions and settings can be used to control which world quests can be _accepted_, you are correct in assuming there is no way to control which world quests can be _completed_ (unless it's NPC-related). I'll look into including supporting this in the future.

**Comment by Castiella** [comment]
I was going to report this too, hopefully it'll be added. :)

**Comment by Cyvros** [comment]
Would love to see even multi-server with bungee using mysql for example?

**Comment by PikaMug** [comment]
Soon to be available in the Conditions Editor, see https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Condition-Editor
