### ISSUE TITLE
Quests Language Phrases Spam

### ISSUE THREAD

**Issue by kaniesha** [PikaMug/Quests#843]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
"There are new language phrases in /lang/en-US/strings_new.yml for the current version! You must transfer them to, or regenerate, strings.yml to remove this warning!" is being spammed in console during restarts and I'm not sure how to make it go away.
https://gist.github.com/kaniesha/ddf8108d446a972dd0adc58253d4b5ce

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
N/A

**Comment by PikaMug** [comment]
The console output explains what you need to do. Update your lang file. If you can't be bothered to copy strings from the file, just delete your /lang folder and let the plugin regenerate it.
