### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MrGametop1** [PikaMug/Quests#844]
**What is your Quests version / build number Quests 3.7.4)?**

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
So it just spams this in the chat:
https://pastebin.com/V9YAHDD7

Second of all it says there are 2 quests
1. Mob Hunter
2. Catch Fish

When i try to take quest 1.

It says complete Stone Miner first, but it is not there.

Quests 3.7.4
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Sounds like you’ve updated from an older version. Stone Miner was a default quest that’s now known as Iron Miner. To fix the issue you’re having, either remove the quest requirement from Mob Hunter or regenerate your quests.yml so it includes the Iron Miner quest.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
