### ISSUE TITLE
Delivering potions to NPC only accepting first potion.

### ISSUE THREAD

**Issue by Shadorunce** [PikaMug/Quests#846]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.0
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No console errors. I'm trying to create a quest that involves either handing in (or even just crafting) one of each potion, or to hand in or craft 100 (or x amount) of potions. It was suggested by "Date" from Discord to use the Deliver to NPC option. 

To add the items I grabbed all the potions from creative move and made them available to just switch to. I selected to Deliver to NPC, Add Item, Use item in hand, done, <switch item>, add item, use item in hand, done, <switch item> and did that for each potion. 

I got through it all, and added the NPC ID 38 times (that's how many potions there are). I got the quest finalized, did /questadmin reload. Accepted the quest, and handing in one of the potions, it accepted the first one, I attempted to give a second potion and it just shakes the potion. No error messages in game or in console. I tried to give a different item that wasn't a potion and it stated that item isn't part of the quest or something like that. I disconnected and reconnected the quest, and it still wouldn't accept the potion so it can't continue.

I'm trying to get this done by the 20th for a special event coming up for us.

I might go ahead and create a new one/copy most of it over and try doing just 1 stage per potion or something and see how well that works.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/GLryhntL

**Comment by PikaMug** [comment]
I’m guessing this is because the code which compares items doesn’t consider Potion Meta (i.e. which effect a potion has). I’ll look into correcting this, but in the meantime having 1 potion per state should certainly work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PikaMug** [comment]
The next Spigot release should resolve this issue (along with a similar issue with Written Books). Note that Potions will only be able to be compared on Minecraft 1.9+ due to certain Bukkit methods not existing prior to that era.
