### ISSUE TITLE
Bug in planner cooldown

### ISSUE THREAD

**Issue by CrashyTop** [PikaMug/Quests#847]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.4, lastest
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Hello, I'm having a problem in the quests planner. Please ask you to do what you do alone after 1 month, that is, 2592000 seconds, the game does not work. When I put it directly into quests.yml, and when a quest says it failed.
http://prntscr.com/oeurks
http://prntscr.com/oeurq8 -> In this image, it shows which mission was started and then failed. But I have not done anything yet.
Aim is to kill players.
Not have erros in console.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/GW75gDTb

**Comment by PikaMug** [comment]
You have an event attached to the quest. This is from your quests.yml:

`    event: Mensal`

Chances are your events.yml contains this event, which fails the quest after a set amount of time. Remove the link through the Quests Editor and it should work fine.
