### ISSUE TITLE
Quest Helper HUD

### ISSUE THREAD

**Issue by codgamerMC** [PikaMug/Quests#848]
**What does your feature do?**
It's like a Questing arrow HUD that helps the player or guides him to the next checkpoint when Talking to NPC quests, in my server 95% of the people can't read Holograms or Signs that say how to use the Quests plugin, how to interact with it or how to start quests even if it specified, if they ever get the quest then they can't read signs or Holograms (For some odd reasons) which guide them to the NPCs, so the suggestion is instead of using these methods to guide them which for normal people it works, how about having a quest helper HUD that guides them to the next check point, it will help out alot on helping these people out!! If there is a similar feature which I did not know about, I would like to know about it, would help people out.

**How would people use it?**
Get a quest and a HUD appears to guide Players to the next checkpoint!!

**Comment by PikaMug** [comment]
Use https://www.spigotmc.org/resources/gps-quests.67835/
