### ISSUE TITLE
Cannot use Mcmmo Reward. Error in console

### ISSUE THREAD

**Issue by SoraShiunin** [PikaMug/Quests#853]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.5
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Cannot select Mcmmo skill, no extra pop ups after typing 1 in mcmmo rewards window.
However, 'cancel' works and redoes the mcmmo rewards window.
![Screenshot_2407](https://user-images.githubusercontent.com/23641964/61419492-be565800-a8fe-11e9-9724-350339b28691.png)
-Create a quest
-Head to reward Section
-Try to add a Mcmmo Reward
-At Mcmmo Reward, trying to select a skill does not work as nothing pops up except error in console

Error:
https://pastebin.com/RBtYStx7

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for your report. What is your mcMMO version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SoraShiunin** [comment]
mcMMO v2.1.88

**Comment by RednedEpic** [comment]
> mcMMO v2.1.88

It appears you're running the overhaul version of mcMMO, which is not supported yet.

**Comment by SoraShiunin** [comment]
Ah. Any plans to add support for it in the (very near) future?

**Comment by PikaMug** [comment]
See #794
