### ISSUE TITLE
I can't using my Kill mythicmobs objective

### ISSUE THREAD

**Issue by O-FLOYER** [PikaMug/Quests#858]
I can't press 9 to done my quest edition
see it on this video
https://www.youtube.com/watch?v=ELRzDoBB5Jc&feature=youtu.be

**Comment by O-FLOYER** [comment]
I'm using the latest version of mythicmobs and quests

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions (missing version number).

Additionally, issues with modules should first be reported the creator of that module; not Quests.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
