### ISSUE TITLE
Commands not working (Quests 3.7.6)

### ISSUE THREAD

**Issue by DynastyCraft** [PikaMug/Quests#862]
Build : Quests 3.7.6

Not a single command seems to be working. No error text ether. Just nothing

Wondering if its because i am on 1.14.4 and this isn't up to date, or the plugin is missing files? 

Edit: Also the server when i go to type to commands. Shows them as commands i can use.
![broken Quests](https://user-images.githubusercontent.com/5089160/61649910-590db880-acaa-11e9-84be-7e0e5db4cbb4.PNG)

**Comment by PikaMug** [comment]
Working just fine for me on 1.14.4 with Quests 3.7.6 installed.

The fact that you're seeing autofill suggestions means the plugin is working. Make sure you have [permissions](https://github.com/PikaMug/Quests/wiki/1-%E2%80%90-Commands-&-Permissions) or are /op

You could also try removing other plugins in-case they conflict.

**Comment by taytay3** [comment]
> You could also try temporarily removing other plugins in-case they conflict.

Hi! I'm an owner of the server me and @DynastyCraft run. I've updated a bunch of the plugins one of which was mystic mobs and since then the plugin is now working. Thanks for your help!
