### ISSUE TITLE
/quests editor - no permission as a server OP

### ISSUE THREAD

**Issue by marvinej** [PikaMug/Quests#869]
I installed Quests-3.7.6 today and even as a server op with full permissions the command "/quests editor" gives me an error that i don't have permission. I also have * permission in my LP perms

Quests-3.7.6

[Thu, 25. Jul 2019 13:59:40 EST INFO] This server is running Paper version git-Paper-146 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[Thu, 25. Jul 2019 13:59:40 EST INFO] Checking version, please wait...
[Thu, 25. Jul 2019 13:59:45 EST INFO] Previous version: git-Paper-136 (MC: 1.14.4)
[Thu, 25. Jul 2019 13:59:45 EST INFO] You are running the latest version

**Comment by PikaMug** [comment]
Being OP should be sufficient ([source](https://github.com/PikaMug/Quests/blob/master/main/src/main/resources/plugin.yml#L91)), but Quests doesn't honor the _*_ permission. It checks for either _quests.editor.*_ or _quests.editor.editor_ so try adding one of those ([source](https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/listeners/CmdExecutor.java#L453)).

More information:
https://github.com/PikaMug/Quests/wiki/1-%E2%80%90-Commands-&-Permissions
