### ISSUE TITLE
org.bukkit.plugin.IllegalPluginAccessException

### ISSUE THREAD

**Issue by LK520** [PikaMug/Quests#870]
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event me.blackvein.quests.events.QuestsEvent. Static getHandlerList method required!

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions. Feel free to provide your Quests version number (do _not_ say "latest") and how to replicate the problem. Also, please supply the full stacktrace if one exists.
