### ISSUE TITLE
Error Loading Quests, ScriptEntryData

### ISSUE THREAD

**Issue by sameethan1** [PikaMug/Quests#876]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-v3.7.7-b12
Denizen-1.06-b1676-REL
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Quests won't load
https://pastebin.com/d405EnkU
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Use https://ci.codemc.org/job/PikaMug/job/Quests/13/
