### ISSUE TITLE
Support PlaceholderAPI in command rewards

### ISSUE THREAD

**Issue by SXRWahrheit** [PikaMug/Quests#878]
**What does your feature do?**

Add support for PAPI placeholders in command rewards

**How would people use it?**

Standard PAPI syntax. Lots of people in the Discord ask about placeholders for commands, it would be nice to just be able to tell them anything from PAPI works

https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/Quest.java#L452

**Comment by PikaMug** [comment]
Use https://ci.codemc.org/job/PikaMug/job/Quests/14/
