### ISSUE TITLE
Crafting items Chest

### ISSUE THREAD

**Issue by CrashyTop** [PikaMug/Quests#879]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.6
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I will write otherwise
I created the quest
The goal is to craft 15 chests
But it does not work
It does not work in the game, I make a good and does not count as manufactured.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/EyDYC15Q

**Comment by PikaMug** [comment]
Your quest works fine for me. Make sure you've crafted all 15 and that no other plugins are canceling the craft event (if you're unsure, try temporarily removing all plugins except for Quests).

![chest](https://user-images.githubusercontent.com/2267126/62102331-a370d580-b266-11e9-8980-f70c8ec79547.png)
