### ISSUE TITLE
Quests not found

### ISSUE THREAD

**Issue by CrashyTop** [PikaMug/Quests#880]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.7
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Basically it is taking a search that I am caught.

For example, quest name: Example1

/ quests leave example1

but I did not get the quest, ie I have no quest to leave but it appears that left.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
It is not necessary

**Comment by PikaMug** [comment]
Post your startup log. Chances are the plugin failed to load the quest.

**Comment by CrashyTop** [comment]
It is not a mission that is not started, it is a player who can get out of a mission that is not doing it.

**Comment by PikaMug** [comment]
It's now my understanding that your player is able to quit a quest which they have not taken.

However, I'm unable to replicate this. Using _/quests leave example1_ without having taken any quests gives me "You do not currently have any active Quests." If I take a quest first, then the same command gives me "Quest not found."

Could you provide an example quest and screenshots of what you're seeing?

**Comment by CrashyTop** [comment]
Ok. I solved
