### ISSUE TITLE
Fully Grown Wheat

### ISSUE THREAD

**Issue by ghost** [PikaMug/Quests#882]
How can I make a quest require that you break FULLY GROWN wheat rather than just any wheat? At the moment, I have a quest for harvesting 64 wheat, however, people can break non-fully-grown wheat, and it will advance the quest.

**Comment by PikaMug** [comment]
On older versions of Minecraft (pre-1.13) this would be done by setting the durability value, which is a number that determines which state of growth the crop is in. I'm unsure whether this would work on 1.13+ so  I would encourage you to ask this question on the Discord if you have not done so already.

https://discordapp.com/invite/d56CQ6e

**Comment by UnofficialAshton** [comment]
I have already asked on the discord, to which nobody responded to.

**Comment by UnofficialAshton** [comment]
I set the durability value to 7, which is fully grown wheat, but it did not change the fact that people can advance the quest no matter what stage the wheat is in. Is this impossible to do?

**Comment by PikaMug** [comment]
What is your Minecraft version?

On 1.13+ it looks like they've switched to using [Ageable](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/data/Ageable.html) so it's no surprise then that the old way doesn't work. Quests supports Minecraft versions 1.7.9 - 1.14.4 at time of writing, so we typically don't do anything version specific, but I'll keep this open pending further investigation. For now, though, what you're looking to do isn't going to be possible with Quests.

**Comment by UnofficialAshton** [comment]
Ouch, that sucks. Any way this can be added in the future?

**Comment by PikaMug** [comment]
Because of the aforementioned compatibility issues, it's not in the project's best interest to implement Ageable. However, my suggestion for this situation would be to put in an extra stage that requires delivering X amount of Wheat to an NPC. This would hopefully require the player to grow the Wheat to its mature age in order to harvest the item.
