### ISSUE TITLE
Modify Reward Name

### ISSUE THREAD

**Issue by CrashyTop** [PikaMug/Quests#884]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.7
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I do not know how to modify the "'s" to money or coins.
I searched all the lines and didn't figure out how to modify.
I use the pt_BR language
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://github.com/PikaMug/Quests/blob/master/main/src/main/resources/lang/pt-BR/strings.yml

**Comment by PikaMug** [comment]
Looks like the line is `money: "Dinheiro"` near the bottom:
https://github.com/PikaMug/Quests/blob/master/main/src/main/resources/lang/pt-BR/strings.yml#L850

Unless you've made your own modifications, you could always just delete the /lang folder and let Quests regenerate it at startup. Also, remember that you _must_ have [Vault](https://www.spigotmc.org/resources/vault.34315/) installed for money rewards to work properly.
