### ISSUE TITLE
Quest Gui not working 1.14.4

### ISSUE THREAD

**Issue by Ratthew** [PikaMug/Quests#889]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.7
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Hi im new to this plugin and im trying to setup a quest it kinda goes like this, talk to npc with gui pop up. click the quest. kill 35 zombies and 5 creepers, talk to npc to finish. but the problem I have is when you go to the gui to begin its like an infinite item haul you can keep closing and opening the gui to take from im on 1.14.4 how can I fix this

A way to replicate this is by creating a quest such like the one described above and then adding a gui to an npc to start it.

**Comment by PikaMug** [comment]
Thanks for your report. I'm unable to replicate this issue. In my testing, taking the item closes the GUI and does not allow it to be re-opened.

Please try temporarily removing non-essential plugins from your server to make sure nothing is conflicting with Quests. If you still experience this issue, post your quests.yml via Pastebin/Hastebin.

**Comment by Chapata** [comment]
It keeps happening

**Comment by PikaMug** [comment]
Again, please try temporarily removing non-essential plugins from your server to make sure nothing is conflicting with Quests. **If you still experience this issue, post your quests.yml via Pastebin/Hastebin**.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ratthew** [comment]
I was able to recreate the problem. My first attempt i left out extra mobs to kill and made everything extreamly short but somehow it worked... After that my entire plugin flatlined and i had to reinstall. This morning i recreated the quest ive had issues with.

This is what my Quest.yml looks like currently
https://pastebin.com/n1NqJtLF

This is what my Config looks like
https://pastebin.com/DEW6YK4P

I want to remove some plugins but most plugins are tied with my essentials for my server I'm not receiving any error codes either.

**Comment by Ratthew** [comment]
I managed to get an error code to appear

erver thread/ERROR Could not pass event InventoryClickEvent to Quests v3.7.7-b12
01.08 13:37:45 [Server] INFO org.bukkit.event.EventException: null
01.08 13:37:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2133) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:908) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:901) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:818) [spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
01.08 13:37:45 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.managers.RegionManager.getApplicableRegions(Lorg/bukkit/Location;)Lcom/sk89q/worldguard/protection/ApplicableRegionSet;
01.08 13:37:45 [Server] INFO at me.blackvein.quests.listeners.PlayerListener.onInventoryClickEvent(PlayerListener.java:147) ~[?:?]
01.08 13:37:45 [Server] INFO at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source) ~[?:?]
01.08 13:37:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
01.08 13:37:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
01.08 13:37:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot_1.14.4.jar:git-Spigot-1981d55-31adfa7]
01.08 13:37:45 [Server] INFO ... 17 more

**Comment by PikaMug** [comment]
@Ratthew Thanks. What is your WorldGuard version?

**Comment by Ratthew** [comment]
7.0.0

**Comment by PikaMug** [comment]
Beta or release?

For example, there's 7.0.0 and 7.0.0-beta3 on [BukkitDev](https://dev.bukkit.org/projects/worldguard/files)

**Comment by Ratthew** [comment]
I think its release 7.0.0, I see nothing with beta

**Comment by PikaMug** [comment]
@Ratthew Use https://ci.codemc.org/job/PikaMug/job/Quests/18/

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.
