### ISSUE TITLE
Suggestions that player can only view the quest they can accept

### ISSUE THREAD

**Issue by Zaohon** [PikaMug/Quests#893]
**What does your feature do?**
To make a config that set whether players can see the quest that they are not able to accept .
It is about the requirement . If player cant accept the quest because of they are lack of some requirement , they will directly cant see the quest . 

**How would people use it?**
When people are making a server depend of quest that contains many quests , and they want people to accomplish these quests one by one , but dont want players to see the future quest before players have accomplished the previous quest . 

It seems like a config that "show-quest-ignore-requirement" or something like that .

Thanks for your reading !

**Comment by PikaMug** [comment]
Already exists. See the `show-requirements` setting in config.yml

https://github.com/PikaMug/Quests/wiki/2-%E2%80%90-Configuration#configyml
