### ISSUE TITLE
Daily/monthly quests

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#894]
**What does your feature do?**

Add a way to create a 'Daily' quests. but not with a cooldown 24h.
A quest that reset every day at 00h00, for everyone. And you fail the quest if the quest is reset at 00h00 if you had it and not finished.

To create a quest like that, you ''Just'' have to create a 'Fail timer', for example, the quest is always failed at 00h00.
(You also could use the PlaceHolder "Server" to use Date format code)

**How would people use it?**

Servers could have daily quests for players, that scale on the server's date and not on the cooldown of each player.
And each players then, could know that every days, they have their daily quests, and then they don't have to calculate the 24h cooldown of an actual daily quest.

**Does it exist an alternative?**

Yeah, actually i use 4 Plugins, 3 ScoreBoards and 3 Skripts juste to make it works like that, and it's a bit strange when the quest reset but it works ...

**Comment by KsuKsuKsu** [comment]
Yeah! And i want to have some quests every years, for example quests only for Christmas

**Comment by tiradorus** [comment]
I already tried, but you can't make a real cycle of quest, because the 'End date' force you to configure a special day of ending.
What i'm asking here is every day. As planner but with a fail hour (not a fail date)

And why not a "force start" for everyone (With the event "OnJoin" for exemple) if the player don't have the quest... but it fails his quest if he don't have finished it in the day.

**Comment by PikaMug** [comment]
For repeating quest, the end date is just used to determine how long the quest should be available for. For example, a quest that starts at 10:00am and ends at 4:00pm has a window of six hours. If you set a repeat cycle of one day (86400 seconds), the quest will start again at 10:00am the next day and last six hours until 4:00pm.

In other words, the end date is only truly the end if you do _not_ set a repeat cycle.
