### ISSUE TITLE
Quest sent to wrong player when using force take command

### ISSUE THREAD

**Issue by ysy960108** [PikaMug/Quests#895]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-3.7.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Background:
I use "/questadmin give <player> <quest>" in menu plugin to give player quest. 
And in my server there are two player named "bilibili" and "_bilibili9602987", they are two different person.

Here is the bug:
When both player "bilibili" and "_bilibili9602987" are online, the command "/questadmin give bilibili <quest>" sent the quest to player "_bilibili9602987".
Here is the console log (it's not in english but you can still see the difference of player name)
![TIM图片20190804162744](https://user-images.githubusercontent.com/11809767/62421537-ebb04d80-b6d5-11e9-827c-6d478bff9642.png)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for your report. Fix will be available in the Quests 3.8.0 release.
