### ISSUE TITLE
Region Start Not Working

### ISSUE THREAD

**Issue by sameethan1** [PikaMug/Quests#896]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-3.7.8
WorldGuard-7.0.1Beta & 7.0.0
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When setting up a quest to start with a region it won't give the player the quest.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/a1XYq39K

**Comment by PikaMug** [comment]
Use https://ci.codemc.org/job/PikaMug/job/Quests/19/

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
