### ISSUE TITLE
Adding support for "Custom Items"

### ISSUE THREAD

**Issue by Tobi-Jakka** [PikaMug/Quests#900]
**What does your feature do?**
It allows for [custom items](https://github.com/jojodmo/CustomItems/wiki/Developer-API) to be used in quests.
**How would people use it?**
They would be able to make quests that either tasks you with mining or finding a custom ore, item or weapon or being rewarded with one.

**Comment by PikaMug** [comment]
This would be best handling with a module. I’ll consider writing it myself, but since such requests are low priority, it may be faster for you to solicit a developer on the Spigot hiring forum.

**Comment by Tobi-Jakka** [comment]
Ah okay, I spoke to the developer of that plugin himself & he said it would be easy for you to add support to it

**Comment by PikaMug** [comment]
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#need-support-for-other-plugins
