### ISSUE TITLE
MythicMobs module for 1.13

### ISSUE THREAD

**Issue by Tobi-Jakka** [PikaMug/Quests#901]
**What does your feature do?**
It would be a MythicMobs quest module working on 1.13 + (perhaps lower versions too), I know there is 1 currently but it havent been updated...
**How would people use it?**
They would be able to use the plugin MythicMobs in their quests, example: Kill a certain custom mob to complete a quest.

**Comment by PikaMug** [comment]
The github page for the current MythicMobs module states it works on up to MC 1.13.2, so I imagine the Spigot page just hasn’t been updated. If the github page is wrong, you’d be better off asking the author to update it, as module requests are low priority for me. Alternatively, you could solicit someone from the Spigot hiring forum.
