### ISSUE TITLE
Translation ERROR

### ISSUE THREAD

**Issue by AniVamGam** [PikaMug/Quests#902]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.8
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
i have created manually the lang florder and downloaded de file in the config i changed to de and tryed DE-de but its not translating
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Please try the steps outlined in Troubleshooting:
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting
