### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by brnxx** [PikaMug/Quests#903]
![image](https://user-images.githubusercontent.com/49076883/62564724-c4838880-b85b-11e9-80bc-fdab5dbbfd55.png)

this happens when I edit a quest.

Log error bug: https://pastebin.com/kSU715Ne

**Comment by PikaMug** [comment]
At first glance, it seems something is wrong with Citizens integration. Please provide your server's startup log.

**Comment by brnxx** [comment]
https://pastebin.com/gFERtjrW

**Comment by brnxx** [comment]
> 
> 
> At first glance, it seems something is wrong with Citizens integration. Please provide your server's startup log.

https://pastebin.com/gFERtjrW

**Comment by PikaMug** [comment]
Recent development builds should resolve this issue.
