### ISSUE TITLE
Cooldown bug

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#905]
`/quests list` don't show me quest with cooldown what i finished even if cooldown ended.

**Comment by KsuKsuKsu** [comment]
And tell me please what is difference between "repeat" and "cooldown" at planner? English is my second lang and i can't understand it.

**Comment by PikaMug** [comment]
This is probably intentional since the list only shows quests which can currently be taken, but I'll look into it.

For the followup question, please see https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Planner

**Comment by KsuKsuKsu** [comment]
Thank you very much. But what about "redo-delay"? I can't find information about it.

**Comment by PikaMug** [comment]
“Redo-delay” is the “cooldown”.  It was renamed many versions ago.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PikaMug** [comment]
So I created a block-break quest with a cooldown of 60 seconds, and it shows up in _/quests list_ before accepting, during the quest, after completing it, and after the cooldown expired. Then, I repeated the quest and it continued to appear in _/quests list_ just fine.

Note that if you have `ignore-locked-quests: true` set in config.yml, then the behavior you've described is intentional.

**Comment by KsuKsuKsu** [comment]
But after all, when the cooldown has passed and the quest is available again, it is no longer considered locked, therefore it should be shown

**Comment by PikaMug** [comment]
In my testing, the quest _did_ show after the cooldown expired with `ignore-locked-quests: true` set. However, it seems that only worked correctly for the first cycle - taking the quest multiple times results in the bug you've described. I will push a commit which resolves this.

**Comment by PikaMug** [comment]
Use https://ci.codemc.org/job/PikaMug/job/Quests/22/ once available

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.
