### ISSUE TITLE
Error when I try to start a Quest

### ISSUE THREAD

**Issue by Tobi-Jakka** [PikaMug/Quests#906]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.7-b12

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/YpfbJVmS

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/P3DHbQvR

**Comment by PikaMug** [comment]
Thanks for the report. What is your exact WorldGuard version?

**Comment by Tobi-Jakka** [comment]
After removing the WorldGuard region from the quest it started working again, I am using WorldGuard v. 7.0.0, also I cant seem to get the "set repeat cycle" to work its just gray (I dont want players to take quests more than once)? & would it be possible to have a config options that allows me to disable the ask & finish message, since I want to handle those messages myself with another plugin* ?

**Comment by PikaMug** [comment]
Glad to hear. Chances are you’re using an old WG 7.0.0 beta version - upgrading to the release should resolve the issue.

You must set a start add end date before being able to set a repeat cycle.

It is not possible to exclude the ask and finish message. After setting one, you could set the messages to a blank string within quests.yml

Please open a new issue for any further non-WorldGuard questions.
