### ISSUE TITLE
Quests not downloading lang files?

### ISSUE THREAD

**Issue by HiChanx** [PikaMug/Quests#907]
Im using Quests 3.7.8

I guess quests isn't writing the files property or somethings stopping it from writing files??
https://pastebin.com/yue9MBAX

I have no other issues with any other plugins creating configs and lang ymls..

**Comment by PikaMug** [comment]
Please try the steps outlined in Troubleshooting:
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting

If that doesn't help, you can download the files manually from
https://github.com/PikaMug/Quests/tree/master/main/src/main/resources/lang

**Comment by HiChanx** [comment]
Hey im trying the troubleshooting now first.. then i'll try to download the files.. but when i went to the download files link.. im not sure how to exactly download them..

**Comment by HiChanx** [comment]
Yeah pika.. none of those are working.. i tried even downloading the lang folder and put it inside of my quests plugin folder.. still not working..

**Comment by PikaMug** [comment]
Have you setup the folder path correctly? As an example, Spanish would be /plugins/Quests/lang/es-ES/strings.yml

Any console warnings?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HiChanx** [comment]
Yes. that is esactly how i had it.. i actually just ended up dragging the whole language folder over from the QuestsMaster folder that i downloaded.. nope the same console warnings..
 something about how it can't downoad the lang files.

**Comment by PikaMug** [comment]
I'm getting the impression you may have tried to download the entire /lang folder I linked, when only the individual files can be directly downloaded. Here's all of the files uploaded to Dropbox for you:
https://www.dropbox.com/s/1gc2slrz1e7lqy8/lang.zip?dl=0

Quests does not download files itself; they're stored within the jar and copied into the folder at startup. Please share the exact console warning(s) you're getting to proceed.

**Comment by HiChanx** [comment]
[17:43:20] [Server thread/ERROR]: [Quests] Failed loading lang files for en-US because they were not found. Using default en-US
[17:43:20] [Server thread/INFO]: [Quests] If the plugin has not generated language files, ensure Quests has write permissions
[17:43:20] [Server thread/INFO]: [Quests] For help, visit https://github.com/FlyingPikachu/Quests/wiki/Casual-%E2%80%90-Translations
[17:43:20] [Server thread/INFO]: [Quests] Loaded language en-US. Translations via Crowdin

That's the error i still recieve even after dragging the lang folder with en-US in it..

**Comment by HiChanx** [comment]
Got any ideas what might be going on pika?

**Comment by PikaMug** [comment]
@HiChanx Still investigating. Would you mind trying something for me?

In the folder of the language you're trying to use, create a second file named `strings_new.yml` and leave the contents of the file blank, then see if it loads.

**Comment by HiChanx** [comment]
Do I do that inside the en-US folder? or just Language.

**Comment by PikaMug** [comment]
en-US or whatever language you're trying to use (i.e. Spanish would be es-ES)

**Comment by HiChanx** [comment]
Okay! will try when i get home!

**Comment by HiChanx** [comment]
YEEEEEEEEEES

[23:01:15] [Server thread/INFO]: [Quests] Enabling Quests v3.8.0-b19
[23:01:15] [Server thread/INFO]: [Quests] Loaded language en-US. Translations via Crowdin

**Comment by HiChanx** [comment]
THANK YOUUUU now the question is.. which one do i use to modify any of the messages? the one in strings or the new?

**Comment by PikaMug** [comment]
Glad you were able to get it working! You would modify the `strings.yml` file to apply changes.
