### ISSUE TITLE
Do not show commands in reward

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#908]
You specify a reward commands like:

      commands:
      - pex user <player> add To.Next
      - pex user <player> remove neproshel.obuchenie
      - sudo <player> tofarm

Then you complete the quest and get a reward. The text of these commands is written in the chat. 

      - pex user <player> add To.Next
      - pex user <player> remove neproshel.obuchenie
      - sudo <player> tofarm

It is not very good for the player to see this. I think this does not need to be shown. In previous versions of the plugin, this was implemented differently.

**Comment by Technodate** [comment]
Look at #849

**Comment by PikaMug** [comment]
Like @Technodate alluded to, use a command display override.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
