### ISSUE TITLE
[ERROR] [Quests] An error has occurred with Quests. Please report on Github. Include the info below

### ISSUE THREAD

**Issue by ShinobiSondre** [PikaMug/Quests#909]
Quests 3.7.1

**Describe the problem and how to replicate it. Any console errors to post _using 
Not entierly sure how to replicate it, but here is the error in full: https://pastebin.com/RNeqEkM5

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by kubastion** [comment]
I have problem, because i have 21 missions in GUI. And when i try to make 22 mission in gui, can't bcs when i do it, quests work but in chat, not in gui
here is config from this one:
`  custom1:
    name: dfdf
    npc-giver-id: 41
    ask-message: fgfg
    finish-message: fgg
    gui-display: name-ENCHANTED_BOOK:amount-1
    stages:
      ordered:
        '1':
          break-block-names:
          - stone
          break-block-amounts:
          - 6000
          break-block-durability:
          - 0
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true`

**Comment by kubastion** [comment]
here looks better https://pastebin.com/peGnrbZf
