### ISSUE TITLE
GUI problem

### ISSUE THREAD

**Issue by kubastion** [PikaMug/Quests#910]
I have problem, because i have 21 missions in GUI. And when i try to make 22 mission in gui, can't bcs when i do it, quests work but in chat, not in gui
here is config from this one:
https://pastebin.com/peGnrbZf

**Comment by PikaMug** [comment]
Try the latest 3.8.0 dev build https://ci.codemc.org/job/PikaMug/job/Quests/

**Warning:** The builds linked above are experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.
