### ISSUE TITLE
Support EliteMobs plugin

### ISSUE THREAD

**Issue by millermx** [PikaMug/Quests#912]
**What does your feature do?**
Support the EliteMobs plugin. Essentially what MythicMobs and BOSS have now.

**How would people use it?**
Players can integrate custom mobs from EliteMobs when building quests.

**Comment by PikaMug** [comment]
This would be best handled with a module. I’ll consider writing it myself, but since such requests are low priority, it may be faster for you to solicit a developer on the Spigot hiring forum.

**Comment by millermx** [comment]
Thank you for a quick reply! I'll head over to the forums and work on that then.
