### ISSUE TITLE
Parties problem

### ISSUE THREAD

**Issue by michaalbo** [PikaMug/Quests#915]
**What is your Quests version/build number (do _not_ say "latest")?**
v3.7.8-b16

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
SkillAPI's party system doesn't work with Quests and blocks them from working.
https://dev.bukkit.org/projects/skillapi-parties <- said party plugin
https://pastebin.com/fQY4uysN <- errors in the console regarding Quests

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
The plugin doesn't enable at all.

**Comment by PikaMug** [comment]
Thanks for reporting this. The next release of Quests will resolve this issue.

Please note that it will not allow SkillAPI-Parties integration within Quests; but merely stop the error. I will attempt to work with the developer of SkillsAPI to better support it the unofficial plugins which depend on it.
