### ISSUE TITLE
Multiple NPC kill doesnt let the quest work

### ISSUE THREAD

**Issue by Azucliar** [PikaMug/Quests#916]
when i set up "Kill npc" if i have more than 1 it doesnt let me close the chat gui, i want it to be able to set roughly 15 npcs that you can kill but you only need to kill 5im using version 3.7.8-b16

here is the pastebin for the quest https://pastebin.com/e9nJxU7Q

Sorry my english isnt very good

**Comment by PikaMug** [comment]
You must set kill amounts for _each_ NPC.

**Comment by Azucliar** [comment]
> You must set kill amounts for _each_ NPC.

how do i do that? and how do i set it to just make it, if they just kill ANY of the npcs it goes towards the counter?

thank you

**Comment by PikaMug** [comment]
Just like how you separated NPC IDs with a space, you must separate NPC kill amounts with a space. You must have the same number of kill amounts as IDs, otherwise the plugin will not let you proceed.

Killing "any" NPC is not possible and would require a custom module. See my last comment in #789
