### ISSUE TITLE
Quests placeholders dont work

### ISSUE THREAD

**Issue by Kranex95** [PikaMug/Quests#918]
Hi, i have a problem with the placeholders.
I have a menu with the plugin DeluxeMenus, where i have items for each quest but the error is this:
when i use Quests placeholders, the menu cant open because the placeholders dont work.
With the same item, with other placeholder like Essentials, the menu can open.

I have all required plugins with latest versions:
- DeluxeMenus 1.12.0
- PlaceholderAPI 2.10.3 with Player, Essentials and Quests expansions.
- Quests 3.7.8-b16
I work with Spigot 1.14.4.
Here my DeluxeMenus menu for my quests: https://pastebin.com/jbaKeeeG
No errors in console and log, so i think is not required because the menu work but no with Quests placeholders.

![deluxemenus](https://user-images.githubusercontent.com/42676494/63197680-b9f59a00-c078-11e9-91a2-7bfe08789684.png)
![papi](https://user-images.githubusercontent.com/42676494/63197681-b9f59a00-c078-11e9-8a05-8cb252384cdc.png)
![quests](https://user-images.githubusercontent.com/42676494/63197682-b9f59a00-c078-11e9-9a63-00f9ef7fc335.png)
![spigot-ver](https://user-images.githubusercontent.com/42676494/63197683-ba8e3080-c078-11e9-851d-1aee4b2f0287.png)

**Comment by PikaMug** [comment]
Thanks for your report. I don’t have DeluxeMenus, but will my best to assist you.

Did you download the Quests expansion from SpigotMC, or the PAPI eCloud?

Also, please provide the “zkiller” quest from quests.yml for testing (use Pastebin).



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kranex95** [comment]
Here i the zkiller quest https://pastebin.com/gDiunvtD

**Comment by PikaMug** [comment]
Thank you. As far as I can tell, placeholders are working as expected:

![zkiller1](https://user-images.githubusercontent.com/2267126/63219785-71f17880-c147-11e9-8a89-470c06f893a3.png)

I've tested the variable using [ChatInjector](https://www.spigotmc.org/resources/chatinjector.38327/), a plugin which lets you display PAPI variables in chat. Before taking the "zkiller" quest, `%quests_player_has_current_quest_zkiller%` returns `false`, then once I take the quest, it returns `true`, as shown.

Are you certain [PlaceholderExpansion-Quests](https://www.spigotmc.org/resources/placeholderexpansion-quests.69357/) loaded properly? It should be located in the _plugins\PlaceholderAPI\expansions_ folder.

Perhaps it's only a specific variable that isn't working? Which variable are you testing with?

**Comment by Kranex95** [comment]
I test placeholders with command /papi parse me %quests_player_has_current_quest_zkiller% and i do the dame, and give false and true, so the expansión its loaded because placeholders works in chat but no with DeluxeMenus. I test 2 placeholders, can accept and has current. In chat both give me correct result.

**Comment by PikaMug** [comment]
This sounds like an issue with DeluxeMenus, then. Please reach out to their developers at https://helpch.at/discord

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kranex95** [comment]
Ok, thanks for help.
