### ISSUE TITLE
Conflict with MythicMobs?

### ISSUE THREAD

**Issue by pab993** [PikaMug/Quests#920]
Quests version: Quest 3.7.8-b16
Hello!, I'm running a server with Quest and MythicMobs plugins together. I don't really know if this can be future problem. Right now, I can play with no ploblem, but the console throws this every time I kill a MyhicMob in game. The MythicMobs version is 4.6.5.

![image](https://user-images.githubusercontent.com/15108240/63445192-3c46db00-c438-11e9-8212-64f43d275013.png)

Thanks for the plugin  and greetings!

**Comment by PikaMug** [comment]
You're using an old version of the MythicMobs extension. Update to the latest version.
