### ISSUE TITLE
Objective Display SPAM

### ISSUE THREAD

**Issue by Prowco** [PikaMug/Quests#922]
**What is your Quests version / build number (do _not_ say "latest")?** 
                                         3.7.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Hi  i have a problem well i create with  quests some jobs so u need to go to some specific places and when  u finish u get paid. Everything works  perfect the gps integration and everything but when you reach a location every step u did close of the location the objective text get spam lot of times so i try change the  objective text for just 3 points  ... but its annoying too, here i let a screenshot as evidence and my quests config.
https://i.imgur.com/51bO08s.png

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/mb6F759J

**Comment by PikaMug** [comment]
Thanks for the report. The "spam" you've described is simply a notification that the player has reached the objective's location. This message is necessary to inform the player that they have fulfilled the objective. There are no plans to remove this message, as doing so could easily confuse and/or frustrate the player.

If you don't like the look of the message, you could set the `completed` and `redoCompleted` to a blank character in strings.yml for your selected language. Alternatively, if it's just the green color that bothers you, the color can be changed using tokens from https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#formatting

**Comment by Prowco** [comment]
i understand the meessage is necesary but why the problem is the msg show like 10 or 15 times per location thats a lot i think 1 time or 3 is enough

**Comment by PikaMug** [comment]
I see. Will reopen pending investigation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PikaMug** [comment]
A build containing the solution to this issue will be available at:
https://ci.codemc.io/job/PikaMug/job/Quests/43/
