### ISSUE TITLE
Different NPCs with different Quests but using the same Item in the GUI 

### ISSUE THREAD

**Issue by DragonCrystal** [PikaMug/Quests#923]
**What is your Quests version / build number (do _not_ say "latest")?**
Version 3.7.7-b12
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When using a differnt NPC with a different quest, everything is fine but until using the GUI with an item that is already used in another NPC with a different quest, it looks as if it accepts the item for the GUI interface but then when Im about to go to another section to set up the quest, it says: Set GUI Item display (none set) I can only think that 1 item that is used in a GUI item display cant be used for another NPC's GUI item display.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by DragonCrystal** [comment]
Nevermind, somehow it fixed itself

**Comment by PikaMug** [comment]
Thanks for the report. Please give the latest dev build a try and let me know if it resolves the issue:
https://ci.codemc.org/job/PikaMug/job/Quests/27/

Warning: The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
