### ISSUE TITLE
Could not pass event EntityDeathEvent to Quests v3.7.8-b16

### ISSUE THREAD

**Issue by Newpoman** [PikaMug/Quests#926]
Please Help! This is spamming my server console constantly. Have no Idea whats causing it.
using latest quests version 3.7.8 and using latest spigot 1.14.4. 
CraftBukkit version git-Spigot-798ea6a-44d675a (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[https://pastebin.com/FVmF0Dt5](url)

**Comment by wrenchyt** [comment]
I had this problem on 3.7.8-b16 and now on 3.8.0-b26

**Comment by wrenchyt** [comment]
I had this problem with npc sentry too

When i create npc sentry and i kill it i have this error: " Could not pass event NPCDeathEvent to Quests v3 7 8-b16" and then 2 npcs respawn and i cannot kill one of them, until i remove that npc.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
