### ISSUE TITLE
Could not pass event NPCDeathEvent to Quests

### ISSUE THREAD

**Issue by wrenchyt** [PikaMug/Quests#927]
When i create npc sentry and i kill it i have this error: " Could not pass event NPCDeathEvent to Quests v3 7 8-b16" and then 2 npcs respawn and i cannot kill one of them, until i remove that npc.
same problem with 3.8.0-b26.
pastebin: https://pastebin.com/jX1Xv9BN

**Comment by PikaMug** [comment]
Thanks for your report. I believe recent development builds should resolve this issue. Please give the latest a try and, if the issue persists, let me know by leaving a comment below.
