### ISSUE TITLE
Quest with GPS feature not working correctly

### ISSUE THREAD

**Issue by codgamerMC** [PikaMug/Quests#928]
**What is your Quests version / build number (do _not_ say "latest")?**
(3.7.8-b16)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** 
NONE

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/fceddDF6

Problem:
The GPS feature for quest stages seemed to have been working fine, as of lately after updating plugins it does not work properly anymore, when picking new quests, the GPS will randomly appear not all the time like it should, also if it does work, when going from one stage to the other it will shut off and stop working, therefore for the next stage, you have to guess where to go, how can I fix this issue?

**Comment by PikaMug** [comment]
Thanks for your report. No changes to integration within Quests have been made in recent memory. Have you tried reverting to an older version of GPS? If that resolves the issue, try to figure out which version of GPS created the problem and I'll look into it.

**Comment by codgamerMC** [comment]
I was using GPS Version 2.13.1 but reverted to 2.11.0 and partially fixed the problem, at least the arrow appears 99% of the time, but I had it set where the arrow would reset no upon the person reaching the destination but updating stages, so if you passed your destination it would not remove the GPS arrow, basically the radius I put to 0.0 but when I do that now, the arrow does not update, I don't think it's much of a problem of GPS but more with the GPS-Quest Integration being outdated, I think, since I am running the latest Quest Version that could cause some problems, but with some tweaks I got it to work at least, not as it used to but at least players don't get lost.

**Comment by PikaMug** [comment]
The "Cannot reach destination from here!" error means the destination is either in another world or over 9999 blocks away. You can increase `maxDistanceToEntry` in GPS's _config.yml_ file to something greater than that, but you may notice decreased performance.

A radius of 0.0 essentially disables arrow updates, so that's expected. I recommend using a value similar to what you're using for most quests' reach-destination radii.

Previously I was compiling GPS-Quests against GPS 2.7.4, but even after upgrading to 2.13.3 I'm not seeing any conflicts. I'm thinking that making the aforementioned adjustments to your settings may resolve the issue. If not, feel free to request re-open.

**Comment by codgamerMC** [comment]
Usually Quest stages are no more than 100 blocks away from each other in the same world the longest one is 300 blocks not 9999 blocks away as for 0.0 never had a problem the arrow would just change to the next objective once the next stage starts, set it to 2.0 tho, still have the problem works for some quest stages, not all, all my quests are NPC talks, but for some it appears for others says can't reach destination and for others well it doesn't work, and it worked before upgrading the quest version from 3.7.6 to 3.7.8, still cracking my head over it

**Comment by codgamerMC** [comment]
@PikaMug Don't know if you have been able to read my reply?

**Comment by PikaMug** [comment]
@codgamerMC I’ll have to try relocating this at some point. Have you verified the issue persists on the latest Jenkins build?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codgamerMC** [comment]
No and how do I access it?

**Comment by PikaMug** [comment]
@codgamerMC https://ci.codemc.org/job/PikaMug/job/Quests/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codgamerMC** [comment]
Thanks @PikaMug, I will be sure to check it out and let you know as soon as possible

**Comment by codgamerMC** [comment]
@PikaMug Updated to 3.8 and For what I see, if GPS destination is reached and next stage is started now it will update but, if radius is set at 2 blocks and player is at 3 blocks then when moving into the next stage the player still does not get an updated Arrow for the next stage which was part of the original problem

**Comment by codgamerMC** [comment]
Was left to the conclusion that GPS-Quest plugin is outdated and the cause of the problem of GPS arrow not updating in each stage, is it possible to update the plugin so the arrow updates to the next stage, GPS and Quest are both in the latest versions

**Comment by PikaMug** [comment]
As I tried to allude to earlier, the radius for Quests and GPS are not intertwined; they are independent of each other. That's not a bug, but rather a limitation of GPS as they don't have an API method to change a destination's radius on-the-fly. All you can do is set the two radii as close to each other as possible. Alternatively, some players have worked around this by forcing the player to do something like stand on a pressure plate in the center to ensure both will be updated.

If GPS ever supplies an API method for its radii, I'll be sure to update GPS-Quests accordingly. Please direct future inquiries about GPS-Quests to [it's own issue tracker](https://github.com/PikaMug/GPS-Quests/issues).
