### ISSUE TITLE
"null" but something went wrong

### ISSUE THREAD

**Issue by fmohican** [PikaMug/Quests#930]
**What is your Quests version / build number (do _not_ say "latest")?**  Quests version 3.7.8-b16

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When user want to take quest from NPC, after answer "yes", on chat says an error and contact admins, on console i got this:

```
[20:34:10 INFO]: [Quests] {InsertPlayerNameThere} attempted to take quest "null" but something went wrong
```

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
I'm not fan of pastebin, i hope you like Gist
https://gist.github.com/fmohican/0bc49dccc96f8a0f98009c35385adeab

Edit: When i take quest with "admin" they work. If i trying to take with user (who has permissions) isn't work.
Also i was trying to take quest with /qs take 1 (cuz this is main quest, that should be completed), sadly isn't work :(

![image](https://user-images.githubusercontent.com/8583317/64217165-00deee80-cec5-11e9-8336-56b7058762a3.png)

**Comment by fmohican** [comment]
Well its ok fine, if i use GUI (`qa toggle gui [npc_id]`) instead of CLI

**Comment by PikaMug** [comment]
Thanks for the report. I've confirmed that the issue is limited to the CLI, but I can't replicate it myself. Do you know which quest is the one affected?

**Comment by fmohican** [comment]
The other quest are required to complete 1st quest, since player can't get 1st quest they cant start others.

By 1st quest i mean "1. Bun venit în Regatul Tys", Line 58 in my config or ( https://gist.github.com/fmohican/0bc49dccc96f8a0f98009c35385adeab#file-quests-yml-L59 )

**Comment by PikaMug** [comment]
I've just pushed a commit which I believe will resolve the issue. If you're able to compile the plugin yourself, feel free to test it and let me know the results. Otherwise, look forward to its inclusion in the next release!

**Comment by fmohican** [comment]
Right now i'm pulling form git and i will try asap.

**Comment by fmohican** [comment]
I can't check, the command to toggle npc gui isn't work.
[20:00:28 INFO]: X issued server command: /qa
[20:00:30 INFO]: X issued server command: /questadmin togglegui 10
![image](https://user-images.githubusercontent.com/8583317/64446258-087adf00-d0e1-11e9-8332-4441cb927711.png)

**Comment by PikaMug** [comment]
@fmohican That command has been removed from Quests 3.8.0+ as the way GUIs are handled has changed, but it looks like I forgot to remove some references to it.

You'll want to open the quest in the editor in order to remove the GUI.

**Comment by fmohican** [comment]
Oke, i will try 👍
