### ISSUE TITLE
Feature Suggestion placeholder and denizen script when accept

### ISSUE THREAD

**Issue by JuanDavidSolano** [PikaMug/Quests#932]
**What does your feature do?**

- Execute a Denizen script when the player accept the quests
- Add a placeholder to show all the tasks that the player have in a scoreboard (I know thhat there is a placeholder but it only shows the task of a specific quest)

**Comment by PikaMug** [comment]
Denizen scripts are now available as Actions using the following build:
https://ci.codemc.io/job/PikaMug/job/Quests/52/

Note that while quests which run scripts alongside objectives in the Quest Editor will still load and work fine, but it is no longer possible to add scripts in this manner.

Also, I'm not interested in adding scoreboards of any kind, for reasons of compatibility and plugin conflict which I have already discussed in several previous tickets. Use the PlaceholderAPI add-on with a plugin like FeatherBoards to accomplish what you're trying to do.
