### ISSUE TITLE
German Language not working

### ISSUE THREAD

**Issue by general2811** [PikaMug/Quests#933]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-3.7.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
[15:22:47 ERROR]: [Quests] Failed loading lang files for de-DE because they were not found. Using default en-US

**Comment by PikaMug** [comment]
Thanks for your report. Please try the latest Quests build from https://ci.codemc.org/job/PikaMug/job/Quests/

If the issue persists, follow the directions at https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations#troubleshooting

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
