### ISSUE TITLE
Not recognizing Citizens

### ISSUE THREAD

**Issue by Diclo** [PikaMug/Quests#934]
server paper 1.14.4
Citizens-2.0.25-b1746
Quests-3.8.0
![imagen](https://user-images.githubusercontent.com/25293585/64678924-d4345500-d437-11e9-9f00-c43abd83992f.png)
![imagen](https://user-images.githubusercontent.com/25293585/64678952-e0b8ad80-d437-11e9-9c6e-1e4a3b98ac10.png)

**Comment by PikaMug** [comment]
Thanks for the report. Which build of Quests are you using? There should be a build number after "3.8.0"

**Comment by Diclo** [comment]
#b27

**Comment by PikaMug** [comment]
Thank you. As far as I can tell, it should work properly with that build. Would you mind providing your startup log?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Diclo** [comment]
https://pastebin.com/8mEueRZ6

**Comment by PikaMug** [comment]
Another plugin is forcing Citizens to load before Quests. I’ll try to find a solution for this.
