### ISSUE TITLE
GUI Item display not working with log variants

### ISSUE THREAD

**Issue by Sz0rt** [PikaMug/Quests#935]
**What is your Quests version / build number (do _not_ say "latest")?**
quests 3.7.8      minecraft 1.12.2
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**  if you make a gui item display a birch log itll show up as an oak log when youre done with the quest. no console errors

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
yeah sure hold up, https://pastebin.com/SHkd90FU

**Comment by PikaMug** [comment]
Thanks for your report. Use the following development build or wait until the next Spigot release:
https://ci.codemc.org/job/PikaMug/job/Quests/33/
