### ISSUE TITLE
Won't save block-quests and ask

### ISSUE THREAD

**Issue by DawrFromUa** [PikaMug/Quests#937]
Hi!

Ver. server Spigot 1.14.4
Ver. plugin Quests-3.8.0

I want make a storylines, where player must choose a line of quests. If i type block quests, it won't to save (in file it save, but won't in game).
What's wrong?

And an ask: How to hide another quests if they was in block-quests ?

**Comment by PikaMug** [comment]
Unable to replicate this with quest-blocks using the latest 3.8.0 build. Note that you must have at least 1 stage in a quest for it to save properly.

I'm not sure what you mean by hiding another quest, but generally blocked quests are hidden from players so long as `ignore-locked-quests: true` is set in config.yml

**Comment by DawrFromUa** [comment]
My quests have more than 2-3 steps.

ignore-locked-quests: false
