### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by SskyWorms** [PikaMug/Quests#939]
Im using 
* Quests  3.7.8 b16
* PlaceholderAPI 2.10.3
Error
* When i parse %quests_player_cooldown_time_remaining_Iron_Miner%
 i get blank line
* No error in console
* I was download QuestExpansion - Placeholder and put it in PlaceholderAPI Expansion folder and then i reloaded but still not work :0 please help me check it
( Im using default quest file )

**Comment by PikaMug** [comment]
Thanks for your report. The default Iron Miner quest does not contain a cooldown, and thus will not display anything unless you modify it to contain one.
