### ISSUE TITLE
Errors when interacting with NPC's

### ISSUE THREAD

**Issue by BytedByte** [PikaMug/Quests#942]
Hello,

Whenever someone interacts with NPC by right-clicking a big error pops up in the console.
I'm running Paper on 1.12.2 using the latest version of Quests (Wahrheit Update) along with latest version of Citizens2 (2.0.25-b1751)

Here's the error message: https://pastebin.com/vtdjPGQC

Any fixes?

**Comment by PikaMug** [comment]
Thanks for your report. That error is from MythicMobsQuestsModule; not Quests. Please seek out the developer of the module (BerndiVader) for assistance.

Also, I highly recommended that you update to a more modern version of Quests.
