### ISSUE TITLE
Reloading causes all stages to be incompletable 

### ISSUE THREAD

**Issue by lyimpike** [PikaMug/Quests#945]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Reloading the plugin causes all stages to require the player to break, damage, place, use and cut a unspecifed block. This does not show up in the quests.yml

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/juKQ1N23

**Comment by PikaMug** [comment]
Thanks for the report. The quest in your Pastebin was missing a space in front of `- name-STONE_SWORD:amount-1` which I've inserted for testing.

I wasn't able to replicate the issue. After reloading with _/questadmin reload_ the objective had not changed in the Quest Journal. I proceeded to craft a Stone Sword and complete the quest without issue.

Perhaps this could be resolved with a more recent build of Quests available from the development server. If not, feel free to comment with additional information.

https://ci.codemc.org/job/PikaMug/job/Quests/

**Comment by lyimpike** [comment]
This is fixed in the lastest build however now when adding a stage step it shows as (not set) when it is clearly set to require a stone sword. Making it impossible to complete the quest.

![image](https://user-images.githubusercontent.com/25600834/65494769-4cecd580-de6a-11e9-8d10-13ce846c6c3d.png)

**Comment by lyimpike** [comment]
UPDATE! This works if you are an OP, if you are a player. Then this does not work

**Comment by lyimpike** [comment]
Video: https://www.youtube.com/watch?v=BgGRLX7_Opg&feature=youtu.be

**Comment by lyimpike** [comment]
If you have a few moments, I would love to invite you to the server and  OP you for testing.

**Comment by lyimpike** [comment]
Update, this only happens for item quests, just tested with a Kill Npc objective and it works fine, OP or not.

**Comment by PikaMug** [comment]
The behavior from your video is not a permissions issue as, once a quest has been accepted, the plugin no longer checks whether a player is OP or not. This is evidenced by the fact your other objectives work fine.

Most likely another plugin is blocking the crafting event for non-OP'd players. Try removing all non-essential plugins except for Quests, then see if it works. If so, add plugins back one-by-one until you find the conflict.
