### ISSUE TITLE
All quest commands no longer responding in chat

### ISSUE THREAD

**Issue by Rexcaliburr** [PikaMug/Quests#949]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No console errors. All commands do not have any response in chat. This includes any /quests and /questadmin command. The plugin is green in /plugins, but just does not respond. Is it possible that this is clashing with FAWE, or GriefPrevention? There have only been these two plugins recently added before Quests stopped working.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
N/A

**Comment by PikaMug** [comment]
Thanks for your report. I'm not aware of any plugin conflicts, however if that's a concern the obvious next step would be for you to remove FAWE and GriefPrevention temporarily to see if that resolves the issue.

**Comment by Rexcaliburr** [comment]
Ah, got it! I got rid of GriefPrevention and it works again, thanks!

**Comment by PikaMug** [comment]
Glad you resolved the issue! I'll keep this open pending further investigation.

**Comment by PikaMug** [comment]
After installing the lastest version of GriefPrevention, I was unable to find any conflicts in my test environment. My hypothesis is that GP altered the loading order of plugins for your server, in which case I'd need more information to proceed. Unless anyone else comes forward with this problem, I'm considering this matter resolved.
