### ISSUE TITLE
CharSemi not working

### ISSUE THREAD

**Issue by iTzMatiasHD** [PikaMug/Quests#951]
Goodnight,

I have changed the translator file currently using the "es_ES" and changed the charSemi to% saved in UTF-8, and I am using version 3.8.0. However, the error that I attached in the pastebin file happens.

Regards.

[https://pastebin.com/U4wABsLh](https://pastebin.com/U4wABsLh)

**Comment by PikaMug** [comment]
Unfortunately, the charSemi variable no longer works in the way you're trying to use it. This has been the case for some time (see #808). The solution is to update to a Quests 3.8.0 development build, available at the link below. After updating, you'll have to open the quest in the editor, then save it and run _/questadmin reload_.

https://ci.codemc.io/job/PikaMug/job/Quests/
