### ISSUE TITLE
Name on Item Stage 4 is NULL

### ISSUE THREAD

**Issue by Sponge1996** [PikaMug/Quests#953]
**What is your Quests version / build number (do _not_ say "latest")?**
Plugin-version: 3.8.0-b34
Minecraft-Server-Version 1.14.4 Paper

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When creating a quest under the Point Items the fourth position is the name NULL which actually means brewing. Procedure: /quests editor -> 1 -> Enter name -> 11 -> 1 -> 2 -> and 4 (NULL)

![item null](https://user-images.githubusercontent.com/18584669/66429655-c19e4300-ea18-11e9-91d6-19922f842121.png)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. Use the following development build, once available:
https://ci.codemc.io/job/PikaMug/job/Quests/36/
