### ISSUE TITLE
Missing names in Potions

### ISSUE THREAD

**Issue by Sponge1996** [PikaMug/Quests#955]
**What is your Quests version / build number (do _not_ say "latest")?**
Plugin Version 3.8.0-b34
Server version 1.14.4 Paper
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
With 7 Potions the correct designation is missing
![Screenshot_4](https://user-images.githubusercontent.com/18584669/66430667-d8459980-ea1a-11e9-9fc9-6889b2711c06.png)
![Screenshot_5](https://user-images.githubusercontent.com/18584669/66430699-e7c4e280-ea1a-11e9-9716-91029e1433d4.png)
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/YG7BAN8X
This is the excerpt from the quest where the potions are not named

**Comment by PikaMug** [comment]
Thanks for the report. Please try the following build and let me know the results:
https://ci.codemc.io/job/PikaMug/job/Quests/37/
