### ISSUE TITLE
Quest with time played

### ISSUE THREAD

**Issue by lbopp42** [PikaMug/Quests#956]
**What does your feature do?**
Have quests with the goal is just to play on the server.

**How would people use it?**
Like all quest. In stage.

**Comment by ArathiaMC** [comment]
+1

**Comment by Larskei-dev** [comment]
You can already make this via an action, just make it so it completes the stage action when it runs out on the timer

**Comment by PikaMug** [comment]
Currently, Quests does not track when players are first- nor last-seen, so there's no way to tell how long they've been playing. If the goal is to merely force the player to spend a certain about of time on a quest, then the suggestion by @Larskei-dev is most effective, as it encourages players not to log out (as the timer will continue ticking).
