### ISSUE TITLE
Add a Command

### ISSUE THREAD

**Issue by DeniedINC** [PikaMug/Quests#959]
**What does your feature do?**
Add a command to open the quest journal.

**How would people use it?**
I use a GUI for my menu and most of my in game stuff, so being able to open it through a gui menu rather than have the quest journal would be amazing

**Comment by Technodate** [comment]
There is a command already;
/quests journal

If you wish to have it be a gui, take a look at this plugin extension;
https://www.spigotmc.org/resources/questsgui.71666/

**Comment by DeniedINC** [comment]
I have the extension but when I type /quests journal I still get the book even after enabling the gui in the questsgui config.
