### ISSUE TITLE
Can't add multiple Command triggered Actions to a stage.

### ISSUE THREAD

**Issue by LegitMeme** [PikaMug/Quests#962]
Note: I don't know if this is a glitch or a feature.

**What is your Quests version / build number (do _not_ say "latest")?**
3.7.6-b5

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Console Errors: None.
How to replicate?:
Firstly, I made a new Quest, I made a new stage and added a goal (Talk to "NPC"), then I went to the actions menu of the stage and added 4 "Command Action" Actions. When I save the Quest and start editing it again, every "Command Action" Actions I added except for the last one dissapear.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
No example, but I can tell you that the "Command Action" Actions I add do not save into the Quest.yml file and when I try to add the multiple Actions into the file manually they dissapear (Except for of course the last one added) after starting the server.

**Comment by Sponge1996** [comment]
Hi legit, Please try this newer version, with this version I could insert several commands in a stage which are also accepted https://ci.codemc.io/job/PikaMug/job/Quests/38/

**Comment by LegitMeme** [comment]
> Hi legit, Please try this newer version, with this version I could insert several commands in a stage which are also accepted https://ci.codemc.io/job/PikaMug/job/Quests/38/

I'll try that thanks!

**Comment by Sponge1996** [comment]
It may happen that you have to delete the complete folder of quests because some changes have been made in the files
