### ISSUE TITLE
Feature Request: Quests journal GUI to have same item as Quest GUI

### ISSUE THREAD

**Issue by Dynamite99** [PikaMug/Quests#963]
I purchased the new Quests GUI plugin and had a suggestion.

When you set the Quests GUI Item with option 8, it should also replace the book in the /quests journal GUI. 

Just a thought to not have  a ton of books in the GUI.

**Comment by PikaMug** [comment]
Thanks for using Quests and QuestsGUI. Your suggestion makes perfect sense and I'll look into it for a future release.

However, please direct all QuestsGUI bugs/suggestions to the discussion thread at:
https://www.spigotmc.org/threads/questsgui-paid.399346/
