### ISSUE TITLE
Feature Request: Hide text when using Quests GUI

### ISSUE THREAD

**Issue by Dynamite99** [PikaMug/Quests#964]
Hello again, I have 1 more suggestion.

When using the /quests editor with the Quests GUI plugin, I would like it to be possible in the config to turn off the text that appears in game, the same that appears when you dont have the addon. This would help to reduce clutter on the player's screen when editing a quest. 

Thanks!

**Comment by PikaMug** [comment]
Thanks for your report. Unfortunately, this is a limitation of the Bukkit [Conversation](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/conversations/Conversation.html) API - it simply isn't possible to hide the text while in a conversation afaik. However, if anyone reading this knows of a way to do it, I'm all ears!
