### ISSUE TITLE
Require stages to be completed using a specific item

### ISSUE THREAD

**Issue by Jakimbo** [PikaMug/Quests#967]
**What does your feature do?**
The player would either be given an item from the quest through an action, or would have to acquire their own through other means. Once they have the item they would have to actually use that specific item to complete a stage (Kill mobs with diamond sword, break blocks with diamond pick, etc)
**How would people use it?**
Admins would have more options to make a larger variety of quests. Could be anything from killing players with a specific sword to "absorb souls", to needing to mine with a particularly fast/slow pickaxe, or even killing the dragon using only a stick.

**Comment by PikaMug** [comment]
It's my understanding that you're asking for conditions, such as "complete quest while holding certain item" or "finish objective while underwater". While the timer action could be considered a condition, I'd very much like to see more of what you've suggested in the plugin one day. I'll place this on the back burner.

**Comment by PikaMug** [comment]
Done as of https://github.com/PikaMug/Quests/commit/a6c9949953ea1210b7dc0610cf75c517fccda4f0
