### ISSUE TITLE
Capturing mobs and bringing them to a specific location

### ISSUE THREAD

**Issue by Jakimbo** [PikaMug/Quests#968]
**What does your feature do?**
Allows an admin to set an area where the player must bring specific mobs. The stage would be completed when the set number of mobs are all in the right area. 
**How would people use it?**
Could make simple quests where you need to catch all of a farmers sheep and bring them back to their pen, or help a dark wizard gather zombie soldiers for his undead army, things like that.

**Comment by PikaMug** [comment]
Thanks for your suggestion. I'm a little hesistant to do something like this as there's a lot of variables to consider. How must the player move the mobs (lead, boat, minecart, pushing, etc.)? What if the mob belongs to another player? If the mob walks away from the location, despawns or dies, do we subtract from the number brought? What if a mob walks into the area without a player nearby? Is an orange Sheep acceptable if the quest creator only wants blue Sheep?

I feel something with that many possibilities should be left to a custom objective. If you have your heart set on this, I suggest visiting the Spigot [hiring forums](https://www.spigotmc.org/forums/hiring-developers.55/) and directing a developer to [this API](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API). Note that the hiring forums are in no way associated with Quests.
