### ISSUE TITLE
Hide the reward commands after completing quest

### ISSUE THREAD

**Issue by BytedByte** [PikaMug/Quests#970]
Hello, Would it be possible to hide all the commands being ran after the player completes a quest? It's incredibly ugly and lets everyone know which plugins I'm using.

Example: https://i.imgur.com/gOkywO6.png

I tried using the 'commands-override-display:' and adding commands on the line after it, but it didn't work.

**Comment by PikaMug** [comment]
The solution for this is to create a command override display, then go into your quests.yml file and change

`- 'myCommandOverride'`

to 

`- ' '`
