### ISSUE TITLE
Close GUI journal with 'E' or 'Esc'

### ISSUE THREAD

**Issue by BytedByte** [PikaMug/Quests#972]
Could you make it so the gui journal closes with E and Esc just like every other inventory menu?
Feels way more convenient than having to click the close button

**Comment by PikaMug** [comment]
Unfortunately, this isn't possible. QuestsGUI doesn't track which prompt you're in - it's merely an overlay for the standard text-based editor - and therefore wouldn't know which numerical input to submit for "Exit". The best I could do is add an option that, if you close the inventory, it can send you back to text-based until the next time you open the editor.

Let me know if that's something you'd like to see in the QuestsGUI discussion thread, where all QuestsGUI bugs/suggestions should be directed to:
https://www.spigotmc.org/threads/questsgui-paid.399346/
