### ISSUE TITLE
More slots in the GUI

### ISSUE THREAD

**Issue by Tecnok** [PikaMug/Quests#973]
Version Quests: 3.7.8
Version server: 1.13.2
Version Citizens: 2.0.24
How to replicate: create more quests than slots have the inventory of the npc gui.
How to solve: create that in the gui have multiple pages.
![quests](https://user-images.githubusercontent.com/25336008/66856622-ebf68000-ef85-11e9-85ac-dd3c14feba11.png)

**Comment by PikaMug** [comment]
As of Quests 3.8.7, the builit-in GUI is limited in size to prevent the pictured overflow. QuestsGUI 0.8 (premium) upgrades this to a paginated GUI which resolves this ticket.

@Tecnok You may reply with your Spigot username below for a free copy of QuestsGUI. Thanks!

**Comment by Tecnok** [comment]
Hello, thanks for that! The username it's XxCoolGamesxX

**Comment by PikaMug** [comment]
@Tecnok XxCoolGamesxX has been added to the Buyers list.
