### ISSUE TITLE
GUI Upgrade

### ISSUE THREAD

**Issue by DeniedINC** [PikaMug/Quests#974]
**What does your feature do?**
Allow the size of the gui quest journal to be changed. from values between 9-54
Allow the empty space to be defined so instead of it being blank I could do BLACK_STAINED_GLASS
Allow exiting the quest journal with ESC, E, etc instead of requiring hitting the exit button

**How would people use it?**
This would allow people to customize the quest journal to their server more. For me it is an amazing addition but doesn't fit the rest of my menu's so it feels out of place.

**Comment by PikaMug** [comment]
This issue tracker is for the Quests plugin only. Please direct any and all QuestsGUI bugs/suggestions to the discussion thread at:
https://www.spigotmc.org/threads/questsgui-paid.399346/
