### ISSUE TITLE
Wrong players can receive quest message responses from Citizens NPCs

### ISSUE THREAD

**Issue by twieteddy** [PikaMug/Quests#975]
Version: 3.8.0

If two players right-click on the same NPC, the second clicker will get the response text from the first clicker when they answer the chat.

Replication:
1. Player 1: Rightclick on Citizens NPC
2. Player 2: Rightclick on Citizens NPC
3. Player 1: Select a quest by using the chat

Player 2 receives the message for player 1

**Comment by PikaMug** [comment]
Thanks for the report. This will be challenging for me to test as my test environment is solo. Will update if and when I’ve made any progress.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PikaMug** [comment]
For your convenience, a build containing the fix will be available at:
https://ci.codemc.io/job/PikaMug/job/Quests/41/
