### ISSUE TITLE
Break Block Materials issue

### ISSUE THREAD

**Issue by PengBread** [PikaMug/Quests#977]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.0, paper 1.13.2

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Regarding quest [breaking block] part, i want to harvest carrots, potatoes and beetroots etc. What Material ID should I put?
I did "carrots/potatoes/beetroots". But it did not pop out on /quest to check on your progress.
![image](https://user-images.githubusercontent.com/28775590/67200974-c2cb6900-f437-11e9-8144-dc6f3b664566.png)
![image](https://user-images.githubusercontent.com/28775590/67200983-cb23a400-f437-11e9-9f73-eb202e9432b2.png)
![image](https://user-images.githubusercontent.com/28775590/67200990-d080ee80-f437-11e9-9b0f-fdbf43431b3d.png)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/asv3BpE8

**Comment by PengBread** [comment]
An Update here.
Although the counter doesn't show in /quest, but the quest still works. The counter has issues.

**Comment by PikaMug** [comment]
I believe you want “CARROTS” not “CARROT”. A full list of acceptable material names can be found here:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

Not sure what you mean about a /quest counter. Feel free to open a separate ticket.
