### ISSUE TITLE
Block Break Issue again

### ISSUE THREAD

**Issue by PengBread** [PikaMug/Quests#978]
What is your Quests version / build number (do not say "latest")?
3.8.0, paper 1.13.2

Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?
I'm using "CARROTS" Material ID. When doing /quest to check on progress, it shows nothing. It only pops out the title in chat, not the "Harvest 0/500 Carrots" but the quest works.
![image](https://user-images.githubusercontent.com/28775590/67263672-543fe700-f4db-11e9-9384-63f3ca4ae7f1.png)

This applies [POTATOES, BEETROOTS].

**Comment by PikaMug** [comment]
I misunderstood what you were trying to portray in #977 

Please give the following dev build a go:
https://ci.codemc.io/job/PikaMug/job/Quests/39/

**Comment by PengBread** [comment]
Issue seems to be solved
