### ISSUE TITLE
Feature: PlaceHolders support for Objective-display-override

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#980]
**What does your feature do?**
1:
Add support for PlaceHolders into the Objective-displays-override of the quests.
Then players can see some informations (From other plugins or anything else) Into their quests journal

2:
+A little suggestion (that is in the same way than placeholders support)
Support stage progression from quests xD Into Objective displays override.
I've searched everywhere how to include progression of the current stage into objective displays override ... can't find anything (Even with %count% etc etc)

**How would people use it?**
For the feature 1:
Player have to collect 5 plants. Because of some internal configs, the collect of thoses plants up his scoreboard to +1 (To make other plugins understand that he have collected a plant)
Then he have scoreboard "Plant": 1 , 2 , 3 ... etc etc
Into his Quest journal, he can have something like that:
```
          objective-override: |-
            §4(§c§M=§4§l Objective §4§m=§c)
            §cCollect 5 plants into the forest

            §5(§d§M=§5§l Location §d§m=§5)
            §dForest of the dark magician

            §9(§3§M=§9§l Progression §3§m=§9)
            §9%objective_score_Plant%§3/§95
```

For the feature 2 (In reality it's the exact same thing but into "PlaceholderExpansion-Quests", there isn't the placeHolder of the progression of the stage)
A quest can have a special display override, as i've written for the feature 1, and players could consult their progression with the objective-overrided.
For exemple: mining something, or reach many locations in the same stage ... But with a better displayer than the 'Basical' one.

Have a nice day! =)
Ps: 3.8.0 is exelent.

**Comment by PikaMug** [comment]
I'm having trouble understanding what you're asking for feature 2. Please open a _separate_ issue if you'd like to explain further.

For feature 1, I'm surprised that overrides aren't already supported. I'll certainly look into adding this in the future.

**Comment by tiradorus** [comment]
What i mean into the Feature 2 ... it's approximatively the same as the 1, that's why it's in the same ticket ^^'

With "Objective display override" You can't show to the player his progression on the stage.
For exemple, he have to break 15 diamond blocks,
If you don't touch anything, he have into his quest journal "0/15 diamond blocks", that change if he break something.

BUT! If you want to add an Objective displays override for this quest, the player can't see into his quest journal how many blocks he already have mined, because i don't have found anywhere how to include thoses statistics into an objective-override

**Comment by PikaMug** [comment]
Alright, I see what you mean. I'll take that into consideration when I look into this.

**Comment by PikaMug** [comment]
Both features will be available in the following dev build:
https://ci.codemc.io/job/PikaMug/job/Quests/44/
