### ISSUE TITLE
Deliver Quest Error

### ISSUE THREAD

**Issue by PengBread** [PikaMug/Quests#981]
What is your Quests version / build number (do not say "latest")?
3.8.1 [ DEV BUILD ], paper 1.13.2

Describe the problem and how to replicate it. Any console errors to post using Pastebin.com?
Accepting a deliver quest causes error.
https://pastebin.com/Fe7zqzxJ
![image](https://user-images.githubusercontent.com/28775590/67386511-afe79e80-f5c7-11e9-83aa-de9b31f0a786.png)

**Comment by PikaMug** [comment]
Related to #978

Thanks for the report. Please give the following dev build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/40/

**Comment by PengBread** [comment]
Issue seems to fixed on the dev version. Thanks
