### ISSUE TITLE
Add into the config a way to disable gui-item-displayed in the chat

### ISSUE THREAD

**Issue by tiradorus** [PikaMug/Quests#982]
**What does your feature do?**
Just add into the configuration a way to disable the Gui item that is displayed in the chat if you want to take a quest.
Player already see the quest on his screen, he don't have to be spamed on his chat too by the quest.
Even more if the gui-item displayed have a long text, it could create many spams for the player, and we should avoid that.

.+ If a player click many times on the PNJ that have the Quest with the Gui item, it could really spam hard the chat of the player.

**How would people use it?**
Configuration ===>
Gui item displayed in the chat : true/false

**Comment by PikaMug** [comment]
Would you mind sharing a screenshot of the chat text you're referring to? I'm unaware of any time a GUI item has its information displayed in chat.

**Comment by tiradorus** [comment]
Here we have =)

https://imgur.com/iTGe2ET

**Comment by PikaMug** [comment]
At first I thought you were talking about the text the player gets after accepting the quest, but it looks like there's a bug that sends text to the player for merely opening the GUI if that GUI only has one quest. Looking into a fix now.
