### ISSUE TITLE
Misspelling on wiki

### ISSUE THREAD

**Issue by TripleNothing** [PikaMug/Quests#984]
Just a note for a basic misspelled word on the wiki.
[Beginner ‐ Planner · PikaMug/Quests Wiki](https://github.com/PikaMug/Quests/wiki/Beginner-‐-Planner)
In the breakdown, the description for option 3 misspells 'Length'
"Lnegth until quest is available again"

**Comment by PikaMug** [comment]
Thanks for catching that. I've updated the page accordingly.
