### ISSUE TITLE
Reward Items loosing Cursive Font

### ISSUE THREAD

**Issue by banit** [PikaMug/Quests#987]
Quests 3.8.0
Example Quest: https://pastebin.com/kzY3aXur
Example Item: https://i.imgur.com/YiY5AJi.png

Hey, i used those items to generate a Reward with my Quests. 
I used the Load in Hand feature but it seems it doesnt take over the Cursive Attribute.
The Cursive Attribute did not make it in any of the Quests.

**Comment by PikaMug** [comment]
Thanks for your report. Did you mean “Italic” attribute? Minecraft does not have “Cursive” text.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
