### ISSUE TITLE
Reach Location Spam

### ISSUE THREAD

**Issue by ArathiaMC** [PikaMug/Quests#990]
**Quests Version 3.8.1**

This happens when creating quests where players have to reach a location. When they reach the location it spams their chat with the reached location message and fills up their chat.
https://gyazo.com/de0c51fe6198230d913f93d12d0503cd

Hope this can be solved.
Thank you.

**Comment by PikaMug** [comment]
Duplicate of #922

**Comment by PikaMug** [comment]
A build containing the solution to this issue will be available at:
https://ci.codemc.io/job/PikaMug/job/Quests/43/
