### ISSUE TITLE
Inquiry for something complicated.

### ISSUE THREAD

**Issue by MrRayhonda** [PikaMug/Quests#991]
This might be a bit complicated for this plugin but I figured I'd ask. Would it be possible to work this in with the BossLands plugin? I want to make an NPC at a guildhall in my spawn town who give you info on the bosses from that plugin. I want to make dialogue where he says where to go to kill the bosses in order starting with the first boss. Once you kill the first boss you return to the NPC for a reward and then the NPC will give you the info for the next boss. Rinse Repeat until all bosses are defeated. Would that be doable? I have npcs on my server using Citizens 2 and DTL Traders.

**Comment by MrRayhonda** [comment]
I'm trying out this plugin and am completely lost. The vid is outdated and all I want to do is pretty much the same pig kill/deliver pork quest in the tutorial vid to learn it and try it out but everything is different and I don't quite get the wiki. any tips? :D

**Comment by PikaMug** [comment]
Is this the plugin you're referring to?
https://www.spigotmc.org/resources/boss-land.68320/

For dialogue, you can put any text you like for the ask message. If you meant to ask for a custom objective for killing bosses from that plugin, it may be possible if the author provides an API. I don't see any mention of one from the plugin page and the source code doesn't appear to be available.

I would recommend contacting the author about whether an API exists. If so, the fastest way to get a module created for you is to visit [the hiring forum](https://www.spigotmc.org/forums/hiring-developers.55/) (not affiliated with Quests) and direct your developer to the following page:

https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API#objectives-api

**Comment by MrRayhonda** [comment]
Yep that's it :D oof that's a whole lotta complicated-ness. How about the other thing I posted below? I'm totally lost on even how to use this plugin and it seemed some parts weren't working like when i put an action to kill 3 pigs it didn't apply and i see no option to deliver items etc. It's completely different than what the Video shows on the page and I'm completely new to making MC stuff/servers so I'm totally lost. I found the wiki a little difficult to understand to. Any ideas or tips? I just want to replicate the pig quest from the video but add a delivery step where u go back to the npc and give it 3 pork to complete the quest. Thanks :D

**Comment by PikaMug** [comment]
@MrRayhonda Please limit inquiries to one per ticket. I’ll try to answer your question, but do open a separate ticket if you need further assistance.

With this plugin, there are two major prompts to know about: _/quests editor_ and _/quests actions_. You want to be using the first one.

Each quest can have multiple stages, which are credit using the Edit Stages option after you’ve named your new quest. Once you’ve created a stage, you may have multiple Objectives.

The “Kill mobs” objective can be used to require your players the kill monsters or animals, like pigs. The “Deliver items” objective (under the “NPC” submenu in newer versions) requires your player to deliver an item to a Citizens NPC. When adding an item to the objective, try holding a porkchop in your hand and selecting option 0.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
