### ISSUE TITLE
Null quests

### ISSUE THREAD

**Issue by Mortderas** [PikaMug/Quests#993]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
04.11 16:16:27 [Server] INFO [Quests] Krasius attempted to take quest "null" but something went wrong

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
custom4:
    name: A good deed
    npc-giver-id: 20
    ask-message: Ah, a new-comer! I am the Strider of Hidden Village, me and my team
      protect this village from mindless zombies. In change of a reward you can help
      us too. Kill 10 zombies and come back to me.
    finish-message: This is a good deed.
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 10
        '2':
          npc-ids-to-talk-to:
          - 20
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 1976
        type: DIAMOND_SWORD
      money: 150
      quest-points: 1
      exp: 100
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true

**Comment by Mortderas** [comment]
I am using the latest Luckperms, this might be a cause

**Comment by PikaMug** [comment]
Closing as OP did not follow issue instructions (must post example quest _using Pastebin.com_ or similar website like Hastebin). Feel free to reply below with the requested information to reopen your ticket.

**Comment by Mortderas** [comment]
Sorry for the late response.. I'd like to request a reopening to this ticket.
https://pastebin.com/UEXdBZ8k

**Comment by Yldales** [comment]
Hello @PikaMug,

I'm encountering the same (?) issue, using **Paper 225** (for Minecraft 1.14.4), **Quests 3.8.1-b42** and **LuckPerms 4.4.31**. 

New players (only) cannot accept quests (using "yes" in chat). When they try, they receive a generic error message, and this is displayed in the console: _[Server thread/INFO]: [Quests] Yldales attempted to take quest "null" but something went wrong_.

Using /qa reset on the new player fix the issue.

**Comment by Mortderas** [comment]
So /qa reset is a fix or just something to do in emergency?

**Comment by andrepl** [comment]
Just evaluating this plugin for the first time.  completely untouched configuration with only LuckPerms installed results in the exact behaviour described here (including `/qa reset <player>` to fix it) .   No startup errors or other messages from this plugin of any kind.

**Comment by PikaMug** [comment]
Thank you all for the feedback! I'm having trouble pinpointing the source of this bug, but am continuing to investigate. Your patience is appreciated.

**Comment by Mortderas** [comment]
Greetings all, how is it the process may I ask?

**Comment by 18PatZ** [comment]
@Mortderas do you get this issue with the default Quests config?

**Comment by Mortderas** [comment]
Hello! I’ve disabled the default quests. But they’re working now. I guess it needs an restart after making quests so the config can work

**Comment by PikaMug** [comment]
Is this still an issue on recent builds? I've been unable to replicate using Paper, with or without LuckPerms.
