### ISSUE TITLE
Proper McMMO not supported? (Can It be? :D)

### ISSUE THREAD

**Issue by MrRayhonda** [PikaMug/Quests#994]
**What does your feature do?**
allows the full official version of McMMO get support
https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/

**How would people use it?**
same as the classic McMMO support currently with the plugin.

**Comment by PikaMug** [comment]
There is no “proper” version of mcMMO. There is only the overhauled, premium version, and the classic, free version. To use Quests with the overhauled version, you need https://www.spigotmc.org/resources/mcmmo-overhaul-quests-module.69548/

**Comment by MrRayhonda** [comment]
oh oups I say it written on the classic page as "official" and mislabeled it here as proper. I'm using the premium one by the original author ^^ My mistake. So this module will work for all of them or just overhauled? Bc i have only the Official premium version and in the quest editor where it lets me use McMMO features it says "Not Installed"

**Comment by PikaMug** [comment]
The module can only be used for the premium version. Once you install the module, look under “Custom objectives”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
