### ISSUE TITLE
(NotABug) How would I make an NPC Give the player an Item upon starting a quest?

### ISSUE THREAD

**Issue by MrRayhonda** [PikaMug/Quests#995]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.1

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No error, Just trying to figure this all out.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Like in the pig quest video, I'd like the NPC to give me the weapon to kill the pigs with then allow me to keep it after the quest. I've figured it mostly all out but currently the player gets a custom "Pig Sticker" weapon as a reward instead of to aid them on the quest. It's fine for this one but for future quests I'd like to know this. Thanks for all your help so far! This is a super cool plugin I'm just not great at all this MC stuff lol

**Comment by PikaMug** [comment]
The closest way to emulate this would be to create an Action using _/quests actions_ -> (name the Action) -> Player -> Give items. After that, set it as the Initial Action for your quest in the _/quests editor_.  This will give the item to your player at the start of the quest.

**Comment by MrRayhonda** [comment]
:O THANK YOU! I'm so dumb. You rock!
