### ISSUE TITLE
NPC Quest Giving Gui Not Working

### ISSUE THREAD

**Issue by polsonator2** [PikaMug/Quests#996]
I just updated to the new version of quests and my npcs no longer open a gui to take the quest. They now do the prompt for chat acceptance. I noticed the data file is no longer used for npcs but how do I get this to work again? Is this feature no longer available? I also bought quests gui but no option there for this feature so dont know what to do.

**Comment by PikaMug** [comment]
Thanks for using Quests. I see you did not follow the issue template. Please provide the exact version number you're running, as well as an example quest from your _quests.yml_ for testing (use Pastebin.com).

**Comment by polsonator2** [comment]
Quests version: 3.8.1

Example quest:

custom20:
    name: FOOD!
    npc-giver-id: 57
    ask-message: I am starving get me some meat for these potatoes!
    finish-message: Thanks! I am stuffed now!
    gui-display: name-BOOK:amount-1
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-BEEF:amount-10
          npc-delivery-ids:
          - 57
          delivery-messages:
          - He snatches the meat from you, wolfs it down raw... (gross)
    rewards:
      items:
      - name-POTATO:amount-1
      quest-points: 1
      custom-rewards:
        req1:
          name: Class Experience Reward
          data:
            Experience: '50'
      commands:
      - mgive <player> sp 10
    planner:
      cooldown: 1800
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 4

**Comment by polsonator2** [comment]
[dQhUev82.txt](https://github.com/PikaMug/Quests/files/3821217/dQhUev82.txt)

**Comment by PikaMug** [comment]
In the future, please provide example quests using Pastebin.com (or a similar site like Hastebin).

I was able to replicate the issue and am currently investigating.

**Comment by polsonator2** [comment]
Thanks for all your help!

**Comment by PikaMug** [comment]
You're welcome. After a bit of digging, it seems this only happens when _ask-confirmation: false_ is set in the config.yml file. Since the player doesn't need to decide whether they want to take the quest, any NPC that only has one quest attached to it will just give them the quest, rather than show a GUI (since the player can't pick which quest they want either). When I set _ask-confirmation: true_ in the file, the GUI shows up as expected.

Thus, the plugin is working correctly.

**Comment by polsonator2** [comment]
I am using ask-confirmation: true in the config and it still does not work.  It is still prompting me in chat to start the quest and not opening the gui.  Not sure if it is affected by me also having questsgui installed? Also, all of my quest npcs use the same item for gui, which is a book. Would this cause an issue?

**Comment by PikaMug** [comment]
That's certainly bizarre. QuestsGUI does not currently affect the confirmaton prompt. If you would, please try the following:
1. Update to Quests version 3.8.2
2. Open the FOOD! quest in the editor, clear the GUI display, then add it back and save/reload

**Comment by polsonator2** [comment]
Downloaded and installed version 3.8.2 from the Github link and cleared the gui item and redid as book.  It now works!  I also tested another npc with for another quest without editing it and it also worked fine.  Thanks for such a fast response on this!

**Comment by polsonator2** [comment]
Hate to say it but the bug has returned.  I have not added or edited any quests and now it is back to no longer allowing the gui quest selection.  The only things I have done since are configure some other gui items for the Spigot plugin Guiplus and changed some mcmmo xp multipliers (should not effect).  I noticed this problem after I slept in a bed and day turned to night. Doubt this is an issue but you never know.

**Comment by PikaMug** [comment]
@polsonator2 Have you tested whether removing GUIPlus temporarily resolves the issue?

**Comment by polsonator2** [comment]
I finally had a chance to test, sorry this has taken so long to get back to you.  I have found it is not the GUIplus plugin. I was able to find out it only happens after a quest has already been completed and you go to take it again after the cooldown.  The first time you take a quest, the gui pops up.

**Comment by PikaMug** [comment]
Please try the following build once available:
https://ci.codemc.io/job/PikaMug/job/Quests/46/

**Comment by polsonator2** [comment]
As always, thanks for such an amazing fast response and fix! The new build seems to have resolved the issue.  I am now getting the NPC quest GUI for 1st time quests and also for quest repeats after the cooldown.
