### ISSUE TITLE
Warn in Console: Quests v3.8.1-b42 generated an exception

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#997]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.1 b42
paper 1.14

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Pastebin Error in console: https://pastebin.com/jxsgBbpU

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Not sure if this is applicable but will provide if needed.

**Comment by PikaMug** [comment]
Thanks for the report. My suspicion is that Citizens isn't installed (or didn't load properly), yet you have _npc-effects.enabled: true_ set in your config.yml file.

I'll update the plugin to check for Citizens before trying to show effects, but for now either make sure Citizens is OK or just disable the config setting.
